### ISSUE TITLE
broker can not start 

### ISSUE THREAD

**Issue by lvs071103** [apache/pulsar#10053]
zookeeper and bookkeeper  Separate deployment

```
[root@pulsar-test01 pulsar]# netstat -lntp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:3181            0.0.0.0:*               LISTEN      1385/java           
tcp        0      0 0.0.0.0:44493           0.0.0.0:*               LISTEN      1282/java           
tcp        0      0 10.1.32.76:3888         0.0.0.0:*               LISTEN      1282/java           
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1007/sshd           
tcp        0      0 0.0.0.0:4888            0.0.0.0:*               LISTEN      1282/java           
tcp        0      0 0.0.0.0:7000            0.0.0.0:*               LISTEN      1282/java           
tcp        0      0 0.0.0.0:8000            0.0.0.0:*               LISTEN      1385/java           
tcp        0      0 0.0.0.0:2181            0.0.0.0:*               LISTEN      1282/java           
tcp        0      0 0.0.0.0:40713           0.0.0.0:*               LISTEN      1385/java           
tcp6       0      0 :::9100                 :::*                    LISTEN      1008/node_exporter  
tcp6       0      0 :::22                   :::*                    LISTEN      1007/sshd 
```
zookeeper query:
```
[zk: 10.1.32.76:2181(CONNECTED) 1] ls /
[admin, bookies, ledgers, managed-ledgers, namespace, stream, zookeeper]
[zk: 10.1.32.76:2181(CONNECTED) 2] ls /ledgers
[INSTANCEID, LAYOUT, available, cookies, idgen, underreplication]
```

package:
```
apache-pulsar-2.7.1-bin.tar.gz
```

report Error:
```
[root@pulsar-test01 pulsar]# bin/pulsar broker
[AppClassLoader@18b4aac2] info AspectJ Weaver Version 1.9.2 built on Wednesday Oct 24, 2018 at 15:43:33 GMT
[AppClassLoader@18b4aac2] info register classloader sun.misc.Launcher$AppClassLoader@18b4aac2
[AppClassLoader@18b4aac2] info using configuration file:/opt/Apps/pulsar/lib/org.apache.pulsar-pulsar-zookeeper-utils-2.7.1.jar!/META-INF/aop.xml
[AppClassLoader@18b4aac2] info using configuration file:/opt/Apps/pulsar/lib/org.apache.pulsar-pulsar-zookeeper-2.7.1.jar!/META-INF/aop.xml
[AppClassLoader@18b4aac2] info register aspect org.apache.pulsar.broker.zookeeper.aspectj.ClientCnxnAspect
[AppClassLoader@18b4aac2] info register aspect org.apache.pulsar.zookeeper.FinalRequestProcessorAspect
[AppClassLoader@18b4aac2] info register aspect org.apache.pulsar.zookeeper.ZooKeeperServerAspect
01:20:01.842 [main] INFO  org.apache.pulsar.broker.PulsarService - Starting Pulsar Broker service; version: '2.7.1'
01:20:01.850 [main] INFO  org.apache.pulsar.broker.PulsarService - Git Revision 8ea4a39dc8bf6f2f23a160688bb70a80f6acfd4d
01:20:01.850 [main] INFO  org.apache.pulsar.broker.PulsarService - Built by StreamNative Bot <snbot@streamnative.io> on fv-az195-823 at 2021-03-06T03:09:42+0000
01:20:01.877 [main] INFO  org.apache.pulsar.broker.protocol.ProtocolHandlerUtils - Searching for protocol handlers in /opt/Apps/pulsar/./protocols
01:20:01.879 [main] WARN  org.apache.pulsar.broker.protocol.ProtocolHandlerUtils - Protocol handler directory not found
01:20:31.910 [main] ERROR org.apache.pulsar.broker.PulsarService - Failed to establish session with local ZK
java.io.IOException: Failed to establish session with local ZK
        at org.apache.pulsar.zookeeper.LocalZooKeeperConnectionService.start(LocalZooKeeperConnectionService.java:73) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.7.1.jar:2.7.1]
        at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:460) [org.apache.pulsar-pulsar-broker-2.7.1.jar:2.7.1]
        at org.apache.pulsar.PulsarBrokerStarter$BrokerStarter.start(PulsarBrokerStarter.java:281) [org.apache.pulsar-pulsar-broker-2.7.1.jar:2.7.1]
        at org.apache.pulsar.PulsarBrokerStarter.main(PulsarBrokerStarter.java:350) [org.apache.pulsar-pulsar-broker-2.7.1.jar:2.7.1]
Caused by: java.util.concurrent.TimeoutException
        at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771) ~[?:1.8.0_112]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915) ~[?:1.8.0_112]
        at org.apache.pulsar.zookeeper.LocalZooKeeperConnectionService.start(LocalZooKeeperConnectionService.java:67) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.7.1.jar:2.7.1]
        ... 3 more
01:20:31.922 [main] ERROR org.apache.pulsar.PulsarBrokerStarter - Failed to start pulsar service.
org.apache.pulsar.broker.PulsarServerException: java.io.IOException: Failed to establish session with local ZK
        at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:625) ~[org.apache.pulsar-pulsar-broker-2.7.1.jar:2.7.1]
        at org.apache.pulsar.PulsarBrokerStarter$BrokerStarter.start(PulsarBrokerStarter.java:281) ~[org.apache.pulsar-pulsar-broker-2.7.1.jar:2.7.1]
        at org.apache.pulsar.PulsarBrokerStarter.main(PulsarBrokerStarter.java:350) [org.apache.pulsar-pulsar-broker-2.7.1.jar:2.7.1]
Caused by: java.io.IOException: Failed to establish session with local ZK
        at org.apache.pulsar.zookeeper.LocalZooKeeperConnectionService.start(LocalZooKeeperConnectionService.java:73) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.7.1.jar:2.7.1]
        at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:460) ~[org.apache.pulsar-pulsar-broker-2.7.1.jar:2.7.1]
        ... 2 more
Caused by: java.util.concurrent.TimeoutException
        at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771) ~[?:1.8.0_112]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915) ~[?:1.8.0_112]
        at org.apache.pulsar.zookeeper.LocalZooKeeperConnectionService.start(LocalZooKeeperConnectionService.java:67) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.7.1.jar:2.7.1]
        at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:460) ~[org.apache.pulsar-pulsar-broker-2.7.1.jar:2.7.1]
        ... 2 more
```

**Comment by BewareMyPower** [comment]
It looks like your broker cannot connect to ZK. Could you use the pulsar's builtin ZK and try again? Or you can try to run the pulsar's builtin ZK shell in your broker's machine:

```bash
./bin/pulsar zookeeper-shell -server <zk-host>:<zk-port>
```

**Comment by lvs071103** [comment]
![image](https://user-images.githubusercontent.com/5029708/112792668-7f4a4500-9096-11eb-8647-163d25d94f28.png)

The test is okay

May be related to the system kernel

```bash
[root@pulsar-test01 conf]# uname -sr
Linux 5.7.4-1.el7.elrepo.x86_64
```
At present, no problems have been found on the 3.10 kernel. We will install the system as a 3.10 kernel for a test

thanks @BewareMyPower

**Comment by lvs071103** [comment]
It is indeed a problem with the system kernel
I did verification today
