### ISSUE TITLE
Flaky-test: SimpleProducerConsumerTestStreamingDispatcherTest.testRedeliveryFailOverConsumer

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#10117]
org.apache.pulsar.broker.service.persistent.SimpleProducerConsumerTestStreamingDispatcherTest is flaky. The testRedeliveryFailOverConsumer test method fails sporadically.

```
java.lang.AssertionError: expected [12] but found [11]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.pulsar.client.api.SimpleProducerConsumerTest.testRedeliveryFailOverConsumer(SimpleProducerConsumerTest.java:2411)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-03-31T14:03:07.4363111Z](https://github.com/apache/pulsar/runs/2235404251?check_suite_focus=true#step:8:604)
[example failure 2021-03-31T14:03:07.4275590Z](https://github.com/apache/pulsar/runs/2235404251?check_suite_focus=true#step:8:582)
[example failure 2021-03-30T09:35:08.4204568Z](https://github.com/apache/pulsar/runs/2224991950?check_suite_focus=true#step:8:595)
[example failure 2021-03-29T11:41:50.4073403Z](https://github.com/apache/pulsar/runs/2217711203?check_suite_focus=true#step:8:542)
[example failure 2021-03-28T14:47:42.1363257Z](https://github.com/apache/pulsar/runs/2212657793?check_suite_focus=true#step:8:542)
[example failure 2021-03-28T13:59:15.0401381Z](https://github.com/apache/pulsar/runs/2212348695?check_suite_focus=true#step:8:1414)
[example failure 2021-03-28T13:02:47.3543057Z](https://github.com/apache/pulsar/runs/2212348695?check_suite_focus=true#step:8:603)
[example failure 2021-03-27T16:26:32.6657405Z](https://github.com/apache/pulsar/runs/2208744104?check_suite_focus=true#step:8:1319)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
java.lang.AssertionError: expected [12] but found [11]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.pulsar.client.api.SimpleProducerConsumerTest.testRedeliveryFailOverConsumer(SimpleProducerConsumerTest.java:2411)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

</pre></code>
</details>

**Comment by zymap** [comment]
Happened again: https://github.com/apache/pulsar/runs/6001472983

**Comment by horizonzy** [comment]
assign to me.

**Comment by horizonzy** [comment]
Change the code as follow as trigger CI. Get useful info:

<img width="774" alt="image" src="https://user-images.githubusercontent.com/22524871/165950905-df88067e-79dc-436c-9ba0-bcf44381002a.png">


<img width="1601" alt="image" src="https://user-images.githubusercontent.com/22524871/165950438-9da20080-51d7-4e8c-a0e7-e0ab5f64faec.png">



`msg = consumer.receive(RECEIVE_TIMEOUT_SECONDS, TimeUnit.SECONDS)` return null.  I will explore continually.

**Comment by horizonzy** [comment]
There is my test 
https://github.com/horizonzy/pulsar/pull/3/files
