### ISSUE TITLE
Flaky-test: KeySharedSubscriptionTest.testOrderingWithConsumerListener

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#10151]
Flaky-test: org.apache.pulsar.client.api.KeySharedSubscriptionTest.testOrderingWithConsumerListener
Number of failures: 33

org.apache.pulsar.client.api.KeySharedSubscriptionTest is flaky. The testOrderingWithConsumerListener test method fails sporadically.

```
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertTrue(Assert.java:45)
	at org.testng.Assert.assertTrue(Assert.java:55)
	at org.apache.pulsar.client.api.KeySharedSubscriptionTest.testOrderingWithConsumerListener(KeySharedSubscriptionTest.java:937)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-04-03T07:46:40.2877044Z](https://github.com/apache/pulsar/runs/2258632460?check_suite_focus=true#step:8:922)
[example failure 2021-04-03T07:01:42.1233279Z](https://github.com/apache/pulsar/runs/2258632460?check_suite_focus=true#step:8:142)
[example failure 2021-04-02T20:39:56.6602015Z](https://github.com/apache/pulsar/runs/2256368447?check_suite_focus=true#step:8:142)
[example failure 2021-04-02T17:23:37.4992880Z](https://github.com/apache/pulsar/runs/2255318929?check_suite_focus=true#step:8:142)
[example failure 2021-04-02T16:56:31.9911720Z](https://github.com/apache/pulsar/runs/2254561747?check_suite_focus=true#step:8:1755)
[example failure 2021-04-02T16:54:25.7523957Z](https://github.com/apache/pulsar/runs/2254571277?check_suite_focus=true#step:8:1755)
[example failure 2021-04-02T16:04:13.4383599Z](https://github.com/apache/pulsar/runs/2254571277?check_suite_focus=true#step:8:975)
[example failure 2021-04-02T16:02:59.4827353Z](https://github.com/apache/pulsar/runs/2254561747?check_suite_focus=true#step:8:949)
[example failure 2021-04-02T15:15:19.9094310Z](https://github.com/apache/pulsar/runs/2254571277?check_suite_focus=true#step:8:142)
[example failure 2021-04-02T12:24:31.9116189Z](https://github.com/apache/pulsar/runs/2253612663?check_suite_focus=true#step:8:142)
[example failure 2021-04-02T12:23:25.9695513Z](https://github.com/apache/pulsar/runs/2253610089?check_suite_focus=true#step:8:142)
[example failure 2021-04-02T10:22:25.1432323Z](https://github.com/apache/pulsar/runs/2252764753?check_suite_focus=true#step:8:901)
[example failure 2021-04-02T09:35:06.9032708Z](https://github.com/apache/pulsar/runs/2252764521?check_suite_focus=true#step:8:142)
[example failure 2021-04-02T09:26:33.5239524Z](https://github.com/apache/pulsar/runs/2252755426?check_suite_focus=true#step:8:142)
[example failure 2021-04-02T05:26:41.2375002Z](https://github.com/apache/pulsar/runs/2251244220?check_suite_focus=true#step:8:1680)
[example failure 2021-04-02T04:48:07.6936481Z](https://github.com/apache/pulsar/runs/2251296363?check_suite_focus=true#step:8:924)
[example failure 2021-04-02T04:00:02.1561803Z](https://github.com/apache/pulsar/runs/2251296363?check_suite_focus=true#step:8:142)
[example failure 2021-04-02T03:44:18.5337883Z](https://github.com/apache/pulsar/runs/2251236112?check_suite_focus=true#step:8:142)
[example failure 2021-04-02T00:44:42.9113733Z](https://github.com/apache/pulsar/runs/2250236865?check_suite_focus=true#step:8:948)
[example failure 2021-04-01T23:50:14.9812852Z](https://github.com/apache/pulsar/runs/2250236865?check_suite_focus=true#step:8:142)
[example failure 2021-04-01T23:48:02.8570835Z](https://github.com/apache/pulsar/runs/2249631010?check_suite_focus=true#step:8:898)
[example failure 2021-04-01T23:45:51.0785052Z](https://github.com/apache/pulsar/runs/2249443637?check_suite_focus=true#step:8:898)
[example failure 2021-04-01T22:54:13.0167609Z](https://github.com/apache/pulsar/runs/2249613388?check_suite_focus=true#step:8:142)
[example failure 2021-04-01T22:54:00.1827949Z](https://github.com/apache/pulsar/runs/2249443637?check_suite_focus=true#step:8:142)
[example failure 2021-04-01T22:53:39.9860242Z](https://github.com/apache/pulsar/runs/2249631010?check_suite_focus=true#step:8:142)
[example failure 2021-04-01T19:42:29.9680051Z](https://github.com/apache/pulsar/runs/2247059533?check_suite_focus=true#step:8:946)
[example failure 2021-04-01T18:45:34.3536353Z](https://github.com/apache/pulsar/runs/2247059533?check_suite_focus=true#step:8:142)
[example failure 2021-04-01T17:26:20.5906803Z](https://github.com/apache/pulsar/runs/2246206809?check_suite_focus=true#step:8:935)
[example failure 2021-04-01T16:01:07.9304984Z](https://github.com/apache/pulsar/runs/2245689926?check_suite_focus=true#step:8:942)
[example failure 2021-04-01T10:14:31.2081049Z](https://github.com/apache/pulsar/runs/2244518581?check_suite_focus=true#step:8:142)
[example failure 2021-04-01T09:36:40.7896877Z](https://github.com/apache/pulsar/runs/2244414606?check_suite_focus=true#step:8:181)
[example failure 2021-04-01T06:33:40.5143025Z](https://github.com/apache/pulsar/runs/2243093236?check_suite_focus=true#step:8:997)
[example failure 2021-04-01T05:42:06.4755137Z](https://github.com/apache/pulsar/runs/2243093236?check_suite_focus=true#step:8:194)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertTrue(Assert.java:45)
	at org.testng.Assert.assertTrue(Assert.java:55)
	at org.apache.pulsar.client.api.KeySharedSubscriptionTest.testOrderingWithConsumerListener(KeySharedSubscriptionTest.java:937)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

</pre></code>
</details>

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
