### ISSUE TITLE
Flaky-test: MultiTopicsReaderTest.testReadMessageWithBatchingWithMessageInclusive / MultiTopicsReaderTest.testReadMessageWithoutBatchingWithMessageInclusive

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#10152]
Flaky-test: org.apache.pulsar.client.impl.MultiTopicsReaderTest.testReadMessageWithBatchingWithMessageInclusive
Number of failures: 5

org.apache.pulsar.client.impl.MultiTopicsReaderTest is flaky. The testReadMessageWithBatchingWithMessageInclusive test method fails sporadically.

```
java.lang.AssertionError: expected [12] but found [14]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.pulsar.client.impl.MultiTopicsReaderTest.testReadMessageWithBatchingWithMessageInclusive(MultiTopicsReaderTest.java:134)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-04-03T11:00:03.4588668Z](https://github.com/apache/pulsar/runs/2259311127?check_suite_focus=true#step:8:312)
[example failure 2021-04-02T07:18:17.4939764Z](https://github.com/apache/pulsar/runs/2252064758?check_suite_focus=true#step:8:312)
[example failure 2021-04-02T00:06:33.5317876Z](https://github.com/apache/pulsar/runs/2250236865?check_suite_focus=true#step:8:312)
[example failure 2021-04-01T23:06:24.2523567Z](https://github.com/apache/pulsar/runs/2249613388?check_suite_focus=true#step:8:312)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
java.lang.AssertionError: expected [12] but found [14]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.pulsar.client.impl.MultiTopicsReaderTest.testReadMessageWithBatchingWithMessageInclusive(MultiTopicsReaderTest.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

</pre></code>
</details>

```
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertTrue(Assert.java:45)
	at org.testng.Assert.assertTrue(Assert.java:55)
	at org.apache.pulsar.client.impl.MultiTopicsReaderTest.testReadMessageWithBatchingWithMessageInclusive(MultiTopicsReaderTest.java:131)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-04-03T07:12:14.7090723Z](https://github.com/apache/pulsar/runs/2258632460?check_suite_focus=true#step:8:312)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertTrue(Assert.java:45)
	at org.testng.Assert.assertTrue(Assert.java:55)
	at org.apache.pulsar.client.impl.MultiTopicsReaderTest.testReadMessageWithBatchingWithMessageInclusive(MultiTopicsReaderTest.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

</pre></code>
</details>

---
        
Flaky-test: org.apache.pulsar.client.impl.MultiTopicsReaderTest.testReadMessageWithoutBatchingWithMessageInclusive
Number of failures: 6

org.apache.pulsar.client.impl.MultiTopicsReaderTest is flaky. The testReadMessageWithoutBatchingWithMessageInclusive test method fails sporadically.

```
java.lang.AssertionError: expected [3] but found [1]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.pulsar.client.impl.MultiTopicsReaderTest.testReadMessageWithoutBatchingWithMessageInclusive(MultiTopicsReaderTest.java:108)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-04-03T11:00:03.4651637Z](https://github.com/apache/pulsar/runs/2259311127?check_suite_focus=true#step:8:334)
[example failure 2021-04-02T08:11:57.2109886Z](https://github.com/apache/pulsar/runs/2252036527?check_suite_focus=true#step:8:1049)
[example failure 2021-04-02T08:09:21.9227516Z](https://github.com/apache/pulsar/runs/2252064758?check_suite_focus=true#step:8:1093)
[example failure 2021-04-01T23:57:40.8247742Z](https://github.com/apache/pulsar/runs/2249443637?check_suite_focus=true#step:8:1088)
[example failure 2021-04-01T06:34:23.0257315Z](https://github.com/apache/pulsar/runs/2243093236?check_suite_focus=true#step:8:1031)
[example failure 2021-03-31T21:14:08.3843483Z](https://github.com/apache/pulsar/runs/2240185745?check_suite_focus=true#step:8:989)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
java.lang.AssertionError: expected [3] but found [1]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.pulsar.client.impl.MultiTopicsReaderTest.testReadMessageWithoutBatchingWithMessageInclusive(MultiTopicsReaderTest.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

</pre></code>
</details>

**Comment by 315157973** [comment]
I am trying to fix it, which is caused by 2 issues.
