### ISSUE TITLE
[Python functions] Unable to run tests locally: No module named '_pulsar'

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#10155]
In an attempt to run the Python Function tests, I ran the script https://github.com/apache/pulsar/blob/master/pulsar-functions/instance/src/scripts/run_python_instance_tests.sh

That blew up with this exception:

> ======================================================================
> ERROR: test_secretsprovider (unittest.loader._FailedTest)
> ----------------------------------------------------------------------
> ImportError: Failed to import test module: test_secretsprovider
> Traceback (most recent call last):
>   File "/Users/dbost/anaconda3/lib/python3.7/unittest/loader.py", line 434, in _find_test_path
>     module = self._get_module_from_name(name)
>   File "/Users/dbost/anaconda3/lib/python3.7/unittest/loader.py", line 375, in _get_module_from_name
>     __import__(name)
>   File "/Users/dbost/src/apache-pulsar/pulsar/pulsar-functions/instance/target/python-instance/tests/test_secretsprovider.py", line 26, in <module>
>     import log
>   File "/Users/dbost/src/apache-pulsar/pulsar/pulsar-functions/instance/target/python-instance/log.py", line 29, in <module>
>     import pulsar
>   File "/Users/dbost/src/apache-pulsar/pulsar/pulsar-functions/instance/target/python-instance/pulsar/__init__.py", line 102, in <module>
>     import _pulsar
> ModuleNotFoundError: No module named '_pulsar'

Sure enough, log.py has the line `pulsar._pulsar.CompressionType.LZ4` (https://github.com/apache/pulsar/blob/master/pulsar-functions/instance/src/main/python/log.py#L51). 
However, in `python_instance.py`, that same enum value is referenced simply as `pulsar.CompressionType.LZ4` (https://github.com/apache/pulsar/blob/master/pulsar-functions/instance/src/main/python/python_instance.py#L325). 

How do I run these tests locally?

**Comment by devinbost** [comment]
Usually, for things like this, I'd also expect there to be a requirements.txt file that contains the versions of all the Python dependencies. That would enable the dependencies to be installed into a conda env or virtual env to prevent dependency conflicts with other packages.

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
