### ISSUE TITLE
NPE in pulsar-admin topics partitioned-stats

### ISSUE THREAD

**Issue by dlg99** [apache/pulsar#10176]
**To Reproduce**

```
$ bin/pulsar-admin topics create-partitioned-topic  partitioned-topic  --partitions 4
```
succeeds

```
$ bin/pulsar-admin topics partitioned-stats persistent-topic --per-partition

java.lang.NullPointerException
	at org.apache.pulsar.admin.cli.CmdTopics$GetPartitionedStats.run(CmdTopics.java:612)
	at org.apache.pulsar.admin.cli.CmdBase.run(CmdBase.java:86)
	at org.apache.pulsar.admin.cli.PulsarAdminTool.run(PulsarAdminTool.java:281)
	at org.apache.pulsar.admin.cli.PulsarAdminTool.main(PulsarAdminTool.java:328)
	
$ bin/pulsar-admin topics partitioned-stats persistent://public/default/persistent-topic --per-partition 

java.lang.NullPointerException
	at org.apache.pulsar.admin.cli.CmdTopics$GetPartitionedStats.run(CmdTopics.java:612)
	at org.apache.pulsar.admin.cli.CmdBase.run(CmdBase.java:86)
	at org.apache.pulsar.admin.cli.PulsarAdminTool.run(PulsarAdminTool.java:281)
	at org.apache.pulsar.admin.cli.PulsarAdminTool.main(PulsarAdminTool.java:328)	
```

**Expected behavior**

Stats or human-friendly error

**Additional context**
tried with pulsar standalone

**Comment by linlinnn** [comment]
I cannot reproduce this issue in version 2.7.1

**Comment by dlg99** [comment]
@linlinnn I got that with 2.8 snapshot
