### ISSUE TITLE
Error writing broker data on ZooKeeper

### ISSUE THREAD

**Issue by bilahepan** [apache/pulsar#10227]
**Describe the bug**
The cluster runs normally, with occasional error reports.
Pulsar version 2.5.1

**Exception details**
[pulsar-load-manager-3-1] WARN  org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerImpl - Error writing broker data on ZooKeeper: {}
com.fasterxml.jackson.databind.JsonMappingException: (was java.util.ConcurrentModificationException) (through reference chain: org.apache.pulsar.policies.data.loadbalancer.LocalBrokerData["lastStats"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394) ~[com.fasterxml.jackson.core-jackson-databind-2.10.1.jar:2.10.1]
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353) ~[com.fasterxml.jackson.core-jackson-databind-2.10.1.jar:2.10.1]
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316) ~[com.fasterxml.jackson.core-jackson-databind-2.10.1.jar:2.10.1]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:730) ~[com.fasterxml.jackson.core-jackson-databind-2.10.1.jar:2.10.1]
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166) ~[com.fasterxml.jackson.core-jackson-databind-2.10.1.jar:2.10.1]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480) ~[com.fasterxml.jackson.core-jackson-databind-2.10.1.jar:2.10.1]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319) ~[com.fasterxml.jackson.core-jackson-databind-2.10.1.jar:2.10.1]
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:4094) ~[com.fasterxml.jackson.core-jackson-databind-2.10.1.jar:2.10.1]
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3428) ~[com.fasterxml.jackson.core-jackson-databind-2.10.1.jar:2.10.1]
	at org.apache.pulsar.policies.data.loadbalancer.JSONWritable.getJsonBytes(JSONWritable.java:38) ~[org.apache.pulsar-pulsar-common-2.5.1.jar:2.5.1]
	at org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerImpl.writeBrokerDataOnZooKeeper(ModularLoadManagerImpl.java:873) [org.apache.pulsar-pulsar-broker-2.5.1.jar:2.5.1]
	at org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerWrapper.writeLoadReportOnZookeeper(ModularLoadManagerWrapper.java:120) [org.apache.pulsar-pulsar-broker-2.5.1.jar:2.5.1]
	at org.apache.pulsar.broker.loadbalance.LoadReportUpdaterTask.run(LoadReportUpdaterTask.java:41) [org.apache.pulsar-pulsar-broker-2.5.1.jar:2.5.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_272]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_272]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_272]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_272]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_272]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_272]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.45.Final.jar:4.1.45.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_272]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1479) ~[?:1.8.0_272]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1477) ~[?:1.8.0_272]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:744) ~[com.fasterxml.jackson.core-jackson-databind-2.10.1.jar:2.10.1]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:639) ~[com.fasterxml.jackson.core-jackson-databind-2.10.1.jar:2.10.1]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33) ~[com.fasterxml.jackson.core-jackson-databind-2.10.1.jar:2.10.1]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727) ~[com.fasterxml.jackson.core-jackson-databind-2.10.1.jar:2.10.1]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722) ~[com.fasterxml.jackson.core-jackson-databind-2.10.1.jar:2.10.1]
	... 17 more

**Comment by codelipenghui** [comment]
@bilahepan This issue is fixed by https://github.com/apache/pulsar/pull/7729, you can upgrade to 2.7.0 to try out.

**Comment by codelipenghui** [comment]
I will close this issue now, feel free to reopen it if necessary.
