### ISSUE TITLE
Broker NullPointerException seen in 2.7.1 logs for Commands#skipMessageMetadata about handleTxnAbortMarker

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#10258]
**Describe the bug**
I am seeing this error in broker logs, 2.7.1

```
21:41:10.575 [pulsar-ordered-OrderedExecutor-5-40] ERROR org.apache.zookeeper.server.NIOServerCnxnFactory - Thread Thread[pulsar-ordered-OrderedExecutor-5-40,5,main] died
java.lang.NullPointerException: null
	at org.apache.pulsar.common.protocol.Commands.hasChecksum(Commands.java:499) ~[org.apache.pulsar-pulsar-common-2.7.1.jar:2.7.1]
	at org.apache.pulsar.common.protocol.Commands.skipChecksumIfPresent(Commands.java:513) ~[org.apache.pulsar-pulsar-common-2.7.1.jar:2.7.1]
	at org.apache.pulsar.common.protocol.Commands.skipMessageMetadata(Commands.java:542) ~[org.apache.pulsar-pulsar-common-2.7.1.jar:2.7.1]
	at org.apache.pulsar.broker.service.AbstractBaseDispatcher.lambda$handleTxnAbortMarker$0(AbstractBaseDispatcher.java:223) ~[org.apache.pulsar-pulsar-broker-2.7.1.jar:2.7.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_282]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty-netty-common-4.1.51.Final.jar:4.1.51.Final]
```

**To Reproduce**
I still do not have a reproducer, probably it is about transaction rollback

**Expected behavior**
No error in logs

** Environment **

Using Apache Pulsar 2.7.1 docker image

**Comment by eolivelli** [comment]
I have never seen this error in current master logs.

In 2.7 transactions are a "Developer preview", so I am not sure it is worth a fix

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
