### ISSUE TITLE
[Performance] Accelerate Jetty HTTPS performance by configuring Jetty to use Conscrypt / OpenSSL provider, also fixes mutual TLS auth on JDK11

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#10372]
**Is your enhancement request related to a problem? Please describe.**

Quote from https://webtide.com/conscrypting-native-ssl-for-jetty/

> By default, Jetty uses the JSSE provider from the JVM for SSL, which has three significant problems:
> 
> * It’s slow!
> * It doesn’t support ALPN in Java 8, which is needed for HTTP/2
> * It’s REALLY slow!
> 

**Describe the solution you'd like**

Enable Conscrypt for Jetty in the Broker and in the Proxy. 

The Jetty documentation describes a way [to enable Conscrypt for Jetty](https://www.eclipse.org/jetty/documentation/jetty-9/index.html#conscrypt):

```
...
Security.addProvider(new OpenSSLProvider());
...
SslContextFactory.Server sslContextFactory = new SslContextFactory.Server();
...
sslContextFactory.setProvider("Conscrypt");
...
```

**Additional context**

It seems that TLS handshake is partially broken in Java 11 when using TLS mutual authentication unless Conscrypt is configured as a Security Provider. An unknown certificate won't be detected on Jetty server side and Jetty doesn't properly return 401 in that case. This leads to an exception like this on the client side:
```
javax.net.ssl.SSLException: error:10000416:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.shutdownWithError(ReferenceCountedOpenSslEngine.java:1066) ~[netty-handler-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.sslReadErrorResult(ReferenceCountedOpenSslEngine.java:1359) ~[netty-handler-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1308) ~[netty-handler-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1384) ~[netty-handler-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1427) ~[netty-handler-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:208) ~[netty-handler-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1358) ~[netty-handler-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1253) ~[netty-handler-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1300) ~[netty-handler-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508) ~[netty-codec-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447) ~[netty-codec-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
```

This happens in `BrokerServiceTest#testTlsAuthDisallowInsecure` and `SuperUserAuthedAdminProxyHandlerTest#testAuthWithRandoCert` tests when running on JDK11.

**Comment by lhotari** [comment]
It seems that switching to use Conscrypt would require more changes than just enabling the Security provider. Quite a few tests (for example org.apache.pulsar.client.api.AuthenticatedProducerConsumerTest) fail  with this type of exception:

```
java.lang.IllegalArgumentException: Private key must be accompanied by certificate chain
  	at java.base/java.security.KeyStore.setKeyEntry(KeyStore.java:1170)
  	at org.apache.pulsar.common.util.KeyStoreHolder.setPrivateKey(KeyStoreHolder.java:60)
  	at org.apache.pulsar.common.util.SecurityUtility.setupKeyManager(SecurityUtility.java:259)
  	at org.apache.pulsar.common.util.SecurityUtility.createSslContext(SecurityUtility.java:247)
  	at org.apache.pulsar.common.util.SecurityUtility.createSslContext(SecurityUtility.java:152)
  	at org.apache.pulsar.common.util.DefaultSslContextBuilder.update(DefaultSslContextBuilder.java:48)
  	at org.apache.pulsar.common.util.DefaultSslContextBuilder.update(DefaultSslContextBuilder.java:27)
  	at org.apache.pulsar.common.util.SslContextAutoRefreshBuilder.get(SslContextAutoRefreshBuilder.java:79)
  	at org.apache.pulsar.common.util.SecurityUtility$SslContextFactoryWithAutoRefresh.getSslContext(SecurityUtility.java:452)
  	at org.eclipse.jetty.util.ssl.SslContextFactory.newSSLEngine(SslContextFactory.java:1897)
  	at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:99)
  	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
  	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
  	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
  	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:321)
  	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
  	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234)
  	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
  	at org.eclipse.jetty.server.Server.doStart(Server.java:401)
  	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
  	at org.apache.pulsar.broker.web.WebService.start(WebService.java:238)
  	... 40 more
```
