### ISSUE TITLE
Struct schema(AvroSchema/JSONSchema) cannot decode without default constructor.

### ISSUE THREAD

**Issue by linlinnn** [apache/pulsar#10393]
Related #10377

**Is your enhancement request related to a problem? Please describe.**
Struct schema(AvroSchema/JSONSchema) cannot decode without default constructor.

**Reproduce code**
```
@Data
@AllArgsConstructor
public static class Payload {
    String message;
}

public static void main(String[] args) {
    AvroSchema<Payload> schema = AvroSchema.of(Payload.class);
    Payload payload = new Payload("test");
    byte[] encode = schema.encode(payload);
    schema.decode(encode);
}
```

**AvroSchema Exception stack**
```
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NoSuchMethodException: org.apache.pulsar.client.impl.schema.JSONSchema$Payload.<init>()
	at org.apache.avro.specific.SpecificData.newInstance(SpecificData.java:466)
	at org.apache.avro.specific.SpecificData.newRecord(SpecificData.java:484)
	at org.apache.avro.reflect.ReflectData.newRecord(ReflectData.java:1038)
	at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:236)
	at org.apache.avro.specific.SpecificDatumReader.readRecord(SpecificDatumReader.java:123)
	at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:179)
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:160)
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:153)
	at org.apache.pulsar.client.impl.schema.reader.AvroReader.read(AvroReader.java:75)
	at org.apache.pulsar.client.api.schema.SchemaReader.read(SchemaReader.java:39)
	at org.apache.pulsar.client.impl.schema.reader.AbstractMultiVersionReader.read(AbstractMultiVersionReader.java:62)
	at org.apache.pulsar.client.api.schema.SchemaReader.read(SchemaReader.java:39)
	at org.apache.pulsar.client.impl.schema.AbstractStructSchema.decode(AbstractStructSchema.java:55)
	at org.apache.pulsar.client.impl.schema.JSONSchema.main(JSONSchema.java:75)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: org.apache.pulsar.client.impl.schema.JSONSchema$Payload.<init>()
	at org.apache.avro.specific.SpecificData$1.computeValue(SpecificData.java:67)
	at org.apache.avro.specific.SpecificData$1.computeValue(SpecificData.java:58)
	at java.lang.ClassValue.getFromHashMap(ClassValue.java:227)
	at java.lang.ClassValue.getFromBackup(ClassValue.java:209)
	at java.lang.ClassValue.get(ClassValue.java:115)
	at org.apache.avro.specific.SpecificData.newInstance(SpecificData.java:463)
	... 13 more
Caused by: java.lang.NoSuchMethodException: org.apache.pulsar.client.impl.schema.JSONSchema$Payload.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.apache.avro.specific.SpecificData$1.computeValue(SpecificData.java:63)
	... 18 more
```

**JSONSchema Exception stack**
```
Exception in thread "main" org.apache.pulsar.client.api.SchemaSerializationException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `org.apache.pulsar.client.impl.schema.JSONSchema$Payload` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (byte[])"{"message":"test"}"; line: 1, column: 2]
	at org.apache.pulsar.client.impl.schema.reader.JacksonJsonReader.read(JacksonJsonReader.java:49)
	at org.apache.pulsar.client.api.schema.SchemaReader.read(SchemaReader.java:39)
	at org.apache.pulsar.client.impl.schema.AbstractStructSchema.decode(AbstractStructSchema.java:55)
	at org.apache.pulsar.client.impl.schema.JSONSchema.main(JSONSchema.java:75)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `org.apache.pulsar.client.impl.schema.JSONSchema$Payload` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (byte[])"{"message":"test"}"; line: 1, column: 2]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1455)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1081)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1332)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3504)
	at org.apache.pulsar.client.impl.schema.reader.JacksonJsonReader.read(JacksonJsonReader.java:47)
	... 3 more
```

**Comment by linlinnn** [comment]
@eolivelli Please take a look

**Comment by eolivelli** [comment]
I am not sure we can do something here.
We should open a ticket in Avro and in Jackson Mapper libraries.

If we add too much 'magic' we could introduce some new behaviour that diverges from the downstream libraries and it will be very hard to maintain.
In java parameters are set by position and not by name so there is no way we can decide which constructor to use and the order of parameters.

We could say we will support Java Records, but that's another story and also it should be handled by the deserialization library as well

**Comment by linlinnn** [comment]
@eolivelli 
I agree with you, so maybe we should hint user to add default construct when using struct schema, otherwise they will be confused about send message sucessfully but receive message cannot decode.
