### ISSUE TITLE
How to use python-client to connect to a pulsar cluster

### ISSUE THREAD

**Issue by MySabers** [apache/pulsar#10399]
How to use python-client to connect to a pulsar cluster ?
```python
import pulsar

client = pulsar.Client('pulsar://localhost:6650')
```
I didn't find a way to connect to the cluster.

**Comment by linlinnn** [comment]
```python
import pulsar

client = pulsar.Client('pulsar://localhost:6550,localhost:6651,localhost:6652')
```

**Comment by MySabers** [comment]
OK, Thank you very much.

**Comment by MySabers** [comment]
Successfully connected to cluster.
```python
import pulsar
import time
client = pulsar.Client('pulsar://10.255.174.52:6650,10.255.174.53:6650,10.255.174.54:6650')
producer = client.create_producer('ct')
```

However, when we tried to turn off one of the broker(10.255.174.52:6650), the following exception occurred:
```python
2021-04-27 17:22:40.946 INFO  [0x11006fe00] ConnectionPool:85 | Created connection for pulsar://10.255.174.52:6650,10.255.174.53:6650,10.255.174.54:6650
2021-04-27 17:22:40.948 ERROR [0x70000d0c5000] ClientConnection:385 | [<none> -> pulsar://10.255.174.52:6650,10.255.174.53:6650,10.255.174.54:6650] Failed to establish connection: Connection refused
2021-04-27 17:22:40.948 INFO  [0x70000d0c5000] ClientConnection:1372 | [<none> -> pulsar://10.255.174.52:6650,10.255.174.53:6650,10.255.174.54:6650] Connection closed
2021-04-27 17:22:40.948 ERROR [0x70000d0c5000] ClientImpl:181 | Error Checking/Getting Partition Metadata while creating producer on persistent://public/default/ct -- ConnectError
2021-04-27 17:22:40.948 INFO  [0x70000d0c5000] ClientConnection:235 | [<none> -> pulsar://10.255.174.52:6650,10.255.174.53:6650,10.255.174.54:6650] Destroyed connection
Traceback (most recent call last):
  File "/Users/hansi/PycharmProjects/test/pulsar_test.py", line 6, in <module>
    producer = client.create_producer('ct')
  File "/usr/local/lib/python3.8/site-packages/pulsar/__init__.py", line 525, in create_producer
    p._producer = self._client.create_producer(topic, conf)
Exception: Pulsar error: ConnectError

Process finished with exit code 1
```
is there anything we didn't notice?

**Comment by BewareMyPower** [comment]
Python client is based on C++ client. Currently C++ client doesn't support multiple URLs, so you can't use `pulsar://ip1:port1,ip2:port2`.

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closed as answered.

The development of the Python client has been permanently moved to https://github.com/apache/pulsar-client-python. If it's still relevant, please open an issue there.
