### ISSUE TITLE
Local runner: Invalid signature file digest for Manifest main attributes

### ISSUE THREAD

**Issue by YannPerthuis** [apache/pulsar#10419]
**Describe the bug**
Hi, I'm currently working with the pulsar functions local runner and I got this following error when I run my application. It throws when I instantiate the FunctionConfig class like the [example](https://pulsar.apache.org/docs/en/functions-debug/#debug-with-localrun-mode) in the doc.

Error:

```java
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
        at java.base/sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:336)
        at java.base/sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:269)
        at java.base/java.util.jar.JarVerifier.processEntry(JarVerifier.java:316)
        at java.base/java.util.jar.JarVerifier.update(JarVerifier.java:230)
        at java.base/java.util.jar.JarFile.initializeVerifier(JarFile.java:757)
        at java.base/java.util.jar.JarFile.ensureInitialization(JarFile.java:1034)
        at java.base/java.util.jar.JavaUtilJarAccessImpl.ensureInitialization(JavaUtilJarAccessImpl.java:69)
        at java.base/jdk.internal.loader.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:870)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:786)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at PulsarFunctionLocalRunner.main(PulsarFunctionLocalRunner.java:17)
```

**To Reproduce**
1. Create gradle project
2. Add following dependencies to your build.gradle :
```groovy
dependencies { 
    implementation group: 'org.apache.pulsar', name: 'pulsar-functions-api', version: '2.7.1'
    implementation group: 'org.apache.pulsar', name: 'pulsar-functions-local-runner', version: '2.7.1'
}
```
3. Copy paste the ExclamationFunction class from the [Debug with localrun mode example](https://pulsar.apache.org/docs/en/functions-debug/#debug-with-localrun-mode)
4. Run the main method

**Expected behavior**
Be able to run the function on the local runner without getting this problem.

**Desktop:**
 - OS: macOs v11.2.3
 - Gradle: v7.0
 - Java: v8
 - Pulsar: v2.7.1

_Originally posted by @YannPerthuis in https://github.com/apache/pulsar/issues/8539#issuecomment-828270908_

**Comment by marksilcox** [comment]
I am seeing this same issue on version 2.9.1 of the local runner, but works on 2.6.4

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.
