### ISSUE TITLE
WebSocketHttpServletRequestWrapperTest is failing consistently on branch.2-7

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#10452]
This test is failing consistently on branch-2.7

```
org.apache.pulsar.broker.PulsarServerException: java.io.IOException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Invalid path string "//127.0.0.1:2181" caused by empty node name specified @1
	at org.apache.pulsar.websocket.WebSocketService.start(WebSocketService.java:111)
	at org.apache.pulsar.websocket.WebSocketHttpServletRequestWrapperTest.mockRequestTest(WebSocketHttpServletRequestWrapperTest.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Invalid path string "//127.0.0.1:2181" caused by empty node name specified @1
	at org.apache.pulsar.zookeeper.GlobalZooKeeperCache.start(GlobalZooKeeperCache.java:75)
	at org.apache.pulsar.websocket.WebSocketService.start(WebSocketService.java:109)
	... 13 more
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Invalid path string "//127.0.0.1:2181" caused by empty node name specified @1
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
	at org.apache.pulsar.zookeeper.GlobalZooKeeperCache.start(GlobalZooKeeperCache.java:68)
	... 14 more
Caused by: java.lang.IllegalArgumentException: Invalid path string "//127.0.0.1:2181" caused by empty node name specified @1
	at org.apache.zookeeper.common.PathUtils.validatePath(PathUtils.java:99)
	at org.apache.zookeeper.client.ConnectStringParser.<init>(ConnectStringParser.java:60)
	at org.apache.zookeeper.ZooKeeper.createDefaultHostProvider(ZooKeeper.java:1311)
	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:951)
	at org.apache.pulsar.zookeeper.ZookeeperClientFactoryImpl.create(ZookeeperClientFactoryImpl.java:46)
	at org.apache.pulsar.zookeeper.GlobalZooKeeperCache.start(GlobalZooKeeperCache.java:63)
	... 14 more
```

**Comment by eolivelli** [comment]
I saw this problem on CI and on a ubuntu machine

**Comment by eolivelli** [comment]
The problem is that in branch-2.7 we do not have "memory://xxxx" metadata store.
I am trying to workaround it, probably we will need to start a real ZK service
