### ISSUE TITLE
Allow Java client to create consumer with receiverQueueSize(0) when receiving with timeout

### ISSUE THREAD

**Issue by bry00** [apache/pulsar#10479]
Currently, consumer with `receiverQueueSize == 0` cannot be user when using `receive` with timeout (see sample code below).

## Suggested solution
Remove this constraint (i.e. allow `receiverQueueSize == 0` when using `receive` with timeout) to facilitate usage cases of shared subscriptions with long term processing of the message.

## Sample code 
```java
package sample;

import org.apache.pulsar.client.api.*;
import java.util.concurrent.TimeUnit;

public class App {
    public static void main(String[] args) {

        try (PulsarClient client = PulsarClient.builder().serviceUrl("pulsar://localhost:6650").build()) {
            try (Consumer consumer = client.newConsumer().topic("sample").subscriptionName("try")
                    .subscriptionType(SubscriptionType.Shared)
                    .subscriptionInitialPosition(SubscriptionInitialPosition.Earliest)
                    .receiverQueueSize(0)
                    .subscribe()) {
                Message msg;
                while ((msg = consumer.receive(10, TimeUnit.SECONDS)) != null) {
                    var data = msg.getValue();
                    System.out.println("Received: " + data.toString());
                    consumer.acknowledge(msg);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

## Error message

```log
org.apache.pulsar.client.api.PulsarClientException$InvalidConfigurationException: Can't use receive with timeout, if the queue size is 0
        at org.apache.pulsar.client.impl.ConsumerBase.receive(ConsumerBase.java:175)
        at sample.App.main(App.java:16)
```

**Comment by eolivelli** [comment]
I have also faced this problem.

**Comment by merlimat** [comment]
The question is: what to do with the message if it comes after the 10 seconds timeout. Using `receiveQueueSize=0` means to  disable the pre-fetching of messages (so that messages don't sit in a queue when there's another consumer available). If we leave the message in the queue after the timeout, it kind of defeats the whole purpose.

**Comment by eolivelli** [comment]
when can implement some dummy loop that pools for a message for the given time, every X ms we call "receive"...

the user can do it by himself, but providing it out-of-the-box may be a good idea in order to provide user (developer) experience

**Comment by complone** [comment]
Can you provide a version of Plusar? I hope to follow up and reproduce this problem

**Comment by bry00** [comment]
2.7.1

**Comment by complone** [comment]
> 2.7.1

Ok i will follow up the problem

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.
