### ISSUE TITLE
pulsar-io-hdfs connect hdfs error

### ISSUE THREAD

**Issue by Hanfee** [apache/pulsar#10514]
```
maxBufferedTuples=1024, functionAuthenticationSpec=null, port=45090, clusterName=local, maxPendingAsyncRequests=1000)

18:08:16.876 [main] INFO  org.apache.pulsar.functions.LocalRunner - RuntimeSpawner quit because of
java.nio.channels.UnresolvedAddressException: null
	at sun.nio.ch.Net.checkAddress(Net.java:101) ~[?:1.8.0_221]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622) ~[?:1.8.0_221]
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:192) ~[?:?]
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:531) ~[?:?]
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:495) ~[?:?]
	at org.apache.pulsar.io.hdfs2.AbstractHdfsConnector.checkHdfsUriForTimeout(AbstractHdfsConnector.java:144) ~[?:?]
	at org.apache.pulsar.io.hdfs2.AbstractHdfsConnector.resetHDFSResources(AbstractHdfsConnector.java:74) ~[?:?]
	at org.apache.pulsar.io.hdfs2.sink.HdfsAbstractSink.connectToHdfs(HdfsAbstractSink.java:83) ~[?:?]
	at org.apache.pulsar.io.hdfs2.sink.HdfsAbstractSink.open(HdfsAbstractSink.java:67) ~[?:?]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.setupOutput(JavaInstanceRunnable.java:784) ~[org.apache.pulsar-pulsar-functions-instance-2.7.1.jar:2.7.1]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.setup(JavaInstanceRunnable.java:212) ~[org.apache.pulsar-pulsar-functions-instance-2.7.1.jar:2.7.1]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:234) ~[org.apache.pulsar-pulsar-functions-instance-2.7.1.jar:2.7.1]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_221]
^C18:08:45.149 [Thread-1] INFO  org.apache.pulsar.functions.LocalRunner - Shutting down the localrun runtimeSpawner ...

```

**Comment by Hanfee** [comment]
I execute a cmd :
`./bin/pulsar-admin sinks localrun \
--archive ./connectors/pulsar-io-hdfs2-2.7.1.nar \
--classname org.apache.pulsar.io.hdfs2.sink.text.HdfsStringSink \
--name hdfs2 \
--tenant public \
--namespace safe \
--inputs persistent://public/safe/my-topic \
--sink-config-file ./usr/conf/hdfsSinkConfig.yaml \
--parallelism 1`

hdfsSinkConfig.yaml 
`configs:
    hdfsConfigResources: "/home/hdp-safe-heimdallr/pulsar/apache-pulsar-2.7.1/usr/conf/core-site.xml,/home/hdp-safe-heimdallr/pulsar/apache-pulsar-2.7.1/usr/conf/hdfs-site.xml"
    directory: "hdfs:///home/test/pulsar"
    filenamePrefix: "prefix"
    fileExtension: ".log"
    compression: "SNAPPY"
    subdirectoryPattern: "yyyy-MM-dd"`

**Comment by Hanfee** [comment]
I replace core-site.xml and hdfs-site.xml resolve this problem, but I find a new problem 
hdfs2 connectors/pulsar-io-hdfs2-2.7.1.nar  lack  hadoop-lzo-0.4.21U2.jar 
```
  16:26:16.839 [main] INFO  org.apache.pulsar.functions.LocalRunner - RuntimeSpawner quit because of
java.lang.IllegalArgumentException: Compression codec com.hadoop.compression.lzo.LzoCodec not found.
	at org.apache.hadoop.io.compress.CompressionCodecFactory.getCodecClasses(CompressionCodecFactory.java:139) ~[?:?]
	at org.apache.hadoop.io.compress.CompressionCodecFactory.<init>(CompressionCodecFactory.java:179) ~[?:?]
	at org.apache.pulsar.io.hdfs2.AbstractHdfsConnector.getCompressionCodecFactory(AbstractHdfsConnector.java:202) ~[?:?]
	at org.apache.pulsar.io.hdfs2.AbstractHdfsConnector.getCompressionCodec(AbstractHdfsConnector.java:194) ~[?:?]
	at org.apache.pulsar.io.hdfs2.sink.text.HdfsAbstractTextFileSink.openHdfsStream(HdfsAbstractTextFileSink.java:74) ~[?:?]
	at org.apache.pulsar.io.hdfs2.sink.text.HdfsAbstractTextFileSink.createWriter(HdfsAbstractTextFileSink.java:47) ~[?:?]
	at org.apache.pulsar.io.hdfs2.sink.HdfsAbstractSink.open(HdfsAbstractSink.java:68) ~[?:?]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.setupOutput(JavaInstanceRunnable.java:784) ~[org.apache.pulsar-pulsar-functions-instance-2.7.1.jar:2.7.1]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.setup(JavaInstanceRunnable.java:212) ~[org.apache.pulsar-pulsar-functions-instance-2.7.1.jar:2.7.1]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:234) ~[org.apache.pulsar-pulsar-functions-instance-2.7.1.jar:2.7.1]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_152]
Caused by: java.lang.ClassNotFoundException: Class com.hadoop.compression.lzo.LzoCodec not found
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2273) ~[?:?]
	at org.apache.hadoop.io.compress.CompressionCodecFactory.getCodecClasses(CompressionCodecFactory.java:132) ~[?:?]
	... 10 more
```

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
@Hanfee Is it still relevant to the latest version? If so, it seems we can add the dependency properly.
