### ISSUE TITLE
Relative paths do not work for pulsar-admin schema upload --filename flag

### ISSUE THREAD

**Issue by bdunn313** [apache/pulsar#10578]
**Describe the bug**

Currently, when using the `pulsar-admin schemas upload` command to upload a schema via a file with the `--filename` flag, an exception is thrown because the file cannot be found.

**To Reproduce**

1. Create a test topic
2. Create a json file based off "Example 1" from the [schema management docs](https://pulsar.apache.org/docs/en/schema-manage/#upload-a-schema)
3. `cd` into the directory where the new json file exists
3. run `<path-to-pulsar-bin>/pulsar-admin schemas upload persistent://<tenant>/<namespace>/<topic>/ --filename ./testSchema.json`
5. Confirm that this works with an absolute path instead by running `<path-to-pulsar-bin>/pulsar-admin schemas upload persistent://<tenant>/<namespace>/<topic>/ --filename /absolute/path/to/testSchema.json`

**Expected behavior**

**Ideal**: When passing in a relative path for a filename, it should accept the filename
**Alternative**: provide a graceful error encouraging the user to use absolute paths

**Example**

```shell
$ pulsar-admin schemas upload persistent://test-tenant/default/test-topic --filename ./testSchema.json
java.io.FileNotFoundException: ./testSchema.json (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:211)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:153)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:916)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3299)
	at org.apache.pulsar.admin.cli.CmdSchemas$UploadSchema.run(CmdSchemas.java:86)
	at org.apache.pulsar.admin.cli.CmdBase.run(CmdBase.java:76)
	at org.apache.pulsar.admin.cli.PulsarAdminTool.run(PulsarAdminTool.java:246)
	at org.apache.pulsar.admin.cli.PulsarAdminTool.main(PulsarAdminTool.java:288)
```

**Desktop (please complete the following information):**

 - OS: Mac OS Catalina 10.15.7 (intel)
 - Pulsar version: How do I check this? see issue: https://github.com/apache/pulsar/issues/10577

**Additional context**

At least one closed issue addresses this same concern with a separate subcommand, so this might suggest there's a larger issue, or that this somehow was missed while addressing this other issue:

https://github.com/apache/pulsar/issues/4481

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Generally, relative path is ambiguous to resolve - is where you execute the command CWD, or the script location CWD? Since shell doesn't resolve it to absolute path, it can be even something more subtle. Always use absolute path is a good practice.

But I can submit a patch to improve the error message.

**Comment by tisonkun** [comment]
The pulsar-admin script has "support" relative path, cause it no more use `new File(schemaFileName)` to creaate the File what resolve relative path somehow, but may not what you want to mean.

**Comment by tisonkun** [comment]
Updated - https://github.com/apache/pulsar/pull/20876
