### ISSUE TITLE
pulsar function 莫名其妙挂了

### ISSUE THREAD

**Issue by xuesong1cao** [apache/pulsar#10608]
function 一直正常运行，突然早晨就挂了，报了个Haven't received health check from spawner in a while. Stopping instance

00:05:23.453 [function-timer-thread-7-1] INFO  org.apache.pulsar.functions.runtime.JavaInstanceMain - Haven't received health check from spawner in a while. Stopping instance...
00:05:23.459 [111/222/333-0-0] INFO  org.apache.pulsar.functions.instance.JavaInstanceRunnable - Encountered exception in source read: 
java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_251]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_251]
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442) ~[?:1.8.0_251]
	at org.apache.pulsar.io.core.PushSource.read(PushSource.java:49) ~[java-instance.jar:2.4.0]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.readInput(JavaInstanceRunnable.java:440) [java-instance.jar:2.4.0]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:235) [java-instance.jar:2.4.0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
00:05:23.462 [111/222/333-0-0] ERROR org.apache.pulsar.functions.instance.JavaInstanceRunnable - [111/222/333-0:0] Uncaught exception in Java Instance
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.readInput(JavaInstanceRunnable.java:444) ~[java-instance.jar:2.4.0]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:235) [java-instance.jar:2.4.0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_251]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_251]
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442) ~[?:1.8.0_251]
	at org.apache.pulsar.io.core.PushSource.read(PushSource.java:49) ~[java-instance.jar:2.4.0]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.readInput(JavaInstanceRunnable.java:440) ~[java-instance.jar:2.4.0]
	... 2 more
00:05:23.463 [111/222/333-0-0] INFO  org.apache.pulsar.functions.instance.JavaInstanceRunnable - Closing instance
00:05:23.469 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.ConsumerImpl - [persistent://4a/audit/parse_devlog] [111/222/333-0] Closed consumer

`[pulsar@pulsar03 pulsar-2.4.0]$ bin/pulsar-admin brokers healthcheck
HTTP 500 Internal Server Error

Reason: HTTP 500 Internal Server Error
[pulsar@pulsar03 pulsar-2.4.0]$ ll
`

#### Steps to reproduce

**我不清楚broker的healthcheck  报500是不是直接导致的function挂掉，其他的function正常运行，其他消息的发布和接收也是正常的，这个问题该如何排查呢，请大佬们帮忙看下！

第一次发布issue，有哪些不太规范的，请大家及时指正**

#### System configuration
**Pulsar version**:  2.4

**Comment by linlinnn** [comment]
You can translate your issue first, and then people in community can understand your proplem well.

**Comment by xuesong1cao** [comment]
> You can translate your issue first, and then people in community can understand your proplem well.
> And your log shows that the consumer was closed because the unhealth broker.

thanks for  your  reply , my   pulsar  function was  running before , but  it was closed suddenly yesterday,  other functions are running abnormally , and my pulsar  mq   is   abnormal .   I   do not know   how  to  localizate problem
