### ISSUE TITLE
function down suddenly

### ISSUE THREAD

**Issue by linyuan2018** [apache/pulsar#10623]
18:43:58.424 [4a/audit/trans_devlog_function-0] INFO  org.apache.pulsar.functions.instance.JavaInstanceRunnable - Encountered exception in source read: 
java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1220) ~[?:1.8.0_251]
	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:335) ~[?:1.8.0_251]
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:439) ~[?:1.8.0_251]
	at org.apache.pulsar.io.core.PushSource.read(PushSource.java:49) ~[java-instance.jar:2.4.0]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.readInput(JavaInstanceRunnable.java:440) [java-instance.jar:2.4.0]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:235) [java-instance.jar:2.4.0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
18:43:58.428 [4a/audit/trans_devlog_function-0] ERROR org.apache.pulsar.functions.instance.JavaInstanceRunnable - [4a/audit/trans_devlog_function:0] Uncaught exception in Java Instance
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.readInput(JavaInstanceRunnable.java:444) ~[java-instance.jar:2.4.0]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:235) [java-instance.jar:2.4.0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1220) ~[?:1.8.0_251]
	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:335) ~[?:1.8.0_251]
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:439) ~[?:1.8.0_251]
	at org.apache.pulsar.io.core.PushSource.read(PushSource.java:49) ~[java-instance.jar:2.4.0]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.readInput(JavaInstanceRunnable.java:440) ~[java-instance.jar:2.4.0]
	... 2 more

**Comment by linyuan2018** [comment]
Haven't received health check from spawner in a while. Stopping instance

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Vague to investigate. Please open a new issue with more details about the repro and symptom if it's still relevant to maintained versions.
