### ISSUE TITLE
Offload Function has java.lang.NoClassDefFoundError: org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader

### ISSUE THREAD

**Issue by KingNF** [apache/pulsar#10624]
**Describe the bug**
when i config pulsar to open offload function , i have done the config as guide, but  can not  restart the broker.

**To Reproduce**
1. Download and untar the Pulsar offloaders package to the apache-pulsar dir.
2. then config the conf/broker.properties, like this:
 managedLedgerOffloadDriver=S3
 s3ManagedLedgerOffloadBucket=offload-test-aws
 s3ManagedLedgerOffloadRegion=us-east-1
3. restart broker
4. get the error like this :

05:21:50.084 [main] INFO  org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl - Not weighted
05:21:50.085 [main] INFO  org.apache.bookkeeper.client.BookKeeper - Weighted ledger placement is not enabled
05:21:50.106 [main] INFO  org.apache.bookkeeper.mledger.offload.OffloaderUtils - Searching for offloaders in /export/foundation/apache-pulsar-2.7.1/offloaders
05:21:50.454 [main] INFO  org.apache.bookkeeper.mledger.offload.OffloaderUtils - Found offloader OffloaderDefinition(name=filesystem, description=fileSystem based offloader implementation, offloaderFactoryClass=org.apache.bookkeeper.mledger.offload.filesystem.FileSystemLedgerOffloaderFactory) from /export/foundation/apache-pulsar-2.7.1/offloaders/tiered-storage-file-system-2.7.1.nar
[NarClassLoader@5eccd3b9] info AspectJ Weaver Version 1.9.2 built on Wednesday Oct 24, 2018 at 15:43:33 GMT
[NarClassLoader@5eccd3b9] info register classloader org.apache.pulsar.common.nar.NarClassLoader@5eccd3b9
[NarClassLoader@5eccd3b9] info using configuration file:/export/foundation/apache-pulsar-2.7.1/lib/org.apache.pulsar-pulsar-zookeeper-utils-2.7.1.jar!/META-INF/aop.xml
[NarClassLoader@5eccd3b9] info using configuration file:/export/foundation/apache-pulsar-2.7.1/lib/org.apache.pulsar-pulsar-zookeeper-2.7.1.jar!/META-INF/aop.xml
[NarClassLoader@5eccd3b9] info register aspect org.apache.pulsar.broker.zookeeper.aspectj.ClientCnxnAspect
[NarClassLoader@5eccd3b9] info register aspect org.apache.pulsar.zookeeper.FinalRequestProcessorAspect
[NarClassLoader@5eccd3b9] info register aspect org.apache.pulsar.zookeeper.ZooKeeperServerAspect
05:21:51.083 [main] INFO  org.apache.bookkeeper.mledger.offload.OffloaderUtils - Found offloader OffloaderDefinition(name=jcloud, description=JCloud based offloader implementation, offloaderFactoryClass=org.apache.bookkeeper.mledger.offload.jcloud.JCloudLedgerOffloaderFactory) from /export/foundation/apache-pulsar-2.7.1/offloaders/tiered-storage-jcloud-2.7.1.nar
[NarClassLoader@30cecdca] info AspectJ Weaver Version 1.9.2 built on Wednesday Oct 24, 2018 at 15:43:33 GMT
[NarClassLoader@30cecdca] info register classloader org.apache.pulsar.common.nar.NarClassLoader@30cecdca
[NarClassLoader@30cecdca] info using configuration file:/export/foundation/apache-pulsar-2.7.1/lib/org.apache.pulsar-pulsar-zookeeper-utils-2.7.1.jar!/META-INF/aop.xml
[NarClassLoader@30cecdca] info using configuration file:/export/foundation/apache-pulsar-2.7.1/lib/org.apache.pulsar-pulsar-zookeeper-2.7.1.jar!/META-INF/aop.xml
[NarClassLoader@30cecdca] info register aspect org.apache.pulsar.broker.zookeeper.aspectj.ClientCnxnAspect
[NarClassLoader@30cecdca] info register aspect org.apache.pulsar.zookeeper.FinalRequestProcessorAspect
[NarClassLoader@30cecdca] info register aspect org.apache.pulsar.zookeeper.ZooKeeperServerAspect
05:21:51.375 [main] INFO  org.apache.bookkeeper.mledger.offload.OffloaderUtils - Found and loaded 2 offloaders
05:21:51.384 [main] ERROR org.apache.pulsar.broker.PulsarService - java.lang.NoClassDefFoundError: org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader
org.apache.pulsar.broker.PulsarServerException: java.lang.NoClassDefFoundError: org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader
	at org.apache.pulsar.broker.PulsarService.createManagedLedgerOffloader(PulsarService.java:949) ~[org.apache.pulsar-pulsar-broker-2.7.1.jar:2.7.1]
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:482) [org.apache.pulsar-pulsar-broker-2.7.1.jar:2.7.1]
	at org.apache.pulsar.PulsarBrokerStarter$BrokerStarter.start(PulsarBrokerStarter.java:281) [org.apache.pulsar-pulsar-broker-2.7.1.jar:2.7.1]
	at org.apache.pulsar.PulsarBrokerStarter.main(PulsarBrokerStarter.java:350) [org.apache.pulsar-pulsar-broker-2.7.1.jar:2.7.1]
Caused by: java.lang.NoClassDefFoundError: org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader
	at org.apache.bookkeeper.mledger.offload.filesystem.FileSystemLedgerOffloaderFactory.isDriverSupported(FileSystemLedgerOffloaderFactory.java:33) ~[?:?]
	at org.apache.bookkeeper.mledger.offload.Offloaders.getOffloaderFactory(Offloaders.java:38) ~[org.apache.pulsar-managed-ledger-2.7.1.jar:2.7.1]
	at org.apache.pulsar.broker.PulsarService.createManagedLedgerOffloader(PulsarService.java:930) ~[org.apache.pulsar-pulsar-broker-2.7.1.jar:2.7.1]
	... 3 more
Caused by: java.lang.ClassNotFoundException: org.apache.bookkeeper.mledger.offload.filesystem.impl.FileSystemManagedLedgerOffloader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_161]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_161]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_161]
	at org.apache.bookkeeper.mledger.offload.filesystem.FileSystemLedgerOffloaderFactory.isDriverSupported(FileSystemLedgerOffloaderFactory.java:33) ~[?:?]
	at org.apache.bookkeeper.mledger.offload.Offloaders.getOffloaderFactory(Offloaders.java:38) ~[org.apache.pulsar-managed-ledger-2.7.1.jar:2.7.1]
	at org.apache.pulsar.broker.PulsarService.createManagedLedgerOffloader(PulsarService.java:930) ~[org.apache.pulsar-pulsar-broker-2.7.1.jar:2.7.1]
	... 3 more

I want to know what happened , and what should i do to solve this problem?

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
