### ISSUE TITLE
pulsar-bookie and pulsar-broker CrashLoopBackOff in kubernetes

### ISSUE THREAD

**Issue by oldthreefeng** [apache/pulsar#10692]
**Describe the bug**
pulsar 2.7.1 
```
 k get pod -n pulsar 
NAME                                     READY   STATUS             RESTARTS   AGE
pulsar-bookie-0                          0/1     CrashLoopBackOff   73         5h58m
pulsar-bookie-1                          0/1     CrashLoopBackOff   73         5h58m
pulsar-bookie-2                          0/1     CrashLoopBackOff   73         5h58m
pulsar-bookie-3                          0/1     CrashLoopBackOff   73         5h58m
pulsar-broker-0                          0/1     CrashLoopBackOff   71         5h58m
pulsar-broker-1                          0/1     CrashLoopBackOff   71         5h58m
pulsar-broker-2                          0/1     CrashLoopBackOff   71         5h57m
pulsar-proxy-0                           1/1     Running            0          5h57m
pulsar-proxy-1                           1/1     Running            0          5h57m
pulsar-proxy-2                           1/1     Running            0          5h57m
pulsar-pulsar-manager-6bf99b4d88-jk22g   1/1     Running            0          27d
pulsar-recovery-0                        1/1     Running            1          27d
pulsar-toolset-0                         1/1     Running            1          27d
pulsar-zookeeper-0                       1/1     Running            1          27d
pulsar-zookeeper-1                       1/1     Running            1          27d
pulsar-zookeeper-2                       1/1     Running            1          27d
```
bookie

```
k logs -n pulsar  pulsar-bookie-0 --tail 20 -f 
22:20:20.891 [main] INFO  org.apache.zookeeper.common.X509Util - Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation
22:20:20.895 [main] INFO  org.apache.zookeeper.ClientCnxnSocket - jute.maxbuffer value is 10485760 Bytes
22:20:20.904 [main] INFO  org.apache.zookeeper.ClientCnxn - zookeeper.request.timeout value is 0. feature enabled=
22:20:20.918 [main-SendThread(pulsar-zookeeper:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server pulsar-zookeeper/172.16.35.208:2181. Will not attempt to authenticate using SASL (unknown error)
22:20:20.924 [main-SendThread(pulsar-zookeeper:2181)] INFO  org.apache.zookeeper.ClientCnxn - Socket connection established, initiating session, client: /172.16.67.24:45748, server: pulsar-zookeeper/172.16.35.208:2181
22:20:20.931 [main-SendThread(pulsar-zookeeper:2181)] INFO  org.apache.zookeeper.ClientCnxn - Session establishment complete on server pulsar-zookeeper/172.16.35.208:2181, sessionid = 0x2000001f885027b, negotiated timeout = 30000
22:20:20.934 [main-EventThread] INFO  org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase - ZooKeeper client is connected now.
22:20:21.104 [main] ERROR org.apache.bookkeeper.bookie.Bookie - There are directories without a cookie, and this is neither a new environment, nor is storage expansion enabled. Empty directories are [/pulsar/data/bookkeeper/journal/current, /pulsar/data/bookkeeper/ledgers/current]
22:20:21.104 [main] INFO  org.apache.bookkeeper.proto.BookieNettyServer - Shutting down BookieNettyServer
22:20:21.113 [main] ERROR org.apache.bookkeeper.server.Main - Failed to build bookie server
org.apache.bookkeeper.bookie.BookieException$InvalidCookieException: 
	at org.apache.bookkeeper.bookie.Bookie.checkEnvironmentWithStorageExpansion(Bookie.java:476) ~[org.apache.bookkeeper-bookkeeper-server-4.12.0.jar:4.12.0]
	at org.apache.bookkeeper.bookie.Bookie.checkEnvironment(Bookie.java:255) ~[org.apache.bookkeeper-bookkeeper-server-4.12.0.jar:4.12.0]
	at org.apache.bookkeeper.bookie.Bookie.<init>(Bookie.java:712) ~[org.apache.bookkeeper-bookkeeper-server-4.12.0.jar:4.12.0]
	at org.apache.bookkeeper.proto.BookieServer.newBookie(BookieServer.java:152) ~[org.apache.bookkeeper-bookkeeper-server-4.12.0.jar:4.12.0]
	at org.apache.bookkeeper.proto.BookieServer.<init>(BookieServer.java:120) ~[org.apache.bookkeeper-bookkeeper-server-4.12.0.jar:4.12.0]
	at org.apache.bookkeeper.server.service.BookieService.<init>(BookieService.java:52) ~[org.apache.bookkeeper-bookkeeper-server-4.12.0.jar:4.12.0]
	at org.apache.bookkeeper.server.Main.buildBookieServer(Main.java:304) ~[org.apache.bookkeeper-bookkeeper-server-4.12.0.jar:4.12.0]
	at org.apache.bookkeeper.server.Main.doMain(Main.java:226) [org.apache.bookkeeper-bookkeeper-server-4.12.0.jar:4.12.0]
	at org.apache.bookkeeper.server.Main.main(Main.java:208) [org.apache.bookkeeper-bookkeeper-server-4.12.0.jar:4.12.0]
```

broker

```
22:28:45.687 [main] ERROR org.apache.pulsar.PulsarBrokerStarter - Failed to start pulsar service.
org.apache.pulsar.broker.PulsarServerException: java.lang.RuntimeException: org.apache.pulsar.client.admin.PulsarAdminException$ServerSideErrorException: HTTP 500 Internal Server Errorjava.io.ByteArrayInputStream@7c3c22f9

```

so is there anyone who can help me out?  

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: centos 7.9
**Additional context**

**Comment by zymap** [comment]
You might need to clean up the `pvc` and `pv`.

**Comment by oldthreefeng** [comment]
@zymap  but why this happed ?   its not a good idea to clean pvc when the pod CrashLoopBackOff.  
Its just runing three weeks.

**Comment by oldthreefeng** [comment]
fix by recreate whole cluster
```
 k get pod -n pulsar        
NAME                                     READY   STATUS      RESTARTS   AGE
pulsar-bookie-0                          1/1     Running     0          7m29s
pulsar-bookie-1                          1/1     Running     0          7m29s
pulsar-bookie-2                          1/1     Running     0          7m29s
pulsar-bookie-3                          1/1     Running     0          7m29s
pulsar-bookie-init-9rk8j                 0/1     Completed   0          7m29s
pulsar-broker-0                          1/1     Running     0          7m29s
pulsar-broker-1                          1/1     Running     0          7m29s
pulsar-broker-2                          1/1     Running     0          7m29s
pulsar-proxy-0                           1/1     Running     0          7m29s
pulsar-proxy-1                           1/1     Running     0          7m29s
pulsar-proxy-2                           1/1     Running     0          7m29s
pulsar-pulsar-init-ppjc4                 0/1     Completed   0          7m29s
pulsar-pulsar-manager-6bf99b4d88-d6jnk   1/1     Running     0          7m30s
pulsar-recovery-0                        1/1     Running     0          7m30s
pulsar-toolset-0                         1/1     Running     0          7m29s
pulsar-zookeeper-0                       1/1     Running     0          7m29s
pulsar-zookeeper-1                       1/1     Running     0          7m11s
pulsar-zookeeper-2                       1/1     Running     0          6m51s
```

**Comment by zymap** [comment]
The reason that `Invalid cookie` looks like you clean up the data directory but not reinitialize the cluster

**Comment by oldthreefeng** [comment]
@zymap  so re run the `pulsar-bookie-init` job can fix the problem? 

BTW, in our test env,  it Crash in the middle night , no one clean up the data directory.

**Comment by zymap** [comment]
Yes. It should fix the issue.

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by kong62** [comment]
```
[#] kubectl get pod -n pulsar 
NAME                                     READY   STATUS             RESTARTS          AGE
pulsar-bookie-0                          1/1     Running            0                 2d18h
pulsar-bookie-1                          1/1     Running            0                 2d23h
pulsar-bookie-2                          1/1     Running            0                 2d23h
pulsar-bookie-3                          0/1     Init:0/1           0                 8m54s
pulsar-broker-0                          0/1     CrashLoopBackOff   247 (3m26s ago)   2d23h
pulsar-broker-1                          0/1     CrashLoopBackOff   248 (3m13s ago)   46h
pulsar-broker-2                          0/1     CrashLoopBackOff   247 (3m1s ago)    2d23h
pulsar-proxy-0                           1/1     Running            0                 2d23h
pulsar-proxy-1                           1/1     Running            0                 2d22h
pulsar-proxy-2                           1/1     Running            0                 45h
pulsar-pulsar-manager-866c55b6c4-qqqwr   1/1     Running            0                 2d23h
pulsar-recovery-0                        1/1     Running            0                 2d23h
pulsar-toolset-0                         1/1     Running            0                 2d23h
pulsar-zookeeper-0                       1/1     Running            0                 2d23h
pulsar-zookeeper-1                       1/1     Running            0                 8m54s
pulsar-zookeeper-2                       1/1     Running            0                 45h

[#] kubectl logs -f -n pulsar pulsar-broker-0
2024-01-12T08:43:28,980+0000 [main-SendThread(pulsar-zookeeper:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server pulsar-zookeeper/10.44.136.164:2181.
2024-01-12T08:43:28,980+0000 [main-SendThread(pulsar-zookeeper:2181)] INFO  org.apache.zookeeper.ClientCnxn - SASL config status: Will not attempt to authenticate using SASL (unknown error)
2024-01-12T08:43:28,983+0000 [main-SendThread(pulsar-zookeeper:2181)] INFO  org.apache.zookeeper.ClientCnxn - Socket connection established, initiating session, client: /10.44.212.112:60960, server: pulsar-zookeeper/10.44.136.164:2181
2024-01-12T08:43:28,986+0000 [main-SendThread(pulsar-zookeeper:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x0 for sever pulsar-zookeeper/10.44.136.164:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
org.apache.zookeeper.ClientCnxn$EndOfStreamException: Unable to read additional data from server sessionid 0x0, likely server has closed socket
        at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77) ~[org.apache.zookeeper-zookeeper-3.6.3.jar:3.6.3]
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350) ~[org.apache.zookeeper-zookeeper-3.6.3.jar:3.6.3]
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290) [org.apache.zookeeper-zookeeper-3.6.3.jar:3.6.3]

kubectl logs -f -n pulsar pulsar-zookeeper-1 --tail=100
2024-01-12T08:46:42,865+0000 [NIOWorkerThread-1] WARN  org.apache.zookeeper.server.NIOServerCnxn - Close of session 0x0
java.io.IOException: ZooKeeperServer not running
        at org.apache.zookeeper.server.NIOServerCnxn.readLength(NIOServerCnxn.java:544) ~[org.apache.zookeeper-zookeeper-3.6.3.jar:3.6.3]
        at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:332) [org.apache.zookeeper-zookeeper-3.6.3.jar:3.6.3]
        at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522) [org.apache.zookeeper-zookeeper-3.6.3.jar:3.6.3]
        at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154) [org.apache.zookeeper-zookeeper-3.6.3.jar:3.6.3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]

```

**Comment by Khemendra-Bhardwaj** [comment]
I got the same issue , then I deleted the pulsar namespace and setup the whole standalone cluster locally, it  worked for me , is their any,
for me its pulsar-mini-bookie get crash loop back errors
