### ISSUE TITLE
Subscribe consumer(Schema.STRING) with wildcard .+$ always fails with Incompatible schema: exists schema type AVRO, new schema type STRING

### ISSUE THREAD

**Issue by frank-montyne** [apache/pulsar#10766]
**Describe the bug**
I'm trying to subscribe to any persistent topic in a namespace. Suppose we have a a tenant 'aTenant' and a namespace 'aNamespace'. I subscribe to all topics:

pulsarClient.newConsumer(Schema.STRING)
	.subscriptionName("allTopics")
	.subscriptionType(SubscriptionType.Exclusive)
	.consumerName("consumerId")
	.topic("persistent://aTenant/aNamespace/.+$")
	.messageListener(messageListener)
	.subscribe()); 
The following exception is thrown:
org.apache.pulsar.client.api.PulsarClientException$IncompatibleSchemaException: Incompatible schema: exists schema type AVRO, new schema type STRING
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:922)
	at org.apache.pulsar.client.impl.ConsumerBuilderImpl.subscribe(ConsumerBuilderImpl.java:101)

**To Reproduce**
Try the above

**Expected behavior**
No exception

**Desktop (please complete the following information):**
 - OS: OSX, Linux
 - Pulsar 2.7.1, 2.7.2

**Comment by gaozhangmin** [comment]
try this:
```
Pattern allTopicsInNamespace = Pattern.compile("public/default/.*");
Consumer allTopicsConsumer = consumerBuilder
        .topicsPattern(allTopicsInNamespace)
        .subscribe();
```

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closed as answered. No news implies good news.
