### ISSUE TITLE
Flaky-test: MessagePublishBufferThrottleTest.testBlockByPublishRateLimiting

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#10787]
MessagePublishBufferThrottleTest is flaky. The testBlockByPublishRateLimiting test method fails sporadically.

[example failure](https://github.com/apache/pulsar/pull/10782/checks?check_run_id=2728428471#step:10:331)

```
testBlockByPublishRateLimiting(org.apache.pulsar.broker.service.MessagePublishBufferThrottleTest)  Time elapsed: 0.591 s  <<< FAILURE!
java.lang.AssertionError: expected [1] but found [0]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:797)
	at org.testng.Assert.assertEquals(Assert.java:807)
	at org.apache.pulsar.broker.service.MessagePublishBufferThrottleTest.testBlockByPublishRateLimiting(MessagePublishBufferThrottleTest.java:129)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by lhotari** [comment]
@Renkai @315157973 Would you be able to fix this flaky test? thank you

**Comment by lhotari** [comment]
yet another [example failure](https://github.com/apache/pulsar/pull/9927/checks?check_run_id=2729711384#step:10:712)

**Comment by lhotari** [comment]
and [another failure](https://github.com/apache/pulsar/pull/9927/checks?check_run_id=2729711384#step:10:1059)

**Comment by 315157973** [comment]
OK

**Comment by 315157973** [comment]
I have fixed it and I will open a PR soon

**Comment by lhotari** [comment]
This test remains flaky. Recent failure: https://github.com/apache/pulsar/runs/3091955732#step:10:418 . 

```
Error:  Tests run: 8, Failures: 1, Errors: 0, Skipped: 7, Time elapsed: 14.491 s <<< FAILURE! - in org.apache.pulsar.broker.service.MessagePublishBufferThrottleTest
Error:  testBlockByPublishRateLimiting(org.apache.pulsar.broker.service.MessagePublishBufferThrottleTest)  Time elapsed: 6.218 s  <<< FAILURE!
java.lang.AssertionError: expected [0] but found [1]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:797)
	at org.testng.Assert.assertEquals(Assert.java:807)
	at org.apache.pulsar.broker.service.MessagePublishBufferThrottleTest.testBlockByPublishRateLimiting(MessagePublishBufferThrottleTest.java:145)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by 315157973** [comment]
Some code has been added to this unit test recently, the reason is the same as before

**Comment by Demogorgon314** [comment]
[ another failure](https://github.com/apache/pulsar/runs/3132013580?check_suite_focus=true#step:10:1964)
```
Error:  Tests run: 8, Failures: 1, Errors: 0, Skipped: 7, Time elapsed: 14.18 s <<< FAILURE! - in org.apache.pulsar.broker.service.MessagePublishBufferThrottleTest
Error:  testBlockByPublishRateLimiting(org.apache.pulsar.broker.service.MessagePublishBufferThrottleTest)  Time elapsed: 5.751 s  <<< FAILURE!
java.lang.AssertionError: expected [0] but found [1]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:797)
	at org.testng.Assert.assertEquals(Assert.java:807)
	at org.apache.pulsar.broker.service.MessagePublishBufferThrottleTest.testBlockByPublishRateLimiting(MessagePublishBufferThrottleTest.java:145)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
