### ISSUE TITLE
Flaky-test: ManagedLedgerTest.testExpiredLedgerDeletionAfterManagedLedgerRestart

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#10796]
ManagedLedgerTest is flaky. The testExpiredLedgerDeletionAfterManagedLedgerRestart test method fails sporadically.

[example failure](https://github.com/apache/pulsar/pull/10793/checks?check_run_id=2734020079#step:9:16190)

```
Error:  testExpiredLedgerDeletionAfterManagedLedgerRestart(org.apache.bookkeeper.mledger.impl.ManagedLedgerTest)  Time elapsed: 0.029 s  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertTrue(Assert.java:45)
	at org.testng.Assert.assertTrue(Assert.java:55)
	at org.apache.bookkeeper.mledger.impl.ManagedLedgerTest.testExpiredLedgerDeletionAfterManagedLedgerRestart(ManagedLedgerTest.java:2954)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by lhotari** [comment]
@wuzhanpeng Would you mind fixing this flaky test? It seems that this test was introduced by PR #10087 .

**Comment by lhotari** [comment]
@wuzhanpeng The test is flaky and was introduced by PR #10087. Would you be able to fix it? Thanks.
A recent failure: https://github.com/apache/pulsar/pull/10944/checks?check_run_id=2846586819#step:9:16462

**Comment by mattisonchao** [comment]
@lhotari  this PR may be fixed this issue: https://github.com/apache/pulsar/pull/11016

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.
