### ISSUE TITLE
Flaky-test: PersistentTopicTest.testAccumulativeStats is flaky

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#10808]
org.apache.pulsar.broker.service.persistent.PersistentTopicTest is flaky. The testAccumulativeStats test method fails sporadically.

[example failure](https://github.com/apache/pulsar/pull/10807/checks?check_run_id=2735643757#step:10:297)

```
Error:  Tests run: 13, Failures: 4, Errors: 0, Skipped: 9, Time elapsed: 3.536 s <<< FAILURE! - in org.apache.pulsar.broker.service.persistent.PersistentTopicTest
Error:  testAccumulativeStats(org.apache.pulsar.broker.service.persistent.PersistentTopicTest)  Time elapsed: 0.104 s  <<< FAILURE!
java.lang.AssertionError: expected [118] but found [177]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:797)
	at org.testng.Assert.assertEquals(Assert.java:807)
	at org.apache.pulsar.broker.service.persistent.PersistentTopicTest.testAccumulativeStats(PersistentTopicTest.java:240)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by lhotari** [comment]
The test was added in PR #10644 . @dlg99 could you fix this flaky test?

**Comment by dlg99** [comment]
@lhotari See the PR and explanation in the PR.
