### ISSUE TITLE
[Website build] pulsar-admin-doc-gen.sh fails with NoClassDefFoundError error

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#10802]
**Describe the bug**

The website build fails in pulsar-admin-doc-gen.sh fails with NoClassDefFoundError error

```
+ /pulsar/site2/tools/pulsar-admin-doc-gen.sh
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
	at org.apache.pulsar.admin.cli.PulsarAdminTool.<init>(PulsarAdminTool.java:90)
	at org.apache.pulsar.admin.cli.PulsarAdminTool.main(PulsarAdminTool.java:301)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 2 more
```

**To Reproduce**

```
mvn -B -ntp clean install -DskipTests -DskipSourceReleaseAssembly=true -Dspotbugs.skip=true -Dlicense.skip=true
mvn -B -ntp -pl pulsar-broker install -DskipTests -Pswagger
mkdir -p site2/website/static/swagger/master
cp pulsar-broker/target/docs/swagger*.json site2/website/static/swagger/master
site2/tools/docker-build-site.sh
```

**Expected behavior**

`pulsar-admin-doc-gen.sh` should work in website build

**Comment by lhotari** [comment]
It seems that the impact of this is that Pulsar Admin CLI documentation at https://pulsar.apache.org/pulsar-admin-cli?version=2.7.2 (release docs for 2.7.2) and https://pulsar.apache.org/pulsar-admin-cli (built from master) is broken.
