### ISSUE TITLE
[Question][Presto]How can I use my own presto cluster to query pulsar data?

### ISSUE THREAD

**Issue by dik111** [apache/pulsar#10856]
pulsar version: 2.7.2
presto version: 0.241

Hi all:
  I saw in the official document that I can use my own presto cluster to query data, and then I put the pulsar-presto-connector in the installation package in the plugin directory of presto, and then start presto, but it prompts an error:

`2021-06-07T22:06:37.719+0800	ERROR	main	com.facebook.presto.server.PrestoServer	No factory for connector pulsar
java.lang.IllegalArgumentException: No factory for connector pulsar
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:216)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:208)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:123)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:98)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:80)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:135)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:77)
`

Is the way I installed it wrong?

**Comment by Anonymitaet** [comment]
@MarvinCai any thoughts on this?

**Comment by MarvinCai** [comment]
@dik111
Hi there, as you might already knew, Presto community split  into PrestoDB and PrestoSQL
Pulsar community choose to go with PulsarSQL as it's more community driven and more active.
So all Presto deps are started with `io.prestosql`, it **will not** run with PrestoDB which has pkg prefix `com.facebook.presto`.
PrestoSQL is now renamed to Trino: https://trino.io/blog/2020/12/27/announcing-trino.html, and we're working on contributing the connector back to Trino main repo: https://github.com/trinodb/trino/pull/8020.
If you want to use your own cluster the best way is to wait for the PR to be merged then run with Trino cluster.

**Comment by dik111** [comment]
@MarvinCai got it, thanks for your answer
