### ISSUE TITLE
Cannot use SchemaBuilder.record() inside a Source#open() method without adding pulsar-client as dependency in the NAR file

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#10919]
I am testing current 2.8.0 rc3 and I have this problem in an integration test.

I have a Pulsar IO Source that in the "open" method tries to prepare a GenericSchema using this code
`RecordSchemaBuilder udtSchemaBuilder = SchemaBuilder.record(typeName);`

The only way to make it work is to add `pulsar-client-original` into the NAR file.

```
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.datastax.oss.pulsar.source.CassandraSource.createConverter(CassandraSource.java:185) ~[source-pulsar-0.2.0-SNAPSHOT.jar:?]
	at com.datastax.oss.pulsar.source.CassandraSource.open(CassandraSource.java:111) ~[source-pulsar-0.2.0-SNAPSHOT.jar:?]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.setupInput(JavaInstanceRunnable.java:734) [org.apache.pulsar-pulsar-functions-instance-2.8.0.jar:2.8.0]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.setup(JavaInstanceRunnable.java:219) [org.apache.pulsar-pulsar-functions-instance-2.8.0.jar:2.8.0]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:243) [org.apache.pulsar-pulsar-functions-instance-2.8.0.jar:2.8.0]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.apache.pulsar.client.impl.schema.RecordSchemaBuilderImpl
	at org.apache.pulsar.client.internal.ReflectionUtils.catchExceptions(ReflectionUtils.java:45) ~[java-instance.jar:?]
	at org.apache.pulsar.client.internal.DefaultImplementation.newRecordSchemaBuilder(DefaultImplementation.java:355) ~[java-instance.jar:?]
	at org.apache.pulsar.client.api.schema.SchemaBuilder.record(SchemaBuilder.java:39) ~[java-instance.jar:?]
	at com.datastax.oss.pulsar.source.converters.AbstractGenericConverter.<init>(AbstractGenericConverter.java:57) ~[source-pulsar-0.2.0-SNAPSHOT.jar:?]
	at com.datastax.oss.pulsar.source.converters.AvroConverter.<init>(AvroConverter.java:30) ~[source-pulsar-0.2.0-SNAPSHOT.jar:?]
	... 10 more
```

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by eolivelli** [comment]
This is no more a problem since 2.10
