### ISSUE TITLE
Pulsar-mini broker failed to start in k8s

### ISSUE THREAD

**Issue by golden-yang** [apache/pulsar#10914]
**Describe the bug**
When I started pulsar-mini according to the pulsar on k8s documentation, the broker report an error

**To Reproduce**
1. build minikube cluster
minikube start --memory=8192 --cpus=4  --kubernetes-version=v1.20.2
minikube v1.20.0 on Centos 7.2 (amd64)
2. download pulsar-helm-chart, checkout to tag pulsar-2.7.2
3.  install pulsar-mini 
 helm install     --values examples/values-minikube.yaml     --set initialize=true     --namespace pulsar     pulsar-mini apache/pulsar

NAME                                         READY   STATUS             RESTARTS   AGE
pulsar-mini-bookie-0                         0/1     CrashLoopBackOff   6          20m
pulsar-mini-bookie-init-z5v7w                0/1     Completed          0          20m
pulsar-mini-broker-0                         0/1     CrashLoopBackOff   12         20m
pulsar-mini-grafana-555cf54cf-4f8fl          1/1     Running            1          20m
pulsar-mini-prometheus-5556dbb8b8-h4xp2      1/1     Running            0          20m
pulsar-mini-proxy-0                          0/1     Init:1/2           1          20m
pulsar-mini-pulsar-init-8nhml                0/1     Completed          0          20m
pulsar-mini-pulsar-manager-6c6889dff-vftnq   0/1     ImagePullBackOff   0          20m
pulsar-mini-toolset-0                        1/1     Running            1          20m
pulsar-mini-zookeeper-0                      1/1     Running            1          20m

It looks like the cgroup got an invalid value when getting the memory limit  in `sun.management.OperatingSystemImpl#getTotalPhysicalMemorySize`.
I'm not sure if I misconfigured the environment.

**pod logs of broker**
kubectl logs pulsar-mini-broker-0 -n pulsar

07:25:22.467 [main] WARN  org.apache.pulsar.broker.loadbalance.LoadManager - Error when trying to create load manager: 
java.lang.NumberFormatException: For input string: "18446744073709551615"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_282]
        at java.lang.Long.parseLong(Long.java:592) ~[?:1.8.0_282]
        at java.lang.Long.parseLong(Long.java:631) ~[?:1.8.0_282]
        at jdk.internal.platform.cgroupv1.SubSystem.getLongValue(SubSystem.java:119) ~[?:1.8.0_282]
        at jdk.internal.platform.cgroupv1.Metrics.getMemoryLimit(Metrics.java:394) ~[?:1.8.0_282]
        at sun.management.OperatingSystemImpl.getTotalPhysicalMemorySize(OperatingSystemImpl.java:109) ~[?:1.8.0_282]
        at org.apache.pulsar.broker.loadbalance.impl.LinuxBrokerHostUsageImpl.getMemUsage(LinuxBrokerHostUsageImpl.java:205) ~[org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
        at org.apache.pulsar.broker.loadbalance.impl.LinuxBrokerHostUsageImpl.calculateBrokerHostUsage(LinuxBrokerHostUsageImpl.java:115) ~[org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
        at org.apache.pulsar.broker.loadbalance.impl.LinuxBrokerHostUsageImpl.<init>(LinuxBrokerHostUsageImpl.java:91) ~[org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
        at org.apache.pulsar.broker.loadbalance.impl.LinuxBrokerHostUsageImpl.<init>(LinuxBrokerHostUsageImpl.java:67) ~[org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
        at org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerImpl.initialize(ModularLoadManagerImpl.java:267) ~[org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
        at org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerWrapper.initialize(ModularLoadManagerWrapper.java:90) ~[org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
        at org.apache.pulsar.broker.loadbalance.LoadManager.create(LoadManager.java:150) [org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
        at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:477) [org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
        at org.apache.pulsar.PulsarBrokerStarter$BrokerStarter.start(PulsarBrokerStarter.java:281) [org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
        at org.apache.pulsar.PulsarBrokerStarter.main(PulsarBrokerStarter.java:350) [org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
07:25:22.476 [main] ERROR org.apache.pulsar.broker.PulsarService - For input string: "18446744073709551615"
java.lang.NumberFormatException: For input string: "18446744073709551615"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_282]
        at java.lang.Long.parseLong(Long.java:592) ~[?:1.8.0_282]
        at java.lang.Long.parseLong(Long.java:631) ~[?:1.8.0_282]
        at jdk.internal.platform.cgroupv1.SubSystem.getLongValue(SubSystem.java:119) ~[?:1.8.0_282]
        at jdk.internal.platform.cgroupv1.Metrics.getMemoryLimit(Metrics.java:394) ~[?:1.8.0_282]
        at sun.management.OperatingSystemImpl.getTotalPhysicalMemorySize(OperatingSystemImpl.java:109) ~[?:1.8.0_282]
        at org.apache.pulsar.broker.loadbalance.impl.LinuxBrokerHostUsageImpl.getMemUsage(LinuxBrokerHostUsageImpl.java:205) ~[org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
        at org.apache.pulsar.broker.loadbalance.impl.LinuxBrokerHostUsageImpl.calculateBrokerHostUsage(LinuxBrokerHostUsageImpl.java:115) ~[org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
        at org.apache.pulsar.broker.loadbalance.impl.LinuxBrokerHostUsageImpl.<init>(LinuxBrokerHostUsageImpl.java:91) ~[org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
        at org.apache.pulsar.broker.loadbalance.impl.LinuxBrokerHostUsageImpl.<init>(LinuxBrokerHostUsageImpl.java:67) ~[org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
        at org.apache.pulsar.broker.loadbalance.impl.SimpleLoadManagerImpl.initialize(SimpleLoadManagerImpl.java:224) ~[org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
        at org.apache.pulsar.broker.loadbalance.impl.SimpleLoadManagerImpl.<init>(SimpleLoadManagerImpl.java:272) ~[org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
        at org.apache.pulsar.broker.loadbalance.LoadManager.create(LoadManager.java:157) ~[org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
        at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:477) [org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
        at org.apache.pulsar.PulsarBrokerStarter$BrokerStarter.start(PulsarBrokerStarter.java:281) [org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
        at org.apache.pulsar.PulsarBrokerStarter.main(PulsarBrokerStarter.java:350) [org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
07:25:22.476 [main] ERROR org.apache.pulsar.PulsarBrokerStarter - Failed to start pulsar service.
org.apache.pulsar.broker.PulsarServerException: java.lang.NumberFormatException: For input string: "18446744073709551615"
        at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:629) ~[org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
        at org.apache.pulsar.PulsarBrokerStarter$BrokerStarter.start(PulsarBrokerStarter.java:281) ~[org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
        at org.apache.pulsar.PulsarBrokerStarter.main(PulsarBrokerStarter.java:350) [org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
Caused by: java.lang.NumberFormatException: For input string: "18446744073709551615"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_282]
        at java.lang.Long.parseLong(Long.java:592) ~[?:1.8.0_282]
        at java.lang.Long.parseLong(Long.java:631) ~[?:1.8.0_282]
        at jdk.internal.platform.cgroupv1.SubSystem.getLongValue(SubSystem.java:119) ~[?:1.8.0_282]
        at jdk.internal.platform.cgroupv1.Metrics.getMemoryLimit(Metrics.java:394) ~[?:1.8.0_282]
        at sun.management.OperatingSystemImpl.getTotalPhysicalMemorySize(OperatingSystemImpl.java:109) ~[?:1.8.0_282]
        at org.apache.pulsar.broker.loadbalance.impl.LinuxBrokerHostUsageImpl.getMemUsage(LinuxBrokerHostUsageImpl.java:205) ~[org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
        at org.apache.pulsar.broker.loadbalance.impl.LinuxBrokerHostUsageImpl.calculateBrokerHostUsage(LinuxBrokerHostUsageImpl.java:115) ~[org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
        at org.apache.pulsar.broker.loadbalance.impl.LinuxBrokerHostUsageImpl.<init>(LinuxBrokerHostUsageImpl.java:91) ~[org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
        at org.apache.pulsar.broker.loadbalance.impl.LinuxBrokerHostUsageImpl.<init>(LinuxBrokerHostUsageImpl.java:67) ~[org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
        at org.apache.pulsar.broker.loadbalance.impl.SimpleLoadManagerImpl.initialize(SimpleLoadManagerImpl.java:224) ~[org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
        at org.apache.pulsar.broker.loadbalance.impl.SimpleLoadManagerImpl.<init>(SimpleLoadManagerImpl.java:272) ~[org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
        at org.apache.pulsar.broker.loadbalance.LoadManager.create(LoadManager.java:157) ~[org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
        at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:477) ~[org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
        ... 2 more

**environment**
kubectl version  
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by MTBirdman89a** [comment]
[]()

**Comment by MTBirdman89a** [comment]
Okay

**Comment by MTBirdman89a** [comment]
End

**Comment by golden-yang** [comment]
I think it's a problem with my docker environment. When I start the docker service with the configuration file `pulsar/docker-compose/kitchen-sink/docker-compose.yml`, this problem also occurs.

But at same time, docker pulsar standalone runs well. I'm confused.
