### ISSUE TITLE
unclear error: Add LoadManagerReport deserializer failed because LoadManagerReport.class has been shaded {}

### ISSUE THREAD

**Issue by Zhen-hao** [apache/pulsar#10980]
I wrote a dummy test in Scala

```scala
package com.nt

import org.scalatest.BeforeAndAfterAll
import org.scalatest.matchers.should.Matchers
import org.scalatest.wordspec.AnyWordSpecLike
import org.apache.pulsar.client.admin.PulsarAdmin

class PulsarSepc extends AnyWordSpecLike with BeforeAndAfterAll with Matchers {

  "Pulsar admin" when {

    val url = "http://192.168.1.203:8080"
    // val url = "http://192.168.1.102:8080,192.168.1.202:8080,192.168.1.203:8080"

    val tlsAllowInsecureConnection = false;
    val tlsTrustCertsFilePath = null;
    val admin = PulsarAdmin
      .builder()
      .serviceHttpUrl(url)
      .tlsTrustCertsFilePath(tlsTrustCertsFilePath)
      .allowTlsInsecureConnection(tlsAllowInsecureConnection)
      .build();

    "initialized" should {

      "work" in {
        val currentTenants = admin.tenants.getTenants
        println(s"currentTenants is $currentTenants")
        true
      }

    }

  }

}
```
and got 
```
java.lang.ClassNotFoundException: org.apache.pulsar.shade.org.apache.pulsar.policies.data.loadbalancer.LoadManagerReport
```
I know this error message comes from [here](https://github.com/apache/pulsar/blob/master/pulsar-common/src/main/java/org/apache/pulsar/common/util/ObjectMapperFactory.java#L205) but it's not very helpful.

full logs:

```
[2021-06-19 08:06:32,211] [DEBUG] [org.apache.pulsar.common.util.ObjectMapperFactory] [] [pool-1-thread-1-ScalaTest-running-PulsarSepc] - Add LoadManagerReport deserializer failed because LoadManagerReport.class has been shaded {}
java.lang.ClassNotFoundException: org.apache.pulsar.shade.org.apache.pulsar.policies.data.loadbalancer.LoadManagerReport
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at org.apache.pulsar.shade.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:1069)
        at org.apache.pulsar.shade.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:1135)
        at org.apache.pulsar.shade.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:1118)
        at org.apache.pulsar.common.util.ObjectMapperFactory.setAnnotationsModule(ObjectMapperFactory.java:202)
        at org.apache.pulsar.common.util.ObjectMapperFactory.create(ObjectMapperFactory.java:116)
        at org.apache.pulsar.client.admin.internal.JacksonConfigurator.<init>(JacksonConfigurator.java:38)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.apache.pulsar.shade.org.glassfish.hk2.utilities.reflection.ReflectionHelper.makeMe(ReflectionHelper.java:1356)
        at org.apache.pulsar.shade.org.jvnet.hk2.internal.ClazzCreator.createMe(ClazzCreator.java:248)
        at org.apache.pulsar.shade.org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:342)
        at org.apache.pulsar.shade.org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
        at org.apache.pulsar.shade.org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:59)
        at org.apache.pulsar.shade.org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:47)
        at org.apache.pulsar.shade.org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:74)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.pulsar.shade.org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:131)
        at org.apache.pulsar.shade.org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:176)
        at org.apache.pulsar.shade.org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:98)
        at org.apache.pulsar.shade.org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
        at org.apache.pulsar.shade.org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetAllServiceHandles(ServiceLocatorImpl.java:1481)
        at org.apache.pulsar.shade.org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServices(ServiceLocatorImpl.java:799)
        at org.apache.pulsar.shade.org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getAllInstances(AbstractHk2InjectionManager.java:170)
        at org.apache.pulsar.shade.org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getAllInstances(ImmediateHk2InjectionManager.java:30)
        at org.apache.pulsar.shade.org.glassfish.jersey.internal.ContextResolverFactory$ContextResolversConfigurator.postInit(ContextResolverFactory.java:69)
        at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientConfig$State.lambda$initRuntime$2(ClientConfig.java:461)
        at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
        at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:461)
        at org.apache.pulsar.shade.org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:317)
        at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:819)
        at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientRequest.getClientRuntime(ClientRequest.java:176)
        at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientRequest.getInjectionManager(ClientRequest.java:567)
        at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyWebTarget.onBuilder(JerseyWebTarget.java:371)
        at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:206)
        at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:38)
        at org.apache.pulsar.client.admin.internal.BaseResource.lambda$requestAsync$1(BaseResource.java:97)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
        at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
        at org.apache.pulsar.client.admin.internal.BaseResource.requestAsync(BaseResource.java:88)
        at org.apache.pulsar.client.admin.internal.BaseResource.request(BaseResource.java:68)
        at org.apache.pulsar.client.admin.internal.BaseResource.asyncGetRequest(BaseResource.java:165)
        at org.apache.pulsar.client.admin.internal.TenantsImpl.getTenantsAsync(TenantsImpl.java:63)
        at org.apache.pulsar.client.admin.internal.TenantsImpl.getTenants(TenantsImpl.java:49)
        at com.nt.PulsarSepc.$anonfun$new$3(PulsarSepc.scala:28)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
        at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
        at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
        at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
        at org.scalatest.Transformer.apply(Transformer.scala:22)
        at org.scalatest.Transformer.apply(Transformer.scala:20)
        at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
        at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
        at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
        at com.nt.PulsarSepc.withFixture(PulsarSepc.scala:8)
        at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1074)
        at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1086)
        at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
        at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1086)
        at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1068)
        at com.nt.PulsarSepc.runTest(PulsarSepc.scala:8)
        at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1145)
        at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
        at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
        at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
        at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
        at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
        at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
        at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
        at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1145)
        at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1144)
        at com.nt.PulsarSepc.runTests(PulsarSepc.scala:8)
        at org.scalatest.Suite.run(Suite.scala:1112)
        at org.scalatest.Suite.run$(Suite.scala:1094)
        at com.nt.PulsarSepc.org$scalatest$wordspec$AnyWordSpecLike$$super$run(PulsarSepc.scala:8)
        at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1190)
        at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
        at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1190)
        at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1188)
        at com.nt.PulsarSepc.org$scalatest$BeforeAndAfterAll$$super$run(PulsarSepc.scala:8)
        at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
        at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
        at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
        at com.nt.PulsarSepc.run(PulsarSepc.scala:8)
        at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:318)
        at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:513)
        at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
[2021-06-19 08:06:32,303] [DEBUG] [org.apache.pulsar.shade.io.netty.channel.DefaultChannelId] [] [org.apache.pulsar.shade.jersey-client-async-executor-0] - -Dio.netty.processId: 1647422 (auto-detected) {}
[2021-06-19 08:06:32,305] [DEBUG] [org.apache.pulsar.shade.io.netty.util.NetUtil] [] [org.apache.pulsar.shade.jersey-client-async-executor-0] - -Djava.net.preferIPv4Stack: false {}
[2021-06-19 08:06:32,305] [DEBUG] [org.apache.pulsar.shade.io.netty.util.NetUtil] [] [org.apache.pulsar.shade.jersey-client-async-executor-0] - -Djava.net.preferIPv6Addresses: false {}
[2021-06-19 08:06:32,306] [DEBUG] [org.apache.pulsar.shade.io.netty.util.NetUtilInitializations] [] [org.apache.pulsar.shade.jersey-client-async-executor-0] - Loopback interface: lo (lo, 0:0:0:0:0:0:0:1%lo) {}
[2021-06-19 08:06:32,306] [DEBUG] [org.apache.pulsar.shade.io.netty.util.NetUtil] [] [org.apache.pulsar.shade.jersey-client-async-executor-0] - /proc/sys/net/core/somaxconn: 4096 {}
[2021-06-19 08:06:32,307] [DEBUG] [org.apache.pulsar.shade.io.netty.channel.DefaultChannelId] [] [org.apache.pulsar.shade.jersey-client-async-executor-0] - -Dio.netty.machineId: 0c:9d:92:ff:fe:c5:74:d6 (auto-detected) {}
[2021-06-19 08:06:32,331] [DEBUG] [org.apache.pulsar.shade.io.netty.buffer.AbstractByteBuf] [] [AsyncHttpClient-7-1] - -Dorg.apache.pulsar.shade.io.netty.buffer.checkAccessible: true {}
[2021-06-19 08:06:32,331] [DEBUG] [org.apache.pulsar.shade.io.netty.buffer.AbstractByteBuf] [] [AsyncHttpClient-7-1] - -Dorg.apache.pulsar.shade.io.netty.buffer.checkBounds: true {}
[2021-06-19 08:06:32,332] [DEBUG] [org.apache.pulsar.shade.io.netty.util.ResourceLeakDetectorFactory] [] [AsyncHttpClient-7-1] - Loaded default ResourceLeakDetector: org.apache.pulsar.shade.io.netty.util.ResourceLeakDetector@40b5770 {}
[2021-06-19 08:06:32,339] [DEBUG] [org.apache.pulsar.shade.org.asynchttpclient.netty.channel.NettyConnectListener] [] [AsyncHttpClient-7-1] - Using new Channel '[id: 0x9314018a, L:/192.168.1.65:43932 - R:/192.168.1.203:8080]' for 'GET' to '/admin/v2/tenants' {}
[2021-06-19 08:06:32,347] [DEBUG] [org.apache.pulsar.shade.io.netty.util.Recycler] [] [AsyncHttpClient-7-1] - -Dio.netty.recycler.maxCapacityPerThread: 4096 {}
[2021-06-19 08:06:32,347] [DEBUG] [org.apache.pulsar.shade.io.netty.util.Recycler] [] [AsyncHttpClient-7-1] - -Dio.netty.recycler.maxSharedCapacityFactor: 2 {}
[2021-06-19 08:06:32,347] [DEBUG] [org.apache.pulsar.shade.io.netty.util.Recycler] [] [AsyncHttpClient-7-1] - -Dio.netty.recycler.linkCapacity: 16 {}
[2021-06-19 08:06:32,347] [DEBUG] [org.apache.pulsar.shade.io.netty.util.Recycler] [] [AsyncHttpClient-7-1] - -Dio.netty.recycler.ratio: 8 {}
[2021-06-19 08:06:32,347] [DEBUG] [org.apache.pulsar.shade.io.netty.util.Recycler] [] [AsyncHttpClient-7-1] - -Dio.netty.recycler.delayedQueue.ratio: 8 {}
[2021-06-19 08:06:32,504] [DEBUG] [org.apache.pulsar.shade.org.asynchttpclient.netty.handler.HttpHandler] [] [AsyncHttpClient-7-1] - 

Request DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: EmptyByteBufBE)
GET /admin/v2/tenants HTTP/1.1
Accept: application/json
host: 192.168.1.203:8080
user-agent: Pulsar-Java-v2.8.0

Response DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 404 Not Found
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: application/json
Server: Jetty(9.4.24.v20191120)
content-length: 149
 {}
[2021-06-19 08:06:32,509] [DEBUG] [org.apache.pulsar.shade.org.asynchttpclient.netty.channel.ChannelManager] [] [AsyncHttpClient-7-1] - Adding key: http://192.168.1.203:8080 for channel [id: 0x9314018a, L:/192.168.1.65:43932 - R:/192.168.1.203:8080] {}
[2021-06-19 08:06:32,553] [DEBUG] [org.apache.pulsar.common.util.ObjectMapperFactory] [] [AsyncHttpClient-7-1] - Add LoadManagerReport deserializer failed because LoadManagerReport.class has been shaded {}
java.lang.ClassNotFoundException: org.apache.pulsar.shade.org.apache.pulsar.policies.data.loadbalancer.LoadManagerReport
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at org.apache.pulsar.shade.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:1069)
        at org.apache.pulsar.shade.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:1135)
        at org.apache.pulsar.shade.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:1118)
        at org.apache.pulsar.common.util.ObjectMapperFactory.setAnnotationsModule(ObjectMapperFactory.java:202)
        at org.apache.pulsar.common.util.ObjectMapperFactory.create(ObjectMapperFactory.java:116)
        at org.apache.pulsar.common.util.ObjectMapperFactory$1.initialValue(ObjectMapperFactory.java:133)
        at org.apache.pulsar.common.util.ObjectMapperFactory$1.initialValue(ObjectMapperFactory.java:130)
        at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocal.initialize(FastThreadLocal.java:177)
        at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocal.get(FastThreadLocal.java:142)
        at org.apache.pulsar.common.util.ObjectMapperFactory.getThreadLocal(ObjectMapperFactory.java:145)
        at org.apache.pulsar.client.admin.internal.BaseResource.getReasonFromServer(BaseResource.java:273)
        at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:224)
        at org.apache.pulsar.client.admin.internal.TenantsImpl$1.failed(TenantsImpl.java:72)
        at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation$1.failed(JerseyInvocation.java:882)
        at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation$1.completed(JerseyInvocation.java:863)
        at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:229)
        at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientRuntime.access$200(ClientRuntime.java:62)
        at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientRuntime$2.lambda$response$0(ClientRuntime.java:173)
        at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.apache.pulsar.shade.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:288
        at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientRuntime$2.response(ClientRuntime.java:173)
        at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$apply$1(AsyncHttpConnector.java:212)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
        at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$retryOperation$4(AsyncHttpConnector.java:254)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
        at org.apache.pulsar.shade.org.asynchttpclient.netty.NettyResponseFuture.loadContent(NettyResponseFuture.java:222)
        at org.apache.pulsar.shade.org.asynchttpclient.netty.NettyResponseFuture.done(NettyResponseFuture.java:257)
        at org.apache.pulsar.shade.org.asynchttpclient.netty.handler.AsyncHttpClientHandler.finishUpdate(AsyncHttpClientHandler.java:241)
        at org.apache.pulsar.shade.org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:114)
        at org.apache.pulsar.shade.org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:143)
        at org.apache.pulsar.shade.org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78)
        at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at org.apache.pulsar.shade.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at org.apache.pulsar.shade.io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at org.apache.pulsar.shade.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
        at org.apache.pulsar.shade.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
        at org.apache.pulsar.shade.io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at org.apache.pulsar.shade.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at org.apache.pulsar.shade.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at org.apache.pulsar.shade.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at org.apache.pulsar.shade.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closed as stale. If it's still relevant to maintained versions, please open a new issue with reproduce.
