### ISSUE TITLE
add direct support for message values already serialized in Apache Avro

### ISSUE THREAD

**Issue by Zhen-hao** [apache/pulsar#11007]
Maybe this is two requests in one post. 

**Background**: 
I want to integrate Pulsar with an existing event store in Cassandra (used by an event-sourced application).
The events are already serialized with Avro. I just want to simply move the events to some Pulsar topics. 
For each event, I have a way to find the writer's schema.

**Problem 1**
Puslar's `Schema<T>` has no constructor for importing an existing native Avro schema, namely a value of `org.apache.avro.Schema`. 

The workaround I found is:
```scala
val avroSchemaString = ??? // for example, avroSchema.toString(pretty = false)
val schemaDefinition = SchemaDefinition.builder().withJsonDef(avroSchemaString).build()
val pulsarSchema = Schema.AUTO_PRODUCE_BYTES(DefaultImplementation.newAvroSchema(schemaDefinition))
```
It is ugly and `DefaultImplementation` is internal. Though I'm happy that I can use it for now.

**Problem 2**

The line `.value(bytes)` in

```scala
producer
  .newMessage(pulsarSchema)
  .key(extractKey(persistenceId))
  .value(bytes) // marked as `$THE_PROBLEMATIC_LINE` in the log
  .send()
```

throws an exception: 

```
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NoSuchMethodException: com.nt.back.user.Event$UserLoggedIn.<init>()
        at org.apache.avro.specific.SpecificData.newInstance(SpecificData.java:466)
        at org.apache.avro.specific.SpecificData.newRecord(SpecificData.java:484)
        at org.apache.avro.reflect.ReflectData.newRecord(ReflectData.java:1038)
        at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:236)
        at org.apache.avro.specific.SpecificDatumReader.readRecord(SpecificDatumReader.java:123)
        at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:179)
        at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:160)
        at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:153)
        at org.apache.pulsar.client.impl.schema.reader.AvroReader.read(AvroReader.java:80)
        at org.apache.pulsar.client.api.schema.SchemaReader.read(SchemaReader.java:41)
        at org.apache.pulsar.client.impl.schema.reader.AbstractMultiVersionReader.read(AbstractMultiVersionReader.java:62)
        at org.apache.pulsar.client.api.schema.SchemaReader.read(SchemaReader.java:41)
        at org.apache.pulsar.client.impl.schema.AbstractStructSchema.decode(AbstractStructSchema.java:62)
        at org.apache.pulsar.client.api.Schema.validate(Schema.java:64)
        at org.apache.pulsar.client.impl.schema.AutoProduceBytesSchema.encode(AutoProduceBytesSchema.java:82)
        at org.apache.pulsar.client.impl.schema.AutoProduceBytesSchema.encode(AutoProduceBytesSchema.java:34)
        at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.value(TypedMessageBuilderImpl.java:175)
        at com.nt.projection.PublishEventsProjectionHandler.$anonfun$process$1($THE_PROBLEMATIC_LINE)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:672)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:431)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: com.nt.back.user.Event$UserLoggedIn.<init>()
        at org.apache.avro.specific.SpecificData$1.computeValue(SpecificData.java:67)
        at org.apache.avro.specific.SpecificData$1.computeValue(SpecificData.java:58)
        at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
        at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
        at java.base/java.lang.ClassValue.get(ClassValue.java:116)
        at org.apache.avro.specific.SpecificData.newInstance(SpecificData.java:463)
        ... 31 common frames omitted
Caused by: java.lang.NoSuchMethodException: com.nt.back.user.Event$UserLoggedIn.<init>()
        at java.base/java.lang.Class.getConstructor0(Class.java:3349)
        at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553)
        at org.apache.avro.specific.SpecificData$1.computeValue(SpecificData.java:63)
        ... 36 common frames omitted
```

It seems that the schema validator of Pulsar tries to find a matching class name from the loader, and then create a value of it from the binary value. I'm not an expert of POJO, or Java in general, but it seems to me the logic assumes the serialization is done via Pulsar's POJO machinery. If my assumption is correct, this will always be a problem when working with external Avro data. 
It feels natural to use a validator that depends only on the Apache Avro project for this kind of use case.

**Comment by Zhen-hao** [comment]
Kafka's approach is to support both POJO and Avro's GenericRecord; see https://faun.pub/tutorial-validate-your-data-pipeline-using-schema-registry-and-kafka-streams-523595d7fe3d

It seems Pulsar only supports POJO as far as the validation is concerned.

**Comment by eolivelli** [comment]
for reference:
here you can find an example about how to deal with a pure org.apache.avro.Schema

https://github.com/apache/pulsar/blob/d81b5f8b8e6cb17f307ec830accaf9dd95d7643b/pul[…]a/src/main/java/org/apache/pulsar/io/kafka/AvroSchemaCache.java

basically you can create an implementation of org.apache.pulsar.schema.Schema that:
- reports the Schema definition from Avro
- keeps the encoded value (no decode/encode)

**Comment by Zhen-hao** [comment]
@eolivelli thanks a lot for your help! 

I can confirm it works. I'm happy that my work is unblocked. 

On the other hand, it feels like cheating. Because we are telling Pulsar it's a schema for `byte []` (or `ByteBuffer`) while it is for some Avro `GenericRecord`.
