### ISSUE TITLE
Flaky-test: KeyValueSchemaInfoTest.encodeDecodeNestedKeyValueSchemaInfo

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#11031]
KeyValueSchemaInfoTest is flaky. The encodeDecodeNestedKeyValueSchemaInfo test method fails sporadically.

[example failure](https://github.com/apache/pulsar/pull/11025/checks?check_run_id=2889196047#step:9:8734)

```
Error:  Tests run: 8, Failures: 1, Errors: 0, Skipped: 5, Time elapsed: 0.265 s <<< FAILURE! - in org.apache.pulsar.client.impl.schema.KeyValueSchemaInfoTest
Error:  encodeDecodeNestedKeyValueSchemaInfo(org.apache.pulsar.client.impl.schema.KeyValueSchemaInfoTest)  Time elapsed: 0.015 s  <<< FAILURE!
java.lang.NullPointerException
	at org.apache.pulsar.client.impl.schema.KeyValueSchemaInfo.decodeKeyValueEncodingType(KeyValueSchemaInfo.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.pulsar.client.internal.DefaultImplementation.lambda$decodeKeyValueEncodingType$43(DefaultImplementation.java:371)
	at org.apache.pulsar.client.internal.ReflectionUtils.catchExceptions(ReflectionUtils.java:34)
	at org.apache.pulsar.client.internal.DefaultImplementation.decodeKeyValueEncodingType(DefaultImplementation.java:368)
	at org.apache.pulsar.client.impl.schema.KeyValueSchemaInfoTest.encodeDecodeNestedKeyValueSchemaInfo(KeyValueSchemaInfoTest.java:141)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Close as stale. Please open a new issue if this flaky test comes back.
