### ISSUE TITLE
Flaky-test: ResourceGroupConfigListenerTest.testResourceGroupAttachToNamespace

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#11045]
ResourceGroupConfigListenerTest is flaky. The testResourceGroupAttachToNamespace test method fails sporadically.

[example failure](https://github.com/apache/pulsar/pull/11026/checks?check_run_id=2894464546#step:10:571)

```
Error:  Tests run: 14, Failures: 1, Errors: 0, Skipped: 13, Time elapsed: 8.365 s <<< FAILURE! - in org.apache.pulsar.broker.resourcegroup.ResourceGroupConfigListenerTest
Error:  testResourceGroupAttachToNamespace(org.apache.pulsar.broker.resourcegroup.ResourceGroupConfigListenerTest)  Time elapsed: 1.058 s  <<< FAILURE!
org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in org.apache.pulsar.broker.resourcegroup.ResourceGroupConfigListenerTest expected object to not be null within 1 seconds.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:679)
	at org.apache.pulsar.broker.resourcegroup.ResourceGroupConfigListenerTest.createResourceGroup(ResourceGroupConfigListenerTest.java:67)
	at org.apache.pulsar.broker.resourcegroup.ResourceGroupConfigListenerTest.testResourceGroupAttachToNamespace(ResourceGroupConfigListenerTest.java:122)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.AssertionError: expected object to not be null
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.assertNotNull(Assert.java:942)
	at org.testng.Assert.assertNotNull(Assert.java:926)
	at org.apache.pulsar.broker.resourcegroup.ResourceGroupConfigListenerTest.lambda$createResourceGroup$0(ResourceGroupConfigListenerTest.java:70)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:222)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:209)
	... 4 more
```

**Comment by lhotari** [comment]
@bharanic-dev The fix seems to be to remove the `.atMost` method calls from Awaitility. It's better to rely on the default that is 10 seconds. The code will also be less cluttered without the `.atMost` statements.

**Comment by lhotari** [comment]
@bharanic-dev I'll fix this, pushing a PR soon.
