### ISSUE TITLE
Flaky-test: ServerCnxTest.testDuplicateConcurrentSubscribeCommand

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#11050]
ServerCnxTest is flaky. The testDuplicateConcurrentSubscribeCommand test method fails sporadically.

[example failure](https://github.com/apache/pulsar/pull/11026/checks?check_run_id=2894465015#step:10:356)

```
Error:  Tests run: 72, Failures: 30, Errors: 0, Skipped: 31, Time elapsed: 8.306 s <<< FAILURE! - in org.apache.pulsar.broker.service.ServerCnxTest
Error:  testDuplicateConcurrentSubscribeCommand(org.apache.pulsar.broker.service.ServerCnxTest)  Time elapsed: 0.684 s  <<< FAILURE!
java.lang.AssertionError: Response is not CommandError but org.apache.pulsar.common.api.proto.CommandSuccess@2b7fae67 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertTrue(Assert.java:45)
	at org.apache.pulsar.broker.service.ServerCnxTest.testDuplicateConcurrentSubscribeCommand(ServerCnxTest.java:767)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by mattisonchao** [comment]
I want to fix this flaky test. : )

**Comment by lhotari** [comment]
A [recent failure](https://github.com/apache/pulsar/pull/11343/checks?check_run_id=3089235382#step:10:529).

**Comment by lhotari** [comment]
Another [recent failure](https://github.com/apache/pulsar/pull/11343/checks?check_run_id=3089235382#step:10:1299).

**Comment by lhotari** [comment]
@mattisonchao [Yet another recent failure](https://github.com/apache/pulsar/pull/11387/checks?check_run_id=3130780794#step:10:2056).

```
Thu, 22 Jul 2021 05:52:17 GMT
Error:  testDuplicateConcurrentSubscribeCommand(org.apache.pulsar.broker.service.ServerCnxTest)  Time elapsed: 10.626 s  <<< FAILURE!
Thu, 22 Jul 2021 05:52:17 GMT
org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in org.apache.pulsar.broker.service.ServerCnxTest Response is not CommandError but org.apache.pulsar.common.api.proto.CommandSuccess@7604884 expected [true] but found [false] within 10 seconds.
Thu, 22 Jul 2021 05:52:17 GMT
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
Thu, 22 Jul 2021 05:52:17 GMT
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
Thu, 22 Jul 2021 05:52:17 GMT
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
Thu, 22 Jul 2021 05:52:17 GMT
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
Thu, 22 Jul 2021 05:52:17 GMT
	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:679)
Thu, 22 Jul 2021 05:52:17 GMT
	at org.apache.pulsar.broker.service.ServerCnxTest.testDuplicateConcurrentSubscribeCommand(ServerCnxTest.java:779)
Thu, 22 Jul 2021 05:52:17 GMT
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Thu, 22 Jul 2021 05:52:17 GMT
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Thu, 22 Jul 2021 05:52:17 GMT
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Thu, 22 Jul 2021 05:52:17 GMT
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Thu, 22 Jul 2021 05:52:17 GMT
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
Thu, 22 Jul 2021 05:52:17 GMT
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
Thu, 22 Jul 2021 05:52:17 GMT
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
Thu, 22 Jul 2021 05:52:17 GMT
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
Thu, 22 Jul 2021 05:52:17 GMT
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Thu, 22 Jul 2021 05:52:17 GMT
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Thu, 22 Jul 2021 05:52:17 GMT
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Thu, 22 Jul 2021 05:52:17 GMT
	at java.base/java.lang.Thread.run(Thread.java:829)
Thu, 22 Jul 2021 05:52:17 GMT
Caused by: java.util.concurrent.TimeoutException
Thu, 22 Jul 2021 05:52:17 GMT
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
Thu, 22 Jul 2021 05:52:17 GMT
	at org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:101)
Thu, 22 Jul 2021 05:52:17 GMT
	at org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:81)
Thu, 22 Jul 2021 05:52:17 GMT
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:101)
Thu, 22 Jul 2021 05:52:17 GMT
	... 17 more
```

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.
