### ISSUE TITLE
Flaky-test: KeyValueSchemaTest.testKeyValueSchemaSeparatedEncoding

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#11054]
KeyValueSchemaTest is flaky. The testKeyValueSchemaSeparatedEncodingtest method fails sporadically.

[example failure](https://github.com/apache/pulsar/pull/11026/checks?check_run_id=2898206737#step:9:10391)

```
Error:  Tests run: 14, Failures: 1, Errors: 0, Skipped: 6, Time elapsed: 0.396 s <<< FAILURE! - in org.apache.pulsar.client.impl.schema.KeyValueSchemaTest
Error:  testKeyValueSchemaSeparatedEncoding(org.apache.pulsar.client.impl.schema.KeyValueSchemaTest)  Time elapsed: 0.008 s  <<< FAILURE!
java.lang.NullPointerException
	at org.apache.pulsar.client.impl.schema.AutoConsumeSchema.getSchema(AutoConsumeSchema.java:184)
	at org.apache.pulsar.client.impl.schema.KeyValueSchemaTest.testKeyValueSchemaSeparatedEncoding(KeyValueSchemaTest.java:402)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.
