### ISSUE TITLE
From v2.8.0, unable to use bookkeeper state storage component on pulsar local runner function :  Provider org.apache.pulsar.functions.runtime.shaded.io.grpc.netty.shaded.org.apache.pulsar.functions.runtime.shaded.io.grpc.netty.NettyChannelProvider not found

### ISSUE THREAD

**Issue by YannPerthuis** [apache/pulsar#11098]
**Describe the bug**
16:07:28.745 [public/default/LocalPulsarFunction-0] ERROR org.apache.pulsar.functions.instance.JavaInstanceRunnable - [public/default/LocalPulsarFunction:0] Uncaught exception in Java Instance
java.util.ServiceConfigurationError: org.apache.pulsar.functions.runtime.shaded.io.grpc.ManagedChannelProvider: Provider org.apache.pulsar.functions.runtime.shaded.io.grpc.netty.shaded.org.apache.pulsar.functions.runtime.shaded.io.grpc.netty.NettyChannelProvider not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:239) ~[?:1.8.0_292]
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185) ~[?:1.8.0_292]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372) ~[?:1.8.0_292]
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[?:1.8.0_292]
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[?:1.8.0_292]
	at org.apache.pulsar.functions.runtime.shaded.io.grpc.ServiceProviders.loadAll(ServiceProviders.java:67) ~[pulsar-functions-local-runner-2.8.0.jar:2.8.0]
	at org.apache.pulsar.functions.runtime.shaded.io.grpc.ServiceProviders.load(ServiceProviders.java:42) ~[pulsar-functions-local-runner-2.8.0.jar:2.8.0]
	at org.apache.pulsar.functions.runtime.shaded.io.grpc.ManagedChannelProvider.<clinit>(ManagedChannelProvider.java:42) ~[pulsar-functions-local-runner-2.8.0.jar:2.8.0]
	at org.apache.pulsar.functions.runtime.shaded.io.grpc.ManagedChannelBuilder.forTarget(ManagedChannelBuilder.java:76) ~[pulsar-functions-local-runner-2.8.0.jar:2.8.0]
	at org.apache.pulsar.functions.runtime.shaded.org.apache.bookkeeper.clients.utils.GrpcChannels.createChannelBuilder(GrpcChannels.java:66) ~[pulsar-functions-local-runner-2.8.0.jar:2.8.0]
	at org.apache.pulsar.functions.runtime.shaded.org.apache.bookkeeper.clients.SimpleClientBase.<init>(SimpleClientBase.java:58) ~[pulsar-functions-local-runner-2.8.0.jar:2.8.0]
	at org.apache.pulsar.functions.runtime.shaded.org.apache.bookkeeper.clients.admin.SimpleStorageAdminClientImpl.<init>(SimpleStorageAdminClientImpl.java:67) ~[pulsar-functions-local-runner-2.8.0.jar:2.8.0]
	at org.apache.pulsar.functions.instance.state.BKStateStoreProviderImpl.createStateTable(BKStateStoreProviderImpl.java:109) ~[pulsar-functions-local-runner-2.8.0.jar:2.8.0]
	at org.apache.pulsar.functions.instance.state.BKStateStoreProviderImpl.getStateStore(BKStateStoreProviderImpl.java:186) ~[pulsar-functions-local-runner-2.8.0.jar:2.8.0]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.setupStateStore(JavaInstanceRunnable.java:313) ~[pulsar-functions-local-runner-2.8.0.jar:2.8.0]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.setup(JavaInstanceRunnable.java:212) ~[pulsar-functions-local-runner-2.8.0.jar:2.8.0]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:243) [pulsar-functions-local-runner-2.8.0.jar:2.8.0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]

16:07:58.442 [public/default/LocalPulsarFunction-0] ERROR org.apache.pulsar.functions.instance.JavaInstanceRunnable - [public/default/LocalPulsarFunction:0] Uncaught exception in Java Instance
java.lang.NoClassDefFoundError: Could not initialize class org.apache.pulsar.functions.runtime.shaded.io.grpc.ManagedChannelProvider
	at org.apache.pulsar.functions.runtime.shaded.io.grpc.ManagedChannelBuilder.forTarget(ManagedChannelBuilder.java:76) ~[pulsar-functions-local-runner-2.8.0.jar:2.8.0]
	at org.apache.pulsar.functions.runtime.shaded.org.apache.bookkeeper.clients.utils.GrpcChannels.createChannelBuilder(GrpcChannels.java:66) ~[pulsar-functions-local-runner-2.8.0.jar:2.8.0]
	at org.apache.pulsar.functions.runtime.shaded.org.apache.bookkeeper.clients.SimpleClientBase.<init>(SimpleClientBase.java:58) ~[pulsar-functions-local-runner-2.8.0.jar:2.8.0]
	at org.apache.pulsar.functions.runtime.shaded.org.apache.bookkeeper.clients.admin.SimpleStorageAdminClientImpl.<init>(SimpleStorageAdminClientImpl.java:67) ~[pulsar-functions-local-runner-2.8.0.jar:2.8.0]
	at org.apache.pulsar.functions.instance.state.BKStateStoreProviderImpl.createStateTable(BKStateStoreProviderImpl.java:109) ~[pulsar-functions-local-runner-2.8.0.jar:2.8.0]
	at org.apache.pulsar.functions.instance.state.BKStateStoreProviderImpl.getStateStore(BKStateStoreProviderImpl.java:186) ~[pulsar-functions-local-runner-2.8.0.jar:2.8.0]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.setupStateStore(JavaInstanceRunnable.java:313) ~[pulsar-functions-local-runner-2.8.0.jar:2.8.0]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.setup(JavaInstanceRunnable.java:212) ~[pulsar-functions-local-runner-2.8.0.jar:2.8.0]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:243) [pulsar-functions-local-runner-2.8.0.jar:2.8.0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
16:07:58.442 [public/default/LocalPulsarFunction-0] INFO  org.apache.pulsar.functions.instance.JavaInstanceRunnable - Closing instance

**To Reproduce**
1. Enable bookkeeper storage feature in con/bookkeeper.conf 
extraServerComponents=org.apache.bookkeeper.stream.server.StreamStorageLifecycleComponent

2. Start a basic function with local runner that define a bookkeeper storate url :
```java
LocalRunner
    .builder()
    .stateStorageServiceUrl((String) functionConfig.getUserConfig().get("bk://localhost:4181")) // default bookkeeper url
    .functionConfig(functionConfig)
    .build()
    .start(true);
```

**Expected behavior**
Local runner does not throw those exceptions and the function can well deal-with state storage.

**Desktop**
- OS: macOs v11.2.3
- Gradle: v7.2
- Java: v8
- Pulsar: v2.8.0

**Additional context**
Its' works as expected up to pulsar 2.7.2, but not from 2.8.0 version

**Comment by YannPerthuis** [comment]
It's seems (I suppose) probably that is a broken fqn for the used NettyChannelProvider class. In my local, this class has this defined package: 'org.apache.pulsar.functions.runtime.shaded.io.grpc.netty' and the stack try to reach it from this package 'org.apache.pulsar.functions.runtime.shaded.io.grpc.netty.shaded.org.apache.pulsar.functions.runtime.shaded.io.grpc.netty'

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.
