### ISSUE TITLE
Can only specify option --broker-conf once

### ISSUE THREAD

**Issue by tuteng** [apache/pulsar#11205]
**Describe the bug**

**To Reproduce**

```
./bin/pulsar broker --broker-conf conf/broker-1.conf
2021-07-03 08:50:38,465 [sun.misc.Launcher$AppClassLoader@55f96302] error Uncaught exception in thread main: Can only specify option --broker-conf once.
com.beust.jcommander.ParameterException: Can only specify option --broker-conf once.
	at com.beust.jcommander.ParameterDescription.addValue(ParameterDescription.java:240)
	at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:913)
	at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:894)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:724)
	at com.beust.jcommander.JCommander.parse(JCommander.java:356)
	at com.beust.jcommander.JCommander.parse(JCommander.java:335)
	at org.apache.pulsar.PulsarBrokerStarter$BrokerStarter.<init>(PulsarBrokerStarter.java:143)
	at org.apache.pulsar.PulsarBrokerStarter.main(PulsarBrokerStarter.java:314)
```

**Expected behavior**
Support for specifying configuration files from the command line

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by murong00** [comment]
This is because this option `--broker-conf` is specified in the startup script `bin/pulsar` as below:
```
cd "$PULSAR_HOME"
if [ $COMMAND == "broker" ]; then
    PULSAR_LOG_FILE=${PULSAR_LOG_FILE:-"pulsar-broker.log"}
    exec $JAVA $LOG4J2_SHUTDOWN_HOOK_DISABLED $OPTS -Dpulsar.log.file=$PULSAR_LOG_FILE org.apache.pulsar.PulsarBrokerStarter --broker-conf $PULSAR_BROKER_CONF $@
```
we can just remove this option in `bin/pulsar` as a workaround since `PulsarBrokerStarter` will use the default `broker.conf` as below:
```
        @Parameter(names = {"-c", "--broker-conf"}, description = "Configuration file for Broker")
        private String brokerConfigFile =
                Paths.get("").toAbsolutePath().normalize().toString() + "/conf/broker.conf";
```

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
The proper way should be set `PULSAR_BROKER_CONF` env var instead. See also https://github.com/apache/pulsar-site/blob/7fe949f2e236e8da7ec72c3d8c675e60ba88374e/tools/pytools/lib/execute/pulsar_clidoc_generator.py#L45-L53 as a use case.

Closed as won't do.
