### ISSUE TITLE
Can not connect to topics

### ISSUE THREAD

**Issue by wenjun8888** [apache/pulsar#11260]
hey, i use pulsar based on version 2.6.0
once broker had an oom problem and soon shut down, after we restart the broker, we find our apps can not connect pulsar, it said:

```
[persistent://xxxxxx_fun/menu/xxxxxx-recombination-topic-partition-0] [null] Error connecting to broker: org.apache.pulsar.client.api.PulsarClientException$TimeoutException: 74 lookup request timedout after ms 3001
```

then we check with command "pulsar-admin topics list" and found that some topics can not display which return 500 internal error but the othders worked.

the log show :

```
16:42:12.605 [pulsar-web-42-8] ERROR org.apache.pulsar.broker.web.PulsarWebResource - **Finding owner for topic persistent://xxxxxx_test/menu/xxxxxx-systemOperLog-topic-partition-0 timed out**
java.util.concurrent.TimeoutException: null
        at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771) ~[?:1.8.0_112]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915) ~[?:1.8.0_112]
        at org.apache.pulsar.broker.namespace.NamespaceService.getWebServiceUrl(NamespaceService.java:215) ~[org.apache.pulsar-pulsar-broker-2.6.1.jar:2.6.1]
        at org.apache.pulsar.broker.web.PulsarWebResource.validateTopicOwnership(PulsarWebResource.java:599) ~[org.apache.pulsar-pulsar-broker-2.6.1.jar:2.6.1]
        at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.validateReadOperationOnTopic(PersistentTopicsBase.java:245) ~[org.apache.pulsar-pulsar-broker-2.6.1.jar:2.6.1]
        at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.internalGetSubscriptionsForNonPartitionedTopic(PersistentTopicsBase.java:881) ~[org.apache.pulsar-pulsar-broker-2.6.1.jar:2.6.
1]
        at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.internalGetSubscriptions(PersistentTopicsBase.java:832) ~[org.apache.pulsar-pulsar-broker-2.6.1.jar:2.6.1]
        at org.apache.pulsar.broker.admin.v2.PersistentTopics.getSubscriptions(PersistentTopics.java:461) ~[org.apache.pulsar-pulsar-broker-2.6.1.jar:2.6.1]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
```  

how can i fix it, thanks~

**Comment by frankjkelly** [comment]
@liangyepianzhou are there particular fixes in Pulsar `2.6.2` and above that might be helping this?

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closing as stale. If it's still relevant to maintained versions, feel free to open a new issue
