### ISSUE TITLE
Cannot use org.apache.avro.generic.GenericRecord  inside a Pulsar Sink (to manage GenericRecord.getNativeObject)

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#11274]
**Describe the bug**
In current master (2.9.0-SNAPSHOT and probably in 2.8.0) it is not possible to use  `org.apache.avro.generic.GenericRecord ` class in order to manipulate the returned object from `GenericRecord.getNativeRecord()`.

If I put the "avro" library inside the NAR file I see this error:

```
class org.apache.avro.generic.GenericData$Record cannot be cast to class org.apache.avro.generic.GenericRecord (org.apache.avro.generic.GenericData$Record is in unnamed module of loader java.net.URLClassLoader @5451c3a8; org.apache.avro.generic.GenericRecord is in unnamed module of loader org.apache.pulsar.common.nar.NarClassLoader @363f0ba0)
	at org.apache.pulsar.io.elasticsearch.ElasticSearchSink.extractJsonNode(ElasticSearchSink.java:284) ~[pulsar-io-elastic-search-2.9.0-SNAPSHOT.nar-unpacked/:?]
	at org.apache.pulsar.io.elasticsearch.ElasticSearchSink.stringifyValue(ElasticSearchSink.java:261) ~[pulsar-io-elastic-search-2.9.0-SNAPSHOT.nar-unpacked/:?]
	at org.apache.pulsar.io.elasticsearch.ElasticSearchSink.extractIdAndDocument(ElasticSearchSink.java:177) ~[pulsar-io-elastic-search-2.9.0-SNAPSHOT.nar-unpacked/:?]
	at org.apache.pulsar.io.elasticsearch.ElasticSearchSink.write(ElasticSearchSink.java:84) ~[pulsar-io-elastic-search-2.9.0-SNAPSHOT.nar-unpacked/:?]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.sendOutputMessage(JavaInstanceRunnable.java:355) [org.apache.pulsar-pulsar-functions-instance-2.9.0-SNAPSHOT.jar:2.9.0-SNAPSHOT]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.handleResult(JavaInstanceRunnable.java:338) [org.apache.pulsar-pulsar-functions-instance-2.9.0-SNAPSHOT.jar:2.9.0-SNAPSHOT]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:283) [org.apache.pulsar-pulsar-functions-instance-2.9.0-SNAPSHOT.jar:2.9.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:829) [?:?]
13:12:50.804 [public/default/test-sink-connector-elastic_search-PROCESS-name-fjpugexj-0] INFO  org.apache.pulsar.functions.instance.JavaInstanceRunnable 
```
If I do not put the AVRO library inside the NAR I see a ClassNotFound error.

**To Reproduce**
I see this problem in integration tests of this PR regarding changes in ElastichSearch Sink
https://github.com/apache/pulsar/pull/11263

**Expected behaviuor**
The Sink is able to manipulate AVRO native objects.

**Additional context**
Initially the ElasticSearch Sink patch was contributed before the 2.8.0 release, when we decided to change the contents of the class path for Functions/Sinks.
At that time we had the full pulsar-client-original and its dependencies (and thus AVRO) and it wasn't needed to add AVRO inside the NAR file.

As a system library probably it is better that it is in the classpath and the implementation loaded by Pulsar takes the precedence over any other jar file inside the nar file.
This is because the Sink must be able to access the results of GenericRecord.getNativeObject(), that can be a Native CRO Record or a Jackson JSON Node.

**Comment by eolivelli** [comment]
In order to make IT pass in the ElasticSearch Sink patch
I added AVRO to the Functions class path and now the test is passing.

https://github.com/apache/pulsar/pull/11263/files#diff-d6656e6646e3133b65fe303a84f70f1f410f3d1b80b3c64d42011cf86b6bab42R92

This is only a partial solution (it does not cover JsonNode and Protobuf Dynamic Descriptor)

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by eolivelli** [comment]
fixed by https://github.com/apache/pulsar/pull/11636
