### ISSUE TITLE
2.8.0 sink can no longer process batched records from Python producer

### ISSUE THREAD

**Issue by dmcarver** [apache/pulsar#11288]
**Describe the bug**
I have a simple Python producer that has been sending messages to Pulsar since 2.6.1 with `batching_enabled=True`. These messages are processed an instance of the built-in InfluxDB sink connector. Since upgrading to 2.8.0, I receive this warning and the records are not processed:

```
12:53:20.020 [pool-2-thread-1] WARN  org.apache.pulsar.io.influxdb.BatchSink - Record flush thread was exception
org.apache.pulsar.client.api.SchemaSerializationException: measurement is a required field.
        at org.apache.pulsar.io.influxdb.v1.InfluxDBGenericRecordSink.buildPoint(InfluxDBGenericRecordSink.java:55) ~[pulsar-io-influxdb-2.8.0.nar-unpacked/:?]
        at org.apache.pulsar.io.influxdb.v1.InfluxDBGenericRecordSink.buildPoint(InfluxDBGenericRecordSink.java:41) ~[pulsar-io-influxdb-2.8.0.nar-unpacked/:?]
        at org.apache.pulsar.io.influxdb.BatchSink.flush(BatchSink.java:85) ~[pulsar-io-influxdb-2.8.0.nar-unpacked/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_292]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_292]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_292]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```

My messages do have a simple schema required by the sink and `measurement` (as seen above) is defined and present in them. More importantly, messages sent with `batching_enabled=False` continue to work fine. 

I added some additional logging to the sink and was able to observe that when `batching_enabled=False`, records seen in `org.apache.pulsar.io.influxdb.BatchSink.flush()` are of class `GenericJsonRecord`, but when batching is set to True, they are of `GenericObjectWrapper`. In 2.7.x, they are `GenericJsonRecord` in both cases.

I also tested using Avro instead of JSON, with the same behavior.

**To Reproduce**
1. Create a simple Python producer:
```
from pulsar import Client
from pulsar.schema import JsonSchema, Record, String

class Test_Schema(Record):
    measurement = String(required=True)
    field1 = String()

client = Client('pulsar://localhost:6650')
producer = client.create_producer(topic='mytopic', schema=JsonSchema(Test_Schema), batching_enabled=True)
producer.send(Test_Schema(measurement='foo', field1='bar'))
```
2. Connect InfluxDB sink to 'mytopic' in localrun mode. I am using this config:
```
configs:
  influxdbUrl: "http://influxdb:8086"
  database: "mydb"
  consistencyLevel: "ONE"
  logLevel: "NONE"
  retentionPolicy: "autogen"
  batchTimeMs: 1000
  batchSize: 100
```
3. Run script

**Expected behavior**
No error generated. Message sent to InfluxDB and written to database.

**Additional context**
As mentioned, this same code works without issue on Pulsar 2.6.1 and 2.7.x. The Python client version does not seem to matter either (I tested using 2.6.1 and 2.8.0). It is only during the recent Pulsar upgrade to 2.8.0 that the batch processing no longer works.

**Comment by eolivelli** [comment]
GenericObjectWrapper is a generic wrapper for every message that is not a Structure (AVRO, JSON, Protobuf).
Can you please check the schema on the topic ?
The logs of the sink will show the Schema when the Consumer is connected.

**Comment by dmcarver** [comment]
If I start from a clean slate (new topic, new sink connector) and send data from the producer with `batching_enabled=True`, the schema isn't written to the logs. The only thing logged is the error above, even with the logging level for the connector set to FULL.

However, I can retrieve the schema with `bin/pulsar-admin schemas get mytopic`:

```
{
  "version": 0,
  "schemaInfo": {
    "name": "mytopic",
    "schema": {
      "name": "Test_Schema",
      "type": "record",
      "fields": [
        {
          "name": "field1",
          "type": [
            "null",
            "string"
          ]
        },
        {
          "name": "measurement",
          "type": "string"
        }
      ]
    },
    "type": "JSON",
    "properties": {}
  }
}
```

**Comment by eolivelli** [comment]
can you try to consume the topic with `bin/pulsar-client consume  -st auto_consume -s subscname TOPICNAME`

`-st auto_consume` means to use AutoConsumeSchema that is the magic schema that downloads the Schema and returns the GenericRecord implementations.

**Comment by dmcarver** [comment]
Running that against the existing topic, it does show the schema:

```
15:48:36.802 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.PulsarClientImpl - Configuring schema for topic
mytopic : {                                     
  "name": "public/default/mytopic",                   
  "schema": {           
    "name": "Test_Schema",
    "type": "record",         
    "fields": [       
      {                           
        "name": "field1",                          
        "type": [                                      
          "null",                
          "string"   
        ]                 
      },                                   
      {                             
        "name": "measurement",               
        "type": "string"    
      }                 
    ]                                                                                                                  
  },                                         
  "type": "JSON",                                                                                                      
  "properties": {}                                                                                                     
}                                                                                                                      
15:48:36.855 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.schema.AutoConsumeSchema - Configure topic schem
a for topic mytopic : {                                                                                                
 "name": "Test_Schema", 
 "type": "record",               
 "fields": [
  {                                                                                                                        "name": "field1",
   "type": [                                
    "null",                    
    "string"          
   ]                    
  },                           
  {                                                                                                                    
   "name": "measurement",                                                                                              
   "type": "string"        
  }                                                                                                                    
 ]                       
}                                                                                                                      
```

And upon producing a new event, it is consumed:
```
15:50:24.303 [pulsar-client-io-1-1] INFO  com.scurrilous.circe.checksum.Crc32cIntChecksum - SSE4.2 CRC32C provider initialized              
----- got message -----                     
key:[null], properties:[], content:{value={
 "measurement": "foo",
 "field1": "bar"        
}, type=class java.lang.String}
15:50:24.337 [main] INFO  org.apache.pulsar.client.impl.PulsarClientImpl - Client closing. URL: pulsar://localhost:6650/
15:50:24.345 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.ConsumerImpl - [mytopic] [subscname] Closed cons
umer                       
15:50:24.349 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.ClientCnx - [id: 0x08a0758f, L:/127.0.0.1:40948
! R:localhost/127.0.0.1:6650] Disconnected
15:50:24.353 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.ClientCnx - [id: 0xcaf87c1d, L:/127.0.0.1:40950
! R:localhost/127.0.0.1:6650] Disconnected                                                                              
15:50:26.371 [main] INFO  org.apache.pulsar.client.cli.PulsarClientTool - 1 messages successfully consumed
```

**Comment by eolivelli** [comment]
it is consumed as a `type=class java.lang.String`, not as a JSON object
this is consistent with seeing a GenericObjectWrapper (that is the wrapper for the java.lang.String)

**Comment by dmcarver** [comment]
I've been attempting o do some troubleshooting on this, and it seems that batched messages do not have the schema version set. Thus the logic in `org.apache.pulsar.client.impl.MessageImpl` to load the schema and deserialize fails. Specifically `getSchemaVersion()` returns null.

The schema itself does appear to be present; if I print it out in `receiveIndividualMessagesFromBatch()` from `org.apache.pulsar.client.impl.ConsumerImpl` I can see output like `AUTO_CONSUME({schemaVersion=,schemaType=BYTES}{schemaVersion=org.apache.pulsar.common.protocol.schema.LatestVersion@2922965a,schemaType=JSON})`. It's just the version that seems to be missing.

**Comment by eolivelli** [comment]
@congbobo184 @gaoran10 can you please take a look ?

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.
