### ISSUE TITLE
Flaky-test: RackAwareTest.testPlacement

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#11349]
RackAwareTest is flaky. The testPlacement test method fails sporadically.

[example failure](https://github.com/apache/pulsar/pull/11345/checks?check_run_id=3089005869#step:10:2090)

```
Error:  Tests run: 4, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 20.821 s <<< FAILURE! - in org.apache.pulsar.broker.service.RackAwareTest
Error:  testPlacement(org.apache.pulsar.broker.service.RackAwareTest)  Time elapsed: 3.237 s  <<< FAILURE!
java.lang.AssertionError: first bookie in rack 0 not included in ensemble expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertTrue(Assert.java:45)
	at org.apache.pulsar.broker.service.RackAwareTest.testPlacement(RackAwareTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by lhotari** [comment]
Another [recent failure](https://github.com/apache/pulsar/pull/11343/checks?check_run_id=3089235382#step:10:2099).

**Comment by lhotari** [comment]
I also took a look at the test. There's a problem in the RackAwareTest itself in setup and cleanup.

These are the required changes for fixing setup and cleaup:
```
public class RackAwareTest extends BkEnsemblesTestBase {

    private static final int NUM_BOOKIES = 6;
    private final List<BookieServer> bookies = new ArrayList<>();

    public RackAwareTest() {
        // Start bookies manually
        super(0);
    }

    @Override
    protected void configurePulsar(ServiceConfiguration config) throws Exception {
        // Start bookies with specific racks
        for (int i = 0; i < NUM_BOOKIES; i++) {
            File bkDataDir = Files.createTempDirectory("bk" + Integer.toString(i) + "test").toFile();
            ServerConfiguration conf = new ServerConfiguration();

            conf.setBookiePort(0);
            conf.setZkServers("127.0.0.1:" + bkEnsemble.getZookeeperPort());
            conf.setJournalDirName(bkDataDir.getPath());
            conf.setLedgerDirNames(new String[] { bkDataDir.getPath() });
            conf.setAllowLoopback(true);

            // Use different advertised addresses for each bookie, so we can place them in different
            // racks.
            // Eg: 1st bookie will be 10.0.0.1, 2nd 10.0.0.2 and so on
            String addr = String.format("10.0.0.%d", i + 1);
            conf.setAdvertisedAddress(addr);

            BookieServer bs = new BookieServer(conf, NullStatsLogger.INSTANCE, null);

            bs.start();
            bookies.add(bs);
        }
    }

    @Override
    protected void cleanup() throws Exception {
        super.cleanup();

        for (BookieServer bs : bookies) {
            bs.shutdown();
        }

        bookies.clear();
    }
```

(also adding `throws Exception` to `configurePulsar`)

With these changes, the test goes into a deadlock. There's some change in Zookeeper caching that seems to trigger the problem. It's probably caused [by the PIP-45 changes](https://github.com/apache/pulsar/pulls?q=is%3Apr+PIP-45).

**Comment by lhotari** [comment]
It looks like there are multiple thread-safety issues in org.apache.pulsar.zookeeper.ZkBookieRackAffinityMapping . It's not a dead lock that is happening. I can see the BookiesRackConfiguration data structure getting corrupted which causes an infinite loop. This can be reproduced by making the changes to RackAwareTest that were described in the previous comment.
