### ISSUE TITLE
Flaky-test: StreamingEntryReaderTests.testCanCancelReadEntryRequestAndResumeReading

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#11428]
StreamingEntryReaderTests is flaky. The testCanCancelReadEntryRequestAndResumeReading test method fails sporadically.

[example failure](https://github.com/apache/pulsar/pull/11407/checks?check_run_id=3130789624#step:10:392)

```
  Error:  testCanCancelReadEntryRequestAndResumeReading(org.apache.pulsar.broker.service.streamingdispatch.StreamingEntryReaderTests)  Time elapsed: 10.165 s  <<< FAILURE!
  org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in org.apache.pulsar.broker.service.streamingdispatch.StreamingEntryReaderTests that uses org.apache.pulsar.broker.service.streamingdispatch.StreamingEntryReader was not fulfilled within 10 seconds.
  	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
  	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
  	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
  	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
  	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:864)
  	at org.apache.pulsar.broker.service.streamingdispatch.StreamingEntryReaderTests.testCanCancelReadEntryRequestAndResumeReading(StreamingEntryReaderTests.java:323)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by codelipenghui** [comment]
Another one: https://github.com/apache/pulsar/runs/8029353543?check_suite_focus=true
