### ISSUE TITLE
keyCertChain required for servers

### ISSUE THREAD

**Issue by jeffschnellerEnvisa** [apache/pulsar#11456]
Upgraded from 2.5.2 to 2.8.0 using a standalone cluster/server.  Using config file from 2.5.2.   2.5.2 was running fine.

Getting the following error when starting 2.8.0.

```
java.lang.NullPointerException: keyCertChain required for servers
        at io.netty.util.internal.ObjectUtil.checkNotNull(ObjectUtil.java:33) ~[io.netty-netty-common-4.1.63.Final.jar:4.1.63.Final]
        at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:430) ~[io.netty-netty-handler-4.1.63.Final.jar:4.1.63.Final]
        at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:350) ~[io.netty-netty-handler-4.1.63.Final.jar:4.1.63.Final]
        at io.netty.handler.ssl.SslContextBuilder.forServer(SslContextBuilder.java:93) ~[io.netty-netty-handler-4.1.63.Final.jar:4.1.63.Final]
        at org.apache.pulsar.common.util.SecurityUtility.createNettySslContextForServer(SecurityUtility.java:279) ~[org.apache.pulsar-pulsar-common-2.8.0.jar:2.8.0]
        at org.apache.pulsar.common.util.NettyServerSslContextBuilder.update(NettyServerSslContextBuilder.java:57) ~[org.apache.pulsar-pulsar-common-2.8.0.jar:2.8.0]
        at org.apache.pulsar.common.util.NettyServerSslContextBuilder.update(NettyServerSslContextBuilder.java:31) ~[org.apache.pulsar-pulsar-common-2.8.0.jar:2.8.0]
        at org.apache.pulsar.common.util.SslContextAutoRefreshBuilder.get(SslContextAutoRefreshBuilder.java:79) ~[org.apache.pulsar-pulsar-common-2.8.0.jar:2.8.0]
        at org.apache.pulsar.broker.service.PulsarChannelInitializer.initChannel(PulsarChannelInitializer.java:114) ~[org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]
        at org.apache.pulsar.broker.service.PulsarChannelInitializer.initChannel(PulsarChannelInitializer.java:42) ~[org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]
```

**Comment by jeffschnellerEnvisa** [comment]
Figured out it was a System Administrator issue when installing.  Properties file from 2.5.2 was copied over to 2.8.0 properties file.  2.8.0 properties file had the same key file properties defined but were set to empty.  When properties file is read it uses the last property value defined which in our case is null even though the same property was defined at the top of the file.
