### ISSUE TITLE
[Python Client] Encode a struct schema object with None field

### ISSUE THREAD

**Issue by gaoran10** [apache/pulsar#11473]
**Describe the bug**

The Python client couldn't encode a struct schema object which has None fields.

**To Reproduce**

```
class User(Record):
        name = String()
        age = Integer()

user = User(name = 'jack', age = 18)
data1 = schema.encode(user) // this could work well

user2 = User(age = 20)
data2 = schema.encode(user2) // encounter  error
```

**error log**
```
user:  {'_required_default': False, '_default': None, '_required': False, 'name': 'jack', 'age': 18}
decodeUser:  {'_required_default': False, '_default': None, '_required': False, 'name': 'jack', 'age': 18}
user2:  {'_required_default': False, '_default': None, '_required': False, 'name': None, 'age': 20}
Traceback (most recent call last):
  File "/Volumes/shit/Workspaces/GitHubFork/pulsar/pulsar-client-cpp/python/schema_test.py", line 992, in <module>
    test.test()
  File "/Volumes/shit/Workspaces/GitHubFork/pulsar/pulsar-client-cpp/python/schema_test.py", line 985, in test
    decodeUser2 = schema.decode(data2)
  File "/Volumes/shit/Workspaces/GitHubFork/pulsar/pulsar-client-cpp/python/pulsar/schema/schema_avro.py", line 64, in decode
    return self._record_cls(**d)
  File "/Volumes/shit/Workspaces/GitHubFork/pulsar/pulsar-client-cpp/python/pulsar/schema/definition.py", line 74, in __init__
    self.__setattr__(k, kwargs[k])
  File "/Volumes/shit/Workspaces/GitHubFork/pulsar/pulsar-client-cpp/python/pulsar/schema/definition.py", line 117, in __setattr__
    value = field.validate_type(key, value)
  File "/Volumes/shit/Workspaces/GitHubFork/pulsar/pulsar-client-cpp/python/pulsar/schema/definition.py", line 290, in validate_type
    raise TypeError("Invalid type '%s' for field '%s'. Expected a string" % (t, name))
TypeError: Invalid type '<class 'NoneType'>' for field 'name'. Expected a string
```

**Expected behavior**

Encode and decode operations should work well.

**Comment by HugoPelletier** [comment]
There are 2 classes to modified to fix this issue. In both cases (Field and String), the method validate_type is ignoring the required keyword argument.

**Field class** (https://github.com/apache/pulsar/blob/master/pulsar-client-cpp/python/pulsar/schema/definition.py#L148)

```python
    def validate_type(self, name, val):
        if not val and not self._required:
            return self.default()

        if type(val) != self.python_type():
            raise TypeError("Invalid type '%s' for field '%s'. Expected: %s" % (type(val), name, self.python_type()))
        return val
 ```

**String class** (https://github.com/apache/pulsar/blob/master/pulsar-client-cpp/python/pulsar/schema/definition.py#L280)

```python
    def validate_type(self, name, val):
        t = type(val)

        if not val and not self._required:
            return self.default()

        if not (t is str or t.__name__ == 'unicode'):
            raise TypeError("Invalid type '%s' for field '%s'. Expected a string" % (t, name))
        return val

**Comment by gaoran10** [comment]
@HugoPelletier Thanks, are you interest to fix this issue?

**Comment by HugoPelletier** [comment]
@gaoran10 Yes
