### ISSUE TITLE
Pulsar 2.6: POST ​/namespaces​/{tenant}​/{namespace}​/autoTopicCreation

### ISSUE THREAD

**Issue by mfortman11** [apache/pulsar#11504]
-e -t "partitioned" options would not work together

$ bin/pulsar-admin namespaces set-auto-topic-creation -e -t "partitioned" ming-luo/newns
java.lang.NullPointerException
at org.apache.pulsar.admin.cli.CmdNamespaces$SetAutoTopicCreation.run(CmdNamespaces.java:503)
at org.apache.pulsar.admin.cli.CmdBase.run(CmdBase.java:76)
at org.apache.pulsar.admin.cli.PulsarAdminTool.run(PulsarAdminTool.java:246)
at org.apache.pulsar.admin.cli.PulsarAdminTool.main(PulsarAdminTool.java:288)

**Comment by liangyuanpeng** [comment]
```
[root@node123 apache-pulsar-2.8.0]# bin/pulsar-admin namespaces set-auto-topicreation -e -t "partitioned" public/default4
Expected a command, got set-auto-topicreation
```  

May shoule be `set-auto-topicreation ` and not ` set-auto-topic-creation`

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
