### ISSUE TITLE
brokerClientTlsEnabled break some admin API - 500 Error

### ISSUE THREAD

**Issue by mnit016** [apache/pulsar#11515]
**Describe the bug**
I have pulsar 2.7.1 using k8s in 2 regions, I created a cluster on each for replication, it connect to each other through ingress with tls. Pulsar doesn't enable tls. (Each cluster's ingress has difference tls key-pair.)
I can't get list of topics under namespace.

**Error Log**
org.apache.pulsar.broker.PulsarServerException: java.lang.NullPointerException
  at org.apache.pulsar.broker.PulsarService.getAdminClient(PulsarService.java:1101)
  at org.apache.pulsar.broker.admin.v2.NonPersistentTopics.getList(NonPersistentTopics.java:271)

**To Reproduce**
I reproduce this by 1 cluster: 3 zookeeper - 3 bookie - 3 broker - 3 proxy - 1 toolset.
1. Set brokerClientTlsEnabled=true
2. Set brokerClientTrustCertsFilePath=cert/file // assume this certFile is used to connect to other.
3. Start cluster then use the toolset with: bin/pulsar-admin topics list public/default

**Expected behavior**
While other API work as well (eg: bin/pulsar-admin namespaces topics public/default)
I just wonder if it may break something else which I not found yet?

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
