### ISSUE TITLE
Pulsar server non-tls ports are still listening when TLS in-transit encryption is enabled

### ISSUE THREAD

**Issue by yabinmeng** [apache/pulsar#11548]
**Describe the bug**
I'm testing out transport encryption using TLS by following the document instruction here:
https://pulsar.apache.org/docs/en/2.7.2/security-tls-transport/

I'm expecting that when TLS is enabled, when broker is starting up, only TLS ports (8443 and 6551) are listening. But it looks like non-TLS ports (8080 and 6650) are also enabled. See the command line output below:

```
$ sudo netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:2181            0.0.0.0:*               LISTEN      16109/java
tcp        0      0 0.0.0.0:9990            0.0.0.0:*               LISTEN      16109/java
tcp        0      0 0.0.0.0:8010            0.0.0.0:*               LISTEN      16109/java
tcp        0      0 0.0.0.0:3181            0.0.0.0:*               LISTEN      16676/java
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      17362/java
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      877/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      9105/sshd
tcp        0      0 0.0.0.0:6650            0.0.0.0:*               LISTEN      17362/java
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN      17362/java
tcp        0      0 0.0.0.0:6651            0.0.0.0:*               LISTEN      17362/java
tcp        0      0 0.0.0.0:8000            0.0.0.0:*               LISTEN      16676/java
```

The only broker configuration changes are those TLS related, as below.

```
$ diff conf/broker.conf ~/pulsar_config/broker.conf.orig
32c32
< brokerServicePortTls=6651
---
> brokerServicePortTls=
38c38
< webServicePortTls=8443
---
> webServicePortTls=
472c472
< tlsEnabled=true
---
> tlsEnabled=false
478c478
< tlsCertificateFilePath=/opt/pulsar/security/tls/broker.cert.pem
---
> tlsCertificateFilePath=
481c481
< tlsKeyFilePath=/opt/pulsar/security/tls/broker.key-pk8.pem
---
> tlsKeyFilePath=
487c487
< tlsTrustCertsFilePath=/opt/pulsar/security/tls/ca.cert.pem
---
> tlsTrustCertsFilePath=
```

**To Reproduce**
1. Download Pulsar 2.7.2 release tarball and extract it to a folder, e.g. /opt/pulsar
2. Create TLS certificates ( by following Pulsar doc: https://pulsar.apache.org/docs/en/2.7.2/security-tls-transport/#broker-configuration
> put the root certificate (ca.cert.pem), the broker key (broker.key-pk8.pem), and the broker certificate (broker.cert.pem) into a sub-folder of Pulsar install: /opt/pulsar/security/tls
3. Configure broker.conf, as below. 
```
brokerServicePort=6650
brokerServicePortTls=6651
webServicePort=8080
webServicePortTls=8443
tlsEnabled=true
tlsCertificateFilePath=/opt/pulsar/security/tls/broker.cert.pem
tlsKeyFilePath=/opt/pulsar/security/tls/broker.key-pk8.pem
tlsTrustCertsFilePath=/opt/pulsar/security/tls/ca.cert.pem
```
4. Restart Pulsar server and we'll see that Pulsar server is listening on all 4 ports (8080, 8443, 6650, and 6651).

I also tried explicitly removing non-TLS ports in the configuration file and only keep TLS ports, as below. 
```
brokerServicePort=
brokerServicePortTls=6651
webServicePort=
webServicePortTls=8443
tlsEnabled=true
tlsCertificateFilePath=/opt/pulsar/security/tls/broker.cert.pem
tlsKeyFilePath=/opt/pulsar/security/tls/broker.key-pk8.pem
tlsTrustCertsFilePath=/opt/pulsar/security/tls/ca.cert.pem
```

If I do so, I can't start broker. The error in **pulsar-broker-xxx.out** is as below:
```
[AppClassLoader@18b4aac2] info AspectJ Weaver Version 1.9.2 built on Wednesday Oct 24, 2018 at 15:43:33 GMT
[AppClassLoader@18b4aac2] info register classloader sun.misc.Launcher$AppClassLoader@18b4aac2
[AppClassLoader@18b4aac2] info using configuration file:/opt/pulsar/lib/org.apache.pulsar-pulsar-zookeeper-utils-2.7.2.jar!/META-INF/aop.xml
[AppClassLoader@18b4aac2] info using configuration file:/opt/pulsar/lib/org.apache.pulsar-pulsar-zookeeper-2.7.2.jar!/META-INF/aop.xml
[AppClassLoader@18b4aac2] info register aspect org.apache.pulsar.broker.zookeeper.aspectj.ClientCnxnAspect
[AppClassLoader@18b4aac2] info register aspect org.apache.pulsar.zookeeper.FinalRequestProcessorAspect
[AppClassLoader@18b4aac2] info register aspect org.apache.pulsar.zookeeper.ZooKeeperServerAspect
2021-08-03 08:56:33,926 [sun.misc.Launcher$AppClassLoader@18b4aac2] error Uncaught exception in thread main: No value present
```

**Expected behavior**
Only TLS ports (8443 and 6551) are listening. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Java: 1.8.0_292

**Additional context**
N/A

**Comment by eolivelli** [comment]
So your problem is that you cannot disable non TLS ports?

**Comment by lhotari** [comment]
@yabinmeng There's a PR #11681 to fix some issues. Most of the fixed issues in that PR apply to Pulsar Standalone.

Setting TLS only requires setting `brokerClientTlsEnabled=true` besides the configuration settings that you have enabled. With self-signed certificates you might have to specify `tlsAllowInsecureConnection=true` unless `brokerClientTlsEnabledWithKeyStore=true` with all required settings.

**Comment by yabinmeng** [comment]
@lhotari Thanks for looking into this.

In my testing, I only have one node. So I don't think `brokerClientTlsEnabled=true` and`brokerClientTlsEnabledWithKeyStore=true` matter because they're used for inter-broker communication.  Technically speaking, if I want to only expose TLS ports on a broker, then I should set `brokerClientTlsEnabledWithKeyStore=true`. But in my testing it really doesn't matter.

My previous testing exposed 2 issues which I believed you confirmed in #11681. 
1. When TLS is enabled, both non-TLS and TLS ports are all listening
2. Broker won't start If I only set TLS ports (brokerServicePortTls and webServicePortTls), but leave non-TLS ports (brokerServicePort and webServicePort) empty.

Anyway, I retested with `brokerClientTlsEnabled=true`  and `brokerClientTrustCertsFilePath=</path/to/root/ca/ceritificate>` (and other required TLS configuration as before), it is the same behavior:
* I have to explicitly set all four ports (6650, 6651, 8080, 8843) in order to start borker when TLS is enabled
* When borker is up, all 4 ports are in listening mode.

In the end, I don't think `brokerClientTlsEnabledWithKeyStore=true` matters if I use `brokerClientTrustCertsFilePath=</path/to/root/ca/ceritificate>` parameter.

**Comment by yabinmeng** [comment]
@lhotari I also tested this on Pulsar version 2.8.0. Here is what i got

1) I only explicitly set TLS ports (6651 and 8443) and leave non-TLS ports empty. The TLS settings are as below:
```
brokerServicePort=
brokerServicePortTls=6651
webServicePort=
webServicePortTls=8443
tlsCertificateFilePath=/opt/pulsar/security/tls/server/broker.cert.pem
tlsKeyFilePath=/opt/pulsar/security/tls/server/broker.key-pk8.pem
tlsTrustCertsFilePath=/opt/pulsar/security/tls/rootca/ca.cert.pem
brokerClientTlsEnabled=true
brokerClientTrustCertsFilePath=/opt/pulsar/security/tls/rootca/ca.cert.pem
```

When I start broker, I get the following error in broker.log file 
```
17:01:47.533 [main] ERROR org.apache.pulsar.functions.worker.PulsarWorkerService - Error Starting up in worker
java.lang.NullPointerException: null
        at org.apache.pulsar.client.admin.internal.PulsarAdminImpl.<init>(PulsarAdminImpl.java:189) ~[org.apache.pulsar-pulsar-client-admin-original-2.8.0.jar:2.8.0]
        at org.apache.pulsar.client.admin.internal.PulsarAdminBuilderImpl.build(PulsarAdminBuilderImpl.java:47) ~[org.apache.pulsar-pulsar-client-admin-original-2.8.0.jar:2.8.0]
        at org.apache.pulsar.functions.worker.WorkerUtils.getPulsarAdminClient(WorkerUtils.java:221) ~[org.apache.pulsar-pulsar-functions-worker-2.8.0.jar:2.8.0]
        at org.apache.pulsar.functions.worker.PulsarWorkerService$1.newPulsarAdmin(PulsarWorkerService.java:136) ~[org.apache.pulsar-pulsar-functions-worker-2.8.0.jar:2.8.0]
        at org.apache.pulsar.functions.worker.PulsarWorkerService.start(PulsarWorkerService.java:434) [org.apache.pulsar-pulsar-functions-worker-2.8.0.jar:2.8.0]
        at org.apache.pulsar.broker.PulsarService.startWorkerService(PulsarService.java:1490) [org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]
        at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:793) [org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]
        at org.apache.pulsar.PulsarBrokerStarter$BrokerStarter.start(PulsarBrokerStarter.java:259) [org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]
        at org.apache.pulsar.PulsarBrokerStarter.main(PulsarBrokerStarter.java:331) [org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]
17:01:47.539 [main] ERROR org.apache.pulsar.broker.PulsarService - Failed to start Pulsar service: java.lang.NullPointerException
java.lang.RuntimeException: java.lang.NullPointerException
        at org.apache.pulsar.functions.worker.PulsarWorkerService.start(PulsarWorkerService.java:571) ~[org.apache.pulsar-pulsar-functions-worker-2.8.0.jar:2.8.0]
        at org.apache.pulsar.broker.PulsarService.startWorkerService(PulsarService.java:1490) ~[org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]
        at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:793) [org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]
        at org.apache.pulsar.PulsarBrokerStarter$BrokerStarter.start(PulsarBrokerStarter.java:259) [org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]
        at org.apache.pulsar.PulsarBrokerStarter.main(PulsarBrokerStarter.java:331) [org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]
Caused by: java.lang.NullPointerException
        at org.apache.pulsar.client.admin.internal.PulsarAdminImpl.<init>(PulsarAdminImpl.java:189) ~[org.apache.pulsar-pulsar-client-admin-original-2.8.0.jar:2.8.0]
        at org.apache.pulsar.client.admin.internal.PulsarAdminBuilderImpl.build(PulsarAdminBuilderImpl.java:47) ~[org.apache.pulsar-pulsar-client-admin-original-2.8.0.jar:2.8.0]
        at org.apache.pulsar.functions.worker.WorkerUtils.getPulsarAdminClient(WorkerUtils.java:221) ~[org.apache.pulsar-pulsar-functions-worker-2.8.0.jar:2.8.0]
        at org.apache.pulsar.functions.worker.PulsarWorkerService$1.newPulsarAdmin(PulsarWorkerService.java:136) ~[org.apache.pulsar-pulsar-functions-worker-2.8.0.jar:2.8.0]
        at org.apache.pulsar.functions.worker.PulsarWorkerService.start(PulsarWorkerService.java:434) ~[org.apache.pulsar-pulsar-functions-worker-2.8.0.jar:2.8.0]
        ... 4 more
17:01:47.539 [main] ERROR org.apache.pulsar.PulsarBrokerStarter - Failed to start pulsar service.
org.apache.pulsar.broker.PulsarServerException: java.lang.RuntimeException: java.lang.NullPointerException
        at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:821) ~[org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]
        at org.apache.pulsar.PulsarBrokerStarter$BrokerStarter.start(PulsarBrokerStarter.java:259) ~[org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]
        at org.apache.pulsar.PulsarBrokerStarter.main(PulsarBrokerStarter.java:331) [org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
```

2) If I explicitly specify all 4 ports, the broker server is able to start. But again, the server is listening on all 4 ports, not ideal.  We should only listen on TLS ports.

**Comment by lhotari** [comment]
> @lhotari I also tested this on Pulsar version 2.8.0. Here is what i got

Thanks for testing this @yabinmeng . This problem is fixed by the PR. I assume that you are testing with Pulsar Standalone or with Pulsar that has Functions Worker as part of the broker. That will fail without the changes in #11681 . 
I was assuming that it might be possible to workaround the issues in a k8s deployment or when Functions worker is deployed separately from the broker.
