### ISSUE TITLE
Got exception java.lang.UnsupportedOperationException: MessageId is null。Using Reader 

### ISSUE THREAD

**Issue by gaozhangmin** [apache/pulsar#11604]
Using Reader interface to consume. Got error:
```
2021-08-07 02:53:28,255 WARN  org.apache.pulsar.client.impl.ClientCnx                      [] - [x,x,x.x/x.x.x.x] Got exception java.lang.UnsupportedOperationException: MessageId is null
	at org.apache.pulsar.client.impl.MessageIdImpl.compareTo(MessageIdImpl.java:204)
	at org.apache.pulsar.client.impl.MessageIdImpl.compareTo(MessageIdImpl.java:37)
	at org.apache.pulsar.client.impl.PersistentAcknowledgmentsGroupingTracker.isDuplicate(PersistentAcknowledgmentsGroupingTracker.java:121)
	at org.apache.pulsar.client.impl.ConsumerImpl.messageReceived(ConsumerImpl.java:1016)
	at org.apache.pulsar.client.impl.ClientCnx.handleMessage(ClientCnx.java:447)
	at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:186)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.apache.pulsar.shade.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at org.apache.pulsar.shade.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.apache.pulsar.shade.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at org.apache.pulsar.shade.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at org.apache.pulsar.shade.io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at org.apache.pulsar.shade.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at org.apache.pulsar.shade.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at org.apache.pulsar.shade.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
```
It seems that this error will cause reader would not ack message.
![image](https://user-images.githubusercontent.com/9278488/128705045-1f1f83ce-0fec-4d34-9e3b-a0677b955a85.png)

**Comment by leizhiyuan** [comment]
which version do you use？

this pr seems fixed it 

https://github.com/apache/pulsar/pull/10586

**Comment by leizhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2684384/128705475-9ea3ebf1-b5c2-470f-b6bc-41ebea06ae57.png)

They add a precheck for messageId

**Comment by gaozhangmin** [comment]
> which version do you use？
2.8.0

**Comment by leizhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2684384/128705973-f4ef264f-ff43-4b46-a2b4-672d3f1b2147.png)

maybe there is a concurrent bug。 


```
  if (lastCumulativeAck.messageId == null) {. // 1. is not null
            return false;
        }
        if (messageId.compareTo(lastCumulativeAck.messageId) <= 0) { //1.another thread change the messageId to null
            // Already included in a cumulative ack
            return true;
        } else {
            return pendingIndividualAcks.contains(messageId);
        }
```
