### ISSUE TITLE
NPE when getPreviousPosition

### ISSUE THREAD

**Issue by gaozhangmin** [apache/pulsar#11619]
```
11:35:36.317 [BookKeeperClientWorker-OrderedExecutor-11-0] ERROR org.apache.bookkeeper.common.util.SafeRunnable - Unexpected throwable caught
java.lang.NullPointerException: null
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.getPreviousPosition(ManagedLedgerImpl.java:3215) ~[org.apache.pulsar-managed-ledger-2.8.0.jar:2.8.0]
        at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl$7.operationComplete(ManagedCursorImpl.java:1060) ~[org.apache.pulsar-managed-ledger-2.8.0.jar:2.8.0]
        at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl$8.markDeleteComplete(ManagedCursorImpl.java:1123) ~[org.apache.pulsar-managed-ledger-2.8.0.jar:2.8.0]
        at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl$17.operationComplete(ManagedCursorImpl.java:1826) ~[org.apache.pulsar-managed-ledger-2.8.0.jar:2.8.0]
        at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.lambda$persistPositionToLedger$23(ManagedCursorImpl.java:2617) ~[org.apache.pulsar-managed-ledger-2.8.0.jar:2.8.0]
        at org.apache.bookkeeper.client.AsyncCallback$AddCallback.addCompleteWithLatency(AsyncCallback.java:92) ~[org.apache.bookkeeper-bookkeeper-server-4.14.1.jar:4.14.1]
        at org.apache.bookkeeper.client.PendingAddOp.submitCallback(PendingAddOp.java:431) ~[org.apache.bookkeeper-bookkeeper-server-4.14.1.jar:4.14.1]
        at org.apache.bookkeeper.client.LedgerHandle.sendAddSuccessCallbacks(LedgerHandle.java:1832) ~[org.apache.bookkeeper-bookkeeper-server-4.14.1.jar:4.14.1]
        at org.apache.bookkeeper.client.PendingAddOp.sendAddSuccessCallbacks(PendingAddOp.java:415) ~[org.apache.bookkeeper-bookkeeper-server-4.14.1.jar:4.14.1]
        at org.apache.bookkeeper.client.PendingAddOp.writeComplete(PendingAddOp.java:409) ~[org.apache.bookkeeper-bookkeeper-server-4.14.1.jar:4.14.1]
        at org.apache.bookkeeper.proto.PerChannelBookieClient$AddCompletion.writeComplete(PerChannelBookieClient.java:2151) ~[org.apache.bookkeeper-bookkeeper-server-4.14.1.jar:4.14.1]
        at org.apache.bookkeeper.proto.PerChannelBookieClient$AddCompletion.handleResponse(PerChannelBookieClient.java:2208) ~[org.apache.bookkeeper-bookkeeper-server-4.14.1.jar:4.14.1]
        at org.apache.bookkeeper.proto.PerChannelBookieClient$AddCompletion.handleV2Response(PerChannelBookieClient.java:2187) ~[org.apache.bookkeeper-bookkeeper-server-4.14.1.jar:4.14.1]
        at org.apache.bookkeeper.proto.PerChannelBookieClient$ReadV2ResponseCallback.safeRun(PerChannelBookieClient.java:1372) ~[org.apache.bookkeeper-bookkeeper-server-4.14.1.jar:4.14.1]
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [org.apache.bookkeeper-bookkeeper-common-4.14.1.jar:4.14.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.66.Final.jar:4.1.66.Final]
        at java.lang.Thread.run(Thread.java:834) [?:?]

```

**Comment by gaozhangmin** [comment]
Please assign to me. I will fix it
