### ISSUE TITLE
Flaky-test: ElasticSearchClientTests.testBulkRetry

### ISSUE THREAD

**Issue by Technoboy-** [apache/pulsar#11628]
ElasticSearchClientTests is flaky. The testBulkRetry test method fails sporadically.

[example failure](https://github.com/apache/pulsar/pull/11564/checks?check_run_id=3290485512)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
Error:  Tests run: 8, Failures: 1, Errors: 0, Skipped: 6, Time elapsed: 145.874 s <<< FAILURE! - in org.apache.pulsar.io.elasticsearch.ElasticSearchClientTests
Error:  testBulkRetry(org.apache.pulsar.io.elasticsearch.ElasticSearchClientTests)  Time elapsed: 1.162 s  <<< FAILURE!
java.lang.AssertionError: expected [2] but found [3]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:797)
	at org.testng.Assert.assertEquals(Assert.java:807)
	at org.apache.pulsar.io.elasticsearch.ElasticSearchClientTests.testBulkRetry(ElasticSearchClientTests.java:184)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:  org.apache.pulsar.io.elasticsearch.ElasticSearchClientTests.testBulkRetry(org.apache.pulsar.io.elasticsearch.ElasticSearchClientTests)
[INFO]   Run 1: PASS
Error:    Run 2: ElasticSearchClientTests.testBulkRetry:184 expected [2] but found [3]
[INFO] 
[INFO] 
Error:  Tests run: 49, Failures: 1, Errors: 0, Skipped: 5
</pre></code>
</details>

**Comment by Technoboy-** [comment]
Hi @eolivelli 
I take a look at the ElasticSearchClientTests#testBulkRetry, I think we may name every index randomly or delete index after each test . 
```
@Test
public void testBulkRetry() throws Exception {
     final String index = "indexbulktest" + final String index = "indexbulktest" + UUID.randomUUID().toString();
```

Or delete index :
```
@Test
public void testBulkRetry() throws Exception {
     final String index = "indexbulktest";
     ...
     client.deleteIndex(index);
```
Could you help give some ideas about this issue?

**Comment by lhotari** [comment]
another failure

```
Error:  Tests run: 8, Failures: 1, Errors: 0, Skipped: 6, Time elapsed: 134.905 s <<< FAILURE! - in org.apache.pulsar.io.elasticsearch.ElasticSearchClientTests
Error:  testBulkRetry(org.apache.pulsar.io.elasticsearch.ElasticSearchClientTests)  Time elapsed: 1.156 s  <<< FAILURE!
java.lang.AssertionError: expected [2] but found [3]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:797)
	at org.testng.Assert.assertEquals(Assert.java:807)
	at org.apache.pulsar.io.elasticsearch.ElasticSearchClientTests.testBulkRetry(ElasticSearchClientTests.java:184)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

at https://github.com/apache/pulsar/pull/11497/checks?check_run_id=3288037630#step:9:27002

testBulkBlocking is also flaky

```
Error:  Tests run: 8, Failures: 1, Errors: 0, Skipped: 7, Time elapsed: 93.14 s <<< FAILURE! - in org.apache.pulsar.io.elasticsearch.ElasticSearchClientTests
Error:  testBulkBlocking(org.apache.pulsar.io.elasticsearch.ElasticSearchClientTests)  Time elapsed: 10.239 s  <<< FAILURE!
org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in org.apache.pulsar.io.elasticsearch.ElasticSearchClientTests that uses org.apache.pulsar.io.elasticsearch.ElasticSearchClientTests$MockRecord, org.apache.pulsar.io.elasticsearch.ElasticSearchClientTests$MockRecordorg.apache.pulsar.io.elasticsearch.ElasticSearchClient expected [5] but found [4] within 10 seconds.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:679)
	at org.apache.pulsar.io.elasticsearch.ElasticSearchClientTests.testBulkBlocking(ElasticSearchClientTests.java:222)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.AssertionError: expected [5] but found [4]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.pulsar.io.elasticsearch.ElasticSearchClientTests.lambda$testBulkBlocking$5(ElasticSearchClientTests.java:223)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:222)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:209)
	... 4 more
```
in https://github.com/apache/pulsar/pull/11497/checks?check_run_id=3288037630#step:9:38776

PTAL @eolivelli @vroyer

**Comment by eolivelli** [comment]
I am working on a fix.

**Comment by vroyer** [comment]
I also look at that.

**Comment by eolivelli** [comment]
Thank you @vroyer  I have assigned the ticket to you

**Comment by lhotari** [comment]
ElasticSearchClientTests.testBulkRetry is failing frequently. @eolivelli @vroyer  any chance to reduce the flakiness?

[recent failure](https://github.com/apache/pulsar/pull/11843/checks?check_run_id=3464533950#step:8:14749)
```
Error:  Tests run: 8, Failures: 1, Errors: 0, Skipped: 6, Time elapsed: 168.237 s <<< FAILURE! - in org.apache.pulsar.io.elasticsearch.ElasticSearchClientTests
Error:  testBulkRetry(org.apache.pulsar.io.elasticsearch.ElasticSearchClientTests)  Time elapsed: 16.005 s  <<< FAILURE!
java.lang.AssertionError: expected [2] but found [3]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:797)
	at org.testng.Assert.assertEquals(Assert.java:807)
	at org.apache.pulsar.io.elasticsearch.ElasticSearchClientTests.testBulkRetry(ElasticSearchClientTests.java:207)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
