### ISSUE TITLE
Flaky-test: PersistentTopicsTest.testSetReplicatedSubscriptionStatus on branch-2.8

### ISSUE THREAD

**Issue by hangc0276** [apache/pulsar#11662]
### Bugs
On branch-2.8, the `PersistentTopicsTest.testSetReplicatedSubscriptionStatus` test always run failed

The stack
```
Error:  Tests run: 37, Failures: 6, Errors: 0, Skipped: 13, Time elapsed: 86.757 s <<< FAILURE! - in org.apache.pulsar.broker.admin.PersistentTopicsTest
Error:  testSetReplicatedSubscriptionStatus(org.apache.pulsar.broker.admin.PersistentTopicsTest)  Time elapsed: 10.112 s  <<< FAILURE!
Wanted but not invoked:
asyncResponse.resume(<Capturing argument>);
-> at org.apache.pulsar.broker.admin.PersistentTopicsTest.testSetReplicatedSubscriptionStatus(PersistentTopicsTest.java:807)

However, there was exactly 1 interaction with this mock:
asyncResponse.resume(
    org.apache.pulsar.broker.web.RestException: HTTP 500 Internal Server Error
);
-> at org.apache.pulsar.broker.admin.AdminResource.resumeAsyncResponseExceptionally(AdminResource.java:792)


	at org.apache.pulsar.broker.admin.PersistentTopicsTest.testSetReplicatedSubscriptionStatus(PersistentTopicsTest.java:807)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by hangc0276** [comment]
Addressed by #11661
