### ISSUE TITLE
Flaky-test: AdminApiTest.testGetPartitionedStatsInternal

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#11704]
AdminApiTest is flaky. The testGetPartitionedStatsInternal test method fails sporadically.

[example failure](https://github.com/apache/pulsar/pull/11697/checks?check_run_id=3363209858#step:10:1100)

```
Error:  testGetPartitionedStatsInternal(org.apache.pulsar.broker.admin.AdminApiTest)  Time elapsed: 1.189 s  <<< FAILURE!
java.lang.AssertionError: expected [{"metadata":{"partitions":2},"partitions":{"persistent://prop-xyz/ns1/my-topic6d7497f0-18ce-4b04-b90f-6dfd85e5e2cc-partition-0":{"entriesAddedCounter":0,"numberOfEntries":0,"totalSize":0,"currentLedgerEntries":0,"currentLedgerSize":0,"lastLedgerCreatedTimestamp":"2021-08-18T16:47:54.744Z","waitingCursorsCount":1,"pendingAddEntriesCount":0,"lastConfirmedEntry":"3:-1","state":"LedgerOpened","ledgers":[],"cursors":{"my-sub":{"markDeletePosition":"3:-1","readPosition":"3:0","waitingReadOp":true,"pendingReadOps":0,"messagesConsumedCounter":0,"cursorLedger":4,"cursorLedgerLastEntry":0,"individuallyDeletedMessages":"[]","lastLedgerSwitchTimestamp":"2021-08-18T16:47:54.748Z","state":"Open","numberOfEntriesSinceFirstNotAckedMessage":1,"totalNonContiguousDeletedMessagesRange":0,"subscriptionHavePendingRead":true,"subscriptionHavePendingReplayRead":false,"properties":{}}},"schemaLedgers":[],"compactedLedger":{"ledgerId":-1,"entries":-1,"size":-1,"offloaded":false,"underReplicated":false}},"persistent://prop-xyz/ns1/my-topic6d7497f0-18ce-4b04-b90f-6dfd85e5e2cc-partition-1":{"entriesAddedCounter":10,"numberOfEntries":10,"totalSize":430,"currentLedgerEntries":10,"currentLedgerSize":430,"lastLedgerCreatedTimestamp":"2021-08-18T16:47:54.757Z","waitingCursorsCount":1,"pendingAddEntriesCount":0,"lastConfirmedEntry":"5:9","state":"LedgerOpened","ledgers":[{"ledgerId":5,"entries":0,"size":0,"offloaded":false,"underReplicated":false}],"cursors":{"my-sub":{"markDeletePosition":"5:-1","readPosition":"5:10","waitingReadOp":true,"pendingReadOps":0,"messagesConsumedCounter":0,"cursorLedger":6,"cursorLedgerLastEntry":0,"individuallyDeletedMessages":"[]","lastLedgerSwitchTimestamp":"2021-08-18T16:47:54.761Z","state":"Open","numberOfEntriesSinceFirstNotAckedMessage":11,"totalNonContiguousDeletedMessagesRange":0,"subscriptionHavePendingRead":true,"subscriptionHavePendingReplayRead":false,"properties":{}}},"schemaLedgers":[],"compactedLedger":{"ledgerId":-1,"entries":-1,"size":-1,"offloaded":false,"underReplicated":false}}}}] but found [{"metadata":{"partitions":2},"partitions":{"persistent://prop-xyz/ns1/my-topic6d7497f0-18ce-4b04-b90f-6dfd85e5e2cc-partition-0":{"entriesAddedCounter":0,"numberOfEntries":0,"totalSize":0,"currentLedgerEntries":0,"currentLedgerSize":0,"lastLedgerCreatedTimestamp":"2021-08-18T16:47:54.744Z","waitingCursorsCount":1,"pendingAddEntriesCount":0,"lastConfirmedEntry":"3:-1","state":"LedgerOpened","ledgers":[{"ledgerId":3,"entries":0,"size":0,"offloaded":false,"underReplicated":false}],"cursors":{"my-sub":{"markDeletePosition":"3:-1","readPosition":"3:0","waitingReadOp":true,"pendingReadOps":0,"messagesConsumedCounter":0,"cursorLedger":4,"cursorLedgerLastEntry":0,"individuallyDeletedMessages":"[]","lastLedgerSwitchTimestamp":"2021-08-18T16:47:54.748Z","state":"Open","numberOfEntriesSinceFirstNotAckedMessage":1,"totalNonContiguousDeletedMessagesRange":0,"subscriptionHavePendingRead":true,"subscriptionHavePendingReplayRead":false,"properties":{}}},"schemaLedgers":[],"compactedLedger":{"ledgerId":-1,"entries":-1,"size":-1,"offloaded":false,"underReplicated":false}},"persistent://prop-xyz/ns1/my-topic6d7497f0-18ce-4b04-b90f-6dfd85e5e2cc-partition-1":{"entriesAddedCounter":10,"numberOfEntries":10,"totalSize":430,"currentLedgerEntries":10,"currentLedgerSize":430,"lastLedgerCreatedTimestamp":"2021-08-18T16:47:54.757Z","waitingCursorsCount":1,"pendingAddEntriesCount":0,"lastConfirmedEntry":"5:9","state":"LedgerOpened","ledgers":[{"ledgerId":5,"entries":0,"size":0,"offloaded":false,"underReplicated":false}],"cursors":{"my-sub":{"markDeletePosition":"5:-1","readPosition":"5:10","waitingReadOp":true,"pendingReadOps":0,"messagesConsumedCounter":0,"cursorLedger":6,"cursorLedgerLastEntry":0,"individuallyDeletedMessages":"[]","lastLedgerSwitchTimestamp":"2021-08-18T16:47:54.761Z","state":"Open","numberOfEntriesSinceFirstNotAckedMessage":11,"totalNonContiguousDeletedMessagesRange":0,"subscriptionHavePendingRead":true,"subscriptionHavePendingReplayRead":false,"properties":{}}},"schemaLedgers":[],"compactedLedger":{"ledgerId":-1,"entries":-1,"size":-1,"offloaded":false,"underReplicated":false}}}}]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:629)
	at org.testng.Assert.assertEquals(Assert.java:639)
	at org.apache.pulsar.broker.admin.AdminApiTest.testGetPartitionedStatsInternal(AdminApiTest.java:1158)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by lhotari** [comment]
[recent failure](https://github.com/apache/pulsar/runs/4724281539?check_suite_focus=true#step:9:383)
```
Error:  Tests run: 139, Failures: 34, Errors: 0, Skipped: 69, Time elapsed: 273.243 s <<< FAILURE! - in org.apache.pulsar.broker.admin.AdminApiTest
Error:  testGetPartitionedStatsInternal(org.apache.pulsar.broker.admin.AdminApiTest)  Time elapsed: 1.212 s  <<< FAILURE!
java.lang.AssertionError: expected [{"metadata":{"partitions":2},"partitions":{"persistent://prop-xyz/ns1/my-topicf4707dcd-c1de-41d5-892f-eba9fbe4a936-partition-0":{"entriesAddedCounter":10,"numberOfEntries":10,"totalSize":430,"currentLedgerEntries":10,"currentLedgerSize":430,"lastLedgerCreatedTimestamp":"2022-01-06T07:32:27.748Z","waitingCursorsCount":1,"pendingAddEntriesCount":0,"lastConfirmedEntry":"3:9","state":"LedgerOpened","ledgers":[],"cursors":{"my-sub":{"markDeletePosition":"3:-1","readPosition":"3:10","waitingReadOp":true,"pendingReadOps":0,"messagesConsumedCounter":0,"cursorLedger":6,"cursorLedgerLastEntry":0,"individuallyDeletedMessages":"[]","lastLedgerSwitchTimestamp":"2022-01-06T07:32:27.759Z","state":"Open","numberOfEntriesSinceFirstNotAckedMessage":11,"totalNonContiguousDeletedMessagesRange":0,"subscriptionHavePendingRead":true,"subscriptionHavePendingReplayRead":false,"properties":{}}},"schemaLedgers":[],"compactedLedger":{"ledgerId":-1,"entries":-1,"size":-1,"offloaded":false,"underReplicated":false}},"persistent://prop-xyz/ns1/my-topicf4707dcd-c1de-41d5-892f-eba9fbe4a936-partition-1":{"entriesAddedCounter":0,"numberOfEntries":0,"totalSize":0,"currentLedgerEntries":0,"currentLedgerSize":0,"lastLedgerCreatedTimestamp":"2022-01-06T07:32:27.748Z","waitingCursorsCount":1,"pendingAddEntriesCount":0,"lastConfirmedEntry":"4:-1","state":"LedgerOpened","ledgers":[{"ledgerId":4,"entries":0,"size":0,"offloaded":false,"underReplicated":false}],"cursors":{"my-sub":{"markDeletePosition":"4:-1","readPosition":"4:0","waitingReadOp":true,"pendingReadOps":0,"messagesConsumedCounter":0,"cursorLedger":5,"cursorLedgerLastEntry":0,"individuallyDeletedMessages":"[]","lastLedgerSwitchTimestamp":"2022-01-06T07:32:27.759Z","state":"Open","numberOfEntriesSinceFirstNotAckedMessage":1,"totalNonContiguousDeletedMessagesRange":0,"subscriptionHavePendingRead":true,"subscriptionHavePendingReplayRead":false,"properties":{}}},"schemaLedgers":[],"compactedLedger":{"ledgerId":-1,"entries":-1,"size":-1,"offloaded":false,"underReplicated":false}}}}] but found [{"metadata":{"partitions":2},"partitions":{"persistent://prop-xyz/ns1/my-topicf4707dcd-c1de-41d5-892f-eba9fbe4a936-partition-0":{"entriesAddedCounter":10,"numberOfEntries":10,"totalSize":430,"currentLedgerEntries":10,"currentLedgerSize":430,"lastLedgerCreatedTimestamp":"2022-01-06T07:32:27.748Z","waitingCursorsCount":1,"pendingAddEntriesCount":0,"lastConfirmedEntry":"3:9","state":"LedgerOpened","ledgers":[{"ledgerId":3,"entries":0,"size":0,"offloaded":false,"underReplicated":false}],"cursors":{"my-sub":{"markDeletePosition":"3:-1","readPosition":"3:10","waitingReadOp":true,"pendingReadOps":0,"messagesConsumedCounter":0,"cursorLedger":6,"cursorLedgerLastEntry":0,"individuallyDeletedMessages":"[]","lastLedgerSwitchTimestamp":"2022-01-06T07:32:27.759Z","state":"Open","numberOfEntriesSinceFirstNotAckedMessage":11,"totalNonContiguousDeletedMessagesRange":0,"subscriptionHavePendingRead":true,"subscriptionHavePendingReplayRead":false,"properties":{}}},"schemaLedgers":[],"compactedLedger":{"ledgerId":-1,"entries":-1,"size":-1,"offloaded":false,"underReplicated":false}},"persistent://prop-xyz/ns1/my-topicf4707dcd-c1de-41d5-892f-eba9fbe4a936-partition-1":{"entriesAddedCounter":0,"numberOfEntries":0,"totalSize":0,"currentLedgerEntries":0,"currentLedgerSize":0,"lastLedgerCreatedTimestamp":"2022-01-06T07:32:27.748Z","waitingCursorsCount":1,"pendingAddEntriesCount":0,"lastConfirmedEntry":"4:-1","state":"LedgerOpened","ledgers":[{"ledgerId":4,"entries":0,"size":0,"offloaded":false,"underReplicated":false}],"cursors":{"my-sub":{"markDeletePosition":"4:-1","readPosition":"4:0","waitingReadOp":true,"pendingReadOps":0,"messagesConsumedCounter":0,"cursorLedger":5,"cursorLedgerLastEntry":0,"individuallyDeletedMessages":"[]","lastLedgerSwitchTimestamp":"2022-01-06T07:32:27.759Z","state":"Open","numberOfEntriesSinceFirstNotAckedMessage":1,"totalNonContiguousDeletedMessagesRange":0,"subscriptionHavePendingRead":true,"subscriptionHavePendingReplayRead":false,"properties":{}}},"schemaLedgers":[],"compactedLedger":{"ledgerId":-1,"entries":-1,"size":-1,"offloaded":false,"underReplicated":false}}}}]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:629)
	at org.testng.Assert.assertEquals(Assert.java:639)
	at org.apache.pulsar.broker.admin.AdminApiTest.testGetPartitionedStatsInternal(AdminApiTest.java:1198)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by lhotari** [comment]
the diff of the above assertion error:
```
<         "ledgers": [],
---
>         "ledgers": [
>           {
>             "ledgerId": 3,
>             "entries": 0,
>             "size": 0,
>             "offloaded": false,
>             "underReplicated": false
>           }
>         ],
```

**Comment by shibd** [comment]
It's because of the wrong use of `CompletableFuture`, I submited pr, please take a look, thanks.

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by RobertIndie** [comment]
Still fail after https://github.com/apache/pulsar/pull/13656 merge:
https://github.com/apache/pulsar/runs/7126133660?check_suite_focus=true

Here is another PR to try to fix this issue: https://github.com/apache/pulsar/pull/16238
