### ISSUE TITLE
Custom conversions for Avro Specific Records are ignored

### ISSUE THREAD

**Issue by tonisojandu-sympower** [apache/pulsar#11819]
I think we found a bug in the Pulsar Java Client. You maybe aware of it or you may have already addressed it. When writing Avro Specific Records into Pulsar producer then it uses shaded Avro code. This means that when it reaches:
`org.apache.pulsar.shade.org.apache.avro.specific.SpecificDatumWriter.writeField(Object datum, Field f, Encoder out, Object state)`
```
at org.apache.pulsar.shade.org.apache.avro.specific.SpecificDatumWriter.writeField(SpecificDatumWriter.java:101)
at org.apache.pulsar.shade.org.apache.avro.reflect.ReflectDatumWriter.writeField(ReflectDatumWriter.java:184)
at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:210)
at org.apache.pulsar.shade.org.apache.avro.specific.SpecificDatumWriter.writeRecord(SpecificDatumWriter.java:83)
at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:131)
at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:83)
at org.apache.pulsar.shade.org.apache.avro.reflect.ReflectDatumWriter.write(ReflectDatumWriter.java:158)
at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:73)
at org.apache.pulsar.client.impl.schema.writer.AvroWriter.write(AvroWriter.java:53)
at org.apache.pulsar.client.impl.schema.AbstractStructSchema.encode(AbstractStructSchema.java:57)
at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.value(TypedMessageBuilderImpl.java:175)
at net.sympower.usernotification.disturbance.DisturbanceStartedUseCaseIT.disturbance(DisturbanceStartedUseCaseIT.kt:58)
```
it has a decision to make:
```
if (datum instanceof SpecificRecordBase) {
  Conversion<?> conversion = ((SpecificRecordBase)datum).getConversion(f.pos());
  Schema fieldSchema = f.schema();
  LogicalType logicalType = fieldSchema.getLogicalType();
  Object value = this.getData().getField(datum, f.name(), f.pos());
  if (conversion != null && logicalType != null) {
     value = this.convert(fieldSchema, logicalType, conversion, value);
  }
  this.writeWithoutConversion(fieldSchema, value, out);
} else {
  super.writeField(datum, f, out, state);
}
```
Since Specific Avro classes created by Avro code generators do not extend this shaded one:
`org.apache.pulsar.shade.org.apache.avro.specific.SpecificRecordBase`

It will end up taking the else path that serializes without special conversion logic provided by the Specific Avro record. We found out about it when we used our generated Avro class that had a field with `timestamp-millis` logical type (`long` in reality). Generator was able to turn it into an Instant on language level. Since the the generated custom conversion logic is ignored then in ends up serializing it as an `IndexedRecord` instead. This path cannot handle Instant class when it is returned the record.

We are not sure what the correct path is here. We got it working by just using Pulsar Admin Java Client. For some reason, for the latter,
`org.apache.pulsar.client.impl.schema.writer.AvroWriter` does not use the shaded `org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumWriter` but the official
`org.apache.avro.generic.GenericDatumWriter` . This might be some build-time  before/after shading order of operation thing. So if the shading is important, then this may be also a bug.

Some blame is maybe on the the code generator that generates `IndexRecord.get(int field)` method that does not do the immediate conversion, but I am not quite sure, if that would be by the Avro spec.
Our exception:

```
Caused by: java.lang.ClassCastException: class java.time.Instant cannot be cast to class java.lang.Number (java.time.Instant and java.lang.Number are in module java.base of loader 'bootstrap') in field startedAt
  at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumWriter.addClassCastMsg(GenericDatumWriter.java:191)
  at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:229)
  at org.apache.pulsar.shade.org.apache.avro.specific.SpecificDatumWriter.writeField(SpecificDatumWriter.java:101)
  at org.apache.pulsar.shade.org.apache.avro.reflect.ReflectDatumWriter.writeField(ReflectDatumWriter.java:184)
  at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:210)
  at org.apache.pulsar.shade.org.apache.avro.specific.SpecificDatumWriter.writeRecord(SpecificDatumWriter.java:83)
  at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:131)
  at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:83)
  at org.apache.pulsar.shade.org.apache.avro.reflect.ReflectDatumWriter.write(ReflectDatumWriter.java:158)
  at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:73)
  at org.apache.pulsar.client.impl.schema.writer.AvroWriter.write(AvroWriter.java:53)
  ... 93 more
Caused by: java.lang.ClassCastException: class java.time.Instant cannot be cast to class java.lang.Number (java.time.Instant and java.lang.Number are in module java.base of loader 'bootstrap')
  at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:160)
  at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:81)
  at org.apache.pulsar.shade.org.apache.avro.reflect.ReflectDatumWriter.write(ReflectDatumWriter.java:158)
  at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:221)
```

To reproduce:
1) using Avro Schema:
`src/main/avro/some-object.avsc`
```json
{
  "name": "SomeObject",
  "namespace": "test",
  "type": "record",
  "version": "1",
  "fields" : [
    {
      "name": "startedAt",
      "type": {
        "type":  "long",
        "logicalType": "timestamp-millis"
      }
    }
  ]
}
```
generate a class using Gradle plugin:
```kotlin
plugins {
  kotlin("jvm") version "1.5.21"
  kotlin("plugin.spring") version "1.5.21"
  id("com.github.davidmc24.gradle.plugin.avro") version "1.2.1"
}

dependencies {
  implementation("org.apache.avro:avro:1.10.2")
  implementation("com.github.davidmc24.gradle.plugin:gradle-avro-plugin:1.2.1")
  implementation("org.apache.pulsar:pulsar-client:2.8.0")
}
```
2) Send an instance of this object to a producer:
```kotlin
val producer = pulsarClient.newProducer(AvroSchema.of(SomeObject::class.java))
      .topic("some-topic")
      .create()
val someObject = SomeObject.newBuilder()
      .setStartedAt(Instant.now())
      .build()
producer.newMessage().value(someObject).send()
```

**Expected behaviour:**
Custom converters are used when sending Avro Specific Records

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by lhotari** [comment]
I have also added a generic workaround for Gradle Kotlin syntax builds:

```kotlin
    configurations {
        all {
            resolutionStrategy {
                eachDependency {
                    if ((requested.group == "org.apache.bookkeeper" || requested.group == "io.streamnative") &&
                        requested.name in listOf("circe-checksum", "cpu-affinity", "native-io")
                    ) {
                        // Workaround for invalid metadata for Bookkeeper dependencies which contain
                        // <packaging>nar</packaging> in pom.xml
                        artifactSelection {
                            selectArtifact("jar", null, null)
                        }
                    } else if (requested.name == "pulsar-client" || requested.name == "pulsar-client-all") {
                        // replace pulsar-client and pulsar-client-all with pulsar-client-original
                        useTarget("${requested.group}:pulsar-client-original:${requested.version}")
                    } else if (requested.name == "pulsar-client-admin") {
                        // replace pulsar-client-admin with pulsar-client-admin-original
                        useTarget("${requested.group}:pulsar-client-admin-original:${requested.version}")
                    }
                }
            }
        }
    }
```

this is also tested in https://github.com/lhotari/pulsar-issue-11819-repro . Since Pulsar client dependencies aren't shaded in this case, it is necessary to ensure that Netty dependencies are "aligned" (all using the same version) and that a recent Netty 4.1 version is used (4.1.116.Final is most recent at the moment). for example

```kotlin
dependencies {
   implementation(platform("io.netty:netty-bom:4.1.116.Final"))
}
```

@tonisojandu-sympower Do you have a chance to test this workaround for your use case?

**Comment by tonisojandu-sympower** [comment]
We used to use the unshaded Pulsar clients because of this issue but we had to stop doing so once we upgraded to Spring 3.x because there was a conflict with the Jersey HTTP client upgrade that came with Spring upgrade. This is when we forked the Pulsar client and unshaded the Avro from the client.

I tried it again to see if the issue had been resolved. However, it still seems to be there. The error is a bit obscure and confusing.

```
SpringPulsarOriginalConflictApplicationTests > contextLoads() FAILED
    java.lang.LinkageError: ClassCastException: attempting to castjar:file:/home/runner/.gradle/caches/modules-2/files-2.1/javax.ws.rs/javax.ws.rs-api/2.1.1/d3466bc9321fe84f268a1adb3b90373fc14b0eb5/javax.ws.rs-api-2.1.1.jar!/javax/ws/rs/client/ClientBuilder.class to jar:file:/home/runner/.gradle/caches/modules-2/files-2.1/javax.ws.rs/javax.ws.rs-api/2.1.1/d3466bc9321fe84f268a1adb3b90373fc14b0eb5/javax.ws.rs-api-2.1.1.jar!/javax/ws/rs/client/ClientBuilder.class
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:81)
        at org.apache.pulsar.client.admin.internal.PulsarAdminImpl.<init>(PulsarAdminImpl.java:142)
        at org.apache.pulsar.client.admin.internal.PulsarAdminBuilderImpl.build(PulsarAdminBuilderImpl.java:45)
        at net.sympower.spring_pulsar_original_conflict.SpringPulsarOriginalConflictApplicationTests.contextLoads(SpringPulsarOriginalConflictApplicationTests.kt:19)
```

Based on some googling and seeing that there are javax/jakarta `.withConfig(httpConfig)` for `ClientBuilder` when I browse `PulsarAdminImpl` with my IDE, I guess that it is still the same problem. 

I created [a repository to demonstrate this issue](https://github.com/tonisojandu-sympower/spring-pulsar-original-conflict) and 
[here is the error itself](https://github.com/tonisojandu-sympower/spring-pulsar-original-conflict/actions/runs/13051328059/job/36412066651#step:4:2247).


Something else interesting I discovered when I tried to recreate the Avro logical type serialization issue in my testbed is that `pulsar-client-admin` does not shade Avro classes, so due to classpath race between the regular client and the admin client, this issue did not manifest when admin was classpath.

Here is what the Pulsar `AvroWriter` references in the shaded Admin client:
```
javap -c ./pulsar-client-admin-4.0.2.jar-out/org/apache/pulsar/client/impl/schema/writer/AvroWriter.class | grep avro
  public org.apache.pulsar.client.impl.schema.writer.AvroWriter(org.apache.avro.Schema);
       3: invokespecial #21                 // Method "<init>":(Lorg/apache/avro/Schema;Z)V
  public org.apache.pulsar.client.impl.schema.writer.AvroWriter(org.apache.avro.Schema, boolean);
      16: invokestatic  #40                 // Method org/apache/avro/io/EncoderFactory.get:()Lorg/apache/avro/io/EncoderFactory;
      24: invokevirtual #44                 // Method org/apache/avro/io/EncoderFactory.binaryEncoder:(Ljava/io/OutputStream;Lorg/apache/avro/io/BinaryEncoder;)Lorg/apache/avro/io/BinaryEncoder;
      27: putfield      #46                 // Field encoder:Lorg/apache/avro/io/BinaryEncoder;
      30: new           #48                 // class org/apache/avro/reflect/ReflectData
      34: invokespecial #49                 // Method org/apache/avro/reflect/ReflectData."<init>":()V
      40: invokestatic  #55                 // Method org/apache/pulsar/client/impl/schema/AvroSchema.addLogicalTypeConversions:(Lorg/apache/avro/reflect/ReflectData;Z)V
      44: new           #57                 // class org/apache/avro/reflect/ReflectDatumWriter
      50: invokespecial #60                 // Method org/apache/avro/reflect/ReflectDatumWriter."<init>":(Lorg/apache/avro/Schema;Lorg/apache/avro/reflect/ReflectData;)V
      53: putfield      #62                 // Field writer:Lorg/apache/avro/reflect/ReflectDatumWriter;
  public org.apache.avro.io.BinaryEncoder getEncoder();
       1: getfield      #46                 // Field encoder:Lorg/apache/avro/io/BinaryEncoder;
       3: getfield      #62                 // Field writer:Lorg/apache/avro/reflect/ReflectDatumWriter;
       8: getfield      #46                 // Field encoder:Lorg/apache/avro/io/BinaryEncoder;
      11: invokevirtual #77                 // Method org/apache/avro/reflect/ReflectDatumWriter.write:(Ljava/lang/Object;Lorg/apache/avro/io/Encoder;)V
      15: getfield      #46                 // Field encoder:Lorg/apache/avro/io/BinaryEncoder;
      18: invokevirtual #82                 // Method org/apache/avro/io/BinaryEncoder.flush:()V
      65: getfield      #46                 // Field encoder:Lorg/apache/avro/io/BinaryEncoder;
      68: invokevirtual #82                 // Method org/apache/avro/io/BinaryEncoder.flush:()V
```

**Comment by tonisojandu-sympower** [comment]
This is not a pretty suggestion for a solution, but `org.apache.pulsar.client.impl.schema.writer.AvroWriter.write` could check with Java reflection if the `message` object class extends non-shaded `SpecificRecordBase` (or any other Avro) class. If so, then it could assume that Avro libraries are on the classpath and try to invoke non-shaded `org.apache.avro.reflect.ReflectDatumWriter` via reflection instead. If it fails because regular Avro is not on the classpath, then it could fall back to the shaded branch. 

It would likely need some resolution caching for performance reasons.

**Comment by lhotari** [comment]
> This is not a pretty suggestion for a solution, but `org.apache.pulsar.client.impl.schema.writer.AvroWriter.write` could check with Java reflection if the `message` object class extends non-shaded `SpecificRecordBase` (or any other Avro) class. If so, then it could assume that Avro libraries are on the classpath and try to invoke non-shaded `org.apache.avro.reflect.ReflectDatumWriter` via reflection instead. If it fails because regular Avro is not on the classpath, then it could fall back to the shaded branch.
> 
> It would likely need some resolution caching for performance reasons.

This could be a solution if there's no way to use the unshaded client. One of the future changes would be to exclude Avro from shading in the shaded client. This is the approach that was taken for Protobuf library in https://github.com/apache/pulsar/pull/23468 .

**Comment by tonisojandu-sympower** [comment]
When combining unshaded client and shaded admin client I started getting really weird exception
```
Caused by: java.lang.NoSuchMethodError: 'io.netty.channel.EventLoopGroup org.apache.pulsar.common.util.netty.EventLoopUtil.newEventLoopGroup(int, boolean, java.util.concurrent.ThreadFactory)'
	at org.apache.pulsar.client.impl.PulsarClientImpl.getEventLoopGroup(PulsarClientImpl.java:1251)
	at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:216)
	at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:166)
	at org.apache.pulsar.client.impl.ClientBuilderImpl.build(ClientBuilderImpl.java:70)
```
These do not make much sense, since `pulsar-common` was present in the classpath but maybe there is a obscure class race problem somewhere.

However, as a workaround using the shaded admin client for everything seems to work for us as well, since it does not shade Avro. As long as this stays so, we can get around this problem.
