### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.pulsar.broker.ServiceConfigurationUtils.getAppliedAdvertisedAddress(Lorg/apache/pulsar/broker/ServiceConfiguration;Z)Ljava/lang/String;

### ISSUE THREAD

**Issue by beyondyinjl2** [apache/pulsar#11857]
apache-pulsar-2.8.0/protocols/
2 versions
pulsar-protocol-handler-mqtt-2.9.0-SNAPSHOT.nar
pulsar-protocol-handler-mqtt-2.8.0.8.nar

vim conf/standalone.conf
messagingProtocols=mqtt
protocolHandlerDirectory=./protocols
brokerServicePort=6651
mqttListeners=mqtt://127.0.0.1:1883
advertisedAddress=127.0.0.1

mqttProxyEnable=true
mqttProxyPort=5682

bin/pulsar-daemon start broker

11:39:29.712 [main] ERROR org.apache.pulsar.PulsarBrokerStarter - Failed to start pulsar service.
java.lang.NoSuchMethodError: org.apache.pulsar.broker.ServiceConfigurationUtils.getAppliedAdvertisedAddress(Lorg/apache/pulsar/broker/ServiceConfiguration;Z)Ljava/lang/String;
        at io.streamnative.pulsar.handlers.mqtt.MQTTProtocolHandler.start(MQTTProtocolHandler.java:103) ~[?:?]
        at org.apache.pulsar.broker.protocol.ProtocolHandlerWithClassLoader.start(ProtocolHandlerWithClassLoader.java:66) ~[org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]
        at org.apache.pulsar.broker.protocol.ProtocolHandlers.lambda$start$4(ProtocolHandlers.java:142) ~[org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_191]
        at org.apache.pulsar.broker.protocol.ProtocolHandlers.start(ProtocolHandlers.java:142) ~[org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]
        at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:785) ~[org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]
        at org.apache.pulsar.PulsarBrokerStarter$BrokerStarter.start(PulsarBrokerStarter.java:259) ~[org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]
        at org.apache.pulsar.PulsarBrokerStarter.main(PulsarBrokerStarter.java:331) [org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]

**Comment by BewareMyPower** [comment]
It's because Pulsar side has some API changes from 2.8.0. You can use StreamNative Pulsar, for example, your MoP version is 2.8.0.8, you can use [StreamNative Pulsar 2.8.0.8](https://github.com/streamnative/pulsar/releases/tag/v2.8.0.8).

**Comment by liangyuanpeng** [comment]
Duplicate https://github.com/streamnative/mop/issues/86 

>  It's because Pulsar side has some API changes from 2.8.0. You can use StreamNative Pulsar, for example, your MoP version is 2.8.0.8, you can use StreamNative Pulsar 2.8.0.8.
 
Thanks for your reply,

**Comment by beyondyinjl2** [comment]
Thank you very much, 2.8.0.8 can be used
