### ISSUE TITLE
topic: persisten://public/default/my-topic/# This format defines an error

### ISSUE THREAD

**Issue by beyondyinjl2** [apache/pulsar#11860]
subscribe topic persisten://public/default/my-topic/# and persisten://public/default/my/+/topic and persisten://public/default/aaa/bbb/topic Report all errors

What are the definition rules of topic, like mqtt protocol, this kind of topic is supported

**Comment by liangyuanpeng** [comment]
What's error message?

**Comment by beyondyinjl2** [comment]
code:
PulsarClient client = PulsarClient.builder()
                .serviceUrl("pulsar://192.168.146.17:6650,192.168.146.18:6650,192.168.146.19:6650")
            .authentication(AuthenticationFactory.token("eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiJ9.OhQ8GtHiF4_oB7j_0Lzf8eTHhxJYfTeKg8t2aKxOuUQ"))
 .build();

        Producer<String> stringProducer = client.newProducer(Schema.STRING)
                .topic("persistent://public/default/my-topic/#")
  .create();
        stringProducer.send("aaaaaaaa11111");

error:
[pulsar-client-io-1-1] WARN org.apache.pulsar.client.impl.BinaryProtoLookupService - [persistent://public/default/my-topic/#] failed to send lookup request : org.apache.pulsar.broker.web.RestException: Cluster does not exist: cluster=default
[pulsar-client-io-1-1] WARN org.apache.pulsar.client.impl.ConnectionHandler - [persistent://public/default/my-topic/#] [null] Error connecting to broker: org.apache.pulsar.client.api.PulsarClientException$LookupException: org.apache.pulsar.broker.web.RestException: Cluster does not exist: cluster=default
[pulsar-client-io-1-1] INFO org.apache.pulsar.client.impl.ProducerImpl - [persistent://public/default/my-topic/#] Producer creation failed for producer 0 after producerTimeout
Exception in thread "main" [pulsar-client-io-1-1] INFO org.apache.pulsar.client.impl.ClientCnx - [id: 0xcee4b859, L:/192.168.3.155:59645 ! R:/192.168.146.19:6650] Disconnected
org.apache.pulsar.client.api.PulsarClientException$LookupException: org.apache.pulsar.broker.web.RestException: Cluster does not exist: cluster=default
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:971)
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:95)
	at com.talkweb.iot.test.TestPulsar22.main(TestPulsar22.java:34)

**Comment by leizhiyuan** [comment]
Cluster does not exist: cluster=default

When you start a local standalone cluster, a public/default namespace is created automatically. The namespace is used for development purposes. All Pulsar topics are managed within namespaces. For more information, see Topics.

maybe you need to create the  namespace first?

**Comment by leizhiyuan** [comment]
try to list the namespace of public

```
bin/pulsar-admin namespaces list public
```

**Comment by codelipenghui** [comment]
@beyondyinjl2 Pulsar does not support the MQTT topic name filters and the local topic name of Pulsar can't with `/`, We have done some topic name mapping on MoP https://github.com/streamnative/mop#topic-names--filters, maybe can help you.

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closed as answered. The Pulsar protocol itself need not to be compatible with MQTT. You can try out MoP.
