### ISSUE TITLE
Need docs for building pulsar from source and run on windows

### ISSUE THREAD

**Issue by tuhao1020** [apache/pulsar#11911]
I have exec `mvn clean install -DskipTests` on windows, but `bin/pulsar` is still a shell script for linux.
What is the right way to build and run it on windows?

**Comment by tuhao1020** [comment]
I changed some code in  `bin/pulsar` and use a bash environment to run it,  then got some errors:

```
 ERROR org.apache.bookkeeper.clients.impl.internal.RootRangeClientImplWithRetries - Reason for the failure {}
io.grpc.StatusRuntimeException: NOT_FOUND
        at io.grpc.StatusRuntimeException.fillInStackTrace(StatusRuntimeException.java:68) ~[io.grpc-grpc-api-1.33.0.jar:1.33.0]
        at io.grpc.StatusRuntimeException.<init>(StatusRuntimeException.java:58) ~[io.grpc-grpc-api-1.33.0.jar:1.33.0]
        at io.grpc.StatusRuntimeException.<init>(StatusRuntimeException.java:50) ~[io.grpc-grpc-api-1.33.0.jar:1.33.0]
        at io.grpc.Status.asRuntimeException(Status.java:533) ~[io.grpc-grpc-api-1.33.0.jar:1.33.0]
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533) ~[io.grpc-grpc-stub-1.33.0.jar:1.33.0]
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:616) ~[io.grpc-grpc-core-1.33.0.jar:1.33.0]
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:69) ~[io.grpc-grpc-core-1.33.0.jar:1.33.0]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:802) ~[io.grpc-grpc-core-1.33.0.jar:1.33.0]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:781) ~[io.grpc-grpc-core-1.33.0.jar:1.33.0]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[io.grpc-grpc-core-1.33.0.jar:1.33.0]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[io.grpc-grpc-core-1.33.0.jar:1.33.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_275]
        at java.lang.Thread.run(Thread.java:823) [?:1.8.0_275]
......

ERROR org.apache.pulsar.common.stats.JvmG1GCMetricsLogger - Failed to collect GC stats: java.lang:type=GarbageCollector,name=G1 Young Generation
```

**Comment by tuhao1020** [comment]
same issue: #11926

**Comment by BewareMyPower** [comment]
```
 ERROR org.apache.bookkeeper.clients.impl.internal.RootRangeClientImplWithRetries - Reason for the failure {}
io.grpc.StatusRuntimeException: NOT_FOUND
```

You can ignore this error.

**Comment by tuhao1020** [comment]
Is the `Failed to collect GC stats` error serious? 
Are there any plans to provide official scripts on Windows? @BewareMyPower

**Comment by BewareMyPower** [comment]
> Is the Failed to collect GC stats error serious?
It's not reproducible in my env (macOS). But it's not a serious for standalone mode because Pulsar standalone is mainly for tests.

> Are there any plans to provide official scripts on Windows?
AFAIK the answer is no.

**Comment by Anonymitaet** [comment]
@BewareMyPower thanks for helping on this issue! I see you answered this question 9 months ago, is that still true now? If yes, this issue can be closed.
