### ISSUE TITLE
pulsar client meet IndexOutOfBoundsException error

### ISSUE THREAD

**Issue by yakir-Yang** [apache/pulsar#11930]
pulsar client keep got IndexOutOfBoundsException error, and we can't fix up this issue by reboot the pulsar cluster.

Seems like some record data have some problem, need some help to figure out what happened.

2021-09-06 14:01:07.354  WARN [,,] 1 --- [] [-client-io-10-1] o.a.p.c.i.ClientCnx                      [exceptionCaught,269] : [10.150.65.133/10.150.65.133:6650] Got exception java.lang.IndexOutOfBoundsException: readerIndex(81339) + length(4) exceeds writerIndex(81339): PooledUnsafeDirectByteBuf(ridx: 81339, widx: 81339, cap: 81339/81339)
 at org.apache.pulsar.shade.io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1477)
 at org.apache.pulsar.shade.io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:810)
 at org.apache.pulsar.shade.io.netty.buffer.AbstractByteBuf.readUnsignedInt(AbstractByteBuf.java:826)
 at org.apache.pulsar.common.protocol.Commands.deSerializeSingleMessageInBatch(Commands.java:2059)
 at org.apache.pulsar.client.impl.ConsumerImpl.receiveIndividualMessagesFromBatch(ConsumerImpl.java:1419)
 at org.apache.pulsar.client.impl.ConsumerImpl.messageReceived(ConsumerImpl.java:1216)
 at org.apache.pulsar.client.impl.ClientCnx.handleMessage(ClientCnx.java:405)
 at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:198)
 at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
 at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
 at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
 at org.apache.pulsar.shade.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
 at org.apache.pulsar.shade.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
 at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
 at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
 at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
 at org.apache.pulsar.shade.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
 at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
 at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
 at org.apache.pulsar.shade.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
 at org.apache.pulsar.shade.io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
 at org.apache.pulsar.shade.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
 at org.apache.pulsar.shade.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
 at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
 at org.apache.pulsar.shade.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
 at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 at java.lang.Thread.run(Thread.java:748)

2021-09-06 14:01:07.358  INFO [,,] 1 --- [] [-client-io-10-1] o.a.p.c.i.ClientCnx                      [channelInactive,237] : [id: 0x9ac4a5a9, L:/10.42.4.29:45840 ! R:10.150.65.133/10.150.65.133:6650] Disconnected
2021-09-06 14:01:07.359  INFO [,,] 1 --- [] [-client-io-10-1] o.a.p.c.i.ConnectionHandler              [connectionClosed,123] : [persistent://edge-prod-metro/welink/alarm] [prod-edge-thing-alarm-convert:line18-hengli] Closed connection [id: 0x9ac4a5a9, L:/10.42.4.29:45840 ! R:10.150.65.133/10.150.65.133:6650] -- Will try again in 0.1 s
2021-09-06 14:01:07.359  INFO [,,] 1 --- [] [-client-io-10-1] o.a.p.c.i.ConnectionHandler              [connectionClosed,123] : [persistent://edge-prod-metro/welink/alarm] [prod-edge-thing-alarm-convert:line18-hengli] Closed connection [id: 0x9ac4a5a9, L:/10.42.4.29:45840 ! R:10.150.65.133/10.150.65.133:6650] -- Will try again in 0.1 s

**Comment by codelipenghui** [comment]
@yakir-Yang Could you please provide more context such as which Pulsar version are you using? And does the producer side also use the Java Client(Which version)? I noticed the client failed with `deSerializeSingleMessageInBatch`, it might related to the batch message serialization

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
