### ISSUE TITLE
Flaky-test: ManagedLedgerTest.testMaximumRolloverTime

### ISSUE THREAD

**Issue by mostafij-rahman** [apache/pulsar#12019]
ManagedLedgerTest is flaky. The testMaximumRolloverTime test method fails sporadically.

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
[ERROR] testMaximumRolloverTime(org.apache.bookkeeper.mledger.impl.ManagedLedgerTest)  Time elapsed: 2.016 s  <<< FAILURE!
java.lang.AssertionError: expected [2] but found [3]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.bookkeeper.mledger.impl.ManagedLedgerTest.testMaximumRolloverTime(ManagedLedgerTest.java:1780)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
</pre></code>
</details>

**Comment by tomscut** [comment]
Hi @sijie @mostafij-rahman , please assign this task to me. Thanks.
