### ISSUE TITLE
Flaky-test: [org.apache.pulsar.broker.resourcegroup.RGUsageMTAggrWaitForAllMesgsTest].[testMTProduceConsumeRGUsage]

### ISSUE THREAD

**Issue by Jason918** [apache/pulsar#12033]
[org.apache.pulsar.broker.resourcegroup.RGUsageMTAggrWaitForAllMesgsTest] is flaky. The [testMTProduceConsumeRGUsage] test method fails sporadically.

[example failure](https://github.com/apache/pulsar/pull/12032/checks?check_run_id=3594996553#step:9:1898)

```
java.lang.AssertionError: expected [3200] but found [0]
        .....
	at org.apache.pulsar.broker.resourcegroup.RGUsageMTAggrWaitForAllMesgsTest.testProduceConsumeUsageOnRG(RGUsageMTAggrWaitForAllMesgsTest.java:467)
	at org.apache.pulsar.broker.resourcegroup.RGUsageMTAggrWaitForAllMesgsTest.testMTProduceConsumeRGUsage(RGUsageMTAggrWaitForAllMesgsTest.java:109)
	.....
```

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
java.lang.AssertionError: expected [3200] but found [0]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.pulsar.broker.resourcegroup.RGUsageMTAggrWaitForAllMesgsTest.testProduceConsumeUsageOnRG(RGUsageMTAggrWaitForAllMesgsTest.java:467)
	at org.apache.pulsar.broker.resourcegroup.RGUsageMTAggrWaitForAllMesgsTest.testMTProduceConsumeRGUsage(RGUsageMTAggrWaitForAllMesgsTest.java:109)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
</pre></code>
</details>

**Comment by poorbarcode** [comment]
another one:

- https://github.com/apache/pulsar/actions/runs/3103950216/jobs/5028077061

```
Error:  Tests run: 11, Failures: 1, Errors: 0, Skipped: 9, Time elapsed: 25.765 s <<< FAILURE! - in org.apache.pulsar.broker.resourcegroup.RGUsageMTAggrWaitForAllMsgsTest
  Error:  testMTProduceConsumeRGUsageNonPersistentTopicNamesSameTenant(org.apache.pulsar.broker.resourcegroup.RGUsageMTAggrWaitForAllMsgsTest)  Time elapsed: 0.589 s  <<< FAILURE!
  java.lang.AssertionError: expected [400] but found [0]
  	at org.testng.Assert.fail(Assert.java:99)
  	at org.testng.Assert.failNotEquals(Assert.java:1037)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
  	at org.testng.Assert.assertEquals(Assert.java:122)
  	at org.testng.Assert.assertEquals(Assert.java:[907](https://github.com/apache/pulsar/actions/runs/3103950216/jobs/5028077061#step:10:908))
  	at org.testng.Assert.assertEquals(Assert.java:917)
  	at org.apache.pulsar.broker.resourcegroup.RGUsageMTAggrWaitForAllMsgsTest.testProduceConsumeUsageOnRG(RGUsageMTAggrWaitForAllMsgsTest.java:463)
  	at org.apache.pulsar.broker.resourcegroup.RGUsageMTAggrWaitForAllMsgsTest.testMTProduceConsumeRGUsageNonPersistentTopicNamesSameTenant(RGUsageMTAggrWaitForAllMsgsTest.java:108)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

The class name has been changed to `RGUsageMTAggrWaitForAllMsgsTest` by PR #12438, and the class name is `...Mesgs...`( has a misstake )
