### ISSUE TITLE
producer can't send to other running broker when force kill the broker 

### ISSUE THREAD

**Issue by moeagle** [apache/pulsar#12086]
Report Bug
pulsar 2.8.0
3 broker cluster

To Reproduce
step
1.start some producers with non-partition topic, or start 1 producer with partition topic. make sure the broker load a partition or topic in producer.
2.force kill one broker by  "kill -9 $pid"

```

org.apache.pulsar.client.api.PulsarClientException$TimeoutException: The producer my-producer3 can not send message to the topic persistent://public/default/my-topic-partition-8 within given timeout : createdAt 30003312600 ns ago, firstSentAt 779931169237300 ns ago, lastSentAt 30003089500 ns ago, retryCount 1

	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:961)
	at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.send(TypedMessageBuilderImpl.java:105)
	at TestPulsar.testProduce(TestPulsar.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)


Process finished with exit code -1
```

**Comment by Shoothzj** [comment]
It seems like your program doesn't catch the exception, could you please show the code ?

**Comment by MarvinCai** [comment]
any additional error messages or is only single broker address configured for `brokerServiceUrl` if it's not url to a LB?
if broker is killed and connection is closed, client will do lookup again which will trigger another broker to load the topic and continue the produce.
