### ISSUE TITLE
Pulsar producer can encounter and integer overflow due to excessive release requests

### ISSUE THREAD

**Issue by aahmed-se** [apache/pulsar#12151]
**Describe the bug**
ProducerImpl.java use default java semaphores, which don't have bound limit checks calling release successively can lead to overflow. 

```
Caused by: java.lang.Error: Maximum permit count exceeded
at java.util.concurrent.Semaphore$Sync.tryReleaseShared(Semaphore.java:192) ~[?:1.8.0_275]
at java.util.concurrent.locks.AbstractQueuedSynchronizer.releaseShared(AbstractQueuedSynchronizer.java:1341) ~[?:1.8.0_275]
at java.util.concurrent.Semaphore.release(Semaphore.java:609) ~[?:1.8.0_275]
at org.apache.pulsar.client.impl.ProducerImpl.batchMessageAndSend(ProducerImpl.java:1567) ~[pulsar-client-2.6.0.SPLK.10805379.jar!/:2.6.0]
at org.apache.pulsar.client.impl.ProducerImpl.doBatchSendAndAdd(ProducerImpl.java:678) ~[pulsar-client-2.6.0.jar!/:2.6.0]
at org.apache.pulsar.client.impl.ProducerImpl.serializeAndSendMessage(ProducerImpl.java:504) ~[pulsar-client-2.6.0.jar!/:2.6.0]
at org.apache.pulsar.client.impl.ProducerImpl.sendAsync(ProducerImpl.java:423) ~[pulsar-client-2.6.0.jar!/:2.6.0]
at org.apache.pulsar.client.impl.ProducerImpl.internalSendAsync(ProducerImpl.java:279) ~[pulsar-client-2.6.0.jar!/:2.6.0]
at org.apache.pulsar.client.impl.PartitionedProducerImpl.internalSendAsync(PartitionedProducerImpl.java:183) ~[pulsar-client-2.6.0.jar!/:2.6.0]
at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.sendAsync(TypedMessageBuilderImpl.java:95) ~[pulsar-client-2.6.0.jar!/:2.6.0]
at org.apache.pulsar.client.impl.ProducerBase.sendAsync(ProducerBase.java:69) ~[pulsar-client-2.6.0.jar!/:2.6.0]
```

**Comment by Shoothzj** [comment]
IMHO, we don't need bound limit checks, it's a bug for releasing more than expected

**Comment by leizhiyuan** [comment]
pulsar-client-2.6.0?
could you update 2.8.1 to check?

**Comment by aahmed-se** [comment]
We should still limit the semaphore count to prevent a breakdown in production.

**Comment by Jason918** [comment]
Any idea how to reproduce this error? @aahmed-se
