### ISSUE TITLE
Error during handshake for tls auth by apache pulsar client on linux server

### ISSUE THREAD

**Issue by thomaeschen** [apache/pulsar#12313]
**Describe the bug**
Follow the instruction from the Apache latest document to setup a TLS connection. The system will generate error related to the handshake and it shows "TLSV1_ALERT_CERTIFICATE_REQUIRED"

**To Reproduce**

 Follow the document [https://pulsar.apache.org/docs/en/security-tls-transport/](url) to create a  public certificate. server certificate and server key and put the path of each certificate into the broker settings : broker.conf.  I also configured the client.conf with the server certificate path in it and then use the CLI-tool "pulsar-client"connecting to the broker (Same tlsTrustCertsFile) . The client show the error "TLSV1_ALERT_CERTIFICATE_REQUIRED".

The client could connect to the broker over TLS successfully once I set the tlsRequireTrustedClientCertOnConnect=false

23:10:54.808 [pulsar-client-io-1-1] WARN  org.apache.pulsar.client.impl.ClientCnx - [cnpulsar01.holystone.com.tw/192.168.60.53:6651] Got exception io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: error:1000045c:SSL routines:OPENSSL_internal:TLSV1_ALERT_CERTIFICATE_REQUIRED
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:477)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: javax.net.ssl.SSLException: error:1000045c:SSL routines:OPENSSL_internal:TLSV1_ALERT_CERTIFICATE_REQUIRED
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.shutdownWithError(ReferenceCountedOpenSslEngine.java:1055)
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.sslReadErrorResult(ReferenceCountedOpenSslEngine.java:1349)
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1289)
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1374)
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1417)
        at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:224)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1344)
        at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1248)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1288)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)

**Expected behavior**
The client could connect to the broker and start consuming thr messages

**Screenshots**
![圖片](https://user-images.githubusercontent.com/87412552/136664765-1fd9aa56-65a7-43f2-a9ba-69f77cd828c9.png)
broker.conf
![圖片](https://user-images.githubusercontent.com/87412552/136664824-3d9ce06c-cfce-4a8b-a797-6c13fefc26c3.png)
client.conf
![圖片](https://user-images.githubusercontent.com/87412552/136664886-872e7e37-1c98-4091-a29b-16ad48db50df.png)

**Environment
Ubuntu 18.04.5 LTS (Bionic Beaver)
Apache Pulsar 2.8.1
openjdk version "11.0.11" 2021-04-20
Opensssl 1.1.1

**Comment by thomaeschen** [comment]
Hi , I solved the issue by adding the client certificate into the client.conf. Hence the issue could be closed

**Comment by iMine141** [comment]
@thomaeschen excuse me, I have the same question as you about TLS. I want to know how you solved the problem 。 the client certificate 
![image](https://user-images.githubusercontent.com/27681125/141978880-cb8d5d7a-ebe1-41ef-ba5e-aeeaa783aed7.png)

**Comment by thomaeschen** [comment]
Hi iMine,

1. You activate the parameter "tlsRequireTrustedClientCertOnConnect=true" in the broker.conf and it means that you must provide the client certificate to the server for the mutual authentication.
2. Following point 1, you need to set the two parameters in the client.conf to provide the certificate . The two parameters are like as follow :
### a. authPlugin=org.apache.pulsar.client.impl.auth.AuthenticationTls'''
### b. authParams={"tlsCertFile":"/pulsar/main/apache-pulsar-2.8.1/certs/client.cert.pem","tlsKeyFile":"/pulsar/main/apache-pulsar-2.8.1/certs/client.key.pem"} '''

This is how I solved the issue and hope you can also solve it.
