### ISSUE TITLE
Failed messages 1 with no more exception message

### ISSUE THREAD

**Issue by Aaronzk** [apache/pulsar#12510]
#### Discribe

When I write data into pulsar topic using a producer,I got this
```
org.apache.pulsar.client.api.PulsarClientException$ProducerQueueIsFullError: Producer send queue is full
    at org.apache.pulsar.client.impl.ProducerImpl.canEnqueueRequest(ProducerImpl.java:763) ~[pulsar-client-all-2.8.0.jar:2.8.0]
    at org.apache.pulsar.client.impl.ProducerImpl.sendAsync(ProducerImpl.java:393)
    at org.apache.pulsar.client.impl.ProducerImpl.internalSendAysnc(ProducerImpl.java:292)
    at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.sendAsync(TypedMessageBuilderImpl.java:103)

...

2021-10-27 16:00:09,178 INFO org.apache.pulsar.client.impl.ProducerStatsRecorderImpl [] - [persistent://t/n/topica] [pulsar-cluster-a-49-1244223] Pending messages: 0 --- Publish throughput: 27.12 msg/s --- 0.08 Mbit/s --- Latency: med: 138.00 ms - 95pct: 139.00 ms - 99pct: 139.00 ms - 99.9pct: 139.00 ms - max: 139.00 ms --- Ack received rate: 27.25 ack/s --- Failed messages: 1
```
and no more data was written into my topic.
#### Help Needed

I would like to know how to locate the cause of this problem, and which message is the "Failed message".

Any indicative answer is appreciate.

#### System configuration
**Pulsar version**: 2.6
**Pulsar client**: 2.8.0
**Client log level**: DEBUG
**Client Configuration**: All default values, no customisation.

**Comment by codelipenghui** [comment]
@Aaronzk There is an internal pending queue with 1000 messages by default for a producer. if the server-side with a slow response but the application send messages very fast that will fill up the pending queue, so by default, you will get the above exception, it's a fail-fast strategy. 

Another available strategy is to block the caller thread if the pending queue filled up, you can add `.blockIfQueueFull(true)` when creating the producer.

**Comment by Aaronzk** [comment]
@codelipenghui 
why not set `blockIfQueueFull(true)` as default?
