### ISSUE TITLE
[Function Worker] Http Server Fails on generating metrics

### ISSUE THREAD

**Issue by nlu90** [apache/pulsar#12631]
**Describe the bug**
Functions on one cluster got into a weird state where all http server failed on generating metrics. Because generating metrics would check isLeader.get() is a blocking call depends on an HTTP service to check who is leader. https://github.com/apache/pulsar/pull/10502/files#diff-d9d7d7b0f950ed7aa1ff11bc0ec1450e95693b6f573a410ccf364861eb355825R286

We should avoid calling blocking call on an HTTP request processing logic which also depends on another HTTP call.

```
05:32:48.376 [prometheus-stats-41-1] WARN  org.apache.pulsar.functions.worker.MembershipManager - Failed to determine leader in functions cluster
05:32:48.376 [prometheus-stats-41-1] ERROR org.apache.pulsar.broker.stats.prometheus.PrometheusMetricsServlet - Failed to generate prometheus stats
	at org.apache.pulsar.functions.worker.PulsarWorkerService.lambda$start$5(PulsarWorkerService.java:515) ~[io.streamnative-pulsar-functions-worker-2.8.1.10.jar:2.8.1.10]
	at org.apache.pulsar.functions.worker.WorkerStatsManager.generateLeaderMetrics(WorkerStatsManager.java:286) ~[io.streamnative-pulsar-functions-worker-2.8.1.10.jar:2.8.1.10]
	at org.apache.pulsar.functions.worker.WorkerStatsManager.getStatsAsString(WorkerStatsManager.java:281) ~[io.streamnative-pulsar-functions-worker-2.8.1.10.jar:2.8.1.10]
	at org.apache.pulsar.functions.worker.FunctionsStatsGenerator.generate(FunctionsStatsGenerator.java:45) ~[io.streamnative-pulsar-functions-worker-2.8.1.10.jar:2.8.1.10]
	at org.apache.pulsar.functions.worker.PulsarWorkerService.generateFunctionsStats(PulsarWorkerService.java:186) ~[io.streamnative-pulsar-functions-worker-2.8.1.10.jar:2.8.1.10]
	at org.apache.pulsar.broker.stats.prometheus.PrometheusMetricsGenerator.generate(PrometheusMetricsGenerator.java:114) ~[io.streamnative-pulsar-broker-2.8.1.10.jar:2.8.1.10]
	at org.apache.pulsar.broker.stats.prometheus.PrometheusMetricsServlet.lambda$doGet$0(PrometheusMetricsServlet.java:77) ~[io.streamnative-pulsar-broker-2.8.1.10.jar:2.8.1.10]
	at org.apache.bookkeeper.mledger.util.SafeRun$1.safeRun(SafeRun.java:32) [io.streamnative-managed-ledger-2.8.1.10.jar:2.8.1.10]
	at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [org.apache.bookkeeper-bookkeeper-common-4.14.2.jar:4.14.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]
05:32:48.376 [prometheus-stats-41-1] INFO  org.eclipse.jetty.server.RequestLog - 10.185.66.93 - - [04/Nov/2021:05:32:48 +0000] "GET /metrics/ HTTP/1.1" 500 0 "http://10.185.60.241:8080/metrics" "Prometheus/2.27.1" 70
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.fail(LengthFieldBasedFrameDecoder.java:503)
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.failIfNecessary(LengthFieldBasedFrameDecoder.java:489)
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.exceededFrameLength(LengthFieldBasedFrameDecoder.java:376)
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:419)
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:332)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

05:32:54.429 [pulsar-web-40-7] INFO  org.eclipse.jetty.server.RequestLog - 10.185.53.138 - - [04/Nov/2021:05:32:54 +0000] "GET /status.html HTTP/1.1" 200 2 "-" "kube-probe/1.17+" 0
05:32:56.869 [pulsar-web-40-1] INFO  org.eclipse.jetty.server.RequestLog - 10.185.53.138 - - [04/Nov/2021:05:32:56 +0000] "GET /status.html HTTP/1.1" 200 2 "-" "kube-probe/1.17+" 1
05:33:03.306 [pulsar-web-40-4] INFO  org.eclipse.jetty.server.RequestLog - 10.185.66.93 - - [04/Nov/2021:05:33:03 +0000] "GET /metrics HTTP/1.1" 302 0 "-" "Prometheus/2.27.1" 0
05:33:03.357 [pulsar-web-40-7] INFO  org.eclipse.jetty.server.RequestLog - 10.185.60.241 - - [04/Nov/2021:05:33:03 +0000] "GET /admin/v2/persistent/public/functions/coordinate/stats?getPreciseBacklog=false&subscriptionBacklogSize=false HTTP/1.1" 307 0 "-" "Pulsar-Java-v2.8.1.10" 34
05:33:03.380 [prometheus-stats-41-1] WARN  org.apache.pulsar.functions.worker.MembershipManager - Failed to determine leader in functions cluster
05:33:03.380 [prometheus-stats-41-1] ERROR org.apache.pulsar.broker.stats.prometheus.PrometheusMetricsServlet - Failed to generate prometheus stats
	at org.apache.pulsar.functions.worker.PulsarWorkerService.lambda$start$5(PulsarWorkerService.java:515) ~[io.streamnative-pulsar-functions-worker-2.8.1.10.jar:2.8.1.10]
	at org.apache.pulsar.functions.worker.WorkerStatsManager.generateLeaderMetrics(WorkerStatsManager.java:286) ~[io.streamnative-pulsar-functions-worker-2.8.1.10.jar:2.8.1.10]
	at org.apache.pulsar.functions.worker.WorkerStatsManager.getStatsAsString(WorkerStatsManager.java:281) ~[io.streamnative-pulsar-functions-worker-2.8.1.10.jar:2.8.1.10]
	at org.apache.pulsar.functions.worker.FunctionsStatsGenerator.generate(FunctionsStatsGenerator.java:45) ~[io.streamnative-pulsar-functions-worker-2.8.1.10.jar:2.8.1.10]
	at org.apache.pulsar.functions.worker.PulsarWorkerService.generateFunctionsStats(PulsarWorkerService.java:186) ~[io.streamnative-pulsar-functions-worker-2.8.1.10.jar:2.8.1.10]
	at org.apache.pulsar.broker.stats.prometheus.PrometheusMetricsGenerator.generate(PrometheusMetricsGenerator.java:114) ~[io.streamnative-pulsar-broker-2.8.1.10.jar:2.8.1.10]
	at org.apache.pulsar.broker.stats.prometheus.PrometheusMetricsServlet.lambda$doGet$0(PrometheusMetricsServlet.java:77) ~[io.streamnative-pulsar-broker-2.8.1.10.jar:2.8.1.10]
	at org.apache.bookkeeper.mledger.util.SafeRun$1.safeRun(SafeRun.java:32) [io.streamnative-managed-ledger-2.8.1.10.jar:2.8.1.10]
	at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [org.apache.bookkeeper-bookkeeper-common-4.14.2.jar:4.14.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**To Reproduce**
1. Deploy functions
2. check the metrics generation

**Expected behavior**
The metrics should be generated successfully

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.
