### ISSUE TITLE
Flaky-test: PersistentTopicsTest.testPeekWithSubscriptionNameNotExist

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#12672]
PersistentTopicsTest is flaky. The testPeekWithSubscriptionNameNotExist test method fails sporadically.

[example failure](https://github.com/apache/pulsar/runs/4139503686?check_suite_focus=true#step:9:483)

```
Error:  Tests run: 50, Failures: 10, Errors: 0, Skipped: 21, Time elapsed: 211.054 s <<< FAILURE! - in org.apache.pulsar.broker.admin.PersistentTopicsTest
Error:  testPeekWithSubscriptionNameNotExist(org.apache.pulsar.broker.admin.PersistentTopicsTest)  Time elapsed: 60.065 s  <<< FAILURE!
org.apache.pulsar.client.api.PulsarClientException$TimeoutException: request timeout {'durationMs': '30000', 'reqId':'1030153108732970473', 'remote':'localhost/127.0.0.1:37151', 'local':'/127.0.0.1:45602'}
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:1008)
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:91)
	at org.apache.pulsar.broker.admin.PersistentTopicsTest.testPeekWithSubscriptionNameNotExist(PersistentTopicsTest.java:682)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by Jason918** [comment]
+1,  I think it's because it sends too many messages, not necessary though.
