### ISSUE TITLE
Flaky-test: TransactionTest.testMaxReadPositionForNormalPublish

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#12671]
TransactionTest is flaky. The testMaxReadPositionForNormalPublish test method fails sporadically.

[example failure](https://github.com/apache/pulsar/runs/4139503686?check_suite_focus=true#step:9:8651)

```
Error:  Tests run: 14, Failures: 3, Errors: 0, Skipped: 7, Time elapsed: 115.852 s <<< FAILURE! - in org.apache.pulsar.broker.transaction.TransactionTest
Error:  testMaxReadPositionForNormalPublish(org.apache.pulsar.broker.transaction.TransactionTest)  Time elapsed: 0.298 s  <<< FAILURE!
java.lang.AssertionError: expected [0] but found [-1]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:797)
	at org.testng.Assert.assertEquals(Assert.java:807)
	at org.apache.pulsar.broker.transaction.TransactionTest.testMaxReadPositionForNormalPublish(TransactionTest.java:388)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by codelipenghui** [comment]
@congbobo184 Could you please help check this issue?
