### ISSUE TITLE
Unable to load the RocksDB shared library

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#12695]
**Describe the bug**
Pulsar v2.8.1
OS：BCLinux

```
17:04:55.267 [main] ERROR org.apache.bookkeeper.server.Main - Failed to build bookie server
java.io.IOException: Failed to load RocksDB JNI library
	at org.apache.bookkeeper.bookie.storage.ldb.KeyValueStorageRocksDB.<init>(KeyValueStorageRocksDB.java:97) ~[org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
	at org.apache.bookkeeper.bookie.storage.ldb.KeyValueStorageRocksDB.<init>(KeyValueStorageRocksDB.java:88) ~[org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
	at org.apache.bookkeeper.bookie.storage.ldb.KeyValueStorageRocksDB.lambda$static$0(KeyValueStorageRocksDB.java:62) ~[org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
	at org.apache.bookkeeper.bookie.storage.ldb.LedgerMetadataIndex.<init>(LedgerMetadataIndex.java:68) ~[org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
	at org.apache.bookkeeper.bookie.storage.ldb.SingleDirectoryDbLedgerStorage.<init>(SingleDirectoryDbLedgerStorage.java:169) ~[org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
	at org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorage.newSingleDirectoryDbLedgerStorage(DbLedgerStorage.java:150) ~[org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
	at org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorage.initialize(DbLedgerStorage.java:129) ~[org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
	at org.apache.bookkeeper.bookie.Bookie.<init>(Bookie.java:818) ~[org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
	at org.apache.bookkeeper.proto.BookieServer.newBookie(BookieServer.java:152) ~[org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
	at org.apache.bookkeeper.proto.BookieServer.<init>(BookieServer.java:120) ~[org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
	at org.apache.bookkeeper.server.service.BookieService.<init>(BookieService.java:52) ~[org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
	at org.apache.bookkeeper.server.Main.buildBookieServer(Main.java:304) ~[org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
	at org.apache.bookkeeper.server.Main.doMain(Main.java:226) [org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
	at org.apache.bookkeeper.server.Main.main(Main.java:208) [org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
Caused by: java.lang.ExceptionInInitializerError
	at org.apache.bookkeeper.bookie.storage.ldb.KeyValueStorageRocksDB.<init>(KeyValueStorageRocksDB.java:95) ~[org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
	... 13 more
Caused by: java.lang.RuntimeException: Unable to load the RocksDB shared library
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:70) ~[org.rocksdb-rocksdbjni-6.10.2.jar:?]
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:38) ~[org.rocksdb-rocksdbjni-6.10.2.jar:?]
	at org.apache.bookkeeper.bookie.storage.ldb.KeyValueStorageRocksDB.<init>(KeyValueStorageRocksDB.java:95) ~[org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
	... 13 more
Caused by: java.io.IOException: Permission denied
	at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[?:1.8.0_251]
	at java.io.File.createTempFile(File.java:2024) ~[?:1.8.0_251]
	at java.io.File.createTempFile(File.java:2070) ~[?:1.8.0_251]
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJarToTemp(NativeLibraryLoader.java:88) ~[org.rocksdb-rocksdbjni-6.10.2.jar:?]
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:79) ~[org.rocksdb-rocksdbjni-6.10.2.jar:?]
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:57) ~[org.rocksdb-rocksdbjni-6.10.2.jar:?]
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:67) ~[org.rocksdb-rocksdbjni-6.10.2.jar:?]
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:38) ~[org.rocksdb-rocksdbjni-6.10.2.jar:?]
	at org.apache.bookkeeper.bookie.storage.ldb.KeyValueStorageRocksDB.<init>(KeyValueStorageRocksDB.java:95) ~[org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
	... 13 more

```

**Comment by codelipenghui** [comment]
@xuesongxs Looks like permission issues? `Caused by: java.io.IOException: Permission denied`

**Comment by xuesongxs** [comment]
> @xuesongxs Looks like permission issues? `Caused by: java.io.IOException: Permission denied`

at org.rocksdb.NativeLibraryLoader.loadLibraryFromJarToTemp(NativeLibraryLoader.java:88) ~[org.rocksdb-rocksdbjni-6.10.2.jar:?]

When starting bookie, the librocksdbjni.so file will be copied to the /tmp directory. The current user does not have permission to write to the /tmp directory. This should be the reason.

 
From: lipenghui
Date: 2021-11-09 23:58
To: apache/pulsar
CC: xuesongxs; Mention
Subject: Re: [apache/pulsar] Unable to load the RocksDB shared library (Issue #12695)
@xuesongxs Looks like permission issues? Caused by: java.io.IOException: Permission denied
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xuesongxs** [comment]
> @xuesongxs Looks like permission issues? `Caused by: java.io.IOException: Permission denied`

at org.rocksdb.NativeLibraryLoader.loadLibraryFromJarToTemp(NativeLibraryLoader.java:88) ~[org.rocksdb-rocksdbjni-6.10.2.jar:?]

When starting bookie, the librocksdbjni.so file will be copied to the /tmp directory. The current user does not have permission to write to the /tmp directory. This should be the reason.

**Comment by tavoda** [comment]
I'm getting this error on new Debian system where exception is caused by:
Caused by: java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni205253776051654618.so: /tmp/librocksdbjni205253776051654618.so: failed to map segment from shared object                          

I traced error to linux /tmp/ folder which is mounted with 'noexec' flag. Because if this, library can't be loaded to process. Solution is to remount /tmp/ folder without noexec flag or set environment variable before starting pulsar:
```
export ROCKSDB_SHAREDLIB_DIR=~/tmp/
mkdir ~/tmp/
```

**Comment by xuesongxs** [comment]
> I'm getting this error on new Debian system where exception is caused by: Caused by: java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni205253776051654618.so: /tmp/librocksdbjni205253776051654618.so: failed to map segment from shared object
> 
> I traced error to linux /tmp/ folder which is mounted with 'noexec' flag. Because if this, library can't be loaded to process. Solution is to remount /tmp/ folder without noexec flag or set environment variable before starting pulsar:
> 
> ```
> export ROCKSDB_SHAREDLIB_DIR=~/tmp/
> mkdir ~/tmp/
> ```

I agree, but rocksdbjni use String DEFAULT_TEMP_DIR = "/tmp", rocksdbjni needs to be modified.

**Comment by tisonkun** [comment]
We're using rocksdbjni-6.29.4.1 now and it calls `File.createTempFile` which should resolve this issue.
