### ISSUE TITLE
[bug]  java.lang.ArrayIndexOutOfBoundsException with user defined replicatorPrefix.

### ISSUE THREAD

**Issue by Jason918** [apache/pulsar#12796]
**Describe the bug**
The following exception occurs when I changed replicatorPrefix, and the replicator does not work.

Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
	at org.apache.pulsar.broker.service.Producer.<init>(Producer.java:131) ~[classes/:?]
	at org.apache.pulsar.broker.service.ServerCnx.buildProducerAndAddTopic(ServerCnx.java:1296) ~[classes/:?]
	at org.apache.pulsar.broker.service.ServerCnx.lambda$handleProducer$18(ServerCnx.java:1240) ~[classes/:?]

**To Reproduce**
1. set replicatorPrefix="my-replicatorPrefix" in config
2. start replicator
3. send message
4. Error occurs

**Expected behavior**
Replicator should works with user defined replicatorPrefix.

**Screenshots**
NO

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**
No

**Comment by codelipenghui** [comment]
Thanks for the quick fix @Jason918
