### ISSUE TITLE
In the process of perf,Broker shutdown.

### ISSUE THREAD

**Issue by xiaobing0508** [apache/pulsar#12884]
### Broker logs
16:12:59.243 [BookKeeperClientWorker-OrderedExecutor-2-0] ERROR org.apache.bookkeeper.common.util.SafeRunnable - Unexpected throwable caught 
java.lang.NullPointerException: null
	at org.apache.bookkeeper.mledger.impl.OpAddEntry.lambda$handleAddFailure$0(OpAddEntry.java:291) ~[org.apache.pulsar-managed-ledger-2.8.1.jar:2.8.1]
	at org.apache.bookkeeper.mledger.util.SafeRun$1.safeRun(SafeRun.java:32) ~[org.apache.pulsar-managed-ledger-2.8.1.jar:2.8.1]
	at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [org.apache.bookkeeper-bookkeeper-common-4.14.2.jar:4.14.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.66.Final.jar:4.1.66.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

16:12:59.344 [pulsar-io-4-27] WARN  org.apache.pulsar.broker.service.BrokerService - Namespace is being unloaded, cannot add topic persistent://my-tenant/my-namespace/test-partition-1
16:12:59.345 [pulsar-io-4-27] WARN  org.apache.pulsar.broker.service.ServerCnx - [/192.168.149.32:43464][persistent://my-tenant/my-namespace/test-partition-1][sub-0] Failed to create consumer: consumerId=7, Namespace is being unloaded, cannot add topic persistent://my-tenant/my-namespace/test-partition-1

16:12:59.510 [pulsar-io-4-58] WARN  org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://my-tenant/my-namespace/test-partition-5] Attempting to subscribe to a fenced topic
16:12:59.510 [pulsar-io-4-58] WARN  org.apache.pulsar.broker.service.ServerCnx - [/192.168.149.32:43516][persistent://my-tenant/my-namespace/test-partition-5][sub-0] Failed to create consumer: consumerId=20, Topic is temporarily unavailable

**Comment by xiaobing0508** [comment]
My pulsar version is 2.8.1.

**Comment by Jason918** [comment]
Any log about zk session expired?

**Comment by xiaobing0508** [comment]
@Jason918 Yes.
[pulsar-ordered-OrderedExecutor-2-0-EventThread] INFO  org.apache.pulsar.zookeeper.ZooKeeperCache - [State:CONNECTED Timeout:30000 sessionid:0x100199b4612009d local:/192.168.191.54:41796 remoteserver:192.168.191.53:2181 lastZxid:4300302298 xid:563640 sent:563640 recv:563704 queuedpkts:0 pendingresp:0 queuedevents:0] Received ZooKeeper watch event: WatchedEvent state:SyncConnected type:NodeDeleted path:/namespace/my-tenant/my-namespace/0xc0000000_0xffffffff

**Comment by Jason918** [comment]
It's the reason broker shutdown. It's the default behavior pulsar handles zk session timeout.

**Comment by xiaobing0508** [comment]
Maximum connections reached? @Jason918

**Comment by Jason918** [comment]
Many reason can cause zk session timeout. Broker long gc, network outage, too much pressure on zk server, ect.
