### ISSUE TITLE
A large number of exceptions occur when starting a standalone server

### ISSUE THREAD

**Issue by massakam** [apache/pulsar#12895]
**Describe the bug**

When I start a standalone server built from [the current master code](https://github.com/apache/pulsar/tree/d74af88a6aed5a7da3139a4228ae29f793ec72b2), I get a lot of the following exceptions:
```
Nov 17, 2021 1:03:46 PM com.github.benmanes.caffeine.cache.LocalAsyncCache lambda$handleCompletion$7
WARNING: Exception thrown during asynchronous load
java.util.concurrent.CompletionException: org.apache.pulsar.metadata.api.MetadataStoreException$ContentDeserializationException: Failed to deserialize payload for key '/counters/producer-name'
        at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
        at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
        at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:925)
        at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:967)
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
        at org.apache.pulsar.metadata.impl.ZKMetadataStore.lambda$null$7(ZKMetadataStore.java:139)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.pulsar.metadata.api.MetadataStoreException$ContentDeserializationException: Failed to deserialize payload for key '/counters/producer-name'
        at org.apache.pulsar.metadata.cache.impl.MetadataCacheImpl.lambda$readValueFromStore$0(MetadataCacheImpl.java:111)
        at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966)
        ... 8 more
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (byte[])""; line: 1, column: 0]
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4688)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4586)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3643)
        at org.apache.pulsar.metadata.cache.impl.JSONMetadataSerdeSimpleType.deserialize(JSONMetadataSerdeSimpleType.java:42)
        at org.apache.pulsar.metadata.cache.impl.MetadataCacheImpl.lambda$readValueFromStore$0(MetadataCacheImpl.java:107)
        ... 9 more
```

I don't know why, but when I revert https://github.com/apache/pulsar/pull/12788, these exceptions disappear.

**To Reproduce**
```sh
$ git clone git@github.com:apache/pulsar.git
$ cd pulsar
$ mvn clean install -DskipTests=true
$ ./bin/pulsar standalone -nfw -nss --wipe-data
```

**Desktop (please complete the following information):**
 - OS: CentOS 7

**Comment by massakam** [comment]
@merlimat Do you have any idea what is the cause of this?

**Comment by Jason918** [comment]
I wrote a fix. See #12896

**Comment by massakam** [comment]
Great! I have confirmed that cherry-picking #12896 solves this problem.

**Comment by massakam** [comment]
This issue is a duplicate of #12894, so close it.
