### ISSUE TITLE
Pulsar in AWS ARM processor group unable to start cluster 

### ISSUE THREAD

**Issue by bhasvij** [apache/pulsar#12907]
**Describe the bug**
After starting the pulsar service using
bin/pulsar-daemon start broker in AWS c6g.4xlarge ARM processor instances the following problem is coming:

java.lang.UnsatisfiedLinkError: no conscrypt_openjdk_jni-linux-aarch_64 in java.library.path: [/usr/java/packages/lib, /lib, /usr/lib, /usr/lib64, /li
b64]
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670) ~[?:?]
at java.lang.Runtime.loadLibrary0(Runtime.java:830) ~[?:?]
at java.lang.System.loadLibrary(System.java:1873) ~[?:?]
at org.conscrypt.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:54) ~[org.conscrypt-conscrypt-openjdk-uber-2.5.2.jar:2.5.2]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
at org.conscrypt.NativeLibraryLoader$1.run(NativeLibraryLoader.java:297) ~[org.conscrypt-conscrypt-openjdk-uber-2.5.2.jar:2.5.2]
at org.conscrypt.NativeLibraryLoader$1.run(NativeLibraryLoader.java:289) ~[org.conscrypt-conscrypt-openjdk-uber-2.5.2.jar:2.5.2]
at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
at org.conscrypt.NativeLibraryLoader.loadLibraryFromHelperClassloader(NativeLibraryLoader.java:289) ~[org.conscrypt-conscrypt-openjdk-uber-2.5
.2.jar:2.5.2]
at org.conscrypt.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:262) ~[org.conscrypt-conscrypt-openjdk-uber-2.5.2.jar:2.5.2]
at org.conscrypt.NativeLibraryLoader.load(NativeLibraryLoader.java:162) ~[org.conscrypt-conscrypt-openjdk-uber-2.5.2.jar:2.5.2]
at org.conscrypt.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:106) ~[org.conscrypt-conscrypt-openjdk-uber-2.5.2.jar:2.5.2]
at org.conscrypt.NativeCryptoJni.init(NativeCryptoJ

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by bhasvij** [comment]
Tried generating library .so file for ARM as mentioned here:
https://support.huaweicloud.com/intl/en-us/prtg-sc-kunpengwebs/kunpengconscryptopenjdkuber_02_0010.html
But unable to do...failing.

**Comment by bhasvij** [comment]
Looks like ARM64 support is not there from google: https://github.com/google/conscrypt
We need to think for pulsar either to think alternative for ARM64 platform support with this library or we can  remove dependency of this jar altogtether

**Comment by bhasvij** [comment]
Found work around temporarily:
By removing the  conscrypt-openjdk uber 2.5.2 jar file and able to run pulsar service.

**Comment by wangjialing218** [comment]
@lhotari This issue seems caused by introduce conscrypt-openjdk in #10541
Is there any problem just removing conscrypt-openjdk uber 2.5.2 jar to run pulsar in ARM env?

**Comment by lhotari** [comment]
> @lhotari This issue seems caused by introduce conscrypt-openjdk in #10541 Is there any problem just removing conscrypt-openjdk uber 2.5.2 jar to run pulsar in ARM env?

@wangjialing218 Yes, you should be able to run Pulsar without Conscrypt by removing the conscrypt jar file. Please report if there are issues. It is also possible to create a specific feature for disabling Conscrypt when ARM platform is detected.

**Comment by lhotari** [comment]
@bhasvij @wangjialing218 I created a PR to fix the issue: #12938 . When Conscrypt cannot be loaded, the JDK default security provider will be used.
