### ISSUE TITLE
Unable to configure a JDBC Sink 

### ISSUE THREAD

**Issue by pgandhap** [apache/pulsar#12960]
I am unable to configure a JDBC Sink . I followed this link : https://pulsar.apache.org/docs/en/io-quickstart/#configure-a-jdbc-sink . In this Step 1 and Step 2 was done , but coming to step 3 which is upload schema to topic . Getting an error with below

root@a817052bbed6:/pulsar# bin/pulsar-admin schemas upload pulsar-postgres-jdbc-sink-topic -f ./connectors/avro-schema
java.io.FileNotFoundException: ./connectors/avro-schema (No such file or directory)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
at java.base/java.io.FileInputStream.(FileInputStream.java:157)
at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1029)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3413)
at org.apache.pulsar.admin.cli.CmdSchemas$UploadSchema.run(CmdSchemas.java:88)
at org.apache.pulsar.admin.cli.CmdBase.run(CmdBase.java:86)
at org.apache.pulsar.admin.cli.PulsarAdminTool.run(PulsarAdminTool.java:282)
at org.apache.pulsar.admin.cli.PulsarAdminTool.main(PulsarAdminTool.java:329)
root@a817052bbed6:/pulsar#

For your information , i installed pulsar through docker command .

Please help on the same . Thanks !!!

**Comment by pgandhap** [comment]
I got the solution . Previously avro-schema file is in local machine not in docker container , but i am trying to run this command to upload schema to a topic . That's why i am getting this error . Now i copied schema file into pulsar docker container and that error was gone .

**Comment by codelipenghui** [comment]
Thanks @pgandhap, I will close the issue first.
