### ISSUE TITLE
Java client consumer acknowledge issue. It should work for both of the cases

### ISSUE THREAD

**Issue by julyday2015** [apache/pulsar#12962]
**Describe the bug**
Hi, I found an issue in java client library. When consumer tried to acknowledge, if consumer acknowledge like following, its working:
`consumer.acknowledge(message.getMessageId())`
But if I do following, it’s failed:
`consumer.acknowledge(MessageId.fromByteArray(message.getMessageId().toByteArray()))`
Ideally, both of the cases should work. There should be something wrong with serialization and deserialization of MessageId’s toByteArray and fromByteArray method.
An exception will be thrown if I use second method for acknowledging:
`java.lang.IllegalArgumentException: null
	at org.apache.pulsar.shade.com.google.common.base.Preconditions.checkArgument(Preconditions.java:128) ~[pulsar-client-2.8.1.jar:2.8.1]
	at org.apache.pulsar.client.impl.MultiTopicsConsumerImpl.doAcknowledge(MultiTopicsConsumerImpl.java:425) ~[pulsar-client-2.8.1.jar:2.8.1]
	at org.apache.pulsar.client.impl.ConsumerBase.doAcknowledgeWithTxn(ConsumerBase.java:554) ~[pulsar-client-2.8.1.jar:2.8.1]
	at org.apache.pulsar.client.impl.ConsumerBase.acknowledgeAsync(ConsumerBase.java:494) ~[pulsar-client-2.8.1.jar:2.8.1]
	at org.apache.pulsar.client.impl.ConsumerBase.acknowledgeAsync(ConsumerBase.java:483) ~[pulsar-client-2.8.1.jar:2.8.1]
	at org.apache.pulsar.client.impl.ConsumerBase.acknowledge(ConsumerBase.java:313) ~[pulsar-client-2.8.1.jar:2.8.1]`
**To Reproduce**
1. Do consumer acknowledge with `consumer.acknowledge(MessageId.fromByteArray(message.getMessageId().toByteArray()))`
2. Exception thrown:
`java.lang.IllegalArgumentException: null
	at org.apache.pulsar.shade.com.google.common.base.Preconditions.checkArgument(Preconditions.java:128) ~[pulsar-client-2.8.1.jar:2.8.1]
	at org.apache.pulsar.client.impl.MultiTopicsConsumerImpl.doAcknowledge(MultiTopicsConsumerImpl.java:425) ~[pulsar-client-2.8.1.jar:2.8.1]
	at org.apache.pulsar.client.impl.ConsumerBase.doAcknowledgeWithTxn(ConsumerBase.java:554) ~[pulsar-client-2.8.1.jar:2.8.1]
	at org.apache.pulsar.client.impl.ConsumerBase.acknowledgeAsync(ConsumerBase.java:494) ~[pulsar-client-2.8.1.jar:2.8.1]
	at org.apache.pulsar.client.impl.ConsumerBase.acknowledgeAsync(ConsumerBase.java:483) ~[pulsar-client-2.8.1.jar:2.8.1]
	at org.apache.pulsar.client.impl.ConsumerBase.acknowledge(ConsumerBase.java:313) ~[pulsar-client-2.8.1.jar:2.8.1]`

**Expected behavior**
It should work like `consumer.acknowledge(message.getMessageId())`

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by nodece** [comment]
@julyday2015 You should use the `MessageId.fromByteArrayWithTopic()`, it will be working, and I checked the `MessageId.fromByteArrayWithTopic()`, which only supports partition topic, so I made a PR: https://github.com/apache/pulsar/pull/12994, please take a look if you are free.

**Comment by julyday2015** [comment]
Hi @nodece , thank you for your help. But it does not work for me either. It will not throw exception, but message looks like not acked because consumer can still receive previous message with same subscription. please check below code
`consumer.acknowledge(
                            MessageId.fromByteArrayWithTopic(
                                    msg.getMessageId().toByteArray(), consumer.getTopic()))`

**Comment by nodece** [comment]
@julyday2015 Could you provide a code to reproduce this issue? I need to know how to produce.

**Comment by xqianwang** [comment]
Hi @nodece , just simply try 
`consumer.acknowledge(MessageId.fromByteArrayWithTopic( message.getMessageId().toByteArray(), consumer.getTopic()))` instead of 
`consumer.acknowledge(message.getMessageId())`
I got same issue

**Comment by nodece** [comment]
@xqianwang Could you try the code of https://github.com/apache/pulsar/pull/12994, I fix the `acknowledge()`, but I'm not sure whether to fix your problem.
