### ISSUE TITLE
Consumer: Failed to load config into existing configuration data

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#13016]
**Describe the bug**
Pulsar v2.8.1

Build consumer by loadConf(), An exception occurred when starting the consumer.

consumer code:

```
        Map<String, Object> config = new HashMap<>();
        config.put("topicNames", "persistent://public/default/test-string1");
        config.put("ackTimeoutMillis", 1000);
        config.put("receiverQueueSize", 2000);
        Consumer<String> builder = pulsarClient.newConsumer(Schema.STRING)
                .loadConf(config)
                .subscribe();
```

```
Exception in thread "main" java.lang.RuntimeException: Failed to load config into existing configuration data
	at org.apache.pulsar.client.impl.conf.ConfigurationDataUtils.loadData(ConfigurationDataUtils.java:69)
	at org.apache.pulsar.client.impl.ConsumerBuilderImpl.loadConf(ConsumerBuilderImpl.java:83)
	at newland.DeadLetterTest1.main(DeadLetterTest1.java:41)
Caused by: org.apache.pulsar.shade.com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `java.util.HashSet` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('persistent://public/default/test-string1')
 at [Source: (String)"{"autoUpdatePartitionsIntervalSeconds":60,"tickDurationMillis":1000,"replicateSubscriptionState":false,"negativeAckRedeliveryDelayMicros":60000000,"expireTimeOfIncompleteChunkedMessageMillis":60000,"maxPendingChuckedMessage":10,"topicNames":"persistent://public/default/test-string1","priorityLevel":0,"ackReceiptEnabled":false,"acknowledgementsGroupTimeMicros":100000,"receiverQueueSize":2000,"autoUpdatePartitions":true,"subscriptionMode":"Durable","poolMessages":false,"patternAutoDiscoveryPeriod""[truncated 407 chars]; line: 1, column: 242] (through reference chain: org.apache.pulsar.client.impl.conf.ConsumerConfigurationData["topicNames"])
	at org.apache.pulsar.shade.com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at org.apache.pulsar.shade.com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1588)
	at org.apache.pulsar.shade.com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1213)
	at org.apache.pulsar.shade.com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromString(StdDeserializer.java:311)
	at org.apache.pulsar.shade.com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.handleNonArray(StringCollectionDeserializer.java:284)
	at org.apache.pulsar.shade.com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:192)
	at org.apache.pulsar.shade.com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:182)
	at org.apache.pulsar.shade.com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:25)
	at org.apache.pulsar.shade.com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at org.apache.pulsar.shade.com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
	at org.apache.pulsar.shade.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at org.apache.pulsar.shade.com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at org.apache.pulsar.shade.com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at org.apache.pulsar.shade.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
	at org.apache.pulsar.shade.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3516)
	at org.apache.pulsar.client.impl.conf.ConfigurationDataUtils.loadData(ConfigurationDataUtils.java:67)
	... 2 more

```

**Comment by mattisonchao** [comment]
i will check it.

**Comment by mattisonchao** [comment]
You need to use Set collection in topicNames.

```java
   Set<String> topicNames = Sets.newHashSet();
        topicNames.add("persistent://public/default/test-string1");
        config.put("topicNames", topicNames);
```

**Comment by xuesongxs** [comment]
In this way, not all attributes can be loaded directly through loadconf, but the pulsar document describes that this can be done, and the producer can load through loadconf.



***@***.***
 
From: Qiang Zhao
Date: 2021-11-29 21:36
To: apache/pulsar
CC: xuesongxs; Author
Subject: Re: [apache/pulsar] Consumer: Failed to load config into existing configuration data (Issue #13016)
You need to use Set collection in topicNames.
   Set<String> topicNames = Sets.newHashSet();
        topicNames.add("persistent://public/default/test-string1");
        config.put("topicNames", topicNames);
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mattisonchao** [comment]
which attributes you can not to load ? @xuesongxs

**Comment by xuesongxs** [comment]
I hope that all attributes of the consumer can be loaded directly through loadconf, so that the consumer's configuration can be placed in a configuration file. The consumer can directly load the contents of the configuration file. If the topic needs to use HashSet, it has to be converted twice.



***@***.***
 
From: Qiang Zhao
Date: 2021-11-29 22:10
To: apache/pulsar
CC: xuesongxs; Mention
Subject: Re: [apache/pulsar] Consumer: Failed to load config into existing configuration data (Issue #13016)
which attributes you can not to load ? @xuesongxs
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mattisonchao** [comment]
@xuesongxs  
I commit a PR for this issues.    #13026

**Comment by mattisonchao** [comment]
@xuesongxs  
I need to discuss with members.

**Comment by Technoboy-** [comment]
Not a bug. Please use the right data type. Not all the properties are string. 
All the properties can be set from conf, but please use the correct type first.
