### ISSUE TITLE
Failed to deserialize load report data

### ISSUE THREAD

**Issue by gaoran10** [apache/pulsar#13109]
**Describe the bug**

I deploy a Pulsar cluster in google cloud based on the image `streamnative/pulsar-all:2.10.0-rc-202111212205`, but I found some broker error logs as below. It seems that the load report data couldn't be deserialized.

```
19:53:48.882 [metadata-store-6-1] INFO  org.apache.pulsar.metadata.coordination.impl.ResourceLockImpl - Acquired resource lock on /loadbalance/brokers/chaos-pulsar-12-broker-2.chaos-pulsar-12-broker.chaos-12.svc.cluster.local:8080
19:53:48.891 [metadata-store-6-1] WARN  com.github.benmanes.caffeine.cache.LocalAsyncCache - Exception thrown during asynchronous load
java.util.concurrent.CompletionException: org.apache.pulsar.metadata.api.MetadataStoreException$ContentDeserializationException: Failed to deserialize payload for key '/loadbalance/brokers/chaos-pulsar-12-broker-2.chaos-pulsar-12-broker.chaos-12.svc.cluster.local:8080'
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1074) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
	at org.apache.pulsar.metadata.impl.ZKMetadataStore.lambda$null$3(ZKMetadataStore.java:139) ~[io.streamnative-pulsar-metadata-2.10.0-rc-202111212205.jar:2.10.0-rc-202111212205]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.apache.pulsar.metadata.api.MetadataStoreException$ContentDeserializationException: Failed to deserialize payload for key '/loadbalance/brokers/chaos-pulsar-12-broker-2.chaos-pulsar-12-broker.chaos-12.svc.cluster.local:8080'
	at org.apache.pulsar.metadata.cache.impl.MetadataCacheImpl.lambda$readValueFromStore$0(MetadataCacheImpl.java:111) ~[io.streamnative-pulsar-metadata-2.10.0-rc-202111212205.jar:2.10.0-rc-202111212205]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
	... 7 more
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `org.apache.pulsar.common.policies.data.impl.BundlesDataImpl` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: (byte[])"{"webServiceUrl":"http://chaos-pulsar-12-broker-2.chaos-pulsar-12-broker.chaos-12.svc.cluster.local:8080","pulsarServiceUrl":"pulsar://chaos-pulsar-12-broker-2.chaos-pulsar-12-broker.chaos-12.svc.cluster.local:6650","persistentTopicsEnabled":true,"nonPersistentTopicsEnabled":true,"cpu":{"usage":4.0274625060417675,"limit":100.0},"memory":{"usage":122.72758483886719,"limit":256.0},"directMemory":{"usage":32.0,"limit":256.0},"bandwidthIn":{"usage":19.836658735978933,"limit":1.024E7},"bandwidthOut":"[truncated 1667 bytes]; line: 1, column: 1283] (through reference chain: org.apache.pulsar.common.policies.data.Policies["bundles"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1601) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1375) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1322) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeFromArray(BeanDeserializer.java:640) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:221) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:197) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3643) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at org.apache.pulsar.metadata.cache.impl.JSONMetadataSerdeSimpleType.deserialize(JSONMetadataSerdeSimpleType.java:42) ~[io.streamnative-pulsar-metadata-2.10.0-rc-202111212205.jar:2.10.0-rc-202111212205]
	at org.apache.pulsar.metadata.cache.impl.MetadataCacheImpl.lambda$readValueFromStore$0(MetadataCacheImpl.java:107) ~[io.streamnative-pulsar-metadata-2.10.0-rc-202111212205.jar:2.10.0-rc-202111212205]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
	... 7 more
19:53:48.893 [metadata-store-6-1] WARN  com.github.benmanes.caffeine.cache.LocalAsyncCache - Exception thrown during asynchronous load
java.util.concurrent.CompletionException: org.apache.pulsar.metadata.api.MetadataStoreException$ContentDeserializationException: Failed to deserialize payload for key '/loadbalance/brokers/chaos-pulsar-12-broker-2.chaos-pulsar-12-broker.chaos-12.svc.cluster.local:8080'
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1074) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
	at org.apache.pulsar.metadata.impl.ZKMetadataStore.lambda$null$3(ZKMetadataStore.java:139) ~[io.streamnative-pulsar-metadata-2.10.0-rc-202111212205.jar:2.10.0-rc-202111212205]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.apache.pulsar.metadata.api.MetadataStoreException$ContentDeserializationException: Failed to deserialize payload for key '/loadbalance/brokers/chaos-pulsar-12-broker-2.chaos-pulsar-12-broker.chaos-12.svc.cluster.local:8080'
	at org.apache.pulsar.metadata.cache.impl.MetadataCacheImpl.lambda$readValueFromStore$0(MetadataCacheImpl.java:111) ~[io.streamnative-pulsar-metadata-2.10.0-rc-202111212205.jar:2.10.0-rc-202111212205]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
	... 7 more
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `org.apache.pulsar.common.policies.data.NamespaceIsolationDataImpl` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('http://chaos-pulsar-12-broker-2.chaos-pulsar-12-broker.chaos-12.svc.cluster.local:8080')
 at [Source: (byte[])"{"webServiceUrl":"http://chaos-pulsar-12-broker-2.chaos-pulsar-12-broker.chaos-12.svc.cluster.local:8080","pulsarServiceUrl":"pulsar://chaos-pulsar-12-broker-2.chaos-pulsar-12-broker.chaos-12.svc.cluster.local:6650","persistentTopicsEnabled":true,"nonPersistentTopicsEnabled":true,"cpu":{"usage":4.0274625060417675,"limit":100.0},"memory":{"usage":122.72758483886719,"limit":256.0},"directMemory":{"usage":32.0,"limit":256.0},"bandwidthIn":{"usage":19.836658735978933,"limit":1.024E7},"bandwidthOut":"[truncated 1667 bytes]; line: 1, column: 18] (through reference chain: java.util.LinkedHashMap["webServiceUrl"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1588) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1213) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromString(StdDeserializer.java:311) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1495) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:207) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:197) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:609) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:437) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3626) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at org.apache.pulsar.metadata.cache.impl.JSONMetadataSerdeTypeRef.deserialize(JSONMetadataSerdeTypeRef.java:44) ~[io.streamnative-pulsar-metadata-2.10.0-rc-202111212205.jar:2.10.0-rc-202111212205]
	at org.apache.pulsar.metadata.cache.impl.MetadataCacheImpl.lambda$readValueFromStore$0(MetadataCacheImpl.java:107) ~[io.streamnative-pulsar-metadata-2.10.0-rc-202111212205.jar:2.10.0-rc-202111212205]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
	... 7 more
19:53:48.894 [metadata-store-6-1] WARN  com.github.benmanes.caffeine.cache.LocalAsyncCache - Exception thrown during asynchronous load
java.util.concurrent.CompletionException: org.apache.pulsar.metadata.api.MetadataStoreException$ContentDeserializationException: Failed to deserialize payload for key '/loadbalance/brokers/chaos-pulsar-12-broker-2.chaos-pulsar-12-broker.chaos-12.svc.cluster.local:8080'
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1074) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
	at org.apache.pulsar.metadata.impl.ZKMetadataStore.lambda$null$3(ZKMetadataStore.java:139) ~[io.streamnative-pulsar-metadata-2.10.0-rc-202111212205.jar:2.10.0-rc-202111212205]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.apache.pulsar.metadata.api.MetadataStoreException$ContentDeserializationException: Failed to deserialize payload for key '/loadbalance/brokers/chaos-pulsar-12-broker-2.chaos-pulsar-12-broker.chaos-12.svc.cluster.local:8080'
	at org.apache.pulsar.metadata.cache.impl.MetadataCacheImpl.lambda$readValueFromStore$0(MetadataCacheImpl.java:111) ~[io.streamnative-pulsar-metadata-2.10.0-rc-202111212205.jar:2.10.0-rc-202111212205]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
	... 7 more
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `org.apache.pulsar.common.policies.data.impl.BundlesDataImpl` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: (byte[])"{"webServiceUrl":"http://chaos-pulsar-12-broker-2.chaos-pulsar-12-broker.chaos-12.svc.cluster.local:8080","pulsarServiceUrl":"pulsar://chaos-pulsar-12-broker-2.chaos-pulsar-12-broker.chaos-12.svc.cluster.local:6650","persistentTopicsEnabled":true,"nonPersistentTopicsEnabled":true,"cpu":{"usage":4.0274625060417675,"limit":100.0},"memory":{"usage":122.72758483886719,"limit":256.0},"directMemory":{"usage":32.0,"limit":256.0},"bandwidthIn":{"usage":19.836658735978933,"limit":1.024E7},"bandwidthOut":"[truncated 1667 bytes]; line: 1, column: 1283] (through reference chain: org.apache.pulsar.common.policies.data.LocalPolicies["bundles"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1601) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1375) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1322) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeFromArray(BeanDeserializer.java:640) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:221) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:197) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3643) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at org.apache.pulsar.metadata.cache.impl.JSONMetadataSerdeSimpleType.deserialize(JSONMetadataSerdeSimpleType.java:42) ~[io.streamnative-pulsar-metadata-2.10.0-rc-202111212205.jar:2.10.0-rc-202111212205]
	at org.apache.pulsar.metadata.cache.impl.MetadataCacheImpl.lambda$readValueFromStore$0(MetadataCacheImpl.java:107) ~[io.streamnative-pulsar-metadata-2.10.0-rc-202111212205.jar:2.10.0-rc-202111212205]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
	... 7 more
19:53:48.895 [metadata-store-6-1] WARN  com.github.benmanes.caffeine.cache.LocalAsyncCache - Exception thrown during asynchronous load
java.util.concurrent.CompletionException: org.apache.pulsar.metadata.api.MetadataStoreException$ContentDeserializationException: Failed to deserialize payload for key '/loadbalance/brokers/chaos-pulsar-12-broker-2.chaos-pulsar-12-broker.chaos-12.svc.cluster.local:8080'
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1074) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
	at org.apache.pulsar.metadata.impl.ZKMetadataStore.lambda$null$3(ZKMetadataStore.java:139) ~[io.streamnative-pulsar-metadata-2.10.0-rc-202111212205.jar:2.10.0-rc-202111212205]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.apache.pulsar.metadata.api.MetadataStoreException$ContentDeserializationException: Failed to deserialize payload for key '/loadbalance/brokers/chaos-pulsar-12-broker-2.chaos-pulsar-12-broker.chaos-12.svc.cluster.local:8080'
	at org.apache.pulsar.metadata.cache.impl.MetadataCacheImpl.lambda$readValueFromStore$0(MetadataCacheImpl.java:111) ~[io.streamnative-pulsar-metadata-2.10.0-rc-202111212205.jar:2.10.0-rc-202111212205]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
	... 7 more
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (byte[])"{"webServiceUrl":"http://chaos-pulsar-12-broker-2.chaos-pulsar-12-broker.chaos-12.svc.cluster.local:8080","pulsarServiceUrl":"pulsar://chaos-pulsar-12-broker-2.chaos-pulsar-12-broker.chaos-12.svc.cluster.local:6650","persistentTopicsEnabled":true,"nonPersistentTopicsEnabled":true,"cpu":{"usage":4.0274625060417675,"limit":100.0},"memory":{"usage":122.72758483886719,"limit":256.0},"directMemory":{"usage":32.0,"limit":256.0},"bandwidthIn":{"usage":19.836658735978933,"limit":1.024E7},"bandwidthOut":"[truncated 1667 bytes]; line: 1, column: 288] (through reference chain: java.util.LinkedHashMap["cpu"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1601) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1375) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1280) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.DeserializationContext.extractScalarFromObject(DeserializationContext.java:872) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:62) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:609) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:437) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3626) ~[com.fasterxml.jackson.core-jackson-databind-2.12.3.jar:2.12.3]
	at org.apache.pulsar.metadata.cache.impl.JSONMetadataSerdeTypeRef.deserialize(JSONMetadataSerdeTypeRef.java:44) ~[io.streamnative-pulsar-metadata-2.10.0-rc-202111212205.jar:2.10.0-rc-202111212205]
	at org.apache.pulsar.metadata.cache.impl.MetadataCacheImpl.lambda$readValueFromStore$0(MetadataCacheImpl.java:107) ~[io.streamnative-pulsar-metadata-2.10.0-rc-202111212205.jar:2.10.0-rc-202111212205]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
	... 7 more
19:53:48.895 [metadata-store-6-1] WARN  com.github.benmanes.caffeine.cache.LocalAsyncCache - Exception thrown during asynchronous load
java.util.concurrent.CompletionException: org.apache.pulsar.metadata.api.MetadataStoreException$ContentDeserializationException: Failed to deserialize payload for key '/loadbalance/brokers/chaos-pulsar-12-broker-2.chaos-pulsar-12-broker.chaos-12.svc.cluster.local:8080'
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1074) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
	at org.apache.pulsar.metadata.impl.ZKMetadataStore.lambda$null$3(ZKMetadataStore.java:139) ~[io.streamnative-pulsar-metadata-2.10.0-rc-202111212205.jar:2.10.0-rc-202111212205]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.apache.pulsar.metadata.api.MetadataStoreException$ContentDeserializationException: Failed to deserialize payload for key '/loadbalance/brokers/chaos-pulsar-12-broker-2.chaos-pulsar-12-broker.chaos-12.svc.cluster.local:8080'
	at org.apache.pulsar.metadata.cache.impl.MetadataCacheImpl.lambda$readValueFromStore$0(MetadataCacheImpl.java:111) ~[io.streamnative-pulsar-metadata-2.10.0-rc-202111212205.jar:2.10.0-rc-202111212205]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
	... 7 more
```

**Comment by mattisonchao** [comment]
can i try to work on it ? :)

**Comment by hangc0276** [comment]
@mattisonchao Thanks for your help, I have assigned it to you.

**Comment by mattisonchao** [comment]
sorry,  i could't reproduce it. could you give me more information ? i think maybe somethings is missing. :)

**Comment by mattisonchao** [comment]
I will close this issue until it re-produced.
