### ISSUE TITLE
[Transactions] SystemTopicBaseTxnBufferSnapshotService.close could hang forever

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#13103]
**Describe the bug**
SystemTopicBaseTxnBufferSnapshotService.close could hang forever.

Here's an example stacktrace from a test which was stuck:
```
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.13/Native Method)
        - parking to wait for  <0x00000000c9180010> (a java.util.concurrent.CompletableFuture$Signaller)
        at java.util.concurrent.locks.LockSupport.park(java.base@11.0.13/LockSupport.java:194)
        at java.util.concurrent.CompletableFuture$Signaller.block(java.base@11.0.13/CompletableFuture.java:1796)
        at java.util.concurrent.ForkJoinPool.managedBlock(java.base@11.0.13/ForkJoinPool.java:3128)
        at java.util.concurrent.CompletableFuture.waitingGet(java.base@11.0.13/CompletableFuture.java:1823)
        at java.util.concurrent.CompletableFuture.get(java.base@11.0.13/CompletableFuture.java:1998)
        at org.apache.pulsar.broker.systopic.SystemTopicClientBase.close(SystemTopicClientBase.java:100)
        at org.apache.pulsar.broker.service.SystemTopicBaseTxnBufferSnapshotService.close(SystemTopicBaseTxnBufferSnapshotService.java:83)
        at org.apache.pulsar.broker.PulsarService.closeAsync(PulsarService.java:451)
        at org.apache.pulsar.broker.PulsarService$MockitoMock$1941038334.closeAsync$accessor$2YWt8V2H(Unknown Source)
        at org.apache.pulsar.broker.PulsarService$MockitoMock$1941038334$auxiliary$vnSPbJ8Z.call(Unknown Source)
        at org.mockito.internal.invocation.RealMethod$FromCallable$1.call(RealMethod.java:40)
        at org.mockito.internal.invocation.RealMethod$FromBehavior.invoke(RealMethod.java:62)
        at org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:141)
        at org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:44)
        at org.mockito.Answers.answer(Answers.java:98)
        at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:106)
        at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
        at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:33)
        at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
        at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:56)
        at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptSuperCallable(MockMethodInterceptor.java:141)
        at org.apache.pulsar.broker.PulsarService$MockitoMock$1941038334.closeAsync(Unknown Source)
        at org.apache.pulsar.broker.PulsarService.close(PulsarService.java:352)
        at org.apache.pulsar.broker.PulsarService$MockitoMock$1941038334.close$accessor$2YWt8V2H(Unknown Source)
        at org.apache.pulsar.broker.PulsarService$MockitoMock$1941038334$auxiliary$scJJCpq9.call(Unknown Source)
        at org.mockito.internal.invocation.RealMethod$FromCallable$1.call(RealMethod.java:40)
        at org.mockito.internal.invocation.RealMethod$FromBehavior.invoke(RealMethod.java:62)
        at org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:141)
        at org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:44)
        at org.mockito.Answers.answer(Answers.java:98)
        at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:106)
        at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
        at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:33)
        at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
        at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:56)
        at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptSuperCallable(MockMethodInterceptor.java:141)
        at org.apache.pulsar.broker.PulsarService$MockitoMock$1941038334.close(Unknown Source)
        at org.apache.pulsar.broker.transaction.TransactionTestBase.internalCleanup(TransactionTestBase.java:295)
        at org.apache.pulsar.broker.transaction.buffer.TransactionBufferClientTest.cleanup(TransactionBufferClientTest.java:95)
```

[Full thread dump of all threads.](https://jstack.review/?https://gist.github.com/lhotari/ef19b7ee3596281c074ce36d0f95fa79#tda_1_dump)

**Comment by lhotari** [comment]
@315157973 @codelipenghui @gaoran10 @hangc0276 @congbobo184 @Renkai Could one of you take a look at this failure?

**Comment by syhily** [comment]
We met the same issue on Flink connector test. Any progress on this?

**Comment by syhily** [comment]
The thread dump for our test failure. It shows almost the same dead lock.

```
"main" #1 prio=5 os_prio=0 tid=0x00007ff99000b000 nid=0x207d waiting on condition [0x00007ff9991d3000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000f7173b40> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1707)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
	at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1742)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
	at org.apache.pulsar.broker.systopic.SystemTopicClientBase.close(SystemTopicClientBase.java:100)
	at org.apache.pulsar.broker.service.SystemTopicBaseTxnBufferSnapshotService.close(SystemTopicBaseTxnBufferSnapshotService.java:83)
	at org.apache.pulsar.broker.PulsarService.closeAsync(PulsarService.java:449)
	at org.apache.pulsar.broker.PulsarService.close(PulsarService.java:350)
```

[jps-traces.log](https://github.com/apache/pulsar/files/9469341/jps-traces.log)

**Comment by congbobo184** [comment]
@syhily What version of the broker are you using? 
Is this problem stable to reproduce or probably to happen? 
https://github.com/apache/pulsar/pull/17051 This pr may be fixed this problem, but I am not sure they are the same problem. Please provide the log of the client to determine whether they are the same problem

**Comment by syhily** [comment]
@congbobo184 We are using Pulsar 2.10.0. This issue is hard to reproduce, I think this could be some race conflict.

**Comment by syhily** [comment]
https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=33945&view=logs&j=fc5181b0-e452-5c8f-68de-1097947f6483&t=995c650b-6573-581c-9ce6-7ad4cc038461&l=28511

The detailed test pipeline can be checked on flink azure.

**Comment by congbobo184** [comment]
@syhily  hi
as you can see the jstack, thread block in `at org.apache.pulsar.broker.systopic.SystemTopicClientBase.close(SystemTopicClientBase.java:100)`, this close method is 

```
        List<CompletableFuture<Void>> futures = new ArrayList<>();
        List<Writer<T>> tempWriters = Lists.newArrayList(writers);
        tempWriters.forEach(writer -> futures.add(writer.closeAsync()));
        List<Reader<T>> tempReaders = Lists.newArrayList(readers);
        tempReaders.forEach(reader -> futures.add(reader.closeAsync()));
        writers.clear();
        readers.clear();
        return FutureUtil.waitForAll(futures);
```
only close producers or consumers can block the thread.
https://github.com/apache/pulsar/pull/17051 has to fix the close produce or consumer block thread problem, and I reproduce it in v2.10.0. carry this fix, I can't reproduce. can you test it with this fix? Maybe the problem can be solved

**Comment by syhily** [comment]
OK, I have tested. It seems like get fixed by this commit. Can you tell me which version it would be included?
