### ISSUE TITLE
Flaky-test: [org.apache.pulsar.client.api.BrokerServiceLookupTest].[testModularLoadManagerSplitBundle]

### ISSUE THREAD

**Issue by Jason918** [apache/pulsar#13125]
[org.apache.pulsar.client.api.BrokerServiceLookupTest] is flaky. The [testModularLoadManagerSplitBundle] test method fails sporadically.

[example failure](https://github.com/apache/pulsar/runs/4409105676?check_suite_focus=true#step:9:592)

```
Caused by: java.lang.AssertionError: did not expect [my-property/my-ns/0x00000000_0xffffffff] but found [my-property/my-ns/0x00000000_0xffffffff]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failEquals(Assert.java:1041)
	at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
	at org.testng.Assert.assertNotEquals(Assert.java:1531)
	at org.testng.Assert.assertNotEquals(Assert.java:1535)
	at org.apache.pulsar.client.api.BrokerServiceLookupTest.lambda$testModularLoadManagerSplitBundle$5(BrokerServiceLookupTest.java:742)
```

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in org.apache.pulsar.client.api.BrokerServiceLookupTest that uses org.apache.pulsar.broker.PulsarService, org.apache.pulsar.broker.PulsarServiceorg.apache.pulsar.common.naming.TopicName, org.apache.pulsar.common.naming.TopicNameorg.apache.pulsar.common.naming.NamespaceBundle did not expect [my-property/my-ns/0x00000000_0xffffffff] but found [my-property/my-ns/0x00000000_0xffffffff] within 10 seconds.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:679)
	at org.apache.pulsar.client.api.BrokerServiceLookupTest.testModularLoadManagerSplitBundle(BrokerServiceLookupTest.java:741)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.AssertionError: did not expect [my-property/my-ns/0x00000000_0xffffffff] but found [my-property/my-ns/0x00000000_0xffffffff]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failEquals(Assert.java:1041)
	at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
	at org.testng.Assert.assertNotEquals(Assert.java:1531)
	at org.testng.Assert.assertNotEquals(Assert.java:1535)
	at org.apache.pulsar.client.api.BrokerServiceLookupTest.lambda$testModularLoadManagerSplitBundle$5(BrokerServiceLookupTest.java:742)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:222)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:209)
	... 4 more

</pre></code>
</details>

**Comment by mattisonchao** [comment]
same to #13102

**Comment by Jason918** [comment]
Duplicated of #13102
