### ISSUE TITLE
Exception on creating sink on Java 17

### ISSUE THREAD

**Issue by marksilcox** [apache/pulsar#13290]
We are deploying Pulsar 2.8.1 to AWS using Ansible (following the playbook provided) and have started getting the exception below when creating a new sink. The playbook hasn't changed and has worked before in AWS (we currently have a number of environments running that were created with the same code).

I have noticed however that the latest AMI is using Java 17 and our other older ones are using Java 11.

```
11:36:20.748 [BookKeeperClientWorker-OrderedExecutor-0-0] ERROR org.apache.bookkeeper.common.util.SafeRunnable - Unexpected throwable caught
java.lang.ExceptionInInitializerError: null
        at org.apache.bookkeeper.proto.checksum.CRC32DigestManager$1.initialValue(CRC32DigestManager.java:42) ~[org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
        at org.apache.bookkeeper.proto.checksum.CRC32DigestManager$1.initialValue(CRC32DigestManager.java:39) ~[org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
        at io.netty.util.concurrent.FastThreadLocal.initialize(FastThreadLocal.java:177) ~[io.netty-netty-common-4.1.66.Final.jar:4.1.66.Final]
        at io.netty.util.concurrent.FastThreadLocal.get(FastThreadLocal.java:142) ~[io.netty-netty-common-4.1.66.Final.jar:4.1.66.Final]
        at org.apache.bookkeeper.proto.checksum.CRC32DigestManager.update(CRC32DigestManager.java:66) ~[org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
        at org.apache.bookkeeper.proto.checksum.DigestManager.computeDigestAndPackageForSending(DigestManager.java:114) ~[org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
        at org.apache.bookkeeper.client.PendingAddOp.safeRun(PendingAddOp.java:263) ~[org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [org.apache.bookkeeper-bookkeeper-common-4.14.2.jar:4.14.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.66.Final.jar:4.1.66.Final]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make private static int java.util.zip.CRC32.updateByteBuffer(int,long,int,int) accessible: module java.base does not "opens java.util.zip" to unnamed module @698076c3
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[?:?]
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
        at java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
        at java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
        at org.apache.bookkeeper.proto.checksum.DirectMemoryCRC32Digest.<clinit>(DirectMemoryCRC32Digest.java:81) ~[org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
        ... 12 more
11:36:20.751 [BookKeeperClientWorker-OrderedExecutor-0-0] ERROR org.apache.bookkeeper.common.util.SafeRunnable - Unexpected throwable caught
java.lang.NoClassDefFoundError: Could not initialize class org.apache.bookkeeper.proto.checksum.DirectMemoryCRC32Digest
        at org.apache.bookkeeper.proto.checksum.CRC32DigestManager$1.initialValue(CRC32DigestManager.java:42) ~[org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
        at org.apache.bookkeeper.proto.checksum.CRC32DigestManager$1.initialValue(CRC32DigestManager.java:39) ~[org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
        at io.netty.util.concurrent.FastThreadLocal.initialize(FastThreadLocal.java:177) ~[io.netty-netty-common-4.1.66.Final.jar:4.1.66.Final]
        at io.netty.util.concurrent.FastThreadLocal.get(FastThreadLocal.java:142) ~[io.netty-netty-common-4.1.66.Final.jar:4.1.66.Final]
        at org.apache.bookkeeper.proto.checksum.CRC32DigestManager.update(CRC32DigestManager.java:66) ~[org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
        at org.apache.bookkeeper.proto.checksum.DigestManager.computeDigestAndPackageForSending(DigestManager.java:114) ~[org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
        at org.apache.bookkeeper.client.PendingAddOp.safeRun(PendingAddOp.java:263) ~[org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [org.apache.bookkeeper-bookkeeper-common-4.14.2.jar:4.14.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.66.Final.jar:4.1.66.Final]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by Shoothzj** [comment]
@marksilcox it needs a higher version of bookkeeper

https://github.com/apache/bookkeeper/pull/2847

**Comment by Shoothzj** [comment]
@marksilcox currently, pulsar doesn't have a version to run on java17, I suggest you to use java11

**Comment by marksilcox** [comment]
@Shoothzj Thanks. Is the update to java17 on the roadmap?

**Comment by Shoothzj** [comment]
> @Shoothzj Thanks. Is the update to java17 on the roadmap?

I am not sure that `update to java17`, I think we will support `java17` to run..
Maybe in `2.10.0` ? @merlimat @codelipenghui
