### ISSUE TITLE
Functions: NullPointerException in FunctionStatsManager.reset

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#13358]
**Describe the bug**
I have seen this NPE in FunctionStatsManager.reset.
Probably it is a race while the function is still starting and it receives a "reset" request

**To Reproduce**
It is hard to reproduce it manually.

**Expected behavior**
No error

**Screenshots**
```
16:55:26.404 [function-timer-thread-6-1] ERROR org.apache.pulsar.functions.instance.stats.ComponentStatsManager - Failed to reset metrics for 1min window
java.lang.NullPointerException: null
    at org.apache.pulsar.functions.instance.stats.FunctionStatsManager.reset(FunctionStatsManager.java:425) ~[com.datastax.oss-pulsar-functions-instance-2.7.2.1.1.21.jar:2.7.2.1.1.21]
    at org.apache.pulsar.functions.instance.stats.ComponentStatsManager.lambda$new$0(ComponentStatsManager.java:81) ~[com.datastax.oss-pulsar-functions-instance-2.7.2.1.1.21.jar:2.7.2.1.1.21]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [java-instance.jar:?]
    at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Envrironment (please complete the following information):**
Pulsar 2.7.2 (actually Luna Streaming fork 2.7.2.1.1.21, but the code is the same as in Pulsar 2.7.2)
Functions with Process runtime on a system with tens of Functions bootstrapping concurrently

**Comment by tisonkun** [comment]
Closed as stale.

Now we're compiled with JDK 17 which can indicate which variable causes NPE. If it happens again, feel free to open a new issue so that we can investigate and fix.
