### ISSUE TITLE
python sdk bug "Pulsar error: IncompatibleSchema"

### ISSUE THREAD

**Issue by jack-tristan** [apache/pulsar#13419]
**Describe the bug**
python sdk bug "Pulsar error: IncompatibleSchema".

**To Reproduce**
1. schema v1 (mind the key `mmid`)
```
import pulsar
from pulsar.schema import *

class TaskMsgSchema(Record):
    #mmid = Long()
    uri = String()  
    bi = Integer()  
    db = Integer()  
    itemid = Integer()   
    tasks = Array(String())  
    redl = Boolean()  
    bk = String()


if __name__ == '__main__':
    msg = TaskMsgSchema()
    msg.uri = 'http://127.0.0.1'
    msg.bi = 83586          
    msg.db = 1              
    msg.itemid = 14966527   
    msg.tasks = ["star"]    
    msg.redl = True       
    msg.bk = "test_bucket"
    #msg.mmid = 8358680908399640577
    client = pulsar.Client('pulsar://10.200.19.39:6650,10.200.19.40:6650,10.200.19.41:6650')

    producer = client.create_producer('persistent://public/default/test-aero-v1', schema=AvroSchema(TaskMsgSchema))
```
2. schema v2 (mind the key `mmid`)
```
import pulsar
from pulsar.schema import *

class TaskMsgSchema(Record):
    mmid = Long()
    uri = String()  
    bi = Integer()  
    db = Integer()  
    itemid = Integer()   
    tasks = Array(String())  
    redl = Boolean()  
    bk = String()


if __name__ == '__main__':
    msg = TaskMsgSchema()
    msg.uri = 'http://127.0.0.1'
    msg.bi = 83586        
    msg.db = 1              
    msg.itemid = 14966527   
    msg.tasks = ["star"]    
    msg.redl = True         
    msg.bk = "test_bucket"
    msg.mmid = 8358680908399640577
    client = pulsar.Client('pulsar://10.200.19.39:6650,10.200.19.40:6650,10.200.19.41:6650')

    producer = client.create_producer('persistent://public/default/test-aero-v1', schema=AvroSchema(TaskMsgSchema))
```
3. pulsar schema setting:
```
AutoUpdate Strategy = Full
Schema Validation Enforced = Disabled
```

**Expected behavior**
Exception: Pulsar error: IncompatibleSchema

**Screenshots**
Error:
```
2021-12-21 10:26:47.133 WARN  [140086447261440] ClientConnection:1034 | [10.200.19.32:36558 -> 10.200.19.41:6650] Received error response from server: IncompatibleSchema (org.apache.pulsar.broker.service.schema.exceptions.IncompatibleSchemaException: org.apache.avro.SchemaValidationException: Unable to read schema:
{
  "type" : "record",
  "name" : "TaskMsgSchema",
  "fields" : [ {
    "name" : "bi",
    "type" : [ "null", "int" ]
  }, {
    "name" : "bk",
    "type" : [ "null", "string" ]
  }, {
    "name" : "db",
    "type" : [ "null", "int" ]
  }, {
    "name" : "itemid",
    "type" : [ "null", "int" ]
  }, {
    "name" : "redl",
    "type" : [ "null", "boolean" ]
  }, {
    "name" : "tasks",
    "type" : [ "null", {
      "type" : "array",
      "items" : "string"
    } ]
  }, {
    "name" : "uri",
    "type" : [ "null", "string" ]
  } ]
}
using schema:
{
  "type" : "record",
  "name" : "TaskMsgSchema",
  "fields" : [ {
    "name" : "bi",
    "type" : [ "null", "int" ]
  }, {
    "name" : "bk",
    "type" : [ "null", "string" ]
  }, {
    "name" : "db",
    "type" : [ "null", "int" ]
  }, {
    "name" : "itemid",
    "type" : [ "null", "int" ]
  }, {
    "name" : "mmid",
    "type" : [ "null", "long" ]
  }, {
    "name" : "redl",
    "type" : [ "null", "boolean" ]
  }, {
    "name" : "tasks",
    "type" : [ "null", {
      "type" : "array",
      "items" : "string"
    } ]
  }, {
    "name" : "uri",
    "type" : [ "null", "string" ]
  } ]
}) -- req_id: 0
2021-12-21 10:26:47.133 ERROR [140086447261440] ProducerImpl:239 | [persistent://public/default/test-aero-v1, ] Failed to create producer: IncompatibleSchema
2021-12-21 10:26:47.133 INFO  [140086447261440] ProducerImpl:564 | Producer - [persistent://public/default/test-aero-v1, ] , [batching  = off]
Traceback (most recent call last):
  File "ttt.py", line 28, in <module>
    producer = client.create_producer('test-aero-v1', schema=AvroSchema(TaskMsgSchema))
  File "/usr/local/python3/lib/python3.7/site-packages/pulsar/__init__.py", line 589, in create_producer
    p._producer = self._client.create_producer(topic, conf)
_pulsar.IncompatibleSchema: Pulsar error: IncompatibleSchema
```

**Desktop (please complete the following information):**
 - OS: centos7

**Additional context**
pulsar version is 2.6.3.
python pulsar-client  error version eg:2.6.3/2.7.2/2.8.1

**Comment by jack-tristan** [comment]
AutoUpdate Strategy = Full
Schema Validation Enforced = Disabled

**Comment by tisonkun** [comment]
- Closed as stale. The development of the Python client has been permanently moved to http://github.com/apache/pulsar-client-python. Please open an issue there if it's still relevant.
