### ISSUE TITLE
Broker health check with `TopicVersion.V2` failed

### ISSUE THREAD

**Issue by gaozhangmin** [apache/pulsar#13520]
1、Broker health check failed with `TopicVersion.V2` but it's ok with `TopicVersion.V1`, The failed reason is:
```
2021-12-27T13:21:17,350+0800 [pulsar-io-4-71] WARN  org.apache.pulsar.client.impl.BinaryProtoLookupService - [persistent://pulsar/hidden-ip:8080/healthcheck] failed to get Partitioned metadata : {"errorMsg":"Policies not found for pulsar/hidden-ip:8080 namespace","reqId":1293596554348340272, "remote":"", "local":""}
org.apache.pulsar.client.api.PulsarClientException$BrokerMetadataException: {"errorMsg":"Policies not found for pulsar/hidden-ip:8080 namespace","reqId":1293596554348340272, "remote":"", "local":""}
        at org.apache.pulsar.client.impl.ClientCnx.getPulsarClientException(ClientCnx.java:1154) ~[org.apache.pulsar-pulsar-client-original-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
        at org.apache.pulsar.client.impl.ClientCnx.handlePartitionResponse(ClientCnx.java:607) [org.apache.pulsar-pulsar-client-original-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
        at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:130) [org.apache.pulsar-pulsar
```
Policies not found for namespace  `pulsar/host:8080` under  znode `admin/policies`. 

But Why v1 is successful?  v1's healthcheck topic name is global, `checkReplication` is skipped.

I cannot decide the best solution to fix it.

**Comment by codelipenghui** [comment]
@gaozhangmin Can you reproduce the issue on 2.8.x or 2.9.1? We are enabled health checks for many clusters but never found such an anomaly.

**Comment by gaozhangmin** [comment]
> @gaozhangmin Can you reproduce the issue on 2.8.x or 2.9.1? We are enabled health checks for many clusters but never found such an anomaly.

Yes, i tested with  2.9.1.
