### ISSUE TITLE
[Bug] Producer timeout when sending message with huge properties.

### ISSUE THREAD

**Issue by Jason918** [apache/pulsar#13560]
**Describe the bug**
Producer timeout when sending message with huge properties.

**To Reproduce**
Add the following test case in `org.apache.pulsar.broker.admin.TopicPoliciesTest`
```
    @Test
    public void testMaxMessageSizeWithLargeHeader() throws Exception {
        this.conf.setMaxMessageSize(100);
        @Cleanup
        PulsarClient pulsarClient = newPulsarClient(lookupUrl.toString(), 0);
        @Cleanup
        Producer<byte[]> producer = pulsarClient.newProducer().topic(persistenceTopic).enableBatching(false).create();
        // this will throw PulsarClientException$TimeoutException
        producer.newMessage().property("P", RandomStringUtils.random(9000)).value(new byte[100]).send();
    }
```
Got the following exception:

> org.apache.pulsar.client.api.PulsarClientException$TimeoutException: The producer test-0-2 can not send message to the topic persistent://my-tenant/my-namespace/test-set-persistence within given timeout : createdAt 30.001 ns ago, firstSentAt 0.002 ns ago, lastSentAt 0.002 ns ago, retryCount 275
> 
> 	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:1008)
> 	at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.send(TypedMessageBuilderImpl.java:90)
> 	at org.apache.pulsar.broker.admin.TopicPoliciesTest.testMaxMessageSizeWithLargeHeader(TopicPoliciesTest.java:3058)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
> 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
> 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
> 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
> 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
> 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
> 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
> 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
> 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
> 	at org.testng.TestRunner.run(TestRunner.java:585)
> 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
> 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
> 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
> 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
> 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
> 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
> 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
> 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
> 	at org.testng.TestNG.runSuites(TestNG.java:1069)
> 	at org.testng.TestNG.run(TestNG.java:1037)
> 	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
> 	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)

**Expected behavior**
Send fail immediately. 

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**

N/A

**Comment by Jason918** [comment]
Key exception in broker:
2021-12-29T19:44:54,624+0800 [pulsar-io-6-21] WARN  org.apache.pulsar.broker.service.ServerCnx - [/127.0.0.1:60447] Got exception io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 10340: 20339 - discarded
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.fail(LengthFieldBasedFrameDecoder.java:503)
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.failIfNecessary(LengthFieldBasedFrameDecoder.java:489)
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.exceededFrameLength(LengthFieldBasedFrameDecoder.java:376)
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:419)
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:332)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by eolivelli** [comment]
What's the use case of having 'huge' properties?
This will be very bad for performances in any case, even we you enlarge the limits

**Comment by Jason918** [comment]
> What's the use case of having 'huge' properties? This will be very bad for performances in any case, even we you enlarge the limits

Yes, using 'huge' properties is not a good practice. 
Some pulsar user may not do it on purpose, but pulsar client does not forbid this.

The root cause of this case is that on the client side maxMessageSize check does not contains message header.

**Comment by Jason918** [comment]
Solved with PIP 132
