### ISSUE TITLE
Flaky-test: MultiTopicsReaderTest.testHasMessageAvailableAsync

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#13605]
MultiTopicsReaderTest is flaky. The testHasMessageAvailableAsync test method fails sporadically.

[example failure](https://github.com/apache/pulsar/runs/4702786250?check_suite_focus=true#step:9:1905)

```
 Error:  Tests run: 43, Failures: 14, Errors: 0, Skipped: 29, Time elapsed: 28.352 s <<< FAILURE! - in org.apache.pulsar.client.impl.MultiTopicsReaderTest
  Error:  testHasMessageAvailableAsync(org.apache.pulsar.client.impl.MultiTopicsReaderTest)  Time elapsed: 10.081 s  <<< FAILURE!
  org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.client.impl.MultiTopicsReaderTest.testHasMessageAvailableAsync() didn't finish within the time-out 10000
  	at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:371)
  	at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:282)
  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:605)
  	at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
  	at org.testng.TestRunner.run(TestRunner.java:585)
  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
  	at org.testng.TestNG.runSuites(TestNG.java:1069)
  	at org.testng.TestNG.run(TestNG.java:1037)
  	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeLazy(TestNGDirectoryTestSuite.java:123)
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:90)
  	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
  	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
  	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
  	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
  	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by lhotari** [comment]
This test was introduced by #13332 . @Demogorgon314 could you please take a look?

**Comment by lhotari** [comment]
yet another failure: https://github.com/apache/pulsar/runs/4714307973?check_suite_focus=true#step:9:1120

@Demogorgon314 could you please take a look? It might be a simple as increasing the 10000ms timeout. I'd suggest doubling it.

**Comment by Demogorgon314** [comment]
@lhotari Increasing the timeout might not work. I try it in my local env, we should find another way to fix it.

**Comment by lhotari** [comment]
> @lhotari Increasing the timeout might not work. I try it in my local env, we should find another way to fix it.

ok great. thanks for looking into the issue @Demogorgon314 . For reproducing CI issues, it can help to run the tests in a VM with low resources.

**Comment by Demogorgon314** [comment]
@lhotari I already pushed a patch, please take a look, thanks : )
