### ISSUE TITLE
Flaky-test: org.apache.pulsar.metadata.LockManagerTest.updateValue

### ISSUE THREAD

**Issue by Jason918** [apache/pulsar#13663]
org.apache.pulsar.metadata.LockManagerTest is flaky. The updateValue test method fails sporadically.

[example failure](https://github.com/apache/pulsar/runs/4735075630?check_suite_focus=true#step:8:4884)

```
java.lang.AssertionError: expected [value-2] but found [lock-1]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:629)
	at org.testng.Assert.assertEquals(Assert.java:639)
	at org.apache.pulsar.metadata.LockManagerTest.updateValue(LockManagerTest.java:148)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by shibd** [comment]
- I reproduced it,I'll try to fix it

**Comment by lhotari** [comment]
More failures: 

        
Flaky-test: org.apache.pulsar.metadata.LockManagerTest.updateValue
Number of failures: 6

org.apache.pulsar.metadata.LockManagerTest is flaky. The updateValue test method fails sporadically.

```
java.lang.AssertionError: expected [value-2] but found [lock-1]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:629)
	at org.testng.Assert.assertEquals(Assert.java:639)
	at org.apache.pulsar.metadata.LockManagerTest.updateValue(LockManagerTest.java:152)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.  
[example failure 2022-01-31T08:43:50.8742741Z](https://github.com/apache/pulsar/runs/5002911603?check_suite_focus=true?check_suite_focus=true#step:8:6996)  
[example failure 2022-01-30T11:03:51.9583217Z](https://github.com/apache/pulsar/runs/4996340534?check_suite_focus=true?check_suite_focus=true#step:8:1495)  
[example failure 2022-01-29T01:50:10.0422954Z](https://github.com/apache/pulsar/runs/4988529705?check_suite_focus=true?check_suite_focus=true#step:8:1497)  
[example failure 2022-01-28T16:12:01.4091105Z](https://github.com/apache/pulsar/runs/4983133951?check_suite_focus=true?check_suite_focus=true#step:8:1495)  
[example failure 2022-01-28T12:23:34.6850146Z](https://github.com/apache/pulsar/runs/4980334625?check_suite_focus=true?check_suite_focus=true#step:8:1495)  
[example failure 2022-01-28T02:52:35.6827048Z](https://github.com/apache/pulsar/runs/4975404880?check_suite_focus=true?check_suite_focus=true#step:8:10562)  


<details>
<summary>Full exception stacktrace</summary>
<code><pre>
java.lang.AssertionError: expected [value-2] but found [lock-1]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:629)
	at org.testng.Assert.assertEquals(Assert.java:639)
	at org.apache.pulsar.metadata.LockManagerTest.updateValue(LockManagerTest.java:152)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

</pre></code>
</details>

@shibd there are recent failures so I wonder if this is fixed. It's also possible that the failures were built with a SHA which didn't contain the fix.

**Comment by shibd** [comment]
@lhotari  Hi,I have tested the master branch for tens of thousands of times, and the not reproduce. I guess the above error is because PR is not  rebase master, and this SHA maybe not  included.

**Comment by lhotari** [comment]
> @lhotari Hi,I have tested the master branch for tens of thousands of times, and the not reproduce. I guess the above error is because PR is not rebase master, and this SHA maybe not included.

The PR run included the previous fix. I check this failure:  
[example failure 2022-01-31T08:43:50.8742741Z](https://github.com/apache/pulsar/runs/5002911603?check_suite_focus=true?check_suite_focus=true#step:8:6996)  

From the logs, you can see the revision for the build, it's [`a4cca4544615e1aeb62884066f1c6e3c79f6973d`](https://github.com/apache/pulsar/runs/5002911603?check_suite_focus=true?check_suite_focus=true#step:2:479)

You can check that it's included:
```
git fetch origin a4cca4544615e1aeb62884066f1c6e3c79f6973d
git checkout a4cca4544615e1aeb62884066f1c6e3c79f6973d
git log --grep="LockManagerTest.updateValue"
```

@shibd A lot of the problem in CI don't reproduce locally unless you simulate the CI environment by restricting the CPU & Memory resources. The GitHub Actions CI has 2 virtual CPUs and 7GB of RAM. I have been using a solution where I run tests in docker with `--cpus=0.8`. That usually reproduces issues which only happen with limited CPU resources. I have some shell functions in https://github.com/lhotari/pulsar-contributor-toolbox . The solution is for Linux docker environments.

Using the solution in pulsar-contributor-toolbox (this works only on Linux):
```
ptbx_build_coremodules
ptbx_until_test_fails_in_docker_with_logs --cpus=0.8 -pl pulsar-metadata -Dtest=LockManagerTest#updateValue
```
I tried a couple of rounds, but wasn't able to reproduce. It's possible that it's just very hard to reproduce.

**Comment by shibd** [comment]
> @shibd A lot of the problem in CI don't reproduce locally unless you simulate the CI environment by restricting the CPU & Memory resources. The GitHub Actions CI has 2 virtual CPUs and 7GB of RAM. I have been using a solution where I run tests in docker with --cpus=0.8. That usually reproduces issues which only happen with limited CPU resources. I have some shell functions in https://github.com/lhotari/pulsar-contributor-toolbox . The solution is for Linux docker environments.

@lhotari Nice! Thank you reply, I'll give it a try.
