### ISSUE TITLE
[branch-2.9]Flaky-test: BacklogQuotaManagerTest.testConsumerBacklogEvictionTimeQuotaWithEmptyLedger

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#13697]
https://github.com/apache/pulsar/runs/4763914497?check_suite_focus=true

```
Error:  Tests run: 34, Failures: 12, Errors: 0, Skipped: 13, Time elapsed: 119.582 s <<< FAILURE! - in org.apache.pulsar.broker.service.BacklogQuotaManagerTest
Error:  testConsumerBacklogEvictionTimeQuotaWithEmptyLedger(org.apache.pulsar.broker.service.BacklogQuotaManagerTest)  Time elapsed: 0.222 s  <<< FAILURE!
java.lang.AssertionError: expected [2] but found [0]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.pulsar.broker.service.BacklogQuotaManagerTest.testConsumerBacklogEvictionTimeQuotaWithEmptyLedger(BacklogQuotaManagerTest.java:508)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by codelipenghui** [comment]
branch-2.8 also failed https://github.com/apache/pulsar/runs/4763565931?check_suite_focus=true

**Comment by mattisonchao** [comment]
@codelipenghui  i can work on it.

**Comment by codelipenghui** [comment]
@mattisonchao I noticed @gaozhangmin already fixed the issue. Please check other issues.
