### ISSUE TITLE
cpp client coredump

### ISSUE THREAD

**Issue by paladin-dalao** [apache/pulsar#13735]
**Describe the bug**

There was a sudden crash when our service was running

**To Reproduce**

I don't konw how to reproduce

**Expected behavior**

```
Missing separate debuginfos, use: debuginfo-install glibc-2.17-106.tl2.5.x86_64 libgcc-4.8.5-4.el7.x86_64 libstdc++-4.8.5-4.el7.x86_64
(gdb) bt
#0  __shared_count (__r=..., this=0x7fc6f9bbf3c8) at /usr/local/include/c++/4.8.2/bits/shared_ptr_base.h:696
#1  std::__shared_ptr<pulsar::ClientImpl, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<pulsar::ClientImpl> (this=this@entry=0x7fc6f9bbf3c0, __r=...) at /usr/local/include/c++/4.8.2/bits/shared_ptr_base.h:807
#2  0x0000000000ce184b in shared_ptr<pulsar::ClientImpl> (__r=<error reading variable: Cannot access memory at address 0x8>, this=0x7fc6f9bbf3c0) at /usr/local/include/c++/4.8.2/bits/shared_ptr.h:249
#3  shared_from_this (this=0x0) at /usr/local/include/c++/4.8.2/bits/shared_ptr.h:557
#4  pulsar::ClientImpl::getConnection (this=0x0, topic="persistent://public/data/druid_log591-partition-5") at /data/commlibsrc/pulsar-2.6.4/pulsar-client-cpp/lib/ClientImpl.cc:399
#5  0x0000000000d113a1 in pulsar::HandlerBase::grabCnx (this=0x772ae018) at /data/commlibsrc/pulsar-2.6.4/pulsar-client-cpp/lib/HandlerBase.cc:56
#6  0x0000000000d1186c in pulsar::HandlerBase::handleTimeout (ec=..., handler=std::shared_ptr (count 4, weak 2) 0x772ae018) at /data/commlibsrc/pulsar-2.6.4/pulsar-client-cpp/lib/HandlerBase.cc:145
#7  0x0000000000d12bdc in __call<void, boost::system::error_code const&, 0ul, 1ul> (__args=<optimized out>, this=0x7fc6f9bbf8b0) at /usr/local/include/c++/4.8.2/functional:1296
#8  operator()<const boost::system::error_code&, void> (this=0x7fc6f9bbf8b0) at /usr/local/include/c++/4.8.2/functional:1355
#9  operator() (this=0x7fc6f9bbf8b0) at /usr/local/include/boost/asio/detail/bind_handler.hpp:47
#10 asio_handler_invoke<boost::asio::detail::binder1<std::_Bind<void (*(std::_Placeholder<1>, std::shared_ptr<pulsar::HandlerBase>))(const boost::system::error_code&, std::shared_ptr<pulsar::HandlerBase>)>, boost::system::error_code> > (function=<error reading variable: access outside bounds of object referenced via synthetic pointer>) at /usr/local/include/boost/asio/handler_invoke_hook.hpp:64
#11 invoke<boost::asio::detail::binder1<std::_Bind<void (*(std::_Placeholder<1>, std::shared_ptr<pulsar::HandlerBase>))(const boost::system::error_code&, std::shared_ptr<pulsar::HandlerBase>)>, boost::system::error_code>, std::_Bind<void (*(std::_Placeholder<1>, std::shared_ptr<pulsar::HandlerBase>))(const boost::system::error_code&, std::shared_ptr<pulsar::HandlerBase>)> > (context=..., function=...)
    at /usr/local/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#12 boost::asio::detail::wait_handler<std::_Bind<void (*(std::_Placeholder<1>, std::shared_ptr<pulsar::HandlerBase>))(boost::system::error_code const&, std::shared_ptr<pulsar::HandlerBase>)> >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) (owner=0xbef89a0, base=0x26f769bd0) at /usr/local/include/boost/asio/detail/wait_handler.hpp:70
#13 0x0000000000d089af in complete (bytes_transferred=<optimized out>, ec=..., owner=..., this=0x26f769bd0) at /usr/local/include/boost/asio/detail/task_io_service_operation.hpp:37
#14 do_run_one (ec=..., this_thread=..., lock=..., this=0xbef89a0) at /usr/local/include/boost/asio/detail/impl/task_io_service.ipp:384
#15 boost::asio::detail::task_io_service::run (this=0xbef89a0, ec=...) at /usr/local/include/boost/asio/detail/impl/task_io_service.ipp:153
#16 0x0000000000d05086 in run (this=<optimized out>) at /usr/local/include/boost/asio/impl/io_service.ipp:59
#17 pulsar::ExecutorService::startWorker (this=<optimized out>, io_service=...) at /data/commlibsrc/pulsar-2.6.4/pulsar-client-cpp/lib/ExecutorService.cc:41
#18 0x0000000000d08f02 in operator()<std::shared_ptr<boost::asio::io_service>&, void> (__object=<optimized out>, this=<optimized out>) at /usr/local/include/c++/4.8.2/functional:601
#19 __call<void, 0ul, 1ul> (__args=<optimized out>, this=<optimized out>) at /usr/local/include/c++/4.8.2/functional:1296
#20 operator()<, void> (this=<optimized out>) at /usr/local/include/c++/4.8.2/functional:1355
#21 _M_invoke<> (this=<optimized out>) at /usr/local/include/c++/4.8.2/functional:1732
#22 operator() (this=<optimized out>) at /usr/local/include/c++/4.8.2/functional:1720
#23 std::thread::_Impl<std::_Bind_simple<std::_Bind<std::_Mem_fn<void (pulsar::ExecutorService::*)(std::shared_ptr<boost::asio::io_service>)> (pulsar::ExecutorService*, std::shared_ptr<boost::asio::io_service>)> ()> >::_M_run() (this=<optimized out>) at /usr/local/include/c++/4.8.2/thread:115
#24 0x00000000013fa6a0 in std::(anonymous namespace)::execute_native_thread_routine (__p=<optimized out>) at ../../../.././libstdc++-v3/src/c++11/thread.cc:84
#25 0x00007fd34e245dc5 in start_thread () from /lib64/libpthread.so.0
#26 0x00007fd34d55d29d in clone () from /lib64/libc.so.6
(gdb) 

```

**Additional context**

**Comment by paladin-dalao** [comment]
@sijie 
Is there a conclusion to this question?

**Comment by tisonkun** [comment]
Closed as stale.

The development of the C++ client has been permanently moved to https://github.com/apache/pulsar-client-cpp. If it's still relevant, please open an issue there.
