### ISSUE TITLE
Flaky-test: BrokerServiceLookupTest#testPartitionTopicLookup

### ISSUE THREAD

**Issue by gaozhangmin** [apache/pulsar#13996]
https://github.com/apache/pulsar/runs/4975389461?check_suite_focus=true
```
Error:  Tests run: 19, Failures: 4, Errors: 0, Skipped: 12, Time elapsed: 182.018 s <<< FAILURE! - in org.apache.pulsar.client.api.BrokerServiceLookupTest
Error:  testPartitionTopicLookup(org.apache.pulsar.client.api.BrokerServiceLookupTest)  Time elapsed: 60.945 s  <<< FAILURE!
org.apache.pulsar.client.admin.PulsarAdminException$TimeoutException: java.util.concurrent.TimeoutException
	at org.apache.pulsar.client.admin.internal.BaseResource.sync(BaseResource.java:299)
	at org.apache.pulsar.client.admin.internal.TopicsImpl.deletePartitionedTopic(TopicsImpl.java:447)
	at org.apache.pulsar.client.admin.Topics.deletePartitionedTopic(Topics.java:618)
	at org.apache.pulsar.client.admin.internal.TopicsImpl.deletePartitionedTopic(TopicsImpl.java:437)
	at org.apache.pulsar.client.api.BrokerServiceLookupTest.testPartitionTopicLookup(BrokerServiceLookupTest.java:405)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at org.apache.pulsar.client.admin.internal.BaseResource.sync(BaseResource.java:292)
	... 16 more
```

**Comment by lhotari** [comment]
duplicates #14046
