### ISSUE TITLE
Flaky-test: PartitionedProducerImplTest.testCustomMessageRouterInstance

### ISSUE THREAD

**Issue by michaeljmarshall** [apache/pulsar#14001]
PartitionedProducerImplTest is flaky. The [testCustomMessageRouterInstance] test method fails sporadically.

https://github.com/apache/pulsar/runs/4973925656?check_suite_focus=true

```
Error:  testCustomMessageRouterInstance(org.apache.pulsar.client.impl.PartitionedProducerImplTest)  Time elapsed: 0.028 s  <<< FAILURE!
java.lang.IllegalArgumentException: Illegal initial time
	at org.apache.pulsar.client.impl.Backoff.<init>(Backoff.java:71)
	at org.apache.pulsar.client.impl.BackoffBuilder.create(BackoffBuilder.java:62)
	at org.apache.pulsar.client.impl.ProducerImpl.<init>(ProducerImpl.java:260)
	at org.apache.pulsar.client.impl.PartitionedProducerImplTest.lambda$setup$0(PartitionedProducerImplTest.java:88)
	at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:42)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:56)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptSuperCallable(MockMethodInterceptor.java:145)
	at org.apache.pulsar.client.impl.PulsarClientImpl$MockitoMock$1945256498.newProducerImpl(Unknown Source)
	at org.apache.pulsar.client.impl.PartitionedProducerImpl.lambda$createProducer$2(PartitionedProducerImpl.java:185)
	at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.put(ConcurrentOpenHashMap.java:302)
	at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap.computeIfAbsent(ConcurrentOpenHashMap.java:151)
	at org.apache.pulsar.client.impl.PartitionedProducerImpl.createProducer(PartitionedProducerImpl.java:183)
	at org.apache.pulsar.client.impl.PartitionedProducerImpl.start(PartitionedProducerImpl.java:152)
	at org.apache.pulsar.client.impl.PartitionedProducerImpl.<init>(PartitionedProducerImpl.java:99)
	at org.apache.pulsar.client.impl.PartitionedProducerImplTest.getMessageRouter(PartitionedProducerImplTest.java:161)
	at org.apache.pulsar.client.impl.PartitionedProducerImplTest.testCustomMessageRouterInstance(PartitionedProducerImplTest.java:116)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by michaeljmarshall** [comment]
Oops, this wasn't a flaky test, it was a legitimate test failure!
