### ISSUE TITLE
Flaky-test: PulsarLedgerIdGeneratorTest#testGenerateLedgerId

### ISSUE THREAD

**Issue by gaozhangmin** [apache/pulsar#14002]
https://github.com/apache/pulsar/runs/4961312358?check_suite_focus=true

```
Error:  Tests run: 13, Failures: 1, Errors: 0, Skipped: 6, Time elapsed: 37.366 s <<< FAILURE! - in org.apache.pulsar.metadata.bookkeeper.PulsarLedgerIdGeneratorTest
Error:  testGenerateLedgerId(org.apache.pulsar.metadata.bookkeeper.PulsarLedgerIdGeneratorTest)  Time elapsed: 11.632 s  <<< FAILURE!
java.lang.AssertionError: Error occur during ledger id generation :  expected [0] but found [2]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.apache.pulsar.metadata.bookkeeper.PulsarLedgerIdGeneratorTest.testGenerateLedgerId(PulsarLedgerIdGeneratorTest.java:113)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by RobertIndie** [comment]
Another failure: https://github.com/apache/pulsar/runs/6505830937?check_suite_focus=true
