### ISSUE TITLE
Flaky-test: LockManagerTest.updateValueWhenVersionIsOutOfSync

### ISSUE THREAD

**Issue by michaeljmarshall** [apache/pulsar#14016]
LockManagerTest is flaky. The updateValueWhenVersionIsOutOfSync test method fails sporadically.

https://github.com/apache/pulsar/runs/4977106658

```
 Error:  updateValueWhenVersionIsOutOfSync(org.apache.pulsar.metadata.LockManagerTest)  Time elapsed: 0.069 s  <<< FAILURE!
java.lang.AssertionError: expected [value-2] but found [lock-1]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:629)
	at org.testng.Assert.assertEquals(Assert.java:639)
	at org.apache.pulsar.metadata.LockManagerTest.updateValueWhenVersionIsOutOfSync(LockManagerTest.java:180)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by michaeljmarshall** [comment]
When I run `mvn -pl :pulsar-metadata clean test -Dtest="LockManagerTest"` locally (after having already run `mvn -Pcore-modules,-main -T 1C clean install -DskipTests -Dspotbugs.skip=true` for the current code), I am seeing other test failures as well. When I ran `mvn -pl :pulsar-metadata clean test -Dtest="LockManagerTest#updateValueWhenVersionIsOutOfSync"`, the test passed.
