### ISSUE TITLE
Flaky-test: [org.apache.pulsar.client.impl.ProducerSemaphoreTest].[testEnsureNotBlockOnThePendingQueue]

### ISSUE THREAD

**Issue by Jason918** [apache/pulsar#14036]
[org.apache.pulsar.client.impl.ProducerSemaphoreTest] is flaky. The [testEnsureNotBlockOnThePendingQueue] test method fails sporadically.

[example failure](https://github.com/apache/pulsar/runs/4989275706?check_suite_focus=true#step:9:708)

```
Error:  testEnsureNotBlockOnThePendingQueue(org.apache.pulsar.client.impl.ProducerSemaphoreTest)  Time elapsed: 0.232 s  <<< FAILURE!
java.lang.AssertionError: expected [0] but found [1]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.pulsar.client.impl.ProducerSemaphoreTest.testEnsureNotBlockOnThePendingQueue(ProducerSemaphoreTest.java:158)
```

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
full exception stacktrace here
</pre></code>
</details>

**Comment by tisonkun** [comment]
Closed as stale. If it comes back, let's open a new issue and refer here.
