### ISSUE TITLE
Cannot set topic retention policy (error 500)

### ISSUE THREAD

**Issue by flowchartsman** [apache/pulsar#14031]
**Describe the bug**
I have a namespace with 4 day retention policy:
```
pulsar-admin namespaces create tenant/ns
pulsar-admin namespaces set-retention --size -1 --time 4d tenant/ns
```
I also have topic-level policy enabled:

```
# Enable or disable system topic
systemTopicEnabled=true

# The schema compatibility strategy to use for system topics
systemTopicSchemaCompatibilityStrategy=ALWAYS_COMPATIBLE

# Enable or disable topic level policies, topic level policies depends on the system topic
# Please enable the system topic first.
topicLevelPoliciesEnabled=true
```

When I attempt to turn off the retention policy for a single topic, I get either an error 504(Bad gateway) when going through pulsar-proxy or an error 500 if issuing the command from the broker with pulsar-admin:

```
./pulsar-admin topics set-retention -s 0 -t 0 tenant/ns/mytopic
00:20:36.472 [AsyncHttpClient-7-1] WARN  org.apache.pulsar.client.admin.internal.BaseResource - [http://localhost:8080/admin/v2/persistent/tenant/ns/mytopic/retention] Failed to perform http post request: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
HTTP 500 Internal Server Error
```

The result is the same when attempting to change size or time to any value, not just 0. There is nothing in the broker or pulsar-proxy logs to indicate the nature of this failure.  `get-retention` for the topic appears to work (returns `null`), and `delete-retention` appears to succeed, even though no retention policy is set for the topic, but I cannot be sure, since I cannot set the policy for the topic.

**Expected behavior**
Topic policy changed

**Desktop (please complete the following information):**
 - OS: n/a

**Additional context**
The build is at current HEAD for 2.7 branch, so `2.7.5-SNAPSHOT`

**Comment by mattisonchao** [comment]
I can help with this issue.

**Comment by flowchartsman** [comment]
Thank you, @mattisonchao, please let me know if I can provide any further information.

**Comment by mattisonchao** [comment]
@flowchartsman  I can not reproduce this issue at 2.7 branches.
Could you give me more detail to help me?

![image](https://user-images.githubusercontent.com/74767115/153154506-06202dba-a5ec-4049-a712-bf4668111897.png)

**Comment by flowchartsman** [comment]
```
21:52:06.450 [pulsar-client-io-60-1] ERROR org.apache.pulsar.client.impl.ProducerImpl - [persistent://tenantname/namespacename/__change_events] [null] Failed to create producer: 112 request timedout after ms 30000
21:52:06.451 [pulsar-client-io-60-1] ERROR org.apache.pulsar.broker.admin.impl.PersistentTopicsBase - [null] Failed to perform setRetention on topic persistent://tenantname/namespacename/topicname
org.apache.pulsar.client.api.PulsarClientException$TimeoutException: 112 request timedout after ms 30000
        at org.apache.pulsar.client.impl.ClientCnx.checkRequestTimeout(ClientCnx.java:1076) ~[org.apache.pulsar-pulsar-client-original-2.7.5-SNAPSHOT.jar:2.7.5-SNAPSHOT]
        at org.apache.pulsar.client.impl.ClientCnx.lambda$channelActive$0(ClientCnx.java:201) ~[org.apache.pulsar-pulsar-client-original-2.7.5-SNAPSHOT.jar:2.7.5-SNAPSHOT]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) [io.netty-netty-common-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:176) [io.netty-netty-common-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty-netty-common-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [io.netty-netty-common-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) [io.netty-netty-transport-native-epoll-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [io.netty-netty-common-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty-netty-common-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.68.Final.jar:4.1.68.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
21:52:06.455 [pulsar-client-io-60-1] INFO  org.eclipse.jetty.server.RequestLog - 192.168.10.5 - - [09/Feb/2022:21:51:18 +0000] "POST /admin/v2/persistent/tenantname/namespacename/topicname/retention?authoritative=false HTTP/1.1" 500 1119 "-" "Pulsar-Java-v2.8.0" 48367
21:52:06.455 [pulsar-client-io-60-1] WARN  org.apache.pulsar.client.impl.ClientCnx - [id: 0xa662f391, L:/172.18.0.4:52114 - R:192.168.2.198/192.168.2.198:6650] 112 request timedout after ms 30000192.168.2
```

**Comment by mattisonchao** [comment]
@flowchartsman 
What is your ``concurrentLookupRequest`` config value? it seems some resources block cause request timeout.

**Comment by flowchartsman** [comment]
```
maxConcurrentLookupRequest=50000
```

**Comment by mattisonchao** [comment]
@flowchartsman   This PR may already fix these problems. 
https://github.com/apache/pulsar/pull/14503
https://github.com/apache/pulsar/pull/14293

**Comment by flowchartsman** [comment]
This appears to have been resolved by an update.
