### ISSUE TITLE
Java client: ConsumerBuilder: java.lang.IllegalArgumentException: properties cannot be empty

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#14072]
**Describe the bug**
If I pass an empty map to ConsumerBuilder#properties I get this error.
It is very annoying in case you have a set of properties that is dynamically generated.
We can just simply ignore the call to ConsumerBuilder is case of empty properties.

```
java.lang.IllegalArgumentException: properties cannot be empty
	at org.apache.pulsar.shade.com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
	at org.apache.pulsar.client.impl.ConsumerBuilderImpl.properties(ConsumerBuilderImpl.java:335)
```

**Additional context**
Pulsar 2.8.2 onwards

**Comment by eolivelli** [comment]
the same applies for the ProducerBuilder, please fix it as well
