### ISSUE TITLE
Flaky-test: MetadataCacheTest.readModifyUpdate

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#14096]
MetadataCacheTest is flaky. The readModifyUpdate test method fails sporadically.

[example failure](https://github.com/apache/pulsar/runs/5039382127?check_suite_focus=true#step:8:1501)

```
Error:  Tests run: 56, Failures: 1, Errors: 0, Skipped: 15, Time elapsed: 41.519 s <<< FAILURE! - in org.apache.pulsar.metadata.MetadataCacheTest
Error:  readModifyUpdate(org.apache.pulsar.metadata.MetadataCacheTest)  Time elapsed: 0.047 s  <<< FAILURE!
java.lang.AssertionError: expected [2] but found [1]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.pulsar.metadata.MetadataCacheTest.readModifyUpdate(MetadataCacheTest.java:462)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by Demogorgon314** [comment]
This flaky test can be closed by #14283
