### ISSUE TITLE
Flaky-test: org.apache.pulsar.client.api.MemoryLimitTest#testRejectMessages

### ISSUE THREAD

**Issue by gaozhangmin** [apache/pulsar#14220]
https://github.com/apache/pulsar/runs/5138925372?check_suite_focus=true
```
Error:  Tests run: 8, Failures: 2, Errors: 0, Skipped: 6, Time elapsed: 11.631 s <<< FAILURE! - in org.apache.pulsar.client.api.MemoryLimitTest
Error:  testRejectMessages(org.apache.pulsar.client.api.MemoryLimitTest)  Time elapsed: 2.115 s  <<< FAILURE!
java.lang.AssertionError: expected [103424] but found [62464]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:797)
	at org.testng.Assert.assertEquals(Assert.java:807)
	at org.apache.pulsar.client.api.MemoryLimitTest.testRejectMessages(MemoryLimitTest.java:86)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by nicoloboschi** [comment]
@codelipenghui after you cherry-picked it to branch-2.8 the test now fails in this way
```
Error:  Tests run: 8, Failures: 2, Errors: 0, Skipped: 6, Time elapsed: 20.321 s <<< FAILURE! - in org.apache.pulsar.client.api.MemoryLimitTest
Error:  testRejectMessages(org.apache.pulsar.client.api.MemoryLimitTest)  Time elapsed: 5.156 s  <<< FAILURE!
org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in org.apache.pulsar.client.api.MemoryLimitTest that uses org.apache.pulsar.client.impl.ProducerImpl was not fulfilled within 5 seconds.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:864)
	at org.apache.pulsar.client.api.MemoryLimitTest.testRejectMessages(MemoryLimitTest.java:90)
```
See here: https://github.com/apache/pulsar/runs/5598419996?check_suite_focus=true
@gaozhangmin could you look at that?

**Comment by codelipenghui** [comment]
@nicoloboschi I have reverted this one in branch-2.8

**Comment by nicoloboschi** [comment]
@codelipenghui I cherry-picked again and it fails again https://github.com/apache/pulsar/runs/5847872746?check_suite_focus=true
