### ISSUE TITLE
[proxy] [2.10.0] Proxy throws type conversion exception on startup, won't start

### ISSUE THREAD

**Issue by utahkay** [apache/pulsar#14357]
**Describe the bug**
In 2.10.0, the proxy throws an exception on startup in StreamNative Cloud environment.

**To Reproduce**
1. Deploy streamnative 2.10.0.0-rc5 into cloud hosted environment.
2. Observe the proxy logs.

**Expected behavior**
Expect the proxy to start up successfully.

**Logs**
```
2022-02-16T17:56:26,370+0000 [main] ERROR org.apache.pulsar.proxy.server.ProxyServiceStarter - Failed to start pulsar proxy service. error msg failed to initialize zooKeeperCacheExpirySeconds field while setting value -1additionalServletDirectory=./proxyAdditionalServlet
java.lang.IllegalArgumentException: failed to initialize zooKeeperCacheExpirySeconds field while setting value -1additionalServletDirectory=./proxyAdditionalServlet
	at org.apache.pulsar.common.util.FieldParser.lambda$update$0(FieldParser.java:149) ~[io.streamnative-pulsar-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
	at org.apache.pulsar.common.util.FieldParser.update(FieldParser.java:138) ~[io.streamnative-pulsar-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	at org.apache.pulsar.common.configuration.PulsarConfigurationLoader.create(PulsarConfigurationLoader.java:98) ~[io.streamnative-pulsar-broker-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	at org.apache.pulsar.common.configuration.PulsarConfigurationLoader.create(PulsarConfigurationLoader.java:75) ~[io.streamnative-pulsar-broker-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	at org.apache.pulsar.common.configuration.PulsarConfigurationLoader.create(PulsarConfigurationLoader.java:55) ~[io.streamnative-pulsar-broker-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	at org.apache.pulsar.proxy.server.ProxyServiceStarter.<init>(ProxyServiceStarter.java:144) [io.streamnative-pulsar-proxy-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	at org.apache.pulsar.proxy.server.ProxyServiceStarter.main(ProxyServiceStarter.java:184) [io.streamnative-pulsar-proxy-2.10.0.0-rc5.jar:2.10.0.0-rc5]
Caused by: java.lang.RuntimeException: Cannot convert from java.lang.String to java.lang.Integer. Conversion failed with null
	at org.apache.pulsar.common.util.FieldParser.convert(FieldParser.java:122) ~[io.streamnative-pulsar-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	at org.apache.pulsar.common.util.FieldParser.value(FieldParser.java:193) ~[io.streamnative-pulsar-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	at org.apache.pulsar.common.util.FieldParser.lambda$update$0(FieldParser.java:144) ~[io.streamnative-pulsar-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.pulsar.common.util.FieldParser.convert(FieldParser.java:118) ~[io.streamnative-pulsar-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	at org.apache.pulsar.common.util.FieldParser.value(FieldParser.java:193) ~[io.streamnative-pulsar-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	at org.apache.pulsar.common.util.FieldParser.lambda$update$0(FieldParser.java:144) ~[io.streamnative-pulsar-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	... 8 more
Caused by: java.lang.NumberFormatException: For input string: "-1additionalServletDirectory=./proxyAdditionalServlet"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:652) ~[?:?]
	at java.lang.Integer.valueOf(Integer.java:983) ~[?:?]
	at org.apache.pulsar.common.util.FieldParser.stringToInteger(FieldParser.java:265) ~[io.streamnative-pulsar-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.pulsar.common.util.FieldParser.convert(FieldParser.java:118) ~[io.streamnative-pulsar-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	at org.apache.pulsar.common.util.FieldParser.value(FieldParser.java:193) ~[io.streamnative-pulsar-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	at org.apache.pulsar.common.util.FieldParser.lambda$update$0(FieldParser.java:144) ~[io.streamnative-pulsar-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	... 8 more
```

**Desktop (please complete the following information):**

**Additional context**

**Comment by utahkay** [comment]
The root cause appears to be that proxy.conf does not have a newline at end of file.

When additional config settings are appended by the cloud hosted environment, the conf file looks like this:

```
# ZooKeeper cache expiry time in seconds
# Deprecated: use metadataStoreCacheExpirySeconds
zooKeeperCacheExpirySeconds=-1additionalServletDirectory=./proxyAdditionalServlet
additionalServlets=prometheus-proxy-servlet
```
