### ISSUE TITLE
Flaky-test: NamespacesTest.testDeleteNamespaceWithBundles

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#14516]
NamespacesTest.testDeleteNamespaceWithBundles is flaky. It fails sporadically.

[example failure](https://github.com/apache/pulsar/runs/5375478775?check_suite_focus=true#step:11:269)

```
Error:  testDeleteNamespaceWithBundles(org.apache.pulsar.broker.admin.NamespacesTest)  Time elapsed: 5.182 s  <<< FAILURE!
Wanted but not invoked:
asyncResponse.resume(<Capturing argument>);
-> at org.apache.pulsar.broker.admin.NamespacesTest.testDeleteNamespaceWithBundles(NamespacesTest.java:853)

However, there was exactly 1 interaction with this mock:
asyncResponse.resume(
    org.apache.pulsar.broker.web.RestException: Failed to find ownership for ServiceUnit:my-tenant/use/test-delete-namespace-with-bundles/0x00000000_0x80000000
);
-> at org.apache.pulsar.broker.admin.AdminResource.resumeAsyncResponseExceptionally(AdminResource.java:761)


	at org.apache.pulsar.broker.admin.NamespacesTest.testDeleteNamespaceWithBundles(NamespacesTest.java:853)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by Technoboy-** [comment]
> This flaky test might be related to #14215 . @Technoboy- please check

Ok.

**Comment by lhotari** [comment]
another failure: https://github.com/apache/pulsar/runs/5389017187?check_suite_focus=true#step:11:270

@Technoboy- it seems that this is very flaky since it appears very often.

**Comment by shibd** [comment]
+1 https://github.com/apache/pulsar/runs/5388581170?check_suite_focus=true#step:11:1759

**Comment by Technoboy-** [comment]
> +1 https://github.com/apache/pulsar/runs/5388581170?check_suite_focus=true#step:11:1759

Do you have time to help take a look at this ?

**Comment by shibd** [comment]
> Do you have time to help take a look at this ?

Ok, I'll try to fix it.

**Comment by shibd** [comment]
Sorry, I didn't reproduce for local. I looked at the test code. It should be that the following code sequence is wrong.

Before delete a namespace, We should mock all done. 847 lines of code should be executed after 851 lines of code.

https://github.com/apache/pulsar/blob/4f1e39b6921ea401b8c27f17a041d06d85f8abf8/pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java#L847-L851

Otherwise, a null pointer may happen during verification `isServiceUnitOwned`

https://github.com/apache/pulsar/blob/4f1e39b6921ea401b8c27f17a041d06d85f8abf8/pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java#L584

Final throw RestException

https://github.com/apache/pulsar/blob/4f1e39b6921ea401b8c27f17a041d06d85f8abf8/pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java#L608-L610

@Jason918  PTAL
