### ISSUE TITLE
"reason": "download/pulsar_functions/function17065127734302601489.tmp"

### ISSUE THREAD

**Issue by JackrayWang** [apache/pulsar#14536]
```
curl --location --request POST 'http://192.168.228.59:8080/admin/v3/functions/wyl/alert/function-01?version=2.9.1' \
--form 'functionConfig="{\"className\":\"com.huawei.isap.function.WordCountFunction\",\"inputs\":[\"alert_data\"],\"output\":\"persistent://wyl/alert/alert_final_data\",\"parallelism\":4}";type=application/json' \
--form 'url="functions://wyl/alert/pulsar-function-01@0.1"'
```

```
{
    "reason": "download/pulsar_functions/function17065127734302601489.tmp"
}
```

**Comment by JackrayWang** [comment]
I can not see errors in broker log file.

Is some config error?

@eolivelli Thanks.

**Comment by JackrayWang** [comment]
I refer to the URL request constructed by the following code.

  ```
  @POST
    @ApiOperation(value = "Creates a new Pulsar Function in cluster mode")
    @ApiResponses(value = {
            @ApiResponse(code = 403, message = "The requester doesn't have admin permissions"),
            @ApiResponse(code = 400, message = "Invalid request (The Pulsar Function already exists, etc.)"),
            @ApiResponse(code = 408, message = "Request timeout"),
            @ApiResponse(code = 200, message = "Pulsar Function successfully created")
    })
    @Path("/{tenant}/{namespace}/{functionName}")
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    public void registerFunction(
            @ApiParam(value = "The tenant of a Pulsar Function")
            final @PathParam("tenant") String tenant,
            @ApiParam(value = "The namespace of a Pulsar Function")
            final @PathParam("namespace") String namespace,
            @ApiParam(value = "The name of a Pulsar Function")
            final @PathParam("functionName") String functionName,
            final @FormDataParam("data") InputStream uploadedInputStream,
            final @FormDataParam("data") FormDataContentDisposition fileDetail,
            final @FormDataParam("url") String functionPkgUrl,
            @ApiParam(
                    value = "You can submit a function (in any languages that you are familiar with) \n"
                            + "to a Pulsar cluster. Follow the steps below. \n"
                            + "1. Create a JSON object using some of the following parameters.\n"
                            + "A JSON value presenting configuration payload of a Pulsar Function.\n"
                            + " An example of the expected Pulsar Function can be found here.\n"
                            + "- **autoAck**\n"
                            + "  Whether or not the framework acknowledges messages automatically.\n"
                            + "- **runtime**\n"
                            + "  What is the runtime of the Pulsar Function. Possible Values: [JAVA, PYTHON, GO]\n"
                            + "- **resources**\n"
                            + "  The size of the system resources allowed by the Pulsar Function runtime."
                            + " The resources include: cpu, ram, disk.\n"
                            + "- **className**\n"
                            + "  The class name of a Pulsar Function.\n"
                            + "- **customSchemaInputs**\n"
                            + "  The map of input topics to Schema class names (specified as a JSON object).\n"
                            + "- **customSerdeInputs**\n"
                            + "  The map of input topics to SerDe class names (specified as a JSON object).\n"
                            + "- **deadLetterTopic**\n"
                            + "  Messages that are not processed successfully are sent to `deadLetterTopic`.\n"
                            + "- **runtimeFlags**\n"
                            + "  Any flags that you want to pass to the runtime."
                            + " Note that in thread mode, these flags have no impact.\n"
                            + "- **fqfn**\n"
                            + "  The Fully Qualified Function Name (FQFN) for the Pulsar Function.\n"
                            + "- **inputSpecs**\n"
                            + "   The map of input topics to its consumer configuration,"
                            + " each configuration has schema of "
                            + "   {\"schemaType\": \"type-x\", \"serdeClassName\": \"name-x\","
                            + " \"isRegexPattern\": true, \"receiverQueueSize\": 5}\n"
                            + "- **inputs**\n"
                            + "  The input topic or topics (multiple topics can be specified as"
                            + " a comma-separated list) of a Pulsar Function.\n"
                            + "- **jar**\n"
                            + "  Path to the JAR file for the Pulsar Function"
                            + " (if the Pulsar Function is written in Java). "
                            + "  It also supports URL path [http/https/file (file protocol assumes that file "
                            + "  already exists on worker host)] from which worker can download the package.\n"
                            + "- **py**\n"
                            + "  Path to the main Python file or Python wheel file for the"
                            + " Pulsar Function (if the Pulsar Function is written in Python).\n"
                            + "- **go**\n"
                            + "  Path to the main Go executable binary for the Pulsar Function"
                            + " (if the Pulsar Function is written in Go).\n"
                            + "- **logTopic**\n"
                            + "  The topic to which the logs of a Pulsar Function are produced.\n"
                            + "- **maxMessageRetries**\n"
                            + "  How many times should we try to process a message before giving up.\n"
                            + "- **output**\n"
                            + "  The output topic of a Pulsar Function"
                            + " (If none is specified, no output is written).\n"
                            + "- **outputSerdeClassName**\n"
                            + "  The SerDe class to be used for messages output by the Pulsar Function.\n"
                            + "- **parallelism**\n"
                            + "  The parallelism factor of a Pulsar Function"
                            + " (i.e. the number of a Pulsar Function instances to run).\n"
                            + "- **processingGuarantees**\n"
                            + "  The processing guarantees (that is, delivery semantics)"
                            + " applied to the Pulsar Function."
                            + "  Possible Values: [ATLEAST_ONCE, ATMOST_ONCE, EFFECTIVELY_ONCE]\n"
                            + "- **retainOrdering**\n"
                            + "  Function consumes and processes messages in order.\n"
                            + "- **outputSchemaType**\n"
                            + "   Represents either a builtin schema type (for example: 'avro', 'json', ect)"
                            + " or the class name for a Schema implementation."
                            + "- **subName**\n"
                            + "  Pulsar source subscription name. User can specify a subscription-name"
                            + " for the input-topic consumer.\n"
                            + "- **windowConfig**\n"
                            + "  The window configuration of a Pulsar Function.\n"
                            + "- **timeoutMs**\n"
                            + "  The message timeout in milliseconds.\n"
                            + "- **topicsPattern**\n"
                            + "  The topic pattern to consume from a list of topics under a namespace"
                            + " that match the pattern."
                            + "  [input] and [topic-pattern] are mutually exclusive. Add SerDe class name for a "
                            + "  pattern in customSerdeInputs (supported for java fun only)\n"
                            + "- **userConfig**\n"
                            + "  A map of user-defined configurations (specified as a JSON object).\n"
                            + "- **secrets**\n"
                            + "  This is a map of secretName(that is how the secret is going to be accessed"
                            + " in the Pulsar Function via context) to an object that"
                            + "  encapsulates how the secret is fetched by the underlying secrets provider."
                            + " The type of an value here can be found by the"
                            + "  SecretProviderConfigurator.getSecretObjectType() method. \n"
                            + "- **cleanupSubscription**\n"
                            + "  Whether the subscriptions of a Pulsar Function created or used should be deleted"
                            + " when the Pulsar Function is deleted.\n"
                            + "2. Encapsulate the JSON object to a multipart object.",
                    examples = @Example(
                            value = {
                                @ExampleProperty(
                                    mediaType = MediaType.TEXT_PLAIN,
                                    value = " Example \n"
                                            + "\n"
                                            + " 1. Create a JSON object. \n"
                                            + "\n"
                                            + "{\n"
                                            + "\t\"inputs\": \"persistent://public/default/input-topic\",\n"
                                            + "\t\"parallelism\": \"4\",\n"
                                            + "\t\"output\": \"persistent://public/default/output-topic\",\n"
                                            + "\t\"log-topic\": \"persistent://public/default/log-topic\",\n"
                                            + "\t\"classname\": \"org.example.test.ExclamationFunction\",\n"
                                            + "\t\"jar\": \"java-function-1.0-SNAPSHOT.jar\"\n"
                                            + "}\n"
                                            + "\n"
                                            + "\n"
                                            + "2. Encapsulate the JSON object to a multipart object (in Python). \n"
                                            + "\n"
                                            + "from requests_toolbelt.multipart.encoder import MultipartEncoder \n"
                                            + "mp_encoder = MultipartEncoder( \n"
                                            + "\t[('functionConfig', "
                                            + "(None, json.dumps(config), 'application/json'))])\n"
                                )
                            }
                    )
            )
            final @FormDataParam("functionConfig") FunctionConfig functionConfig) {
        functions().registerFunction(tenant, namespace, functionName, uploadedInputStream, fileDetail,
            functionPkgUrl, functionConfig, clientAppId(), clientAuthData());
    }
```

**Comment by JackrayWang** [comment]
Where can I find the file named "download/pulsar_functions/function17065127734302601489.tmp"

**Comment by JackrayWang** [comment]
```
Invalid register Function request @ /wyl/alert/function-01
java.nio.file.NoSuchFileException: download/pulsar_functions/function4815395680403053409.tmp
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:370) ~[?:?]
	at java.nio.file.Files.createFile(Files.java:647) ~[?:?]
	at java.nio.file.TempFileHelper.create(TempFileHelper.java:137) ~[?:?]
	at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:160) ~[?:?]
	at java.nio.file.Files.createTempFile(Files.java:867) ~[?:?]
	at org.apache.pulsar.functions.worker.rest.api.FunctionsImpl.downloadPackageFile(FunctionsImpl.java:774) ~[org.apache.pulsar-pulsar-functions-worker-2.9.1.jar:2.9.1]
	at org.apache.pulsar.functions.worker.rest.api.FunctionsImpl.downloadPackageFile(FunctionsImpl.java:763) ~[org.apache.pulsar-pulsar-functions-worker-2.9.1.jar:2.9.1]
	at org.apache.pulsar.functions.worker.rest.api.FunctionsImpl.registerFunction(FunctionsImpl.java:158) ~[org.apache.pulsar-pulsar-functions-worker-2.9.1.jar:2.9.1]
	at org.apache.pulsar.broker.admin.impl.FunctionsBase.registerFunction(FunctionsBase.java:183) ~[org.apache.pulsar-pulsar-broker-2.9.1.jar:2.9.1]
	at jdk.internal.reflect.GeneratedMethodAccessor160.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[org.glassfish.jersey.core-jersey-server-2.34.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[org.glassfish.jersey.core-jersey-server-2.34.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[org.glassfish.jersey.core-jersey-server-2.34.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:159) ~[org.glassfish.jersey.core-jersey-server-2.34.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[org.glassfish.jersey.core-jersey-server-2.34.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475) ~[org.glassfish.jersey.core-jersey-server-2.34.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397) ~[org.glassfish.jersey.core-jersey-server-2.34.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[org.glassfish.jersey.core-jersey-server-2.34.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255) ~[org.glassfish.jersey.core-jersey-server-2.34.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[org.glassfish.jersey.core-jersey-common-2.34.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[org.glassfish.jersey.core-jersey-common-2.34.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[org.glassfish.jersey.core-jersey-common-2.34.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[org.glassfish.jersey.core-jersey-common-2.34.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[org.glassfish.jersey.core-jersey-common-2.34.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[org.glassfish.jersey.core-jersey-common-2.34.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) ~[org.glassfish.jersey.core-jersey-server-2.34.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) ~[org.glassfish.jersey.core-jersey-server-2.34.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) ~[org.glassfish.jersey.containers-jersey-container-servlet-core-2.34.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) ~[org.glassfish.jersey.containers-jersey-container-servlet-core-2.34.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366) ~[org.glassfish.jersey.containers-jersey-container-servlet-core-2.34.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319) ~[org.glassfish.jersey.containers-jersey-container-servlet-core-2.34.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) ~[org.glassfish.jersey.containers-jersey-container-servlet-core-2.34.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[org.eclipse.jetty-jetty-servlet-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626) ~[org.eclipse.jetty-jetty-servlet-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.apache.pulsar.broker.web.ResponseHandlerFilter.doFilter(ResponseHandlerFilter.java:67) ~[org.apache.pulsar-pulsar-broker-2.9.1.jar:2.9.1]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[org.eclipse.jetty-jetty-servlet-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[org.eclipse.jetty-jetty-servlet-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548) ~[org.eclipse.jetty-jetty-servlet-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[org.eclipse.jetty-jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[org.eclipse.jetty-jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[org.eclipse.jetty-jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434) ~[org.eclipse.jetty-jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[org.eclipse.jetty-jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) ~[org.eclipse.jetty-jetty-servlet-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[org.eclipse.jetty-jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[org.eclipse.jetty-jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349) ~[org.eclipse.jetty-jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[org.eclipse.jetty-jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234) ~[org.eclipse.jetty-jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146) ~[org.eclipse.jetty-jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179) ~[org.eclipse.jetty-jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[org.eclipse.jetty-jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[org.eclipse.jetty-jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388) ~[org.eclipse.jetty-jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633) [org.eclipse.jetty-jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380) [org.eclipse.jetty-jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) [org.eclipse.jetty-jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [org.eclipse.jetty-jetty-io-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [org.eclipse.jetty-jetty-io-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [org.eclipse.jetty-jetty-io-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) [org.eclipse.jetty-jetty-util-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) [org.eclipse.jetty-jetty-util-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) [org.eclipse.jetty-jetty-util-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [org.eclipse.jetty-jetty-util-9.4.43.v20210629.jar:9.4.43.v20210629]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386) [org.eclipse.jetty-jetty-util-9.4.43.v20210629.jar:9.4.43.v20210629]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.72.Final.jar:4.1.72.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]

```

**Comment by JackrayWang** [comment]
```
{
    "reason": "java.nio.file.FileAlreadyExistsException: download/pulsar_functions/function12666420312234369421.tmp"
}
```

**Comment by JackrayWang** [comment]
And I can see the files as following。
```
[root@host-192-168-228-107 pulsar_functions]# pwd
/opt/apache-pulsar-2.9.1/download/pulsar_functions
[root@host-192-168-228-107 pulsar_functions]# ll
total 4
-rw------- 1 root root    0 Mar  4 11:08 function12666420312234369421.tmp
-rw------- 1 root root    0 Mar  4 11:10 function9999152526472097262.tmp
```
