### ISSUE TITLE
unsubscribe doesn't work if bookkeeper is outage

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#1459]
#### Expected behavior

if bookkeeper is outage due to disk fillup, admins want to unsubscribe a subscription to clear backlog. the unsubscribe should work.

#### Actual behavior

unsubscribe at ptn level fail with 404.
unsubscribe at topic level fail with 404.
unsubscribe at namespace level fail with 500.

NPE is found when unsubscribing a subscription from a namespace.

```
Mar 28 01:56:03 ip-10-0-0-19.ec2.internal pulsar[28836]: 01:56:02.961 [pulsar-web-25-1] INFO  org.apache.pulsar.broker.web.PulsarWebResource - Successfully validated clusters on property [benchmark]
Mar 28 01:56:03 ip-10-0-0-19.ec2.internal pulsar[28836]: 01:56:02.961 [pulsar-web-25-1] ERROR org.apache.pulsar.broker.admin.impl.NamespacesBase - [null] Failed to unsubscribe sub-000 for namespace benchmark/local/ns-JQGPJ5A/0xac000000_0xb0000000
Mar 28 01:56:03 ip-10-0-0-19.ec2.internal pulsar[28836]: java.lang.NullPointerException: null
Mar 28 01:56:03 ip-10-0-0-19.ec2.internal pulsar[28836]: at org.apache.pulsar.broker.service.BrokerService.getAllTopicsFromNamespaceBundle(BrokerService.java:1025) ~[org.apache.pulsar-pulsar-broker-2.0.0-incubating-SNAPSHOT.jar:2.0.0-incubating-SNAPSHOT]
Mar 28 01:56:03 ip-10-0-0-19.ec2.internal pulsar[28836]: at org.apache.pulsar.broker.admin.impl.NamespacesBase.unsubscribe(NamespacesBase.java:1123) [org.apache.pulsar-pulsar-broker-2.0.0-incubating-SNAPSHOT.jar:2.0.0-incubating-SNAPSHOT]
Mar 28 01:56:03 ip-10-0-0-19.ec2.internal pulsar[28836]: at org.apache.pulsar.broker.admin.impl.NamespacesBase.internalUnsubscribeNamespaceBundle(NamespacesBase.java:965) [org.apache.pulsar-pulsar-broker-2.0.0-incubating-SNAPSHOT.jar:2.0.0-incubating-SNAPSHOT]
Mar 28 01:56:03 ip-10-0-0-19.ec2.internal pulsar[28836]: at org.apache.pulsar.broker.admin.v1.Namespaces.unsubscribeNamespaceBundle(Namespaces.java:684) [org.apache.pulsar-pulsar-broker-2.0.0-incubating-SNAPSHOT.jar:2.0.0-incubating-SNAPSHOT]
Mar 28 01:56:03 ip-10-0-0-19.ec2.internal pulsar[28836]: at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source) ~[?:?]
Mar 28 01:56:03 ip-10-0-0-19.ec2.internal pulsar[28836]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
Mar 28 01:56:03 ip-10-0-0-19.ec2.internal pulsar[28836]: at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
Mar 28 01:56:03 ip-10-0-0-19.ec2.internal pulsar[28836]: at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [org.glassfish.jersey.core-jersey-server-2.25.jar:?]
Mar 28 01:56:03 ip-10-0-0-19.ec2.internal pulsar[28836]: at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [org.glassfish.jersey.core-jersey-server-2.25.jar:?]
Mar 28 01:56:03 ip-10-0-0-19.ec2.internal pulsar[28836]: at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [org.glassfish.jersey.core-jersey-server-2.25.jar:?]
Mar 28 01:56:03 ip-10-0-0-19.ec2.internal pulsar[28836]: at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:143) [org.glassfish.jersey.core-jersey-server-2.25.jar:?]
Mar 28 01:56:03 ip-10-0-0-19.ec2.internal pulsar[28836]: at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [org.glassfish.jersey.core-jersey-server-2.25.jar:?]
Mar 28 01:56:03 ip-10-0-0-19.ec2.internal pulsar[28836]: at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [org.glassfish.jersey.core-jersey-server-2.25.jar:?]
Mar 28 01:56:03 ip-10-0-0-19.ec2.internal pulsar[28836]: at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [org.glassfish.jersey.core-jersey-server-2.25.jar:?]
Mar 28 01:56:03 ip-10-0-0-19.ec2.internal pulsar[28836]: at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [org.glassfish.jersey.core-jersey-server-2.25.jar:?]
Mar 28 01:56:03 ip-10-0-0-19.ec2.internal pulsar[28836]: at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [org.glassfish.jersey.core-jersey-server-2.25.jar:?]
Mar 28 01:56:03 ip-10-0-0-19.ec2.internal pulsar[28836]: at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [org.glassfish.jersey.core-jersey-common-2.25.jar:?]
Mar 28 01:56:03 ip-10-0-0-19.ec2.internal pulsar[28836]: at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [org.glassfish.jersey.core-jersey-common-2.25.jar:?]
Mar 28 01:56:03 ip-10-0-0-19.ec2.internal pulsar[28836]: at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [org.glassfish.jersey.core-jersey-common-2.25.jar:?]
Mar 28 01:56:03 ip-10-0-0-19.ec2.internal pulsar[28836]: at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [org.glassfish.jersey.core-jersey-common-2.25.jar:?]
Mar 28 01:56:03 ip-10-0-0-19.ec2.internal pulsar[28836]: at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [org.glassfish.jersey.core-jersey-common-2.25.jar:?]
Mar 28 01:56:03 ip-10-0-0-19.ec2.internal pulsar[28836]: at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [org.glassfish.jersey.core-jersey-common-2.25.jar:?]
```

#### Steps to reproduce

fill-up the disks to cause bookkeeper outage, and run unsubscribe.

#### System configuration
**Pulsar version**: master

**Comment by ConcurrencyPractitioner** [comment]
Hi @sijie, 
Could you assign this issue to me?
I'm interested in picking this one up.

**Comment by sijie** [comment]
@ConcurrencyPractitioner : that's cool! Unfortunately Github doesn't allow assign issues to users who don't have write permissions. We just use comments to track who is working on this. 

Assigned to @ConcurrencyPractitioner - he will pick this up.

**Comment by ConcurrencyPractitioner** [comment]
Oh, one more thing. How did you fill-up the disks? 

I did a search on how to do it. And I found that they used something like this (a Linux command):
dd if=/dev/zero of=filename bs=1 count=1 seek=$((10*1024*1024*1024))
or
fallocate -l 5G file
Is this the way you did it?

**Comment by ConcurrencyPractitioner** [comment]
Hi,
I changed the configs as follows:
[change.pdf](https://github.com/apache/pulsar/files/2705451/change.pdf)

And I ran the following test:
https://github.com/apache/pulsar/blob/master/pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java#L1265

I wasn't able to replicate the error. Was this the right approach?

**Comment by ConcurrencyPractitioner** [comment]
Ok, so I realized that we need to use PulsarAdmin to unsubscribe once we are done. But how do we connect this back to Bookkeeper? I ran through the tests and saw a few examples where Pulsar Admin and bkEnsemble (LocalBookkeeperEnsemble) was used in conjunction. So should we tweak the ServerConfigurations of those BookkeeperServers to replicate this test error?

**Comment by sijie** [comment]
@ConcurrencyPractitioner - this issue requires you understand how managed ledger works and as well as how bookie works. If you want to replicate this test, you don't better not use standalone or local ensemble, since standalone hardcodes the disk thresholds. you need to try set with a cluster of bookies and reduce the disk threshold to a small values, which it will enforce all the bookies in readonly modes.

**Comment by ConcurrencyPractitioner** [comment]
Hi @sijie,

I did try adding a test to stimulate the outage. Not sure if this was what you were thinking about.
https://github.com/apache/pulsar/commit/d7bf197367c24475adea3be51fb33869b6a071e3

**Comment by ConcurrencyPractitioner** [comment]
Oh, I realized this approach might not be best. I will probably add a spec to PulsarClusterSpec signaling when to have a near zero value for DiskUsageThreshold.

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to maintain versions.
