### ISSUE TITLE
Flaky-test: SubscriptionSeekTest. testSeekForBatchMessageAndSpecifiedBatchIndex

### ISSUE THREAD

**Issue by shibd** [apache/pulsar#14676]
SubscriptionSeekTest. testSeekForBatchMessageAndSpecifiedBatchIndex is flaky. It fails sporadically.

[example failure](https://github.com/apache/pulsar/runs/5534041774?check_suite_focus=true#step:9:2226)

```
Error:  Tests run: 21, Failures: 1, Errors: 0, Skipped: 12, Time elapsed: 15.006 s <<< FAILURE! - in org.apache.pulsar.broker.service.SubscriptionSeekTest
Error:  testSeekForBatchMessageAndSpecifiedBatchIndex(org.apache.pulsar.broker.service.SubscriptionSeekTest)  Time elapsed: 0.09 s  <<< FAILURE!
org.apache.pulsar.client.api.PulsarClientException$ConsumerBusyException: {"errorMsg":"Exclusive consumer is already connected","reqId":1201333508522616164, "remote":"localhost/127.0.0.1:36071", "local":"/127.0.0.1:54928"}
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:1038)
	at org.apache.pulsar.client.impl.ConsumerBuilderImpl.subscribe(ConsumerBuilderImpl.java:101)
	at org.apache.pulsar.broker.service.SubscriptionSeekTest.testSeekForBatchMessageAndSpecifiedBatchIndex(SubscriptionSeekTest.java:240)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by llIlll** [comment]
Please assign me, i can fix him.
