### ISSUE TITLE
Failed to initialize DNS Resolver org.apache.pulsar.bookie.rackawareness.BookieRackAffinityMapping

### ISSUE THREAD

**Issue by gaozhangmin** [apache/pulsar#14690]
pulsar version: 2.10.0
With configuration 
`reppDnsResolverClass=org.apache.pulsar.bookie.rackawareness.BookieRackAffinityMapping`

```
2022-03-15T13:11:57,872+0800 [main] ERROR org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl - Failed to initialize DNS Resolver org.apache.pulsar.bookie.rackawareness.BookieRackAffinityMapping, used default subnet resolver
java.lang.RuntimeException: METADATA_STORE_INSTANCE configuration was not set in the BK client configuration
        at org.apache.pulsar.bookie.rackawareness.BookieRackAffinityMapping.setConf(BookieRackAffinityMapping.java:71) ~[org.apache.pulsar-pulsar-broker-common-2.10.0.jar:2.10.0]
        at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl.initialize(RackawareEnsemblePlacementPolicyImpl.java:265) [org.apache.bookkeeper-bookkeeper-server-4.14.4.jar:4.14.4]
        at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl.initialize(RackawareEnsemblePlacementPolicyImpl.java:80) [org.apache.bookkeeper-bookkeeper-server-4.14.4.jar:4.14.4]
        at org.apache.bookkeeper.client.BookKeeper.initializeEnsemblePlacementPolicy(BookKeeper.java:581) [org.apache.bookkeeper-bookkeeper-server-4.14.4.jar:4.14.4]
        at org.apache.bookkeeper.client.BookKeeper.<init>(BookKeeper.java:505) [org.apache.bookkeeper-bookkeeper-server-4.14.4.jar:4.14.4]
        at org.apache.bookkeeper.client.BookKeeper.<init>(BookKeeper.java:344) [org.apache.bookkeeper-bookkeeper-server-4.14.4.jar:4.14.4]
        at org.apache.bookkeeper.client.BookKeeperAdmin.<init>(BookKeeperAdmin.java:165) [org.apache.bookkeeper-bookkeeper-server-4.14.4.jar:4.14.4]
        at org.apache.bookkeeper.server.http.BKHttpServiceProvider.<init>(BKHttpServiceProvider.java:94) [org.apache.bookkeeper-bookkeeper-server-4.14.4.jar:4.14.4]
        at org.apache.bookkeeper.server.http.BKHttpServiceProvider.<init>(BKHttpServiceProvider.java:75) [org.apache.bookkeeper-bookkeeper-server-4.14.4.jar:4.14.4]
        at org.apache.bookkeeper.server.http.BKHttpServiceProvider$Builder.build(BKHttpServiceProvider.java:161) [org.apache.bookkeeper-bookkeeper-server-4.14.4.jar:4.14.4]
        at org.apache.bookkeeper.server.Main.buildBookieServer(Main.java:332) [org.apache.bookkeeper-bookkeeper-server-4.14.4.jar:4.14.4]
        at org.apache.bookkeeper.server.Main.doMain(Main.java:226) [org.apache.bookkeeper-bookkeeper-server-4.14.4.jar:4.14.4]
        at org.apache.bookkeeper.server.Main.main(Main.java:208) [org.apache.bookkeeper-bookkeeper-server-4.14.4.jar:4.14.4]
```

**Comment by codelipenghui** [comment]
@gaozhangmin Looks like it's a regression in 2.10.0 RC?

**Comment by gaozhangmin** [comment]
> @gaozhangmin Looks like it's a regression in 2.10.0 RC?

Yes. it's ok for 2.9
