### ISSUE TITLE
[Broker] Failed to read speed for nic

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#14906]
**Describe the bug**
Pulsar v2.8.3

15:53:46.332 [pulsar-load-manager-1-1] ERROR org.apache.pulsar.broker.loadbalance.impl.LinuxBrokerHostUsageImpl - Failed to read speed for nic virbr0-nic
```
java.io.IOException: Invalid argument
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_251]
        at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:46) ~[?:1.8.0_251]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_251]
        at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[?:1.8.0_251]
        at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:159) ~[?:1.8.0_251]
        at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65) ~[?:1.8.0_251]
        at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109) ~[?:1.8.0_251]
        at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103) ~[?:1.8.0_251]
        at java.nio.file.Files.read(Files.java:3105) ~[?:1.8.0_251]
        at java.nio.file.Files.readAllBytes(Files.java:3158) ~[?:1.8.0_251]
        at org.apache.pulsar.broker.loadbalance.impl.LinuxBrokerHostUsageImpl.lambda$getTotalNicLimitKbps$3(LinuxBrokerHostUsageImpl.java:260) ~[org.apache.pulsar-pulsar-broker-2.8.3.jar:2.8.3]
        at java.util.stream.ReferencePipeline$6$1.accept(ReferencePipeline.java:244) ~[?:1.8.0_251]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_251]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_251]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_251]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_251]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_251]
        at java.util.stream.DoublePipeline.collect(DoublePipeline.java:478) ~[?:1.8.0_251]
        at java.util.stream.DoublePipeline.sum(DoublePipeline.java:389) ~[?:1.8.0_251]
        at org.apache.pulsar.broker.loadbalance.impl.LinuxBrokerHostUsageImpl.lambda$getTotalNicLimitKbps$4(LinuxBrokerHostUsageImpl.java:265) ~[org.apache.pulsar-pulsar-broker-2.8.3.jar:2.8.3]
        at java.util.Optional.orElseGet(Optional.java:267) ~[?:1.8.0_251]
        at org.apache.pulsar.broker.loadbalance.impl.LinuxBrokerHostUsageImpl.getTotalNicLimitKbps(LinuxBrokerHostUsageImpl.java:257) ~[org.apache.pulsar-pulsar-broker-2.8.3.jar:2.8.3]
        at org.apache.pulsar.broker.loadbalance.impl.LinuxBrokerHostUsageImpl.calculateBrokerHostUsage(LinuxBrokerHostUsageImpl.java:104) ~[org.apache.pulsar-pulsar-broker-2.8.3.jar:2.8.3]
        at org.apache.pulsar.common.util.Runnables$CatchingAndLoggingRunnable.run(Runnables.java:53) [org.apache.pulsar-pulsar-common-2.8.3.jar:2.8.3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_251]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_251]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_251]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_251]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.74.Final.jar:4.1.74.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
15:53:46.332 [pulsar-load-manager-1-1] ERROR org.apache.pulsar.broker.loadbalance.impl.LinuxBrokerHostUsageImpl - Failed to read speed for nic virbr0-nic

```
![image](https://user-images.githubusercontent.com/54351417/160359092-1e02265c-e408-42ab-a1fb-8351c8619507.png)

**Comment by mattisonchao** [comment]
Hi, @xuesongxs 

I'm not sure what VM are you using? maybe you need to set ``loadBalancerOverrideBrokerNicSpeedGbps ``.

Relative PR: https://github.com/apache/pulsar/pull/14340
@codelipenghui  @eolivelli @lhotari @michaeljmarshall Should we cherry-pick this PR to other active branches?

**Comment by sikangliu** [comment]
@xuesongxs Have you solved the problem yet? I had the same problem with the new version

**Comment by xuesongxs** [comment]
> set `loadBalancerOverrideBrokerNicSpeedGbps`

set loadBalancerOverrideBrokerNicSpeedGbps manually.

**Comment by xuesongxs** [comment]
> > set `loadBalancerOverrideBrokerNicSpeedGbps`
> 
> set loadBalancerOverrideBrokerNicSpeedGbps manually.

for example:
loadBalancerOverrideBrokerNicSpeedGbps=20

**Comment by sikangliu** [comment]
@xuesongxs What does this value do? What are the values based on? How big is the appropriate setting?Can you explain that

**Comment by codelipenghui** [comment]
@sikangliu @xuesongxs The fix has been cherry-picked into release branches, close the issue for now.
