### ISSUE TITLE
[2.8.1]Protocol message tag had invalid wire type

### ISSUE THREAD

**Issue by liangjianwen** [apache/pulsar#14905]
**Describe the bug**
When the producer(java client) sends a message to the Pulsar cluster, the broker log reports an error.  
Pulsar clusters are GEO replicated.

**To Reproduce**
1. There is a cluster of Pulsar GEO
2. Send a message to Pulsar with a producer
3. See error

**Expected behavior**
The producer can send messages normally.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Pulsar server version: 2.8.1
 - Pulsar client: Java client, version:2.8.0

**Additional context**
broker exception log: 
```
Mar 28 07:23:14 Test pulsar[1354958]: org.apache.bookkeeper.mledger.ManagedLedgerException: com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
Mar 28 07:23:14 Test pulsar[1354958]: Caused by: com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
Mar 28 07:23:14 Test pulsar[1354958]:         at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:111) ~[com.google.protobuf-protobuf-java-3.11.4.jar:?]
Mar 28 07:23:14 Test pulsar[1354958]:         at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:557) ~[com.google.protobuf-protobuf-java-3.11.4.jar:?]
Mar 28 07:23:14 Test pulsar[1354958]:         at com.google.protobuf.GeneratedMessageV3.parseUnknownField(GeneratedMessageV3.java:320) ~[com.google.protobuf-protobuf-java-3.11.4.jar:?]
Mar 28 07:23:14 Test pulsar[1354958]:         at org.apache.bookkeeper.mledger.proto.MLDataFormats$PositionInfo.<init>(MLDataFormats.java:7464) ~[org.apache.pulsar-managed-ledger-2.8.1.jar:2.8.1]
Mar 28 07:23:14 Test pulsar[1354958]:         at org.apache.bookkeeper.mledger.proto.MLDataFormats$PositionInfo.<init>(MLDataFormats.java:7380) ~[org.apache.pulsar-managed-ledger-2.8.1.jar:2.8.1]
Mar 28 07:23:14 Test pulsar[1354958]:         at org.apache.bookkeeper.mledger.proto.MLDataFormats$PositionInfo$1.parsePartialFrom(MLDataFormats.java:9230) ~[org.apache.pulsar-managed-ledger-2.8.1.jar:2.8.1]
Mar 28 07:23:14 Test pulsar[1354958]:         at org.apache.bookkeeper.mledger.proto.MLDataFormats$PositionInfo$1.parsePartialFrom(MLDataFormats.java:9224) ~[org.apache.pulsar-managed-ledger-2.8.1.jar:2.8.1]
Mar 28 07:23:14 Test pulsar[1354958]:         at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:158) ~[com.google.protobuf-protobuf-java-3.11.4.jar:?]
Mar 28 07:23:14 Test pulsar[1354958]:         at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:191) ~[com.google.protobuf-protobuf-java-3.11.4.jar:?]
Mar 28 07:23:14 Test pulsar[1354958]:         at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203) ~[com.google.protobuf-protobuf-java-3.11.4.jar:?]
Mar 28 07:23:14 Test pulsar[1354958]:         at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:208) ~[com.google.protobuf-protobuf-java-3.11.4.jar:?]
Mar 28 07:23:14 Test pulsar[1354958]:         at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48) ~[com.google.protobuf-protobuf-java-3.11.4.jar:?]
Mar 28 07:23:14 Test pulsar[1354958]:         at org.apache.bookkeeper.mledger.proto.MLDataFormats$PositionInfo.parseFrom(MLDataFormats.java:7866) ~[org.apache.pulsar-managed-ledger-2.8.1.jar:2.8.1]
Mar 28 07:23:14 Test pulsar[1354958]:         at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.lambda$recoverFromLedger$3(ManagedCursorImpl.java:427) ~[org.apache.pulsar-managed-ledger-2.8.1.jar:2.8.1]
Mar 28 07:23:14 Test pulsar[1354958]:         at org.apache.bookkeeper.client.LedgerHandle$6.onSuccess(LedgerHandle.java:804) [org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
Mar 28 07:23:14 Test pulsar[1354958]:         at org.apache.bookkeeper.client.LedgerHandle$6.onSuccess(LedgerHandle.java:801) [org.apache.bookkeeper-bookkeeper-server-4.14.2.jar:4.14.2]
Mar 28 07:23:14 Test pulsar[1354958]:         at org.apache.bookkeeper.common.concurrent.FutureEventListener.accept(FutureEventListener.java:42) [org.apache.bookkeeper-bookkeeper-common-4.14.2.jar:4.14.2]
Mar 28 07:23:14 Test pulsar[1354958]:         at org.apache.bookkeeper.common.concurrent.FutureEventListener.accept(FutureEventListener.java:26) [org.apache.bookkeeper-bookkeeper-common-4.14.2.jar:4.14.2]
Mar 28 07:23:14 Test pulsar[1354958]:         at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) [?:?]
Mar 28 07:23:14 Test pulsar[1354958]:         at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) [?:?]
Mar 28 07:23:14 Test pulsar[1354958]:         at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) [?:?]
Mar 28 07:23:14 Test pulsar[1354958]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
Mar 28 07:23:14 Test pulsar[1354958]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
Mar 28 07:23:14 Test pulsar[1354958]:         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.66.Final.jar:4.1.66.Final]
Mar 28 07:23:14 Test pulsar[1354958]:         at java.lang.Thread.run(Thread.java:829) [?:?]
Mar 28 07:23:14 Test pulsar[1354958]: 07:23:14.695 [BookKeeperClientWorker-OrderedExecutor-3-0] ERROR org.apache.bookkeeper.mledger.impl.ManagedLedgerFactoryImpl - [public/default/persistent/TestMsg] Failed to initialize managed ledger: com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
```

**Comment by sijie** [comment]
@liangjianwen is this a new cluster? or did you upgrade from an older version?

**Comment by liangjianwen** [comment]
@sijie This problem is caused by my improper manipulation of bookie metadata. I will close this issue. Thank you for your help.
