### ISSUE TITLE
Spaces not trimmed for configuration tlsProtocols

### ISSUE THREAD

**Issue by daniwb** [apache/pulsar#14914]
**Describe the bug**
The Documentation in the configuration for Broker states that this is a valid input:
```
# Specify the tls protocols the broker will use to negotiate during TLS handshake
# (a comma-separated list of protocol names).
# Examples:- [TLSv1.3, TLSv1.2]
tlsProtocols=
```

When configured as described, the TLSv1.2 will be taken as " TLSv1.2")

**To Reproduce**
1. Configure broker.conf with 
```tlsProtocols=TLSv1.3, TLSv1.2```
2. Restart Pulsar-Broker
3. Try to connect with Pulsar-Client

2022-03-28T16:44:17,879+0200 logLevel=WARN thread="pulsar-io-4-7" category=io.netty.channel.ChannelInitializer Failed to initialize a channel. Closing: [id: 0x4df94b79, L:/20db::c000:0:0:7b%0:6651 - R:/20db::c000:0:0:35e%0:36792]
java.lang.IllegalArgumentException: Protocol "TLSv1.2" is not supported.
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.setEnabledProtocols0(ReferenceCountedOpenSslEngine.java:1755) ~[io.netty-netty-handler-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.<init>(ReferenceCountedOpenSslEngine.java:337) ~[io.netty-netty-handler-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.handler.ssl.OpenSslEngine.<init>(OpenSslEngine.java:32) ~[io.netty-netty-handler-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.handler.ssl.OpenSslContext.newEngine0(OpenSslContext.java:51) ~[io.netty-netty-handler-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.newHandler(ReferenceCountedOpenSslContext.java:431) ~[io.netty-netty-handler-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.handler.ssl.SslContext.newHandler(SslContext.java:954) ~[io.netty-netty-handler-4.1.72.Final.jar:4.1.72.Final]
	at org.apache.pulsar.broker.service.PulsarChannelInitializer.initChannel(PulsarChannelInitializer.java:119) ~[org.apache.pulsar-pulsar-broker-2.9.1.jar:2.9.1]
	at org.apache.pulsar.broker.service.PulsarChannelInitializer.initChannel(PulsarChannelInitializer.java:45) ~[org.apache.pulsar-pulsar-broker-2.9.1.jar:2.9.1]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) [io.netty-netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) [io.netty-netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938) [io.netty-netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) [io.netty-netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) [io.netty-netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463) [io.netty-netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115) [io.netty-netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650) [io.netty-netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514) [io.netty-netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429) [io.netty-netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) [io.netty-netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty-netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [io.netty-netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) [io.netty-netty-transport-classes-epoll-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [io.netty-netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty-netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.72.Final.jar:4.1.72.Final]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]

**Expected behavior**
TLSv1.2 should be trimmed while reading.
With this configuration the Connection will be successful

**Desktop (please complete the following information):**
 - OS: RedHat 8.0

**Comment by Technoboy-** [comment]
> 1. tlsProtocols

You should config it with `tlsProtocols=[TLSv1.3, TLSv1.2]`

**Comment by Technoboy-** [comment]
I will work on it.

**Comment by Technoboy-** [comment]
We have fixed this by https://github.com/apache/pulsar/pull/13984.  You can wait for 2.9.2 or cherry-pick #13984 your local branch. 
Thanks.
