### ISSUE TITLE
Python Pulsar Function Deployed on 2.9.1

### ISSUE THREAD

**Issue by tspannhw** [apache/pulsar#14915]
**Describe the bug**
Function will not run with create, but will work with localrun.

**To Reproduce**

Deploy a python function with logging

**Expected behavior**

Deploy and run.

**Desktop (please complete the following information):**
 - OS: Ubuntu on Intel

ava.lang.RuntimeException: java.lang.RuntimeException: User class must be in class path
        at org.apache.pulsar.functions.runtime.RuntimeSpawner.<init>(RuntimeSpawner.java:72) ~[org.apache.pulsar-pulsar-functions-runtime-2.9.1.jar:2.9.1]
        at org.apache.pulsar.functions.worker.FunctionActioner.getRuntimeSpawner(FunctionActioner.java:172) ~[org.apache.pulsar-pulsar-functions-worker-2.9.1.jar:2.9.1]
        at org.apache.pulsar.functions.worker.FunctionActioner.startFunction(FunctionActioner.java:139) ~[org.apache.pulsar-pulsar-functions-worker-2.9.1.jar:2.9.1]
        at org.apache.pulsar.functions.worker.FunctionRuntimeManager.conditionallyStartFunction(FunctionRuntimeManager.java:962) ~[org.apache.pulsar-pulsar-functions-worker-2.9.1.jar:2.9.1]
        at org.apache.pulsar.functions.worker.FunctionRuntimeManager.startFunctionInstance(FunctionRuntimeManager.java:866) ~[org.apache.pulsar-pulsar-functions-worker-2.9.1.jar:2.9.1]
        at org.apache.pulsar.functions.worker.FunctionRuntimeManager.addAssignment(FunctionRuntimeManager.java:848) ~[org.apache.pulsar-pulsar-functions-worker-2.9.1.jar:2.9.1]
        at org.apache.pulsar.functions.worker.FunctionRuntimeManager.processAssignment(FunctionRuntimeManager.java:701) ~[org.apache.pulsar-pulsar-functions-worker-2.9.1.jar:2.9.1]
        at org.apache.pulsar.functions.worker.SchedulerManager.invokeScheduler(SchedulerManager.java:474) ~[org.apache.pulsar-pulsar-functions-worker-2.9.1.jar:2.9.1]
        at org.apache.pulsar.functions.worker.SchedulerManager.lambda$schedule$1(SchedulerManager.java:229) ~[org.apache.pulsar-pulsar-functions-worker-2.9.1.jar:2.9.1]
        at org.apache.pulsar.functions.worker.SchedulerManager.lambda$scheduleInternal$0(SchedulerManager.java:209) ~[org.apache.pulsar-pulsar-functions-worker-2.9.1.jar:2.9.1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_302]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_302]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_302]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_302]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]
Caused by: java.lang.RuntimeException: User class must be in class path
        at org.apache.pulsar.common.util.Reflections.createInstance(Reflections.java:113) ~[org.apache.pulsar-pulsar-common-2.9.1.jar:2.9.1]
        at org.apache.pulsar.functions.runtime.thread.ThreadRuntimeFactory.createContainer(ThreadRuntimeFactory.java:177) ~[org.apache.pulsar-pulsar-functions-runtime-2.9.1.jar:2.9.1]
        at org.apache.pulsar.functions.runtime.thread.ThreadRuntimeFactory.createContainer(ThreadRuntimeFactory.java:56) ~[org.apache.pulsar-pulsar-functions-runtime-2.9.1.jar:2.9.1]
        at org.apache.pulsar.functions.runtime.RuntimeSpawner.<init>(RuntimeSpawner.java:69) ~[org.apache.pulsar-pulsar-functions-runtime-2.9.1.jar:2.9.1]
        ... 14 more
Caused by: java.lang.ClassNotFoundException: secretsprovider.ClearTextSecretsProvider
        at [java.net](http://java.net/).URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_302]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_302]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_302]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_302]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_302]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_302]
        at org.apache.pulsar.common.util.Reflections.createInstance(Reflections.java:111) ~[org.apache.pulsar-pulsar-common-2.9.1.jar:2.9.1]
        at org.apache.pulsar.functions.runtime.thread.ThreadRuntimeFactory.createContainer(ThreadRuntimeFactory.java:177) ~[org.apache.pulsar-pulsar-functions-runtime-2.9.1.jar:2.9.1]
        at org.apache.pulsar.functions.runtime.thread.ThreadRuntimeFactory.createContainer(ThreadRuntimeFactory.java:56) ~[org.apache.pulsar-pulsar-functions-runtime-2.9.1.jar:2.9.1]
        at org.apache.pulsar.functions.runtime.RuntimeSpawner.<init>(RuntimeSpawner.java:69) ~[org.apache.pulsar-pulsar-functions-runtime-2.9.1.jar:2.9.1]

**Comment by tisonkun** [comment]
IIRC 2.9.1 is a yanked version. Closed as stale. Feel free to open a new issue if it's still relevant to maintained version.
