### ISSUE TITLE
Pulsar SQL won't start with Java 11.0.14.1

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#14951]
**Describe the bug**

Pulsar SQL won't start with Java 11.0.14.1 .

This is the errror message in `/pulsar/lib/presto/var/log/launcher.log`
```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot parse version 11.0.14.1
	at io.prestosql.server.JavaVersion.parse(JavaVersion.java:76)
	at io.prestosql.server.PrestoSystemRequirements.verifyJavaVersion(PrestoSystemRequirements.java:102)
	at io.prestosql.server.PrestoSystemRequirements.verifyJvmRequirements(PrestoSystemRequirements.java:45)
	at io.prestosql.server.PrestoServer.run(PrestoServer.java:78)
	at io.prestosql.$gen.Presto_332____20220330_100314_1.run(Unknown Source)
	at io.prestosql.server.PrestoServer.main(PrestoServer.java:72)
```

**To Reproduce**

1. Use Java 11.0.14.1
2. Try to run `/pulsar/bin/pulsar sql-worker start`

**Expected behavior**

Java 11.0.14.1 should be supported

**Comment by lhotari** [comment]
This is the line of code where the "Cannot parse version 11.0.14.1" comes from: 
https://github.com/trinodb/trino/blob/d239bb4c038124742bed07654dd73c257becc780/presto-main/src/main/java/io/prestosql/server/JavaVersion.java#L76

**Comment by lhotari** [comment]
It seems that the problem can be addressed by upgrading Trino to version 334 since that contains a commit where JavaVersion class was removed: https://github.com/trinodb/trino/commit/e7eeeedcc9751c022ffb9df648ee5442cd421c32

**Comment by lhotari** [comment]
A possible workaround would be to pass `-Djava.version=11.0.14` to the Pulsar SQL process. That would prevent the issue which prevents Pulsar SQL from starting.
