### ISSUE TITLE
RocksDB upgrade to 6.29.4.1 breaks Bookies

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#14961]
**Describe the bug**

RocksDB upgrade to 6.29.4.1 (#14886) breaks Bookies. Here's an example of log entries:

```
2022-03-31T02:28:35,308+0000 [BookieHighPriorityThread-3181-OrderedExecutor-4-0] WARN  org.apache.bookkeeper.proto.ReadEntryProcessor - Ledger: 20  fenced by: /172.21.0.6:59732
2022-03-31T02:28:35,315+0000 [BookieHighPriorityThread-3181-OrderedExecutor-4-0] ERROR org.apache.bookkeeper.proto.ReadEntryProcessor - Unexpected exception reading at 20:-1 : 'org.rocksdb.ReadOptions org.rocksdb.ReadOptions.setIterateUpperBound(org.rocksdb.Slice)'
java.lang.NoSuchMethodError: 'org.rocksdb.ReadOptions org.rocksdb.ReadOptions.setIterateUpperBound(org.rocksdb.Slice)'
	at org.apache.bookkeeper.bookie.storage.ldb.KeyValueStorageRocksDB.getFloor(KeyValueStorageRocksDB.java:257) ~[org.apache.bookkeeper-bookkeeper-server-4.14.4.jar:4.14.4]
	at org.apache.bookkeeper.bookie.storage.ldb.EntryLocationIndex.getLastEntryInLedgerInternal(EntryLocationIndex.java:106) ~[org.apache.bookkeeper-bookkeeper-server-4.14.4.jar:4.14.4]
	at org.apache.bookkeeper.bookie.storage.ldb.EntryLocationIndex.getLastEntryInLedger(EntryLocationIndex.java:99) ~[org.apache.bookkeeper-bookkeeper-server-4.14.4.jar:4.14.4]
	at org.apache.bookkeeper.bookie.storage.ldb.SingleDirectoryDbLedgerStorage.getLastEntry(SingleDirectoryDbLedgerStorage.java:559) ~[org.apache.bookkeeper-bookkeeper-server-4.14.4.jar:4.14.4]
	at org.apache.bookkeeper.bookie.storage.ldb.SingleDirectoryDbLedgerStorage.getEntry(SingleDirectoryDbLedgerStorage.java:401) ~[org.apache.bookkeeper-bookkeeper-server-4.14.4.jar:4.14.4]
	at org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorage.getEntry(DbLedgerStorage.java:200) ~[org.apache.bookkeeper-bookkeeper-server-4.14.4.jar:4.14.4]
	at org.apache.bookkeeper.bookie.LedgerDescriptorImpl.readEntry(LedgerDescriptorImpl.java:160) ~[org.apache.bookkeeper-bookkeeper-server-4.14.4.jar:4.14.4]
	at org.apache.bookkeeper.bookie.Bookie.readEntry(Bookie.java:1500) ~[org.apache.bookkeeper-bookkeeper-server-4.14.4.jar:4.14.4]
	at org.apache.bookkeeper.proto.ReadEntryProcessor.processPacket(ReadEntryProcessor.java:83) [org.apache.bookkeeper-bookkeeper-server-4.14.4.jar:4.14.4]
	at org.apache.bookkeeper.proto.PacketProcessorBase.safeRun(PacketProcessorBase.java:106) [org.apache.bookkeeper-bookkeeper-server-4.14.4.jar:4.14.4]
	at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [org.apache.bookkeeper-bookkeeper-common-4.14.4.jar:4.14.4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.74.Final.jar:4.1.74.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**To Reproduce**
1. Run Pulsar IO integration tests
2. Wait for the tests to fail
3. Check container logs for bookies

**Expected behavior**

Pulsar should use a RocksDB version that is compatible with Bookkeeper.

**Comment by lhotari** [comment]
RocksDB broke binary compatibility in 6.17.3 release. explained in https://github.com/apache/pulsar/pull/14962#issuecomment-1084192562

**Comment by lhotari** [comment]
"There is no guarantee of Binary Compatibility between RocksDB versions, I am afraid you will have to recompile."
https://github.com/facebook/rocksdb/commit/1001bc01c9ea06785c2d5261ca9fe7ac0eac0625#r70067997
/cc @nicoloboschi
