### ISSUE TITLE
Admin java sdk can't use  BrokerStats.getLoadReport method

### ISSUE THREAD

**Issue by WillsonYip** [apache/pulsar#15167]
**Describe the bug**

Admin java sdk can't use  BrokerStats.getLoadReport method . Below is environment

os: win 10 
java: 1.8 

maven

```
  <dependency>
      <groupId>org.apache.pulsar</groupId>
      <artifactId>pulsar-client-admin</artifactId>
      <version>2.9.2</version>
  </dependency>
```

here is the code 

```java
try( PulsarAdmin admin = PulsarAdmin.builder()
        .serviceHttpUrl(url)
        .build()) {

    BrokerStats brokerStats = admin.brokerStats();

    System.out.println(brokerStats.getLoadReportAsync().get());

} catch (Exception e) {
   e.printStackTrace();
}
```

exception:

```
java.util.concurrent.ExecutionException: org.apache.pulsar.client.admin.PulsarAdminException: java.lang.TypeNotPresentException: Type org.apache.pulsar.shade.org.apache.pulsar.policies.data.loadbalancer.LoadManagerReport not present
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
	at com.pulsar.service.impl.BrokerServiceImpl.main(BrokerServiceImpl.java:94)
Caused by: org.apache.pulsar.client.admin.PulsarAdminException: java.lang.TypeNotPresentException: Type org.apache.pulsar.shade.org.apache.pulsar.policies.data.loadbalancer.LoadManagerReport not present
	at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:247)
	at org.apache.pulsar.client.admin.internal.BrokerStatsImpl$5.failed(BrokerStatsImpl.java:210)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.submit(JerseyInvocation.java:908)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.submit(JerseyInvocation.java:800)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation$AsyncInvoker.method(JerseyInvocation.java:614)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.CompletableFutureAsyncInvoker.get(CompletableFutureAsyncInvoker.java:30)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.CompletableFutureAsyncInvoker.get(CompletableFutureAsyncInvoker.java:26)
	at org.apache.pulsar.client.admin.internal.BaseResource.asyncGetRequest(BaseResource.java:165)
	at org.apache.pulsar.client.admin.internal.BrokerStatsImpl.getLoadReportAsync(BrokerStatsImpl.java:201)
	... 1 more
Caused by: java.lang.TypeNotPresentException: Type org.apache.pulsar.shade.org.apache.pulsar.policies.data.loadbalancer.LoadManagerReport not present
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.repository.ClassRepository.getSuperInterfaces(ClassRepository.java:108)
	at java.lang.Class.getGenericInterfaces(Class.java:913)
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.util.ReflectionHelper.getClass(ReflectionHelper.java:1085)
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.util.ReflectionHelper.getClass(ReflectionHelper.java:1081)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.submit(JerseyInvocation.java:823)
	... 7 more
Caused by: java.lang.ClassNotFoundException: org.apache.pulsar.shade.org.apache.pulsar.policies.data.loadbalancer.LoadManagerReport
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	... 17 more

```

**Comment by WillsonYip** [comment]
o. I found pulsar-client-admin-original can solve problem. so ignore me

**Comment by shibd** [comment]
According to the official website description, we do not need to specifically refer to the dependencies of `original`. `pulsar-client-admin` includes `pulsar-client-admin-original`.  I had the same problem, and I use `pulsar-client-all` same reproduce.

https://pulsar.apache.org/docs/en/client-libraries-java/

**Comment by WillsonYip** [comment]
OK . I reopen this issue.

**Comment by geniusjoe** [comment]
Maybe relevant to this fix https://github.com/apache/pulsar/pull/23886
