### ISSUE TITLE
pulsar-bug

### ISSUE THREAD

**Issue by Designxiaozai** [apache/pulsar#15249]
**Describe the bug**

**To Reproduce**
1. Go to '...'2022-04-21T15:40:30,438+0800 [pulsar-io-30-1] INFO org.apache.pulsar.broker.service.ServerCnx - [/10.249.136.244:40136][persistent://public/11734a41bed74173a37264b7fdaa8fd0/2b0cdbe70dc7498c8eb5ac8376316cc9] Creating producer. producerId=0
2022-04-21T15:40:30,454+0800 [BookKeeperClientWorker-OrderedExecutor-0-0] ERROR org.apache.pulsar.broker.transaction.buffer.impl.TopicTransactionBuffer - Topic persistent://public/11734a41bed74173a37264b7fdaa8fd0/2b0cdbe70dc7498c8eb5ac8376316cc9: TransactionBuffer recover failed
java.util.concurrent.CompletionException: org.apache.pulsar.client.api.PulsarClientException$BrokerMetadataException: The subscription reader-bbfebda917 of the topic persistent://public/11734a41bed74173a37264b7fdaa8fd0/__transaction_buffer_snapshot gets the last message id was failed
{"errorMsg":"Failed to read last entry of the compacted Ledger Incorrect parameter input","reqId":2395440622435992897, "remote":"localhost/127.0.0.1:6651", "local":"/127.0.0.1:55222"}
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
at java.util.concurrent.CompletableFuture.uniRunNow(CompletableFuture.java:809) ~[?:?]
at java.util.concurrent.CompletableFuture.uniRunStage(CompletableFuture.java:799) ~[?:?]
at java.util.concurrent.CompletableFuture.thenRun(CompletableFuture.java:2121) ~[?:?]
at org.apache.pulsar.broker.transaction.buffer.impl.TopicTransactionBuffer.checkIfTBRecoverCompletely(TopicTransactionBuffer.java:181) ~[org.apache.pulsar-pulsar-broker-2.9.1.jar:2.9.1]
at org.apache.pulsar.broker.service.persistent.PersistentTopic.checkIfTransactionBufferRecoverCompletely(PersistentTopic.java:573) ~[org.apache.pulsar-pulsar-broker-2.9.1.jar:2.9.1]
at org.apache.pulsar.broker.service.ServerCnx.lambda$null$20(ServerCnx.java:1239) ~[org.apache.pulsar-pulsar-broker-2.9.1.jar:2.9.1]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
at java.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by liangyuanpeng** [comment]
Can you provide more info for this?

**Comment by tisonkun** [comment]
Close as stale.
