### ISSUE TITLE
Flaky-test: ProducerCloseTest.brokerCloseTopicTest

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#15277]
ProducerCloseTest.brokerCloseTopicTest is flaky. It fails sporadically.

[example failure](https://github.com/apache/pulsar/runs/6128834673?check_suite_focus=true#step:11:620)

```
Error:  Tests run: 16, Failures: 1, Errors: 0, Skipped: 12, Time elapsed: 37.177 s <<< FAILURE! - in org.apache.pulsar.client.impl.ProducerCloseTest
  Error:  brokerCloseTopicTest(org.apache.pulsar.client.impl.ProducerCloseTest)  Time elapsed: 0.117 s  <<< FAILURE!
  java.lang.AssertionError: expected [Connecting] but found [Ready]
  	at org.testng.Assert.fail(Assert.java:99)
  	at org.testng.Assert.failNotEquals(Assert.java:1037)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
  	at org.testng.Assert.assertEquals(Assert.java:122)
  	at org.testng.Assert.assertEquals(Assert.java:617)
  	at org.apache.pulsar.client.impl.ProducerCloseTest.brokerCloseTopicTest(ProducerCloseTest.java:140)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:[635](https://github.com/apache/pulsar/runs/6128834673?check_suite_focus=true#step:11:635))
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by lhotari** [comment]
@gaoran10  This flaky test was introduced in your change #14870 . Could you please take a look and fix this?

**Comment by nicoloboschi** [comment]
another failure here: https://github.com/apache/pulsar/runs/6520937037?check_suite_focus=true
