### ISSUE TITLE
[python] Pulsar Client package is missing from PyPi for Macosx and Python37

### ISSUE THREAD

**Issue by zbentley** [apache/pulsar#15402]
**Describe the bug**
On PyPi, there are macosx `pulsar-client` wheels for python 38, 39, and 310, but not 37.

Python 3.7 is the most widely used version of Python 3; supporting it should be a priority.

**Comment by merlimat** [comment]
Good point. The main problem was that Python 3.7 doesn't support universal2 binaries out of the box, so it was making it a bit more difficult to integrate in the build scripts. Working on a fix to patch python 3.7 to make this work.

**Comment by zbentley** [comment]
Thank you!

**Comment by merlimat** [comment]
@zbentley Fixed the scripts and uploaded the 3.7 wheel: https://files.pythonhosted.org/packages/02/7f/3eff77a28595a7654b40807e23bd0ea5ceb4738a3e87a4787e3d81ca4748/pulsar_client-2.10.0-cp37-cp37m-macosx_11_0_x86_64.whl

**Comment by zbentley** [comment]
Awesome, thanks! Any chance of an macosx ARM wheel for 37? Happy to run a build for it if the issue is hardware availability.

**Comment by merlimat** [comment]
I don’t think it’s possible because Python 3.7 doesn’t support ARM on Mac.

**Comment by zbentley** [comment]
3.7 works well on ARM; we use `pyenv` to install it (`pyenv install 3.7.13` or `pipenv --python 3.7.13` with a `brew install pyenv pipenv` rather than relying on Homebrew pythons. Are there build instructions I can follow for M1? If so, I can initiate a build.

**Comment by merlimat** [comment]
@zbentley This is the script used to build the mac wheels, the version in the PR has added 3.7: https://github.com/apache/pulsar/blob/b435b760e60f37188d2c32905d78abf8db34e857/pulsar-client-cpp/python/build-mac-wheels.sh 

I actually run the build on M1 and I had to force to build Python 3.7 for x86_64 to avoid failure in building it. There is some description of the issues in https://bugs.python.org/issue41100 which is marked to fix Python 3.8+

**Comment by zbentley** [comment]
Try `brew install pyenv; pyenv install 3.7.13` on your M1; I bet it'll work. If not, I'll try building when back at work in a couple days.

**Comment by merlimat** [comment]
I tried that. Pyenv seems to be back porting a series of patches into 3.7 to make it compile on Arm, though there are still issues with some of the modules. Eg: I'm getting error when creating the wheel file because the `_ctypes` modules was somehow not enabled: 

```
➜  python git:(2318a180c06) ✗ find /Users/mmerli/.pyenv/versions/3.7.13/lib/python3.7/ -name '*.so' | grep ctype
/Users/mmerli/.pyenv/versions/3.7.13/lib/python3.7//lib-dynload/_ctypes_test.cpython-37m-darwin.so
➜  python git:(2318a180c06) ✗ /Users/mmerli/.pyenv/versions/3.7.13/bin/python3.7 -c "import ctypes"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mmerli/.pyenv/versions/3.7.13/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
```

**Comment by merlimat** [comment]
```
+ /Users/mmerli/.pyenv/versions/3.7.13/bin/python3 setup.py bdist_wheel
Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    from setuptools import setup
  File "/Users/mmerli/.pyenv/versions/3.7.13/lib/python3.7/site-packages/setuptools/__init__.py", line 19, in <module>
    from setuptools.dist import Distribution
  File "/Users/mmerli/.pyenv/versions/3.7.13/lib/python3.7/site-packages/setuptools/dist.py", line 34, in <module>
    from setuptools import windows_support
  File "/Users/mmerli/.pyenv/versions/3.7.13/lib/python3.7/site-packages/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/Users/mmerli/.pyenv/versions/3.7.13/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
```

**Comment by zbentley** [comment]
#15436 remains open, which should make building these easier.

In the meantime, on a recently factory-reset M1, I built a py37 client on a few different tags this morning
[pulsar_client-2.9.1-cp37-cp37m-macosx_11_0_arm64.whl.zip](https://github.com/apache/pulsar/files/8730661/pulsar_client-2.9.1-cp37-cp37m-macosx_11_0_arm64.whl.zip)
[pulsar_client-2.9.1-cp37-cp37m-macosx_11_0_x86_64.whl.zip](https://github.com/apache/pulsar/files/8730662/pulsar_client-2.9.1-cp37-cp37m-macosx_11_0_x86_64.whl.zip)
[pulsar_client-2.10.0-cp37-cp37m-macosx_11_0_arm64.whl.zip](https://github.com/apache/pulsar/files/8730663/pulsar_client-2.10.0-cp37-cp37m-macosx_11_0_arm64.whl.zip)
, and created the attached wheels; I hope they come in useful for folks.
