### ISSUE TITLE
Flaky-test: RackAwareTest.testPlacement

### ISSUE THREAD

**Issue by BewareMyPower** [apache/pulsar#15421]
RackAwareTest.testPlacement is flaky. It fails sporadically.

[example failure](https://github.com/apache/pulsar/pull/15413/checks?check_run_id=6285362452)

```
org.apache.pulsar.broker.service.RackAwareTest ► testPlacement
Failed test found in:
  TEST-org.apache.pulsar.broker.service.RackAwareTest.xml
Error:
      java.lang.AssertionError: first bookie in rack 0 not included in ensemble expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.apache.pulsar.broker.service.RackAwareTest.testPlacement(RackAwareTest.java:144)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by BewareMyPower** [comment]
Some other failures:
- https://github.com/apache/pulsar/pull/15282/checks?check_run_id=6298763232
- https://github.com/apache/pulsar/pull/15376/checks?check_run_id=6299007757
- https://github.com/apache/pulsar/pull/15436/checks?check_run_id=6298814274

**Comment by wuxuanqicn** [comment]
Duplicated with #14106
