### ISSUE TITLE
allowAutoTopicCreation has weird behavior

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar#15452]
**Describe the bug**
allowAutoTopicCreation doesn't work with default configuration files.

**To Reproduce**
1. Download https://www.apache.org/dyn/mirrors/mirrors.cgi?action=download&filename=pulsar/pulsar-2.10.0/apache-pulsar-2.10.0-bin.tar.gz
2. Extract it
3. Run `bin/standalone -nfw`
4. Ensure that the `standalone.conf` `allowAutoTopicCreation=true`
5. Create a tenant `test` on `standalone` cluster
```bash
pulsarctl --admin-service-url http://localhost:8080  tenants create test -c standalone
````
7. Create a namespace `test/test`
```bash
pulsarctl --admin-service-url http://localhost:8080  namespaces create test/test
````
9. Try to create a producer on it and get
client side:
```
14:11:51.571 [pulsar-client-io-1-1] ERROR org.apache.pulsar.client.impl.ProducerImpl - [test/test/test] [null] Failed to create producer: {"errorMsg":"Topic Not Found.","reqId":1977895818880687123, "remote":"localhost/127.0.0.1:6650", "local":"/127.0.0.1:46162"}
Exception in thread "main" org.apache.pulsar.client.api.PulsarClientException$TopicDoesNotExistException: {"errorMsg":"Topic Not Found.","reqId":1977895818880687123, "remote":"localhost/127.0.0.1:6650", "local":"/127.0.0.1:46162"}
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:1066)
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:88)
	at com.clevercloud.PulsarProducer.main(PulsarProducer.java:83)
```
standalone side:
```
2022-05-05T15:02:36,328+0200 [pulsar-io-29-1] INFO  org.apache.pulsar.broker.service.ServerCnx - New connection from /127.0.0.1:46190
2022-05-05T15:02:36,619+0200 [pulsar-27-1] INFO  org.apache.pulsar.broker.namespace.OwnershipCache - Trying to acquire ownership of test/test/0xc0000000_0xffffffff
2022-05-05T15:02:36,635+0200 [main-EventThread] INFO  org.apache.pulsar.metadata.coordination.impl.ResourceLockImpl - Acquired resource lock on /namespace/test/test/0xc0000000_0xffffffff
2022-05-05T15:02:36,635+0200 [main-EventThread] INFO  org.apache.pulsar.broker.namespace.OwnershipCache - Successfully acquired ownership of OwnedBundle(bundle=test/test/0xc0000000_0xffffffff, isActive=1)
2022-05-05T15:02:36,635+0200 [pulsar-27-2] INFO  org.apache.pulsar.broker.PulsarService - Loading all topics on bundle: test/test/0xc0000000_0xffffffff
2022-05-05T15:02:36,659+0200 [pulsar-io-29-1] INFO  org.apache.pulsar.broker.service.ServerCnx - [/127.0.0.1:46190][persistent://test/test/test] Creating producer. producerId=0
2022-05-05T15:02:36,668+0200 [pulsar-io-29-1] INFO  org.apache.pulsar.broker.PulsarService - No ledger offloader configured, using NULL instance
2022-05-05T15:02:36,689+0200 [pulsar-io-29-1] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - Opening managed ledger test/test/persistent/test
2022-05-05T15:02:36,694+0200 [bookkeeper-ml-scheduler-OrderedScheduler-3-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [test/test/persistent/test] Closing managed ledger
2022-05-05T15:02:36,696+0200 [bookkeeper-ml-scheduler-OrderedScheduler-3-0] INFO  org.apache.pulsar.broker.service.ServerCnx - [/127.0.0.1:46190] Failed to load topic persistent://test/test/test, producerId=0: Topic not found
```

11. Get the `test/test` policies
 ```bash
pulsarctl --admin-service-url http://localhost:8080  namespaces policies test/test
````

```json
"autoTopicCreationOverride": {
    "allowAutoTopicCreation": false,
    "topicType": "",
    "defaultNumPartitions": 0
  },
```

Why it is false? 

12. Try to change this using REST API (because the --enable option is not available on pulsarctl namespaces set-auto-topic-creation) it doesn't work better
```bash
curl -X POST http://localhost:8080/admin/v2/namespaces/test/test/autoTopicCreation -L -H "Content-Type: application/json"  -d '{"allowAutoTopicCreation":true,"topicType":"non-partitioned"}'
```
The auto topic creation only works using `partitioned topicType` with default partition > 0.

It is quite weird because we can't have auto topic creation using `non-partitioned topics`. More the policies shows as auto topic creation is not authorized for this namespace while it should be inherited from broker/standalone config which is enabled. And default ns policies should have `null` so fallback to broker config key.

**Expected behavior**
really allowAutoTopicCreation

**Comment by KannarFr** [comment]
@mattisonchao I dived into this issue and it seems to be a pulsarctl https://github.com/streamnative/pulsarctl/issues/703 issue. Can you confirm it?

**Comment by mattisonchao** [comment]
Hi, @KannarFr 

Could you try using `pulsar-admin` to test it? it's not related to `pulsarctl.`

@nodece  Could you have time to help check this issue?
/cc @nodece

**Comment by mattisonchao** [comment]
@KannarFr  Already use RestAPI confirm it. So, I will close this issue.

**Comment by nodece** [comment]
Hi @KannarFr, thanks for your report, this issue should be from pulsarctl, and has been fixed by https://github.com/streamnative/pulsarctl/pull/556.
