### ISSUE TITLE
Flaky-test: PendingAckPersistentTest.testPendingAckLowWaterMarkRemoveFirstTxn

### ISSUE THREAD

**Issue by nicoloboschi** [apache/pulsar#15676]
PendingAckPersistentTest.testPendingAckLowWaterMarkRemoveFirstTxn is flaky. It fails sporadically.

[example failure](https://github.com/apache/pulsar/pull/15638/checks?check_run_id=6506945433)

```
      java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at org.apache.pulsar.broker.transaction.pendingack.PendingAckPersistentTest.testPendingAckLowWaterMarkRemoveFirstTxn(PendingAckPersistentTest.java:567)
```

**Comment by nicoloboschi** [comment]
I believe it is related to #15530 @liangyepianzhou, can you take a look ?

**Comment by liangyepianzhou** [comment]
The test has fixed by https://github.com/apache/pulsar/pull/15592
