### ISSUE TITLE
Flaky-test: MessageImplTest.testMessageBrokerAndEntryMetadataTimestampMissed

### ISSUE THREAD

**Issue by Technoboy-** [apache/pulsar#15689]
https://github.com/apache/pulsar/runs/6522138165?check_suite_focus=true

```
Error:  Tests run: 18, Failures: 1, Errors: 0, Skipped: 8, Time elapsed: 3.189 s <<< FAILURE! - in org.apache.pulsar.client.impl.MessageImplTest
  Error:  testMessageBrokerAndEntryMetadataTimestampMissed(org.apache.pulsar.client.impl.MessageImplTest)  Time elapsed: 0.033 s  <<< FAILURE!
  java.lang.OutOfMemoryError: test
  	at org.apache.bookkeeper.common.allocator.impl.ByteBufAllocatorImpl.buffer(ByteBufAllocatorImpl.java:134)
  	at org.apache.pulsar.client.impl.MessageImplTest.testMessageBrokerAndEntryMetadataTimestampMissed(MessageImplTest.java:433)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by lhotari** [comment]
The `java.lang.OutOfMemoryError: test` seems to leak from 
https://github.com/apache/pulsar/blob/dc602c04a6daf55e7391cda3e9f9e3c2850db815/pulsar-client/src/test/java/org/apache/pulsar/client/impl/BatchMessageContainerImplTest.java#L41-L44 . There was a change in this area in #14250. @nicoloboschi Is this going to be resolved with #15513 ?
