### ISSUE TITLE
CoordinationServiceImpl.close hangs and doesn't complete

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#15774]
**Describe the bug**

CoordinationServiceImpl.close hangs and doesn't complete. This causes some test runs to get stuck. This might also be a production issue.

[Example thread dump](https://jstack.review/?https://gist.github.com/lhotari/6f7d659eb0651491e1a59d545d8559c7#tda_1_tg_25).

```
"main" #1 prio=5 os_prio=0 cpu=12135.43ms elapsed=3504.47s tid=0x00007fdff8024370 nid=0xab5 waiting on condition  [0x00007fdffede0000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.3/Native Method)
	- parking to wait for  <0x00000000c9200010> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.3/LockSupport.java:211)
	at java.util.concurrent.CompletableFuture$Signaller.block(java.base@17.0.3/CompletableFuture.java:1864)
	at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@17.0.3/ForkJoinPool.java:3463)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.3/ForkJoinPool.java:3434)
	at java.util.concurrent.CompletableFuture.waitingGet(java.base@17.0.3/CompletableFuture.java:1898)
	at java.util.concurrent.CompletableFuture.join(java.base@17.0.3/CompletableFuture.java:2117)
	at org.apache.pulsar.metadata.coordination.impl.CoordinationServiceImpl.close(CoordinationServiceImpl.java:72)
	at org.apache.pulsar.broker.PulsarService.closeAsync(PulsarService.java:526)
	at org.apache.pulsar.broker.PulsarService.close(PulsarService.java:372)
```

**Expected behavior**

Calling CoordinationServiceImpl.close should complete or timeout.

**Comment by lhotari** [comment]
Since we are now on Java 17, it would be possible to start leveraging Java API methods that have been added since Java 8.

One useful method is [`CompletableFuture.orTimeout`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/CompletableFuture.html#orTimeout(long,java.util.concurrent.TimeUnit)) . It's a simple way to add a timeout to a Completable Future.

**Comment by lhotari** [comment]
Yet another failure: https://github.com/apache/pulsar/runs/6666238441?check_suite_focus=true#step:11:86
