### ISSUE TITLE
Flaky-test: AdminApiTransactionTest.testGetPendingAckInternalStats

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#15916]
AdminApiTransactionTest.testGetPendingAckInternalStats is flaky. It fails sporadically.

[example failure](https://github.com/apache/pulsar/runs/6713195445?check_suite_focus=true#step:10:2573)

```
  Error:  Tests run: 32, Failures: 1, Errors: 0, Skipped: 30, Time elapsed: 22.768 s <<< FAILURE! - in org.apache.pulsar.broker.admin.v3.AdminApiTransactionTest
  Error:  testGetPendingAckInternalStats(org.apache.pulsar.broker.admin.v3.AdminApiTransactionTest)  Time elapsed: 2.63 s  <<< FAILURE!
  java.lang.AssertionError: expected object to not be null
  	at org.testng.Assert.fail(Assert.java:99)
  	at org.testng.Assert.assertNotNull(Assert.java:942)
  	at org.testng.Assert.assertNotNull(Assert.java:926)
  	at org.apache.pulsar.broker.admin.v3.AdminApiTransactionTest.verifyManagedLegerInternalStats(AdminApiTransactionTest.java:608)
  	at org.apache.pulsar.broker.admin.v3.AdminApiTransactionTest.testGetPendingAckInternalStats(AdminApiTransactionTest.java:496)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by lhotari** [comment]
I'll fix this.
