### ISSUE TITLE
Flaky-test: GeoReplicationTest.testTopicReplication

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#15913]
GeoReplicationTest.testTopicReplication is flaky. It fails sporadically.

[example failure](https://github.com/apache/pulsar/runs/6715214224?check_suite_focus=true#step:12:15869)

```
  Error:  Tests run: 43, Failures: 6, Errors: 0, Skipped: 20, Time elapsed: 552.812 s <<< FAILURE! - in TestSuite
  Error:  testTopicReplication(org.apache.pulsar.tests.integration.messaging.GeoReplicationTest)  Time elapsed: 18.618 s  <<< FAILURE!
  java.lang.AssertionError: expected object to not be null
  	at org.testng.Assert.fail(Assert.java:99)
  	at org.testng.Assert.assertNotNull(Assert.java:942)
  	at org.testng.Assert.assertNotNull(Assert.java:926)
  	at org.apache.pulsar.tests.integration.messaging.GeoReplicationTest.testTopicReplication(GeoReplicationTest.java:124)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by lhotari** [comment]
another one: https://github.com/apache/pulsar/actions/runs/3086967858/jobs/4991995273#step:12:15153

**Comment by lhotari** [comment]
another one: https://github.com/apache/pulsar/actions/runs/3539850595/jobs/5943592808#step:12:15283

**Comment by lhotari** [comment]
Another occurrence of this flaky test.

**Example failure:** https://github.com/apache/pulsar/actions/runs/23586018795/job/68681280441

**Failed variant:** `testTopicReplication[non-persistent](6)` (retry attempt — invocation 4 was skipped due to prior failed setup)

**Stack trace:**
```
java.lang.AssertionError: expected object to not be null
	at org.testng.Assert.assertNotNull(Assert.java:1483)
	at org.apache.pulsar.tests.integration.messaging.GeoReplicationTest.testTopicReplication(GeoReplicationTest.java:124)
```

**Analysis:** The persistent variant passed (18.4s), but the non-persistent variant timed out after 21s. The test sends 10 messages from cluster1 and expects to receive all 10 on cluster2 with a 10-second per-message timeout. `c.receive(10, TimeUnit.SECONDS)` returned null, meaning the non-persistent message was not replicated in time. Non-persistent topics don't guarantee delivery — messages can be lost if the replication cursor hasn't caught up or connections aren't fully established between clusters in the containerized CI environment.

**Comment by void-ptr974** [comment]
Another occurrence of this flaky test.

**Example failure:** https://github.com/apache/pulsar/actions/runs/27804576061/job/82585497783

**Related PR:** https://github.com/apache/pulsar/pull/26056

**Failed check:** `CI - Integration - Messaging`

**Failed variant:** `testTopicReplication[4](non-persistent)` (the previous `non-persistent` retry attempt was recorded as skipped after the same assertion failure)

**Stack trace:**
```text
java.lang.AssertionError: expected object to not be null
    at org.testng.Assert.assertNotNull(Assert.java:1496)
    at org.testng.Assert.assertNotNull(Assert.java:1480)
    at org.apache.pulsar.tests.integration.messaging.GeoReplicationTest.testTopicReplication(GeoReplicationTest.java:133)
```

**Analysis:** The persistent variant passed, while the non-persistent variant timed out waiting for a message from the remote cluster. The test sends messages immediately after creating the producer and consumer. For non-persistent topics, replication can drop messages when the remote replicator producer is not started or writable yet, so this looks like a startup race where the test sends before the non-persistent replication path is ready.
