### ISSUE TITLE
Flaky-test: PartitionedSystemTopicTest.cleanup

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#15920]
PartitionedSystemTopicTest.cleanup is flaky. It fails sporadically.

[example failure](https://github.com/apache/pulsar/runs/6721616096?check_suite_focus=true#step:10:1876)

```
  Error:  Tests run: 9, Failures: 1, Errors: 0, Skipped: 6, Time elapsed: 83.268 s <<< FAILURE! - in org.apache.pulsar.broker.systopic.PartitionedSystemTopicTest
  Error:  cleanup(org.apache.pulsar.broker.systopic.PartitionedSystemTopicTest)  Time elapsed: 71.628 s  <<< FAILURE!
  org.apache.pulsar.broker.PulsarServerException: org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.ExecutionException: org.apache.pulsar.common.util.FutureUtil$LowOverheadTimeoutException: Closing producers and consumers timed out.
  	at org.apache.pulsar.broker.PulsarService.closeAsync(PulsarService.java:574)
  	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
  	at org.apache.pulsar.broker.PulsarService.closeAsync(PulsarService.java:395)
  	at org.apache.pulsar.broker.PulsarService.close(PulsarService.java:374)
  	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
  	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
  Caused by: org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.ExecutionException: org.apache.pulsar.common.util.FutureUtil$LowOverheadTimeoutException: Closing producers and consumers timed out.
  	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:1074)
  	at org.apache.pulsar.client.impl.PulsarClientImpl.close(PulsarClientImpl.java:711)
  	at org.apache.pulsar.broker.PulsarService.closeAsync(PulsarService.java:491)
  	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
  	at org.mockito.internal.util.reflection.InstrumentationMemberAccessor$Dispatcher$ByteBuddy$Kf8nzKi5.invokeWithArguments(Unknown Source)
  	at org.mockito.internal.util.reflection.InstrumentationMemberAccessor.invoke(InstrumentationMemberAccessor.java:239)
  	at org.mockito.internal.util.reflection.ModuleMemberAccessor.invoke(ModuleMemberAccessor.java:55)
  	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.tryInvoke(MockMethodAdvice.java:333)
  	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.access$500(MockMethodAdvice.java:60)
  	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice$RealMethodCall.invoke(MockMethodAdvice.java:253)
  	at org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:142)
  	at org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:45)
  	at org.mockito.Answers.answer(Answers.java:99)
  	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:110)
  	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
  	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
  	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
  	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handle(MockMethodAdvice.java:151)
  	at org.apache.pulsar.broker.PulsarService.closeAsync(PulsarService.java:395)
  	at org.apache.pulsar.broker.PulsarService.close(PulsarService.java:374)
```

**Comment by lhotari** [comment]
PulsarClientImpl.close shouldn't throw an exception when closing producers and consumers times out.
