### ISSUE TITLE
[test] NPE of StringSchema for branch-2.10

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#16000]
**Describe the bug**
https://github.com/apache/pulsar/runs/6812506434?check_suite_focus=true

```
Error:  Tests run: 4, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 7.561 s <<< FAILURE! - in org.apache.pulsar.broker.service.BrokerServiceBundlesCacheInvalidationTest
Error:  testRecreateNamespace(org.apache.pulsar.broker.service.BrokerServiceBundlesCacheInvalidationTest)  Time elapsed: 0.2 s  <<< FAILURE!
java.lang.NullPointerException
	at java.base/java.lang.String.getBytes(String.java:963)
	at org.apache.pulsar.client.impl.schema.StringSchema.encode(StringSchema.java:98)
	at org.apache.pulsar.client.impl.schema.StringSchema.encode(StringSchema.java:34)
	at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.value(TypedMessageBuilderImpl.java:173)
	at org.apache.pulsar.client.impl.ProducerBase.send(ProducerBase.java:62)
	at org.apache.pulsar.broker.service.BrokerServiceBundlesCacheInvalidationTest.testRecreateNamespace(BrokerServiceBundlesCacheInvalidationTest.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**To Reproduce**
Always fail on CI but it's not able to reproduce on my laptop

**Comment by codelipenghui** [comment]
Looks like temurin has a new release [jdk-11.0.15+10](https://github.com/adoptium/temurin11-binaries/releases/tag/jdk-11.0.15%2B10) which introduced the issue. After rollback to `[jdk-11.0.15+10]`, the failed test get passed.

**Comment by eolivelli** [comment]
@codelipenghui @nicoloboschi is there any link to a OpenJDK issue ?
I can create tickets on OpenJDK JIRA, if it is a new issue we can report it but we need more context

**Comment by codelipenghui** [comment]
Sorry @eolivelli

I'm still testing. It's not a JDK issue but related to `reuseFork`. I have disabled the `reuseFork in PR #15995`, the test gets passed. Looks like the `reuseFork` lead some static code doesn't work.
