### ISSUE TITLE
The standalone service can not start in the non-root container

### ISSUE THREAD

**Issue by zymap** [apache/pulsar#16077]
**Describe the bug**
When I running the command `$ docker run -it -p 6650:6650  -p 8080:8080 --mount source=pulsardata,target=/pulsar/data --mount source=pulsarconf,target=/pulsar/conf apachepulsar/pulsar:2.10.0 bin/pulsar standalone`, the pulsar standalone service can not start successfully.

error log:

```

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/pulsar/lib/io.netty-netty-common-4.1.74.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2022-06-15T13:09:46,206+0000 [main] INFO  org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble - Running 1 bookie(s) and advertised them at 127.0.0.1.
2022-06-15T13:09:46,212+0000 [main] INFO  org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble - Starting ZK server
2022-06-15T13:09:46,215+0000 [main] ERROR org.apache.pulsar.PulsarStandaloneStarter - Failed to start pulsar service.
java.nio.file.AccessDeniedException: /pulsar/data/standalone
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]
	at java.nio.file.Files.createDirectory(Files.java:690) ~[?:?]
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:797) ~[?:?]
	at java.nio.file.Files.createDirectories(Files.java:783) ~[?:?]
	at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.runZookeeper(LocalBookkeeperEnsemble.java:190) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.10.0.jar:2.10.0]
	at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.startStandalone(LocalBookkeeperEnsemble.java:443) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.10.0.jar:2.10.0]
	at org.apache.pulsar.PulsarStandalone.start(PulsarStandalone.java:269) ~[org.apache.pulsar-pulsar-broker-2.10.0.jar:2.10.0]
	at org.apache.pulsar.PulsarStandaloneStarter.main(PulsarStandaloneStarter.java:139) [org.apache.pulsar-pulsar-broker-2.10.0.jar:2.10.0]
```

Anything I missed?

**Comment by zymap** [comment]
@michaeljmarshall You made the change about this. Maybe you are familiar with it. Any suggestion about this?

**Comment by zymap** [comment]
related fix: https://github.com/apache/pulsar/pull/15769
