### ISSUE TITLE
Failed to flush mark-delete position

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#16237]
**Describe the bug**
Pulsar v2.8.1
broker log:
[pulsar/iot/persistent/19_rate_merge-partition-0][consumer19] Failed to flush mark-delete position
org.apache.bookkeeper.mledger.ManagedLedgerException: java.lang.IllegalArgumentException: Mark deleting an already mark-deleted position
Caused by: java.lang.IllegalArgumentException: Mark deleting an already mark-deleted position
	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.setAcknowledgedPosition(ManagedCursorImpl.java:1580) ~[org.apache.pulsar-managed-ledger-2.8.1.jar:2.8.1]
	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.asyncMarkDelete(ManagedCursorImpl.java:1718) ~[org.apache.pulsar-managed-ledger-2.8.1.jar:2.8.1]
	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.flush(ManagedCursorImpl.java:3026) ~[org.apache.pulsar-managed-ledger-2.8.1.jar:2.8.1]
	at org.apache.bookkeeper.mledger.impl.ManagedLedgerFactoryImpl.lambda$flushCursors$1(ManagedLedgerFactoryImpl.java:212) ~[org.apache.pulsar-managed-ledger-2.8.1.jar:2.8.1]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_151]
	at org.apache.bookkeeper.mledger.impl.ManagedLedgerFactoryImpl.lambda$flushCursors$2(ManagedLedgerFactoryImpl.java:212) ~[org.apache.pulsar-managed-ledger-2.8.1.jar:2.8.1]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) ~[?:1.8.0_151]
	at org.apache.bookkeeper.mledger.impl.ManagedLedgerFactoryImpl.flushCursors(ManagedLedgerFactoryImpl.java:208) ~[org.apache.pulsar-managed-ledger-2.8.1.jar:2.8.1]
	at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) ~[org.apache.bookkeeper-bookkeeper-common-4.14.2.jar:4.14.2]
	at org.apache.bookkeeper.common.util.OrderedExecutor$TimedRunnable.run(OrderedExecutor.java:203) ~[org.apache.bookkeeper-bookkeeper-common-4.14.2.jar:4.14.2]
	at org.apache.bookkeeper.common.util.OrderedExecutor$TimedRunnable.run(OrderedExecutor.java:203) ~[org.apache.bookkeeper-bookkeeper-common-4.14.2.jar:4.14.2]
	at com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator$NeverSuccessfulListenableFutureTask.run(MoreExecutors.java:705) ~[com.google.guava-guava-30.1-jre.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_151]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty-netty-common-4.1.66.Final.jar:4.1.66.Final]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_151]

**Comment by Technoboy-** [comment]
@merlimat 
When the above exception occurs, can we consider `asyncMarkDelete` successfully?
If so, I will push a patch to improve it.

**Comment by Technoboy-** [comment]
#14261 #15031 may fix this issue. Suggest to upgrade to v2.8.3
