### ISSUE TITLE
Flaky-test: schema_test.SchemaTest.test_field_type_check

### ISSUE THREAD

**Issue by RobertIndie** [apache/pulsar#16467]
schema_test.SchemaTest.test_field_type_check is flaky. It fails sporadically.

[example failure](https://github.com/apache/pulsar/runs/7245006983?check_suite_focus=true#step:11:1715)

```
ERROR: test_field_type_check (schema_test.SchemaTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/schema_test.py", line 288, in test_field_type_check
    self._expectTypeError(lambda: E9(a=[1, 2, 3]))
  File "/tmp/schema_test.py", line 202, in _expectTypeError
    func()
  File "/tmp/schema_test.py", line 288, in <lambda>
    self._expectTypeError(lambda: E9(a=[1, 2, 3]))
  File "/usr/local/lib/python3.8/dist-packages/pulsar/schema/definition.py", line 94, in __init__
    self.__setattr__(k, kwargs[k])
  File "/usr/local/lib/python3.8/dist-packages/pulsar/schema/definition.py", line 164, in __setattr__
    value = field.validate_type(key, value)
  File "/usr/local/lib/python3.8/dist-packages/pulsar/schema/definition.py", line 450, in validate_type
    self.array_type.type().__name__)
AttributeError: 'str' object has no attribute '__name__'
```

<!-- optionally provide the full stacktrace ->
<details>
<summary>Full exception stacktrace</summary>
<code><pre>
full exception stacktrace here
</pre></code>
</details>

**Comment by tisonkun** [comment]
Closed as stale. Python client has been moved out.
