### ISSUE TITLE
Master: flaky tests

### ISSUE THREAD

**Issue by Technoboy-** [apache/pulsar#16496]
Stack Trace
```
Error:  Tests run: 10, Failures: 1, Errors: 0, Skipped: 9, Time elapsed: 65.361 s <<< FAILURE! - in org.apache.pulsar.broker.service.NonPersistentTopicE2ETest
  Error:  testGC(org.apache.pulsar.broker.service.NonPersistentTopicE2ETest)  Time elapsed: 0.403 s  <<< FAILURE!
  java.lang.AssertionError: expected [false] but found [true]
  	at org.testng.Assert.fail(Assert.java:99)
  	at org.testng.Assert.failNotEquals(Assert.java:1037)
  	at org.testng.Assert.assertFalse(Assert.java:67)
  	at org.testng.Assert.assertFalse(Assert.java:77)
  	at org.apache.pulsar.broker.service.NonPersistentTopicE2ETest.testGC(NonPersistentTopicE2ETest.java:202)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)</summary>
```

**Comment by Technoboy-** [comment]
```
Error:  Tests run: 8, Failures: 2, Errors: 0, Skipped: 6, Time elapsed: 0.055 s <<< FAILURE! - in org.apache.pulsar.broker.service.PersistentDispatcherFailoverConsumerTest
  Error:  shutdown(org.apache.pulsar.broker.service.PersistentDispatcherFailoverConsumerTest)  Time elapsed: 0.053 s  <<< FAILURE!
  java.lang.NullPointerException: Cannot invoke "org.apache.bookkeeper.common.util.OrderedExecutor.shutdown()" because "this.executor" is null
  	at org.apache.pulsar.broker.service.PersistentDispatcherFailoverConsumerTest.shutdown(PersistentDispatcherFailoverConsumerTest.java:207)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
  	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
  	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
  	at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:701)
  	at org.testng.internal.TestInvoker.runAfterGroupsConfigurations(TestInvoker.java:677)
  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:661)
  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)

```

**Comment by Technoboy-** [comment]
```
Error:  Tests run: 8, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 97.994 s <<< FAILURE! - in org.apache.pulsar.broker.service.persistent.PersistentTopicTest
  Error:  testUnblockStuckSubscription(org.apache.pulsar.broker.service.persistent.PersistentTopicTest)  Time elapsed: 2.375 s  <<< FAILURE!
  java.lang.AssertionError: expected [null] but found [org.apache.pulsar.client.impl.MessageImpl@5cc10e7e]
  	at org.testng.Assert.fail(Assert.java:99)
  	at org.testng.Assert.failNotSame(Assert.java:1033)
  	at org.testng.Assert.assertNull(Assert.java:965)
  	at org.testng.Assert.assertNull(Assert.java:953)
  	at org.apache.pulsar.broker.service.persistent.PersistentTopicTest.testUnblockStuckSubscription(PersistentTopicTest.java:147)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

**Comment by Technoboy-** [comment]
```
Error:  Tests run: 6, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 73.003 s <<< FAILURE! - in org.apache.pulsar.broker.service.persistent.PersistentFailoverStreamingDispatcherE2ETest
  Error:  testSimpleConsumerEventsWithoutPartition(org.apache.pulsar.broker.service.persistent.PersistentFailoverStreamingDispatcherE2ETest)  Time elapsed: 0.689 s  <<< FAILURE!
  java.lang.AssertionError: expected [0] but found [29]
  	at org.testng.Assert.fail(Assert.java:99)
  	at org.testng.Assert.failNotEquals(Assert.java:1037)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
  	at org.testng.Assert.assertEquals(Assert.java:122)
  	at org.testng.Assert.assertEquals(Assert.java:797)
  	at org.testng.Assert.assertEquals(Assert.java:807)
  	at org.apache.pulsar.broker.service.PersistentFailoverE2ETest.testSimpleConsumerEventsWithoutPartition(PersistentFailoverE2ETest.java:204)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
```

**Comment by Technoboy-** [comment]
```
Error:  Tests run: 15, Failures: 7, Errors: 0, Skipped: 8, Time elapsed: 50.191 s <<< FAILURE! - in org.apache.pulsar.broker.service.persistent.PersistentDispatcherFailoverConsumerStreamingDispatcherTest
  Error:  testAddRemoveConsumer(org.apache.pulsar.broker.service.persistent.PersistentDispatcherFailoverConsumerStreamingDispatcherTest)  Time elapsed: 10.166 s  <<< FAILURE!
  java.lang.NullPointerException: Cannot invoke "org.apache.pulsar.common.api.proto.CommandActiveConsumerChange.getConsumerId()" because "change" is null
  	at org.apache.pulsar.broker.service.PersistentDispatcherFailoverConsumerTest.verifyActiveConsumerChange(PersistentDispatcherFailoverConsumerTest.java:285)
  	at org.apache.pulsar.broker.service.PersistentDispatcherFailoverConsumerTest.testAddRemoveConsumer(PersistentDispatcherFailoverConsumerTest.java:408)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
```

**Comment by Technoboy-** [comment]
```
Error:  Tests run: 9, Failures: 3, Errors: 0, Skipped: 3, Time elapsed: 31.381 s <<< FAILURE! - in org.apache.pulsar.broker.service.MessageCumulativeAckTest
  Error:  setup(org.apache.pulsar.broker.service.MessageCumulativeAckTest)  Time elapsed: 0.394 s  <<< FAILURE!
  org.mockito.exceptions.misusing.WrongTypeOfReturnValue: 
  
  BrokerService cannot be returned by getPulsarResources()
  getPulsarResources() should return PulsarResources
  ***
  If you're unsure why you're getting above error read on.
  Due to the nature of the syntax above problem might occur because:
  1. This exception *might* occur in wrongly written multi-threaded tests.
     Please refer to Mockito FAQ on limitations of concurrency testing.
  2. A spy is stubbed using when(spy.foo()).then() syntax. It is safer to stub spies - 
     - with doReturn|Throw() family of methods. More in javadocs for Mockito.spy() method.
  
  	at org.apache.pulsar.broker.PulsarService.getBrokerService(PulsarService.java:1242)
  	at org.apache.pulsar.broker.service.MessageCumulativeAckTest.setup(MessageCumulativeAckTest.java:110)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
```

**Comment by Technoboy-** [comment]
```
Error:  Tests run: 36, Failures: 9, Errors: 0, Skipped: 27, Time elapsed: 110.475 s <<< FAILURE! - in org.apache.pulsar.client.impl.PatternTopicsConsumerImplTest
  Error:  testAutoSubscribePatternConsumer(org.apache.pulsar.client.impl.PatternTopicsConsumerImplTest)  Time elapsed: 90.009 s  <<< FAILURE!
  org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.client.impl.PatternTopicsConsumerImplTest.testAutoSubscribePatternConsumer() didn't finish within the time-out 90000
```

**Comment by Technoboy-** [comment]
```
2022-07-11T01:58:32.3133601Z [ERROR] Tests run: 10, Failures: 1, Errors: 0, Skipped: 9, Time elapsed: 178.706 s <<< FAILURE! - in org.apache.pulsar.broker.service.plugin.FilterEntryTest
2022-07-11T01:58:32.3139565Z [ERROR] testEntryFilterRescheduleMessageDependingOnConsumerSharedSubscription(org.apache.pulsar.broker.service.plugin.FilterEntryTest)  Time elapsed: 61.154 s  <<< FAILURE!
2022-07-11T01:58:32.3141639Z java.util.concurrent.TimeoutException
2022-07-11T01:58:32.3142644Z 	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
2022-07-11T01:58:32.3143815Z 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
2022-07-11T01:58:32.3145808Z 	at org.apache.pulsar.broker.service.plugin.FilterEntryTest.testEntryFilterRescheduleMessageDependingOnConsumerSharedSubscription(FilterEntryTest.java:326)
2022-07-11T01:58:32.3147497Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-07-11T01:58:32.3148636Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
```

**Comment by Technoboy-** [comment]
```
2022-07-11T02:07:23.1365128Z [INFO] Running org.apache.pulsar.broker.stats.ManagedLedgerMetricsTest
2022-07-11T02:07:37.2828233Z [ERROR] Tests run: 18, Failures: 3, Errors: 0, Skipped: 9, Time elapsed: 128.822 s <<< FAILURE! - in org.apache.pulsar.broker.intercept.BrokerInterceptorTest
2022-07-11T02:07:37.2832018Z [ERROR] testProducerCreation(org.apache.pulsar.broker.intercept.BrokerInterceptorTest)  Time elapsed: 0.247 s  <<< FAILURE!
2022-07-11T02:07:37.2832880Z java.lang.AssertionError: expected [true] but found [false]
2022-07-11T02:07:37.2833545Z 	at org.testng.Assert.fail(Assert.java:99)
2022-07-11T02:07:37.2834124Z 	at org.testng.Assert.failNotEquals(Assert.java:1037)
2022-07-11T02:07:37.2834733Z 	at org.testng.Assert.assertTrue(Assert.java:45)
2022-07-11T02:07:37.2835320Z 	at org.testng.Assert.assertTrue(Assert.java:55)
2022-07-11T02:07:37.2836262Z 	at org.apache.pulsar.broker.intercept.BrokerInterceptorTest.testProducerCreation(BrokerInterceptorTest.java:145)
```

**Comment by Technoboy-** [comment]
```
2022-07-11T01:50:13.6787248Z [ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 88.325 s <<< FAILURE! - in org.apache.pulsar.broker.service.persistent.PersistentFailoverStreamingDispatcherE2ETest
2022-07-11T01:50:13.6792631Z [ERROR] testSimpleConsumerEventsWithoutPartition(org.apache.pulsar.broker.service.persistent.PersistentFailoverStreamingDispatcherE2ETest)  Time elapsed: 0.78 s  <<< FAILURE!
2022-07-11T01:50:13.6886571Z java.lang.AssertionError: expected [0] but found [17]
2022-07-11T01:50:13.6887170Z 	at org.testng.Assert.fail(Assert.java:99)
2022-07-11T01:50:13.6887771Z 	at org.testng.Assert.failNotEquals(Assert.java:1037)
2022-07-11T01:50:13.6888457Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
2022-07-11T01:50:13.6889122Z 	at org.testng.Assert.assertEquals(Assert.java:122)
2022-07-11T01:50:13.6889659Z 	at org.testng.Assert.assertEquals(Assert.java:797)
2022-07-11T01:50:13.6890082Z 	at org.testng.Assert.assertEquals(Assert.java:807)
2022-07-11T01:50:13.6890900Z 	at org.apache.pulsar.broker.service.PersistentFailoverE2ETest.testSimpleConsumerEventsWithoutPartition(PersistentFailoverE2ETest.java:204)
```

**Comment by Technoboy-** [comment]
```
2022-07-11T01:39:45.9410569Z [ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 110.339 s <<< FAILURE! - in org.apache.pulsar.broker.service.PersistentFailoverE2ETest
2022-07-11T01:39:45.9414746Z [ERROR] testSimpleConsumerEventsWithoutPartition(org.apache.pulsar.broker.service.PersistentFailoverE2ETest)  Time elapsed: 0.782 s  <<< FAILURE!
2022-07-11T01:39:45.9416116Z java.lang.AssertionError: expected [0] but found [30]
2022-07-11T01:39:45.9416846Z 	at org.testng.Assert.fail(Assert.java:99)
2022-07-11T01:39:45.9417397Z 	at org.testng.Assert.failNotEquals(Assert.java:1037)
2022-07-11T01:39:45.9418030Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
2022-07-11T01:39:45.9418748Z 	at org.testng.Assert.assertEquals(Assert.java:122)
2022-07-11T01:39:45.9419333Z 	at org.testng.Assert.assertEquals(Assert.java:797)
2022-07-11T01:39:45.9419922Z 	at org.testng.Assert.assertEquals(Assert.java:807)
2022-07-11T01:39:45.9420885Z 	at org.apache.pulsar.broker.service.PersistentFailoverE2ETest.testSimpleConsumerEventsWithoutPartition(PersistentFailoverE2ETest.java:204)
```

**Comment by Technoboy-** [comment]
```
2022-07-11T01:45:34.4237922Z [ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 98.061 s <<< FAILURE! - in org.apache.pulsar.broker.service.ManagedLedgerCompressionTest
2022-07-11T01:45:34.4244376Z [ERROR] testRestartBrokerEnableManagedLedgerInfoCompression(org.apache.pulsar.broker.service.ManagedLedgerCompressionTest)  Time elapsed: 21.105 s  <<< FAILURE!
2022-07-11T01:45:34.4348235Z org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.broker.service.ManagedLedgerCompressionTest.testRestartBrokerEnableManagedLedgerInfoCompression() didn't finish within the time-out 20000
2022-07-11T01:45:34.4349749Z 	at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:371)
2022-07-11T01:45:34.4350706Z 	at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:282)
2022-07-11T01:45:34.4351420Z 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:605)
2022-07-11T01:45:34.4352896Z 	at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:
```

**Comment by Technoboy-** [comment]
```
2022-07-11T01:45:46.1928254Z [INFO] Running org.apache.pulsar.broker.service.persistent.DelayedDeliveryTest
2022-07-11T01:46:21.1161732Z [ERROR] Tests run: 79, Failures: 1, Errors: 0, Skipped: 73, Time elapsed: 43.067 s <<< FAILURE! - in org.apache.pulsar.broker.service.persistent.PersistentTopicStreamingDispatcherTest
2022-07-11T01:46:21.1167248Z [ERROR] setup(org.apache.pulsar.broker.service.persistent.PersistentTopicStreamingDispatcherTest)  Time elapsed: 0.643 s  <<< FAILURE!
2022-07-11T01:46:21.1277496Z org.mockito.exceptions.base.MockitoException: Unable to create mock instance of type 'ServerCnx'
2022-07-11T01:46:21.1278349Z 	at org.apache.pulsar.broker.BrokerTestUtil.spyWithClassAndConstructorArgs(BrokerTestUtil.java:43)
2022-07-11T01:46:21.1279550Z 	at org.apache.pulsar.broker.service.PersistentTopicTest.setup(PersistentTopicTest.java:226)
2022-07-11T01:46:21.1280555Z 	at org.apache.pulsar.broker.service.persistent.PersistentTopicStreamingDispatcherTest.setup(PersistentTopicStreamingDispatcherTest.java:34)
2022-07-11T01:46:21.1281497Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-07-11T01:46:21.1282202Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2022-07-11T01:46:21.1283538Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-07-11T01:46:21.1284194Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2022-07-11T01:46:21.1284831Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
2022-07-11T01:46:21.1285658Z 	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
2022-07-11T01:46:21.1287067Z 	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
2022-07-11T01:46:21.1287821Z 	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
2022-07-11T01:46:21.1288523Z 	at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:701)
2022-07-11T01:46:21.1289221Z 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:527)
2022-07-11T01:46:21.1289888Z 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
2022-07-11T01:46:21.1290551Z 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
2022-07-11T01:46:21.1291184Z 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
2022-07-11T01:46:21.1291827Z 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
2022-07-11T01:46:21.1292552Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
2022-07-11T01:46:21.1293271Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
2022-07-11T01:46:21.1294314Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2022-07-11T01:46:21.1294881Z 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
2022-07-11T01:46:21.1295348Z 	at org.testng.TestRunner.run(TestRunner.java:585)
2022-07-11T01:46:21.1295812Z 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
2022-07-11T01:46:21.1296563Z 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
2022-07-11T01:46:21.1297084Z 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
2022-07-11T01:46:21.1297532Z 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
2022-07-11T01:46:21.1298990Z 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
2022-07-11T01:46:21.1299586Z 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
2022-07-11T01:46:21.1300104Z 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
2022-07-11T01:46:21.1300607Z 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
2022-07-11T01:46:21.1301086Z 	at org.testng.TestNG.runSuites(TestNG.java:1069)
2022-07-11T01:46:21.1301798Z 	at org.testng.TestNG.run(TestNG.java:1037)
2022-07-11T01:46:21.1302406Z 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
2022-07-11T01:46:21.1303249Z 	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
2022-07-11T01:46:21.1305198Z 	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
2022-07-11T01:46:21.1306251Z 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
2022-07-11T01:46:21.1307067Z 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
2022-07-11T01:46:21.1308230Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
2022-07-11T01:46:21.1308963Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
2022-07-11T01:46:21.1309612Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
2022-07-11T01:46:21.1310231Z Caused by: org.mockito.creation.instance.InstantiationException: 
2022-07-11T01:46:21.1310987Z Unable to create instance of 'ServerCnx'.
2022-07-11T01:46:21.1311602Z Please ensure the target class has a constructor that matches these argument types: [org.apache.pulsar.broker.PulsarService] and executes cleanly.
2022-07-11T01:46:21.1312173Z 	... 40 more
2022-07-11T01:46:21.1312605Z Caused by: java.lang.reflect.InvocationTargetException
2022-07-11T01:46:21.1313866Z 	at org.mockito.internal.util.reflection.InstrumentationMemberAccessor.newInstance(InstrumentationMemberAccessor.java:198)
2022-07-11T01:46:21.1315299Z 	at org.mockito.internal.util.reflection.InstrumentationMemberAccessor.newInstance(InstrumentationMemberAccessor.java:161)
2022-07-11T01:46:21.1316347Z 	at org.mockito.internal.util.reflection.ModuleMemberAccessor.newInstance(ModuleMemberAccessor.java:42)
2022-07-11T01:46:21.1317637Z 	at org.mockito.internal.creation.instance.ConstructorInstantiator.invokeConstructor(ConstructorInstantiator.java:70)
2022-07-11T01:46:21.1318814Z 	at org.mockito.internal.creation.instance.ConstructorInstantiator.withParams(ConstructorInstantiator.java:53)
2022-07-11T01:46:21.1319970Z 	at org.mockito.internal.creation.instance.ConstructorInstantiator.newInstance(ConstructorInstantiator.java:39)
2022-07-11T01:46:21.1322671Z 	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.doCreateMock(InlineDelegateByteBuddyMockMaker.java:360)
2022-07-11T01:46:21.1324060Z 	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createMock(InlineDelegateByteBuddyMockMaker.java:330)
2022-07-11T01:46:21.1325193Z 	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMock(InlineByteBuddyMockMaker.java:58)
2022-07-11T01:46:21.1326462Z 	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:53)
2022-07-11T01:46:21.1327128Z 	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:84)
2022-07-11T01:46:21.1327717Z 	at org.mockito.Mockito.mock(Mockito.java:1964)
2022-07-11T01:46:21.1328100Z 	... 40 more
2022-07-11T01:46:21.1330363Z Caused by: java.lang.ClassCastException: class org.apache.pulsar.broker.service.BrokerService cannot be cast to class org.apache.pulsar.broker.resources.PulsarResources (org.apache.pulsar.broker.service.BrokerService and org.apache.pulsar.broker.resources.PulsarResources are in unnamed module of loader 'app')
2022-07-11T01:46:21.1331999Z 	at org.apache.pulsar.broker.PulsarService.getPulsarResources(PulsarService.java:265)
2022-07-11T01:46:21.1332769Z 	at org.apache.pulsar.broker.service.TopicListService.<init>(TopicListService.java:103)
2022-07-11T01:46:21.1333524Z 	at org.apache.pulsar.broker.service.ServerCnx.<init>(ServerCnx.java:279)
2022-07-11T01:46:21.1334159Z 	at org.apache.pulsar.broker.service.ServerCnx.<init>(ServerCnx.java:239)
2022-07-11T01:46:21.1334841Z 	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
2022-07-11T01:46:21.1335763Z 	at org.mockito.internal.util.reflection.InstrumentationMemberAccessor$Dispatcher$ByteBuddy$odOJstKk.invokeWithArguments(Unknown Source)
2022-07-11T01:46:21.1382388Z 	at org.mockito.internal.util.reflection.InstrumentationMemberAccessor.lambda$newInstance$0(InstrumentationMemberAccessor.java:191)
2022-07-11T01:46:21.1383683Z 	at org.mockito.internal.util.reflection.InstrumentationMemberAccessor.newInstance(InstrumentationMemberAccessor.java:188)
2022-07-11T01:46:21.1384306Z 	... 51 more
```

**Comment by lhotari** [comment]
@Technoboy- Please report each flaky test independently. It's not very useful to collect all failures in a single issue.
