### ISSUE TITLE
Flaky-test: PersistentDispatcherFailoverConsumerTest. testAddRemoveConsumerNonPartitionedTopic

### ISSUE THREAD

**Issue by Technoboy-** [apache/pulsar#16498]
```
Error:  Tests run: 14, Failures: 6, Errors: 0, Skipped: 7, Time elapsed: 21.986 s <<< FAILURE! - in org.apache.pulsar.broker.service.PersistentDispatcherFailoverConsumerTest
  Error:  testAddRemoveConsumerNonPartitionedTopic(org.apache.pulsar.broker.service.PersistentDispatcherFailoverConsumerTest)  Time elapsed: 1.056 s  <<< FAILURE!
  Wanted but not invoked:
  consumer.notifyActiveConsumerChange(
      same(Consumer{subscription=PersistentSubscription{topic=persistent://part-perf/global/perf.t1/ptopic, name=sub-1}, consumerId=2, consumerName=Cons2, address=localhost/127.0.0.1:1234})
  );
  -> at org.apache.pulsar.broker.service.Consumer.notifyActiveConsumerChange(Consumer.java:218)
  
  However, there was exactly 1 interaction with this mock:
  consumer.notifyActiveConsumerChange(
      Consumer{subscription=PersistentSubscription{topic=persistent://part-perf/global/perf.t1/ptopic, name=sub-1}, consumerId=1, consumerName=Cons1, address=localhost/127.0.0.1:1234}
  );
  -> at org.apache.pulsar.broker.service.AbstractDispatcherSingleActiveConsumer.addConsumer(AbstractDispatcherSingleActiveConsumer.java:180)
  
  
  	at org.apache.pulsar.broker.service.Consumer.notifyActiveConsumerChange(Consumer.java:218)
  	at org.apache.pulsar.broker.service.PersistentDispatcherFailoverConsumerTest.testAddRemoveConsumerNonPartitionedTopic(PersistentDispatcherFailoverConsumerTest.java:502)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by poorbarcode** [comment]
The logic of test `testAddRemoveConsumerNonPartitionedTopic` has changed now, we should close this issue.
