### ISSUE TITLE
Flaky-test: ManagedLedgerCompressionTest. testRestartBrokerEnableManagedLedgerInfoCompression

### ISSUE THREAD

**Issue by Technoboy-** [apache/pulsar#16497]
```
Error:  Tests run: 4, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 78.765 s <<< FAILURE! - in org.apache.pulsar.broker.service.ManagedLedgerCompressionTest
  Error:  testRestartBrokerEnableManagedLedgerInfoCompression(org.apache.pulsar.broker.service.ManagedLedgerCompressionTest)  Time elapsed: 20.018 s  <<< FAILURE!
  org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.broker.service.ManagedLedgerCompressionTest.testRestartBrokerEnableManagedLedgerInfoCompression() didn't finish within the time-out 20000
  	at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:371)
  	at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:282)
  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:605)
  	at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
  	at org.testng.TestRunner.run(TestRunner.java:[585](https://github.com/apache/pulsar/runs/7263165064?check_suite_focus=true#step:10:586))
  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
  	at org.testng.TestNG.runSuites(TestNG.java:1069)
  	at org.testng.TestNG.run(TestNG.java:1037)
  	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
  	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
```

**Comment by lhotari** [comment]
Recent failure https://github.com/apache/pulsar/actions/runs/4162624968/jobs/7219477678#step:11:1176

```
Error:  Tests run: 5, Failures: 1, Errors: 0, Skipped: 4, Time elapsed: 49.726 s <<< FAILURE! - in org.apache.pulsar.broker.service.ManagedLedgerCompressionTest
  Error:  testRestartBrokerEnableManagedLedgerInfoCompression(org.apache.pulsar.broker.service.ManagedLedgerCompressionTest)  Time elapsed: 20.044 s  <<< FAILURE!
  org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.broker.service.ManagedLedgerCompressionTest.testRestartBrokerEnableManagedLedgerInfoCompression() didn't finish within the time-out 20000
  	at java.base@17.0.6/jdk.internal.misc.Unsafe.park(Native Method)
  	at java.base@17.0.6/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
  	at java.base@17.0.6/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
  	at java.base@17.0.6/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
  	at java.base@17.0.6/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
  	at java.base@17.0.6/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
  	at java.base@17.0.6/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2072)
  	at app//org.apache.pulsar.client.impl.PulsarClientImpl.close(PulsarClientImpl.java:713)
  	at app//org.apache.pulsar.broker.PulsarService.closeAsync(PulsarService.java:524)
  	at java.base@17.0.6/java.lang.invoke.DirectMethodHandle$Holder.invokeVirtual(DirectMethodHandle$Holder)
  	at java.base@17.0.6/java.lang.invoke.LambdaForm$MH/0x00000008016db800.invoke(LambdaForm$MH)
  	at java.base@17.0.6/java.lang.invoke.LambdaForm$MH/0x00000008016d9c00.invoke(LambdaForm$MH)
  	at java.base@17.0.6/java.lang.invoke.LambdaForm$MH/0x0000000800c3f800.invokeExact_MT(LambdaForm$MH)
  	at java.base@17.0.6/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
  	at org.mockito.internal.util.reflection.InstrumentationMemberAccessor$Dispatcher$ByteBuddy$iBuBO5ry.invokeWithArguments(Unknown Source)
  	at app//org.mockito.internal.util.reflection.InstrumentationMemberAccessor.invoke(InstrumentationMemberAccessor.java:239)
  	at app//org.mockito.internal.util.reflection.ModuleMemberAccessor.invoke(ModuleMemberAccessor.java:55)
  	at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.tryInvoke(MockMethodAdvice.java:333)
  	at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.access$500(MockMethodAdvice.java:60)
  	at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice$RealMethodCall.invoke(MockMethodAdvice.java:253)
  	at app//org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:142)
  	at app//org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:45)
  	at app//org.mockito.Answers.answer(Answers.java:99)
  	at app//org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:110)
  	at app//org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
  	at app//org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
  	at app//org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
  	at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handle(MockMethodAdvice.java:151)
  	at app//org.apache.pulsar.broker.PulsarService.closeAsync(PulsarService.java:408)
  	at app//org.apache.pulsar.broker.PulsarService.close(PulsarService.java:387)
  	at java.base@17.0.6/java.lang.invoke.LambdaForm$DMH/0x0000000800fec800.invokeVirtual(LambdaForm$DMH)
  	at java.base@17.0.6/java.lang.invoke.LambdaForm$MH/0x00000008014e0400.invoke(LambdaForm$MH)
  	at java.base@17.0.6/java.lang.invoke.LambdaForm$MH/0x00000008016d9c00.invoke(LambdaForm$MH)
  	at java.base@17.0.6/java.lang.invoke.LambdaForm$MH/0x0000000800c3f800.invokeExact_MT(LambdaForm$MH)
  	at java.base@17.0.6/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
  	at org.mockito.internal.util.reflection.InstrumentationMemberAccessor$Dispatcher$ByteBuddy$iBuBO5ry.invokeWithArguments(Unknown Source)
  	at app//org.mockito.internal.util.reflection.InstrumentationMemberAccessor.invoke(InstrumentationMemberAccessor.java:239)
  	at app//org.mockito.internal.util.reflection.ModuleMemberAccessor.invoke(ModuleMemberAccessor.java:55)
  	at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.tryInvoke(MockMethodAdvice.java:333)
  	at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.access$500(MockMethodAdvice.java:60)
  	at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice$RealMethodCall.invoke(MockMethodAdvice.java:253)
  	at app//org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:142)
  	at app//org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:45)
  	at app//org.mockito.Answers.answer(Answers.java:99)
  	at app//org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:110)
  	at app//org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
  	at app//org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
  	at app//org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
  	at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handle(MockMethodAdvice.java:151)
  	at app//org.apache.pulsar.broker.PulsarService.close(PulsarService.java:387)
  	at app//org.apache.pulsar.broker.auth.MockedPulsarServiceBaseTest.stopBroker(MockedPulsarServiceBaseTest.java:279)
  	at app//org.apache.pulsar.broker.service.ManagedLedgerCompressionTest.testRestartBrokerEnableManagedLedgerInfoCompression(ManagedLedgerCompressionTest.java:79)
  	at java.base@17.0.6/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base@17.0.6/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base@17.0.6/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base@17.0.6/java.lang.reflect.Method.invoke(Method.java:568)
  	at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base@17.0.6/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base@17.0.6/java.lang.Thread.run(Thread.java:833)
```

**Comment by poorbarcode** [comment]
another one: https://github.com/apache/pulsar/actions/runs/4366235019/jobs/7636165465

**Comment by coderzc** [comment]
another one: https://github.com/apache/pulsar/actions/runs/4413610159/jobs/7734530087

**Comment by poorbarcode** [comment]
Another one: https://github.com/apache/pulsar/actions/runs/4900653270/jobs/8751562365?pr=20232

**Comment by lhotari** [comment]
again: https://github.com/lhotari/pulsar/actions/runs/4924107742/jobs/8797156674#step:10:1381

**Comment by lhotari** [comment]
again https://github.com/apache/pulsar/actions/runs/5056774399/jobs/9079880762?pr=20372#step:10:1214
