### ISSUE TITLE
Flaky-test: BrokerServiceTest.testLookupThrottlingForClientByClient

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#16521]
```
  Error:  Tests run: 44, Failures: 1, Errors: 0, Skipped: 31, Time elapsed: 116.962 s <<< FAILURE! - in org.apache.pulsar.broker.service.BrokerServiceTest
  Error:  testLookupThrottlingForClientByClient(org.apache.pulsar.broker.service.BrokerServiceTest)  Time elapsed: 0.482 s  <<< FAILURE!
  java.lang.AssertionError: At least one should fail
  	at org.testng.Assert.fail(Assert.java:99)
  	at org.apache.pulsar.broker.service.BrokerServiceTest.testLookupThrottlingForClientByClient(BrokerServiceTest.java:1065)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```
[example failure](https://github.com/apache/pulsar/runs/7277547968?check_suite_focus=true)

<!-- optionally provide the full stacktrace ->
<details>
<summary>Full exception stacktrace</summary>
<code><pre>
full exception stacktrace here
</pre></code>
</details>

**Comment by poorbarcode** [comment]
assign to me

**Comment by lhotari** [comment]
This continues to be flaky:
recent failure in https://github.com/apache/pulsar/actions/runs/12957233886/job/36170976644?pr=23893#step:11:1703
```
  Error:  Tests run: 74, Failures: 1, Errors: 0, Skipped: 55, Time elapsed: 222.371 s <<< FAILURE! - in org.apache.pulsar.broker.service.BrokerServiceTest
  Error:  org.apache.pulsar.broker.service.BrokerServiceTest.testLookupThrottlingForClientByClient  Time elapsed: 60.047 s  <<< FAILURE!
  java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException$TimeoutException: Lookup request timeout {'durationMs': '30000', 'reqId':'-559038730', 'remote':'localhost/127.0.0.1:45235', 'local':'/127.0.0.1:49716'}
  	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
  	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
  	at org.apache.pulsar.broker.service.BrokerServiceTest.testLookupThrottlingForClientByClient(BrokerServiceTest.java:1141)
  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  	at java.base/java.lang.Thread.run(Thread.java:1583)
  Caused by: org.apache.pulsar.client.api.PulsarClientException$TimeoutException: Lookup request timeout {'durationMs': '30000', 'reqId':'-559038730', 'remote':'localhost/127.0.0.1:45235', 'local':'/127.0.0.1:49716'}
  	at org.apache.pulsar.client.impl.ClientCnx.checkRequestTimeout(ClientCnx.java:1422)
  	at org.apache.pulsar.common.util.Runnables$CatchingAndLoggingRunnable.run(Runnables.java:54)
  	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
  	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:162)
  	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
  	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
  	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
  	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:408)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  	... 1 more
```
