### ISSUE TITLE
Flaky-test: org.apache.pulsar.functions.worker.PulsarFunctionTlsTest.PulsarFunctionTlsTest

### ISSUE THREAD

**Issue by nodece** [apache/pulsar#16538]
```
Error:  tearDown(org.apache.pulsar.functions.worker.PulsarFunctionTlsTest)  Time elapsed: 132.024 s  <<< FAILURE!
  org.apache.pulsar.broker.PulsarServerException: java.util.concurrent.TimeoutException
  	at org.apache.pulsar.broker.PulsarService.closeAsync(PulsarService.java:581)
  	at org.apache.pulsar.broker.PulsarService.close(PulsarService.java:380)
  	at org.apache.pulsar.functions.worker.PulsarFunctionTlsTest.tearDown(PulsarFunctionTlsTest.java:185)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
  	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
  	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
  	at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:701)
  	at org.testng.internal.TestInvoker.runAfterGroupsConfigurations(TestInvoker.java:677)
  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:661)
  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
  	at org.testng.TestRunner.run(TestRunner.java:585)
  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
  	at org.testng.TestNG.runSuites(TestNG.java:1069)
  	at org.testng.TestNG.run(TestNG.java:1037)
  	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeLazy(TestNGDirectoryTestSuite.java:123)
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:90)
  	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
  	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
  	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
  	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
  	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
  Caused by: java.util.concurrent.TimeoutException
  	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
  	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
  	at org.apache.pulsar.metadata.coordination.impl.CoordinationServiceImpl.close(CoordinationServiceImpl.java:75)
  	at org.apache.pulsar.broker.PulsarService.closeAsync(PulsarService.java:533)
  	... 41 more
  ```

**Comment by codelipenghui** [comment]
@nodece Do you want to fix this flaky test?

**Comment by codelipenghui** [comment]
A new one https://github.com/apache/pulsar/runs/7471854513?check_suite_focus=true

**Comment by nodece** [comment]
> @nodece Do you want to fix this flaky test?

Okay

**Comment by coderzc** [comment]
I also met this problem: https://github.com/apache/pulsar/runs/7492227697?check_suite_focus=true

**Comment by Technoboy-** [comment]
Closed by #16765

**Comment by nodece** [comment]
#16765 cannot fix this issue. 

Met this issue again: https://github.com/apache/pulsar/runs/7535091922?check_suite_focus=true#step:10:1253

**Comment by codelipenghui** [comment]
A new one https://github.com/apache/pulsar/runs/7709485227?check_suite_focus=true

**Comment by nodece** [comment]
Thread blocked:
```
"main" prio=0 tid=0x0 nid=0x0 waiting on condition
     java.lang.Thread.State: TIMED_WAITING
 on java.util.concurrent.CompletableFuture$Signaller@6d214cc3
	at java.base@17.0.3/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@17.0.3/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
	at java.base@17.0.3/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1866)
	at java.base@17.0.3/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
	at java.base@17.0.3/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
	at java.base@17.0.3/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1939)
	at java.base@17.0.3/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at app//org.apache.pulsar.broker.service.BrokerService.lambda$unloadNamespaceBundlesGracefully$21(BrokerService.java:939)
	at app//org.apache.pulsar.broker.service.BrokerService$$Lambda$1486/0x00000008015f1c70.accept(Unknown Source)
	at java.base@17.0.3/java.lang.Iterable.forEach(Iterable.java:75)
	at app//org.apache.pulsar.broker.service.BrokerService.unloadNamespaceBundlesGracefully(BrokerService.java:930)
	at app//org.apache.pulsar.broker.service.BrokerService.unloadNamespaceBundlesGracefully(BrokerService.java:902)
	at app//org.apache.pulsar.broker.service.BrokerService.closeAsync(BrokerService.java:737)
	at app//org.apache.pulsar.broker.PulsarService.closeAsync(PulsarService.java:462)
	at app//org.apache.pulsar.functions.worker.PulsarFunctionTlsTest.tearDown(PulsarFunctionTlsTest.java:193)
	at java.base@17.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.3/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.3/java.lang.reflect.Method.invoke(Method.java:568)
	at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at app//org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
	at app//org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
	at app//org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
	at app//org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:701)
	at app//org.testng.internal.TestInvoker.runAfterGroupsConfigurations(TestInvoker.java:677)
	at app//org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:661)
	at app//org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
	at app//org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at app//org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at app//org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at app//org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at app//org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at app//org.testng.TestRunner$$Lambda$161/0x0000000800d8c258.accept(Unknown Source)
	at java.base@17.0.3/java.util.ArrayList.forEach(ArrayList.java:1511)
	at app//org.testng.TestRunner.privateRun(TestRunner.java:764)
	at app//org.testng.TestRunner.run(TestRunner.java:585)
	at app//org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at app//org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at app//org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at app//org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at app//org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at app//org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at app//org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
	at app//org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at app//org.testng.TestNG.runSuites(TestNG.java:1069)
	at app//org.testng.TestNG.run(TestNG.java:1037)
	at app//com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at app//com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
```

Make `unloadNamespaceBundlesGracefully` to async.

**Comment by codelipenghui** [comment]
A new one: https://github.com/apache/pulsar/runs/7781756219?check_suite_focus=true

**Comment by poorbarcode** [comment]
Should we close this issue ?
