### ISSUE TITLE
Flaky-test: PersistentFailoverStreamingDispatcherE2ETest. testSimpleConsumerEventsWithoutPartition

### ISSUE THREAD

**Issue by RobertIndie** [apache/pulsar#16532]
PersistentFailoverStreamingDispatcherE2ETest. testSimpleConsumerEventsWithoutPartition is flaky. It fails sporadically.

[example failure](https://github.com/apache/pulsar/runs/7281271405?check_suite_focus=true#step:10:1626)

```
java.lang.AssertionError: expected [0] but found [47]
  	at org.testng.Assert.fail(Assert.java:99)
  	at org.testng.Assert.failNotEquals(Assert.java:1037)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
  	at org.testng.Assert.assertEquals(Assert.java:122)
  	at org.testng.Assert.assertEquals(Assert.java:797)
  	at org.testng.Assert.assertEquals(Assert.java:807)
  	at org.apache.pulsar.broker.service.PersistentFailoverE2ETest.testSimpleConsumerEventsWithoutPartition(PersistentFailoverE2ETest.java:204)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

<!-- optionally provide the full stacktrace ->
<details>
<summary>Full exception stacktrace</summary>
<code><pre>
full exception stacktrace here
</pre></code>
</details>

**Comment by RobertIndie** [comment]
Fixed by https://github.com/apache/pulsar/pull/16493

**Comment by BewareMyPower** [comment]
This test is still flaky: https://github.com/BewareMyPower/pulsar/actions/runs/4231135027/jobs/7349506262

It now could fail at 

```java
        verifyConsumerActive(listener1, -1);
```

I have run this test locally for 5 times, it failed twice.
