### ISSUE TITLE
Flaky-test: org.apache.pulsar.tests.integration.functions.java.PulsarFunctionsJavaThreadTest.testJavaLoggingFunction

### ISSUE THREAD

**Issue by nodece** [apache/pulsar#16558]
```
2022-07-12T22:19:13.6006402Z [ERROR] testJavaLoggingFunction(org.apache.pulsar.tests.integration.functions.java.PulsarFunctionsJavaThreadTest)  Time elapsed: 48.927 s  <<< FAILURE!
2022-07-12T22:19:13.6008084Z java.lang.NullPointerException: Cannot invoke "org.apache.pulsar.client.api.Message.getValue()" because "msg" is null
2022-07-12T22:19:13.6008984Z 	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.publishAndConsumeMessages(PulsarFunctionsTest.java:1590)
2022-07-12T22:19:13.6010283Z 	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testLoggingFunction(PulsarFunctionsTest.java:1509)
2022-07-12T22:19:13.6011380Z 	at org.apache.pulsar.tests.integration.functions.java.PulsarFunctionsJavaTest.testJavaLoggingFunction(PulsarFunctionsJavaTest.java:111)
2022-07-12T22:19:13.6012669Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-07-12T22:19:13.6013364Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2022-07-12T22:19:13.6014123Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-07-12T22:19:13.6014737Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2022-07-12T22:19:13.6015404Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
2022-07-12T22:19:13.6016011Z 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
2022-07-12T22:19:13.6016572Z 	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
2022-07-12T22:19:13.6022991Z 	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
2022-07-12T22:19:13.6023842Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-07-12T22:19:13.6024398Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2022-07-12T22:19:13.6024979Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2022-07-12T22:19:13.6025720Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2022-07-12T22:19:13.6025950Z 
```

**Comment by tisonkun** [comment]
Another instance: https://github.com/apache/pulsar/runs/7351817517?check_suite_focus=true

**Comment by shibd** [comment]
same https://github.com/apache/pulsar/issues/15392

**Comment by lhotari** [comment]
duplicates #15392
