### ISSUE TITLE
Flaky-test: PulsarSinkE2ETest.testPulsarSinkDLQ

### ISSUE THREAD

**Issue by nicoloboschi** [apache/pulsar#16578]
[example failure](https://github.com/apache/pulsar/runs/7320943955?check_suite_focus=true)

```
java.lang.AssertionError: expected object to not be null
  	at org.testng.Assert.fail(Assert.java:99)
  	at org.testng.Assert.assertNotNull(Assert.java:942)
  	at org.testng.Assert.assertNotNull(Assert.java:926)
  	at org.apache.pulsar.io.PulsarSinkE2ETest.testPulsarSinkDLQ(PulsarSinkE2ETest.java:195)
```

**Comment by codelipenghui** [comment]
A new one https://github.com/apache/pulsar/runs/7710408190?check_suite_focus=true

**Comment by codelipenghui** [comment]
Another one https://github.com/apache/pulsar/runs/7870706984?check_suite_focus=true

**Comment by nicoloboschi** [comment]
Another one: https://github.com/apache/pulsar/runs/7893473002?check_suite_focus=true

**Comment by lhotari** [comment]
another one https://github.com/apache/pulsar/runs/7988259367?check_suite_focus=true#step:10:1055

**Comment by lhotari** [comment]
another one https://github.com/apache/pulsar/runs/8303606708?check_suite_focus=true#step:10:1071

**Comment by coderzc** [comment]
another one https://github.com/coderzc/pulsar/actions/runs/3094888567/jobs/5008832313

**Comment by tisonkun** [comment]
another case https://github.com/apache/pulsar/actions/runs/3463258596/jobs/5800854674

**Comment by labuladong** [comment]
still flaky https://github.com/apache/pulsar/actions/runs/3599540010/jobs/6087484941#step:10:859

**Comment by Nicklee007** [comment]
another case https://github.com/apache/pulsar/actions/runs/3645973398/jobs/6159179081

**Comment by AnonHxy** [comment]
another case https://github.com/AnonHxy/pulsar/actions/runs/3691537854/jobs/6251074750
