### ISSUE TITLE
Flaky-test: TransactionEndToEndWithoutBatchIndexAckTest.txnAckTestBatchAndCumulativeSub

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#16589]
[example failure](https://github.com/apache/pulsar/runs/7327040379?check_suite_focus=true)

```
Error:  Tests run: 43, Failures: 1, Errors: 0, Skipped: 28, Time elapsed: 141.1 s <<< FAILURE! - in org.apache.pulsar.client.impl.TransactionEndToEndWithoutBatchIndexAckTest
  Error:  txnAckTestBatchAndCumulativeSub(org.apache.pulsar.client.impl.TransactionEndToEndWithoutBatchIndexAckTest)  Time elapsed: 4.778 s  <<< FAILURE!
  java.lang.AssertionError: expected object to not be null
  	at org.testng.Assert.fail(Assert.java:99)
  	at org.testng.Assert.assertNotNull(Assert.java:942)
  	at org.testng.Assert.assertNotNull(Assert.java:926)
  	at org.apache.pulsar.client.impl.TransactionEndToEndTest.txnCumulativeAckTest(TransactionEndToEndTest.java:612)
  	at org.apache.pulsar.client.impl.TransactionEndToEndTest.txnAckTestBatchAndCumulativeSub(TransactionEndToEndTest.java:540)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

<!-- optionally provide the full stacktrace ->
<details>
<summary>Full exception stacktrace</summary>
<code><pre>
full exception stacktrace here
</pre></code>
</details>

**Comment by congbobo184** [comment]
https://github.com/apache/pulsar/pull/16592 fixed.
