### ISSUE TITLE
Tests inherited from MockedPulsarServiceBaseTest cannot run locally

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar#16694]
It's because:

```java
    public final static String BROKER_KEYSTORE_FILE_PATH =
            Resources.getResource("certificate-authority/jks/broker.keystore.jks").getPath();
    public final static String BROKER_TRUSTSTORE_FILE_PATH =
            Resources.getResource("certificate-authority/jks/broker.truststore.jks").getPath();
    public final static String BROKER_TRUSTSTORE_NO_PASSWORD_FILE_PATH =
            Resources.getResource("certificate-authority/jks/broker.truststore.nopassword.jks").getPath();
    public final static String CLIENT_KEYSTORE_FILE_PATH =
            Resources.getResource("certificate-authority/jks/client.keystore.jks").getPath();
    public final static String CLIENT_TRUSTSTORE_FILE_PATH =
            Resources.getResource("certificate-authority/jks/client.truststore.jks").getPath();
    public final static String CLIENT_TRUSTSTORE_NO_PASSWORD_FILE_PATH =
            Resources.getResource("certificate-authority/jks/client.truststore.nopassword.jks").getPath();
```

... these resources files are under `tests` folder. So if you run a unit test inherited from `MockedPulsarServiceBaseTest` from IDEA, test will fail with:

```
Caused by: java.lang.IllegalArgumentException: resource certificate-authority/jks/broker.keystore.jks not found.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220)
	at com.google.common.io.Resources.getResource(Resources.java:198)
	at org.apache.pulsar.broker.auth.MockedPulsarServiceBaseTest.<clinit>(MockedPulsarServiceBaseTest.java:86)
	... 29 more
```

Currently, I must set those field as `null` to run a unit test locally. Thus, I have two questions here:

1. How can we run tests normally in the CI environment?
2. Can we improve testing settings to run unit test smoothly?

**Comment by tisonkun** [comment]
It seems we have a plugin to copy-resources before test-compile. So how can I integrate it with IDEA?

```xml
      <plugin>
        <artifactId>maven-resources-plugin</artifactId>
        <executions>
          <execution>
            <id>copy-resources</id>
            <phase>test-compile</phase>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <configuration>
              <outputDirectory>${project.build.testOutputDirectory}/certificate-authority</outputDirectory>
              <overwrite>true</overwrite>
              <resources>
                <resource>
                  <directory>${project.parent.basedir}/tests/certificate-authority</directory>
                  <filtering>false</filtering>
                </resource>
              </resources>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

**Comment by nodece** [comment]
Run `mvn clean install -Pcore-modules,-main -DskipTests -Dspotbugs.skip` for copy resource, then run your test.

**Comment by tisonkun** [comment]
@nodece Thank you! That works. I can run `mvn clean install -DskipTests` before debugging.

Not sure why IDEA doesn't execute that goal before running test, but it should not be a Pulsar issue :)
