### ISSUE TITLE
Flaky-test: TxnLogBufferedWriterTest.testMainProcess

### ISSUE THREAD

**Issue by shibd** [apache/pulsar#16723]
TxnLogBufferedWriterTest.testMainProcess is flaky. It fails sporadically.

[example failure](https://github.com/apache/pulsar/runs/7449540085?check_suite_focus=true)

```
  Error:  Tests run: 25, Failures: 2, Errors: 0, Skipped: 13, Time elapsed: 24.634 s <<< FAILURE! - in org.apache.pulsar.transaction.coordinator.impl.TxnLogBufferedWriterTest
  Error:  testMainProcess(org.apache.pulsar.transaction.coordinator.impl.TxnLogBufferedWriterTest)  Time elapsed: 4.032 s  <<< FAILURE!
  org.awaitility.core.ConditionTimeoutException: Condition with org.apache.pulsar.transaction.coordinator.impl.TxnLogBufferedWriterTest was not fulfilled within 4 seconds.
  	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
  	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
  	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
  	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
  	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:954)
  	at org.apache.pulsar.transaction.coordinator.impl.TxnLogBufferedWriterTest.testMainProcess(TxnLogBufferedWriterTest.java:235)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Technoboy-** [comment]
https://github.com/apache/pulsar/runs/7573727384?check_suite_focus=true

```
Error:  Tests run: 25, Failures: 2, Errors: 0, Skipped: 13, Time elapsed: 20.098 s <<< FAILURE! - in org.apache.pulsar.transaction.coordinator.impl.TxnLogBufferedWriterTest
  Error:  testMainProcess(org.apache.pulsar.transaction.coordinator.impl.TxnLogBufferedWriterTest)  Time elapsed: 0.116 s  <<< FAILURE!
  java.lang.AssertionError: expected [true] but found [false]
  	at org.testng.Assert.fail(Assert.java:99)
  	at org.testng.Assert.failNotEquals(Assert.java:1037)
  	at org.testng.Assert.assertTrue(Assert.java:45)
  	at org.testng.Assert.assertTrue(Assert.java:55)
  	at org.apache.pulsar.transaction.coordinator.impl.TxnLogBufferedWriterTest.testMainProcess(TxnLogBufferedWriterTest.java:250)
```

**Comment by RobertIndie** [comment]
Another but different failure:
https://github.com/apache/pulsar/runs/7644899001?check_suite_focus=true#step:10:5753

```
Error:  testMainProcess(org.apache.pulsar.transaction.coordinator.impl.TxnLogBufferedWriterTest)  Time elapsed: 4.021 s  <<< FAILURE!
  org.awaitility.core.ConditionTimeoutException: Condition with org.apache.pulsar.transaction.coordinator.impl.TxnLogBufferedWriterTest was not fulfilled within 4 seconds.
  	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
  	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
  	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
  	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
  	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:954)
  	at org.apache.pulsar.transaction.coordinator.impl.TxnLogBufferedWriterTest.testMainProcess(TxnLogBufferedWriterTest.java:235)
```

**Comment by poorbarcode** [comment]
assign to me
