### ISSUE TITLE
Flaky-test: PersistentSubscriptionMessageDispatchStreamingDispatcherThrottlingTest.testRelativeMessageRateLimitingThrottling

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#16770]
[example failure](https://github.com/apache/pulsar/runs/7492592847?check_suite_focus=true)

```
Error:  Tests run: 56, Failures: 10, Errors: 0, Skipped: 36, Time elapsed: 55.824 s <<< FAILURE! - in org.apache.pulsar.broker.service.persistent.PersistentSubscriptionMessageDispatchStreamingDispatcherThrottlingTest
  Error:  testRelativeMessageRateLimitingThrottling(org.apache.pulsar.broker.service.persistent.PersistentSubscriptionMessageDispatchStreamingDispatcherThrottlingTest)  Time elapsed: 4.925 s  <<< FAILURE!
  java.lang.AssertionError: Messages not received in time
  	at org.testng.Assert.fail(Assert.java:99)
  	at org.apache.pulsar.client.api.MessageDispatchThrottlingTest.testRelativeMessageRateLimitingThrottling(MessageDispatchThrottlingTest.java:1181)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

<!-- optionally provide the full stacktrace ->
<details>
<summary>Full exception stacktrace</summary>
<code><pre>
full exception stacktrace here
</pre></code>
</details>

**Comment by shibd** [comment]
+1 https://github.com/apache/pulsar/runs/7590561094?check_suite_focus=true

**Comment by codelipenghui** [comment]
A new one https://github.com/apache/pulsar/runs/7709485482?check_suite_focus=true

**Comment by codelipenghui** [comment]
Another one: https://github.com/apache/pulsar/runs/7859284770?check_suite_focus=true

**Comment by mattisonchao** [comment]
I think this PR probably fixes the problem https://github.com/apache/pulsar/pull/17143.

So, I chose this close this issue until this problem appears again.
