### ISSUE TITLE
Flaky-test: SimpleProducerConsumerTest.testSharedSamePriorityConsumer

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#16795]
[example failure](https://github.com/apache/pulsar/runs/7514010794?check_suite_focus=true)

```
Error:  Tests run: 117, Failures: 1, Errors: 0, Skipped: 27, Time elapsed: 575.841 s <<< FAILURE! - in org.apache.pulsar.client.api.SimpleProducerConsumerTest
  Error:  testSharedSamePriorityConsumer(org.apache.pulsar.client.api.SimpleProducerConsumerTest)  Time elapsed: 15.853 s  <<< FAILURE!
  java.lang.AssertionError: expected [500] but found [501]
  	at org.testng.Assert.fail(Assert.java:99)
  	at org.testng.Assert.failNotEquals(Assert.java:1037)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
  	at org.testng.Assert.assertEquals(Assert.java:122)
  	at org.testng.Assert.assertEquals(Assert.java:907)
  	at org.testng.Assert.assertEquals(Assert.java:917)
  	at org.apache.pulsar.client.api.SimpleProducerConsumerTest.testSharedSamePriorityConsumer(SimpleProducerConsumerTest.java:2450)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

<!-- optionally provide the full stacktrace ->
<details>
<summary>Full exception stacktrace</summary>
<code><pre>
full exception stacktrace here
</pre></code>
</details>

**Comment by codelipenghui** [comment]
Another one: https://github.com/apache/pulsar/runs/7856447331?check_suite_focus=true

**Comment by nicoloboschi** [comment]
Another one: https://github.com/apache/pulsar/runs/7884888194?check_suite_focus=true

**Comment by coderzc** [comment]
Another one: https://github.com/coderzc/pulsar/actions/runs/3096439259/jobs/5041008782

**Comment by shibd** [comment]
Another one: https://github.com/shibd/pulsar/actions/runs/3210516613/jobs/5248015431

**Comment by shibd** [comment]
@eolivelli @codelipenghui Can you help reopen it?

**Comment by tisonkun** [comment]
another instance: https://github.com/apache/pulsar/actions/runs/3328130218/jobs/5509161587

**Comment by codelipenghui** [comment]
@poorbarcode Please help check this one

**Comment by poorbarcode** [comment]
@codelipenghui 

> Please help check this one

OK
