### ISSUE TITLE
Flaky-test: PersistentDispatcherFailoverConsumerTest.testAddRemoveConsumer

### ISSUE THREAD

**Issue by Nicklee007** [apache/pulsar#16790]
[example failure](https://github.com/apache/pulsar/pull/16573/checks?check_run_id=7487144384)

```
org.apache.pulsar.broker.service.persistent.PersistentDispatcherFailoverConsumerStreamingDispatcherTest ► testAddRemoveConsumer
Failed test found in:
  TEST-org.apache.pulsar.broker.service.persistent.PersistentDispatcherFailoverConsumerStreamingDispatcherTest.xml
  TEST-org.apache.pulsar.broker.service.PersistentDispatcherFailoverConsumerTest.xml
Error:
        java.lang.AssertionError: expected object to not be null

java.lang.AssertionError: expected object to not be null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.assertNotNull(Assert.java:942)
at org.testng.Assert.assertNotNull(Assert.java:926)
at org.apache.pulsar.broker.service.PersistentDispatcherFailoverConsumerTest.testAddRemoveConsumer(PersistentDispatcherFailoverConsumerTest.java:431)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
```

<!-- optionally provide the full stacktrace ->
<details>
<summary>Full exception stacktrace</summary>
<code><pre>
full exception stacktrace here
</pre></code>
</details>

**Comment by shibd** [comment]
duplicate #14540
