### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/pulsar/shade/io/netty/buffer/PoolArena$1

### ISSUE THREAD

**Issue by oldwangmate** [apache/pulsar#16827]
When using pulsar client to send messages in flick, the following errors often appear. How can I end up

java.lang.NoClassDefFoundError: org/apache/pulsar/shade/io/netty/buffer/PoolArena$1
	at org.apache.pulsar.shade.io.netty.buffer.PoolArena.freeChunk(PoolArena.java:247)
	at org.apache.pulsar.shade.io.netty.buffer.PoolThreadCache$MemoryRegionCache.freeEntry(PoolThreadCache.java:430)
	at org.apache.pulsar.shade.io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:396)
	at org.apache.pulsar.shade.io.netty.buffer.PoolThreadCache$MemoryRegionCache.trim(PoolThreadCache.java:414)
	at org.apache.pulsar.shade.io.netty.buffer.PoolThreadCache.trim(PoolThreadCache.java:277)
	at org.apache.pulsar.shade.io.netty.buffer.PoolThreadCache.trim(PoolThreadCache.java:269)
	at org.apache.pulsar.shade.io.netty.buffer.PoolThreadCache.trim(PoolThreadCache.java:258)
	at org.apache.pulsar.shade.io.netty.buffer.PoolThreadCache.allocate(PoolThreadCache.java:170)
	at org.apache.pulsar.shade.io.netty.buffer.PoolThreadCache.allocateSmall(PoolThreadCache.java:151)
	at org.apache.pulsar.shade.io.netty.buffer.PoolArena.tcacheAllocateSmall(PoolArena.java:148)
	at org.apache.pulsar.shade.io.netty.buffer.PoolArena.allocate(PoolArena.java:134)
	at org.apache.pulsar.shade.io.netty.buffer.PoolArena.allocate(PoolArena.java:126)
	at org.apache.pulsar.shade.io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:395)
	at org.apache.pulsar.shade.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
	at org.apache.pulsar.shade.org.apache.bookkeeper.common.allocator.impl.ByteBufAllocatorImpl.newDirectBuffer(ByteBufAllocatorImpl.java:163)
	at org.apache.pulsar.shade.org.apache.bookkeeper.common.allocator.impl.ByteBufAllocatorImpl.newDirectBuffer(ByteBufAllocatorImpl.java:157)
	at org.apache.pulsar.shade.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
	at org.apache.pulsar.shade.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
	at org.apache.pulsar.shade.io.netty.channel.unix.PreferredDirectByteBufAllocator.ioBuffer(PreferredDirectByteBufAllocator.java:53)
	at org.apache.pulsar.shade.io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:120)
	at org.apache.pulsar.shade.io.netty.channel.epoll.EpollRecvByteAllocatorHandle.allocate(EpollRecvByteAllocatorHandle.java:75)
	at org.apache.pulsar.shade.io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:780)
	at org.apache.pulsar.shade.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at org.apache.pulsar.shade.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at org.apache.pulsar.shade.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.pulsar.shade.io.netty.buffer.PoolArena$1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$ChildFirstClassLoader.loadClass(FlinkUserCodeClassLoaders.java:129)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 28 more

**Comment by leizhiyuan** [comment]
It maybe an issue of flink classloader

```
Caused by: java.lang.ClassNotFoundException: org.apache.pulsar.shade.io.netty.buffer.PoolArena$1
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$ChildFirstClassLoader.loadClass(FlinkUserCodeClassLoaders.java:129)
```

if you can debug this , you can  print 

org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$ChildFirstClassLoader


```
.loadClass("org.apache.pulsar.shade.io.netty.buffer.PoolArena").getProtectionDomain().getCodeSource().getLocation()
```
to see which one is loaded by this classloader , and see the original jar file.

**Comment by tisonkun** [comment]
Closed as no response.

It's a Flink Pulsar connector issue. If it's still an issue, please report on https://issues.apache.org/jira/projects/FLINK/issues.
