### ISSUE TITLE
Flaky-test: PersistentStickyKeyDispatcherMultipleConsumersTest.testMessageRedelivery

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#16830]
[example failure](https://github.com/apache/pulsar/runs/7549605041?check_suite_focus=true)

```
Error:  Tests run: 9, Failures: 1, Errors: 0, Skipped: 7, Time elapsed: 20.618 s <<< FAILURE! - in org.apache.pulsar.broker.service.persistent.PersistentStickyKeyDispatcherMultipleConsumersTest
  Error:  testMessageRedelivery(org.apache.pulsar.broker.service.persistent.PersistentStickyKeyDispatcherMultipleConsumersTest)  Time elapsed: 7.488 s  <<< FAILURE!
  java.lang.StackOverflowError
  	at org.mockito.internal.util.MockUtil.getMockHandler(MockUtil.java:73)
  	at org.mockito.internal.util.MockUtil.getMockName(MockUtil.java:128)
  	at org.mockito.internal.stubbing.defaultanswers.ReturnsEmptyValues.answer(ReturnsEmptyValues.java:75)
  	at org.mockito.internal.stubbing.defaultanswers.GloballyConfiguredAnswer.answer(GloballyConfiguredAnswer.java:25)
  	at org.mockito.Answers.answer(Answers.java:99)
  	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:110)
  	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
  	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
  	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
  	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handle(MockMethodAdvice.java:151)
  	at org.apache.pulsar.broker.service.persistent.PersistentSubscription.toString(PersistentSubscription.java:481)
  	at org.apache.pulsar.broker.service.AbstractBaseDispatcher.lambda$filterEntriesForConsumer$1(AbstractBaseDispatcher.java:136)
  	at java.base/java.util.Optional.orElseGet(Optional.java:364)
  	at org.apache.pulsar.broker.service.AbstractBaseDispatcher.filterEntriesForConsumer(AbstractBaseDispatcher.java:136)
  	at org.apache.pulsar.broker.service.AbstractBaseDispatcher.filterEntriesForConsumer(AbstractBaseDispatcher.java:105)
  	at org.apache.pulsar.broker.service.persistent.PersistentStickyKeyDispatcherMultipleConsumers.trySendMessagesToConsumers(PersistentStickyKeyDispatcherMultipleConsumers.java:276)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.sendMessagesToConsumers(PersistentDispatcherMultipleConsumers.java:552)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readEntriesComplete(PersistentDispatcherMultipleConsumers.java:545)
  	at org.apache.pulsar.broker.service.persistent.PersistentStickyKeyDispatcherMultipleConsumersTest.lambda$testMessageRedelivery$8(PersistentStickyKeyDispatcherMultipleConsumersTest.java:404)
  	at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:42)
  	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
  	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
  	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
  	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
  	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handle(MockMethodAdvice.java:151)
  	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.asyncReadEntriesOrWait(ManagedCursorImpl.java:[841](https://github.com/apache/pulsar/runs/7549605041?check_suite_focus=true#step:10:842))
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readMoreEntries(PersistentDispatcherMultipleConsumers.java:305)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.sendMessagesToConsumers(PersistentDispatcherMultipleConsumers.java:556)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readEntriesComplete(PersistentDispatcherMultipleConsumers.java:545)
  	at org.apache.pulsar.broker.service.persistent.PersistentStickyKeyDispatcherMultipleConsumersTest.lambda$testMessageRedelivery$8(PersistentStickyKeyDispatcherMultipleConsumersTest.java:404)
  	at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:42)
  	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
  	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
  	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
  	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
  	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handle(MockMethodAdvice.java:151)
  	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.asyncReadEntriesOrWait(ManagedCursorImpl.java:841)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readMoreEntries(PersistentDispatcherMultipleConsumers.java:305)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.sendMessagesToConsumers(PersistentDispatcherMultipleConsumers.java:556)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readEntriesComplete(PersistentDispatcherMultipleConsumers.java:545)
  	at org.apache.pulsar.broker.service.persistent.PersistentStickyKeyDispatcherMultipleConsumersTest.lambda$testMessageRedelivery$8(PersistentStickyKeyDispatcherMultipleConsumersTest.java:404)
  	at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:42)
  	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
  	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
  	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
  	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
  	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handle(MockMethodAdvice.java:151)
  	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.asyncReadEntriesOrWait(ManagedCursorImpl.java:841)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readMoreEntries(PersistentDispatcherMultipleConsumers.java:305)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.sendMessagesToConsumers(PersistentDispatcherMultipleConsumers.java:556)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readEntriesComplete(PersistentDispatcherMultipleConsumers.java:545)
  	at org.apache.pulsar.broker.service.persistent.PersistentStickyKeyDispatcherMultipleConsumersTest.lambda$testMessageRedelivery$8(PersistentStickyKeyDispatcherMultipleConsumersTest.java:404)
  	at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:42)
  	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
  	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
  	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
  	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
  	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handle(MockMethodAdvice.java:151)
  	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.asyncReadEntriesOrWait(ManagedCursorImpl.java:841)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readMoreEntries(PersistentDispatcherMultipleConsumers.java:305)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.sendMessagesToConsumers(PersistentDispatcherMultipleConsumers.java:556)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readEntriesComplete(PersistentDispatcherMultipleConsumers.java:545)
  	at org.apache.pulsar.broker.service.persistent.PersistentStickyKeyDispatcherMultipleConsumersTest.lambda$testMessageRedelivery$8(PersistentStickyKeyDispatcherMultipleConsumersTest.java:404)
  	at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:42)
  	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
  	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
  	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
  	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
  	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handle(MockMethodAdvice.java:151)
  	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.asyncReadEntriesOrWait(ManagedCursorImpl.java:841)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readMoreEntries(PersistentDispatcherMultipleConsumers.java:305)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.sendMessagesToConsumers(PersistentDispatcherMultipleConsumers.java:556)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readEntriesComplete(PersistentDispatcherMultipleConsumers.java:545)
  	at org.apache.pulsar.broker.service.persistent.PersistentStickyKeyDispatcherMultipleConsumersTest.lambda$testMessageRedelivery$8(PersistentStickyKeyDispatcherMultipleConsumersTest.java:404)
  	at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:42)
  	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
  	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
  	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
  	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
  	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handle(MockMethodAdvice.java:151)
  	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.asyncReadEntriesOrWait(ManagedCursorImpl.java:841)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readMoreEntries(PersistentDispatcherMultipleConsumers.java:305)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.sendMessagesToConsumers(PersistentDispatcherMultipleConsumers.java:556)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readEntriesComplete(PersistentDispatcherMultipleConsumers.java:545)
  	at org.apache.pulsar.broker.service.persistent.PersistentStickyKeyDispatcherMultipleConsumersTest.lambda$testMessageRedelivery$8(PersistentStickyKeyDispatcherMultipleConsumersTest.java:404)
  	at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:42)
  	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
  	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
  	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
  	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
  	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handle(MockMethodAdvice.java:151)
  	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.asyncReadEntriesOrWait(ManagedCursorImpl.java:841)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readMoreEntries(PersistentDispatcherMultipleConsumers.java:305)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.sendMessagesToConsumers(PersistentDispatcherMultipleConsumers.java:556)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readEntriesComplete(PersistentDispatcherMultipleConsumers.java:545)
  	at
```

<!-- optionally provide the full stacktrace ->
<details>
<summary>Full exception stacktrace</summary>
<code><pre>
full exception stacktrace here
</pre></code>
</details>

**Comment by michaeljmarshall** [comment]
I have seen this same test fail multiple times today with the following error:

```
   Error:  testMessageRedelivery(org.apache.pulsar.broker.service.persistent.PersistentStickyKeyDispatcherMultipleConsumersTest)  Time elapsed: 0.038 s  <<< FAILURE!
  java.lang.AssertionError: lists don't have the same size expected [1] but found [6]
  	at org.testng.Assert.fail(Assert.java:99)
  	at org.testng.Assert.failNotEquals(Assert.java:1037)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
  	at org.testng.Assert.assertEquals(Assert.java:122)
  	at org.testng.Assert.assertEquals(Assert.java:907)
  	at org.testng.Assert.assertEquals(Assert.java:1089)
  	at org.testng.Assert.assertEquals(Assert.java:1065)
  	at org.apache.pulsar.broker.service.persistent.PersistentStickyKeyDispatcherMultipleConsumersTest.testMessageRedelivery(PersistentStickyKeyDispatcherMultipleConsumersTest.java:436)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by codelipenghui** [comment]
A new one: https://github.com/apache/pulsar/runs/7752040336?check_suite_focus=true

**Comment by Technoboy-** [comment]
A new one: https://github.com/apache/pulsar/runs/7761836102?check_suite_focus=true
