### ISSUE TITLE
Flaky-test: NegativeAcksTest.testNegativeAcksWithBatchAckEnabled

### ISSUE THREAD

**Issue by Technoboy-** [apache/pulsar#16864]
https://github.com/apache/pulsar/runs/7573727921?check_suite_focus=true

```
[INFO] Running org.apache.pulsar.client.impl.TopicPublishThrottlingInitTest
  Error:  Tests run: 69, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 109.161 s <<< FAILURE! - in org.apache.pulsar.client.impl.NegativeAcksTest
  Error:  testNegativeAcksWithBatchAckEnabled(org.apache.pulsar.client.impl.NegativeAcksTest)  Time elapsed: 11.79 s  <<< FAILURE!
  org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.client.impl.NegativeAcksTest.testNegativeAcksWithBatchAckEnabled() didn't finish within the time-out 10000
  	at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:371)
  	at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:282)
```

**Comment by RobertIndie** [comment]
Another one: https://github.com/apache/pulsar/runs/7644899225?check_suite_focus=true#step:10:1133

**Comment by poorbarcode** [comment]
assign to me

**Comment by michaeljmarshall** [comment]
Just saw this again: https://github.com/apache/pulsar/actions/runs/4209830786/jobs/7362172483

```
 Error:  Tests run: 77, Failures: 1, Errors: 0, Skipped: 5, Time elapsed: 166.776 s <<< FAILURE! - in org.apache.pulsar.client.impl.NegativeAcksTest
  Error:  testNegativeAcksWithBatchAckEnabled(org.apache.pulsar.client.impl.NegativeAcksTest)  Time elapsed: 10.03 s  <<< FAILURE!
  org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.client.impl.NegativeAcksTest.testNegativeAcksWithBatchAckEnabled() didn't finish within the time-out 10000
  	at java.base@17.0.6/jdk.internal.misc.Unsafe.park(Native Method)
  	at java.base@17.0.6/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
  	at java.base@17.0.6/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506)
  	at java.base@17.0.6/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
  	at java.base@17.0.6/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
  	at java.base@17.0.6/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623)
  	at app//org.apache.pulsar.common.util.collections.GrowableArrayBlockingQueue.take(GrowableArrayBlockingQueue.java:177)
  	at app//org.apache.pulsar.client.impl.ConsumerImpl.internalReceive(ConsumerImpl.java:445)
  	at app//org.apache.pulsar.client.impl.ConsumerBase.receive(ConsumerBase.java:253)
  	at app//org.apache.pulsar.client.impl.NegativeAcksTest.testNegativeAcksWithBatchAckEnabled(NegativeAcksTest.java:362)
  	at java.base@17.0.6/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base@17.0.6/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base@17.0.6/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base@17.0.6/java.lang.reflect.Method.invoke(Method.java:568)
  	at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base@17.0.6/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base@17.0.6/java.lang.Thread.run(Thread.java:833)
  ```

**Comment by shibd** [comment]
+1 https://github.com/shibd/pulsar/actions/runs/4299141063/jobs/7494199821
