### ISSUE TITLE
Flaky-test: NegativeAcksTest.testNegativeAcks

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#16949]
[example failure](https://github.com/apache/pulsar/runs/7644153917?check_suite_focus=true)

```
Error:  Tests run: 128, Failures: 4, Errors: 0, Skipped: 121, Time elapsed: 64.753 s <<< FAILURE! - in org.apache.pulsar.client.impl.NegativeAcksTest
  Error:  testNegativeAcks(org.apache.pulsar.client.impl.NegativeAcksTest)  Time elapsed: 0.869 s  <<< FAILURE!
  java.lang.AssertionError: expected [null] but found [org.apache.pulsar.client.impl.TopicMessageImpl@12da2698]
  	at org.testng.Assert.fail(Assert.java:99)
  	at org.testng.Assert.failNotSame(Assert.java:1033)
  	at org.testng.Assert.assertNull(Assert.java:965)
  	at org.testng.Assert.assertNull(Assert.java:953)
  	at org.apache.pulsar.client.impl.NegativeAcksTest.testNegativeAcks(NegativeAcksTest.java:160)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:[1136](https://github.com/apache/pulsar/runs/7644153917?check_suite_focus=true#step:10:1137))
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

<!-- optionally provide the full stacktrace ->
<details>
<summary>Full exception stacktrace</summary>
<code><pre>
full exception stacktrace here
</pre></code>
</details>

**Comment by coderzc** [comment]
assigned to me
