### ISSUE TITLE
[website] doc website crash with error "(0 , a.useNavbarMobileSidebar) is not a function"

### ISSUE THREAD

**Issue by AlphaWang** [apache/pulsar#16963]
**Describe the bug**
https://pulsar.apache.org/docs/ crashes while changing the width of web browser.

**To Reproduce**
1. Open 'https://pulsar.apache.org/docs/ ' with web browsers.
2. Drag the browser to make the width smaller.
3. Crashes with error: This page crashed. (0 , a.useNavbarMobileSidebar) is not a function
4. Browser console error:
```
main.b969a23a.js:2 TypeError: (0 , a.useNavbarMobileSidebar) is not a function
    at pe (1be78505.48e6e8c1.js:1:8638)
    at is (main.b969a23a.js:2:436075)
    at Gi (main.b969a23a.js:2:488156)
    at Lc (main.b969a23a.js:2:475429)
    at Pc (main.b969a23a.js:2:475357)
    at Cc (main.b969a23a.js:2:475220)
    at yc (main.b969a23a.js:2:472207)
    at main.b969a23a.js:2:421994
    at t.unstable_runWithPriority (main.b969a23a.js:2:537060)
    at Wa (main.b969a23a.js:2:421771)
li @ main.b969a23a.js:2
r.componentDidCatch.n.callback @ main.b969a23a.js:2
br @ main.b969a23a.js:2
gi @ main.b969a23a.js:2
Rc @ main.b969a23a.js:2
t.unstable_runWithPriority @ main.b969a23a.js:2
Wa @ main.b969a23a.js:2
Oc @ main.b969a23a.js:2
yc @ main.b969a23a.js:2
(anonymous) @ main.b969a23a.js:2
t.unstable_runWithPriority @ main.b969a23a.js:2
Wa @ main.b969a23a.js:2
Ya @ main.b969a23a.js:2
Ka @ main.b969a23a.js:2
mc @ main.b969a23a.js:2
Ns @ main.b969a23a.js:2
e @ main.b969a23a.js:2
main.b969a23a.js:2 Error: Unexpected: no Docusaurus route context found
    at i (main.b969a23a.js:2:256761)
    at f (main.b969a23a.js:2:257724)
    at is (main.b969a23a.js:2:436075)
    at Gi (main.b969a23a.js:2:488156)
    at Lc (main.b969a23a.js:2:475429)
    at Pc (main.b969a23a.js:2:475357)
    at Cc (main.b969a23a.js:2:475220)
    at yc (main.b969a23a.js:2:472207)
    at main.b969a23a.js:2:421994
    at t.unstable_runWithPriority (main.b969a23a.js:2:537060)
```

**Expected behavior**
The web page should be responsive.

**Screenshots**
![wider](https://user-images.githubusercontent.com/3367744/183229463-4c462779-6b43-45c3-8c48-48c12b49580d.png)
![narrow](https://user-images.githubusercontent.com/3367744/183229484-90228d15-8e20-4fe3-a6ee-70716ef2a55e.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome 103.0.5060.134, Safari 15.6 (17613.3.9.1.5)

**Comment by tisonkun** [comment]
Should be fixed now.
