### ISSUE TITLE
Flaky-test: BrokerServiceLookupTest.testModularLoadManagerSplitBundle

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#16980]
[example failure](https://github.com/apache/pulsar/runs/7709485357?check_suite_focus=true)

```
 Error:  Tests run: 25, Failures: 1, Errors: 0, Skipped: 23, Time elapsed: 68.05 s <<< FAILURE! - in org.apache.pulsar.client.api.BrokerServiceLookupTest
  Error:  testModularLoadManagerSplitBundle(org.apache.pulsar.client.api.BrokerServiceLookupTest)  Time elapsed: 17.259 s  <<< FAILURE!
  org.awaitility.core.ConditionTimeoutException: Condition with org.apache.pulsar.client.api.BrokerServiceLookupTest was not fulfilled within 10 seconds.
  	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
  	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
  	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
  	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
  	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:954)
  	at org.apache.pulsar.client.api.BrokerServiceLookupTest.testModularLoadManagerSplitBundle(BrokerServiceLookupTest.java:714)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

<!-- optionally provide the full stacktrace ->
<details>
<summary>Full exception stacktrace</summary>
<code><pre>
full exception stacktrace here
</pre></code>
</details>

**Comment by Demogorgon314** [comment]
I'll take look at this issue.

**Comment by Demogorgon314** [comment]
look like it can't reproduce in my local env.

<img width="670" alt="image" src="https://user-images.githubusercontent.com/22697570/183371883-832c21c1-9b29-4c30-ab50-5d090962b495.png">

**Comment by poorbarcode** [comment]
another one:

- https://github.com/poorbarcode/pulsar/actions/runs/3129690847/jobs/5079281833

**Comment by Shawyeok** [comment]
Same here:
- https://github.com/Shawyeok/pulsar/actions/runs/3213296801/jobs/5252927147
