### ISSUE TITLE
NPE when persistPositionToLedger 

### ISSUE THREAD

**Issue by Technoboy-** [apache/pulsar#17107]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Master branch

### Minimal reproduce step

ReplicatorTest#testReplicatorWithFailedAck

### What did you expect to see?

No NEP.

### What did you see instead?

```
org.apache.bookkeeper.mledger.ManagedLedgerException: java.lang.NullPointerException
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.persistPositionToLedger(ManagedCursorImpl.java:2814) ~[classes/:?]
	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.internalMarkDelete(ManagedCursorImpl.java:1968) ~[classes/:?]
	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.internalAsyncMarkDelete(ManagedCursorImpl.java:1911) ~[classes/:?]
	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.asyncDelete(ManagedCursorImpl.java:2226) ~[classes/:?]
	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.asyncDelete(ManagedCursorImpl.java:2030) ~[classes/:?]
	at org.apache.pulsar.broker.service.persistent.PersistentReplicator.lambda$deleteFailed$4(PersistentReplicator.java:645) ~[classes/:?]
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by coderzc** [comment]
It seems to be a flask test, I will fix it.

**Comment by tisonkun** [comment]
Closed.

See https://github.com/apache/pulsar/pull/20096 and https://github.com/apache/pulsar/pull/20096#discussion_r1169428743.
