### ISSUE TITLE
Flaky-test: ResourceGroupUsageAggregationTest.testProduceConsumeUsageOnRG

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#17120]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/runs/7856747228?check_suite_focus=true

### Exception stacktrace

```
Error:  Tests run: 4, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 7.957 s <<< FAILURE! - in org.apache.pulsar.broker.resourcegroup.ResourceGroupUsageAggregationTest
  Error:  testProduceConsumeUsageOnRG(org.apache.pulsar.broker.resourcegroup.ResourceGroupUsageAggregationTest)  Time elapsed: 0.194 s  <<< FAILURE!
  java.lang.AssertionError: expected [7] but found [10]
  	at org.testng.Assert.fail(Assert.java:99)
  	at org.testng.Assert.failNotEquals(Assert.java:1037)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
  	at org.testng.Assert.assertEquals(Assert.java:122)
  	at org.testng.Assert.assertEquals(Assert.java:797)
  	at org.testng.Assert.assertEquals(Assert.java:807)
  	at org.apache.pulsar.broker.resourcegroup.ResourceGroupUsageAggregationTest.verifyStats(ResourceGroupUsageAggregationTest.java:205)
  	at org.apache.pulsar.broker.resourcegroup.ResourceGroupUsageAggregationTest.testProduceConsumeUsageOnRG(ResourceGroupUsageAggregationTest.java:174)
  	at org.apache.pulsar.broker.resourcegroup.ResourceGroupUsageAggregationTest.testProduceConsumeUsageOnRG(ResourceGroupUsageAggregationTest.java:82)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by YczYanchengzhe** [comment]
I have no problem using the master code to run the test method locally, can you provide your reproduction steps?

**Comment by codelipenghui** [comment]
@YczYanchengzhe it's the flaky test, not able to reproduce stability. From the CI, you can get detailed logs.

**Comment by Technoboy-** [comment]
https://github.com/apache/pulsar/runs/8235931618?check_suite_focus=true
