### ISSUE TITLE
Flaky-test: ClientCnxRequestTimeoutQueueTest. setupClientCnx

### ISSUE THREAD

**Issue by Technoboy-** [apache/pulsar#17127]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/runs/7870157500?check_suite_focus=true

### Exception stacktrace

```
Error:  Tests run: 8, Failures: 1, Errors: 0, Skipped: 7, Time elapsed: 0.061 s <<< FAILURE! - in org.apache.pulsar.client.impl.ClientCnxRequestTimeoutQueueTest
  Error:  setupClientCnx(org.apache.pulsar.client.impl.ClientCnxRequestTimeoutQueueTest)  Time elapsed: 0.018 s  <<< FAILURE!
  java.lang.NoClassDefFoundError: Could not initialize class org.apache.pulsar.common.protocol.Commands
  	at org.apache.pulsar.client.impl.ClientCnx.<init>(ClientCnx.java:220)
  	at org.apache.pulsar.client.impl.ClientCnxRequestTimeoutQueueTest.setupClientCnx(ClientCnxRequestTimeoutQueueTest.java:63)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
  	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
  	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
  	at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:617)
```

```
Error:  Tests run: 6, Failures: 3, Errors: 0, Skipped: 3, Time elapsed: 0.341 s <<< FAILURE! - in org.apache.pulsar.client.impl.BinaryProtoLookupServiceTest
  Error:  maxLookupRedirectsTest1(org.apache.pulsar.client.impl.BinaryProtoLookupServiceTest)  Time elapsed: 0.003 s  <<< FAILURE!
  java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class org.apache.pulsar.common.protocol.Commands
  	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
  	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
  	at org.apache.pulsar.client.impl.BinaryProtoLookupServiceTest.maxLookupRedirectsTest1(BinaryProtoLookupServiceTest.java:83)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:70)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.pulsar.common.protocol.Commands
  	at org.apache.pulsar.client.impl.BinaryProtoLookupService.lambda$findBroker$2(BinaryProtoLookupService.java:117)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by poorbarcode** [comment]
and this one https://github.com/apache/pulsar/runs/7871237359?check_suite_focus=true

**Comment by codelipenghui** [comment]
The issue should be fixed by here https://github.com/apache/pulsar/pull/17049/files#diff-e6ac90fc5f2373a64dc1ecaa11a9c965f9a22f128cc4ca1265972e0dc4fef9c5R137
