### ISSUE TITLE
Flaky-tests: misc tests failing with java.lang.NoClassDefFoundError: Could not initialize class org.apache.pulsar.common.protocol.Commands

### ISSUE THREAD

**Issue by nicoloboschi** [apache/pulsar#17152]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/runs/7884887469?check_suite_focus=true

### Exception stacktrace

```
java.lang.NoClassDefFoundError: Could not initialize class org.apache.pulsar.common.protocol.Commands
  	at org.apache.pulsar.client.impl.ClientCnx.<init>(ClientCnx.java:220)
  	at org.apache.pulsar.client.impl.ClientCnxRequestTimeoutQueueTest.setupClientCnx(ClientCnxRequestTimeoutQueueTest.java:63)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by nicoloboschi** [comment]
This is probably caused by JDK ZGC issue https://github.com/openjdk/jdk17u-dev/pull/605
IIUC this will released in the next hotfix version of JDK 17

**Comment by codelipenghui** [comment]
@nicoloboschi I have changed [here](https://github.com/apache/pulsar/pull/17049/files#diff-e6ac90fc5f2373a64dc1ecaa11a9c965f9a22f128cc4ca1265972e0dc4fef9c5R137), the test get passed. It looks like related to Mockito and reuseForks. I'm not sure what exactly the problem is but disabled the reuse fork can help.

**Comment by mattisonchao** [comment]
I think the `reuseForks=false` can fix this problem.

Link: https://maven.apache.org/surefire/maven-surefire-plugin/examples/fork-options-and-parallel-execution.html

So, I closed the question and opened it when it reappeared.

**Comment by nicoloboschi** [comment]
I'm not sure we should close this issue. `reuseForks=false` may helps but it means we don't know the real source of the problem. 
@codelipenghui have you verified how much time the suite get now? is it relevant for the CI pipeline?

**Comment by codelipenghui** [comment]
@nicoloboschi Yes, we can keep it open until we find the root cause.
