### ISSUE TITLE
Flaky-test: PersistentSubscriptionMessageDispatchStreamingDispatcherThrottlingTest.testMultiLevelDispatch

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#17225]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/runs/7964439338?check_suite_focus=true

### Exception stacktrace

```
  Error:  Tests run: 41, Failures: 1, Errors: 0, Skipped: 13, Time elapsed: 137.054 s <<< FAILURE! - in org.apache.pulsar.broker.service.persistent.PersistentSubscriptionMessageDispatchStreamingDispatcherThrottlingTest
  Error:  testMultiLevelDispatch(org.apache.pulsar.broker.service.persistent.PersistentSubscriptionMessageDispatchStreamingDispatcherThrottlingTest)  Time elapsed: 7.89 s  <<< FAILURE!
  java.lang.AssertionError: expected [true] but found [false]
  	at org.testng.Assert.fail(Assert.java:99)
  	at org.testng.Assert.failNotEquals(Assert.java:1037)
  	at org.testng.Assert.assertTrue(Assert.java:45)
  	at org.testng.Assert.assertTrue(Assert.java:55)
  	at org.apache.pulsar.client.api.SubscriptionMessageDispatchThrottlingTest.testDispatchRate(SubscriptionMessageDispatchThrottlingTest.java:392)
  	at org.apache.pulsar.client.api.SubscriptionMessageDispatchThrottlingTest.testMultiLevelDispatch(SubscriptionMessageDispatchThrottlingTest.java:421)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
another failure: https://github.com/apache/pulsar/runs/7988259605?check_suite_focus=true#step:10:2074

**Comment by codelipenghui** [comment]
Another one: https://github.com/apache/pulsar/runs/8037496908?check_suite_focus=true

**Comment by mattisonchao** [comment]
The fix here: #17225

**Comment by poorbarcode** [comment]
failure:
- https://github.com/apache/pulsar/actions/runs/3053391609/jobs/4932388162
- https://github.com/apache/pulsar/actions/runs/3057952598/jobs/4933640170

**Comment by codelipenghui** [comment]
Another failure: https://github.com/apache/pulsar/actions/runs/3050809344/jobs/4918810532

**Comment by HQebupt** [comment]
@MarvinCai @congbobo184 @mattisonchao I found the failure it is due to dataProvider. I split the subscriptions into two separate data provider. It works. PTAL

**Comment by codelipenghui** [comment]
Close the issue for now since it is not active.
