### ISSUE TITLE
Flaky-test: KinesisSinkTest.testWrite is flaky: SdkClientException: Unable to parse date : 1.661894722507E9

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#17367]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://pipelines.actions.githubusercontent.com/serviceHosts/365d4aae-a024-4701-977d-a4807b036dda/_apis/pipelines/1/runs/639469/signedlogcontent/11?urlExpires=2022-08-31T06%3A26%3A00.6700367Z&urlSigningMethod=HMACV1&urlSignature=jIFWMl4F6R4OoLcQV%2BHhQ7Gn2MhUpP7G5dVbRav3TPk%3D

### Exception stacktrace

```
2022-08-30T21:25:26.6090813Z [ERROR] testWrite(org.apache.pulsar.io.kinesis.KinesisSinkTest)  Time elapsed: 2.513 s  <<< FAILURE!
2022-08-30T21:25:26.6092222Z java.util.concurrent.ExecutionException: software.amazon.awssdk.core.exception.SdkClientException: Unable to parse date : 1.661894722507E9
2022-08-30T21:25:26.6093640Z 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
2022-08-30T21:25:26.6241939Z 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
2022-08-30T21:25:26.6242581Z 	at org.apache.pulsar.io.kinesis.KinesisSinkTest.getStreamRecords(KinesisSinkTest.java:177)
2022-08-30T21:25:26.6243220Z 	at org.apache.pulsar.io.kinesis.KinesisSinkTest.testWrite(KinesisSinkTest.java:116)
2022-08-30T21:25:26.6243823Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-08-30T21:25:26.6244715Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2022-08-30T21:25:26.6245458Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-08-30T21:25:26.6246035Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2022-08-30T21:25:26.6246558Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
2022-08-30T21:25:26.6247174Z 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
2022-08-30T21:25:26.6247738Z 	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
2022-08-30T21:25:26.6248286Z 	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
2022-08-30T21:25:26.6248977Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-08-30T21:25:26.6249589Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2022-08-30T21:25:26.6250361Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2022-08-30T21:25:26.6250810Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2022-08-30T21:25:26.6251680Z Caused by: software.amazon.awssdk.core.exception.SdkClientException: Unable to parse date : 1.661894722507E9
2022-08-30T21:25:26.6252830Z 	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:97)
2022-08-30T21:25:26.6253606Z 	at software.amazon.awssdk.protocols.core.StringToInstant.lambda$safeParseDate$0(StringToInstant.java:77)
2022-08-30T21:25:26.6254705Z 	at software.amazon.awssdk.protocols.core.StringToInstant.convert(StringToInstant.java:56)
2022-08-30T21:25:26.6255729Z 	at software.amazon.awssdk.protocols.core.StringToInstant.convert(StringToInstant.java:32)
2022-08-30T21:25:26.6256590Z 	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller$SimpleTypeJsonUnmarshaller.unmarshall(JsonProtocolUnmarshaller.java:160)
2022-08-30T21:25:26.6258672Z 	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshallStructured(JsonProtocolUnmarshaller.java:210)
2022-08-30T21:25:26.6259680Z 	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshallStructured(JsonProtocolUnmarshaller.java:114)
2022-08-30T21:25:26.6260831Z 	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.lambda$unmarshallList$2(JsonProtocolUnmarshaller.java:143)
2022-08-30T21:25:26.6261725Z 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
2022-08-30T21:25:26.6262220Z 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
2022-08-30T21:25:26.6262921Z 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
2022-08-30T21:25:26.6263479Z 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
2022-08-30T21:25:26.6264010Z 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
2022-08-30T21:25:26.6264874Z 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2022-08-30T21:25:26.6265592Z 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
2022-08-30T21:25:26.6266602Z 	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshallList(JsonProtocolUnmarshaller.java:145)
2022-08-30T21:25:26.6267826Z 	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshallStructured(JsonProtocolUnmarshaller.java:210)
2022-08-30T21:25:26.6269665Z 	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshall(JsonProtocolUnmarshaller.java:197)
2022-08-30T21:25:26.6271031Z 	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshall(JsonProtocolUnmarshaller.java:168)
2022-08-30T21:25:26.6272066Z 	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.handle(JsonResponseHandler.java:79)
2022-08-30T21:25:26.6273182Z 	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.handle(JsonResponseHandler.java:36)
2022-08-30T21:25:26.6274201Z 	at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonResponseHandler.handle(AwsJsonResponseHandler.java:43)
2022-08-30T21:25:26.6275049Z 	at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$resultTransformationResponseHandler$5(BaseClientHandler.java:232)
2022-08-30T21:25:26.6275847Z 	at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler.lambda$prepare$0(AsyncResponseHandler.java:88)
2022-08-30T21:25:26.6276512Z 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
2022-08-30T21:25:26.6277190Z 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
2022-08-30T21:25:26.6277755Z 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
2022-08-30T21:25:26.6278425Z 	at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler$BaosSubscriber.onComplete(AsyncResponseHandler.java:129)
2022-08-30T21:25:26.6279160Z 	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.runAndLogError(ResponseHandler.java:171)
2022-08-30T21:25:26.6279869Z 	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.access$500(ResponseHandler.java:68)
2022-08-30T21:25:26.6280556Z 	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.onComplete(ResponseHandler.java:287)
2022-08-30T21:25:26.6281154Z 	at com.typesafe.netty.HandlerPublisher.complete(HandlerPublisher.java:408)
2022-08-30T21:25:26.6281682Z 	at com.typesafe.netty.HandlerPublisher.handlerRemoved(HandlerPublisher.java:395)
2022-08-30T21:25:26.6282317Z 	at io.netty.channel.AbstractChannelHandlerContext.callHandlerRemoved(AbstractChannelHandlerContext.java:946)
2022-08-30T21:25:26.6282997Z 	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:637)
2022-08-30T21:25:26.6283571Z 	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:477)
2022-08-30T21:25:26.6284112Z 	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:423)
2022-08-30T21:25:26.6284709Z 	at com.typesafe.netty.http.HttpStreamsHandler.removeHandlerIfActive(HttpStreamsHandler.java:328)
2022-08-30T21:25:26.6285358Z 	at com.typesafe.netty.http.HttpStreamsHandler.handleReadHttpContent(HttpStreamsHandler.java:189)
2022-08-30T21:25:26.6285971Z 	at com.typesafe.netty.http.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:165)
2022-08-30T21:25:26.6286584Z 	at com.typesafe.netty.http.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:148)
2022-08-30T21:25:26.6287254Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2022-08-30T21:25:26.6287960Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2022-08-30T21:25:26.6288661Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
2022-08-30T21:25:26.6289404Z 	at software.amazon.awssdk.http.nio.netty.internal.LastHttpContentHandler.channelRead(LastHttpContentHandler.java:43)
2022-08-30T21:25:26.6290157Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2022-08-30T21:25:26.6290857Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2022-08-30T21:25:26.6291546Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
2022-08-30T21:25:26.6292332Z 	at software.amazon.awssdk.http.nio.netty.internal.http2.Http2ToHttpInboundAdapter.onDataRead(Http2ToHttpInboundAdapter.java:66)
2022-08-30T21:25:26.6293211Z 	at software.amazon.awssdk.http.nio.netty.internal.http2.Http2ToHttpInboundAdapter.channelRead0(Http2ToHttpInboundAdapter.java:44)
2022-08-30T21:25:26.6294193Z 	at software.amazon.awssdk.http.nio.netty.internal.http2.Http2ToHttpInboundAdapter.channelRead0(Http2ToHttpInboundAdapter.java:38)
2022-08-30T21:25:26.6294975Z 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
2022-08-30T21:25:26.6295648Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2022-08-30T21:25:26.6296355Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2022-08-30T21:25:26.6297049Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
2022-08-30T21:25:26.6297666Z 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
2022-08-30T21:25:26.6298366Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2022-08-30T21:25:26.6299074Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2022-08-30T21:25:26.6299769Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
2022-08-30T21:25:26.6300406Z 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
2022-08-30T21:25:26.6301048Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2022-08-30T21:25:26.6301744Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2022-08-30T21:25:26.6302387Z 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
2022-08-30T21:25:26.6303033Z 	at io.netty.handler.codec.http2.AbstractHttp2StreamChannel$Http2ChannelUnsafe.doRead0(AbstractHttp2StreamChannel.java:901)
2022-08-30T21:25:26.6303749Z 	at io.netty.handler.codec.http2.AbstractHttp2StreamChannel$Http2ChannelUnsafe.doBeginRead(AbstractHttp2StreamChannel.java:816)
2022-08-30T21:25:26.6304647Z 	at io.netty.handler.codec.http2.AbstractHttp2StreamChannel$Http2ChannelUnsafe.beginRead(AbstractHttp2StreamChannel.java:785)
2022-08-30T21:25:26.6305258Z 	at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362)
2022-08-30T21:25:26.6305836Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:686)
2022-08-30T21:25:26.6306444Z 	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:671)
2022-08-30T21:25:26.6307090Z 	at software.amazon.awssdk.http.nio.netty.internal.http2.FlushOnReadHandler.read(FlushOnReadHandler.java:40)
2022-08-30T21:25:26.6307754Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:686)
2022-08-30T21:25:26.6308343Z 	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:671)
2022-08-30T21:25:26.6308892Z 	at com.typesafe.netty.HandlerPublisher.requestDemand(HandlerPublisher.java:86)
2022-08-30T21:25:26.6309409Z 	at com.typesafe.netty.http.HttpStreamsHandler$1.requestDemand(HttpStreamsHandler.java:157)
2022-08-30T21:25:26.6311121Z 	at com.typesafe.netty.HandlerPublisher.flushBuffer(HandlerPublisher.java:311)
2022-08-30T21:25:26.6311721Z 	at com.typesafe.netty.HandlerPublisher.receivedDemand(HandlerPublisher.java:258)
2022-08-30T21:25:26.6312274Z 	at com.typesafe.netty.HandlerPublisher.access$200(HandlerPublisher.java:41)
2022-08-30T21:25:26.6312801Z 	at com.typesafe.netty.HandlerPublisher$ChannelSubscription$1.run(HandlerPublisher.java:452)
2022-08-30T21:25:26.6313398Z 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
2022-08-30T21:25:26.6314043Z 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
2022-08-30T21:25:26.6314727Z 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
2022-08-30T21:25:26.6315588Z 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
2022-08-30T21:25:26.6316270Z 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
2022-08-30T21:25:26.6317149Z 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2022-08-30T21:25:26.6317463Z 	... 1 more
2022-08-30T21:25:26.6317781Z Caused by: java.lang.NumberFormatException: For input string: "1.661894722507E9"
2022-08-30T21:25:26.6318264Z 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
2022-08-30T21:25:26.6318707Z 	at java.base/java.lang.Long.parseLong(Long.java:711)
2022-08-30T21:25:26.6319049Z 	at java.base/java.lang.Long.parseLong(Long.java:836)
2022-08-30T21:25:26.6319652Z 	at software.amazon.awssdk.utils.DateUtils.parseUnixTimestampMillisInstant(DateUtils.java:146)
2022-08-30T21:25:26.6320268Z 	at software.amazon.awssdk.protocols.core.StringToInstant.lambda$safeParseDate$0(StringToInstant.java:72)
2022-08-30T21:25:26.6320676Z 	... 83 more

```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by nicoloboschi** [comment]
Fixed with https://github.com/apache/pulsar/pull/17357
