### ISSUE TITLE
Flaky-test: TopicReaderTest.testMultiReaderIsAbleToSeekWithTimeOnMiddleOfTopic

### ISSUE THREAD

**Issue by RobertIndie** [apache/pulsar#17407]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/runs/8127487718?check_suite_focus=true#step:10:2418

### Exception stacktrace

```
Error:  Tests run: 87, Failures: 1, Errors: 0, Skipped: 72, Time elapsed: 14.693 s <<< FAILURE! - in org.apache.pulsar.client.api.TopicReaderTest
  Error:  testMultiReaderIsAbleToSeekWithTimeOnMiddleOfTopic(org.apache.pulsar.client.api.TopicReaderTest)  Time elapsed: 0.326 s  <<< FAILURE!
  java.lang.AssertionError: Received duplicate message msg num 5 expected [true] but found [false]
  	at org.testng.Assert.fail(Assert.java:99)
  	at org.testng.Assert.failNotEquals(Assert.java:1037)
  	at org.testng.Assert.assertTrue(Assert.java:45)
  	at org.apache.pulsar.client.api.TopicReaderTest.testMultiReaderIsAbleToSeekWithTimeOnMiddleOfTopic(TopicReaderTest.java:1404)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```
### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by poorbarcode** [comment]
another one:
- https://github.com/poorbarcode/pulsar/actions/runs/3145169735/jobs/5112123882

**Comment by codelipenghui** [comment]
Looks like the issue doesn't happen again. Close it first.

**Comment by poorbarcode** [comment]
another one: https://github.com/apache/pulsar/actions/runs/3349222804/jobs/5549024802
