### ISSUE TITLE
[Bug] cpp client coredump

### ISSUE THREAD

**Issue by zhcn** [apache/pulsar#17674]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

gcc version 7.3.1 20180303 (Red Hat 7.3.1-6) (GCC)
pulsar cpp client version 2.11

### Minimal reproduce step

It use with my internel packages, so it may not easy to reproduce

### What did you expect to see?

send pulsar message  successfully

### What did you see instead?

```
2022-09-15 20:09:37.496 INFO  [140083160143616] ClientConnection:375 | [xxx -> xxx] Connected to broker
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/message_lite.cc:439] pulsar.proto.BaseCommand exceeded maximum protobuf size of 2GB: 140082774282145
Segmentation fault (core dumped)
```
```
Program terminated with signal 11, Segmentation fault.
#0  0x00007f67b8875916 in __dynamic_cast () from /lib64/libstdc++.so.6
Missing separate debuginfos, use: debuginfo-install apache-pulsar-client-2.11.0-1.x86_64 glibc-2.17-157.tl2.2.x86_64 libgcc-7.3.1-6.tl2.x86_64 libstdc++-7.3.1-6.tl2.x86_64
(gdb) bt
#0  0x00007f67b8875916 in __dynamic_cast () from /lib64/libstdc++.so.6
#1  0x00007f67b7b670d3 in pulsar::proto::BaseCommand const* google::protobuf::internal::down_cast<pulsar::proto::BaseCommand const*, google::protobuf::MessageLite const>(google::protobuf::MessageLite const*) () from /usr/lib/libpulsar.so.2.11.0-SNAPSHOT
#2  0x00007f67b7b623a4 in pulsar::proto::BaseCommand const* google::protobuf::internal::DownCast<pulsar::proto::BaseCommand const*, google::protobuf::MessageLite const>(google::protobuf::MessageLite const*) () from /usr/lib/libpulsar.so.2.11.0-SNAPSHOT
#3  0x00007f67b7b40f10 in pulsar::proto::BaseCommand::CheckTypeAndMergeFrom(google::protobuf::MessageLite const&) ()
   from /usr/lib/libpulsar.so.2.11.0-SNAPSHOT
#4  0x0000000000ab4351 in google::protobuf::MessageLite::ParseFrom<(google::protobuf::MessageLite::ParseFlags)1, google::protobuf::StringPiece> (this=0x2df2518, input=...) at external/com_google_protobuf/src/google/protobuf/message_lite.h:512
#5  0x0000000000ab2a3d in google::protobuf::MessageLite::ParseFromArray (this=0x2df2518, data=0x2df33a0, size=26)
    at external/com_google_protobuf/src/google/protobuf/message_lite.cc:308
#6  0x00007f67b78f7d20 in pulsar::ClientConnection::processIncomingBuffer() () from /usr/lib/libpulsar.so.2.11.0-SNAPSHOT
#7  0x00007f67b78f7895 in pulsar::ClientConnection::handleRead(boost::system::error_code const&, unsigned long, unsigned int) ()
   from /usr/lib/libpulsar.so.2.11.0-SNAPSHOT
#8  0x00007f67b79525b0 in void std::__invoke_impl<void, void (pulsar::ClientConnection::*&)(boost::system::error_code const&, unsigned long, unsigned int), std::shared_ptr<pulsar::ClientConnection>&, boost::system::error_code&, unsigned long&, unsigned int&>(std::__invoke_memfun_deref, void (pulsar::ClientConnection::*&)(boost::system::error_code const&, unsigned long, unsigned int), std::shared_ptr<pulsar::ClientConnection>&, boost::system::error_code&, unsigned long&, unsigned int&) () from /usr/lib/libpulsar.so.2.11.0-SNAPSHOT
#9  0x00007f67b794f6c5 in std::__invoke_result<void (pulsar::ClientConnection::*&)(boost::system::error_code const&, unsigned long, unsigned int), std::shared_ptr<pulsar::ClientConnection>&, boost::system::error_code&, unsigned long&, unsigned int&>::type std::__invoke<void (pulsar::ClientConnection::*&)(boost::system::error_code const&, unsigned long, unsigned int), std::shared_ptr<pulsar::ClientConnection>&, boost::system::error_code&, unsigned long&, unsigned int&>(void (pulsar::ClientConnection::*&)(boost::system::error_code const&, unsigned long, unsigned int), std::shared_ptr<pulsar::ClientConnection>&, boost::system::error_code&, unsigned long&, unsigned int&) ()
   from /usr/lib/libpulsar.so.2.11.0-SNAPSHOT
#10 0x00007f67b794c794 in void std::_Bind<void (pulsar::ClientConnection::*(std::shared_ptr<pulsar::ClientConnection>, std::_Placeholder<1>, std::_Placeholder<2>, unsigned int))(boost::system::error_code const&, unsigned long, unsigned int)>::__call<void, boost::system::error_code&, unsigned long&, 0ul, 1ul, 2ul, 3ul>(std::tuple<boost::system::error_code&, unsigned long&>&&, std::_Index_tuple<0ul, 1ul, 2ul, 3ul>) () from /usr/lib/libpulsar.so.2.11.0-SNAPSHOT
#11 0x00007f67b7949854 in void std::_Bind<void (pulsar::ClientConnection::*(std::shared_ptr<pulsar::ClientConnection>, std::_Placeholder<1>, std::_Placeholder<2>, unsigned int))(boost::system::error_code const&, unsigned long, unsigned int)>::operator()<boost::system::error_code&, unsigned long&, void>(boost::system::error_code&, unsigned long&) () from /usr/lib/libpulsar.so.2.11.0-SNAPSHOT
#12 0x00007f67b794711d in void AllocHandler<std::_Bind<void (pulsar::ClientConnection::*(std::shared_ptr<pulsar::ClientConnection>, std::_Placeholder<1>, std::_Placeholder<2>, unsigned int))(boost::system::error_code const&, unsigned long, unsigned int)> >::operator()<boost::system::error_code, unsigned long>(boost::system::error_code, unsigned long) () from /usr/lib/libpulsar.so.2.11.0-SNAPSHOT
#13 0x00007f67b7944960 in boost::asio::detail::binder2<AllocHandler<std::_Bind<void (pulsar::ClientConnection::*(std::shared_ptr<pulsar::ClientConnection>, std::_Placeholder<1>, std::_Placeholder<2>, unsigned int))(boost::system::error_code const&, unsigned long, unsigned int)> >, boost::system::error_code, unsigned long>::operator()() () from /usr/lib/libpulsar.so.2.11.0-SNAPSHOT
#14 0x00007f67b7941f43 in void boost::asio::asio_handler_invoke<boost::asio::detail::binder2<AllocHandler<std::_Bind<void (pulsar::ClientConnection::*(std::shared_ptr<pulsar::ClientConnection>, std::_Placeholder<1>, std::_Placeholder<2>, unsigned int))(boost::system::error_code const&, unsigned long, unsigned int)> >, boost::system::error_code, unsigned long> >(boost::asio::detail::binder2<AllocHandler<std::_Bind<void (pulsar::ClientConnection::*(std::shared_ptr<pulsar::ClientConnection>, std::_Placeholder<1>, std::_Placeholder<2>, unsigned int))(boost::system::error_code const&, unsigned long, unsigned int)> >, boost::system::error_code, unsigned long>&, ...) ()
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zhcn** [comment]
I found the reason: pulsar client is compiled with protobuf 3.20.0 , other package in my program use protobuf 3.8.0. I recompiled pulsar client with protobuf 3.8.0, and it works
