### ISSUE TITLE
unload bundle causes topic fence, OpAddEntry NPE appears in addComplete.

### ISSUE THREAD

**Issue by lightzhao** [apache/pulsar#17737]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

2.8.1

### Minimal reproduce step

1. unload bundle causes topic fence
2. OpAddEntry NPE appears in addComplete.
3. add producer/consumer fail

### What did you expect to see?

When the bundle is unloaded, the producer/consumer can be added normally, and the topic status is available

### What did you see instead?

```
14:48:29.599 [BookKeeperClientWorker-OrderedExecutor-0-0] ERROR org.apache.bookkeeper.client.PendingAddOp - Write of ledger entry to quor
um failed: L3908720 E912517
14:48:29.599 [BookKeeperClientWorker-OrderedExecutor-0-0] ERROR org.apache.bookkeeper.client.PendingAddOp - Write of ledger entry to quor
um failed: L3908720 E912518
14:48:29.599 [BookKeeperClientWorker-OrderedExecutor-0-0] ERROR org.apache.bookkeeper.client.PendingAddOp - Write of ledger entry to quor
um failed: L3908720 E912519
14:48:29.599 [BookKeeperClientWorker-OrderedExecutor-0-0] ERROR org.apache.bookkeeper.common.util.SafeRunnable - Unexpected throwable cau
ght
java.lang.NullPointerException: null
        at org.apache.bookkeeper.mledger.impl.OpAddEntry.addComplete(OpAddEntry.java:153) ~[managed-ledger.jar:2.8.1]
        at org.apache.bookkeeper.client.AsyncCallback$AddCallback.addCompleteWithLatency(AsyncCallback.java:92) ~[org.apache.bookkeeper-b
ookkeeper-server-4.14.2.jar:4.14.2]
        at org.apache.bookkeeper.client.PendingAddOp.submitCallback(PendingAddOp.java:431) ~[org.apache.bookkeeper-bookkeeper-server-4.14
.2.jar:4.14.2]
        at org.apache.bookkeeper.client.LedgerHandle.errorOutPendingAdds(LedgerHandle.java:1799) ~[org.apache.bookkeeper-bookkeeper-serve
r-4.14.2.jar:4.14.2]
        at org.apache.bookkeeper.client.LedgerHandle$5.safeRun(LedgerHandle.java:574) ~[org.apache.bookkeeper-bookkeeper-server-4.14.2.ja
r:4.14.2]
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [org.apache.bookkeeper-bookkeeper-common-4.14.2.jar:4
.14.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.66.Final.jar:
4.1.66.Final]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]


14:48:29.698 [ForkJoinPool.commonPool-worker-16] ERROR org.apache.pulsar.broker.service.ServerCnx - [/10.176.139.107:12898] Failed to add producer to topic persistent:********: producerId=4, org.apache.pulsar.broker.service.BrokerServiceException$TopicFencedException: Topic is temporarily unavailable
```

<img width="1303" alt="image" src="https://user-images.githubusercontent.com/40714172/191214881-db80948b-bbe7-48a8-af35-d9a5a474d515.png">

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by lhotari** [comment]
Possibly related to #5284
