### ISSUE TITLE
Flaky-test: PersistentSubscriptionTest.testCanAcknowledgeAndCommitForTransaction

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#17755]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/3087399137/jobs/4996282487

### Exception stacktrace

Error:  Tests run: 5, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 2.162 s <<< FAILURE! - in org.apache.pulsar.broker.service.persistent.PersistentSubscriptionTest
  Error:  testCanAcknowledgeAndCommitForTransaction(org.apache.pulsar.broker.service.persistent.PersistentSubscriptionTest)  Time elapsed: 0.019 s  <<< FAILURE!
  org.mockito.exceptions.misusing.UnfinishedStubbingException: 
  
  Unfinished stubbing detected here:
  -> at org.apache.pulsar.broker.service.persistent.PersistentSubscriptionTest.testCanAcknowledgeAndCommitForTransaction(PersistentSubscriptionTest.java:258)
  
  E.g. thenReturn() may be missing.
  Examples of correct stubbing:
      when(mock.isOk()).thenReturn(true);
      when(mock.isOk()).thenThrow(exception);
      doThrow(exception).when(mock).someVoidMethod();
  Hints:
   1. missing thenReturn()
   2. you are trying to stub a final method, which is not supported
   3. you are stubbing the behaviour of another mock inside before 'thenReturn' instruction is completed
  
  	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.asyncMarkDelete(ManagedCursorImpl.java:1842)
  	at org.apache.pulsar.broker.service.persistent.PersistentSubscriptionTest.testCanAcknowledgeAndCommitForTransaction(PersistentSubscriptionTest.java:263)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:[833](https://github.com/apache/pulsar/actions/runs/3087399137/jobs/4996282487#step:10:834))

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by poorbarcode** [comment]
assign to me

**Comment by congbobo184** [comment]
https://github.com/apache/pulsar/pull/17845 has fixed it, so closed this PR
