### ISSUE TITLE
[Site Error] https://pulsar.apache.org/admin-rest-api/ page crashes

### ISSUE THREAD

**Issue by dave2wave** [apache/pulsar#17896]
The page fails with
<img width="604" alt="Screen Shot 2022-08-30 at 8 49 04 AM" src="https://user-images.githubusercontent.com/29803617/187482644-1981ebaa-a4cb-4235-b0f2-09fcc887bfe2.png">

```
Refused to apply style from 'https://fonts.googleapis.com/css2?family=Red+Hat+Display:wght@300;400;600,900&display=swap' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
main.4cc898d0.js:2 TypeError: Cannot read properties of undefined (reading '0')
    at u (35a86300.52ee81c8.js:1:19592)
    at 35a86300.52ee81c8.js:1:17105
    at n.componentDidMount (35a86300.52ee81c8.js:1:17215)
    at gi (main.4cc898d0.js:2:457539)
    at Rc (main.4cc898d0.js:2:474345)
    at t.unstable_runWithPriority (main.4cc898d0.js:2:531823)
    at Wa (main.4cc898d0.js:2:416534)
    at Oc (main.4cc898d0.js:2:471084)
    at xc (main.4cc898d0.js:2:467195)
    at mc (main.4cc898d0.js:2:464326)
li @ main.4cc898d0.js:2
main.4cc898d0.js:2 Error: Unexpected: no Docusaurus route context found
    at i (main.4cc898d0.js:2:256415)
    at f (main.4cc898d0.js:2:257378)
    at is (main.4cc898d0.js:2:430838)
    at Gi (main.4cc898d0.js:2:482919)
    at Lc (main.4cc898d0.js:2:470192)
    at Tc (main.4cc898d0.js:2:470120)
    at Cc (main.4cc898d0.js:2:469983)
    at xc (main.4cc898d0.js:2:466970)
    at main.4cc898d0.js:2:416757
    at t.unstable_runWithPriority (main.4cc898d0.js:2:531823)
li @ main.4cc898d0.js:2
main.4cc898d0.js:2 TypeError: Cannot read properties of undefined (reading '0')
    at u (35a86300.52ee81c8.js:1:19592)
    at 35a86300.52ee81c8.js:1:17105
    at n.componentDidMount (35a86300.52ee81c8.js:1:17215)
    at gi (main.4cc898d0.js:2:457539)
    at Rc (main.4cc898d0.js:2:474345)
    at t.unstable_runWithPriority (main.4cc898d0.js:2:531823)
    at Wa (main.4cc898d0.js:2:416534)
    at Oc (main.4cc898d0.js:2:471084)
    at xc (main.4cc898d0.js:2:467195)
    at main.4cc898d0.js:2:416757
li @ main.4cc898d0.js:2
main.4cc898d0.js:2 Error: Unexpected: no Docusaurus route context found
    at i (main.4cc898d0.js:2:256415)
    at f (main.4cc898d0.js:2:257378)
    at is (main.4cc898d0.js:2:430838)
    at Gi (main.4cc898d0.js:2:482919)
    at Lc (main.4cc898d0.js:2:470192)
    at Tc (main.4cc898d0.js:2:470120)
    at Cc (main.4cc898d0.js:2:469983)
    at xc (main.4cc898d0.js:2:466970)
    at main.4cc898d0.js:2:416757
    at t.unstable_runWithPriority (main.4cc898d0.js:2:531823)
li @ main.4cc898d0.js:2
pulsar.apache.org/:1 Refused to apply style from 'https://fonts.googleapis.com/css2?family=Red+Hat+Display:wght@300;400;600,900&display=swap' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

**Comment by Anonymitaet** [comment]
I'll close this issue since it has been transferred to `pulsar`.
For more context, see https://github.com/apache/pulsar-site/pull/236

**Comment by tisonkun** [comment]
Closed. It seems an issue with networking. I try the page and it works well.
