### ISSUE TITLE
Flaky-test: PrometheusMetricsTest.testDuplicateMetricTypeDefinitions

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar#17921]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/tisonkun/pulsar/actions/runs/3179774186/jobs/5182608943

### Exception stacktrace

```
  java.lang.AssertionError: Metric pulsar_txn_pending_ack_store_bufferedwriter_batch_record_count_count does not have a corresponding summary type definition
  	at org.testng.Assert.fail(Assert.java:99)
  	at org.apache.pulsar.broker.stats.PrometheusMetricsTest.testDuplicateMetricTypeDefinitions(PrometheusMetricsTest.java:842)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
another instance https://github.com/apache/pulsar/actions/runs/3186170155/jobs/5198019258

**Comment by poorbarcode** [comment]
This error was caused by the non-standard definition of the metrics name `pulsar_txn_pending_ack_store_bufferedwriter_batch_record_count_count `, and I submitted a PR #17905 to solve this problem before

**Comment by tisonkun** [comment]
@poorbarcode @nicoloboschi this seems another race condition for fixing bugs.

And #17905 seems fixed the root cause so that we should reopen this issue?
