### ISSUE TITLE
[Bug][Client] Direct Buffer memory leak on Pulsar Admin API in Java

### ISSUE THREAD

**Issue by syhily** [apache/pulsar#17989]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

pulsar-client-all: 2.10.1
pulsar: 2.10.0
flink-connector-pulsar: 1.17-SNAPSHOT

### Minimal reproduce step

Change the Java from 8 to 11 in flink application which uses `pulsar-client-all`. The console shows that the direct buffer memory leaks in Admin API querying.

### What did you expect to see?

No OOM exception.

### What did you see instead?

![image](https://user-images.githubusercontent.com/1761698/194965747-2f15c385-a481-4087-914f-5d142a9abbc0.png)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by michaeljmarshall** [comment]
@syhily - thank you for opening an issue. Are you able to post the whole stack trace as text instead of as a screenshot? This will help for debugging. Thanks.

**Comment by syhily** [comment]
```log
Caused by: org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector$RetryException: Could not complete the operation. Number of retries has been exhausted. Failed reason: lava.lang. OutOfMemoryError: Direct buffer memors
at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$retryOperation$4(AsyncHttpConnector.java:265)~[?:?]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)~[?:?1
at java.util.concurrent.CompletableFuture$UniwhenComplete.tryFire(CompletableFuture.java:837)~?:?1 at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)~[?:?]
at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)~[?:?]
at org.apache.pulsar. shade.org. asynchttpclient. netty. NettyResponseFuture. abort (NettyResponseFuture. java: 273) - [?:?] at org. apache.pulsar. shade. org.asynchttpolient. netty. request .WriteListener.abortOnThrowable (WriteListener. java:50) ~ [?:?] at org.apache.pulsar.shade.org.asynchttpclient.netty.request.WriteListener.operationComplete(WriteListener.java:61)~[?:?] at org. apache.pulsar.shade.org.asynchttpclient.netty.request.WriteCompleteListener.operationComplete(WriteCompleteListener.java:28)-[2:?]
at org.apache.pulsar.shade.org.asynchttpclient.netty.request.WriteCompleteListener.operationComplete(WriteCompleteListener.java:20)~[2:2]
at org. apache.pulsar. shade. io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)~[2:31
at org. apache.pulsar.shade.jo.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)-[?:?]
at org. apache.pulsar.shade.io.netty.util.concurrent. DefaultPromise.notifyListeners (DefaultPromise. java: 491) - [2:?] at org.apache.pulsar.shade.io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184)~[?:?] at org.apache.pulsar.shade.jo.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)~[?:?1 at org.apache.pulsar. shade. io. netty.channel. DefaultChannelPromise.addListener (DefaultChannelPromise. java: 30) - [2:?] at org.apache.pulsar.shade.org.asynchttpclient.netty.request.NettyRequestSender.writeRequest(NettyRequestSender.java:421)-[?:?] at org.apache.pulsar. shade.org. asynchttpclient. netty .channel.NettyConnectListener.writeRequest (NettyConnectListener. java: 80) - [?:?1 at org.apache.pulsar.shade.org.asynchttpclient.netty.channel.NettyConnectListener.onSuccess(NettyConnectListener.java:156)~[?:?] at org.apache.pulsar.shade.org.asynchttpclient. netty.channel. NettyChannelConnector$1.onSuccess (NettyChannelConnector. java: 92) - [?:?] at org. apache.pulsar. shade. org.asynchttpclient. netty. SimpleChannelFutureListener.operationComplete (SimpleChannelFutureListener. java: 26) ~ [?:?] at org.apache.pulsar.shade.org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)~[?:?]
org.apache.pulsar.shade.jo.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)~[?:?]
at org.apache.pulsar.shade.jo.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)~[?:?1 at org.apache.pulsar.shade.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)-[?:?]
at org.apache.pulsar.shade.jo.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)~[?:?]
at org.apache.pulsar.shade.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)~[?:?]
at org.apache.pulsar.shade.io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)-[?:?] at org.apache.pulsar.shade.io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)~[?:?]
at org.apache.pulsar. shade. io.netty. channel.DefaultChannelPromise.trySuccess (DefaultChannelPromise. java: 84) ~ [?:?] at org.apache.pulsar.shade.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:300)-[?:?]
at org.apache.pulsar.shade.jo.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnectAbstractNioChannel.java:335)~[?:?1 at org. apache.pulsar. shade. jo.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)~[?:?]
at org.apache.pulsar.shade.lo.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)~[?:?]
at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)~[?:?]
at org.apache.pulsar.shade.jo.netty. channel.nio.NioEventLoop.run (NioEventLoop. java: 496) ~ [?:?1
at org.apache.pulsar.shade.jo.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)~?:?1 at org.apache.pulsar.shade.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)~[?:?]
at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)~г?:?1 at java.lang. Thread.run (Thread. java: 829) ~ [?:?]
Caused by:
org.apache.pulsar.shade. io.netty. handler.codec. EncoderException: java.lang.OutOfMemoryError: Direct buffer memory at org.apache.pulsar.shade. lo. netty. handler. codec. MessageToMessageEncoder.write (MessageToMessageEncoder. java: 104) - [?: ?] at org. apache.pulsar. shade. io. netty.channel.CombinedChannelDuplexHandler.write(CombinedChannelDuplexHandler.java:346) ~ [?:?] at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)~[?:?] at org.apache.pulsar.shade.jo.netty.channel.AbstractChannelHandlerContext.invokewrite(AbstractChannelHandlerContext.java:709)~[?:?1
org. apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)~|?:?1 at org.apache.pulsar. shade. io.netty. channel.AbstractChannelHandlerContext.write (AbstractChannelHandlerContext. java: 702) ~ [?:?]
at org.apache.pulsar.shade.io.netty. handler.stream. ChunkedWriteHandler.doFlush (ChunkedwriteHandler. java: 302) ~ [?:?]
```
