### ISSUE TITLE
[Bug] Cannot publish chunking message in the standalone mode

### ISSUE THREAD

**Issue by RobertIndie** [apache/pulsar#17984]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

master branch

### Minimal reproduce step

* Start the standalone with the default configuration. (Using rocksdb as the metadata store)
* Publish the large message

### What did you expect to see?

* Publish successfully

### What did you see instead?
```
2022-09-22T18:01:48,202+0800 [bookie-io-8-2] ERROR org.apache.bookkeeper.proto.BookieRequestHandler - Unhandled exception occurred in I/O thread or handler on [id: 0x81692555, L:/127.0.0.1:3181 - R:/127.0.0.1:51910]
io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 5242880: 5243010 - discarded
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.fail(LengthFieldBasedFrameDecoder.java:507) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.failIfNecessary(LengthFieldBasedFrameDecoder.java:493) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.exceededFrameLength(LengthFieldBasedFrameDecoder.java:377) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:423) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:333) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by startjava** [comment]
maybe not bug ！
standalone.conf：
maxMessageSize=5242880
nettyMaxFrameSizeBytes=5253120

you try ! good luck .

**Comment by startjava** [comment]
@RobertIndie 
https://github.com/apache/pulsar/pull/17985
mean future version not config bottom 2 item ?
maxMessageSize=5242880
nettyMaxFrameSizeBytes=5253120

**Comment by RobertIndie** [comment]
> mean future version not config bottom 2 item ?
> maxMessageSize=5242880
> nettyMaxFrameSizeBytes=5253120
> 

@startjava This is a bug fix for the standalone. Currently, the pulsar standalone doesn't respect these configurations.

**Comment by startjava** [comment]
@RobertIndie 
I still don't understand, so what is the effect of fixing this bug result? Don't  need to configure these two items?

**Comment by RobertIndie** [comment]
> I still don't understand, so what is the effect of fixing this bug result? Don't need to configure these two items?

You can try to reproduce the issue yourself. The current behavior is incorrect. No matter what bookie-related configurations you set for it, it will not respect.

**Comment by startjava** [comment]
@RobertIndie 

but i use ：
```
standalone.conf：
maxMessageSize=5242880
nettyMaxFrameSizeBytes=5253120
```

```
@Bean
    public Producer createPulsarProducer_myTopic1() throws PulsarClientException {
        Producer<String> stringProducer = pulsarClient.newProducer(Schema.STRING).topic(myTopic1).enableBatching(false).enableChunking(true).create();
        // Producer<String> stringProducer = pulsarClient.newProducer(Schema.STRING).topic(myTopic1).create();
        return stringProducer;
    }
```

i print info :
```
subscriptions getChunkedMessageRate=1
consumerStats getChunkedMessageRate=1.4833248108659105
```
look print result ,chunking success ! ??

i effect is error ??

**Comment by RobertIndie** [comment]
@startjava What metadata store did you use? Also, make sure to use the correct pulsar version.

**Comment by startjava** [comment]
i only start standalone pulsar , all  default config .
i use pulsar 2.10.1 version.
@RobertIndie

**Comment by liangyuanpeng** [comment]
Pulsar 2.10.1 use zk metadata store by default and this issue is about rocksdb metadata store.

**Comment by startjava** [comment]
if use my envirment , how do unackmsgcount value not 0 ?  wait new pulsar release version?

**Comment by RobertIndie** [comment]
> ok,but i now use pulsar 2.10.1 version can't implement?

Do you mean reproduce? I think you could also reproduce in pulsar 2.10.1 by using other metadata like rocksdb.

**Comment by startjava** [comment]
i mean , i only use pulsar 2.10.1 release version , not use new master branch version, can implement value not is 0 result?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月11日(星期二) 下午4:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/pulsar] [Bug] Cannot publish chunking message in the standalone mode (Issue #17984)





  
ok,but i now use pulsar 2.10.1 version can't implement?
  
Do you mean reproduce? I think you could also reproduce in pulsar 2.10.1 by using other metadata like rocksdb.

**Comment by RobertIndie** [comment]
> i mean , i only use pulsar 2.10.1 release version , not use new master branch version, can implement value not is 0 result?

This is not related to this issue. Please discuss it in a separate issue.

**Comment by startjava** [comment]
@RobertIndie 
I'm so sorry. I figured it out .
i question is at https://github.com/apache/pulsar/discussions/17978
can help me ? thank you much . i wait one day .

**Comment by startjava** [comment]
@RobertIndie 
the issues descript result and use zk run result same , 
Does it mean that there is also this bug in the standalone+zk environment?

**Comment by RobertIndie** [comment]
> the issues descript result and use zk run result same , Does it mean that there is also this bug in the standalone+zk environment?

Not sure what you want to say exactly. Do you mean it's also reproducible in the standalone+zk? I can't reproduce it. Could you paste your steps or other information here?
