### ISSUE TITLE
Flaky-test: NamespacesTest.testSplitBundleForMultiTimes

### ISSUE THREAD

**Issue by nicoloboschi** [apache/pulsar#18069]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/3224912715/jobs/5276751731#step:10:787

### Exception stacktrace

```
org.apache.pulsar.client.admin.PulsarAdminException$ServerSideErrorException:

 --- An unexpected error occurred in the server ---

Message: Namespace bundle my-tenant/namespace-f713b9e6-e63b-4b97-975b-c879a722ae40/0x00000000_0x02000000 is being unloaded

Stacktrace:

java.lang.IllegalStateException: Namespace bundle my-tenant/namespace-f713b9e6-e63b-4b97-975b-c879a722ae40/0x00000000_0x02000000 is being unloaded
	at org.apache.pulsar.broker.namespace.NamespaceService.lambda$findBrokerServiceUrl$9(NamespaceService.java:419)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
	at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182)
	at org.apache.pulsar.broker.namespace.NamespaceService.lambda$findBrokerServiceUrl$13(NamespaceService.java:404)
	at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.put(ConcurrentOpenHashMap.java:409)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Technoboy-** [comment]
Fixed by https://github.com/apache/pulsar/pull/17993
