### ISSUE TITLE
Flaky-test: ProxyPublishConsumeWithoutZKTest.socketTest

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#18231]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875

### Exception stacktrace

```
Error:  Tests run: 4, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 113.092 s <<< FAILURE! - in org.apache.pulsar.websocket.proxy.ProxyPublishConsumeWithoutZKTest
[491](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:492)
  Error:  socketTest(org.apache.pulsar.websocket.proxy.ProxyPublishConsumeWithoutZKTest)  Time elapsed: 30.045 s  <<< FAILURE!
[492](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:493)
  org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.websocket.proxy.ProxyPublishConsumeWithoutZKTest.socketTest() didn't finish within the time-out 30000
[493](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:494)
  	at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:371)
[494](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:495)
  	at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:282)
[495](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:496)
  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:605)
[496](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:497)
  	at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
[497](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:498)
  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
[498](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:499)
  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[499](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:500)
  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[500](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:501)
  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[501](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:502)
  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[502](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:503)
  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[503](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:504)
  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[504](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:505)
  	at org.testng.TestRunner.run(TestRunner.java:585)
[505](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:506)
  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[506](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:507)
  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[507](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:508)
  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[508](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:509)
  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[509](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:510)
  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[510](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:511)
  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[511](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:512)
  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[512](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:513)
  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[513](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:514)
  	at org.testng.TestNG.runSuites(TestNG.java:1069)
[514](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:515)
  	at org.testng.TestNG.run(TestNG.java:1037)
[515](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:516)
  	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
[516](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:517)
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
[517](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:518)
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeLazy(TestNGDirectoryTestSuite.java:123)
[518](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:519)
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:90)
[519](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:520)
  	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
[520](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:521)
  	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
[521](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:522)
  	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
[522](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:523)
  	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
[523](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935875#step:10:524)
  	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by poorbarcode** [comment]
The problem has happened again and someone has created another issue

- https://github.com/apache/pulsar/issues/18294
