### ISSUE TITLE
Flaky-test: org.apache.pulsar.broker.admin.AdminApiOffloadTest#testTopicLevelOffloadPartitioned

### ISSUE THREAD

**Issue by labuladong** [apache/pulsar#18274]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/3365965817/jobs/5582476700#step:10:1295

### Exception stacktrace

<details>
<summary>Full exception stacktrace</summary>
<pre><code>
[ERROR] testTopicLevelOffloadPartitioned(org.apache.pulsar.broker.admin.AdminApiOffloadTest)  Time elapsed: 14.607 s  <<< FAILURE!
2022-11-01T02:19:03.3331135Z org.apache.pulsar.client.admin.PulsarAdminException$ServerSideErrorException: 
2022-11-01T02:19:03.3334189Z 
2022-11-01T02:19:03.3336595Z  --- An unexpected error occurred in the server ---
2022-11-01T02:19:03.3336890Z 
2022-11-01T02:19:03.3337022Z Message: Topic policies cache have not init.
2022-11-01T02:19:03.3337250Z 
2022-11-01T02:19:03.3337374Z Stacktrace:
2022-11-01T02:19:03.3339570Z 
2022-11-01T02:19:03.3339973Z org.apache.pulsar.broker.service.BrokerServiceException$TopicPoliciesCacheNotInitException: Topic policies cache have not init.
2022-11-01T02:19:03.3340826Z 	at org.apache.pulsar.broker.service.SystemTopicBasedTopicPoliciesService.getTopicPolicies(SystemTopicBasedTopicPoliciesService.java:214)
2022-11-01T02:19:03.3343828Z 	at org.apache.pulsar.broker.service.TopicPoliciesService.lambda$getTopicPoliciesAsyncWithRetry$0(TopicPoliciesService.java:100)
2022-11-01T02:19:03.3344498Z 	at org.apache.pulsar.client.util.RetryUtil.executeWithRetry(RetryUtil.java:48)
2022-11-01T02:19:03.3347008Z 	at org.apache.pulsar.client.util.RetryUtil.lambda$executeWithRetry$1(RetryUtil.java:57)
2022-11-01T02:19:03.3347650Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2022-11-01T02:19:03.3350478Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-11-01T02:19:03.3351116Z 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
2022-11-01T02:19:03.3357844Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2022-11-01T02:19:03.3358576Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2022-11-01T02:19:03.3360985Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2022-11-01T02:19:03.3361518Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2022-11-01T02:19:03.3361744Z 
2022-11-01T02:19:03.3363980Z 	at org.apache.pulsar.client.admin.PulsarAdminException.wrap(PulsarAdminException.java:252)
2022-11-01T02:19:03.3364632Z 	at org.apache.pulsar.client.admin.internal.BaseResource.sync(BaseResource.java:351)
2022-11-01T02:19:03.3365311Z 	at org.apache.pulsar.client.admin.internal.TopicsImpl.setOffloadPolicies(TopicsImpl.java:1836)
2022-11-01T02:19:03.3368090Z 	at org.apache.pulsar.broker.admin.AdminApiOffloadTest.testOffload(AdminApiOffloadTest.java:318)
2022-11-01T02:19:03.3368756Z 	at org.apache.pulsar.broker.admin.AdminApiOffloadTest.testTopicLevelOffloadPartitioned(AdminApiOffloadTest.java:272)
2022-11-01T02:19:03.3369420Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-11-01T02:19:03.3371973Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2022-11-01T02:19:03.3374100Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-11-01T02:19:03.3374609Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2022-11-01T02:19:03.3377066Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
2022-11-01T02:19:03.3379710Z 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
2022-11-01T02:19:03.3380256Z 	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
2022-11-01T02:19:03.3380758Z 	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
2022-11-01T02:19:03.3389516Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-11-01T02:19:03.3390062Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2022-11-01T02:19:03.3392508Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2022-11-01T02:19:03.3395963Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2022-11-01T02:19:03.3396480Z 	Suppressed: org.apache.pulsar.client.admin.PulsarAdminException$ServerSideErrorException: 
2022-11-01T02:19:03.3400408Z  --- An unexpected error occurred in the server ---
2022-11-01T02:19:03.3400638Z 
2022-11-01T02:19:03.3402068Z Message: Topic policies cache have not init.
2022-11-01T02:19:03.3402276Z 
2022-11-01T02:19:03.3404285Z Stacktrace:
2022-11-01T02:19:03.3404419Z 
2022-11-01T02:19:03.3404777Z org.apache.pulsar.broker.service.BrokerServiceException$TopicPoliciesCacheNotInitException: Topic policies cache have not init.
2022-11-01T02:19:03.3405617Z 	at org.apache.pulsar.broker.service.SystemTopicBasedTopicPoliciesService.getTopicPolicies(SystemTopicBasedTopicPoliciesService.java:214)
2022-11-01T02:19:03.3408541Z 	at org.apache.pulsar.broker.service.TopicPoliciesService.lambda$getTopicPoliciesAsyncWithRetry$0(TopicPoliciesService.java:100)
2022-11-01T02:19:03.3409202Z 	at org.apache.pulsar.client.util.RetryUtil.executeWithRetry(RetryUtil.java:48)
2022-11-01T02:19:03.3411663Z 	at org.apache.pulsar.client.util.RetryUtil.lambda$executeWithRetry$1(RetryUtil.java:57)
2022-11-01T02:19:03.3412186Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2022-11-01T02:19:03.3414623Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-11-01T02:19:03.3415161Z 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
2022-11-01T02:19:03.3417528Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2022-11-01T02:19:03.3418166Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2022-11-01T02:19:03.3420562Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2022-11-01T02:19:03.3421035Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2022-11-01T02:19:03.3423172Z 
2022-11-01T02:19:03.3423503Z 		at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:272)
2022-11-01T02:19:03.3424361Z 		at org.apache.pulsar.client.admin.internal.BaseResource$2.failed(BaseResource.java:168)
2022-11-01T02:19:03.3429332Z 		at org.glassfish.jersey.client.JerseyInvocation$1.failed(JerseyInvocation.java:882)
2022-11-01T02:19:03.3429921Z 		at org.glassfish.jersey.client.JerseyInvocation$1.completed(JerseyInvocation.java:863)
2022-11-01T02:19:03.3432408Z 		at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:229)
2022-11-01T02:19:03.3432967Z 		at org.glassfish.jersey.client.ClientRuntime.access$200(ClientRuntime.java:62)
2022-11-01T02:19:03.3437305Z 		at org.glassfish.jersey.client.ClientRuntime$2.lambda$response$0(ClientRuntime.java:173)
2022-11-01T02:19:03.3437846Z 		at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
2022-11-01T02:19:03.3438239Z 		at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
2022-11-01T02:19:03.3441943Z 		at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
2022-11-01T02:19:03.3442566Z 		at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
2022-11-01T02:19:03.3444976Z 		at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
2022-11-01T02:19:03.3446060Z 		at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:288)
2022-11-01T02:19:03.3449029Z 		at org.glassfish.jersey.client.ClientRuntime$2.response(ClientRuntime.java:173)
2022-11-01T02:19:03.3449611Z 		at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$apply$1(AsyncHttpConnector.java:251)
2022-11-01T02:19:03.3456260Z 		at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
2022-11-01T02:19:03.3460126Z 		at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
2022-11-01T02:19:03.3462391Z 		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
2022-11-01T02:19:03.3462980Z 		at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
2022-11-01T02:19:03.3466606Z 		at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$retryOperation$4(AsyncHttpConnector.java:293)
2022-11-01T02:19:03.3468795Z 		at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
2022-11-01T02:19:03.3469355Z 		at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
2022-11-01T02:19:03.3474054Z 		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
2022-11-01T02:19:03.3474627Z 		at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
2022-11-01T02:19:03.3477602Z 		at org.asynchttpclient.netty.NettyResponseFuture.loadContent(NettyResponseFuture.java:222)
2022-11-01T02:19:03.3478369Z 		at org.asynchttpclient.netty.NettyResponseFuture.done(NettyResponseFuture.java:257)
2022-11-01T02:19:03.3481034Z 		at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.finishUpdate(AsyncHttpClientHandler.java:241)
2022-11-01T02:19:03.3491952Z 		at org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:114)
2022-11-01T02:19:03.3492575Z 		at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:143)
2022-11-01T02:19:03.3493231Z 		at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78)
2022-11-01T02:19:03.3499417Z 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2022-11-01T02:19:03.3500216Z 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2022-11-01T02:19:03.3505743Z 		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
2022-11-01T02:19:03.3506446Z 		at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
2022-11-01T02:19:03.3515657Z 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2022-11-01T02:19:03.3516363Z 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2022-11-01T02:19:03.3517061Z 		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
2022-11-01T02:19:03.3542421Z 		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
2022-11-01T02:19:03.3544387Z 		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
2022-11-01T02:19:03.3547267Z 		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
2022-11-01T02:19:03.3547891Z 		at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
2022-11-01T02:19:03.3550400Z 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2022-11-01T02:19:03.3551252Z 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2022-11-01T02:19:03.3553837Z 		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
2022-11-01T02:19:03.3554585Z 		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
2022-11-01T02:19:03.3557459Z 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2022-11-01T02:19:03.3563052Z 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2022-11-01T02:19:03.3563831Z 		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
2022-11-01T02:19:03.3573803Z 		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
2022-11-01T02:19:03.3574485Z 		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
2022-11-01T02:19:03.3575021Z 		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
2022-11-01T02:19:03.3581816Z 		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
2022-11-01T02:19:03.3582345Z 		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
2022-11-01T02:19:03.3587283Z 		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
2022-11-01T02:19:03.3587855Z 		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2022-11-01T02:19:03.3591936Z 		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2022-11-01T02:19:03.3592319Z 		... 1 more
2022-11-01T02:19:03.3595165Z 	Caused by: javax.ws.rs.InternalServerErrorException: HTTP 500 Topic policies cache have not init.
2022-11-01T02:19:03.3595821Z 		at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:960)
2022-11-01T02:19:03.3599027Z 		at org.glassfish.jersey.client.JerseyInvocation.access$700(JerseyInvocation.java:82)
2022-11-01T02:19:03.3599500Z 		... 54 more
2022-11-01T02:19:03.3605867Z Caused by: [CIRCULAR REFERENCE: javax.ws.rs.InternalServerErrorException: HTTP 500 Topic policies cache have not init.]
2022-11-01T02:19:03.3606280Z 
</code></pre>
</details>

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Technoboy-** [comment]
Mark this as closed because we don't see this anymore and we have fixed several bugs related to topic policies.
