### ISSUE TITLE
Flaky-test: ProxyPublishConsumeWithoutZKTest.socketTest

### ISSUE THREAD

**Issue by labuladong** [apache/pulsar#18294]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/3374860995/jobs/5601165093#step:10:492

### Exception stacktrace

<details>
<summary>Full exception stacktrace</summary>
<pre><code>
Error:  socketTest(org.apache.pulsar.websocket.proxy.ProxyPublishConsumeWithoutZKTest)  Time elapsed: 30.029 s  <<< FAILURE!
  org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.websocket.proxy.ProxyPublishConsumeWithoutZKTest.socketTest() didn't finish within the time-out 30000
  	at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:371)
  	at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:282)
  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:605)
  	at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
  	at org.testng.TestRunner.run(TestRunner.java:585)
  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
  	at org.testng.TestNG.runSuites(TestNG.java:1069)
  	at org.testng.TestNG.run(TestNG.java:1037)
  	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeLazy(TestNGDirectoryTestSuite.java:123)
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:90)
  	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
  	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
  	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
  	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
  	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
</code></pre>
</details>

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by poorbarcode** [comment]
another one:

https://github.com/poorbarcode/pulsar/actions/runs/3371924159/jobs/5594942720

**Comment by poorbarcode** [comment]
This case failed after https://github.com/apache/pulsar/pull/18268 merge

- https://github.com/apache/pulsar/actions/runs/3374860995/jobs/5601165093#step:10:492

### problem occurs at:

<img width="798" alt="截屏2022-11-02 17 54 33" src="https://user-images.githubusercontent.com/25195800/199459520-13d4e40a-9f47-4585-bd1c-2be7facadae4.png">


### #18268 merge time:

<img width="984" alt="截屏2022-11-02 17 55 09" src="https://user-images.githubusercontent.com/25195800/199459654-85693aec-2799-48f0-92ca-bba6016d9f27.png">

**Comment by coderzc** [comment]
> * https://github.com/apache/pulsar/actions/runs/3374860995/jobs/5601165093#step:10:492

It seems to no rebase master.

**Comment by labuladong** [comment]
> It seems to no rebase master.

Yes, that branch didn't rebase master.

But seems this https://github.com/poorbarcode/pulsar/pull/32 has rebased master still has timeout failure:

<img width="958" alt="image" src="https://user-images.githubusercontent.com/37220920/199480514-0ec48cb5-de21-439b-8d13-bc547d2e6650.png">

**Comment by poorbarcode** [comment]
another one:
- https://github.com/poorbarcode/pulsar/actions/runs/3407116575/jobs/5666517854
