### ISSUE TITLE
Flaky-test: MetadataStoreStatsTest#testBatchMetadataStoreMetrics

### ISSUE THREAD

**Issue by labuladong** [apache/pulsar#18300]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/labuladong/pulsar/actions/runs/3376057575/jobs/5603501145#step:10:1208

### Exception stacktrace

<details>
<summary>Full exception stacktrace</summary>
<pre><code>
 Error:  Tests run: 7, Failures: 2, Errors: 0, Skipped: 5, Time elapsed: 28.876 s <<< FAILURE! - in org.apache.pulsar.broker.stats.MetadataStoreStatsTest
  Error:  testBatchMetadataStoreMetrics(org.apache.pulsar.broker.stats.MetadataStoreStatsTest)  Time elapsed: 10.577 s  <<< FAILURE!
  java.lang.AssertionError: expected object to not be null
  	at org.testng.Assert.fail(Assert.java:99)
  	at org.testng.Assert.assertNotNull(Assert.java:942)
  	at org.testng.Assert.assertNotNull(Assert.java:926)
  	at org.apache.pulsar.broker.stats.MetadataStoreStatsTest.testBatchMetadataStoreMetrics(MetadataStoreStatsTest.java:185)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
</code></pre>
</details>

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by labuladong** [comment]
cc @tjiuming

**Comment by poorbarcode** [comment]
another one:
 - https://github.com/apache/pulsar/actions/runs/3437251092/jobs/5731951247

**Comment by tjiuming** [comment]
sorry for missed the issue, I'll check it later

**Comment by coderzc** [comment]
Another one: https://github.com/apache/pulsar/actions/runs/3496355710/jobs/5854319305

**Comment by tjiuming** [comment]
cannot reproduce the issue on my local

**Comment by lhotari** [comment]
Yet another one: https://github.com/apache/pulsar/actions/runs/3995672027/jobs/6855066875#step:11:1233

**Comment by lhotari** [comment]
> cannot reproduce the issue on my local. When [MetadataStoreConfig](https://github.com/apache/pulsar/blob/master/pulsar-metadata/src/main/java/org/apache/pulsar/metadata/api/MetadataStoreConfig.java)#metadataStoreName is a empty string, this issue happens, but I've checked everywhere, the field must not be empty

@tjiuming This was fairly easy to reproduce with `@Test(invocations = 100)`. I created a fix in #19329. Please review

**Comment by lhotari** [comment]
The problem remains. 
Example failure: https://github.com/apache/pulsar/actions/runs/4072071397/jobs/7016199219#step:11:1265

There's more debug logging after the #19329 changes so it might be easier to find out what is going on.
