### ISSUE TITLE
Flaky-test: PersistentTopicStreamingDispatcherE2ETest.testMessageRedelivery

### ISSUE THREAD

**Issue by coderzc** [apache/pulsar#18314]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/3377038718/jobs/5605505912#step:8:1667

### Exception stacktrace

<details>
<summary>Full exception stacktrace</summary>
<pre><code>
  Error:  testMessageRedelivery(org.apache.pulsar.broker.service.persistent.PersistentTopicStreamingDispatcherE2ETest)  Time elapsed: 1.14 s  <<< FAILURE!
  java.lang.AssertionError: msg should be redelivered 
  	at org.testng.Assert.fail(Assert.java:87)
  	at org.apache.pulsar.broker.service.PersistentTopicE2ETest.testMessageRedelivery(PersistentTopicE2ETest.java:1723)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.pulsar.client.api.Message.getValue()" because "redeliveredMsg" is null
  	at org.apache.pulsar.broker.service.PersistentTopicE2ETest.lambda$testMessageRedelivery$7(PersistentTopicE2ETest.java:1721)
  	at java.base/java.util.ArrayList.removeIf(ArrayList.java:[1672](https://github.com/apache/pulsar/actions/runs/3377038718/jobs/5605505912#step:8:1674))
  	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)
  	at org.apache.pulsar.broker.service.PersistentTopicE2ETest.testMessageRedelivery(PersistentTopicE2ETest.java:1721)
  	... 12 more
</code></pre>
</details>

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by poorbarcode** [comment]
another one :https://github.com/apache/pulsar/actions/runs/3391255532/jobs/5636256181

**Comment by tisonkun** [comment]
another instance https://github.com/apache/pulsar/actions/runs/3446107017

It remains after 3 times of rerun. I highly suspect that it steadily fails now.
