### ISSUE TITLE
[Bug] Pulsar client - MessageId.fromByteArrayWithTopic is not backward compatible from 2.7.2

### ISSUE THREAD

**Issue by PatrykWitkowski** [apache/pulsar#18395]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

2.7.2

### Minimal reproduce step

- send a message to some topic using pulsar client below 2.7.2
- upgrade pulsar client to 2.7.2 or above
- try to consume that message and retrieve message id using: MessageId.fromByteArrayWithTopic()

### What did you expect to see?

the message is consumed correctly and I got a message id

### What did you see instead?

the exception that "batch_size" field is not set is thrown
![image](https://user-images.githubusercontent.com/15839519/200805484-01e0c89d-b1af-4166-b690-81b8da933668.png)

### Anything else?

I found in the source code that for the: MessageId.fromByteArray() that backward compatibility was preserved by adding the check if that "batch_size" exist:

MessageIdImpl.fromByteArray():
```
if (idData.hasBatchSize()) {
                messageId = new BatchMessageIdImpl(idData.getLedgerId(), idData.getEntryId(), idData.getPartition(), idData.getBatchIndex(), idData.getBatchSize(), BatchMessageAcker.newAcker(idData.getBatchSize()));
            } else {
                messageId = new BatchMessageIdImpl(idData.getLedgerId(), idData.getEntryId(), idData.getPartition(), idData.getBatchIndex());
}
```

and I think that something like this should be added as well to the MessageIdImpl.fromByteArrayWithTopic() where now a check like this is missing.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by BewareMyPower** [comment]
> try to consume that message and retrieve message id using: MessageId.fromByteArrayWithTopic()

Is the byte array saved by yourself? Why not use `Message#getMessageId` to retrieve the message id?

**Comment by BewareMyPower** [comment]
I can reproduce this issue by the following steps.

Run a 2.10.1 consumer:

```java
        @Cleanup final var client = PulsarClient.builder().serviceUrl(Config.BROKER_URL).build();
        @Cleanup final var consumer = client.newConsumer()
                .topic("message-id-topic")
                .subscriptionName("sub")
                .subscriptionInitialPosition(SubscriptionInitialPosition.Earliest)
                .subscribe();
        while (true) {
            final var msg = consumer.receive();
            try {
                final var id = MessageId.fromByteArrayWithTopic(msg.getData(),
                        consumer.getTopic());
                log.info("XYZ Received {}", id);
            } catch (IOException e) {
                log.error("XYZ Failed to parse: {}", e.getMessage());
            }
        }
```

Run a 2.7.1 producer:

```java
        @Cleanup final var client = PulsarClient.builder()
                .serviceUrl("pulsar://172.20.58.232:6650")
                .build();
        @Cleanup final var producer = client.newProducer(Schema.STRING)
                .topic("topic")
                .create();
        var id = producer.send("msg");
        log.info("XYZ sent to {}", id);
        @Cleanup final var msgIdProducer = client.newProducer()
                .topic("message-id-topic")
                .create();
        msgIdProducer.send(id.toByteArray());
```

The consumer side failed with

```
Exception in thread "main" java.lang.IllegalStateException: Field 'batch_size' is not set
	at org.apache.pulsar.common.api.proto.MessageIdData.getBatchSize(MessageIdData.java:147)
	at org.apache.pulsar.client.impl.MessageIdImpl.fromByteArrayWithTopic(MessageIdImpl.java:159)
	at org.apache.pulsar.client.impl.MessageIdImpl.fromByteArrayWithTopic(MessageIdImpl.java:144)
	at org.apache.pulsar.client.impl.PulsarClientImplementationBindingImpl.newMessageIdFromByteArrayWithTopic(PulsarClientImplementationBindingImpl.java:110)
	at org.apache.pulsar.client.api.MessageId.fromByteArrayWithTopic(MessageId.java:73)
	at pulsar.ConsumerDemo.main(ConsumerDemo.java:27)
```
