### ISSUE TITLE
[Bug] Unable to run locally using IntelliJ + Ventura MacOS

### ISSUE THREAD

**Issue by Somnium99** [apache/pulsar#18441]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

OS : 13.0.1 Ventura MacOS
Pulsar : 2.10.2

### Minimal reproduce step

build.gradle.kts :
```
dependencies {
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4")
    testImplementation("org.jetbrains.kotlin:kotlin-test")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    implementation("io.ktor:ktor-server-netty:2.1.3")

    implementation("org.apache.pulsar:pulsar-client:2.10.2")
     
```
 
 also tried :
  ```
     runtimeOnly("io.netty:netty-resolver-dns-classes-macos:4.1.85.Final")
     runtimeOnly("io.netty:netty-resolver-dns-classes-macos:4.1.85.Final:osx-x86_64")
   ```

Main.kt : 
```
    val pulsar = PulsarClient.builder().serviceUrl("pulsar://localhost:6650").build()
```

On running the program I get :
```
21:42:28.732 [main] DEBUG org.apache.pulsar.shade.io.netty.util.NetUtilInitializations - Loopback interface: lo0 (lo0, 0:0:0:0:0:0:0:1%lo0)
21:42:28.733 [main] DEBUG org.apache.pulsar.shade.io.netty.util.NetUtil - Failed to get SOMAXCONN from sysctl and file /proc/sys/net/core/somaxconn. Default: 128
21:42:28.750 [main] DEBUG org.apache.pulsar.shade.io.netty.resolver.DefaultHostsFileEntriesResolver - -Dio.netty.hostsFileRefreshInterval: 0
21:42:28.753 [main] WARN org.apache.pulsar.shade.io.netty.resolver.dns.DnsServerAddressStreamProviders - Can not find org.apache.pulsar.shade.io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider in the classpath, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS.
21:42:28.762 [main] WARN org.apache.pulsar.common.util.netty.DnsResolverUtil - Cannot get DNS TTL settings from sun.net.InetAddressCachePolicy class
java.lang.IllegalAccessException: class org.apache.pulsar.common.util.netty.DnsResolverUtil cannot access class sun.net.InetAddressCachePolicy (in module java.base) because module java.base does not export sun.net to unnamed module @3aefe5e5
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
	at java.base/java.lang.reflect.Method.invoke(Method.java:560)
	at org.apache.pulsar.common.util.netty.DnsResolverUtil.<clinit>(DnsResolverUtil.java:46)
	at org.apache.pulsar.client.impl.ConnectionPool.createAddressResolver(ConnectionPool.java:121)
	at org.apache.pulsar.client.impl.ConnectionPool.lambda$new$1(ConnectionPool.java:109)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:109)
	at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:78)
	at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:73)
	at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:194)
	at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:150)
	at org.apache.pulsar.client.impl.ClientBuilderImpl.build(ClientBuilderImpl.java:67)
	at MainKt.main(Main.kt:72)
```

### What did you expect to see?

No error. And a functioning program.

### What did you see instead?

Program does not crash, but pulsar framework does not work. 
It also shows the mentioned stacktrace when trying to build a pulsar client.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by labuladong** [comment]
I think `Connection refused: localhost/127.0.0.1:6650` is the root cause.

Have you started the [pulsar standalone](https://pulsar.apache.org/docs/getting-started-standalone/) first?

**Comment by Somnium99** [comment]
Ok, so I tried 3 ways of installing and running pulsar, and only one worked.

I. brew - problem exists 
```
> brew install apache-pulsar
> brew services start apache-pulsar
> pulsar standalone
```

II. download local binary - problem exists
```
> download and unzip the binary files, and then go to the directory in terminal
> ./bin/pulsar standalone
```

III. downloading and running via Docker - **Works!**
```
docker run -it -p 6650:6650 -p 8080:8080 --mount source=pulsardata,target=/pulsar/data --mount source=pulsarconf,target=/pulsar/conf apachepulsar/pulsar:2.10.2 bin/pulsar standalone
```

**Comment by labuladong** [comment]
I guess you are using 2.10.x version of Pulsar on m1 MacBook. In 2.10.x, there will be an issue using the second way, and the newer version will resolve that issue.

**Comment by Somnium99** [comment]
No it's actually a quite an old macbook - Macbook Pro 2019 , 2.6 GHz 6-Core Intel Core i7

**Comment by labuladong** [comment]
OK, maybe you can search your problem in issues. Or just use docker :)

**Comment by os-architect** [comment]
same problem here. @Somnium99 , have you found a solution for this?
