### ISSUE TITLE
Flaky-test: TransactionEndToEndTest.produceCommitTest

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#18466]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137

### Exception stacktrace

```
Error:  Tests run: 52, Failures: 22, Errors: 0, Skipped: 27, Time elapsed: 617.386 s <<< FAILURE! - in org.apache.pulsar.client.impl.TransactionEndToEndTest
[1386](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1387)
  Error:  produceCommitTest(org.apache.pulsar.client.impl.TransactionEndToEndTest)  Time elapsed: 300.015 s  <<< FAILURE!
[1387](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1388)
  org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.client.impl.TransactionEndToEndTest.produceCommitTest() didn't finish within the time-out 300000
[1388](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1389)
  	at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:371)
[1389](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1390)
  	at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:282)
[1390](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1391)
  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:605)
[1391](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1392)
  	at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
[1392](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1393)
  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
[1393](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1394)
  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[1394](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1395)
  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[1395](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1396)
  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[1396](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1397)
  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[1397](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1398)
  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[1398](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1399)
  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[1399](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1400)
  	at org.testng.TestRunner.run(TestRunner.java:585)
[1400](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1401)
  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[1401](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1402)
  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[1402](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1403)
  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[1403](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1404)
  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[1404](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1405)
  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[1405](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1406)
  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[1406](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1407)
  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[1407](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1408)
  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[1408](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1409)
  	at org.testng.TestNG.runSuites(TestNG.java:1069)
[1409](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1410)
  	at org.testng.TestNG.run(TestNG.java:1037)
[1410](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1411)
  	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
[1411](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1412)
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
[1412](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1413)
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeLazy(TestNGDirectoryTestSuite.java:123)
[1413](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1414)
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:90)
[1414](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1415)
  	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
[1415](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1416)
  	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
[1416](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1417)
  	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
[1417](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1418)
  	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
[1418](https://github.com/apache/pulsar/actions/runs/3461842392/jobs/5780214137#step:10:1419)
  	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by liangyepianzhou** [comment]
Ok,  I'm willing to resolve it.

**Comment by liangyepianzhou** [comment]
This flaky test can be resolve by https://github.com/apache/pulsar/pull/17836

**Comment by lhotari** [comment]
> This flaky test can be resolved by https://github.com/apache/pulsar/pull/18486 and https://github.com/apache/pulsar/pull/17836

@liangyepianzhou this problem remains. #18522 didn't resolve this either. 

Latest failure: https://github.com/apache/pulsar/actions/runs/4498077999/jobs/7914492741?pr=19904#step:11:547

```
  Error:  Tests run: 144, Failures: 1, Errors: 0, Skipped: 140, Time elapsed: 126.933 s <<< FAILURE! - in org.apache.pulsar.client.impl.TransactionEndToEndTest
  Error:  produceCommitTest(org.apache.pulsar.client.impl.TransactionEndToEndTest)  Time elapsed: 10.631 s  <<< FAILURE!
  org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.transaction.TransactionCoordinatorClientException$InvalidTxnStatusException: [(2,0)] with unexpected state : TIME_OUT, expect OPEN state!
  	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:1111)
  	at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.send(TypedMessageBuilderImpl.java:90)
  	at org.apache.pulsar.client.impl.TransactionEndToEndTest.produceCommitTest(TransactionEndToEndTest.java:285)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Caused by: java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.transaction.TransactionCoordinatorClientException$InvalidTxnStatusException: [(2,0)] with unexpected state : TIME_OUT, expect OPEN state!
  	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
  	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
  	at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.send(TypedMessageBuilderImpl.java:88)
  	... 13 more
  Caused by: org.apache.pulsar.client.api.transaction.TransactionCoordinatorClientException$InvalidTxnStatusException: [(2,0)] with unexpected state : TIME_OUT, expect OPEN state!
  	at org.apache.pulsar.client.impl.transaction.TransactionImpl.checkIfOpen(TransactionImpl.java:259)
  	at org.apache.pulsar.client.impl.PartitionedProducerImpl.internalSendWithTxnAsync(PartitionedProducerImpl.java:228)
  	at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.sendAsync(TypedMessageBuilderImpl.java:99)
  	at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.send(TypedMessageBuilderImpl.java:80)
  	... 13 more
```

do you have a chance to fix this? thanks

**Comment by lhotari** [comment]
I wonder if the most recent failure is different. 
The stack trace contains
`org.apache.pulsar.client.api.transaction.TransactionCoordinatorClientException$InvalidTxnStatusException: [(2,0)] with unexpected state : TIME_OUT, expect OPEN state!`

**Comment by liangyepianzhou** [comment]
There may have been some recent changes or unresolved issues from before. I will make another attempt to address this problem.
