### ISSUE TITLE
Flaky-test: NegativeAcksTest.testFailoverConsumerBatchCumulateAck

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#18480]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/3468163315/jobs/5798520468

### Exception stacktrace

```
Error:  Tests run: 16, Failures: 1, Errors: 0, Skipped: 15, Time elapsed: 18.237 s <<< FAILURE! - in org.apache.pulsar.client.impl.NegativeAcksTest
[727](https://github.com/apache/pulsar/actions/runs/3468163311/jobs/5798518872#step:10:728)
  Error:  testFailoverConsumerBatchCumulateAck(org.apache.pulsar.client.impl.NegativeAcksTest)  Time elapsed: 6.245 s  <<< FAILURE!
[728](https://github.com/apache/pulsar/actions/runs/3468163311/jobs/5798518872#step:10:729)
  java.lang.AssertionError: expected [9] but found [0]
[729](https://github.com/apache/pulsar/actions/runs/3468163311/jobs/5798518872#step:10:730)
  	at org.testng.Assert.fail(Assert.java:99)
[730](https://github.com/apache/pulsar/actions/runs/3468163311/jobs/5798518872#step:10:731)
  	at org.testng.Assert.failNotEquals(Assert.java:1037)
[731](https://github.com/apache/pulsar/actions/runs/3468163311/jobs/5798518872#step:10:732)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
[732](https://github.com/apache/pulsar/actions/runs/3468163311/jobs/5798518872#step:10:733)
  	at org.testng.Assert.assertEquals(Assert.java:122)
[733](https://github.com/apache/pulsar/actions/runs/3468163311/jobs/5798518872#step:10:734)
  	at org.testng.Assert.assertEquals(Assert.java:907)
[734](https://github.com/apache/pulsar/actions/runs/3468163311/jobs/5798518872#step:10:735)
  	at org.testng.Assert.assertEquals(Assert.java:917)
[735](https://github.com/apache/pulsar/actions/runs/3468163311/jobs/5798518872#step:10:736)
  	at org.apache.pulsar.client.impl.NegativeAcksTest.testFailoverConsumerBatchCumulateAck(NegativeAcksTest.java:439)
[736](https://github.com/apache/pulsar/actions/runs/3468163311/jobs/5798518872#step:10:737)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[737](https://github.com/apache/pulsar/actions/runs/3468163311/jobs/5798518872#step:10:738)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[738](https://github.com/apache/pulsar/actions/runs/3468163311/jobs/5798518872#step:10:739)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[739](https://github.com/apache/pulsar/actions/runs/3468163311/jobs/5798518872#step:10:740)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[740](https://github.com/apache/pulsar/actions/runs/3468163311/jobs/5798518872#step:10:741)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[741](https://github.com/apache/pulsar/actions/runs/3468163311/jobs/5798518872#step:10:742)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
[742](https://github.com/apache/pulsar/actions/runs/3468163311/jobs/5798518872#step:10:743)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
[743](https://github.com/apache/pulsar/actions/runs/3468163311/jobs/5798518872#step:10:744)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
[744](https://github.com/apache/pulsar/actions/runs/3468163311/jobs/5798518872#step:10:745)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[745](https://github.com/apache/pulsar/actions/runs/3468163311/jobs/5798518872#step:10:746)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[746](https://github.com/apache/pulsar/actions/runs/3468163311/jobs/5798518872#step:10:747)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[747](https://github.com/apache/pulsar/actions/runs/3468163311/jobs/5798518872#step:10:748)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by BewareMyPower** [comment]
This test is too flaky.

https://github.com/apache/pulsar/actions/runs/3472040284/jobs/5805588109

**Comment by BewareMyPower** [comment]
No, it's another fix, not related to this test.
