### ISSUE TITLE
[Bug] `pulsar-admin topics skip-all` not work

### ISSUE THREAD

**Issue by labuladong** [apache/pulsar#18525]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Master branch.

### Minimal reproduce step

I read doc: https://pulsar.apache.org/docs/next/admin-api-topics#skip-all-messages

Execute this command:

```shell
./pulsar-admin topics skip-all \
     --subscription java-subscription-aa my-topic-aaa
```

### What did you expect to see?

Skip all messages of the subscription.

### What did you see instead?

```shell
Expected a command, got skip-all

Invalid command, please use `pulsar-admin --help` to check out how to use
2022-11-18T05:22:03,186+0800 [main] WARN  org.apache.pulsar.common.util.ShutdownUtil - Triggering immediate shutdown of current process with status 1
java.lang.Exception: Stacktrace for immediate shutdown
	at org.apache.pulsar.common.util.ShutdownUtil.triggerImmediateForcefulShutdown(ShutdownUtil.java:52) ~[org.apache.pulsar-pulsar-common-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
	at org.apache.pulsar.admin.cli.PulsarAdminTool.exit(PulsarAdminTool.java:309) ~[org.apache.pulsar-pulsar-client-tools-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
	at org.apache.pulsar.admin.cli.PulsarAdminTool.main(PulsarAdminTool.java:300) ~[org.apache.pulsar-pulsar-client-tools-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
```

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by labuladong** [comment]
This is not cli bug, `skip-all` command has been renamed to `clear-backlog`, so fixing the document is enough.
