### ISSUE TITLE
[Bug] bin/pulsar-client NoClassDefFoundError: io/netty/incubator/channel/uring/IOUringEventLoopGroup

### ISSUE THREAD

**Issue by michaeljmarshall** [apache/pulsar#18530]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

I built `bin/pulsar-client` using a recent version of master. Here is the commit sha 080213bdf7a00dda8f8e7c5927d83d7e6a9c5c6a.

### Minimal reproduce step

Build the pulsar project's `master` branch using `mvn -Pcore-modules,-main -T 1C clean install -DskipTests -Dspotbugs.skip=true`. I was at 080213bdf7a00dda8f8e7c5927d83d7e6a9c5c6a. I used:

```
$ java -version
openjdk version "17.0.4.1" 2022-08-12
OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode, sharing)
```

```
$ bin/pulsar-client produce -m test test
2022-11-17T22:30:47,216-0600 [main] INFO  org.apache.pulsar.client.cli.PulsarClientTool - 0 messages successfully produced
Exception in thread "main" java.lang.NoClassDefFoundError: io/netty/incubator/channel/uring/IOUringEventLoopGroup
        at org.apache.pulsar.common.util.netty.EventLoopUtil.getClientSocketChannelClass(EventLoopUtil.java:106)
        at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:111)
        at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:95)
        at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:90)
        at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:197)
        at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:153)
        at org.apache.pulsar.client.impl.ClientBuilderImpl.build(ClientBuilderImpl.java:63)
        at org.apache.pulsar.client.cli.CmdProduce.publish(CmdProduce.java:247)
        at org.apache.pulsar.client.cli.CmdProduce.run(CmdProduce.java:239)
        at org.apache.pulsar.client.cli.PulsarClientTool.run(PulsarClientTool.java:231)
        at org.apache.pulsar.client.cli.PulsarClientTool.main(PulsarClientTool.java:271)
Caused by: java.lang.ClassNotFoundException: io.netty.incubator.channel.uring.IOUringEventLoopGroup
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 11 more
```

### What did you expect to see?

It should not have failed.

### What did you see instead?

A missing class.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
cc @coderzc 

I suspect that we shouldn't link io_uring if on platforms other than linux.

**Comment by coderzc** [comment]
@michaeljmarshall I build the pulsar project's master branch using `mvn -Pcore-modules,-main -T 1C clean install -DskipTests -Dspotbugs.skip=true`, and it works well.

```
[INFO] Pulsar Build Tools ................................. SUCCESS [  7.866 s]
[INFO] Pulsar ............................................. SUCCESS [  3.687 s]
[INFO] Pulsar Test Mocks .................................. SUCCESS [ 12.947 s]
[INFO] Pulsar Client :: API ............................... SUCCESS [ 13.771 s]
[INFO] Pulsar Client Admin :: API ......................... SUCCESS [  8.712 s]
[INFO] Pulsar Common ...................................... SUCCESS [ 31.486 s]
[INFO] Pulsar Metadata .................................... SUCCESS [ 18.867 s]
[INFO] Managed Ledger ..................................... SUCCESS [ 20.755 s]
[INFO] pulsar-broker-common ............................... SUCCESS [ 13.223 s]
[INFO] Apache Pulsar :: Bouncy Castle :: Parent ........... SUCCESS [  2.676 s]
[INFO] Apache Pulsar :: Bouncy Castle :: BC ............... SUCCESS [  2.315 s]
[INFO] pulsar-client-messagecrypto-bc ..................... SUCCESS [  2.262 s]
[INFO] Pulsar Functions :: Parent ......................... SUCCESS [  2.676 s]
[INFO] Pulsar Functions :: Proto .......................... SUCCESS [ 12.350 s]
[INFO] Pulsar Client Java ................................. SUCCESS [ 35.030 s]
[INFO] Pulsar WebSocket ................................... SUCCESS [  8.552 s]
[INFO] Apache Pulsar :: Package Management ................ SUCCESS [  4.767 s]
[INFO] Apache Pulsar :: Package Management :: Core ........ SUCCESS [  2.887 s]
[INFO] Pulsar Client Admin Original ....................... SUCCESS [  8.693 s]
[INFO] Pulsar Transaction :: Parent ....................... SUCCESS [  5.340 s]
[INFO] Pulsar Transaction :: Common ....................... SUCCESS [  3.805 s]
[INFO] Pulsar Functions :: API ............................ SUCCESS [  3.164 s]
[INFO] Pulsar IO :: Parent ................................ SUCCESS [  4.408 s]
[INFO] Pulsar IO :: IO .................................... SUCCESS [  4.769 s]
[INFO] Pulsar IO :: Batch Discovery Triggerers ............ SUCCESS [  2.799 s]
[INFO] pulsar-config-validation ........................... SUCCESS [ 10.960 s]
[INFO] Pulsar Functions :: Utils .......................... SUCCESS [  8.066 s]
[INFO] Pulsar IO :: IO Common ............................. SUCCESS [  2.905 s]
[INFO] Pulsar Functions :: Secrets ........................ SUCCESS [  2.981 s]
[INFO] Pulsar Functions :: Instance ....................... SUCCESS [  9.452 s]
[INFO] Pulsar Functions :: Runtime ........................ SUCCESS [  5.555 s]
[INFO] Pulsar IO :: Cassandra ............................. SUCCESS [  6.352 s]
[INFO] Pulsar IO :: Twitter ............................... SUCCESS [  6.587 s]
[INFO] Pulsar Functions :: API Examples ................... SUCCESS [  6.761 s]
[INFO] Pulsar Functions :: API Examples (NAR) ............. SUCCESS [  2.521 s]
[INFO] Pulsar Functions :: Worker ......................... SUCCESS [ 11.628 s]
[INFO] Pulsar Functions :: Local Runner original .......... SUCCESS [  3.416 s]
[INFO] Pulsar IO :: Batch Data Generator .................. SUCCESS [  6.105 s]
[INFO] Pulsar IO :: Data Generator ........................ SUCCESS [  6.352 s]
[INFO] Pulsar Transaction :: Coordinator .................. SUCCESS [  8.381 s]
[INFO] Apache Pulsar :: Package Management :: Filesystem Storage SUCCESS [  5.292 s]
[INFO] Pulsar Broker ...................................... SUCCESS [01:02 min]
[INFO] Pulsar Client Tools API ............................ SUCCESS [  1.976 s]
[INFO] Pulsar Client Tools ................................ SUCCESS [  9.342 s]
[INFO] Pulsar CLI Custom command example .................. SUCCESS [ 18.833 s]
[INFO] Pulsar Client Tools Test ........................... SUCCESS [  4.252 s]
[INFO] Pulsar Proxy ....................................... SUCCESS [  7.962 s]
[INFO] Pulsar Test Client ................................. SUCCESS [  6.722 s]
[INFO] pulsar-client-auth-sasl ............................ SUCCESS [  3.379 s]
[INFO] pulsar-broker-auth-sasl ............................ SUCCESS [  5.766 s]
[INFO] Pulsar Functions :: Runtime All .................... SUCCESS [  8.738 s]
[INFO] Apache Pulsar :: Bouncy Castle :: BC-FIPS .......... SUCCESS [  5.124 s]
[INFO] Pulsar Bouncy Castle FIPS Test ..................... SUCCESS [  3.922 s]
[INFO] Apache Pulsar :: Package Management :: BookKeeper Storage SUCCESS [  6.032 s]
[INFO] Pulsar :: Distribution ............................. SUCCESS [  2.678 s]
[INFO] Pulsar :: Distribution :: Server ................... SUCCESS [ 19.729 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:59 min (Wall Clock)
[INFO] Finished at: 2022-11-19T20:13:21+08:00
[INFO] ------------------------------------------------------------------------
```

I use java version:
```
$ java -version
openjdk version "17.0.3" 2022-04-19 LTS
OpenJDK Runtime Environment Corretto-17.0.3.6.1 (build 17.0.3+6-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.3.6.1 (build 17.0.3+6-LTS, mixed mode, sharing)
```

**Comment by tisonkun** [comment]
@coderzc @michaeljmarshall which os/platform do you run this command?

**Comment by coderzc** [comment]
> @coderzc @michaeljmarshall which os/platform do you run this command?

I use macOS 12.4 (M1 chip)

**Comment by michaeljmarshall** [comment]
I am on MacOS with an intel chip

**Comment by michaeljmarshall** [comment]
I'll try to reproduce it again.

**Comment by drgnchan** [comment]
@michaeljmarshall you can check your environment variable `enable.io_uring`. Is it '1' or 'true'?

**Comment by nodece** [comment]
This is a bug. I already reproduce it on my computer.

```
mvn clean install -Pcore-modules,-main -DskipTests -Dspotbugs.skip
./bin/pulsar-client produce -m "message" test-topic-1
```
log:
```
❯ ./bin/pulsar-client produce -m "message" test-topic-1
2022-11-21T20:56:31,582+0800 [main] INFO  org.apache.pulsar.client.cli.PulsarClientTool - 0 messages successfully produced
Exception in thread "main" java.lang.NoClassDefFoundError: io/netty/incubator/channel/uring/IOUringEventLoopGroup
        at org.apache.pulsar.common.util.netty.EventLoopUtil.getClientSocketChannelClass(EventLoopUtil.java:106)
        at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:111)
        at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:95)
        at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:90)
        at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:197)
        at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:153)
        at org.apache.pulsar.client.impl.ClientBuilderImpl.build(ClientBuilderImpl.java:63)
        at org.apache.pulsar.client.cli.CmdProduce.publish(CmdProduce.java:247)
        at org.apache.pulsar.client.cli.CmdProduce.run(CmdProduce.java:239)
        at org.apache.pulsar.client.cli.PulsarClientTool.run(PulsarClientTool.java:231)
        at org.apache.pulsar.client.cli.PulsarClientTool.main(PulsarClientTool.java:271)
Caused by: java.lang.ClassNotFoundException: io.netty.incubator.channel.uring.IOUringEventLoopGroup
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 11 more
```

**Comment by tisonkun** [comment]
Trying to fix it at https://github.com/apache/pulsar/pull/18559.

@michaeljmarshall @nodece you can verify it.

**Comment by nodece** [comment]
#18559 can fix this issue.

**Comment by nicoloboschi** [comment]
@nodece @tisonkun pushed a fix here: https://github.com/apache/pulsar/pull/18609

**Comment by michaeljmarshall** [comment]
Thanks for fixing this @nicoloboschi!
