### ISSUE TITLE
[Bug] Stateful Functions not working

### ISSUE THREAD

**Issue by Technoboy-** [apache/pulsar#18546]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Master branch/ branch-2.11

### Minimal reproduce step

1. Build the branch
2. Validate the branch by [Validate Release Candidate#validate-stateful-functions](https://pulsar.apache.org/contribute/validate-release-candidate#validate-stateful-functions)
3. Go to the step `3. Query the state table for the function: watching on a key called "hello"`, error occurs

### What did you expect to see?

```
# key 'hello' doesn't exist.
# key 'hello' doesn't exist.
# key 'hello' doesn't exist
```

### What did you see instead?

```
State storage client is not done initializing. Please try again in a little while.

Reason: State storage client is not done initializing. Please try again in a little while.
2022-11-19T16:03:38,163+0800 [main] WARN  org.apache.pulsar.common.util.ShutdownUtil - Triggering immediate shutdown of current process with status 1
java.lang.Exception: Stacktrace for immediate shutdown
	at org.apache.pulsar.common.util.ShutdownUtil.triggerImmediateForcefulShutdown(ShutdownUtil.java:52) ~[org.apache.pulsar-pulsar-common-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
	at org.apache.pulsar.admin.cli.PulsarAdminTool.exit(PulsarAdminTool.java:309) ~[org.apache.pulsar-pulsar-client-tools-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
	at org.apache.pulsar.admin.cli.PulsarAdminTool.main(PulsarAdminTool.java:300) ~[org.apache.pulsar-pulsar-client-tools-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by eolivelli** [comment]
I believe that this cannot work without ZK, it requires BookKeeper StreamStorage and there are no tests about it without ZK

We should make it easy for people to run standalone with ZK and document this behavior.

**Comment by Technoboy-** [comment]
> I believe that this cannot work without ZK, it requires BookKeeper StreamStorage and there are no tests about it without ZK
> 
> We should make it easy for people to run standalone with ZK and document this behavior.

Decide to tell the users to set the ENV variable to verify the standalone mode.
