### ISSUE TITLE
Flaky-test: NamespacesTest.testSetOffloadThreshold

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#18588]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/3530823792/jobs/5923383857

### Exception stacktrace

```
2022-11-23T10:06:21.6045306Z [ERROR] Tests run: 96, Failures: 1, Errors: 0, Skipped: 70, Time elapsed: 80.822 s <<< FAILURE! - in org.apache.pulsar.broker.admin.NamespacesTest
2022-11-23T10:06:21.6049385Z [ERROR] testSetOffloadThreshold(org.apache.pulsar.broker.admin.NamespacesTest)  Time elapsed: 0.253 s  <<< FAILURE!
2022-11-23T10:06:21.6050494Z java.lang.AssertionError: expected [100] but found [-1]
2022-11-23T10:06:21.6051266Z 	at org.testng.Assert.fail(Assert.java:110)
2022-11-23T10:06:21.6051687Z 	at org.testng.Assert.failNotEquals(Assert.java:1413)
2022-11-23T10:06:21.6052086Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
2022-11-23T10:06:21.6161964Z 	at org.testng.Assert.assertEquals(Assert.java:131)
2022-11-23T10:06:21.6164814Z 	at org.testng.Assert.assertEquals(Assert.java:911)
2022-11-23T10:06:21.6170616Z 	at org.testng.Assert.assertEquals(Assert.java:945)
2022-11-23T10:06:21.6173421Z 	at org.apache.pulsar.broker.admin.NamespacesTest.testSetOffloadThreshold(NamespacesTest.java:1496)
2022-11-23T10:06:21.6176759Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-11-23T10:06:21.6179568Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2022-11-23T10:06:21.6182447Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-11-23T10:06:21.6185918Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2022-11-23T10:06:21.6189100Z 	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
2022-11-23T10:06:21.6192284Z 	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
2022-11-23T10:06:21.6195463Z 	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
2022-11-23T10:06:21.6198382Z 	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
2022-11-23T10:06:21.6201047Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-11-23T10:06:21.6203701Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2022-11-23T10:06:21.6206392Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2022-11-23T10:06:21.6208964Z 	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
another one: https://github.com/apache/pulsar/actions/runs/3539907924/jobs/5943355246#step:10:1285

**Comment by lhotari** [comment]
This seems to be caused by #17875 changes. I'll take a look.
