### ISSUE TITLE
Flaky-test: AdditionalServletsTest.testEmptyStringAsExtractionDirectory

### ISSUE THREAD

**Issue by Technoboy-** [apache/pulsar#18597]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/3530823792/jobs/5937262614

### Exception stacktrace

```
Error:  Tests run: 2, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 0.418 s <<< FAILURE! - in org.apache.pulsar.broker.web.plugin.servlet.AdditionalServletsTest
  Error:  testEmptyStringAsExtractionDirectory(org.apache.pulsar.broker.web.plugin.servlet.AdditionalServletsTest)  Time elapsed: 0.018 s  <<< FAILURE!
  java.lang.NullPointerException: Cannot invoke "org.apache.pulsar.broker.web.plugin.servlet.AdditionalServletDefinitions.servlets()" because "definitions" is null
  	at org.apache.pulsar.broker.web.plugin.servlet.AdditionalServlets.load(AdditionalServlets.java:89)
  	at org.apache.pulsar.broker.web.plugin.servlet.AdditionalServletsTest.testEmptyStringAsExtractionDirectory(AdditionalServletsTest.java:64)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
duplicates #18587
