### ISSUE TITLE
Flaky-test: AdminApiTransactionMultiBrokerTest.testRedirectOfGetCoordinatorInternalStats

### ISSUE THREAD

**Issue by labuladong** [apache/pulsar#18600]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/3539262113/jobs/5941141801#step:10:1363

### Exception stacktrace

<details>
<summary>Full exception stacktrace</summary>
<pre><code>
org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.broker.admin.v3.AdminApiTransactionMultiBrokerTest.testRedirectOfGetCoordinatorInternalStats() didn't finish within the time-out 300000
  	at java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method)
  	at java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
  	at java.base@17.0.4.1/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1866)
  	at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
  	at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
  	at java.base@17.0.4.1/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1939)
  	at java.base@17.0.4.1/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
  	at app//org.apache.pulsar.broker.resources.BaseResources.create(BaseResources.java:128)
  	at app//org.apache.pulsar.broker.resources.NamespaceResources$PartitionedTopicResources.createPartitionedTopic(NamespaceResources.java:243)
  	at app//org.apache.pulsar.broker.admin.v3.AdminApiTransactionMultiBrokerTest.testRedirectOfGetCoordinatorInternalStats(AdminApiTransactionMultiBrokerTest.java:61)
  	at java.base@17.0.4.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base@17.0.4.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base@17.0.4.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base@17.0.4.1/java.lang.reflect.Method.invoke(Method.java:568)
  	at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base@17.0.4.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)
</code></pre>
</details>

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
another one: https://github.com/apache/pulsar/actions/runs/4291253777/jobs/7476432503#step:11:1470
```
  Error:  Tests run: 6, Failures: 1, Errors: 0, Skipped: 5, Time elapsed: 677.453 s <<< FAILURE! - in org.apache.pulsar.broker.admin.v3.AdminApiTransactionMultiBrokerTest
  Error:  testRedirectOfGetCoordinatorInternalStats(org.apache.pulsar.broker.admin.v3.AdminApiTransactionMultiBrokerTest)  Time elapsed: 300.011 s  <<< FAILURE!
  org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.broker.admin.v3.AdminApiTransactionMultiBrokerTest.testRedirectOfGetCoordinatorInternalStats() didn't finish within the time-out 300000
  	at java.base@17.0.6/jdk.internal.misc.Unsafe.park(Native Method)
  	at java.base@17.0.6/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
  	at java.base@17.0.6/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1866)
  	at java.base@17.0.6/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
  	at java.base@17.0.6/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
  	at java.base@17.0.6/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1939)
  	at java.base@17.0.6/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
  	at app//org.apache.pulsar.client.admin.internal.BaseResource.sync(BaseResource.java:342)
  	at app//org.apache.pulsar.client.admin.internal.LookupImpl.lookupPartitionedTopic(LookupImpl.java:65)
  	at app//org.apache.pulsar.broker.admin.v3.AdminApiTransactionMultiBrokerTest.testRedirectOfGetCoordinatorInternalStats(AdminApiTransactionMultiBrokerTest.java:63)
  	at java.base@17.0.6/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base@17.0.6/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base@17.0.6/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base@17.0.6/java.lang.reflect.Method.invoke(Method.java:568)
  	at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base@17.0.6/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base@17.0.6/java.lang.Thread.run(Thread.java:833)
```

**Comment by lhotari** [comment]
@liangyepianzhou this flaky test was introduced by PR #14965. Would you mind fixing this?

**Comment by liangyepianzhou** [comment]
@lhotari I am willing to fix it.

**Comment by liangyepianzhou** [comment]
Closed by https://github.com/apache/pulsar/pull/19715
