### ISSUE TITLE
Flaky-test: TransactionTest.testEndTxnWhenCommittingOrAborting

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#18605]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/3539850595/jobs/5943437683#step:10:826

### Exception stacktrace

```
Error:  Tests run: 97, Failures: 1, Errors: 0, Skipped: 86, Time elapsed: 41.195 s <<< FAILURE! - in org.apache.pulsar.broker.transaction.TransactionTest
  Error:  testEndTxnWhenCommittingOrAborting(org.apache.pulsar.broker.transaction.TransactionTest)  Time elapsed: 0.116 s  <<< FAILURE!
  java.lang.AssertionError: expected [1] but found [0]
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.testng.Assert.failNotEquals(Assert.java:1413)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
  	at org.testng.Assert.assertEquals(Assert.java:131)
  	at org.testng.Assert.assertEquals(Assert.java:1240)
  	at org.testng.Assert.assertEquals(Assert.java:1274)
  	at org.apache.pulsar.broker.transaction.TransactionTest.testEndTxnWhenCommittingOrAborting(TransactionTest.java:926)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:[833](https://github.com/apache/pulsar/actions/runs/3539850595/jobs/5943437683#step:10:834))
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by codelipenghui** [comment]
Another one https://github.com/apache/pulsar/actions/runs/3935861095/jobs/6732032238
@congbobo184 @liangyepianzhou Could you please help take a look?

**Comment by poorbarcode** [comment]
link PR:
- https://github.com/apache/pulsar/pull/18318

**Comment by congbobo184** [comment]
https://github.com/apache/pulsar/pull/18318 has fixed this issue, so close it
