### ISSUE TITLE
Flaky-test: KeySharedSubscriptionTest.testCanRecoverConsumptionWhenLiftMaxUnAckedMessagesRestriction

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#18617]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/3539850595/jobs/5943288285#step:10:592

### Exception stacktrace

```
  Error:  Tests run: 16, Failures: 1, Errors: 0, Skipped: 15, Time elapsed: 45.361 s <<< FAILURE! - in org.apache.pulsar.client.impl.KeySharedSubscriptionTest
  Error:  testCanRecoverConsumptionWhenLiftMaxUnAckedMessagesRestriction(org.apache.pulsar.client.impl.KeySharedSubscriptionTest)  Time elapsed: 15.738 s  <<< FAILURE!
  org.awaitility.core.ConditionTimeoutException: Condition with org.apache.pulsar.client.impl.KeySharedSubscriptionTest was not fulfilled within 10 seconds.
  	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
  	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
  	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
  	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
  	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:954)
  	at org.apache.pulsar.client.impl.KeySharedSubscriptionTest.testCanRecoverConsumptionWhenLiftMaxUnAckedMessagesRestriction(KeySharedSubscriptionTest.java:180)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
@mattisonchao Is this related to #17483? would you be able to take a look?

**Comment by coderzc** [comment]
+1 testCanRecoverConsumptionWhenLiftMaxUnAckedMessagesRestriction

**Comment by labuladong** [comment]
+1

https://github.com/apache/pulsar/actions/runs/3582673357/jobs/6027379286#step:10:590

**Comment by codelipenghui** [comment]
+1

https://github.com/apache/pulsar/actions/runs/3583371268/jobs/6060482792

**Comment by labuladong** [comment]
Assign to me

**Comment by AnonHxy** [comment]
This flaky test still exists  https://github.com/apache/pulsar/actions/runs/5804173763/job/15750864467?pr=20952

**Comment by tuteng** [comment]
> This flaky test still exists https://github.com/apache/pulsar/actions/runs/5804173763/job/15750864467?pr=20952

Please rebase master
