### ISSUE TITLE
Flaky-test: ZKSessionTest.testReacquireLeadershipAfterSessionLost

### ISSUE THREAD

**Issue by lifepuzzlefun** [apache/pulsar#18641]
### Search before asking

- [ ] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

ses below

### Exception stacktrace

see below

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by WJL3333** [comment]
see https://github.com/apache/pulsar/pull/18578/files 
![image](https://user-images.githubusercontent.com/13600283/204096504-c559bdc3-1c1b-48ac-9541-613ad605913d.png)
also this test fail in local environment very often.

**Comment by WJL3333** [comment]
also https://github.com/apache/pulsar/pull/18518/files
![image](https://user-images.githubusercontent.com/13600283/204096954-eacfec40-e8b5-4507-b2ae-d132f4c9bcc2.png)

i dont know how to find the relate CI link.

**Comment by lifepuzzlefun** [comment]
another one  https://github.com/apache/pulsar/pull/18672/files
<img width="1581" alt="image" src="https://user-images.githubusercontent.com/13600283/204719495-cc8d3bb3-1dad-4ab6-8929-495d7499afe4.png">

**Comment by dave2wave** [comment]
This looks like a possible return of #11032

**Comment by lhotari** [comment]
recent failures:

```
java.util.concurrent.CompletionException: org.apache.pulsar.metadata.api.MetadataStoreException: org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:781)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at org.apache.pulsar.metadata.impl.ZKMetadataStore.lambda$batchOperation$4(ZKMetadataStore.java:201)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.apache.pulsar.metadata.impl.ZKMetadataStore.lambda$batchOperation$7(ZKMetadataStore.java:201)
	at org.apache.pulsar.metadata.impl.PulsarZooKeeperClient$3$1.processResult(PulsarZooKeeperClient.java:489)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:714)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:553)
Caused by: org.apache.pulsar.metadata.api.MetadataStoreException: org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired
	at org.apache.pulsar.metadata.impl.ZKMetadataStore.getException(ZKMetadataStore.java:476)
	at org.apache.pulsar.metadata.impl.ZKMetadataStore.lambda$batchOperation$7(ZKMetadataStore.java:200)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.  
[example failure 2023-11-01T16:28:13.4988707Z](https://github.com/apache/pulsar/actions/runs/6722104352/job/18269625331#step:11:1879)  
[example failure 2023-10-29T09:21:00.2103841Z](https://github.com/apache/pulsar/actions/runs/6682361718/job/18157652403#step:10:1917)  


<details>
<summary>Full exception stacktrace</summary>
<code><pre>
java.util.concurrent.CompletionException: org.apache.pulsar.metadata.api.MetadataStoreException: org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:781)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at org.apache.pulsar.metadata.impl.ZKMetadataStore.lambda$batchOperation$4(ZKMetadataStore.java:201)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.apache.pulsar.metadata.impl.ZKMetadataStore.lambda$batchOperation$7(ZKMetadataStore.java:201)
	at org.apache.pulsar.metadata.impl.PulsarZooKeeperClient$3$1.processResult(PulsarZooKeeperClient.java:489)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:714)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:553)
Caused by: org.apache.pulsar.metadata.api.MetadataStoreException: org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired
	at org.apache.pulsar.metadata.impl.ZKMetadataStore.getException(ZKMetadataStore.java:476)
	at org.apache.pulsar.metadata.impl.ZKMetadataStore.lambda$batchOperation$7(ZKMetadataStore.java:200)
	... 3 more
Caused by: org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:134)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
	at org.apache.pulsar.metadata.impl.ZKMetadataStore.getException(ZKMetadataStore.java:466)
	... 4 more

</pre></code>
</details>

**Comment by lifepuzzlefun** [comment]
close for leave project any one can reopen this issue again.
