### ISSUE TITLE
[Bug] NoClassDefFoundError BlobStoreBackedReadHandleImpl

### ISSUE THREAD

**Issue by jpfeltracco** [apache/pulsar#18895]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Red Hat Enterprise Linux 9.0 (Plow) 
Pulsar 2.10.2

### Minimal reproduce step

Follow ansible deployment instructions, unzip offloads into /opt/pulsar/offloaders and set offloadersDirectory="/opt/pulsar/offloaders".

Setup aws-s3 offloading.

### What did you expect to see?

I can both read and write to S3 through offloader.

### What did you see instead?

Writes to S3 work, but reads don't. If I create a consumer or reader starting at earliest message id, my client just hangs. In broker logs I see this "NoClassDefFoundError".

```
[offloader-OrderedScheduler-1-0] ERROR org.apache.bookkeeper.mledger.offload.jcloud.impl.BlobStoreManagedLedgerOffloader - Failed readOffloaded:
 java.lang.NoClassDefFoundError: org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreBackedReadHandleImpl
         at org.apache.bookkeeper.mledger.offload.jcloud.impl.BlobStoreManagedLedgerOffloader.lambda$readOffloaded$3(BlobStoreManagedLedgerOffloader.java:518) ~[?:?]
         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
         at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125) [com.google.guava-guava-30.1-jre.jar:?]
         at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69) [com.google.guava-guava-30.1-jre.jar:?]
         at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78) [com.google.guava-guava-30.1-jre.jar:?]
         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
         at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.77.Final.jar:4.1.77.Final]
         at java.lang.Thread.run(Thread.java:829) [?:?]
 2022-12-12T20:38:57,043+0000 [BookKeeperClientWorker-OrderedExecutor-1-0] ERROR org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - Unknown exception for ManagedLedgerException.
 java.lang.NoClassDefFoundError: org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreBackedReadHandleImpl
         at org.apache.bookkeeper.mledger.offload.jcloud.impl.BlobStoreManagedLedgerOffloader.lambda$readOffloaded$3(BlobStoreManagedLedgerOffloader.java:518) ~[?:?]
         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
         at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125) ~[com.google.guava-guava-30.1-jre.jar:?]
         at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69) ~[com.google.guava-guava-30.1-jre.jar:?]
         at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78) ~[com.google.guava-guava-30.1-jre.jar:?]
         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
         at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.77.Final.jar:4.1.77.Final]
.us-gov-west-1.compute.internal pulsar[49511]:         at java.lang.Thread.run(Thread.java:829) [?:?]

```

### Anything else?

I have the offloaders extracted to /opt/pulsar/offloaders:

-rw-r--r--.  1 root root 88430539 Jan 22  2020 tiered-storage-file-system-2.10.2.nar
-rw-r--r--.  1 root root 74685516 Jan 22  2020 tiered-storage-jcloud-2.10.2.nar

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ethqunzhong** [comment]
it seems load `tiered-storage-jcloud-2.10.2.nar` incorrect.
how about use the default config `offloadersDirectory=offloaders` and unzip offloads into this path then try again. 
<img width="824" alt="image" src="https://user-images.githubusercontent.com/16517186/211014703-f69da387-a945-4fe6-aff2-f0fb42cca0a9.png">

**Comment by tisonkun** [comment]
Interesting, `BlobStoreManagedLedgerOffloader` and `BlobStoreBackedReadHandleImpl` are actually both in the NAR file. Now you can load `BlobStoreManagedLedgerOffloader` but `BlobStoreBackedReadHandleImpl` not found.

Could you try out 2.10.3 version and see if there still the issue? If so, could you share some detailed configure how you actually configure and run the application? It can be a malformed NAR file, or some config to exclude the class on load.

For NAR file completeness, I suggest you check the tarball with checksum file.
