### ISSUE TITLE
[Bug] broker cannot connect the bookie when bookieId set hostname

### ISSUE THREAD

**Issue by liguangcheng** [apache/pulsar#18899]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

2.10.2

### Minimal reproduce step

With zookeeper deployed, bookieId is set to hostname, and the broker cannot connect to bookie

===============================================================
My preliminary analysis is that in the scenario of Zookeeper deployment, the broker should need to use zk to get the IP of Bookie

In the following function, DNS is directly applied to resolve IP, and there is no support for zk
```
public BookieSocketAddress(String addr) throws UnknownHostException {
        String[] parts = addr.split(COLON);
        if (parts.length < 2) {
            throw new UnknownHostException(addr);
        }
        this.hostname = parts[0];

        try {
            this.port = Integer.parseInt(parts[1]);
        } catch (NumberFormatException nfe) {
            throw new UnknownHostException(addr);
        }

        if (InetAddresses.isInetAddress(hostname)) {
            socketAddress = Optional.of(new InetSocketAddress(hostname, port));
        } else {
            socketAddress = Optional.empty();
        }
}
```

### What did you expect to see?

broker should connect the bookie when bookieId set with hostname

### What did you see instead?

N/A

### Anything else?

N/A

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by liguangcheng** [comment]
> add the `ip hostname` config to the /etc/hosts file

yes, this works, I have already tested

But I think that in the deployment mode of zk, the ip should not be obtained through DNS resolve, but should be obtained through zk, this is old feature but missing in the 2.10.2

**Comment by pisceslj** [comment]
The same problem when bookieId set with hostname，zookeeper deployed，k8s environment,  version 2.10.2 

====================================================================================
The error log: 

`[pulsar-registration-client-28-1] ERROR org.apache.bookkeeper.client.TopologyAwareEnsemblePlacementPolicy - Cannot resolve bookieId pulsar-k8s-cluster-bookie-2 to a network address, resolving as /default-region/default-rack
org.apache.bookkeeper.proto.BookieAddressResolver$BookieIdNotResolvedException: Cannot resolve bookieId pulsar-k8s-cluster-bookie-2, bookie does not exist or it is not running
	at org.apache.bookkeeper.client.DefaultBookieAddressResolver.resolve(DefaultBookieAddressResolver.java:68) ~[org.apache.bookkeeper-bookkeeper-server-4.14.5.jar:4.14.5]
	at org.apache.bookkeeper.client.TopologyAwareEnsemblePlacementPolicy.resolveNetworkLocation(TopologyAwareEnsemblePlacementPolicy.java:804) ~[org.apache.bookkeeper-bookkeeper-server-4.14.5.jar:4.14.5]
	at org.apache.bookkeeper.client.TopologyAwareEnsemblePlacementPolicy.createBookieNode(TopologyAwareEnsemblePlacementPolicy.java:794) ~[org.apache.bookkeeper-bookkeeper-server-4.14.5.jar:4.14.5]
	at org.apache.bookkeeper.client.TopologyAwareEnsemblePlacementPolicy.handleBookiesThatJoined(TopologyAwareEnsemblePlacementPolicy.java:718) ~[org.apache.bookkeeper-bookkeeper-server-4.14.5.jar:4.14.5]
	at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl.handleBookiesThatJoined(RackawareEnsemblePlacementPolicyImpl.java:80) ~[org.apache.bookkeeper-bookkeeper-server-4.14.5.jar:4.14.5]
	at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicy.handleBookiesThatJoined(RackawareEnsemblePlacementPolicy.java:249) ~[org.apache.bookkeeper-bookkeeper-server-4.14.5.jar:4.14.5]
	at org.apache.bookkeeper.client.TopologyAwareEnsemblePlacementPolicy.onClusterChanged(TopologyAwareEnsemblePlacementPolicy.java:665) ~[org.apache.bookkeeper-bookkeeper-server-4.14.5.jar:4.14.5]
	at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl.onClusterChanged(RackawareEnsemblePlacementPolicyImpl.java:80) ~[org.apache.bookkeeper-bookkeeper-server-4.14.5.jar:4.14.5]
	at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicy.onClusterChanged(RackawareEnsemblePlacementPolicy.java:92) ~[org.apache.bookkeeper-bookkeeper-server-4.14.5.jar:4.14.5]
	at org.apache.bookkeeper.client.BookieWatcherImpl.processWritableBookiesChanged(BookieWatcherImpl.java:197) ~[org.apache.bookkeeper-bookkeeper-server-4.14.5.jar:4.14.5]
	at org.apache.bookkeeper.client.BookieWatcherImpl.lambda$initialBlockingBookieRead$1(BookieWatcherImpl.java:233) ~[org.apache.bookkeeper-bookkeeper-server-4.14.5.jar:4.14.5]
	at org.apache.pulsar.metadata.bookkeeper.PulsarRegistrationClient.lambda$null$5(PulsarRegistrationClient.java:139) ~[org.apache.pulsar-pulsar-metadata-2.10.2.jar:2.10.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty-netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.net.UnknownHostException: pulsar-k8s-cluster-bookie-2
	at org.apache.bookkeeper.net.BookieSocketAddress.<init>(BookieSocketAddress.java:68) ~[org.apache.bookkeeper-bookkeeper-server-4.14.5.jar:4.14.5]
	at org.apache.bookkeeper.discover.BookieServiceInfoUtils.buildLegacyBookieServiceInfo(BookieServiceInfoUtils.java:40) ~[org.apache.bookkeeper-bookkeeper-server-4.14.5.jar:4.14.5]
	at org.apache.bookkeeper.discover.RegistrationClient.getBookieServiceInfo(RegistrationClient.java:84) ~[org.apache.bookkeeper-bookkeeper-server-4.14.5.jar:4.14.5]
	at org.apache.bookkeeper.client.DefaultBookieAddressResolver.resolve(DefaultBookieAddressResolver.java:43) ~[org.apache.bookkeeper-bookkeeper-server-4.14.5.jar:4.14.5]
	... 18 more`

====================================================================================

it's not convenient and flexible to add the "ip hostname" config to the /etc/hosts file in k8s environment.  The pod's ip maybe   change.

**Comment by Ultranium** [comment]
I experience the same problem with Pulsar 4.0.3 on Docker, set up by the [official guide](https://pulsar.apache.org/docs/4.0.x/getting-started-docker-compose/).

Right after deploying the stack, everything works fine. But when the whole stack gets restarted (for example, on machine reboot), clients fail to connect to the bookie with a timeout, despite all the containers being running.
There are these messages in the bookie container log:
```
2025-03-07T15:54:29,964+0000 [BookKeeperClientScheduler-OrderedScheduler-0-0] INFO  org.apache.bookkeeper.client.DefaultBookieAddressResolver - Cannot resolve bookie:3181, bookie is unknown org.apache.bookkeeper.client.BKException$BKBookieHandleNotAvailableException: Bookie handle is not available
2025-03-07T15:54:29,964+0000 [BookKeeperClientScheduler-OrderedScheduler-0-0] ERROR org.apache.bookkeeper.proto.PerChannelBookieClient - Cannot connect to bookie:3181 as endpoint resolution failed (probably bookie is down) err org.apache.bookkeeper.proto.BookieAddressResolver$BookieIdNotResolvedException: Cannot resolve bookieId bookie:3181, bookie does not exist or it is not running
2025-03-07T15:54:29,964+0000 [BookKeeperClientScheduler-OrderedScheduler-0-0] ERROR org.apache.bookkeeper.proto.PerChannelBookieClient - Could not connect to bookie: null/bookie:3181, current state CONNECTING : 
org.apache.bookkeeper.proto.BookieAddressResolver$BookieIdNotResolvedException: Cannot resolve bookieId bookie:3181, bookie does not exist or it is not running
	at org.apache.bookkeeper.client.DefaultBookieAddressResolver.resolve(DefaultBookieAddressResolver.java:69) ~[org.apache.bookkeeper-bookkeeper-server-4.17.1.jar:4.17.1]
	at org.apache.bookkeeper.proto.PerChannelBookieClient.connect(PerChannelBookieClient.java:541) ~[org.apache.bookkeeper-bookkeeper-server-4.17.1.jar:4.17.1]
	at org.apache.bookkeeper.proto.PerChannelBookieClient.connectIfNeededAndDoOp(PerChannelBookieClient.java:679) ~[org.apache.bookkeeper-bookkeeper-server-4.17.1.jar:4.17.1]
	at org.apache.bookkeeper.proto.DefaultPerChannelBookieClientPool.obtain(DefaultPerChannelBookieClientPool.java:120) ~[org.apache.bookkeeper-bookkeeper-server-4.17.1.jar:4.17.1]
	at org.apache.bookkeeper.proto.DefaultPerChannelBookieClientPool.obtain(DefaultPerChannelBookieClientPool.java:115) ~[org.apache.bookkeeper-bookkeeper-server-4.17.1.jar:4.17.1]
	at org.apache.bookkeeper.proto.BookieClientImpl.readEntry(BookieClientImpl.java:502) ~[org.apache.bookkeeper-bookkeeper-server-4.17.1.jar:4.17.1]
	at org.apache.bookkeeper.proto.BookieClientImpl.readEntry(BookieClientImpl.java:488) ~[org.apache.bookkeeper-bookkeeper-server-4.17.1.jar:4.17.1]
	at org.apache.bookkeeper.proto.BookieClientImpl.readEntry(BookieClientImpl.java:482) ~[org.apache.bookkeeper-bookkeeper-server-4.17.1.jar:4.17.1]
	at org.apache.bookkeeper.client.ReadLastConfirmedOp.initiate(ReadLastConfirmedOp.java:79) ~[org.apache.bookkeeper-bookkeeper-server-4.17.1.jar:4.17.1]
	at org.apache.bookkeeper.client.LedgerHandle.asyncReadPiggybackLastConfirmed(LedgerHandle.java:1710) ~[org.apache.bookkeeper-bookkeeper-server-4.17.1.jar:4.17.1]
	at org.apache.bookkeeper.client.LedgerHandle.asyncReadLastConfirmed(LedgerHandle.java:1673) ~[org.apache.bookkeeper-bookkeeper-server-4.17.1.jar:4.17.1]
	at org.apache.bookkeeper.client.LedgerOpenOp.openWithMetadata(LedgerOpenOp.java:222) ~[org.apache.bookkeeper-bookkeeper-server-4.17.1.jar:4.17.1]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at org.apache.bookkeeper.common.util.SingleThreadSafeScheduledExecutorService$SafeRunnable.run(SingleThreadSafeScheduledExecutorService.java:46) ~[org.apache.bookkeeper-bookkeeper-common-4.17.1.jar:4.17.1]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty-netty-common-4.1.118.Final.jar:4.1.118.Final]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: org.apache.bookkeeper.client.BKException$BKBookieHandleNotAvailableException: Bookie handle is not available
	at org.apache.pulsar.metadata.bookkeeper.PulsarRegistrationClient.getBookieServiceInfo(PulsarRegistrationClient.java:324) ~[org.apache.pulsar-pulsar-metadata-4.0.3.jar:4.0.3]
	at org.apache.bookkeeper.client.DefaultBookieAddressResolver.resolve(DefaultBookieAddressResolver.java:47) ~[org.apache.bookkeeper-bookkeeper-server-4.17.1.jar:4.17.1]
	... 21 more
2025-03-07T15:54:29,964+0000 [BookKeeperClientWorker-OrderedExecutor-1-0] ERROR org.apache.bookkeeper.client.ReadLastConfirmedOp - While readLastConfirmed ledger: 2 did not hear success responses from all quorums, QuorumCoverage(e:1,w:1,a:1) = [-8]
2025-03-07T15:54:29,964+0000 [ReplicationWorker] INFO  org.apache.bookkeeper.replication.ReplicationWorker - BKReadException while rereplicating ledger 2. Enough Bookies might not have available So, no harm to continue
2025-03-07T15:54:29,964+0000 [ReplicationWorker] INFO  org.apache.pulsar.metadata.impl.AbstractMetadataStore - Deleting path: /ledgers/underreplication/locks/urL0000000002 (v. Optional.empty)
2025-03-07T15:54:29,969+0000 [metadata-store-17-1] INFO  org.apache.pulsar.metadata.impl.AbstractMetadataStore - Deleted path: /ledgers/underreplication/locks/urL0000000002 (v. Optional.empty)
2025-03-07T15:54:29,969+0000 [ReplicationWorker] WARN  org.apache.bookkeeper.replication.ReplicationWorker - failed while replicating fragments
```
I successfully pinged bookie by its hostname from within the bookie and the broker containers, so the network and name resolution between containers work just fine.

Restarting the bookie container manually resolves the problem until next reboot.
