### ISSUE TITLE
Flaky-test: ProxyServiceStarterDisableZeroCopyTest.stateCheck

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#19011]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582

### Exception stacktrace

```
Error:  Tests run: 13, Failures: 2, Errors: 0, Skipped: 10, Time elapsed: 9.11 s <<< FAILURE! - in org.apache.pulsar.proxy.server.ProxyServiceStarterDisableZeroCopyTest
[467](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:470)
  Error:  stateCheck(org.apache.pulsar.proxy.server.ProxyServiceStarterDisableZeroCopyTest)  Time elapsed: 5.683 s  <<< FAILURE!
[468](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:471)
  java.lang.IllegalArgumentException: Failed to register Collector of type Gauge: jvm_memory_direct_bytes_used is already in use by another Collector of type Gauge
[469](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:472)
  	at io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:57)
[470](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:473)
  	at io.prometheus.client.Collector.register(Collector.java:307)
[471](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:474)
  	at org.apache.pulsar.proxy.server.ProxyServiceStarter.start(ProxyServiceStarter.java:220)
[472](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:475)
  	at org.apache.pulsar.proxy.server.ProxyServiceStarterDisableZeroCopyTest.setup(ProxyServiceStarterDisableZeroCopyTest.java:38)
[473](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:476)
  	at org.apache.pulsar.tests.TestRetrySupport.stateCheck(TestRetrySupport.java:60)
[474](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:477)
  	at jdk.internal.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
[475](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:478)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[476](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:479)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[477](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:480)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
[478](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:481)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
[479](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:482)
  	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
[480](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:483)
  	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
[481](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:484)
  	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:823)
[482](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:485)
  	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:590)
[483](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:486)
  	at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
[484](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:487)
  	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
[485](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:488)
  	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
[486](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:489)
  	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
[487](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:490)
  	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
[488](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:491)
  	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
[489](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:492)
  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[490](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:493)
  	at org.testng.TestRunner.privateRun(TestRunner.java:829)
[491](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:494)
  	at org.testng.TestRunner.run(TestRunner.java:602)
[492](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:495)
  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
[493](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:496)
  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
[494](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:497)
  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
[495](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:498)
  	at org.testng.SuiteRunner.run(SuiteRunner.java:330)
[496](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:499)
  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[497](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:500)
  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
[498](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:501)
  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
[499](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:502)
  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
[500](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:503)
  	at org.testng.TestNG.runSuites(TestNG.java:1099)
[501](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:504)
  	at org.testng.TestNG.run(TestNG.java:1067)
[502](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:505)
  	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
[503](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:506)
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
[504](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:507)
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeLazy(TestNGDirectoryTestSuite.java:123)
[505](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:508)
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:90)
[506](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:509)
  	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
[507](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:510)
  	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
[508](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:511)
  	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
[509](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:512)
  	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
[510](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:513)
  	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
[511](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:514)
  
[512](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:515)
  Error:  testProduceAndConsumeMessageWithWebsocket(org.apache.pulsar.proxy.server.ProxyServiceStarterDisableZeroCopyTest)  Time elapsed: 0.017 s  <<< FAILURE!
[513](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:516)
  java.lang.NullPointerException: Cannot invoke "String.toLowerCase(java.util.Locale)" because "host" is null
[514](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:517)
  	at org.eclipse.jetty.client.HttpClient.createOrigin(HttpClient.java:560)
[515](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:518)
  	at org.eclipse.jetty.client.HttpClient.resolveDestination(HttpClient.java:550)
[516](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:519)
  	at org.eclipse.jetty.client.HttpClient.send(HttpClient.java:599)
[517](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:520)
  	at org.eclipse.jetty.client.HttpRequest.sendAsync(HttpRequest.java:780)
[518](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:521)
  	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:767)
[519](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:522)
  	at org.eclipse.jetty.websocket.client.WebSocketUpgradeRequest.send(WebSocketUpgradeRequest.java:565)
[520](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:523)
  	at org.eclipse.jetty.websocket.client.WebSocketUpgradeRequest.sendAsync(WebSocketUpgradeRequest.java:570)
[521](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:524)
  	at org.eclipse.jetty.websocket.client.WebSocketClient.connect(WebSocketClient.java:389)
[522](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:525)
  	at org.eclipse.jetty.websocket.client.WebSocketClient.connect(WebSocketClient.java:315)
[523](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:526)
  	at org.eclipse.jetty.websocket.client.WebSocketClient.connect(WebSocketClient.java:301)
[524](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:527)
  	at org.apache.pulsar.proxy.server.ProxyServiceStarterTest.testProduceAndConsumeMessageWithWebsocket(ProxyServiceStarterTest.java:115)
[525](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:528)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[526](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:529)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[527](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:530)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[528](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:531)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[529](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:532)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
[530](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:533)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
[531](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:534)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
[532](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:535)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
[533](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:536)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[534](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:537)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[535](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:538)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[536](https://github.com/apache/pulsar/actions/runs/3737268788/jobs/6360208582#step:10:539)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by gaoran10** [comment]
I'll check this problem.

**Comment by gaoran10** [comment]
The PR https://github.com/apache/pulsar/pull/19062 wants to resolve the collector registry conflict problem when resetting the test environment.
