### ISSUE TITLE
Flaky-test: ResourceGroupUsageAggregationTest.testProduceConsumeUsageOnRG

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#19061]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/3779970439/jobs/6425838234

### Exception stacktrace

```
Error:  Tests run: 6, Failures: 1, Errors: 0, Skipped: 5, Time elapsed: 8.132 s <<< FAILURE! - in org.apache.pulsar.broker.resourcegroup.ResourceGroupUsageAggregationTest
[630](https://github.com/apache/pulsar/actions/runs/3779970439/jobs/6425838234#step:10:631)
  Error:  testProduceConsumeUsageOnRG(org.apache.pulsar.broker.resourcegroup.ResourceGroupUsageAggregationTest)  Time elapsed: 0.185 s  <<< FAILURE!
[631](https://github.com/apache/pulsar/actions/runs/3779970439/jobs/6425838234#step:10:632)
  org.apache.pulsar.client.admin.PulsarAdminException: Resource group does not exist: runProduceConsume
[632](https://github.com/apache/pulsar/actions/runs/3779970439/jobs/6425838234#step:10:633)
  	at org.apache.pulsar.broker.resourcegroup.ResourceGroupService.checkResourceGroupExists(ResourceGroupService.java:417)
[633](https://github.com/apache/pulsar/actions/runs/3779970439/jobs/6425838234#step:10:634)
  	at org.apache.pulsar.broker.resourcegroup.ResourceGroupService.registerTenant(ResourceGroupService.java:196)
[634](https://github.com/apache/pulsar/actions/runs/3779970439/jobs/6425838234#step:10:635)
  	at org.apache.pulsar.broker.resourcegroup.ResourceGroupUsageAggregationTest.testProduceConsumeUsageOnRG(ResourceGroupUsageAggregationTest.java:140)
[635](https://github.com/apache/pulsar/actions/runs/3779970439/jobs/6425838234#step:10:636)
  	at org.apache.pulsar.broker.resourcegroup.ResourceGroupUsageAggregationTest.testProduceConsumeUsageOnRG(ResourceGroupUsageAggregationTest.java:85)
[636](https://github.com/apache/pulsar/actions/runs/3779970439/jobs/6425838234#step:10:637)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[637](https://github.com/apache/pulsar/actions/runs/3779970439/jobs/6425838234#step:10:638)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[638](https://github.com/apache/pulsar/actions/runs/3779970439/jobs/6425838234#step:10:639)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[639](https://github.com/apache/pulsar/actions/runs/3779970439/jobs/6425838234#step:10:640)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[640](https://github.com/apache/pulsar/actions/runs/3779970439/jobs/6425838234#step:10:641)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
[641](https://github.com/apache/pulsar/actions/runs/3779970439/jobs/6425838234#step:10:642)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
[642](https://github.com/apache/pulsar/actions/runs/3779970439/jobs/6425838234#step:10:643)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
[643](https://github.com/apache/pulsar/actions/runs/3779970439/jobs/6425838234#step:10:644)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
[644](https://github.com/apache/pulsar/actions/runs/3779970439/jobs/6425838234#step:10:645)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[645](https://github.com/apache/pulsar/actions/runs/3779970439/jobs/6425838234#step:10:646)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[646](https://github.com/apache/pulsar/actions/runs/3779970439/jobs/6425838234#step:10:647)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[647](https://github.com/apache/pulsar/actions/runs/3779970439/jobs/6425838234#step:10:648)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by poorbarcode** [comment]
another one: https://github.com/apache/pulsar/actions/runs/4370505227/jobs/7651296557
