### ISSUE TITLE
Flaky-test: org.apache.pulsar.broker.admin.AdminApi2Test.testDeleteNamespaceWithTopicPolicies

### ISSUE THREAD

**Issue by lin-zhao** [apache/pulsar#19083]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/lin-zhao/pulsar/actions/runs/3789636139/jobs/6443735442

### Exception stacktrace

<details>
<summary>Full exception stacktrace</summary>
<pre><code>
org.apache.pulsar.client.admin.PulsarAdminException$ServerSideErrorException:
 --- An unexpected error occurred in the server ---

Message: org.apache.zookeeper.KeeperException$NotEmptyException: KeeperErrorCode = Directory not empty for /managed-ledgers/test-tenant/test-ns2/persistent

Stacktrace:

org.apache.pulsar.metadata.api.MetadataStoreException: org.apache.zookeeper.KeeperException$NotEmptyException: KeeperErrorCode = Directory not empty for /managed-ledgers/test-tenant/test-ns2/persistent
        at org.apache.pulsar.metadata.impl.ZKMetadataStore.getException(ZKMetadataStore.java:473)
        at org.apache.pulsar.metadata.impl.ZKMetadataStore.handleDeleteResult(ZKMetadataStore.java:301)
        at org.apache.pulsar.metadata.impl.ZKMetadataStore.lambda$batchOperation$5(ZKMetadataStore.java:213)
        at org.apache.zookeeper.MockZooKeeper.multi(MockZooKeeper.java:1006)
        at org.apache.zookeeper.MockZooKeeperSession.multi(MockZooKeeperSession.java:184)
        at org.apache.pulsar.metadata.impl.ZKMetadataStore.batchOperation(ZKMetadataStore.java:187)
        at org.apache.pulsar.metadata.impl.batching.AbstractBatchedMetadataStore.internalBatchOperation(AbstractBatchedMetadataStore.java:182)
        at org.apache.pulsar.metadata.impl.batching.AbstractBatchedMetadataStore.flush(AbstractBatchedMetadataStore.java:122)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.zookeeper.KeeperException$NotEmptyException: KeeperErrorCode = Directory not empty for /managed-ledgers/test-tenant/test-ns2/persistent
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:132)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
        at org.apache.pulsar.metadata.impl.ZKMetadataStore.getException(ZKMetadataStore.java:463)
        ... 14 more

        at org.apache.pulsar.client.admin.PulsarAdminException.wrap(PulsarAdminException.java:252)
        at org.apache.pulsar.client.admin.internal.BaseResource.sync(BaseResource.java:351)
        at org.apache.pulsar.client.admin.internal.NamespacesImpl.deleteNamespace(NamespacesImpl.java:231)
        at org.apache.pulsar.broker.admin.AdminApi2Test.testDeleteNamespaceWithTopicPolicies(AdminApi2Test.java:1655)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
        at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
        at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
        at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
        at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
        at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.testng.TestRunner.privateRun(TestRunner.java:829)
        at org.testng.TestRunner.run(TestRunner.java:602)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
        at org.testng.SuiteRunner.run(SuiteRunner.java:330)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)</code></pre>
</details>

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
Another with with a different stacktrace. https://github.com/lhotari/pulsar/actions/runs/3941348137/jobs/6743859727#step:11:901
```
  org.apache.pulsar.broker.service.BrokerServiceException$TopicFencedException: Topic is already fenced
  	at org.apache.pulsar.broker.service.persistent.PersistentTopic.delete(PersistentTopic.java:1166)
  	at org.apache.pulsar.broker.service.persistent.PersistentTopic.deleteForcefully(PersistentTopic.java:1137)
  	at org.apache.pulsar.broker.service.BrokerService.deleteTopic(BrokerService.java:1073)
  	at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.lambda$internalDeleteTopicAsync$127(PersistentTopicsBase.java:1117)
```

<details>
<summary>Full exception stacktrace</summary>
<pre><code>
[INFO] Running org.apache.pulsar.broker.admin.AdminApiSchemaTest
  Error:  Tests run: 413, Failures: 1, Errors: 0, Skipped: 392, Time elapsed: 137.262 s <<< FAILURE! - in org.apache.pulsar.broker.admin.AdminApi2Test
  Error:  testDeleteNamespaceWithTopicPolicies(org.apache.pulsar.broker.admin.AdminApi2Test)  Time elapsed: 0.432 s  <<< FAILURE!
  org.apache.pulsar.client.admin.PulsarAdminException$ServerSideErrorException: 
  
   --- An unexpected error occurred in the server ---
  
  Message: Topic is already fenced
  
  Stacktrace:
  
  org.apache.pulsar.broker.service.BrokerServiceException$TopicFencedException: Topic is already fenced
  	at org.apache.pulsar.broker.service.persistent.PersistentTopic.delete(PersistentTopic.java:1166)
  	at org.apache.pulsar.broker.service.persistent.PersistentTopic.deleteForcefully(PersistentTopic.java:1137)
  	at org.apache.pulsar.broker.service.BrokerService.deleteTopic(BrokerService.java:1073)
  	at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.lambda$internalDeleteTopicAsync$127(PersistentTopicsBase.java:1117)
  	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
  	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
  	at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.internalDeleteTopicAsync(PersistentTopicsBase.java:1117)
  	at org.apache.pulsar.broker.admin.v2.PersistentTopics.deleteTopic(PersistentTopics.java:1108)
  	at jdk.internal.reflect.GeneratedMethodAccessor349.invoke(Unknown Source)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
  	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
  	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
  	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:159)
  	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
  	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
  	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
  	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
  	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
  	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
  	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
  	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
  	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
  	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
  	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
  	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
  	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
  	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
  	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
  	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
  	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
  	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
  	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
  	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656)
  	at org.apache.pulsar.broker.web.ResponseHandlerFilter.doFilter(ResponseHandlerFilter.java:67)
  	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
  	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
  	at org.eclipse.jetty.servlets.QoSFilter.doFilter(QoSFilter.java:202)
  	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
  	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
  	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552)
  	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
  	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
  	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
  	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
  	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
  	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
  	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
  	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
  	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
  	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
  	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234)
  	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
  	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:181)
  	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
  	at org.eclipse.jetty.server.Server.handle(Server.java:516)
  	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
  	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
  	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
  	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
  	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
  	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
  	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
  	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
  	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
  	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
  	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
  	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  
  	at org.apache.pulsar.client.admin.PulsarAdminException.wrap(PulsarAdminException.java:252)
  	at org.apache.pulsar.client.admin.internal.BaseResource.sync(BaseResource.java:352)
  	at org.apache.pulsar.client.admin.internal.NamespacesImpl.deleteNamespace(NamespacesImpl.java:231)
  	at org.apache.pulsar.broker.admin.AdminApi2Test.testDeleteNamespaceWithTopicPolicies(AdminApi2Test.java:1655)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  	Suppressed: org.apache.pulsar.client.admin.PulsarAdminException$ServerSideErrorException: 
   --- An unexpected error occurred in the server ---
  
  Message: Topic is already fenced
  
  Stacktrace:
  
  org.apache.pulsar.broker.service.BrokerServiceException$TopicFencedException: Topic is already fenced
  	at org.apache.pulsar.broker.service.persistent.PersistentTopic.delete(PersistentTopic.java:1166)
  	at org.apache.pulsar.broker.service.persistent.PersistentTopic.deleteForcefully(PersistentTopic.java:1137)
  	at org.apache.pulsar.broker.service.BrokerService.deleteTopic(BrokerService.java:1073)
  	at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.lambda$internalDeleteTopicAsync$127(PersistentTopicsBase.java:1117)
  	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
  	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
  	at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.internalDeleteTopicAsync(PersistentTopicsBase.java:1117)
  	at org.apache.pulsar.broker.admin.v2.PersistentTopics.deleteTopic(PersistentTopics.java:1108)
  	at jdk.internal.reflect.GeneratedMethodAccessor349.invoke(Unknown Source)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
  	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
  	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
  	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:159)
  	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
  	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
  	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
  	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
  	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
  	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
  	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
  	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
  	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
  	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
  	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
  	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
  	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
  	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
  	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
  	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
  	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
  	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
  	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
  	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656)
  	at org.apache.pulsar.broker.web.ResponseHandlerFilter.doFilter(ResponseHandlerFilter.java:67)
  	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
  	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
  	at org.eclipse.jetty.servlets.QoSFilter.doFilter(QoSFilter.java:202)
  	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
  	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
  	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552)
  	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
  	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
  	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
  	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
  	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
  	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
  	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
  	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
  	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
  	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
  	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234)
  	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
  	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:181)
  	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
  	at org.eclipse.jetty.server.Server.handle(Server.java:516)
  	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
  	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
  	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
  	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
  	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
  	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
  	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
  	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
  	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
  	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
  	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
  	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  
  		at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:272)
  		at org.apache.pulsar.client.admin.internal.BaseResource$4.failed(BaseResource.java:237)
  		at org.glassfish.jersey.client.JerseyInvocation$1.failed(JerseyInvocation.java:882)
  		at org.glassfish.jersey.client.JerseyInvocation$1.completed(JerseyInvocation.java:863)
  		at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:229)
  		at org.glassfish.jersey.client.ClientRuntime.access$200(ClientRuntime.java:62)
  		at org.glassfish.jersey.client.ClientRuntime$2.lambda$response$0(ClientRuntime.java:173)
  		at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
  		at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
  		at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
  		at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
  		at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
  		at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:288)
  		at org.glassfish.jersey.client.ClientRuntime$2.response(ClientRuntime.java:173)
  		at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$apply$1(AsyncHttpConnector.java:254)
  		at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
  		at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
  		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
  		at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
  		at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$retryOperation$4(AsyncHttpConnector.java:296)
  		at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
  		at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
  		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
  		at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
  		at org.asynchttpclient.netty.NettyResponseFuture.loadContent(NettyResponseFuture.java:222)
  		at org.asynchttpclient.netty.NettyResponseFuture.done(NettyResponseFuture.java:257)
  		at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.finishUpdate(AsyncHttpClientHandler.java:241)
  		at org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:114)
  		at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:143)
  		at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78)
  		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
  		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  		at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
  		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
  		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
  		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
  		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
  		at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
  		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
  		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
  		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
  		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:[919](https://github.com/lhotari/pulsar/actions/runs/3941348137/jobs/6743859727#step:11:920))
  		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
  		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
  		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
  		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
  		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
  		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
  		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  		... 1 more
  		</code></pre>
</details>

**Comment by lhotari** [comment]
another one: https://github.com/apache/pulsar/actions/runs/3986209500/jobs/6834772806#step:11:826

**Comment by codelipenghui** [comment]
another one https://github.com/apache/pulsar/actions/runs/4049485995/jobs/6966062739

**Comment by michaeljmarshall** [comment]
Got this one again: https://github.com/apache/pulsar/actions/runs/4059057719/jobs/6986870824.
