### ISSUE TITLE
 no org_apache_pulsar_shade_netty_tcnative_x86_64 in java.library.path

### ISSUE THREAD

**Issue by tianjingle** [apache/pulsar#19122]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

**Pulsar-cilent 2.10, when I started the project, I got an error.**
`	Caused by: java.io.FileNotFoundException: META-INF/native/org_apache_pulsar_shade_netty_tcnative_x86_64.dll
		at org.apache.pulsar.shade.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:171) ~[pulsar-client-2.10.0.jar:2.10.0]
		... 39 more
		Suppressed: java.lang.UnsatisfiedLinkError: no org_apache_pulsar_shade_netty_tcnative_x86_64 in java.library.path
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867) ~[?:1.8.0_202]
			at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[?:1.8.0_202]
			at java.lang.System.loadLibrary(System.java:1122) ~[?:1.8.0_202]`
**how i could do ? thanks**

### Minimal reproduce step

1. os win10
2. java 8

### What did you expect to see?

no error.

### What did you see instead?

no need

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
@BewareMyPower @merlimat @nicoloboschi do we provide compatibility to run on Win? If we don't maintain it, I'd prefer to close as won't fix or if @tianjingle can provide a patch that doesn't affect other codepath, merge it.

**Comment by BewareMyPower** [comment]
No. But I think we should. The only reason that Pulsar cannot run on Windows is that RocksDB, which is depended by BookKeeper, cannot run on Windows.

I have debugged before and found it might be something wrong with BK that BK does not handle the Windows file path well. So the unit tests that depend on a mocked BK can run well on Windows. I have been working on Windows for several months and the unit tests worked well.

However, the client that does not depend on BK should run well on Windows.
