### ISSUE TITLE
[Bug][io] The Alluxio sink fails to write messages out after the first file rotation

### ISSUE THREAD

**Issue by sekikn** [apache/pulsar#19174]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

OS: Ubuntu 22.04 LTS
Pulsar: master branch (commit id: 9ef54fd012e2f80f4499263f6ac4542b45c5bc15)
Alluxio: 2.7.3

### Minimal reproduce step

Build Pulsar on the master branch and run it with the Alluxio sink:

```
$ git show --shortstat 
commit 9ef54fd012e2f80f4499263f6ac4542b45c5bc15 (HEAD -> master, upstream/master, origin/master, origin/HEAD)
Author: AloysZhang <lofterzhang@gmail.com>
Date:   Tue Jan 10 15:07:29 2023 +0800

    [improve][cli] Expose updateLocalTopicOnly to UpdatePartitionedCmd (#19162)

 1 file changed, 5 insertions(+), 1 deletion(-)
$ ./mvnw clean install -DskipTests

...

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  08:54 min
[INFO] Finished at: 2023-01-10T23:09:54+09:00
[INFO] ------------------------------------------------------------------------
$ mkdir connectors
$ cp pulsar-io/alluxio/target/pulsar-io-alluxio-2.12.0-SNAPSHOT.nar connectors
$ bin/pulsar standalone
```

Download and setup Alluxio:

```
$ curl -sLO https://downloads.alluxio.io/downloads/files/2.7.3/alluxio-2.7.3-bin.tar.gz
$ tar xf alluxio-2.7.3-bin.tar.gz 
$ cd alluxio-2.7.3
$ bin/alluxio-start.sh local SudoMount

...

-----------------------------------------
Starting to monitor all local services.
-----------------------------------------
--- [ OK ] The master service @ sekikn-ThinkCentre-M75q-Gen-2 is in a healthy state.
--- [ OK ] The job_master service @ sekikn-ThinkCentre-M75q-Gen-2 is in a healthy state.
--- [ OK ] The worker service @ sekikn-ThinkCentre-M75q-Gen-2 is in a healthy state.
--- [ OK ] The job_worker service @ sekikn-ThinkCentre-M75q-Gen-2 is in a healthy state.
--- [ OK ] The proxy service @ sekikn-ThinkCentre-M75q-Gen-2 is in a healthy state.
```
```
$ bin/alluxio fs mkdir /pulsar
Successfully created directory /pulsar
$ bin/alluxio fs chmod 777 /pulsar
Changed permission of /pulsar to 777
```

Register the Alluxio sink and ingest more messages than the value of `rotationRecords`. In the example below, 11 messages are ingested while `rotationRecords` is set to 10.

```
$ bin/pulsar-admin sink available-sinks
alluxio
Writes data into Alluxio
----------------------------------------
$ cat ~/alluxio-sink.yml 
configs:
    alluxioMasterHost: "localhost"
    alluxioMasterPort: "19998"
    alluxioDir: "pulsar"
    filePrefix: "TopicA"
    fileExtension: ".txt"
    lineSeparator: "\n"
    rotationRecords: 10
    rotationInterval: "-1"
$ bin/pulsar-admin sinks create --tenant public --namespace default --name alluxio-sink --sink-type alluxio --sink-config-file ~/alluxio-sink.yml --inputs TopicA
Created successfully
$ for i in $(seq 0 10); do bin/pulsar-client produce -m "key-$i" -n 1 TopicA; done
```

### What did you expect to see?

A new temporary file is created on Alluxio.

### What did you see instead?

File creation fails with the following error.

Pulsar:
```
$ cat logs/functions/public/default/alluxio-sink/alluxio-sink-0.log

...

2023-01-10T23:15:41,468+0900 [public/default/alluxio-sink-0] ERROR org.apache.pulsar.io.alluxio.sink.AlluxioSink - Unable to write record to alluxio.
alluxio.exception.FileDoesNotExistException: Path "/pulsar/tmp/c436b01b-2c4c-44b6-9f76-cfa436c55133_tmp.txt" does not exist.
	at alluxio.client.file.BaseFileSystem.rpc(BaseFileSystem.java:575) ~[alluxio-core-client-fs-2.7.3.jar:?]
	at alluxio.client.file.BaseFileSystem.createFile(BaseFileSystem.java:164) ~[alluxio-core-client-fs-2.7.3.jar:?]
	at org.apache.pulsar.io.alluxio.sink.AlluxioSink.createTmpFile(AlluxioSink.java:222) ~[C7-XLukrb504fkTxC3363g/:?]
	at org.apache.pulsar.io.alluxio.sink.AlluxioSink.writeToAlluxio(AlluxioSink.java:198) ~[C7-XLukrb504fkTxC3363g/:?]
	at org.apache.pulsar.io.alluxio.sink.AlluxioSink.write(AlluxioSink.java:137) ~[C7-XLukrb504fkTxC3363g/:?]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.sendOutputMessage(JavaInstanceRunnable.java:429) ~[?:?]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.handleResult(JavaInstanceRunnable.java:391) ~[?:?]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:331) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Alluxio:
```
$ cat logs/master.log

...

2023-01-10 23:16:41,540 WARN  FileSystemMasterClientServiceHandler - Exit (Error): CreateFile: request=path: "/pulsar/tmp/8cbf15f1-35ee-4240-992e-c77dd4befe7c_tmp.txt"
options {
  blockSizeBytes: 67108864
  recursive: false
  mode {
    ownerBits: READ_WRITE
    groupBits: READ
    otherBits: READ
  }
  replicationMax: -1
  replicationMin: 0
  replicationDurable: 1
  writeTier: 0
  writeType: MUST_CACHE
  commonOptions {
    syncIntervalMs: -1
    ttl: -1
    ttlAction: DELETE
    operationId {
      mostSignificantBits: 269283063510748789
      leastSignificantBits: -7374140582089861256
    }
  }
  persistenceWaitTime: 0
}
, Error=alluxio.exception.FileDoesNotExistException: Path "/pulsar/tmp/8cbf15f1-35ee-4240-992e-c77dd4befe7c_tmp.txt" does not exist.
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by sekikn** [comment]
I'm still not sure what is its root cause. Once I figured it out, I'll submit a PR.

**Comment by sekikn** [comment]
Thank you for the advice @tisonkun! I finally figured out the root cause.
Simply put, moving the `optionsBuilder` field to a local variable in the `createTmpFile` method should fix the problem. I'll submit a PR later.

Following your advice, I set Alluxio's log level to DEBUG and got the following error.

```
alluxio.exception.FileDoesNotExistException: Path "/pulsar/tmp/7836e23f-78bc-4d3e-922f-004940749a5f_tmp.txt" does not exist.
        at alluxio.master.file.DefaultFileSystemMaster.checkLoadMetadataOptions(DefaultFileSystemMaster.java:1196)
        at alluxio.master.file.DefaultFileSystemMaster.getFileInfo(DefaultFileSystemMaster.java:870)
        at alluxio.master.file.DefaultFileSystemMaster.createFile(DefaultFileSystemMaster.java:1613)
        at alluxio.master.file.FileSystemMasterClientServiceHandler.lambda$createFile$4(FileSystemMasterClientServiceHandler.java:180)
```

The code in question is https://github.com/Alluxio/alluxio/blob/v2.7.3/core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java#L1613. Entering this route means `isOperationComplete` at L1610 returned `true`, and it indicates the same operation (`createFile` here) is retried again.

Every Alluxio's filesystem operation is tracked by an unique ID if `alluxio.master.filesystem.operation.retry.cache.enabled` is true (enabled by default). But in our `AlluxioSink`, [the builder for CreateFilePOptions, in which the operation ID is stored, is created once in the `open` method](https://github.com/apache/pulsar/blob/master/pulsar-io/alluxio/src/main/java/org/apache/pulsar/io/alluxio/sink/AlluxioSink.java#L117) and reused.
Because the operation ID is generated when the builder is instantiated, the first `createFile` operation is successful,
but the subsequent ones are regerded as the same operation as the first one, since the operation ID is not changed.
So we have to use a new builder object for each `createFile` operation.

**Comment by tisonkun** [comment]
@sekikn Thanks for your detailed investigation! Would you submit a patch? I'm glad to give it a review.

**Comment by tisonkun** [comment]
@sekikn thanks for your report and fix!
