### ISSUE TITLE
pulsar-shell should quit cleanly on EOF character (CTRL-D)

### ISSUE THREAD

**Issue by pgier** [apache/pulsar#19213]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

It's common for command line shells to interpret the EOF (CTRL-D) character as a quit command.  For example `bash` and `python`.   The current behavior of pulsar-shell is to print an exception and then quit.
```
Exception in thread "main" org.jline.reader.EndOfFileException
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:657)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:468)
	at org.apache.pulsar.shell.PulsarShell$1.readLine(PulsarShell.java:280)
	at org.apache.pulsar.shell.PulsarShell.lambda$run$4(PulsarShell.java:398)
	at org.apache.pulsar.shell.PulsarShell.run(PulsarShell.java:410)
	at org.apache.pulsar.shell.PulsarShell.run(PulsarShell.java:221)
	at org.apache.pulsar.shell.PulsarShell.main(PulsarShell.java:210)
Goodbye!
```
Since pulsar-shell is already doing the correct thing by quitting, this should just be done cleanly without the exception.

### Solution

Catch the EOF character and quit with no error.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
```
./bin/pulsar-shell
Using directory: /Users/tison/.pulsar-shell
Welcome to Pulsar shell!
  Service URL: pulsar://localhost:6650/
  Admin URL: http://localhost:8080/

Type help to get started or try the autocompletion (TAB button).
Type exit or quit to end the shell session.

default(localhost)> 
Goodbye!
```

Checked with the current behavior. It seems already fixed.

**Comment by tisonkun** [comment]
I think it's https://github.com/apache/pulsar/pull/17204. But the commit is earlier than your report. So if you encounter this issue with different reproduce steps, please describe in details.
