### ISSUE TITLE
Flaky-test: CompactionReaderImplTest.test

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#19214]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/3904728193/jobs/6671101717#step:11:540

### Exception stacktrace

```
  Error:  Tests run: 6, Failures: 1, Errors: 0, Skipped: 5, Time elapsed: 69.264 s <<< FAILURE! - in org.apache.pulsar.client.impl.CompactionReaderImplTest
  Error:  test(org.apache.pulsar.client.impl.CompactionReaderImplTest)  Time elapsed: 30.238 s  <<< FAILURE!
  java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException$TimeoutException: The subscription __compaction of the topic persistent://my-property/my-ns/my-compact-topic could not get the last message id withing configured timeout
  	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
  	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
  	at org.apache.pulsar.client.impl.CompactionReaderImplTest.test(CompactionReaderImplTest.java:97)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Caused by: org.apache.pulsar.client.api.PulsarClientException$TimeoutException: The subscription __compaction of the topic persistent://my-property/my-ns/my-compact-topic could not get the last message id withing configured timeout
  	at org.apache.pulsar.client.impl.ConsumerImpl.internalGetLastMessageIdAsync(ConsumerImpl.java:2406)
  	at org.apache.pulsar.client.impl.ConsumerImpl.lambda$internalGetLastMessageIdAsync$58(ConsumerImpl.java:2415)
  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  	... 1 more
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
another one:
https://github.com/apache/pulsar/actions/runs/3905696188/jobs/6673192180#step:11:539

**Comment by lhotari** [comment]
@heesung-sn This test seems to be flaky. Do you have a chance to take a look at it? it was added by #18195

**Comment by heesung-sn** [comment]
Ack. will work on this.

**Comment by lhotari** [comment]
thank you @heesung-sn .

I faced yet another one: https://github.com/apache/pulsar/actions/runs/3906374418/jobs/6674698961#step:11:540

**Comment by heesung-sn** [comment]
Raised a PR: https://github.com/apache/pulsar/pull/19222

**Comment by lhotari** [comment]
This problem seems to remain after the PR. https://github.com/apache/pulsar/actions/runs/3918969732/jobs/6699757621#step:11:537 . @heesung-sn Please check

**Comment by heesung-sn** [comment]
@lhotari I see. will work on this.

**Comment by heesung-sn** [comment]
Sorry for this back-and-forth. I couldn't replicate the issue on my local, but we could try this fix too.

Raised another PR:
https://github.com/apache/pulsar/pull/19238
