### ISSUE TITLE
Flaky-test: PersistentTopicsTest.testUnloadTopic

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#19265]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/3944347704/jobs/6750282741

### Exception stacktrace

```
Warning:  Tests run: 154, Failures: 0, Errors: 0, Skipped: 86, Time elapsed: 261.231 s - in org.apache.pulsar.broker.admin.AdminApiTest
[1429](https://github.com/apache/pulsar/actions/runs/3944347704/jobs/6750282741#step:11:1430)
  [INFO] 
[1430](https://github.com/apache/pulsar/actions/runs/3944347704/jobs/6750282741#step:11:1431)
  [INFO] Results:
[1431](https://github.com/apache/pulsar/actions/runs/3944347704/jobs/6750282741#step:11:1432)
  [INFO] 
[1432](https://github.com/apache/pulsar/actions/runs/3944347704/jobs/6750282741#step:11:1433)
  Error:  Failures: 
[1433](https://github.com/apache/pulsar/actions/runs/3944347704/jobs/6750282741#step:11:1434)
  Error:  org.apache.pulsar.broker.admin.PersistentTopicsTest.testUnloadTopic(org.apache.pulsar.broker.admin.PersistentTopicsTest)
[1434](https://github.com/apache/pulsar/actions/runs/3944347704/jobs/6750282741#step:11:1435)
  [INFO]   Run 1: PASS
[1435](https://github.com/apache/pulsar/actions/runs/3944347704/jobs/6750282741#step:11:1436)
  Error:    Run 2: PersistentTopicsTest.testUnloadTopic:737 
[1436](https://github.com/apache/pulsar/actions/runs/3944347704/jobs/6750282741#step:11:1437)
  asyncResponse.resume(<Capturing argument>);
[1437](https://github.com/apache/pulsar/actions/runs/3944347704/jobs/6750282741#step:11:1438)
  Wanted 1 time:
[1438](https://github.com/apache/pulsar/actions/runs/3944347704/jobs/6750282741#step:11:1439)
  -> at org.apache.pulsar.broker.admin.PersistentTopicsTest.testUnloadTopic(PersistentTopicsTest.java:737)
[1439](https://github.com/apache/pulsar/actions/runs/3944347704/jobs/6750282741#step:11:1440)
  But was 2 times:
[1440](https://github.com/apache/pulsar/actions/runs/3944347704/jobs/6750282741#step:11:1441)
  -> at org.apache.pulsar.broker.admin.v2.PersistentTopics.lambda$createNonPartitionedTopic$6(PersistentTopics.java:334)
[1441](https://github.com/apache/pulsar/actions/runs/3944347704/jobs/6750282741#step:11:1442)
  -> at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.lambda$internalUnloadNonPartitionedTopicAsync$119(PersistentTopicsBase.java:1079)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by labuladong** [comment]
Assign to me please
