### ISSUE TITLE
[Bug] Error while producing messages

### ISSUE THREAD

**Issue by zhoudayu123** [apache/pulsar#19269]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

2.10.3， 3 nodes cluster

### Minimal reproduce step

bin/pulsar-client produce my-topic --messages "hello-pulsar"

### What did you expect to see?

send message success

### What did you see instead?

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/51695477/213103137-bde34dd4-0bce-4c17-81b7-2aa391d3bed4.png">
2023-01-18T05:46:22,260+0000 [pulsar-timer-6-1] INFO  org.apache.pulsar.client.impl.ProducerImpl - [my-topic] [pulsar-cluster-zk-0-321] Message send timed out. Failing 1 messages
2023-01-18T05:46:22,264+0000 [main] ERROR org.apache.pulsar.client.cli.PulsarClientTool - Error while producing messages
2023-01-18T05:46:22,264+0000 [main] ERROR org.apache.pulsar.client.cli.PulsarClientTool - The producer pulsar-cluster-zk-0-321 can not send message to the topic my-topic within given timeout : createdAt 30.003 seconds ago, firstSentAt 30.001 seconds ago, lastSentAt 30.001 seconds ago, retryCount 1
org.apache.pulsar.client.api.PulsarClientException$TimeoutException: The producer pulsar-cluster-zk-0-321 can not send message to the topic my-topic within given timeout : createdAt 30.003 seconds ago, firstSentAt 30.001 seconds ago, lastSentAt 30.001 seconds ago, retryCount 1
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:1008) ~[org.apache.pulsar-pulsar-client-api-2.10.3.jar:2.10.3]
	at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.send(TypedMessageBuilderImpl.java:90) ~[org.apache.pulsar-pulsar-client-original-2.10.3.jar:2.10.3]
	at org.apache.pulsar.client.cli.CmdProduce.publish(CmdProduce.java:309) ~[org.apache.pulsar-pulsar-client-tools-2.10.3.jar:2.10.3]
	at org.apache.pulsar.client.cli.CmdProduce.run(CmdProduce.java:241) ~[org.apache.pulsar-pulsar-client-tools-2.10.3.jar:2.10.3]
	at org.apache.pulsar.client.cli.PulsarClientTool.run(PulsarClientTool.java:184) ~[org.apache.pulsar-pulsar-client-tools-2.10.3.jar:2.10.3]
	at org.apache.pulsar.client.cli.PulsarClientTool.main(PulsarClientTool.java:220) ~[org.apache.pulsar-pulsar-client-tools-2.10.3.jar:2.10.3]
2023-01-18T05:46:22,268+0000 [main] INFO  org.apache.pulsar.client.cli.PulsarClientTool - 0 messages successfully produced

### Anything else?

how can i solve this error?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tjiuming** [comment]
Seems your topic name is incorrect, topic name should follow the pattern `persistent/non-persistent://tenant/namespace/topic`.
But, it's also an issue, we need to check the topic name before send.

@codelipenghui Could you please assign this to me?

**Comment by tjiuming** [comment]
Did there are error logs in the broker side?

**Comment by zhoudayu123** [comment]
[pulsar-broker-ip-10-106-45-231.us-west-2.compute.internal.log](https://github.com/apache/pulsar/files/10462843/pulsar-broker-ip-10-106-45-231.us-west-2.compute.internal.log)
i set loadBalancerOverrideBrokerNicSpeedGbps=20,and resatrt brokes.  no errors ,but still can't produce message

**Comment by zhoudayu123** [comment]
the second ec2 broker log is different 
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/51695477/213609112-1a2d4c8b-4294-438d-bd44-9c8443867a3d.png">

**Comment by zhoudayu123** [comment]
wow, the thrid ec2 logs are differt error log .
[pulsar-broker-ip-10-106-45-183.us-west-2.compute.internal.log](https://github.com/apache/pulsar/files/10462925/pulsar-broker-ip-10-106-45-183.us-west-2.compute.internal.log)

**Comment by deadcoden** [comment]
Any solution to this? Getting this intermittently.

**Comment by dao-jun** [comment]
> Any solution to this? Getting this intermittently. Java Client Version: 3.0.4 Server Version: 3.0.4

Try to upgrade broker and client version, I heard this issue in the early 3.0.x releases, it should already fixed
