### ISSUE TITLE
Flaky-test: AdminApiOffloadTest.testSetTopicOffloadPolicies

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#19286]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/3957519115/jobs/6778166020#step:11:918

### Exception stacktrace

```
  Error:  Tests run: 28, Failures: 1, Errors: 0, Skipped: 21, Time elapsed: 23.623 s <<< FAILURE! - in org.apache.pulsar.broker.admin.AdminApiOffloadTest
  Error:  testSetTopicOffloadPolicies(org.apache.pulsar.broker.admin.AdminApiOffloadTest)  Time elapsed: 0.043 s  <<< FAILURE!
  java.lang.AssertionError: expected [300] but found [-1]
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.testng.Assert.failNotEquals(Assert.java:1413)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
  	at org.testng.Assert.assertEquals(Assert.java:131)
  	at org.testng.Assert.assertEquals(Assert.java:911)
  	at org.testng.Assert.assertEquals(Assert.java:945)
  	at org.apache.pulsar.broker.admin.AdminApiOffloadTest.testSetTopicOffloadPolicies(AdminApiOffloadTest.java:310)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
@tjiuming would you like to take a look at this flaky test? It looks like the test was added in PR #18218

**Comment by lhotari** [comment]
This flaky test is an example of eventual consistent behavior of Pulsar metadata.
