### ISSUE TITLE
Flaky-test: ReplicatorTest.testDoNotReplicateSystemTopic

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#19297]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/3965645897/jobs/6795733528#step:11:1096

### Exception stacktrace

```
  Error:  testDoNotReplicateSystemTopic(org.apache.pulsar.broker.service.ReplicatorTest)  Time elapsed: 11.45 s  <<< FAILURE!
  org.apache.pulsar.client.admin.PulsarAdminException$ConflictException: This topic already exists
  	at org.apache.pulsar.client.admin.PulsarAdminException.wrap(PulsarAdminException.java:252)
  	at org.apache.pulsar.client.admin.internal.BaseResource.sync(BaseResource.java:352)
  	at org.apache.pulsar.client.admin.internal.TopicsImpl.createNonPartitionedTopic(TopicsImpl.java:308)
  	at org.apache.pulsar.client.admin.Topics.createNonPartitionedTopic(Topics.java:539)
  	at org.apache.pulsar.broker.service.ReplicatorTest.testDoNotReplicateSystemTopic(ReplicatorTest.java:1499)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  	Suppressed: org.apache.pulsar.client.admin.PulsarAdminException$ConflictException: This topic already exists
  		at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:287)
  		at org.apache.pulsar.client.admin.internal.BaseResource$1.failed(BaseResource.java:136)
  		at org.glassfish.jersey.client.JerseyInvocation$1.failed(JerseyInvocation.java:882)
  		at org.glassfish.jersey.client.JerseyInvocation$1.completed(JerseyInvocation.java:863)
  		at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:229)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
There's also #12774, but the problem seems to be different.

In this case, it looks like there's a race condition in the test itself.

https://github.com/apache/pulsar/blob/3ba6fa8f2f31e7805aad5cb03252ad5c519c10c2/pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java#L1493-L1501

@nicoloboschi can you check this since you added `consumerFromR2` in #18896?

It seems that the problem is that `consumerFromR2` will auto-create the topic in r2 and there's a possibility that r2 creates the topic in r1 when replication starts? That's why the line 1499 could fail with ConflictException?

**Comment by lhotari** [comment]
Another failure: https://github.com/apache/pulsar/actions/runs/3994646219/jobs/6852832582#step:11:1099

**Comment by lhotari** [comment]
...and again https://github.com/apache/pulsar/actions/runs/3994646219/jobs/6855263170#step:11:1100
