### ISSUE TITLE
Flaky-test: TokenOauth2AuthenticatedProducerConsumerTest.testOAuth2TokenRefreshedWithoutReconnect, depends on external service

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#19330]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/4010953903/jobs/6894569493#step:11:607

### Exception stacktrace

```
  Error:  Tests run: 17, Failures: 1, Errors: 0, Skipped: 16, Time elapsed: 71.923 s <<< FAILURE! - in org.apache.pulsar.client.api.TokenOauth2AuthenticatedProducerConsumerTest
  Error:  testOAuth2TokenRefreshedWithoutReconnect(org.apache.pulsar.client.api.TokenOauth2AuthenticatedProducerConsumerTest)  Time elapsed: 10.031 s  <<< FAILURE!
  org.awaitility.core.ConditionTimeoutException: Condition was evaluated in 9 seconds 17 milliseconds which is earlier than expected minimum timeout 10 seconds
  	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:172)
  	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
  	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
  	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
  	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:769)
  	at org.apache.pulsar.client.api.TokenOauth2AuthenticatedProducerConsumerTest.testOAuth2TokenRefreshedWithoutReconnect(TokenOauth2AuthenticatedProducerConsumerTest.java:219)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
There's another severe problem in the test: it connects to an external service. Why?

I think that this should be replaced with a local mock that implements the required HTTP calls. Wiremock is good for that purpose.

**Comment by lhotari** [comment]
It looks like the external service was added in the original PR #7420.
