### ISSUE TITLE
[Bug] [pulsar-function-go] function process `ackInputMessage`  error

### ISSUE THREAD

**Issue by quinniup** [apache/pulsar#19367]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

+ branch: master
+ commit: 785fb82966d0e152e65bd86de0c695ce5d6cf45f

### Minimal reproduce step

1. write function-go code;

2. start function with golang:
```shelll
 ./bin/pulsar-admin functions localrun \
--go ./func-test/publishFunc \
--inputs privatetenant/functions/input-test \
--tenant privatetenant \
--namespace functions \
--output privatetenant/functions/event \
--name test-hello \
--auto-ack true
```

3. when functions receive msg, ack message had panic: `runtime error: invalid memory address or nil pointer dereference`

### What did you expect to see?

Functions normal ack message.

### What did you see instead?

```shell
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xaf9cf3]

goroutine 1 [running]:
github.com/apache/pulsar/pulsar-function-go/pf.(*goInstance).ackInputMessage(0xc000198640, {0xdaefe0, 0xc000186b40})
        /Users/cheneyin/project/intelliJ/github/apache/pulsar/pulsar-function-go/pf/instance.go:395 +0xb3
github.com/apache/pulsar/pulsar-function-go/pf.(*goInstance).processResult(0xc000198640, {0xdaefe0?, 0xc000186b40?}, {0x0?, 0x0?, 0x1?})
        /Users/cheneyin/project/intelliJ/github/apache/pulsar/pulsar-function-go/pf/instance.go:387 +0x1bd
github.com/apache/pulsar/pulsar-function-go/pf.(*goInstance).startFunction(0xc000198640, {0xda5aa0?, 0xc0000afec0?})
        /Users/cheneyin/project/intelliJ/github/apache/pulsar/pulsar-function-go/pf/instance.go:179 +0x4f6
github.com/apache/pulsar/pulsar-function-go/pf.Start({0xb7d020?, 0xcd6c88?})
        /Users/cheneyin/project/intelliJ/github/apache/pulsar/pulsar-function-go/pf/function.go:171 +0x45
main.main()
        /Users/cheneyin/project/intelliJ/github/apache/pulsar/pulsar-function-go/examples/publishFunc/publishFunc.go:53 +0x27
```

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by pocockn** [comment]
I am also seeing this issue on `github.com/apache/pulsar/pulsar-function-go v0.0.0-20230518181313-2ebb3797c3f3`
