### ISSUE TITLE
Flaky-test: InactiveTopicDeleteTest.testDeleteWhenNoSubscriptionsWithMultiConfig

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#19379]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/4057506699/jobs/6983668429#step:11:1137

### Exception stacktrace

```
  Error:  Tests run: 114, Failures: 1, Errors: 0, Skipped: 109, Time elapsed: 44.479 s <<< FAILURE! - in org.apache.pulsar.broker.service.InactiveTopicDeleteTest
  Error:  testDeleteWhenNoSubscriptionsWithMultiConfig(org.apache.pulsar.broker.service.InactiveTopicDeleteTest)  Time elapsed: 7.185 s  <<< FAILURE!
  java.lang.AssertionError: expected [false] but found [true]
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.testng.Assert.failNotEquals(Assert.java:1413)
  	at org.testng.Assert.assertFalse(Assert.java:78)
  	at org.testng.Assert.assertFalse(Assert.java:88)
  	at org.apache.pulsar.broker.service.InactiveTopicDeleteTest.testDeleteWhenNoSubscriptionsWithMultiConfig(InactiveTopicDeleteTest.java:310)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by labuladong** [comment]
Assign to me please. I'll fix it.
