### ISSUE TITLE
Flaky-test: PersistentTopicTest.testGetReplicationClusters

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#19418]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/4081522085/jobs/7035431254#step:11:1138

### Exception stacktrace

```
  Error:  Tests run: 195, Failures: 1, Errors: 0, Skipped: 169, Time elapsed: 8.755 s <<< FAILURE! - in org.apache.pulsar.broker.service.PersistentTopicTest
  Error:  testGetReplicationClusters(org.apache.pulsar.broker.service.PersistentTopicTest)  Time elapsed: 0.055 s  <<< FAILURE!
  java.lang.AssertionError: lists don't have the same size expected [1] but found [0]
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.testng.Assert.failNotEquals(Assert.java:1413)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
  	at org.testng.Assert.assertEquals(Assert.java:131)
  	at org.testng.Assert.assertEquals(Assert.java:1240)
  	at org.testng.Assert.assertEquals(Assert.java:1465)
  	at org.testng.Assert.assertEquals(Assert.java:1441)
  	at org.apache.pulsar.broker.service.PersistentTopicTest.testGetReplicationClusters(PersistentTopicTest.java:2266)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
This fails consistently locally. I think that master branch is currently broken.

**Comment by lhotari** [comment]
My PR #19388 broke this. I'm working on a fix for the test.
