### ISSUE TITLE
Flaky-test: MetadataStoreStatsTest.testMetadataStoreStats

### ISSUE THREAD

**Issue by michaeljmarshall** [apache/pulsar#19456]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/michaeljmarshall/pulsar/actions/runs/4117926823/jobs/7110068497#step:11:1262

### Exception stacktrace

```
   Error:  Tests run: 7, Failures: 1, Errors: 0, Skipped: 5, Time elapsed: 18.502 s <<< FAILURE! - in org.apache.pulsar.broker.stats.MetadataStoreStatsTest
  Error:  testMetadataStoreStats(org.apache.pulsar.broker.stats.MetadataStoreStatsTest)  Time elapsed: 0.735 s  <<< FAILURE!
  java.lang.AssertionError: 
  Assertion failed with metrics:

(omitted metrics)

    expected object to not be null
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.testng.Assert.assertNotNull(Assert.java:1319)
  	at org.apache.pulsar.broker.stats.MetadataStoreStatsTest.testMetadataStoreStats(MetadataStoreStatsTest.java:113)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by niharrathod** [comment]
One more failure : https://github.com/apache/pulsar/actions/runs/4438438090/jobs/7800585599?pr=19842#step:11:2533

**Comment by niharrathod** [comment]
CI test-suit is failing due to this.

Is there anyone working on this issue?  If not, I can give a try.

**Comment by tisonkun** [comment]
@niharrathod are you working on this issue? I can assign it to you if you're still willing to continue :)

**Comment by niharrathod** [comment]
@tisonkun : Actually, I tried to re-produce running unit test locally using below command but I could not re-produce the same.  I didn't work further on this. 

`./build/run_unit_group.sh BROKER_GROUP_1  `

**Comment by tisonkun** [comment]
@niharrathod Yes. This is a flaky test highly possible due to concurrent issue, which is hard to reproduce.

**Comment by tisonkun** [comment]
@niharrathod But I found you open a PR #19842 against this issue, so it's also possible that this case has been fixed?

**Comment by niharrathod** [comment]
@tisonkun : I agree, I was just sharing info :).  

I just looked at it again and I can see, there is fix [PR#19829](https://github.com/apache/pulsar/pull/19829) around the same line(MetadataStoreStatsTest.java:113) where is issue occurred. I am not sure that fixes this or not. You can take a call to close or keep it open in case we see it again. 

I am actually not looking at it as of now. feel free to assign to anyone :)
