### ISSUE TITLE
Flaky-test: MessageChunkingSharedTest.testMultiConsumers

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#19508]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/4169319611/jobs/7217300566

### Exception stacktrace

```
Error:  Tests run: 14, Failures: 1, Errors: 0, Skipped: 12, Time elapsed: 14.557 s <<< FAILURE! - in org.apache.pulsar.client.impl.MessageChunkingSharedTest
[551](https://github.com/apache/pulsar/actions/runs/4169319611/jobs/7217300566#step:11:552)
  Error:  testMultiConsumers(org.apache.pulsar.client.impl.MessageChunkingSharedTest)  Time elapsed: 3.308 s  <<< FAILURE!
[552](https://github.com/apache/pulsar/actions/runs/4169319611/jobs/7217300566#step:11:553)
  org.awaitility.core.ConditionTimeoutException: Condition with org.apache.pulsar.client.impl.MessageChunkingSharedTest was not fulfilled within 3 seconds.
[553](https://github.com/apache/pulsar/actions/runs/4169319611/jobs/7217300566#step:11:554)
  	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
[554](https://github.com/apache/pulsar/actions/runs/4169319611/jobs/7217300566#step:11:555)
  	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
[555](https://github.com/apache/pulsar/actions/runs/4169319611/jobs/7217300566#step:11:556)
  	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
[556](https://github.com/apache/pulsar/actions/runs/4169319611/jobs/7217300566#step:11:557)
  	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
[557](https://github.com/apache/pulsar/actions/runs/4169319611/jobs/7217300566#step:11:558)
  	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:954)
[558](https://github.com/apache/pulsar/actions/runs/4169319611/jobs/7217300566#step:11:559)
  	at org.apache.pulsar.client.impl.MessageChunkingSharedTest.testMultiConsumers(MessageChunkingSharedTest.java:136)
[559](https://github.com/apache/pulsar/actions/runs/4169319611/jobs/7217300566#step:11:560)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[560](https://github.com/apache/pulsar/actions/runs/4169319611/jobs/7217300566#step:11:561)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[561](https://github.com/apache/pulsar/actions/runs/4169319611/jobs/7217300566#step:11:562)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[562](https://github.com/apache/pulsar/actions/runs/4169319611/jobs/7217300566#step:11:563)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[563](https://github.com/apache/pulsar/actions/runs/4169319611/jobs/7217300566#step:11:564)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
[564](https://github.com/apache/pulsar/actions/runs/4169319611/jobs/7217300566#step:11:565)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
[565](https://github.com/apache/pulsar/actions/runs/4169319611/jobs/7217300566#step:11:566)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
[566](https://github.com/apache/pulsar/actions/runs/4169319611/jobs/7217300566#step:11:567)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
[567](https://github.com/apache/pulsar/actions/runs/4169319611/jobs/7217300566#step:11:568)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[568](https://github.com/apache/pulsar/actions/runs/4169319611/jobs/7217300566#step:11:569)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[569](https://github.com/apache/pulsar/actions/runs/4169319611/jobs/7217300566#step:11:570)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[570](https://github.com/apache/pulsar/actions/runs/4169319611/jobs/7217300566#step:11:571)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by labuladong** [comment]
Assign to me please

**Comment by tisonkun** [comment]
Seems no new occurance. Please open a new issue if it comes back.

**Comment by RobertIndie** [comment]
New occurrence: https://github.com/apache/pulsar/actions/runs/6297507751/job/17094944494?pr=21204#step:10:1547
```
  Error:  org.apache.pulsar.client.api.UnloadSubscriptionTest.testMultiConsumer[100, true, 5, Shared, 50](32)  Time elapsed: 8.535 s  <<< FAILURE!
  java.lang.AssertionError: expected [50] but found [54]
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.testng.Assert.failNotEquals(Assert.java:1577)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
  	at org.testng.Assert.assertEquals(Assert.java:131)
  	at org.testng.Assert.assertEquals(Assert.java:1418)
  	at org.testng.Assert.assertEquals(Assert.java:1382)
  	at org.testng.Assert.assertEquals(Assert.java:1428)
  	at org.apache.pulsar.client.api.UnloadSubscriptionTest.testMultiConsumer(UnloadSubscriptionTest.java:184)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by lhotari** [comment]
Another one for UnloadSubscriptionTest.testMultiConsumer(

- [2023-09-25T09:54:27.3975410Z](https://github.com/apache/pulsar/actions/runs/6297507751/job/17094944494#step:9:617) 

```
java.lang.AssertionError: expected [50] but found [54]
	at org.testng.Assert.fail(Assert.java:110)
	at org.testng.Assert.failNotEquals(Assert.java:1577)
	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
	at org.testng.Assert.assertEquals(Assert.java:131)
	at org.testng.Assert.assertEquals(Assert.java:1418)
	at org.testng.Assert.assertEquals(Assert.java:1382)
	at org.testng.Assert.assertEquals(Assert.java:1428)
	at org.apache.pulsar.client.api.UnloadSubscriptionTest.testMultiConsumer(UnloadSubscriptionTest.java:184)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
