### ISSUE TITLE
[Bug] Zookeeper event thread gets deadlocked when resetcursor API is called

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#19536]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

2.10.x , forked version https://github.com/datastax/pulsar/tree/ls210_2.3

### Minimal reproduce step

The exact steps aren't clear. This happens when trying out Flink Pulsar connector. Flink Pulsar connector has a setting `pulsar.source.resetSubscriptionCursor` . The call is in the Flink Pulsar connector [at this location](https://github.com/apache/flink-connector-pulsar/blob/6e5ed0c82aa2bcdffb176ba4fe44d88f03a01df9/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/cursor/CursorPosition.java#L114). This seems to call `/{tenant}/{namespace}/{topic}/subscription/{subName}/resetcursor` API. Calling this API causes a deadlock which results in Zookeeper session expiration.

### What did you expect to see?

No deadlocks.

### What did you see instead?

Zookeeper session dies because the EventThread is blocked

Stack trace
```
"main-EventThread" #17 daemon prio=5 os_prio=0 cpu=1788.73ms elapsed=5176.10s tid=0x00007fa97a581000 nid=0x54 waiting on condition  [0x00007fa8ffbfb000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.16/Native Method)
	- parking to wait for  <0x00000007dbaff838> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.16/LockSupport.java:194)
	at java.util.concurrent.CompletableFuture$Signaller.block(java.base@11.0.16/CompletableFuture.java:1796)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@11.0.16/ForkJoinPool.java:3128)
	at java.util.concurrent.CompletableFuture.waitingGet(java.base@11.0.16/CompletableFuture.java:1823)
	at java.util.concurrent.CompletableFuture.get(java.base@11.0.16/CompletableFuture.java:1998)
	at org.apache.pulsar.broker.admin.AdminResource.fetchPartitionedTopicMetadata(AdminResource.java:492)
	at org.apache.pulsar.broker.admin.AdminResource.getPartitionedTopicMetadata(AdminResource.java:480)
	at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.lambda$internalResetCursorOnPosition$212(PersistentTopicsBase.java:2595)
	at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase$$Lambda$1475/0x0000000840b46840.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(java.base@11.0.16/CompletableFuture.java:714)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@11.0.16/CompletableFuture.java:506)
	at java.util.concurrent.CompletableFuture.complete(java.base@11.0.16/CompletableFuture.java:2073)
	at org.apache.pulsar.broker.web.PulsarWebResource.lambda$checkLocalOrGetPeerReplicationCluster$21(PulsarWebResource.java:859)
	at org.apache.pulsar.broker.web.PulsarWebResource$$Lambda$1135/0x000000084096fc40.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(java.base@11.0.16/CompletableFuture.java:714)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@11.0.16/CompletableFuture.java:506)
	at java.util.concurrent.CompletableFuture.complete(java.base@11.0.16/CompletableFuture.java:2073)
	at org.apache.pulsar.metadata.impl.ZKMetadataStore.handleGetResult(ZKMetadataStore.java:244)
	at org.apache.pulsar.metadata.impl.ZKMetadataStore.lambda$batchOperation$7(ZKMetadataStore.java:188)
	at org.apache.pulsar.metadata.impl.ZKMetadataStore$$Lambda$177/0x00000008402da040.processResult(Unknown Source)
	at org.apache.pulsar.metadata.impl.PulsarZooKeeperClient$3$1.processResult(PulsarZooKeeperClient.java:490)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:712)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:553)
   Locked ownable synchronizers:
	- None
```
(line numbers for https://github.com/datastax/pulsar/tree/ls210_2.3)

### Anything else?

This issue is already fixed for master branch as a side effect of #19015. The PR commit has also been cherry-picked to branch-2.11 . This PR doesn't apply cleanly to branch-2.10 and a separate fix will be needed for branch-2.10.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by shy-share** [comment]
@lhotari this issue shoud be closed.Because relative pr had merged;
