### ISSUE TITLE
Flaky-test: SegmentAbortedTxnProcessorTest.testClearSnapshotSegments

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#19650]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/4282039327/jobs/7455965414#step:11:1147

### Exception stacktrace

```
  Error:  Tests run: 15, Failures: 1, Errors: 0, Skipped: 14, Time elapsed: 37.063 s <<< FAILURE! - in org.apache.pulsar.broker.transaction.SegmentAbortedTxnProcessorTest
  Error:  testClearSnapshotSegments(org.apache.pulsar.broker.transaction.SegmentAbortedTxnProcessorTest)  Time elapsed: 10.097 s  <<< FAILURE!
  org.testcontainers.shaded.org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a org.apache.pulsar.broker.transaction.SegmentAbortedTxnProcessorTest expected [2] but found [1] within 10 seconds.
  	at org.testcontainers.shaded.org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
  	at org.testcontainers.shaded.org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
  	at org.testcontainers.shaded.org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
  	at org.testcontainers.shaded.org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
  	at org.testcontainers.shaded.org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:769)
  	at org.apache.pulsar.broker.transaction.SegmentAbortedTxnProcessorTest.testClearSnapshotSegments(SegmentAbortedTxnProcessorTest.java:196)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Caused by: java.lang.AssertionError: expected [2] but found [1]
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.testng.Assert.failNotEquals(Assert.java:1413)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
  	at org.testng.Assert.assertEquals(Assert.java:131)
  	at org.testng.Assert.assertEquals(Assert.java:1240)
  	at org.testng.Assert.assertEquals(Assert.java:1274)
  	at org.apache.pulsar.broker.transaction.SegmentAbortedTxnProcessorTest.verifySnapshotSegmentsSize(SegmentAbortedTxnProcessorTest.java:251)
  	at org.apache.pulsar.broker.transaction.SegmentAbortedTxnProcessorTest.lambda$testClearSnapshotSegments$3(SegmentAbortedTxnProcessorTest.java:196)
  	at org.testcontainers.shaded.org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
  	at org.testcontainers.shaded.org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
  	at org.testcontainers.shaded.org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
  	... 4 more
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
@liangyepianzhou would you be able to fix this flaky test? it was introduced by your PR #18273. Thanks!

**Comment by lhotari** [comment]
[more recent](https://github.com/apache/pulsar/actions/runs/18463783817/job/52601614654?pr=24840#step:11:612):
```
  Error:  Tests run: 18, Failures: 1, Errors: 0, Skipped: 17, Time elapsed: 43.65 s <<< FAILURE! -- in org.apache.pulsar.broker.transaction.SegmentAbortedTxnProcessorTest
  Error:  org.apache.pulsar.broker.transaction.SegmentAbortedTxnProcessorTest.testClearSnapshotSegments -- Time elapsed: 10.04 s <<< FAILURE!
  org.awaitility.core.ConditionTimeoutException: Assertion condition expected:<1> but was:<2> within 10 seconds.
  	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
  	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
  	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
  	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
  	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:769)
  	at org.apache.pulsar.broker.transaction.SegmentAbortedTxnProcessorTest.testClearSnapshotSegments(SegmentAbortedTxnProcessorTest.java:221)
  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  	at java.base/java.lang.Thread.run(Thread.java:1583)
  Caused by: java.lang.AssertionError: expected:<1> but was:<2>
  	at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
  	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:467)
  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:318)
  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:328)
  	at org.apache.pulsar.broker.transaction.SegmentAbortedTxnProcessorTest.verifySnapshotSegmentsSize(SegmentAbortedTxnProcessorTest.java:358)
  	at org.apache.pulsar.broker.transaction.SegmentAbortedTxnProcessorTest.lambda$testClearSnapshotSegments$3(SegmentAbortedTxnProcessorTest.java:221)
  	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
  	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
  	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
  	... 4 more
```
