### ISSUE TITLE
Flaky-test: BucketDelayedDeliveryTrackerTest. testWithBkException

### ISSUE THREAD

**Issue by Demogorgon314** [apache/pulsar#19720]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/4339230785/jobs/7579423655#step:11:1190

### Exception stacktrace

```
  Error:  Tests run: 28, Failures: 1, Errors: 0, Skipped: 7, Time elapsed: 6.132 s <<< FAILURE! - in org.apache.pulsar.broker.delayed.bucket.BucketDelayedDeliveryTrackerTest
  Error:  testWithBkException(org.apache.pulsar.broker.delayed.bucket.BucketDelayedDeliveryTrackerTest)  Time elapsed: 0.035 s  <<< FAILURE!
  java.lang.AssertionError: expected [14] but found [10]
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.testng.Assert.failNotEquals(Assert.java:1413)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
  	at org.testng.Assert.assertEquals(Assert.java:131)
  	at org.testng.Assert.assertEquals(Assert.java:1240)
  	at org.testng.Assert.assertEquals(Assert.java:1274)
  	at org.apache.pulsar.broker.delayed.bucket.BucketDelayedDeliveryTrackerTest.testWithBkException(BucketDelayedDeliveryTrackerTest.java:313)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by poorbarcode** [comment]
another one: https://github.com/apache/pulsar/actions/runs/4355740128/jobs/7613004633

**Comment by poorbarcode** [comment]
another one: https://github.com/apache/pulsar/actions/runs/4355740128/jobs/7628669248
