### ISSUE TITLE
Flaky-test: ExtensibleLoadManagerImplTest.testSplitBundleAdminAPI

### ISSUE THREAD

**Issue by coderzc** [apache/pulsar#19908]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/4496824499/jobs/7912653752?pr=19899#step:11:1584

### Exception stacktrace

```
  Error:  testSplitBundleAdminAPI(org.apache.pulsar.broker.loadbalance.extensions.ExtensibleLoadManagerImplTest)  Time elapsed: 0 s  <<< FAILURE!
  java.lang.NullPointerException: Cannot invoke "org.apache.pulsar.client.admin.PulsarAdmin.topics()" because "this.admin" is null
  	at org.apache.pulsar.broker.loadbalance.extensions.ExtensibleLoadManagerImplTest.testSplitBundleAdminAPI(ExtensibleLoadManagerImplTest.java:380)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by devinbost** [comment]
Also hitting this issue. Seems related to the split bundle issues have have been coming up in the mailing list threads.

**Comment by devinbost** [comment]
I hit this again. This time, I just got this output from the CI:
  Error:  org.apache.pulsar.broker.loadbalance.extensions.ExtensibleLoadManagerImplTest.testSplitBundleAdminAPI(org.apache.pulsar.broker.loadbalance.extensions.ExtensibleLoadManagerImplTest)
  [INFO]   Run 1: PASS
  Error:    Run 2: ExtensibleLoadManagerImplTest.testSplitBundleAdminAPI:380 NullPointer Cannot i...

https://pipelines.actions.githubusercontent.com/serviceHosts/1e11ea78-7103-4d16-8bd8-700e92a4654d/_apis/pipelines/1/runs/130/signedlogcontent/32?urlExpires=2023-03-31T10%3A44%3A30.8944325Z&urlSigningMethod=HMACV1&urlSignature=3oZB7lcjHEKp6oSpe%2BcWIG%2B30rRZkAUs5Bw%2FolW2gxU%3D

**Comment by michaeljmarshall** [comment]
Another example: https://github.com/michaeljmarshall/pulsar/actions/runs/5870146353/job/15916990299?pr=55

```
  Error:  org.apache.pulsar.broker.loadbalance.extensions.ExtensibleLoadManagerImplTest.testSplitBundleAdminAPI  Time elapsed: 0.185 s  <<< FAILURE!
  java.lang.AssertionError: expected [2] but found [1]
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.testng.Assert.failNotEquals(Assert.java:1577)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
  	at org.testng.Assert.assertEquals(Assert.java:131)
  	at org.testng.Assert.assertEquals(Assert.java:1418)
  	at org.testng.Assert.assertEquals(Assert.java:1382)
  	at org.testng.Assert.assertEquals(Assert.java:1428)
  	at org.apache.pulsar.broker.loadbalance.extensions.ExtensibleLoadManagerImplTest.testSplitBundleAdminAPI(ExtensibleLoadManagerImplTest.java:431)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by michaeljmarshall** [comment]
https://github.com/apache/pulsar/actions/runs/5872509170/job/15924697050#step:12:29109

Hit this again. @heesung-sn would you know who might be able to help on this one? Thanks!

**Comment by heesung-sn** [comment]
Hi, sorry for this failures. I will take a look at this tmr. Thanks.

**Comment by heesung-sn** [comment]
Observed this error : https://github.com/apache/pulsar/actions/runs/5872509170/job/15924697050#step:12:29109

 Error:  Tests run: 17, Failures: 1, Errors: 0, Skipped: 12, Time elapsed: 766.346 s <<< FAILURE! - in TestSuite
  Error:  org.apache.pulsar.tests.integration.loadbalance.ExtensibleLoadManagerTest.testSplitBundleAdminApi  Time elapsed: 0.821 s  <<< FAILURE!
  java.lang.AssertionError: expected [101] but found [100]
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.testng.Assert.failNotEquals(Assert.java:1577)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
  	at org.testng.Assert.assertEquals(Assert.java:131)
  	at org.testng.Assert.assertEquals(Assert.java:1418)
  	at org.testng.Assert.assertEquals(Assert.java:1382)
  	at org.testng.Assert.assertEquals(Assert.java:1428)
  	at org.apache.pulsar.tests.integration.loadbalance.ExtensibleLoadManagerTest.testSplitBundleAdminApi(ExtensibleLoadManagerTest.java:214)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  
  [INFO] 
  [INFO] Results:
  [INFO] 
  Error:  Failures: 
  Error:  org.apache.pulsar.tests.integration.loadbalance.ExtensibleLoadManagerTest.testSplitBundleAdminApi
  [INFO]   Run 1: PASS
  Error:    Run 2: ExtensibleLoadManagerTest.testSplitBundleAdminApi:214 expected [101] but found [100]
  [INFO] 
  [INFO] 
  Error:  Tests run: 10, Failures: 1, Errors: 0, Skipped: 5

**Comment by poorbarcode** [comment]
Another case: https://github.com/apache/pulsar/actions/runs/5887661028/job/15968042877?pr=20958

**Comment by heesung-sn** [comment]
failure from
`Another case: https://github.com/apache/pulsar/actions/runs/5887661028/job/15968042877?pr=20958`


2023-08-17T07:29:59.1477574Z [ERROR] org.apache.pulsar.tests.integration.loadbalance.ExtensibleLoadManagerTest.testSplitBundleAdminApi  Time elapsed: 1.259 s  <<< FAILURE!
2023-08-17T07:29:59.1478551Z java.lang.AssertionError: expected [101] but found [100]
2023-08-17T07:29:59.1479021Z    at org.testng.Assert.fail(Assert.java:110)
2023-08-17T07:29:59.1479486Z    at org.testng.Assert.failNotEquals(Assert.java:1577)
2023-08-17T07:29:59.1480045Z    at org.testng.Assert.assertEqualsImpl(Assert.java:149)
2023-08-17T07:29:59.1480841Z    at org.testng.Assert.assertEquals(Assert.java:131)
2023-08-17T07:29:59.1491309Z    at org.testng.Assert.assertEquals(Assert.java:1418)
2023-08-17T07:29:59.1491721Z    at org.testng.Assert.assertEquals(Assert.java:1382)
2023-08-17T07:29:59.1492059Z    at org.testng.Assert.assertEquals(Assert.java:1428)
2023-08-17T07:29:59.1492972Z    at org.apache.pulsar.tests.integration.loadbalance.ExtensibleLoadManagerTest.testSplitBundleAdminApi(ExtensibleLoadManagerTest.java:214)
2023-08-17T07:29:59.1493662Z    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-08-17T07:29:59.1494185Z    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-08-17T07:29:59.1494757Z    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-08-17T07:29:59.1495236Z    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-08-17T07:29:59.1495708Z    at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
2023-08-17T07:29:59.1496267Z    at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
2023-08-17T07:29:59.1496780Z    at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
2023-08-17T07:29:59.1497355Z    at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
2023-08-17T07:29:59.1497799Z    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-08-17T07:29:59.1498253Z    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-08-17T07:29:59.1498740Z    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-08-17T07:29:59.1499116Z    at java.base/java.lang.Thread.run(Thread.java:833)
2023-08-17T07:29:59.1499296Z

**Comment by heesung-sn** [comment]
Raised a fix PR : https://github.com/apache/pulsar/pull/21019
