### ISSUE TITLE
Flaky-test: LeaderElectionImplTest.validateDeadLock

### ISSUE THREAD

**Issue by michaeljmarshall** [apache/pulsar#20308]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/4949638662/jobs/8852414583?pr=20297#step:10:1573

### Exception stacktrace

```
  Error:  Tests run: 9, Failures: 1, Errors: 0, Skipped: 5, Time elapsed: 19.697 s <<< FAILURE! - in org.apache.pulsar.metadata.coordination.impl.LeaderElectionImplTest
  Error:  org.apache.pulsar.metadata.coordination.impl.LeaderElectionImplTest.validateDeadLock[Etcd, org.apache.pulsar.metadata.BaseMetadataStoreTest$$Lambda$379/0x00000008013a5888@6dc9da2d](10)  Time elapsed: 0.007 s  <<< FAILURE!
  java.lang.IllegalStateException: Mapped port can only be obtained after the container is started
  	at org.testcontainers.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:174)
  	at org.testcontainers.containers.ContainerState.getMappedPort(ContainerState.java:149)
  	at io.etcd.jetcd.launcher.EtcdContainer.clientEndpoint(EtcdContainer.java:201)
  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
  	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
  	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
  	at io.etcd.jetcd.launcher.EtcdClusterFactory$2.getClientEndpoints(EtcdClusterFactory.java:112)
  	at org.apache.pulsar.metadata.BaseMetadataStoreTest.getEtcdClusterConnectString(BaseMetadataStoreTest.java:90)
  	at org.apache.pulsar.metadata.BaseMetadataStoreTest.lambda$implementations$3(BaseMetadataStoreTest.java:81)
  	at org.apache.pulsar.metadata.coordination.impl.LeaderElectionImplTest.validateDeadLock(LeaderElectionImplTest.java:41)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by michaeljmarshall** [comment]
Looks like the problem is with this code:

https://github.com/apache/pulsar/blob/82237d3684fe506bcb6426b3b23f413422e6e4fb/pulsar-metadata/src/test/java/org/apache/pulsar/metadata/BaseMetadataStoreTest.java#L85-L91

The `start` method looks like it blocks until the container is started, so it is odd that to me that it is failing.

**Comment by michaeljmarshall** [comment]
This does appear to be an etcd library issue, as documented here: https://github.com/etcd-io/jetcd/issues/1081. The commit is in 0.7.3. We're using 0.5.11. We should look into upgrading the dependency.
