### ISSUE TITLE
[Bug] pulsar-admin shows confusing warning when called without any commands and arguments

### ISSUE THREAD

**Issue by visortelle** [apache/pulsar#20497]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

3.0.0

### Minimal reproduce step

Run `pulsar-admin`

### What did you expect to see?

List of available commands without any warning messages.

### What did you see instead?

```
pulsar-admin                                                                                                                                                                  <aws:pulsar-developer>
Usage: pulsar-admin [options] [command] [command options]
  Options:
    --admin-url
      Admin Service URL to which to connect.
      Default: http://localhost:8080/
    --auth-params
      Authentication parameters, whose format is determined by the
      implementation of method `configure` in authentication plugin class, for
      example "key1:val1,key2:val2" or "{"key1":"val1","key2":"val2"}".
      Default: <empty string>
    --auth-plugin
      Authentication plugin class name.
      Default: <empty string>
    -h, --help
      Show this help.
    --request-timeout
      Request time out in seconds for the pulsar admin client for any request
      Default: 300
    --tls-allow-insecure
      Allow TLS insecure connection
    --tls-enable-hostname-verification
      Enable TLS common name verification
    --tls-provider
      Set up TLS provider. When TLS authentication with CACert is used, the
      valid value is either OPENSSL or JDK. When TLS authentication with
      KeyStore is used, available options can be SunJSSE, Conscrypt and so on.
      Default: <empty string>
    --tls-trust-cert-path
      Allow TLS trust cert file path
    -v, --version
      Get version of pulsar admin client
      Default: false
  Commands:
    brokers      Operations about brokers
      Usage: brokers [options]

    functions      Interface for managing Pulsar Functions (lightweight,
            Lambda-style compute processes that work with Pulsar)
      Usage: functions [options]

    sources(source)      Interface for managing Pulsar IO Sources (ingress
            data into Pulsar)
      Usage: sources(source) [options]

    sinks(sink)      Interface for managing Pulsar IO sinks (egress data from
            Pulsar)
      Usage: sinks(sink) [options]

    documents      Generate documents automatically.
      Usage: documents [options]

    resource-quotas      Operations about resource quotas
      Usage: resource-quotas [options]

    ns-isolation-policy      Operations about namespace isolation policy
      Usage: ns-isolation-policy [options]

    bookies      Operations about bookies rack placement
      Usage: bookies [options]

    broker-stats      Operations to collect broker statistics
      Usage: broker-stats [options]

    functions-worker      Operations to collect function-worker statistics
      Usage: functions-worker [options]

    clusters      Operations about clusters
      Usage: clusters [options]

    tenants      Operations about tenants
      Usage: tenants [options]

    topicPolicies      Operations on persistent topics
      Usage: topicPolicies [options]

    proxy-stats      Operations to collect Proxy statistics
      Usage: proxy-stats [options]

    topics      Operations on persistent topics
      Usage: topics [options]

    packages      Operations about packages
      Usage: packages [options]

    transactions      Operations on transactions
      Usage: transactions [options]

    schemas      Operations about schemas
      Usage: schemas [options]

    resourcegroups      Operations about ResourceGroups
      Usage: resourcegroups [options]

    namespaces      Operations about namespaces
      Usage: namespaces [options]


2023-06-05T18:35:34,355+0200 [main] WARN  org.apache.pulsar.common.util.ShutdownUtil - Triggering immediate shutdown of current process with status 1
java.lang.Exception: Stacktrace for immediate shutdown
	at org.apache.pulsar.common.util.ShutdownUtil.triggerImmediateForcefulShutdown(ShutdownUtil.java:52) ~[org.apache.pulsar-pulsar-common-3.0.0.jar:3.0.0]
	at org.apache.pulsar.admin.cli.PulsarAdminTool.exit(PulsarAdminTool.java:315) ~[org.apache.pulsar-pulsar-client-tools-3.0.0.jar:3.0.0]
	at org.apache.pulsar.admin.cli.PulsarAdminTool.execute(PulsarAdminTool.java:305) ~[org.apache.pulsar-pulsar-client-tools-3.0.0.jar:3.0.0]
	at org.apache.pulsar.admin.cli.PulsarAdminTool.main(PulsarAdminTool.java:280) ~[org.apache.pulsar-pulsar-client-tools-3.0.0.jar:3.0.0]
```

### Anything else?

I see that there are some similar issues like: 

https://github.com/apache/pulsar/issues/17761
https://github.com/apache/pulsar/pull/17589

But pulsar-admin `v2.11.0` at the same machine doesn't show any warnings.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Should be fixed by https://github.com/apache/pulsar/pull/19884.
