### ISSUE TITLE
Flaky-test: SimpleProducerConsumerStatTest.testMsgRateExpired

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#20615]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/5318677656/jobs/9630529043?pr=20609#step:10:785

### Exception stacktrace

```
  Error:  org.apache.pulsar.client.api.SimpleProducerConsumerStatTest.testMsgRateExpired  Time elapsed: 7.346 s  <<< FAILURE!
  org.awaitility.core.ConditionTimeoutException: Condition with org.apache.pulsar.client.api.SimpleProducerConsumerStatTest was not fulfilled within 5 seconds.
  	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
  	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
  	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
  	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
  	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:954)
  	at org.apache.pulsar.client.api.SimpleProducerConsumerStatTest.testMsgRateExpired(SimpleProducerConsumerStatTest.java:549)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
It looks like this test was introduced in #19759. @massakam would you be able to take a look? thanks
