### ISSUE TITLE
[Bug] pulsar-proxy: error Uncaught exception in thread main: Failed to start HTTP server on ports [80]

### ISSUE THREAD

**Issue by hueifeng** [apache/pulsar#20636]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

apachepulsar/pulsar-all:2.10.2

### Minimal reproduce step

Use in Kubernetes https://github.com/apache/pulsar-helm-chart

### What did you expect to see?

pulsar-proxy It should start normally

### What did you see instead?

error Uncaught exception in thread main: Failed to start HTTP server on ports [80]

### Anything else?

log
```
[conf/proxy.conf] Applying config brokerServiceURL = pulsar://pulsar-y72p4h-broker:6650

 [conf/proxy.conf] Applying config brokerWebServiceURL = http://pulsar-y72p4h-broker:8080

 [conf/proxy.conf] Applying config clusterName = pulsar-y72p4h

 [conf/proxy.conf] Applying config httpNumThreads = 8

 [conf/proxy.conf] Applying config servicePort = 6650

 [conf/proxy.conf] Applying config statusFilePath = /pulsar/status

 [conf/proxy.conf] Applying config webServicePort = 80

 WARNING: An illegal reflective access operation has occurred

 WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/pulsar/lib/io.netty-netty-common-4.1.77.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)

 WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil

 WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations

 WARNING: All illegal access operations will be denied in a future release

 2023-06-24T14:05:41,112+0000 [main] INFO  org.apache.pulsar.broker.authentication.AuthenticationService - Authentication is disabled

 2023-06-24T14:05:41,452+0000 [main] INFO  org.apache.pulsar.proxy.extensions.ProxyExtensionsUtils - Searching for extensions in /pulsar/./proxyextensions

 2023-06-24T14:05:41,453+0000 [main] WARN  org.apache.pulsar.proxy.extensions.ProxyExtensionsUtils - extension directory not found

 2023-06-24T14:05:41,500+0000 [main] INFO  org.eclipse.jetty.util.log - Logging initialized @2327ms to org.eclipse.jetty.util.log.Slf4jLog

 2023-06-24T14:05:41,658+0000 [main] INFO  org.apache.pulsar.proxy.server.ProxyService - Started Pulsar Proxy at /0.0.0.0:6650

 2023-06-24T14:05:41,998+0000 [main] INFO  org.eclipse.jetty.server.Server - jetty-9.4.48.v20220622; built: 2022-06-21T20:42:25.880Z; git: 6b67c5719d1f4371b33655ff2d047d24e171e49a; jvm 11.0.16+8-post-Ubuntu-0ubuntu120.04

 2023-06-24T14:05:42,073+0000 [main] INFO  org.eclipse.jetty.server.session - DefaultSessionIdManager workerName=node0

 2023-06-24T14:05:42,074+0000 [main] INFO  org.eclipse.jetty.server.session - No SessionScavenger set, using defaults

 2023-06-24T14:05:42,076+0000 [main] INFO  org.eclipse.jetty.server.session - node0 Scavenging every 600000ms

 2023-06-24T14:05:42,091+0000 [main] INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@21325036{/metrics,null,AVAILABLE}

 2023-06-24T14:05:42,553+0000 [main] WARN  org.glassfish.jersey.server.wadl.WadlFeature - JAXBContext implementation could not be found. WADL feature is disabled.

 2023-06-24T14:05:42,849+0000 [main] INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@6272c96f{/,null,AVAILABLE}

 2023-06-24T14:05:42,902+0000 [main] WARN  org.glassfish.jersey.server.wadl.WadlFeature - JAXBContext implementation could not be found. WADL feature is disabled.

 2023-06-24T14:05:43,062+0000 [main] INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@489543a6{/proxy-stats,null,AVAILABLE}

 2023-06-24T14:05:43,119+0000 [main] INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@417d6615{/admin,null,AVAILABLE}

 2023-06-24T14:05:43,121+0000 [main] INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@7a6ebe1e{/lookup,null,AVAILABLE}

 2023-06-24T14:05:43,133Z [jdk.internal.loader.ClassLoaders$AppClassLoader@5ffd2b27] error Uncaught exception in thread main: Failed to start HTTP server on ports [80]

 java.io.IOException: Failed to start HTTP server on ports [80]

 	at org.apache.pulsar.proxy.server.WebServer.start(WebServer.java:243)

 	at org.apache.pulsar.proxy.server.ProxyServiceStarter.start(ProxyServiceStarter.java:223)

 	at org.apache.pulsar.proxy.server.ProxyServiceStarter.main(ProxyServiceStarter.java:185)

 Caused by: java.io.IOException: Failed to bind to /0.0.0.0:80

 	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349)

 	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310)

 	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)

 	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234)

 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)

 	at org.eclipse.jetty.server.Server.doStart(Server.java:401)

 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)

 	at org.apache.pulsar.proxy.server.WebServer.start(WebServer.java:221)

 	... 2 more

 Caused by: java.net.SocketException: Permission denied

 	at java.base/sun.nio.ch.Net.bind0(Native Method)

 	at java.base/sun.nio.ch.Net.bind(Net.java:459)

 	at java.base/sun.nio.ch.Net.bind(Net.java:448)

 	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)

 	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)

 	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344)

 	... 9 more
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Technoboy-** [comment]
This should be a permission issue  for accessing port 80 of your OS

**Comment by tisonkun** [comment]
Closed as answered.
