### ISSUE TITLE
[Bug] Master branch is broken due to failing test testElasticSearch8Sink

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#20661]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

master

### Minimal reproduce step

Run a Pr against master branch

https://github.com/apache/pulsar/actions/runs/5388118701/jobs/9782385675?pr=20654

### What did you expect to see?

The tests are passing

### What did you see instead?

The test failed

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
> https://github.com/apache/pulsar/commit/2b01f83ea4f3ab7b22f4ea2b0290cc183e79bbb8

It's even the latest commit 🤣

**Comment by lhotari** [comment]
@tisonkun @eolivelli I found a problem in PulsarIOSinkRunner. 
Instead of Awaitility, it's using [Failsafe](https://failsafe.dev/).

https://github.com/apache/pulsar/blob/46bb63d6bd3f119bbad0801d801915715dc061a7/tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/PulsarIOSinkRunner.java#L117-L119

This is [the first exception in the log](https://github.com/apache/pulsar/actions/runs/5388118701/jobs/9782385675?pr=20654#step:11:20191):
```
  2023-06-27T11:39:06,756 - INFO  - [main:TestRetrySupport@70] - Detected test failure in test PulsarSinksTest.testElasticSearch8Sink, currentSetupNumber=1
  	at org.testng.Assert.failNotEquals(Assert.java:1577)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
  	at org.testng.Assert.assertEquals(Assert.java:131)
  	at org.testng.Assert.assertEquals(Assert.java:979)
  	at org.testng.Assert.assertEquals(Assert.java:955)
  	at org.testng.Assert.assertEquals(Assert.java:989)
  	at org.apache.pulsar.tests.integration.io.sinks.PulsarIOSinkRunner.waitForProcessingSinkMessages(PulsarIOSinkRunner.java:339)
  	at org.apache.pulsar.tests.integration.io.sinks.PulsarIOSinkRunner.lambda$runSinkTester$4(PulsarIOSinkRunner.java:119)
  	at net.jodah.failsafe.Functions.lambda$toSupplier$10(Functions.java:262)
  	at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:48)
  	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
  	at net.jodah.failsafe.Execution.executeSync(Execution.java:128)
  	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:379)
  	at net.jodah.failsafe.FailsafeExecutor.run(FailsafeExecutor.java:212)
  	at org.apache.pulsar.tests.integration.io.sinks.PulsarIOSinkRunner.runSinkTester(PulsarIOSinkRunner.java:118)
  	at org.apache.pulsar.tests.integration.io.PulsarIOTestBase.testSink(PulsarIOTestBase.java:40)
  	at org.apache.pulsar.tests.integration.io.sinks.PulsarSinksTest.testElasticSearch8Sink(PulsarSinksTest.java:75)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```
it retries using TestRetrySupport
```
  2023-06-27T11:39:06,771 - INFO  - [main:TestRetrySupport@53] - Previous test run has failed before PulsarSinksTest.testElasticSearch8Sink, failedSetupNumber=1. Running cleanup and setup.
```

and fails on the retry:
```
  java.lang.AssertionError: expected [20] but found [1]
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.testng.Assert.failNotEquals(Assert.java:1577)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
  	at org.testng.Assert.assertEquals(Assert.java:131)
  	at org.testng.Assert.assertEquals(Assert.java:979)
  	at org.testng.Assert.assertEquals(Assert.java:955)
  	at org.testng.Assert.assertEquals(Assert.java:989)
  	at org.apache.pulsar.tests.integration.io.sinks.PulsarIOSinkRunner.waitForProcessingSinkMessages(PulsarIOSinkRunner.java:339)
  	at org.apache.pulsar.tests.integration.io.sinks.PulsarIOSinkRunner.lambda$runSinkTester$4(PulsarIOSinkRunner.java:119)
  	at net.jodah.failsafe.Functions.lambda$toSupplier$10(Functions.java:262)
  	at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:48)
  	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
  	at net.jodah.failsafe.Execution.executeSync(Execution.java:128)
  	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:379)
  	at net.jodah.failsafe.FailsafeExecutor.run(FailsafeExecutor.java:212)
  	at org.apache.pulsar.tests.integration.io.sinks.PulsarIOSinkRunner.runSinkTester(PulsarIOSinkRunner.java:118)
  	at org.apache.pulsar.tests.integration.io.PulsarIOTestBase.testSink(PulsarIOTestBase.java:40)
  	at org.apache.pulsar.tests.integration.io.sinks.PulsarSinksTest.testElasticSearch8Sink(PulsarSinksTest.java:75)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

This looks simply because of slow execution and that the retry solution isn't working.

Failsafe isn't clearly working as expected since the log doesn't contain any lines with "Retry ... ", that should get printed by Failsafe when it retries:
https://github.com/apache/pulsar/blob/82237d3684fe506bcb6426b3b23f413422e6e4fb/tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/PulsarIOTestRunner.java#L45-L48

I'll replace Failsafe with Awaitility since we use Awaitility in tests.

**Comment by tisonkun** [comment]
Yeah. I notice that part also. IIRC the last passed run doesn't print "Retry ..."

**Comment by lhotari** [comment]
btw. I'm running an experiment in my own fork by adding logging to the Elasticsearch container to see what's going on there, https://github.com/lhotari/pulsar/pull/151 .

**Comment by eolivelli** [comment]
Thank you @lhotari 

Today I cannot continue, can you please pick up this issue ?

**Comment by lhotari** [comment]
In forks, the Pulsar CI will activate ssh access to the user that triggered the build.
I'm currently trying to find the reason why the failure happens.

To investigate integration test failures, there's a possibility to leave docker containers running so that problems can be investigated. This makes only sense when triggering the test manually. Here's an example:

```
# terminate any existing java processes or current running build:
pkill java

# setup Java 17
export JAVA_HOME=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.7-7/x64
export PATH=$JAVA_HOME/bin:$PATH

# leave docker containers running after the test completes
export PULSAR_CONTAINERS_LEAVE_RUNNING=true TESTCONTAINERS_REUSE_ENABLE=true

# run a single test method 
mvn test -DredirectTestOutputToFile=false -DtestRetryCount=0 -Dspotbugs.skip=true -DintegrationTests -pl tests/integration -Dtest=org.apache.pulsar.tests.integration.io.sinks.PulsarSinksTest#testElasticSearch8Sink

# list running containers
docker ps
```

**Comment by lhotari** [comment]
The problem went away during I was investigating it. :( 

My current suspicion is the automatic download of MaxMind DB by Elasticsearch. This is a bug reported as https://github.com/elastic/elasticsearch/pull/92335 .

It should be possible to disable downloading by setting `.withEnv("ingest.geoip.downloader.enabled", "false")`. Let's see if this makes a difference.
