### ISSUE TITLE
Flaky-test: TransactionBufferCloseTest.deleteTopicCloseTransactionBufferTest

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#20673]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/5401760645/jobs/9812478081?pr=20671#step:10:913

### Exception stacktrace

```
  Error:  Tests run: 14, Failures: 1, Errors: 0, Skipped: 13, Time elapsed: 52.953 s <<< FAILURE! - in org.apache.pulsar.broker.transaction.buffer.TransactionBufferCloseTest
  Error:  org.apache.pulsar.broker.transaction.buffer.TransactionBufferCloseTest.deleteTopicCloseTransactionBufferTest[true](3)  Time elapsed: 10.058 s  <<< FAILURE!
  org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.broker.transaction.buffer.TransactionBufferCloseTest.deleteTopicCloseTransactionBufferTest() didn't finish within the time-out 10000
  	at java.base@17.0.7/jdk.internal.misc.Unsafe.park(Native Method)
  	at java.base@17.0.7/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
  	at java.base@17.0.7/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1866)
  	at java.base@17.0.7/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
  	at java.base@17.0.7/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
  	at java.base@17.0.7/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1939)
  	at java.base@17.0.7/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
  	at app//org.apache.pulsar.client.admin.internal.BaseResource.sync(BaseResource.java:342)
  	at app//org.apache.pulsar.client.admin.internal.TopicsImpl.deletePartitionedTopic(TopicsImpl.java:457)
  	at app//org.apache.pulsar.client.admin.Topics.deletePartitionedTopic(Topics.java:802)
  	at app//org.apache.pulsar.broker.transaction.buffer.TransactionBufferCloseTest.deleteTopic(TransactionBufferCloseTest.java:81)
  	at app//org.apache.pulsar.broker.transaction.buffer.TransactionBufferCloseTest.deleteTopicCloseTransactionBufferTest(TransactionBufferCloseTest.java:72)
  	at java.base@17.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base@17.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base@17.0.7/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base@17.0.7/java.lang.reflect.Method.invoke(Method.java:568)
  	at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base@17.0.7/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Technoboy-** [comment]
```
@Test(timeOut = 10_000, dataProvider = "isPartition")
    public void deleteTopicCloseTransactionBufferTest(boolean isPartition) throws Exception {
        int partitionCount = isPartition ? 30 : 1;
        List<TopicName> topicNames = createAndLoadTopics(isPartition, partitionCount);
        String namespaceName = topicNames.get(0).getNamespace();
        checkSnapshotPublisherCount(namespaceName, 1);

        for (int i = 0; i < topicNames.size(); i++) {
            deleteTopic(isPartition, topicNames.get(i));
            // When delete all topics of the namespace, the publisher count should be 0.
            int expectCount = i == topicNames.size() - 1 ? 0 : 1;
            checkSnapshotPublisherCount(namespaceName, expectCount);
        }
    }
```
I think we can remove the timeout of the test. Because it creates and then deletes 60 topics if `isPartition=true`.

**Comment by gaoran10** [comment]
This is strange, I tested on my local env, and it only costs less than 2 seconds.

**Comment by gaoran10** [comment]
It seems that this method was blocked, I'm afraid the thread was stuck.

```
admin.topics().deletePartitionedTopic(topicName.getPartitionedTopicName(), true);
```

**Comment by lhotari** [comment]
again: https://github.com/apache/pulsar/actions/runs/5536635370/jobs/10110676512?pr=20623#step:10:1201

**Comment by lhotari** [comment]
@gaoran10 It looks like there's a resource leak somewhere. When the test times out there are 718  threads:
https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_dump

Lots of threads with the same name, for example:
[pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47c3c3a20)awaiting notification on [ [0x00000800337ab3f8](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x00000800337ab3f8) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47ca98f80)awaiting notification on [ [0x0000080000cab0d0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x0000080000cab0d0) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47caa29b0)awaiting notification on [ [0x00000800336f0e18](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x00000800336f0e18) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47cc88f60)awaiting notification on [ [0x000008001c456320](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x000008001c456320) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47cd2fd00)awaiting notification on [ [0x000008001c4453c8](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x000008001c4453c8) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47cd34020)awaiting notification on [ [0x00000803f5e314f0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x00000803f5e314f0) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47cd38a20)awaiting notification on [ [0x00000803f5e1e848](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x00000803f5e1e848) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47cd64200)awaiting notification on [ [0x00000800167b9f60](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x00000800167b9f60) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47cd6cce0)awaiting notification on [ [0x00000803f5e29468](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x00000803f5e29468) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47d6d9810)awaiting notification on [ [0x00000803f5e35928](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x00000803f5e35928) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47d7382f0)awaiting notification on [ [0x00000803f49f6c58](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x00000803f49f6c58) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47d9dd150)awaiting notification on [ [0x00000803f5e1a4c8](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x00000803f5e1a4c8) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47da15b80)awaiting notification on [ [0x00000803f5e250f8](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x00000803f5e250f8) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47da1fe20)awaiting notification on [ [0x00000803fd845250](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x00000803fd845250) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47dd504a0)awaiting notification on [ [0x000008003371cc80](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x000008003371cc80) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47dd92620)awaiting notification on [ [0x000008003374c040](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x000008003374c040) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47e003090)awaiting notification on [ [0x00000800336fcc80](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x00000800336fcc80) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47e03fae0)awaiting notification on [ [0x0000080033743fd0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x0000080033743fd0) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47e2235e0)awaiting notification on [ [0x000008002e436230](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x000008002e436230) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47e284110)awaiting notification on [ [0x00000800336f4cb8](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x00000800336f4cb8) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47e289070)awaiting notification on [ [0x00000803fd839070](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x00000803fd839070) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47e28cef0)awaiting notification on [ [0x000008001c43b4b8](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x000008001c43b4b8) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47e3f0890)awaiting notification on [ [0x00000800336ffdf0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x00000800336ffdf0) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47e4f1e20)awaiting notification on [ [0x00000803fd834ee0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x00000803fd834ee0) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47e551d50)awaiting notification on [ [0x000008003375cf68](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x000008003375cf68) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47e9eb840)awaiting notification on [ [0x00000803f5e22758](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x00000803f5e22758) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47ea2fa30)awaiting notification on [ [0x0000080033714c18](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x0000080033714c18) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47ea8ba70)awaiting notification on [ [0x00000803fd854f08](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x00000803fd854f08) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47eabd620)awaiting notification on [ [0x000008002e43f5d0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x000008002e43f5d0) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47eb15a10)awaiting notification on [ [0x000008001b7ada88](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x000008001b7ada88) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe47eb566e0)awaiting notification on [ [0x00000800368373a0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x00000800368373a0) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe6d987be00)awaiting notification on [ [0x0000080033748020](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x0000080033748020) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe6d9d83180)awaiting notification on [ [0x00000800337109b0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x00000800337109b0) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe6d9e20c90)awaiting notification on [ [0x00000800093d68d8](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x00000800093d68d8) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe6d9e24aa0)awaiting notification on [ [0x0000080033752588](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x0000080033752588) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe6daba4410)awaiting notification on [ [0x0000080036824490](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x0000080036824490) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe6db301250)awaiting notification on [ [0x0000080036840ae0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x0000080036840ae0) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe6db3056b0)awaiting notification on [ [0x0000080033718d10](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x0000080033718d10) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe6db5495a0)awaiting notification on [ [0x00000800093c1028](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x00000800093c1028) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe6db5f4a60)awaiting notification on [ [0x0000080000ca5d10](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x0000080000ca5d10) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe6db67a2b0)awaiting notification on [ [0x00000803f5e39718](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x00000803f5e39718) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe6db6839c0)awaiting notification on [ [0x000008001c4401f8](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x000008001c4401f8) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe6db689a70)awaiting notification on [ [0x000008003370c850](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x000008003370c850) ]
 [pulsar-backlog-quota-checker-OrderedScheduler-0-0](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_threaddetails_0x00007fe6db9fd720)awaiting notification on [ [0x00000800336f8d80](https://jstack.review/?https://gist.github.com/lhotari/a4276e94f10c8f62cc0fd3c1257624f6#tda_1_sync_0x00000800336f8d80) ]

/Cc @dave2wave @Technoboy-  Here yet another resource leak in tests.

**Comment by lhotari** [comment]
thread leaks:
```
❯ grep -shEr "created [0-9][0-9]+ new threads" pulsar-broker
2023-07-13T06:18:12,115 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.service.ReplicatorAdminTlsTest created 26 new threads
2023-07-13T06:09:10,589 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.service.TopicOwnerTest created 40 new threads
2023-07-13T06:18:27,708 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.service.BrokerBkEnsemblesTests created 32 new threads
2023-07-13T05:59:04,195 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.loadbalance.SimpleBrokerStartTest created 13 new threads
2023-07-13T06:02:54,883 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.loadbalance.extensions.scheduler.UnloadSchedulerTest created 10 new threads
2023-07-13T06:27:27,595 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.service.BacklogQuotaManagerTest created 17 new threads
2023-07-13T06:24:54,267 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.service.BrokerServiceTest created 37 new threads
2023-07-13T06:31:26,617 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.service.ReplicatorSubscriptionTest created 23 new threads
2023-07-13T06:14:34,465 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.service.ReplicatorTlsTest created 18 new threads
2023-07-13T06:34:40,969 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.transaction.buffer.TransactionStablePositionTest created 78 new threads
2023-07-13T06:32:03,632 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.service.BrokerBookieIsolationTest created 51 new threads
2023-07-13T06:00:16,670 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.loadbalance.impl.BundleSplitterTaskTest created 13 new threads
2023-07-13T06:07:32,859 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.service.PeerReplicatorTest created 24 new threads
2023-07-13T06:05:18,690 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.auth.AuthorizationTest created 12 new threads
2023-07-13T06:05:50,722 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.loadbalance.SimpleLoadManagerImplTest created 51 new threads
2023-07-13T06:04:49,333 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.loadbalance.MultiBrokerLeaderElectionTest created 89 new threads
2023-07-13T06:10:48,796 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.service.persistent.PersistentStickyKeyDispatcherMultipleConsumersTest created 11 new threads
2023-07-13T06:30:07,831 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.service.ReplicatorTopicPoliciesTest created 22 new threads
2023-07-13T06:31:28,204 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.intercept.MangedLedgerInterceptorImplTest created 10 new threads
2023-07-13T06:20:06,450 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.service.ClusterMigrationTest created 743 new threads
2023-07-13T06:20:30,680 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.service.schema.PartitionedTopicsSchemaTest created 16 new threads
2023-07-13T06:08:03,645 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.service.ReplicatorRemoveClusterTest created 18 new threads
2023-07-13T06:06:43,539 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.service.ReplicatorAdminTlsWithKeyStoreTest created 25 new threads
2023-07-13T06:27:39,557 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.service.MessageCumulativeAckTest created 62 new threads
2023-07-13T06:29:35,866 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.service.ServerCnxTest created 849 new threads
2023-07-13T06:05:18,567 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.loadbalance.ModularLoadManagerImplTest created 47 new threads
2023-07-13T06:31:20,507 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.service.MaxMessageSizeTest created 23 new threads
2023-07-13T06:23:33,302 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.service.schema.SchemaServiceTest created 18 new threads
2023-07-13T06:34:47,454 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.transaction.pendingack.PendingAckInMemoryDeleteTest created 78 new threads
2023-07-13T06:17:41,339 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.service.OneWayReplicatorTest created 20 new threads
2023-07-13T06:05:49,956 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.SLAMonitoringTest created 31 new threads
2023-07-13T06:34:39,547 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.transaction.AuthenticatedTransactionProducerConsumerTest created 100 new threads
2023-07-13T05:59:13,933 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.loadbalance.LeaderElectionServiceTest created 13 new threads
2023-07-13T06:27:18,576 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.service.ReplicatorTest created 61 new threads
2023-07-13T06:00:53,494 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.loadbalance.MultiBrokerLeaderElectionExpirationTest created 81 new threads
2023-07-13T06:02:37,720 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.loadbalance.LoadBalancerTest created 92 new threads
2023-07-13T06:10:33,889 - WARN  - [main:ThreadLeakDetectorListener@60] - Summary: Tests in class org.apache.pulsar.broker.service.persistent.PersistentSubscriptionTest created 25 new threads
```

**Comment by gaoran10** [comment]
@lhotari Thanks for this discovery, I'll check the dump and try to fix this problem.

**Comment by lhotari** [comment]
UPDATE: the thread leak detection does some false alarms since broker shutdown is asynchronous in tests because of performance reasons. For example, in ServerCnxTest, ` svcConfig.setBrokerShutdownTimeoutMs(5000L);` makes the shutdown wait for completion, but that makes the test very slow. /cc @gaoran10

**Comment by lhotari** [comment]
Actually, setting `svcConfig.setBrokerShutdownTimeoutMs(5000L);` in ServerCnxTest didn't make the thread leak go away. There must be some other problem in shutdown sequence. I'll file another bug report for it.
