### ISSUE TITLE
[Bug] broker stuck when getBundleDataOrDefault

### ISSUE THREAD

**Issue by codeHardest** [apache/pulsar#20738]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

pulsar Version: 2.11.1
OS: Linux k8s-ma 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux

### Minimal reproduce step

broker seems stuck. there is no deadlock found, but all the pulsar-x-x thread are wating to lock a object which already locked by pulsar-2-7 thread . pulsar-2-7 thread self stuck at getBundleDataOrDefault

"pulsar-2-7" #127 prio=5 os_prio=0 cpu=941834.56ms elapsed=431390.74s tid=0x00007f3cd401b100 nid=0x142 waiting on condition  [0x00007f3c28bf5000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.6/Native Method)
	- parking to wait for  <0x000000071b78aac8> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.6/LockSupport.java:211)
	at java.util.concurrent.CompletableFuture$Signaller.block(java.base@17.0.6/CompletableFuture.java:1864)
	at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@17.0.6/ForkJoinPool.java:3463)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.6/ForkJoinPool.java:3434)
	at java.util.concurrent.CompletableFuture.waitingGet(java.base@17.0.6/CompletableFuture.java:1898)
	at java.util.concurrent.CompletableFuture.join(java.base@17.0.6/CompletableFuture.java:2117)
	at org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerImpl.getBundleDataOrDefault(ModularLoadManagerImpl.java:389)
	at org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerImpl.lambda$selectBrokerForAssignment$8(ModularLoadManagerImpl.java:839)
	at org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerImpl$$Lambda$698/0x00000008012b34d0.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(java.base@17.0.6/ConcurrentHashMap.java:1708)
	- locked <0x000000071b78ab28> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
	at org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerImpl.selectBrokerForAssignment(ModularLoadManagerImpl.java:838)
	- locked <0x0000000702298510> (a java.util.HashSet)
	at org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerWrapper.getLeastLoaded(ModularLoadManagerWrapper.java:68)
	at org.apache.pulsar.broker.namespace.NamespaceService.getLeastLoadedFromLoadManager(NamespaceService.java:702)
	at org.apache.pulsar.broker.namespace.NamespaceService.searchForCandidateBroker(NamespaceService.java:525)
	at org.apache.pulsar.broker.namespace.NamespaceService.lambda$findBrokerServiceUrl$8(NamespaceService.java:410)
	at org.apache.pulsar.broker.namespace.NamespaceService$$Lambda$696/0x00000008012b3068.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@17.0.6/Executors.java:539)
	at java.util.concurrent.FutureTask.run(java.base@17.0.6/FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(java.base@17.0.6/ScheduledThreadPoolExecutor.java:304)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.6/ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.6/ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(java.base@17.0.6/Thread.java:833)

the whole thread dump are below
[dump.txt](https://github.com/apache/pulsar/files/11966613/dump.txt)

### What did you expect to see?

not suck

### What did you see instead?

stuck, request timeout

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by poorbarcode** [comment]
I think this issue was fixed by https://github.com/apache/pulsar/pull/20189

You can see there has a thread that hits the deadlock issue(it is the same as the issue that https://github.com/apache/pulsar/pull/20189 solved):

```
"main-EventThread" #20 daemon prio=5 os_prio=0 cpu=337912.60ms elapsed=431398.16s tid=0x00007f3d4e1f0fc0 nid=0xd2 waiting on condition  [0x00007f3d1d6fd000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.6/Native Method)
	- parking to wait for  <0x000000071b786a00> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.6/LockSupport.java:211)
	at java.util.concurrent.CompletableFuture$Signaller.block(java.base@17.0.6/CompletableFuture.java:1864)
	at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@17.0.6/ForkJoinPool.java:3463)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.6/ForkJoinPool.java:3434)
	at java.util.concurrent.CompletableFuture.waitingGet(java.base@17.0.6/CompletableFuture.java:1898)
	at java.util.concurrent.CompletableFuture.get(java.base@17.0.6/CompletableFuture.java:2072)
	at com.github.benmanes.caffeine.cache.LocalAsyncCache$AbstractCacheView.resolve(LocalAsyncCache.java:515)
	at com.github.benmanes.caffeine.cache.LocalAsyncLoadingCache$LoadingCacheView.get(LocalAsyncLoadingCache.java:122)
	at org.apache.pulsar.common.naming.NamespaceBundleFactory.getBundles(NamespaceBundleFactory.java:261)
	at org.apache.pulsar.broker.namespace.NamespaceService.getBundle(NamespaceService.java:222)
	at org.apache.pulsar.broker.namespace.NamespaceService.isServiceUnitActiveAsync(NamespaceService.java:1026)
	at org.apache.pulsar.broker.service.BrokerService.checkOwnershipAndCreatePersistentTopic(BrokerService.java:1454)
	at org.apache.pulsar.broker.service.BrokerService.lambda$loadOrCreatePersistentTopic$46(BrokerService.java:1429)
	at org.apache.pulsar.broker.service.BrokerService$$Lambda$734/0x00000008012c6628.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(java.base@17.0.6/CompletableFuture.java:787)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@17.0.6/CompletableFuture.java:510)
	at java.util.concurrent.CompletableFuture.complete(java.base@17.0.6/CompletableFuture.java:2147)
	at org.apache.pulsar.common.naming.NamespaceBundleFactory.lambda$doLoadBundles$2(NamespaceBundleFactory.java:110)
	at org.apache.pulsar.common.naming.NamespaceBundleFactory$$Lambda$515/0x000000080110ac48.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(java.base@17.0.6/CompletableFuture.java:718)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@17.0.6/CompletableFuture.java:510)
	at java.util.concurrent.CompletableFuture.complete(java.base@17.0.6/CompletableFuture.java:2147)
	at org.apache.pulsar.metadata.impl.ZKMetadataStore.handleGetResult(ZKMetadataStore.java:253)
	at org.apache.pulsar.metadata.impl.ZKMetadataStore.lambda$batchOperation$7(ZKMetadataStore.java:197)
	at org.apache.pulsar.metadata.impl.ZKMetadataStore$$Lambda$169/0x0000000800ebc238.processResult(Unknown Source)
	at org.apache.pulsar.metadata.impl.PulsarZooKeeperClient$3$1.processResult(PulsarZooKeeperClient.java:489)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:712)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:553)
```

**Comment by codeHardest** [comment]
@poorbarcode  thanks a lot for your reply. I will upgrade to 2.11.2
