### ISSUE TITLE
[Bug] java.lang.NoSuchMethodError: int com.scurrilous.circe.checksum.Crc32cIntChecksum.computeChecksum

### ISSUE THREAD

**Issue by nodece** [apache/pulsar#20915]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Pulsar 3.0.0

### Minimal reproduce step

Unable to reproduce in the new project.

### What did you expect to see?

It works fine.

### What did you see instead?

```
2023-08-02T13:01:34,848+0800 [main] WARN  org.apache.pulsar.client.impl.ProducerImpl - [persistent://pulsar/default/my-topic] [standalone-0-0] error while create opSendMsg by batch message container
java.lang.NoSuchMethodError: 'int com.scurrilous.circe.checksum.Crc32cIntChecksum.computeChecksum(org.apache.pulsar.shade.io.netty.buffer.ByteBuf)'
	at org.apache.pulsar.common.protocol.Commands.serializeCommandSendWithSize(Commands.java:1650) ~[pulsar-client-3.0.0.jar:3.0.0]
	at org.apache.pulsar.common.protocol.Commands.newSend(Commands.java:568) ~[pulsar-client-3.0.0.jar:3.0.0]
	at org.apache.pulsar.common.protocol.Commands.newSend(Commands.java:515) ~[pulsar-client-3.0.0.jar:3.0.0]
	at org.apache.pulsar.client.impl.ProducerImpl.sendMessage(ProducerImpl.java:854) ~[pulsar-client-3.0.0.jar:3.0.0]
	at org.apache.pulsar.client.impl.BatchMessageContainerImpl.createOpSendMsg(BatchMessageContainerImpl.java:255) ~[pulsar-client-3.0.0.jar:3.0.0]
	at org.apache.pulsar.client.impl.ProducerImpl.batchMessageAndSend(ProducerImpl.java:2166) ~[pulsar-client-3.0.0.jar:3.0.0]
	at org.apache.pulsar.client.impl.ProducerImpl.triggerFlush(ProducerImpl.java:2107) ~[pulsar-client-3.0.0.jar:3.0.0]
	at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.send(TypedMessageBuilderImpl.java:85) ~[pulsar-client-3.0.0.jar:3.0.0]
```

If I open a new project, it works fine, I'm not sure what happened.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
For Gradle and shadow plugin, this is the workaround: https://github.com/apache/bookkeeper/issues/3511
