### ISSUE TITLE
Flaky-test: PulsarDebeziumSourcesTest.testDebeziumMongoDbSource

### ISSUE THREAD

**Issue by michaeljmarshall** [apache/pulsar#20999]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/michaeljmarshall/pulsar/actions/runs/5861597383/job/15914886171?pr=55

### Exception stacktrace

```
  Error:  Tests run: 35, Failures: 1, Errors: 0, Skipped: 34, Time elapsed: 408.276 s <<< FAILURE! - in TestSuite
  Error:  org.apache.pulsar.tests.integration.io.sources.debezium.PulsarDebeziumSourcesTest.testDebeziumMongoDbSource  Time elapsed: 64.142 s  <<< FAILURE!
  java.lang.AssertionError: expected [1] but found [0]
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.testng.Assert.failNotEquals(Assert.java:1577)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
  	at org.testng.Assert.assertEquals(Assert.java:131)
  	at org.testng.Assert.assertEquals(Assert.java:1418)
  	at org.testng.Assert.assertEquals(Assert.java:1382)
  	at org.testng.Assert.assertEquals(Assert.java:1428)
  	at org.apache.pulsar.tests.integration.io.sources.PulsarIOSourceRunner.getSourceStatus(PulsarIOSourceRunner.java:212)
  	at org.apache.pulsar.tests.integration.io.sources.debezium.PulsarIODebeziumSourceRunner.lambda$internalTestSource$0(PulsarIODebeziumSourceRunner.java:84)
  	at net.jodah.failsafe.Functions.lambda$toSupplier$10(Functions.java:262)
  	at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:48)
  	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
  	at net.jodah.failsafe.Execution.executeSync(Execution.java:128)
  	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:379)
  	at net.jodah.failsafe.FailsafeExecutor.run(FailsafeExecutor.java:212)
  	at org.apache.pulsar.tests.integration.io.sources.debezium.PulsarIODebeziumSourceRunner.internalTestSource(PulsarIODebeziumSourceRunner.java:84)
  	at org.apache.pulsar.tests.integration.io.sources.debezium.PulsarIODebeziumSourceRunner.testSource(PulsarIODebeziumSourceRunner.java:66)
  	at org.apache.pulsar.tests.integration.io.sources.debezium.PulsarDebeziumSourcesTest.testDebeziumMongoDbConnect(PulsarDebeziumSourcesTest.java:206)
  	at org.apache.pulsar.tests.integration.io.sources.debezium.PulsarDebeziumSourcesTest.testDebeziumMongoDbSource(PulsarDebeziumSourcesTest.java:74)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by michaeljmarshall** [comment]
For the same code, this test passes locally on my macOS

**Comment by michaeljmarshall** [comment]
This was actually an issue with my PR. Closing as "not flaky".
