### ISSUE TITLE
Flaky-test: RawReaderTest.testHasMessageAvailableWithBatch

### ISSUE THREAD

**Issue by michaeljmarshall** [apache/pulsar#20998]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/michaeljmarshall/pulsar/actions/runs/5869219096/job/15914141056?pr=54

### Exception stacktrace

```
   Error:  Tests run: 28, Failures: 1, Errors: 0, Skipped: 21, Time elapsed: 52.798 s <<< FAILURE! - in org.apache.pulsar.client.impl.RawReaderTest
  Error:  org.apache.pulsar.client.impl.RawReaderTest.testHasMessageAvailableWithBatch  Time elapsed: 0.221 s  <<< FAILURE!
  java.lang.AssertionError: HasMessageAvailable shows still has message when there is no message
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.apache.pulsar.client.impl.RawReaderTest.testHasMessageAvailableWithBatch(RawReaderTest.java:148)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by michaeljmarshall** [comment]
This test passes locally on my macOS system for the same code that failed in the referenced CI run.

**Comment by michaeljmarshall** [comment]
Another: https://github.com/apache/pulsar/actions/runs/5872509170/job/15926365652#step:10:1447

**Comment by poorbarcode** [comment]
Another case: https://github.com/apache/pulsar/actions/runs/5853688776/job/15963322497?pr=20971
