### ISSUE TITLE
Flaky-test: TransactionEndToEndTest.txnIndividualAckTestNoBatchAndSharedSub

### ISSUE THREAD

**Issue by michaeljmarshall** [apache/pulsar#21003]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/5872509170/job/15927601818#step:10:1434

### Exception stacktrace

```
   Error:  Tests run: 41, Failures: 1, Errors: 0, Skipped: 14, Time elapsed: 338.25 s <<< FAILURE! - in org.apache.pulsar.client.impl.TransactionEndToEndTest
  Error:  org.apache.pulsar.client.impl.TransactionEndToEndTest.txnIndividualAckTestNoBatchAndSharedSub  Time elapsed: 20.725 s  <<< FAILURE!
  java.lang.AssertionError: expected object to not be null
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.testng.Assert.assertNotNull(Assert.java:1483)
  	at org.testng.Assert.assertNotNull(Assert.java:1467)
  	at org.apache.pulsar.client.impl.TransactionEndToEndTest.txnAckTest(TransactionEndToEndTest.java:533)
  	at org.apache.pulsar.client.impl.TransactionEndToEndTest.txnIndividualAckTestNoBatchAndSharedSub(TransactionEndToEndTest.java:467)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by poorbarcode** [comment]
Another case: https://github.com/apache/pulsar/actions/runs/5853688776/job/15974247761?pr=20971

```
  Error:  Tests run: 41, Failures: 1, Errors: 0, Skipped: 14, Time elapsed: 320.168 s <<< FAILURE! - in org.apache.pulsar.client.impl.TransactionEndToEndTest
  Error:  org.apache.pulsar.client.impl.TransactionEndToEndTest.txnIndividualAckTestNoBatchAndSharedSub  Time elapsed: 38.657 s  <<< FAILURE!
  java.lang.AssertionError: expected object to not be null
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.testng.Assert.assertNotNull(Assert.java:1483)
  	at org.testng.Assert.assertNotNull(Assert.java:1467)
  	at org.apache.pulsar.client.impl.TransactionEndToEndTest.txnAckTest(TransactionEndToEndTest.java:533)
  	at org.apache.pulsar.client.impl.TransactionEndToEndTest.txnIndividualAckTestNoBatchAndSharedSub(TransactionEndToEndTest.java:467)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by nikhil-ctds** [comment]
@michaeljmarshall @poorbarcode 
This issue seems to solved by the below PR https://github.com/apache/pulsar/pull/21273 which fixed a different test in the same class, which was receiving null object from the same method as the consumer receive time was too short. It applies to the above test as well.
