### ISSUE TITLE
Flaky-test: MultiTopicsReaderTest.testReaderWithTimeLong

### ISSUE THREAD

**Issue by michaeljmarshall** [apache/pulsar#21002]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/5872509170/job/15927963485#step:10:1472

### Exception stacktrace

```
  Error:  Tests run: 19, Failures: 1, Errors: 0, Skipped: 5, Time elapsed: 93.07 s <<< FAILURE! - in org.apache.pulsar.client.impl.MultiTopicsReaderTest
  Error:  org.apache.pulsar.client.impl.MultiTopicsReaderTest.testReaderWithTimeLong  Time elapsed: 10.398 s  <<< FAILURE!
  org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.client.impl.MultiTopicsReaderTest.testReaderWithTimeLong() didn't finish within the time-out 10000
  	at java.base@17.0.8/java.util.stream.ReduceOps$3ReducingSink.begin(ReduceOps.java:164)
  	at java.base@17.0.8/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:354)
  	at java.base@17.0.8/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
  	at java.base@17.0.8/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
  	at java.base@17.0.8/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
  	at java.base@17.0.8/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  	at java.base@17.0.8/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
  	at app//org.glassfish.jersey.server.spi.internal.ParameterValueHelper.createValueProviders(ParameterValueHelper.java:103)
  	at app//org.glassfish.jersey.server.model.ResourceMethodValidator.checkValueProviders(ResourceMethodValidator.java:171)
  	at app//org.glassfish.jersey.server.model.ResourceMethodValidator.checkMethod(ResourceMethodValidator.java:80)
  	at app//org.glassfish.jersey.server.model.ResourceMethodValidator.visitJaxrsResourceMethod(ResourceMethodValidator.java:76)
  	at app//org.glassfish.jersey.server.model.ResourceMethodValidator.visitResourceMethod(ResourceMethodValidator.java:66)
  	at app//org.glassfish.jersey.server.model.ResourceMethod.accept(ResourceMethod.java:876)
  	at app//org.glassfish.jersey.server.model.ComponentModelValidator.validateWithErrors(ComponentModelValidator.java:126)
  	at app//org.glassfish.jersey.server.model.ComponentModelValidator.validateWithErrors(ComponentModelValidator.java:132)
  	at app//org.glassfish.jersey.server.model.ComponentModelValidator.validateWithErrors(ComponentModelValidator.java:132)
  	at app//org.glassfish.jersey.server.model.ComponentModelValidator.validateWithErrors(ComponentModelValidator.java:132)
  	at app//org.glassfish.jersey.server.model.ComponentModelValidator.access$000(ComponentModelValidator.java:55)
  	at app//org.glassfish.jersey.server.model.ComponentModelValidator$1.run(ComponentModelValidator.java:116)
  	at app//org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
  	at app//org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
  	at app//org.glassfish.jersey.internal.Errors.process(Errors.java:292)
  	at app//org.glassfish.jersey.internal.Errors.process(Errors.java:274)
  	at app//org.glassfish.jersey.internal.Errors.process(Errors.java:244)
  	at app//org.glassfish.jersey.server.model.ComponentModelValidator.validate(ComponentModelValidator.java:111)
  	at app//org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:366)
  	at app//org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:293)
  	at app//org.glassfish.jersey.server.ApplicationHandler$$Lambda$779/0x00007f69f87c8af0.call(Unknown Source)
  	at app//org.glassfish.jersey.internal.Errors.process(Errors.java:292)
  	at app//org.glassfish.jersey.internal.Errors.process(Errors.java:274)
  	at app//org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232)
  	at app//org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:292)
  	at app//org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:259)
  	at app//org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311)
  	at app//org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154)
  	at app//org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:347)
  	at app//javax.servlet.GenericServlet.init(GenericServlet.java:244)
  	at app//org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:632)
  	at app//org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:415)
  	at app//org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:750)
  	at app//org.eclipse.jetty.servlet.ServletHandler$$Lambda$729/0x00007f69f87755e0.accept(Unknown Source)
  	at java.base@17.0.8/java.util.stream.StreamSpliterators$WrappingSpliterator$$Lambda$732/0x00007f69f86efa98.accept(Unknown Source)
  	at java.base@17.0.8/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
  	at java.base@17.0.8/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
  	at java.base@17.0.8/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
  	at java.base@17.0.8/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
  	at java.base@17.0.8/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
  	at java.base@17.0.8/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
  	at app//org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:774)
  	at app//org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379)
  	at app//org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:916)
  	at app//org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288)
  	at app//org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
  	at app//org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
  	at app//org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
  	at app//org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
  	at app//org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
  	at app//org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
  	at app//org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
  	at app//org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
  	at app//org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
  	at app//org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
  	at app//org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
  	at app//org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
  	at app//org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:264)
  	at app//org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
  	at app//org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
  	at app//org.eclipse.jetty.server.Server.start(Server.java:423)
  	at app//org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
  	at app//org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
  	at app//org.eclipse.jetty.server.Server.doStart(Server.java:387)
  	at app//org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
  	at app//org.apache.pulsar.broker.web.WebService.start(WebService.java:309)
  	at app//org.apache.pulsar.broker.PulsarService.start(PulsarService.java:813)
  	at java.base@17.0.8/java.lang.invoke.LambdaForm$DMH/0x00007f69f8184000.invokeVirtual(LambdaForm$DMH)
  	at java.base@17.0.8/java.lang.invoke.LambdaForm$MH/0x00007f69f8d72800.invoke(LambdaForm$MH)
  	at java.base@17.0.8/java.lang.invoke.LambdaForm$MH/0x00007f69f88fa800.invoke(LambdaForm$MH)
  	at java.base@17.0.8/java.lang.invoke.LambdaForm$MH/0x00007f69f809b800.invokeExact_MT(LambdaForm$MH)
  	at java.base@17.0.8/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
  	at org.mockito.internal.util.reflection.InstrumentationMemberAccessor$Dispatcher$ByteBuddy$G6acFWQ7.invokeWithArguments(Unknown Source)
  	at app//org.mockito.internal.util.reflection.InstrumentationMemberAccessor.invoke(InstrumentationMemberAccessor.java:239)
  	at app//org.mockito.internal.util.reflection.ModuleMemberAccessor.invoke(ModuleMemberAccessor.java:55)
  	at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.tryInvoke(MockMethodAdvice.java:333)
  	at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.access$500(MockMethodAdvice.java:60)
  	at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice$RealMethodCall.invoke(MockMethodAdvice.java:253)
  	at app//org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:142)
  	at app//org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:45)
  	at app//org.mockito.Answers.answer(Answers.java:99)
  	at app//org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:110)
  	at app//org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
  	at app//org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
  	at app//org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
  	at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handle(MockMethodAdvice.java:151)
  	at app//org.apache.pulsar.broker.PulsarService.start(PulsarService.java:690)
  	at app//org.apache.pulsar.broker.testcontext.PulsarTestContext$AbstractCustomBuilder.build(PulsarTestContext.java:541)
  	at app//org.apache.pulsar.broker.auth.MockedPulsarServiceBaseTest.createMainPulsarTestContext(MockedPulsarServiceBaseTest.java:362)
  	at app//org.apache.pulsar.broker.auth.MockedPulsarServiceBaseTest.startBroker(MockedPulsarServiceBaseTest.java:314)
  	at app//org.apache.pulsar.broker.auth.MockedPulsarServiceBaseTest.restartBroker(MockedPulsarServiceBaseTest.java:298)
  	at app//org.apache.pulsar.client.impl.MultiTopicsReaderTest.testReaderWithTimeLong(MultiTopicsReaderTest.java:273)
  	at java.base@17.0.8/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base@17.0.8/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base@17.0.8/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base@17.0.8/java.lang.reflect.Method.invoke(Method.java:568)
  	at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base@17.0.8/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
```

Note: seems connected to https://github.com/apache/pulsar/issues/9636. That one is 2 years old though, so creating a new issue.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by michaeljmarshall** [comment]
Another instance: https://github.com/apache/pulsar/actions/runs/5872509170/job/15927297398#step:10:1390

**Comment by Technoboy-** [comment]
Remove the timeout in #21032. we the issue still existed, we can reopen it.
