### ISSUE TITLE
[Bug] the global topicPolicies config override the local topicPolicies config

### ISSUE THREAD

**Issue by chenhongSZ** [apache/pulsar#21202]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

2.10.5

### Minimal reproduce step

1. create a Topic 
`./pulsar-admin --admin-url http://127.0.0.1:8881 topics create-partitioned-topic -p 2 persistent://geo/geo/geo_3`

2. set local topicPolicies 
` ./pulsar-admin --admin-url http://127.0.0.1:8880 topicPolicies set-max-message-size persistent://geo/geo/geo_3 -m 10000`

3. set global topicPolicies 
`  ./pulsar-admin --admin-url http://127.0.0.1:8880 topicPolicies set-max-message-size persistent://geo/geo/geo_3 -g -m 10`

4. check the topicPolicies
`./pulsar-admin --admin-url http://127.0.0.1:8880 topicPolicies get-max-message-size persistent://geo/geo/geo_3`
result: 10000

`./pulsar-admin --admin-url http://127.0.0.1:8880 topicPolicies get-max-message-size persistent://geo/geo/geo_3 -g`
result: 10

4. verify the configuration to take effect 
  `./pulsar-client --url pulsar://127.0.0.1:6650 produce -m 0123456780123456789 persistent://geo/geo/geo_3`

   

### What did you expect to see?

2023-09-18T20:25:03,301+0800 [main] INFO  org.apache.pulsar.client.cli.PulsarClientTool - 1 messages successfully produced

### What did you see instead?

2023-09-18T20:25:33,934+0800 [main] ERROR org.apache.pulsar.client.cli.PulsarClientTool - Exceed maximum message size
org.apache.pulsar.client.api.PulsarClientException$NotAllowedException: Exceed maximum message size
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:1048) ~[org.apache.pulsar-pulsar-client-api-2.10.4.jar:2.10.4]
	at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.send(TypedMessageBuilderImpl.java:90) ~[org.apache.pulsar-pulsar-client-original-2.10.4.jar:2.10.4]
	at org.apache.pulsar.client.cli.CmdProduce.publish(CmdProduce.java:309) ~[org.apache.pulsar-pulsar-client-tools-2.10.4.jar:2.10.4]
	at org.apache.pulsar.client.cli.CmdProduce.run(CmdProduce.java:241) ~[org.apache.pulsar-pulsar-client-tools-2.10.4.jar:2.10.4]
	at org.apache.pulsar.client.cli.PulsarClientTool.run(PulsarClientTool.java:184) ~[org.apache.pulsar-pulsar-client-tools-2.10.4.jar:2.10.4]
	at org.apache.pulsar.client.cli.PulsarClientTool.main(PulsarClientTool.java:220) ~[org.apache.pulsar-pulsar-client-tools-2.10.4.jar:2.10.4]
2023-09-18T20:25:33,937+0800 [main] INFO  org.apache.pulsar.client.cli.PulsarClientTool - 0 messages successfully produced

### Anything else?

as [PIP-92](https://github.com/apache/pulsar/wiki/PIP-92%3A-Topic-policy-across-multiple-clusters) described:
After adding the global topic policy, the topic applied priority is:

Local cluster topic > policy Global topic policy > Namespace policy > Broker default configuration

the global topicPolicies config shouldn't override the local topicPolicies config

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by mattisonchao** [comment]
It should be a known issue. 
I guess the root cause should be global and local topic policies using the same key. it will be compacted by the compactor.

Could you please share the idea of fixing it?

**Comment by chenhongSZ** [comment]
@mattisonchao  I think there could be multiple issues here。

In my test case, the error was caused by the local topic policy and global topic policy using the same value in the `PolicyHierarchyValue` class (`topicValue`).  It should be divided into two variables.

<img width="839" alt="image" src="https://github.com/apache/pulsar/assets/18002867/55a78aba-746a-41a5-b226-5a73e24f9ec4">
