### ISSUE TITLE
[Bug] Websocket connection closed

### ISSUE THREAD

**Issue by miton18** [apache/pulsar#21628]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

v3.1.1

### Minimal reproduce step

Try to produce in Websocket

### What did you expect to see?

A message produced

### What did you see instead?

````2023-11-27T17:18:28,518+0000 [pulsar-external-web-5-15] WARN  org.apache.pulsar.websocket.ReaderHandler - [78.242.0.0:40693] Failed in creating reader  on topic non-persistent://tenant/pulsar_1/profile
org.apache.pulsar.client.api.PulsarClientException$LookupException: {"errorMsg":"org.apache.pulsar.client.api.PulsarClientException: Connection already closed","reqId":3472645042792490684, "remote":"pulsar.com/91.208.0.0:6650", "local":"/10.2.0.0:44840"}
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:1053) ~[org.apache.pulsar-pulsar-client-api-3.1.1.jar:3.1.1]
	at org.apache.pulsar.client.impl.ReaderBuilderImpl.create(ReaderBuilderImpl.java:78) ~[org.apache.pulsar-pulsar-client-original-3.1.1.jar:3.1.1]
	at org.apache.pulsar.websocket.ReaderHandler.<init>(ReaderHandler.java:112) ~[org.apache.pulsar-pulsar-websocket-3.1.1.jar:3.1.1]
	at org.apache.pulsar.websocket.WebSocketReaderServlet.lambda$configure$0(WebSocketReaderServlet.java:44) ~[org.apache.pulsar-pulsar-websocket-3.1.1.jar:3.1.1]
	at org.eclipse.jetty.websocket.server.WebSocketServerFactory.acceptWebSocket(WebSocketServerFactory.java:275) ~[org.eclipse.jetty.websocket-websocket-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.websocket.server.WebSocketServerFactory.acceptWebSocket(WebSocketServerFactory.java:260) ~[org.eclipse.jetty.websocket-websocket-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.websocket.servlet.WebSocketServlet.service(WebSocketServlet.java:160) ~[org.eclipse.jetty.websocket-websocket-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]

### Anything else?

on client side
```>Error 500 Failed to create producer/consumer: {&quot;errorMsg&quot;:&quot;org.apache.pulsar.client.api.PulsarClientException: Connection already closed&quot;,&quot;reqId&quot;:2689535377619156521, &quot;remote&quot;:&quot;pulsar.com/91.208.0.0:6650&quot;, &quot;local&quot;:&quot;/10.2.0.0:52584&quot;}</title>\n</head>\n<body><h2>HTTP ERROR 500 Failed to create producer/consumer: {&quot;errorMsg&quot;:&quot;org.apache.pulsar.client.api.PulsarClientException: Connection already closed&quot;,&quot;reqId&quot;:2689535377619156521, &quot;remote&quot;:&quot;pulsar.com/91.208.0.0:6650&quot;, &quot;local&quot;:&quot;/10.2.0.0:52584&quot;}</h2>\n<table>\n<tr><th>URI:</th><td>/ws/v2/producer/persistent/tenant/pulsar_1/ttopic</td></tr>\n<tr><th>STATUS:</th><td>500</td></tr>\n<tr><th>MESSAGE:</th><td>Failed to create producer/consumer: {&quot;errorMsg&quot;:&quot;org.apache.pulsar.client.api.PulsarClientException: Connection already closed&quot;,&quot;reqId&quot;:2689535377619156521, &quot;remote&quot;:&quot;pulsar.com/91.208.0.0:6650&quot;, &quot;local&quot;:&quot;/10.2.0.0:52584&quot;}</td></tr>\n<tr><th>SERVLET:</th><td>org.apache.pulsar.websocket.WebSocketProducerServlet-38cedb7d</td></tr>\n</table>\n<hr/><a href="https://eclipse.org/jetty">Powered by Jetty:// 9.4.51.v20230217</a><hr/>\n\n</body>\n</html>\n'

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Technoboy-** [comment]
When you meet this error, a new connection will be re-created later, do you mean it never been successfully created?

**Comment by miton18** [comment]
Yes, the connection never succeed

**Comment by sunheyi6** [comment]
> Yes, the connection never succeed

can you show the code

**Comment by miton18** [comment]
Yes,
```
import websocket, base64, json
import urllib.parse

# If set enableTLS to true, your have to set tlsEnabled to true in conf/websocket.conf.
enable_TLS = True
scheme = 'ws'
if enable_TLS:
    scheme = 'wss'

token = 'TOKEN_which_work_with_binary_protocol'
safe_string = urllib.parse.quote_plus(token)

TOPIC = scheme + '://pulsar_proxy:443/ws/v2/producer/persistent/t1/n1/ttopic?token=' + token

websocket.enableTrace(True)
try: 
    ws = websocket.create_connection(TOPIC)
except ConnectionError as e:
    raise e

print('connected')

# encode message
s = "Hello World"
firstEncoded = s.encode("UTF-8")
binaryEncoded = base64.b64encode(firstEncoded)
payloadString = binaryEncoded.decode('UTF-8')

# Send one message as JSON
ws.send(json.dumps({
    'payload' : payloadString,
    'properties': {
        'key1' : 'value1',
        'key2' : 'value2'
    },
    'context' : 5
}))

response =  json.loads(ws.recv())
if response['result'] == 'ok':
    print( 'Message published successfully')
else:
    print('Failed to publish message:', response)
ws.close()
