### ISSUE TITLE
Flaky-test: FilterEntryTest. testFilter

### ISSUE THREAD

**Issue by Technoboy-** [apache/pulsar#21712]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/7176247224/job/19541021647?pr=21711
https://github.com/apache/pulsar/actions/runs/7208049048/job/19637548110?pr=21704

### Exception stacktrace

```
Error:  Tests run: 20, Failures: 1, Errors: 0, Skipped: 16, Time elapsed: 24.003 s <<< FAILURE! - in org.apache.pulsar.broker.service.plugin.FilterEntryTest
  Error:  org.apache.pulsar.broker.service.plugin.FilterEntryTest.testFilter  Time elapsed: 1.917 s  <<< FAILURE!
  java.lang.AssertionError: expected:<10> but was:<8>
  	at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
  	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:467)
  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:318)
  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:328)
  	at org.apache.pulsar.broker.service.plugin.FilterEntryTest.testFilter(FilterEntryTest.java:267)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:840)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Technoboy-** [comment]
```
2023-12-12T14:47:47,632 - INFO  - [PulsarTestContext-executor-OrderedExecutor-0-0:Slf4jRequestLogWriter@62] - 127.0.0.1 - - [12/Dec/2023:14:47:47 +0800] "POST /admin/v2/persistent/prop/ns-abc/topicbd6c9c99-226e-4ff7-8c7c-e66af068aebc/subscription/sub/analyzeBacklog HTTP/1.1" 200 256 "-" "Pulsar-Java-v3.2.0-SNAPSHOT" 13
2023-12-12T14:47:47,634 - INFO  - [main:FilterEntryTest@261] - received : 3:0:-1
2023-12-12T14:47:47,675 - INFO  - [PulsarTestContext-executor-OrderedExecutor-0-0:PulsarMockBookKeeper@123] - Creating ledger 5
2023-12-12T14:47:47,676 - INFO  - [main:FilterEntryTest@261] - received : 3:1:-1
2023-12-12T14:47:47,679 - INFO  - [bookkeeper-ml-scheduler-OrderedScheduler-1-0:ManagedCursorImpl$31@3175] - [prop/ns-abc/persistent/topicbd6c9c99-226e-4ff7-8c7c-e66af068aebc] Updated cursor sub with ledger id 5 md-position=3:0 rd-position=3:10
2023-12-12T14:47:47,774 - INFO  - [main:FilterEntryTest@261] - received : 3:2:-1
2023-12-12T14:47:47,877 - INFO  - [main:FilterEntryTest@261] - received : 3:3:-1
2023-12-12T14:47:47,988 - INFO  - [main:FilterEntryTest@261] - received : 3:4:-1
2023-12-12T14:47:48,090 - INFO  - [main:FilterEntryTest@261] - received : 3:5:-1
2023-12-12T14:47:48,192 - INFO  - [main:FilterEntryTest@261] - received : 3:6:-1
2023-12-12T14:47:48,297 - INFO  - [main:FilterEntryTest@261] - received : 3:7:-1
2023-12-12T14:47:49,445 - INFO  - [PulsarTestContext-executor-OrderedExecutor-0-0:PersistentSubscription@614] - [persistent://prop/ns-abc/topicbd6c9c99-226e-4ff7-8c7c-e66af068aebc][sub] scan took 2 ms - AnalyzeBacklogResult(entries=2, messages=2, filterRejectedEntries=0, filterAcceptedEntries=2, filterRescheduledEntries=0, filterRejectedMessages=0, filterAcceptedMessages=2, filterRescheduledMessages=0, scanOutcome=COMPLETED, firstPosition=3:8, lastPosition=3:9)
2023-12-12T14:47:49,445 - INFO  - [PulsarTestContext-executor-OrderedExecutor-0-0:PersistentTopicsBase@1664] - [null] analyzeBacklog topic sub subscription persistent://prop/ns-abc/topicbd6c9c99-226e-4ff7-8c7c-e66af068aebc result AnalyzeSubscriptionBacklogResult(entries=2, messages=2, filterRejectedEntries=0, filterAcceptedEntries=2, filterRescheduledEntries=0, filterRejectedMessages=0, filterAcceptedMessages=2, filterRescheduledMessages=0, aborted=false, firstMessageId=3:8, lastMessageId=3:9)

```
