### ISSUE TITLE
Flaky-test: SubscriptionMessageDispatchThrottlingTest.testClosingRateLimiter

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#21756]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failures

- [2023-12-19T06:28:09.7491887Z](https://github.com/apache/pulsar/actions/runs/7258004430/job/19772661615#step:9:2165) 
- [2023-12-18T06:27:21.4417513Z](https://github.com/apache/pulsar/actions/runs/7244255862/job/19732299740#step:9:2165) 
- [2023-12-17T06:27:12.5417636Z](https://github.com/apache/pulsar/actions/runs/7236708045/job/19715534805#step:9:2229) 
- [2023-12-16T06:27:12.6309426Z](https://github.com/apache/pulsar/actions/runs/7230194114/job/19701980223#step:9:2165) 
- [2023-12-15T06:27:56.4802059Z](https://github.com/apache/pulsar/actions/runs/7218583714/job/19668197509#step:9:2165) 

### Exception stacktrace

```
java.lang.AssertionError: expected [-1] but found [10]
	at org.testng.Assert.fail(Assert.java:110)
	at org.testng.Assert.failNotEquals(Assert.java:1577)
	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
	at org.testng.Assert.assertEquals(Assert.java:131)
	at org.testng.Assert.assertEquals(Assert.java:979)
	at org.testng.Assert.assertEquals(Assert.java:955)
	at org.testng.Assert.assertEquals(Assert.java:989)
	at org.apache.pulsar.client.api.SubscriptionMessageDispatchThrottlingTest.testClosingRateLimiter(SubscriptionMessageDispatchThrottlingTest.java:915)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
This seems to be broken by #21682 changes. Will be fixed by #21736 .
