### ISSUE TITLE
[Bug] AutthenticationToken must implements configure(Map<String, String> authParams) | Spring integration broken 

### ISSUE THREAD

**Issue by ng-galien** [apache/pulsar#21770]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

**Pulsar Java client 3.1.1**

### Minimal reproduce step

Follow [Spring doc](https://docs.spring.io/spring-pulsar/docs/1.0.0/reference/reference/pulsar.html#pulsar-client)

```yaml
spring:
  pulsar:
    client:
      authentication:
        plugin-class-name: org.apache.pulsar.client.impl.auth.AuthenticationToken
        param:
          token: some-token-goes-here
```

### What did you expect to see?

Configuration is correctly apply by method 

```java
public class AuthenticationUtil {

   public static final Authentication create(String authPluginClassName, Map<String, String> authParams)
            throws UnsupportedAuthenticationException {
        try {
            if (isNotBlank(authPluginClassName)) {
                Class<?> authClass = Class.forName(authPluginClassName);
                Authentication auth = (Authentication) authClass.getDeclaredConstructor().newInstance();
                auth.configure(authParams);
                return auth;
            } else {
                return new AuthenticationDisabled();
            }
        } catch (Throwable t) {
            throw new UnsupportedAuthenticationException(t);
        }
    }
}
```

### What did you see instead?

The config is not applicable

```
 WARN- 23-12-20 19:59:39.966 1351900-[r-client-io-1-5] o.a.p.c.i.ClientCnx                       : [localhost/127.0.0.1:6650] Got exception java.lang.RuntimeException: failed to get client token
	at org.apache.pulsar.client.impl.auth.AuthenticationDataToken.getToken(AuthenticationDataToken.java:64)
	at org.apache.pulsar.client.impl.auth.AuthenticationDataToken.<init>(AuthenticationDataToken.java:36)
```

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by onobc** [comment]
Hi @ng-galien, closing this in favor of https://github.com/spring-projects/spring-pulsar/issues/529
