### ISSUE TITLE
Flaky-test: ProxyWithExtensibleLoadManagerTest.testClientReconnectsToBrokerOnProxyClosing

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#21877]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/7474661816/job/20347553688?pr=17524#step:11:544

### Exception stacktrace

```
Error:  Tests run: 8, Failures: 2, Errors: 0, Skipped: 6, Time elapsed: 105.326 s <<< FAILURE! - in org.apache.pulsar.proxy.server.ProxyWithExtensibleLoadManagerTest
  Error:  org.apache.pulsar.proxy.server.ProxyWithExtensibleLoadManagerTest.testClientReconnectsToBrokerOnProxyClosing  Time elapsed: 30.01 s  <<< FAILURE!
  org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.proxy.server.ProxyWithExtensibleLoadManagerTest.testClientReconnectsToBrokerOnProxyClosing() didn't finish within the time-out 30000
  	at java.base@17.0.9/jdk.internal.misc.Unsafe.park(Native Method)
  	at java.base@17.0.9/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
  	at java.base@17.0.9/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
  	at java.base@17.0.9/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1047)
  	at java.base@17.0.9/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
  	at app//org.apache.pulsar.proxy.server.ProxyWithExtensibleLoadManagerTest.testClientReconnectsToBrokerOnProxyClosing(ProxyWithExtensibleLoadManagerTest.java:316)
  	at java.base@17.0.9/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base@17.0.9/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base@17.0.9/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base@17.0.9/java.lang.reflect.Method.invoke(Method.java:568)
  	at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base@17.0.9/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base@17.0.9/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base@17.0.9/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base@17.0.9/java.lang.Thread.run(Thread.java:840)
  
  Error:  org.apache.pulsar.proxy.server.ProxyWithExtensibleLoadManagerTest.proxyCleanup  Time elapsed: 0.019 s  <<< FAILURE!
  java.util.concurrent.RejectedExecutionException: event executor terminated
  	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:934)
  	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:351)
  	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:344)
  	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:836)
  	at io.netty.util.concurrent.SingleThreadEventExecutor.execute0(SingleThreadEventExecutor.java:827)
  	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:817)
  	at io.netty.channel.AbstractChannelHandlerContext.safeExecute(AbstractChannelHandlerContext.java:1165)
  	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:729)
  	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:[560](https://github.com/apache/pulsar/actions/runs/7474661816/job/20347553688?pr=17524#step:11:563))
  	at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:957)
  	at io.netty.channel.AbstractChannel.close(AbstractChannel.java:244)
  	at org.apache.pulsar.proxy.server.ProxyService.close(ProxyService.java:361)
  	at org.apache.pulsar.proxy.server.ProxyService.close(ProxyService.java:359)
  	at org.apache.pulsar.proxy.server.ProxyWithExtensibleLoadManagerTest.proxyCleanup(ProxyWithExtensibleLoadManagerTest.java:161)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:[568](https://github.com/apache/pulsar/actions/runs/7474661816/job/20347553688?pr=17524#step:11:571))
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
  	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
  	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
  	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:823)
  	at org.testng.internal.invokers.TestInvoker.runAfterConfigurations(TestInvoker.java:792)
  	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:613)
  	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
  	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
  	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
  	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
  	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
  	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
  	at org.testng.TestRunner.privateRun(TestRunner.java:829)
  	at org.testng.TestRunner.run(TestRunner.java:602)
  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
  	at org.testng.SuiteRunner.run(SuiteRunner.java:330)
  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
  	at org.testng.TestNG.runSuites(TestNG.java:1099)
  	at org.testng.TestNG.run(TestNG.java:1067)
  	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:155)
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:102)
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeLazy(TestNGDirectoryTestSuite.java:117)
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:86)
  	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:137)
  	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
  	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
  	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
  	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
Surefire logs: https://gist.github.com/lhotari/d0da6f477ffdd1c691040ffe26f71523

**Comment by lhotari** [comment]
Another failure: https://github.com/apache/pulsar/actions/runs/7474661816/job/20343045181#step:11:544

**Comment by lhotari** [comment]
This test was added in #21789 . @dragosvictor Do you have a chance to check this? If you cannot reproduce locally, it might be a timing issue. For simulating the CI environment, I have some scripts for running tests in Docker with CPU and memory limits. That helps reproduce some issues. My personal shell scripts that I use for Pulsar development are at https://github.com/lhotari/pulsar-contributor-toolbox .

**Comment by lhotari** [comment]
This might be triggered by the PR #17524 changes.

**Comment by lhotari** [comment]
Closing since PR #17524 is possibly the reason.
