### ISSUE TITLE
Flaky-test: ExtensibleLoadManagerImplTest.testTransferClientReconnectionWithoutLookup

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#21876]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/7474661816/job/20347550855?pr=17524#step:11:1559

### Exception stacktrace

```
  Error:  org.apache.pulsar.broker.loadbalance.extensions.ExtensibleLoadManagerImplTest.testTransferClientReconnectionWithoutLookup[persistent, Exclusive](3)  Time elapsed: 30.015 s  <<< FAILURE!
  org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.broker.loadbalance.extensions.ExtensibleLoadManagerImplTest.testTransferClientReconnectionWithoutLookup() didn't finish within the time-out 30000
  	at java.base@17.0.9/jdk.internal.misc.Unsafe.park(Native Method)
  	at java.base@17.0.9/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
  	at java.base@17.0.9/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
  	at java.base@17.0.9/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3465)
  	at java.base@17.0.9/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3436)
  	at java.base@17.0.9/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
  	at java.base@17.0.9/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2072)
  	at app//org.apache.pulsar.broker.loadbalance.extensions.ExtensibleLoadManagerImplTest.testTransferClientReconnectionWithoutLookup(ExtensibleLoadManagerImplTest.java:560)
  	at java.base@17.0.9/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base@17.0.9/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base@17.0.9/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base@17.0.9/java.lang.reflect.Method.invoke(Method.java:568)
  	at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base@17.0.9/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base@17.0.9/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base@17.0.9/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base@17.0.9/java.lang.Thread.run(Thread.java:840)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
Surefire logs: https://gist.github.com/lhotari/abf15ee24529e21dd71286a33f36d4bb

**Comment by lhotari** [comment]
@dragosvictor @heesung-sn Do you have a chance to check this one?

**Comment by lhotari** [comment]
This might be triggered by the PR https://github.com/apache/pulsar/pull/17524 changes.
