### ISSUE TITLE
create producer thread stuck[Bug] 

### ISSUE THREAD

**Issue by qiaofazhan** [apache/pulsar#21900]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

pulsar client 3.01.
pulsar broker 3.0.1
puslar proxy 3.0.1

### Minimal reproduce step

It is hard to reproduce

### What did you expect to see?

When you use puslar client to create producer objects synchronously, you can trigger a timeout or other exception normally, rather than the thread staying stuck

### What did you see instead?

Threads keep getting stuck when creating producer objects synchronously using puslar client. To reproduce it, the pulsar cluster is stopped, and a timeout exception is reported when the produce object is created. Therefore, it is not clear how this situation has arisen. At present, it has appeared many times in the production environment.
![企业微信截图_17047919918562](https://github.com/apache/pulsar/assets/19525691/6877f5de-8d3a-4a0e-91f7-1e67053cef08)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
@qiaofazhan Does the thread dump contain a deadlock?

**Comment by qiaofazhan** [comment]
您好，邮件已收到，尽快给您回复。

**Comment by qiaofazhan** [comment]
> @qiaofazhan Does the thread dump contain a deadlock?

There are no deadlocks in the thread dump。

**Comment by lhotari** [comment]
@qiaofazhan is it a partitioned topic or non-partitioned topic? if partitioned, how many partitions?

**Comment by qiaofazhan** [comment]
> @qiaofazhan is it a partitioned topic or non-partitioned topic? if partitioned, how many partitions?

It is a  non-partitioned topic.

**Comment by lhotari** [comment]
@qiaofazhan There's a chance that this is a bug in Apache Eventmesh. I noticed from the thread dump that Apache Eventmesh is used, perhaps version v1.8.0 . 
The producer cache within Eventmesh uses java.util.HashMap which isn't thread safe. 
https://github.com/apache/eventmesh/blob/63ac4ec808933a64b048a3988f6c91671d2bc41a/eventmesh-connector-plugin/eventmesh-connector-pulsar/src/main/java/org/apache/eventmesh/connector/pulsar/client/PulsarClientWrapper.java#L47
I'd assume that a ConcurrentHashMap should be used if Eventmesh uses multiple threads. This is a bug that should be reported to Apache Eventmesh.

**Comment by qiaofazhan** [comment]
> @qiaofazhan There's a chance that this is a bug in Apache Eventmesh. I noticed from the thread dump that Apache Eventmesh is used, perhaps version v1.8.0 . The producer cache within Eventmesh uses java.util.HashMap which isn't thread safe. https://github.com/apache/eventmesh/blob/63ac4ec808933a64b048a3988f6c91671d2bc41a/eventmesh-connector-plugin/eventmesh-connector-pulsar/src/main/java/org/apache/eventmesh/connector/pulsar/client/PulsarClientWrapper.java#L47 I'd assume that a ConcurrentHashMap should be used if Eventmesh uses multiple threads. This is a bug that should be reported to Apache Eventmesh.


========================
thanks, but I use concurrentHap for that problem .  And there are some other dump info:

"pulsar-client-io-112-1" #286 daemon prio=5 os_prio=0 cpu=64764.93ms elapsed=128885.97s tid=0x00007f66c407be40 nid=0x17e waiting for monitor entry  [0x00007f661458b000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at org.apache.pulsar.client.impl.ProducerImpl.closeAndClearPendingMessages(ProducerImpl.java:1092)
        - waiting to lock <0x000000064b01bde8> (a org.apache.pulsar.client.impl.ProducerImpl)
        at org.apache.pulsar.client.impl.ProducerImpl.lambda$closeAsync$10(ProducerImpl.java:1079)
        at org.apache.pulsar.client.impl.ProducerImpl$$Lambda$782/0x0000000840948c40.apply(Unknown Source)
        at java.util.concurrent.CompletableFuture.uniHandle(java.base@11.0.15/CompletableFuture.java:930)
        at java.util.concurrent.CompletableFuture$UniHandle.tryFire(java.base@11.0.15/CompletableFuture.java:907)
        at java.util.concurrent.CompletableFuture.postComplete(java.base@11.0.15/CompletableFuture.java:506)
        at java.util.concurrent.CompletableFuture.complete(java.base@11.0.15/CompletableFuture.java:2073)
        at org.apache.pulsar.client.impl.ClientCnx.handleSuccess(ClientCnx.java:533)
        at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:252)
        at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at org.apache.pulsar.shade.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at org.apache.pulsar.shade.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
        at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at org.apache.pulsar.shade.io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
        at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at org.apache.pulsar.shade.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at org.apache.pulsar.shade.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at org.apache.pulsar.shade.io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at org.apache.pulsar.shade.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
        at org.apache.pulsar.shade.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
        at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at org.apache.pulsar.shade.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(java.base@11.0.15/Thread.java:829)

   Locked ownable synchronizers:
        - None

**Comment by lhotari** [comment]
> thanks, but I use concurrentHap for that problem . And there are some other dump info:

Yes, indeed. Which Apache EventMesh version do you use? Custom fork?

**Comment by lhotari** [comment]
> "pulsar-client-io-112-1" #286 daemon prio=5 os_prio=0 cpu=64764.93ms elapsed=128885.97s tid=0x00007f66c407be40 nid=0x17e waiting for monitor entry [0x00007f661458b000]
> java.lang.Thread.State: BLOCKED (on object monitor)
> at org.apache.pulsar.client.impl.ProducerImpl.closeAndClearPendingMessages(ProducerImpl.java:1092)
> - waiting to lock <0x000000064b01bde8> (a org.apache.pulsar.client.impl.ProducerImpl)

@qiaofazhan There might be a deadlock even though the JVM doesn't detect a deadlock. Have you analysed the thread dump with something like https://jstack.review/ ?
would it be possible to share the full threaddump? You could sanitize it if there's any sensitive information.

**Comment by qiaofazhan** [comment]
> Custom fork

 Custom fork from EventMesh v1.8.0 ;
 Now, I try to create a producer in a practical asynchronous way; Add a timeout wait when getting the producer object
========
 private Producer<byte[]> createProducer(String topic) {
        long start = System.currentTimeMillis();
        log.info("init create producer start:");
       Producer<byte[]> producer ;
        CompletableFuture<Producer<byte[]>> future=this.pulsarClient.newProducer()
                .topic(topic)
                .enableBatching(false)  //enableBatch  always happen timeout in prod env（The timeout looks like it only took 1 millisecond）; there are similar issures in pulsar community about this;
                //.batchingMaxPublishDelay(15, TimeUnit.MILLISECONDS)
                .sendTimeout(8, TimeUnit.SECONDS)
               // .batchingMaxMessages(100)
                .maxPendingMessages(100)
                .createAsync();
        try {
            producer = future.get(60,TimeUnit.SECONDS);
        } catch (Exception ex) {
            log.error("init create producer error ,cost time="+(System.currentTimeMillis()-start)/1000);
            log.error(">>>> create pulsar producer error",unwrapCompletionException(ex));
            reInitPulsarClient(topic);
            throw new ConnectorRuntimeException(
                    String.format("Failed to create pulsar producer for %s with exception: %s", topic, ex.getMessage()));
        }
        return producer;
    }

**Comment by qiaofazhan** [comment]
> > thanks, but I use concurrentHap for that problem . And there are some other dump info:
> 
> Yes, indeed. Which Apache EventMesh version do you use? Custom fork?


 Custom fork from EventMesh v1.8.0 ;
 Now, I try to create a producer in a practical asynchronous way; Add a timeout wait when getting the producer object
========
 private Producer<byte[]> createProducer(String topic) {
        long start = System.currentTimeMillis();
        log.info("init create producer start:");
       Producer<byte[]> producer ;
        CompletableFuture<Producer<byte[]>> future=this.pulsarClient.newProducer()
                .topic(topic)
                .enableBatching(false)  //enableBatch  always happen timeout in prod env（The timeout looks like it only took 1 millisecond）; there are similar issures in pulsar community about this;
                //.batchingMaxPublishDelay(15, TimeUnit.MILLISECONDS)
                .sendTimeout(8, TimeUnit.SECONDS)
               // .batchingMaxMessages(100)
                .maxPendingMessages(100)
                .createAsync();
        try {
            producer = future.get(60,TimeUnit.SECONDS);
        } catch (Exception ex) {
            log.error("init create producer error ,cost time="+(System.currentTimeMillis()-start)/1000);
            log.error(">>>> create pulsar producer error",unwrapCompletionException(ex));
            reInitPulsarClient(topic);
            throw new ConnectorRuntimeException(
                    String.format("Failed to create pulsar producer for %s with exception: %s", topic, ex.getMessage()));
        }
        return producer;
    }

**Comment by lhotari** [comment]
@qiaofazhan please reply to https://github.com/apache/pulsar/issues/21900#issuecomment-1891635612 since that will help investigating the possible deadlock.
