### ISSUE TITLE
Flaky-test: ConsistentHashingStickyKeyConsumerSelectorTest.testConsumerSelect

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#22089]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/7985548157/job/21804460968?pr=22086#step:11:860

### Exception stacktrace

```
  Error:  Tests run: 5, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 0.248 s <<< FAILURE! - in org.apache.pulsar.broker.service.ConsistentHashingStickyKeyConsumerSelectorTest
  Error:  org.apache.pulsar.broker.service.ConsistentHashingStickyKeyConsumerSelectorTest.testConsumerSelect  Time elapsed: 0.074 s  <<< FAILURE!
  java.lang.AssertionError: expected [250.0] but found [199.0]
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.testng.Assert.failNotEquals(Assert.java:1577)
  	at org.testng.Assert.assertEquals(Assert.java:697)
  	at org.testng.Assert.assertEquals(Assert.java:710)
  	at org.apache.pulsar.broker.service.ConsistentHashingStickyKeyConsumerSelectorTest.testConsumerSelect(ConsistentHashingStickyKeyConsumerSelectorTest.java:102)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:840)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
Failed here: https://github.com/apache/pulsar/blob/7e73967f9daf368562fa0318d4ecb62272d72174/pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ConsistentHashingStickyKeyConsumerSelectorTest.java#L102

I guess `PERCENT_ERROR` could be increased from 0.2 to 0.3 to mitigate the issue.
