### ISSUE TITLE
[Bug] Caused by: java.net.UnknownHostException: Failed to resolve 'us-east-pulsar-broker-7c85cd9684-7rn98' after 2 queries

### ISSUE THREAD

**Issue by HGHNice** [apache/pulsar#22197]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

3.1

### Minimal reproduce step

pulsar cannot send and receive messages after I start geo cluster by following this step
![屏幕截图 2024-03-05 102342](https://github.com/apache/pulsar/assets/84365959/7e52dc66-3585-40cd-a97e-2460d5cfbb1e)

### What did you expect to see?

I would like to know the cause of this error and how to solve it

### What did you see instead?

**Caused by: java.net.UnknownHostException: Failed to resolve 'us-east-pulsar-broker-7c85cd9684-7rn98' after 2 queries**                                
│ us-east-pulsar-proxy-57875b8d7c-twnfg us-east-pulsar-proxy     at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1047) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Fi  
│ us-east-pulsar-proxy-57875b8d7c-twnfg us-east-pulsar-proxy     at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1000) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.  
│ us-east-pulsar-proxy-57875b8d7c-twnfg us-east-pulsar-proxy     at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:418) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]       
│ us-east-pulsar-proxy-57875b8d7c-twnfg us-east-pulsar-proxy     at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:971) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.8  
│ us-east-pulsar-proxy-57875b8d7c-twnfg us-east-pulsar-proxy     at io.netty.resolver.dns.DnsResolveContext.access$700(DnsResolveContext.java:66) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]   
│ us-east-pulsar-proxy-57875b8d7c-twnfg us-east-pulsar-proxy     at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:471) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.  
│ us-east-pulsar-proxy-57875b8d7c-twnfg us-east-pulsar-proxy     at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[io.netty-netty-common-4.1.86.Final.jar:4.1.86.Final]      
│ us-east-pulsar-proxy-57875b8d7c-twnfg us-east-pulsar-proxy     at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583) ~[io.netty-netty-common-4.1.86.Final.jar:4.1.86.Final]     
│ us-east-pulsar-proxy-57875b8d7c-twnfg us-east-pulsar-proxy     at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559) ~[io.netty-netty-common-4.1.86.Final.jar:4.1.86.Final]   
│ us-east-pulsar-proxy-57875b8d7c-twnfg us-east-pulsar-proxy     at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) ~[io.netty-netty-common-4.1.86.Final.jar:4.1.86.Final]      
│ us-east-pulsar-proxy-57875b8d7c-twnfg us-east-pulsar-proxy     at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636) ~[io.netty-netty-common-4.1.86.Final.jar:4.1.86.Final]            
│ us-east-pulsar-proxy-57875b8d7c-twnfg us-east-pulsar-proxy     at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625) ~[io.netty-netty-common-4.1.86.Final.jar:4.1.86.Final]          
│ us-east-pulsar-proxy-57875b8d7c-twnfg us-east-pulsar-proxy     at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105) ~[io.netty-netty-common-4.1.86.Final.jar:4.1.86.Final] 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by HGHNice** [comment]
I tested in different namespaces in the same k8s cluster, using the pulsar-helm installation
