### ISSUE TITLE
Flaky-test: ManagedLedgerErrorsTest.recoverAfterZnodeVersionError

### ISSUE THREAD

**Issue by coderzc** [apache/pulsar#22348]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/8415552736/job/23083691179

### Exception stacktrace

```
Error:  org.apache.bookkeeper.mledger.impl.ManagedLedgerErrorsTest.recoverAfterZnodeVersionError  Time elapsed: 0.013 s  <<< FAILURE!
  java.lang.AssertionError: expected [class org.apache.bookkeeper.mledger.ManagedLedgerException$BadVersionException] but found [class java.lang.Exception]
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.testng.Assert.failNotEquals(Assert.java:1577)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
  	at org.testng.Assert.assertEquals(Assert.java:131)
  	at org.testng.Assert.assertEquals(Assert.java:643)
  	at org.apache.bookkeeper.mledger.impl.ManagedLedgerErrorsTest.recoverAfterZnodeVersionError(ManagedLedgerErrorsTest.java:384)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:840)

```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
Another one here: https://github.com/apache/pulsar/actions/runs/8448669057/job/23141572878?pr=22361#step:11:2323

```
  Error:  Tests run: 28, Failures: 1, Errors: 0, Skipped: 13, Time elapsed: 0.556 s <<< FAILURE! - in org.apache.bookkeeper.mledger.impl.ManagedLedgerErrorsTest
  Error:  org.apache.bookkeeper.mledger.impl.ManagedLedgerErrorsTest.recoverAfterZnodeVersionError  Time elapsed: 0.008 s  <<< FAILURE!
  java.lang.AssertionError: expected [class org.apache.bookkeeper.mledger.ManagedLedgerException$BadVersionException] but found [class java.lang.Exception]
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.testng.Assert.failNotEquals(Assert.java:1577)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
  	at org.testng.Assert.assertEquals(Assert.java:131)
  	at org.testng.Assert.assertEquals(Assert.java:643)
  	at org.apache.bookkeeper.mledger.impl.ManagedLedgerErrorsTest.recoverAfterZnodeVersionError(ManagedLedgerErrorsTest.java:384)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by lhotari** [comment]
I'll fix this.
