### ISSUE TITLE
Flaky-test: ManagedLedgerTest.testGetNumberOfEntriesInStorage

### ISSUE THREAD

**Issue by nodece** [apache/pulsar#22347]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/8419142906/job/23063610336#step:11:11301

### Exception stacktrace

Error:  org.apache.bookkeeper.mledger.impl.ManagedLedgerTest.testGetNumberOfEntriesInStorage  Time elapsed: 10.041 s  <<< FAILURE!
  org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a org.apache.bookkeeper.mledger.impl.ManagedLedgerTest expected [3] but found [4] within 10 seconds.
  	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
  	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
  	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
  	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
  	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:769)
  	at org.apache.bookkeeper.mledger.impl.ManagedLedgerTest.testGetNumberOfEntriesInStorage(ManagedLedgerTest.java:2650)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:840)
  Caused by: java.lang.AssertionError: expected [3] but found [4]
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.testng.Assert.failNotEquals(Assert.java:1577)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
  	at org.testng.Assert.assertEquals(Assert.java:131)
  	at org.testng.Assert.assertEquals(Assert.java:1418)
  	at org.testng.Assert.assertEquals(Assert.java:1382)
  	at org.testng.Assert.assertEquals(Assert.java:1428)
  	at org.apache.bookkeeper.mledger.impl.ManagedLedgerTest.lambda$testGetNumberOfEntriesInStorage$16(ManagedLedgerTest.java:2651)
  	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
  	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
  	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
  	... 4 more

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by coderzc** [comment]
+1 https://github.com/apache/pulsar/actions/runs/8415552736/job/23084102366

**Comment by nodece** [comment]
https://github.com/apache/pulsar/pull/22034 breaks this test.

**Comment by lhotari** [comment]
@liangyepianzhou your change #22034 seems to have made this test flaky. do you have a chance to fix this?

**Comment by lhotari** [comment]
same problem: https://github.com/apache/pulsar/actions/runs/8448669057/job/23147779766?pr=22361#step:11:11301

**Comment by lhotari** [comment]
Oh, it's already fixed by #22344. Closing this issue.
