### ISSUE TITLE
Flaky-test: PersistentMessageFinderTest.testMessageExpiryWithTimestampNonRecoverableException

### ISSUE THREAD

**Issue by nodece** [apache/pulsar#22351]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/8423801843/job/23066766599?pr=22344#step:11:785

### Exception stacktrace

```
Error:  org.apache.pulsar.broker.service.PersistentMessageFinderTest.testMessageExpiryWithTimestampNonRecoverableException  Time elapsed: 0.021 s  <<< FAILURE!
  java.lang.AssertionError: expected [5] but found [6]
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.testng.Assert.failNotEquals(Assert.java:1577)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
  	at org.testng.Assert.assertEquals(Assert.java:131)
  	at org.testng.Assert.assertEquals(Assert.java:1418)
  	at org.testng.Assert.assertEquals(Assert.java:1382)
  	at org.testng.Assert.assertEquals(Assert.java:1428)
  	at org.apache.pulsar.broker.service.PersistentMessageFinderTest.testMessageExpiryWithTimestampNonRecoverableException(PersistentMessageFinderTest.java:409)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:840)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by nodece** [comment]
https://github.com/apache/pulsar/pull/22034 breaks this test.

**Comment by lhotari** [comment]
similar issue in https://github.com/apache/pulsar/actions/runs/8540082190/job/23397010640?pr=22415#step:11:781

**Comment by lhotari** [comment]
@liangyepianzhou do you have a chance to take a look? your PR #22034 seems to be causing the flakiness in this test. thanks
