### ISSUE TITLE
[Bug] NumberFormatException when consuming messages from pulsar-admin CLI

### ISSUE THREAD

**Issue by david-streamlio** [apache/pulsar#22405]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

    image: apachepulsar/pulsar-all:3.2.2
    platform: linux/amd64

### Minimal reproduce step

./bin/pulsar-client consume -n 0 -p Earliest -s sub <TOPIC NAME>

### What did you expect to see?

No errors

### What did you see instead?

$ ./bin/pulsar-client consume -n 0 -p Earliest -s sub persistent://feeds/realtime/coinbase-rfq
2024-04-02T18:34:44,234+0000 [main] WARN  org.apache.pulsar.common.util.netty.DnsResolverUtil - Cannot get DNS TTL settings
java.lang.NumberFormatException: For input string: "1 RUN apt-get -y --purge autoremove"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
        at java.lang.Integer.valueOf(Integer.java:973) ~[?:?]
        at java.lang.Integer.decode(Integer.java:1458) ~[?:?]
        at java.util.Optional.map(Optional.java:260) ~[?:?]
        at org.apache.pulsar.common.util.netty.DnsResolverUtil.<clinit>(DnsResolverUtil.java:71) ~[org.apache.pulsar-pulsar-common-3.2.2.jar:3.2.2]
        at org.apache.pulsar.client.impl.ConnectionPool.createAddressResolver(ConnectionPool.java:164) ~[org.apache.pulsar-pulsar-client-original-3.2.2.jar:3.2.2]
        at org.apache.pulsar.client.impl.ConnectionPool.lambda$new$1(ConnectionPool.java:127) ~[org.apache.pulsar-pulsar-client-original-3.2.2.jar:3.2.2]
        at java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
        at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:127) ~[org.apache.pulsar-pulsar-client-original-3.2.2.jar:3.2.2]
        at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:96) ~[org.apache.pulsar-pulsar-client-original-3.2.2.jar:3.2.2]
        at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:91) ~[org.apache.pulsar-pulsar-client-original-3.2.2.jar:3.2.2]
        at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:199) ~[org.apache.pulsar-pulsar-client-original-3.2.2.jar:3.2.2]
        at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:156) ~[org.apache.pulsar-pulsar-client-original-3.2.2.jar:3.2.2]
        at org.apache.pulsar.client.impl.ClientBuilderImpl.build(ClientBuilderImpl.java:65) ~[org.apache.pulsar-pulsar-client-original-3.2.2.jar:3.2.2]
        at org.apache.pulsar.client.cli.CmdConsume.consume(CmdConsume.java:149) ~[org.apache.pulsar-pulsar-client-tools-3.2.2.jar:3.2.2]
        at org.apache.pulsar.client.cli.CmdConsume.run(CmdConsume.java:141) ~[org.apache.pulsar-pulsar-client-tools-3.2.2.jar:3.2.2]
        at org.apache.pulsar.client.cli.PulsarClientTool.run(PulsarClientTool.java:246) ~[org.apache.pulsar-pulsar-client-tools-3.2.2.jar:3.2.2]
        at org.apache.pulsar.client.cli.PulsarClientTool.main(PulsarClientTool.java:286) ~[org.apache.pulsar-pulsar-client-tools-3.2.2.jar:3.2.2]

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
Fixed by #22400

**Comment by lhotari** [comment]
The DNS settings problem has existed for a very long time in the Dockerfile, since #17733 in Pulsar 3.0.0, but it only became visible after #22329 changes. Unfortunately, nobody ran extensive tests with the docker images during the release candidate phase of Pulsar 3.2.2 and Pulsar 3.0.4 . We'll have the fix in Pulsar 3.2.3 and Pulsar 3.0.5 .

**Comment by lhotari** [comment]
Closing this issue since the fix PR has been merged to branch-3.0 and branch-3.2 .

**Comment by lhotari** [comment]
A possible workaround is to add `-Dsun.net.inetaddr.ttl=1 -Dsun.net.inetaddr.negative.ttl=1` to `OPTS`.
For example:
```
export OPTS="-Dsun.net.inetaddr.ttl=1 -Dsun.net.inetaddr.negative.ttl=1"
```

**Comment by lhotari** [comment]
The impact of the DNS settings being broken in the Dockerfile since Pulsar 3.0.0 is that the positive DNS cache TTL has been 30 seconds. The negative DNS cache TTL has been 0, so there hasn't been any caching at all.

**Comment by visortelle** [comment]
> Unfortunately, nobody ran extensive tests with the docker images during the release candidate phase

Would having nightly images help to catch more issues before an actual release?
https://github.com/apache/pulsar/issues/14755
