### ISSUE TITLE
Flaky-test: TransactionEndToEndTest.testDelayedTransactionMessages

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#22431]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failures

- [2024-03-23T12:40:43.6042514Z](https://github.com/apache/pulsar/actions/runs/8401646017/job/23010402960#step:11:1575) 

### Exception stacktrace

```
java.lang.AssertionError: expected [null] but found [org.apache.pulsar.client.impl.MessageImpl@32958558]
	at org.testng.Assert.fail(Assert.java:110)
	at org.testng.Assert.failNotSame(Assert.java:1573)
	at org.testng.Assert.assertNull(Assert.java:1506)
	at org.testng.Assert.assertNull(Assert.java:1494)
	at org.apache.pulsar.client.impl.TransactionEndToEndTest.testDelayedTransactionMessages(TransactionEndToEndTest.java:1669)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
Also

- [2024-05-20T12:39:55.3993135Z](https://github.com/apache/pulsar/actions/runs/9158449757/job/25176850414#step:9:2414) 

```
java.lang.AssertionError: expected [null] but found [org.apache.pulsar.client.impl.MessageImpl@496169b]
	at org.testng.Assert.fail(Assert.java:110)
	at org.testng.Assert.failNotSame(Assert.java:1573)
	at org.testng.Assert.assertNull(Assert.java:1506)
	at org.testng.Assert.assertNull(Assert.java:1494)
	at org.apache.pulsar.client.impl.TransactionEndToEndTest.testDelayedTransactionMessages(TransactionEndToEndTest.java:1669)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by lhotari** [comment]
Also in TransactionEndToEndWithoutBatchIndexAckTest.testDelayedTransactionMessages
