### ISSUE TITLE
[Bug]  pulsar standalaone won't start : NotEnoughBookiesException: Not enough non-faulty bookies available

### ISSUE THREAD

**Issue by ghpu** [apache/pulsar#22508]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

Ubuntu 23.10
openjdk version "17.0.10" 2024-01-16
OpenJDK Runtime Environment (build 17.0.10+7-Ubuntu-123.10.1)
OpenJDK 64-Bit Server VM (build 17.0.10+7-Ubuntu-123.10.1, mixed mode, sharing)
apache-pulsar-3.2.2

### Minimal reproduce step

wget https://archive.apache.org/dist/pulsar/pulsar-3.2.2/apache-pulsar-3.2.2-bin.tar.gz
tar xvfz apache-pulsar-3.2.2-bin.tar.gz
cd apache-pulsar-3.2.2/
bin/pulsar standalone

### What did you expect to see?

A running pulsar server :-)

### What did you see instead?

Log excerpt (too long for a comment otherwise)
```
[...]

2024-04-15T11:48:21,237+0200 [pulsar-io-18-7] ERROR org.apache.bookkeeper.proto.PerChannelBookieClient - Could not connect to bookie: [id: 0x8440c1d9, L:/10.192.150.52:40764]/10.193.48.45:36113, current state CONNECTING : 
io.netty.channel.ConnectTimeoutException: connection timed out after 10000 ms: /10.193.48.45:36113
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:613) ~[io.netty-netty-transport-classes-epoll-4.1.105.Final.jar:4.1.105.Final]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[io.netty-netty-common-4.1.105.Final.jar:4.1.105.Final]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) ~[io.netty-netty-common-4.1.105.Final.jar:4.1.105.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[io.netty-netty-common-4.1.105.Final.jar:4.1.105.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[io.netty-netty-common-4.1.105.Final.jar:4.1.105.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[io.netty-netty-common-4.1.105.Final.jar:4.1.105.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:416) ~[io.netty-netty-transport-classes-epoll-4.1.105.Final.jar:4.1.105.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[io.netty-netty-common-4.1.105.Final.jar:4.1.105.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty-netty-common-4.1.105.Final.jar:4.1.105.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty-netty-common-4.1.105.Final.jar:4.1.105.Final]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[...]

2024-04-15T11:48:21,246+0200 [pulsar-io-18-7] ERROR org.apache.bookkeeper.client.MetadataUpdateLoop - UpdateLoop(ledgerId=2,loopId=537d0c8a) Exception updating
org.apache.bookkeeper.client.BKException$BKNotEnoughBookiesException: Not enough non-faulty bookies available

```

### Anything else?

I followed the default instructions here :
https://pulsar.apache.org/docs/3.2.x/getting-started-standalone/

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ghpu** [comment]
Looks like a DNS issue on my side. My hostname is resolved to another ip....
