### ISSUE TITLE
[Bug] Ctrl-C does not terminating the current shell operation in pulsar shell

### ISSUE THREAD

**Issue by mukesh154** [apache/pulsar#22671]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

3.2.2

### Minimal reproduce step

**Issue Description:**
In the Pulsar-Shell environment, when a user presses Ctrl-C during a shell operation to terminate the running shell operation, an exception `org.apache.pulsar.shell.PulsarShell$InterruptShellException` occurs but it does not terminate the running shell operation, it prints the below stack trace and the current execution keeps on running. Ideally, it should terminate the current execution.
```
^CException in thread "SIGINT handler" org.apache.pulsar.shell.PulsarShell$InterruptShellException
	at org.apache.pulsar.shell.PulsarShell.lambda$run$2(PulsarShell.java:230)
	at org.jline.terminal.impl.AbstractTerminal.raise(AbstractTerminal.java:89)
	at org.jline.terminal.impl.PosixSysTerminal.lambda$handle$1(PosixSysTerminal.java:65)
	at org.jline.utils.Signals.lambda$register$1(Signals.java:53)
	at jdk.proxy2/jdk.proxy2.$Proxy3.handle(Unknown Source)
	at jdk.unsupported/sun.misc.Signal$InternalMiscHandler.handle(Signal.java:198)
	at java.base/jdk.internal.misc.Signal$1.run(Signal.java:219)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**To reproduce it locally:**

- Run pulsar in standalone mode.
- Start pulsar-shell using `./bin/pulsar-shell`
- Run some command for example, `client produce my-topic -m "my-msg" -n 1000` or `client consume -s s1 my-topic -n 1000`
- Then try to press Ctrl+C immediately. The expected behaviour should be that it terminate the above command immediately and return to the shell terminal. But it will print the above stack trace instead and keeps running the command till it finishes producing 1000 messages or till it finishes consuming 1000 messages respectively.

### What did you expect to see?

When the user presses Ctrl-C to terminate the currently running shell operation it should terminate the current execution and return to the shell terminal.

### What did you see instead?

On pressing Ctrl-C during a shell operation, the current shell operation keeps on running. In addition, it also prints the below stack trace:
```
^CException in thread "SIGINT handler" org.apache.pulsar.shell.PulsarShell$InterruptShellException
	at org.apache.pulsar.shell.PulsarShell.lambda$run$2(PulsarShell.java:230)
	at org.jline.terminal.impl.AbstractTerminal.raise(AbstractTerminal.java:89)
	at org.jline.terminal.impl.PosixSysTerminal.lambda$handle$1(PosixSysTerminal.java:65)
	at org.jline.utils.Signals.lambda$register$1(Signals.java:53)
	at jdk.proxy2/jdk.proxy2.$Proxy3.handle(Unknown Source)
	at jdk.unsupported/sun.misc.Signal$InternalMiscHandler.handle(Signal.java:198)
	at java.base/jdk.internal.misc.Signal$1.run(Signal.java:219)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

### Anything else?

This [PR](https://github.com/apache/pulsar/pull/18615/files) is related which fixes #19218.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by nodece** [comment]
The latest(3.3.0-SHAPSHOT) version works fine.

```
Welcome to Pulsar shell!
  Service URL: pulsar://localhost:6650/
  Admin URL: http://localhost:8080/

Type help to get started or try the autocompletion (TAB button).
Type exit or quit to end the shell session.

test(localhost)> 
Goodbye!
```

control + C, and you can see Goodbye!.

**Comment by mukesh154** [comment]
@nodece I tried with latest(3.3.0-SHAPSHOT) version. And i see the same issue. It is reproducible on this version as well.
Might be you are misunderstanding the issue at hand. 

The problem is when a user the presses Ctrl-C during an ongoing operation let's say `client consume -s s1 my-topic -n 1000`, the user wants to terminate the client consume command but as per current behaviour, the shell keeps running the command until it finishes. It just print an exception on pressing Ctrl-C `org.apache.pulsar.shell.PulsarShell$InterruptShellException` the stack trace is added in the issue description.
