### ISSUE TITLE
Flaky-test: ManagedCursorTest.testForceCursorRecovery

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#23417]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/11232853373/job/31225793977?pr=23414#step:11:2927

### Exception stacktrace

```
  Error:  Tests run: 282, Failures: 1, Errors: 0, Skipped: 202, Time elapsed: 36.683 s <<< FAILURE! - in org.apache.bookkeeper.mledger.impl.ManagedCursorTest
  Error:  org.apache.bookkeeper.mledger.impl.ManagedCursorTest.testForceCursorRecovery  Time elapsed: 0.031 s  <<< FAILURE!
  java.lang.AssertionError: expected [true] but found [false]
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.testng.Assert.failNotEquals(Assert.java:1577)
  	at org.testng.Assert.assertTrue(Assert.java:56)
  	at org.testng.Assert.assertTrue(Assert.java:66)
  	at org.apache.bookkeeper.mledger.impl.ManagedCursorTest.testForceCursorRecovery(ManagedCursorTest.java:4831)
  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
another example: https://github.com/apache/pulsar/actions/runs/11272107670/job/31346818625?pr=22802#step:11:2929

**Comment by lhotari** [comment]
@ZhaoGuorui666 here's a good candidate for fixing

**Comment by ZhaoGuorui666** [comment]
> @ZhaoGuorui666 here's a good candidate for fixing. Latest failures: https://github.com/lhotari/pulsar-flakes/blob/master/2024-10-23-14d-master/org.apache.bookkeeper.mledger.impl.ManagedCursorTest.testForceCursorRecovery.md



Thank you very much. I will carefully review these failures.

**Comment by ZhaoGuorui666** [comment]
@lhotari I found an error while logging: `BadVersionsException`, and I also identified the issue: updating the cursor position information in the `MetadataStore`. The specific code is as follows:
![image](https://github.com/user-attachments/assets/d6e05025-bbae-4f4b-97df-6fee973fc427)

I will continue to delve deeper into this issue tomorrow.

**Comment by ZhaoGuorui666** [comment]
@lhotari I’ve submitted a pull request for review. Could you please take a look when you have time?
