### ISSUE TITLE
[Bug] checkBacklogQuota NullPointerException

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar#23735]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

4.0.1

### Minimal reproduce step

/

### What did you expect to see?

Nothing

### What did you see instead?

```
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]: 2024-12-16T11:25:35,145+0000 [pulsar-backlog-quota-checker-OrderedScheduler-0-0] ERROR org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://orga_2b5d63f2-610f-4f14-8d4e-7ede8fb3a77a/logs/__change_events-partition-0][java.lang.NullPointerException] Error reading entry for update old position
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]: 2024-12-16T11:25:35,145+0000 [pulsar-backlog-quota-checker-OrderedScheduler-0-0] ERROR org.apache.pulsar.broker.service.BrokerService - Error when checkBacklogQuota(persistent://orga_2b5d63f2-610f-4f14-8d4e-7ede8fb3a77a/logs/__change_events-partition-0) in monitorBacklogQuota
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]: java.util.concurrent.CompletionException: java.lang.NullPointerException
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]:        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]:        at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:747) ~[?:?]
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]:        at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735) ~[?:?]
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]:        at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2214) ~[?:?]
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]:        at org.apache.pulsar.broker.service.BrokerService.lambda$monitorBacklogQuota$111(BrokerService.java:2248) ~[org.apache.pulsar-pulsar-broker-4.0.1.jar:4.0.1]
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]:        at org.apache.pulsar.broker.service.BrokerService.lambda$forEachPersistentTopic$106(BrokerService.java:2238) ~[org.apache.pulsar-pulsar-broker-4.0.1.jar:4.0.1]
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]:        at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]:        at org.apache.pulsar.broker.service.BrokerService.lambda$forEachPersistentTopic$107(BrokerService.java:2238) ~[org.apache.pulsar-pulsar-broker-4.0.1.jar:4.0.1]
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]:        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]:        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]:        at java.base/java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3612) ~[?:?]
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]:        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]:        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]:        at org.apache.pulsar.broker.service.BrokerService.forEachPersistentTopic(BrokerService.java:2238) ~[org.apache.pulsar-pulsar-broker-4.0.1.jar:4.0.1]
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]:        at org.apache.pulsar.broker.service.BrokerService.monitorBacklogQuota(BrokerService.java:2247) ~[org.apache.pulsar-pulsar-broker-4.0.1.jar:4.0.1]
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]:        at com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator$NeverSuccessfulListenableFutureTask.run(MoreExecutors.java:741) ~[com.google.guava-guava-32.1.2-jre.jar:?]
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]:        at org.apache.bookkeeper.common.util.SingleThreadSafeScheduledExecutorService$SafeRunnable.run(SingleThreadSafeScheduledExecutorService.java:46) ~[org.apache.bookkeeper-bookkeeper-common-4.17.1.jar:4.17.1]
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]:        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty-netty-common-4.1.115.Final.jar:4.1.115.Final]
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]:        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Dec 16 11:25:35 yo-pulsar-broker-c3-n4 pulsar[3729204]: Caused by: java.lang.NullPointerException
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by dao-jun** [comment]
can you please provide more related logs?

**Comment by lhotari** [comment]
I wonder if this is fixed by #23720?

**Comment by KannarFr** [comment]
@dao-jun I have no more related logs.

@lhotari it looks like yes.

Also, apparently it only occurs on __change_events-partiton-0 topics.

**Comment by lhotari** [comment]
Is this also related to #23294?

**Comment by zlemisie** [comment]
we had the same after updating Pulsar Server to 4.0.1 - what's the impact on reading/writing to the topic?

{"log":"2025-01-17T16:17:57,301+0000 [pulsar-backlog-quota-checker-OrderedScheduler-0-0] ERROR org.apache.pulsar.broker.service.BrokerService - Error when checkBacklogQuota(persistent://datalake/replay_queue/LiveData_XXXX_f6d82d54-4ac8-4e33-8bf4-3a1d3f8e589c_CONNECTIVITY) in monitorBacklogQuota\njava.util.concurrent.CompletionException: java.lang.NullPointerException\n\tat java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]\n\tat java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(Unknown Source) ~[?:?]\n\tat java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(Unknown Source) ~[?:?]\n\tat java.base/java.util.concurrent.CompletableFuture.thenAccept(Unknown Source) ~[?:?]\n\tat org.apache.pulsar.broker.service.BrokerService.lambda$monitorBacklogQuota$111(BrokerService.java:2248) ~[org.apache.pulsar-pulsar-broker-4.0.1.jar:4.0.1]\n\tat org.apache.pulsar.broker.service.BrokerService.lambda$forEachPersistentTopic$106(BrokerService.java:2238) ~[org.apache.pulsar-pulsar-broker-4.0.1.jar:4.0.1]\n\tat java.base/java.util.Optional.ifPresent(Unknown Source) ~[?:?]\n\tat org.apache.pulsar.broker.service.BrokerService.lambda$forEachPersistentTopic$107(BrokerService.java:2238) ~[org.apache.pulsar-pulsar-broker-4.0.1.jar:4.0.1]\n\tat java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]\n\tat java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]\n\tat java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]\n\tat java.base/java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(Unknown Source) ~[?:?]\n\tat java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]\n\tat java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]\n\tat java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]\n\tat java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]\n\tat java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]\n\tat java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]\n\tat org.apache.pulsar.broker.service.BrokerService.forEachPersistentTopic(BrokerService.java:2238) ~[org.apache.pulsar-pulsar-broker-4.0.1.jar:4.0.1]\n\tat org.apache.pulsar.broker.service.BrokerService.monitorBacklogQuota(BrokerService.java:2247) ~[org.apache.pulsar-pulsar-broker-4.0.1.jar:4.0.1]\n\tat com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator$NeverSuccessfulListenableFutureTask.run(MoreExecutors.java:741) ~[com.google.guava-guava-32.1.2-jre.jar:?]\n\tat org.apache.bookkeeper.common.util.SingleThreadSafeScheduledExecutorService$SafeRunnable.run(SingleThreadSafeScheduledExecutorService.java:46) ~[org.apache.bookkeeper-bookkeeper-common-4.17.1.jar:4.17.1]\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]\n\tat java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[?:?]\n\tat java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty-netty-common-4.1.115.Final.jar:4.1.115.Final]\n\tat java.base/java.lang.Thread.run(Unknown Source) [?:?]\nCaused by: java.lang.NullPointerException","stream":"stdout","time":"2025-01-17T16:17:57.301463739Z","timestamp":1737130677301}

**Comment by KannarFr** [comment]
(It is fixed in 4.1.0-SNAPSHOT).

**Comment by zlemisie** [comment]
is the possible impact of this on reading/writing to the topic known @KannarFr?

**Comment by KannarFr** [comment]
I didn't experience any impact when having the exception. Unfortunately, this does not mean there is not. :/

**Comment by KannarFr** [comment]
Let's close it for now.
