### ISSUE TITLE
Get not allowed error, Unable to create topic list watcher: Pattern longer than maximum: 50

### ISSUE THREAD

**Issue by dmonopoly** [apache/pulsar#23750]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

I have topics that are very long: about 100 characters. The regex matcher cannot handle this apparently.
```
var patternStr = topic + ".*"
val topicPattern: Pattern = Pattern.compile(patternStr)
pulsarConsumer = consumerBuilder.topicsPattern(topicPattern).subscribe()
```
=> [pulsar-client-io-1-3] ERROR org.apache.pulsar.client.impl.ClientCnx - Get not allowed error, Unable to create topic list watcher: Pattern longer than maximum: 50

If I try to shorten the topic pattern and only use the last 50 or so characters, this is also not allowed:
```
var patternStr = topic + ".*"
if (topic.length > 46) {
    patternStr = ".*" + topic.slice(topic.length - 46..topic.length - 1) + ".*"
    logger.info("Using shortened topic regex matcher: $patternStr")
}
val topicPattern: Pattern = Pattern.compile(patternStr)
pulsarConsumer = consumerBuilder.topicsPattern(topicPattern).subscribe()
```

=>
    Exception in thread "main" org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Invalid short topic name '.*place513/consumption-metamagic542153-coverage-v0.*', it should be in the format of <tenant>/<namespace>/<topic> or <topic>
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:1111)
	at org.apache.pulsar.client.impl.ConsumerBuilderImpl.subscribe(ConsumerBuilderImpl.java:103)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tsturzl** [comment]
I'm running into this, seems very strange to limit the pattern by string length

**Comment by tsturzl** [comment]
There is a broker configuration field `subscriptionPatternMaxLength` you can set to whatever limit you want. I'm still not entirely sure why this is limited. I've run into issues trying to match large quantities of topics, but I can't imagine that regex length is a major factor in how fast topic lookup happens.
