### ISSUE TITLE
NonPersistentTopicTest#testMsgDropStat

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#2394]
*Problem*

```
-------------------------------------------------------------------------------
Test set: org.apache.pulsar.client.api.NonPersistentTopicTest
-------------------------------------------------------------------------------
Tests run: 19, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 91.727 s <<< FAILURE! - in org.apache.pulsar.client.api.NonPersistentTopicTest
testMsgDropStat(org.apache.pulsar.client.api.NonPersistentTopicTest)  Time elapsed: 0.918 s  <<< FAILURE!
java.lang.AssertionError: expected [2018-08-16T19:29:27.772Z] but found [2018-08-16T19:29:27.625Z]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:453)
	at org.testng.Assert.assertEquals(Assert.java:463)
	at org.apache.pulsar.client.api.NonPersistentTopicTest.testMsgDropStat(NonPersistentTopicTest.java:818)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The problem seems to related to #2351 (as commented https://github.com/apache/incubator-pulsar/pull/2390#issuecomment-413685952)

#2390 removed the assertion to make master stable first.

This issue for tracking the real fix for the problem.

**Comment by sijie** [comment]
@rdhabalia ^^

**Comment by sijie** [comment]
@rdhabalia any ideas about the fix here?

**Comment by rdhabalia** [comment]
is it still happening, if not then we can close it for now?

**Comment by sijie** [comment]
closed it as discussed.
