### ISSUE TITLE
can't generate ca key using the open ssl cnf file suggested for TLS Auth

### ISSUE THREAD

**Issue by dsambandam** [apache/pulsar#2533]
#### Expected behavior

Tell us what should happen

#### Actual behavior
can't generate ca key using the open ssl cnf file suggested 

#### Steps to reproduce
$ mkdir my-ca
$ cd my-ca
$ wget https://github.com/apache/incubator-pulsar/tree/master/site2/website/static/examples/openssl.cnf
$ export CA_HOME=$(pwd)

mkdir certs crl newcerts private
$ chmod 700 private/
$ touch index.txt
$ echo 1000 > serial
$ openssl genrsa -aes256 -out private/ca.key.pem 4096
$ chmod 400 private/ca.key.pem
$ **openssl req -config openssl.cnf -key private/ca.key.pem \
      -new -x509 -days 7300 -sha256 -extensions v3_ca \
      -out certs/ca.cert.pem**
How can we reproduce the issue

#### System configuration
**Pulsar version**: 2.1

 openssl req -config openssl.cnf -key private/ca.key.pem \
>       -new -x509 -days 7300 -sha256 -extensions v3_ca \
>       -out certs/ca.cert.pem
**error on line 153 of openssl.cnf
140172073654160:error:0E079065:configuration file routines:DEF_LOAD_BIO:missing equal sign:conf_def.c:345:line 153**

**Comment by sijie** [comment]
@dsambandam I think the problem is `wget https://github.com/apache/incubator-pulsar/tree/master/site2/website/static/examples/openssl.cnf`. This fetches the html file of github page. You can retrieve the file from the raw content : 

```
wget https://raw.githubusercontent.com/apache/incubator-pulsar/master/site2/website/static/examples/openssl.cnf
```

**Comment by dsambandam** [comment]
@sijie Thanks! I shall try it out and keep you posted.

**Comment by dsambandam** [comment]
Updated broker.conf and client.conf file with below configuration but not able to get pulsar-admin/client working . Fails to with exception DecoderException : javax.net.ssl.SSLHandshakeException: error:10000438:SSL routines:OPENSSL_internal:TLSV1_ALERT_INTERNAL_ERROR

@sijie Any suggestions to resolve this issue? 

**# Broker Configuration to enable authentication**
authenticationEnabled=true
authenticationProviders=org.apache.pulsar.broker.authentication.AuthenticationProviderTls

tlsEnabled=true
tlsCertificateFilePath=/Path/my-ca/broker.cert.pem
tlsKeyFilePath=/Path/my-ca/broker.key-pk8.pem
tlsTrustCertsFilePath=/Path/my-ca/certs/ca.cert.pem




**# Pulsar Client and pulsar-admin configuration**

webServiceUrl=https://carocnxodapa2v:8443/
brokerServiceUrl=pulsar+ssl://carocnxodapa2v:6651/
useTls=true
tlsTrustCertsFilePath=/Path/my-ca/certs/ca.cert.pem
#tlsEnableHostnameVerification=true
authPlugin=org.apache.pulsar.client.impl.auth.AuthenticationTls
authParams=tlsCertFile:/Path/my-ca/broker.cert.pem,tlsKeyFile:/Path/my-ca/broker.key-pk8.pem



**Pulsar client consume command Logs:**

2018-09-12 20:35:41,152 pulsar-client-io-1-1 DEBUG AsyncLogger.ThreadNameStrategy=UNCACHED (user specified null, default is UNCACHED)
20:35:41.317 [pulsar-client-io-1-1] WARN  org.apache.pulsar.client.impl.ClientCnx - Error during handshake
javax.net.ssl.SSLException: SSLEngine closed already
        at io.netty.handler.ssl.SslHandler.wrap(...)(Unknown Source) ~[io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
20:35:41.331 [pulsar-client-io-1-1] WARN  org.apache.pulsar.client.impl.ClientCnx - [broker1/IP:6651] Got exception DecoderException : javax.net.ssl.SSLHandshakeException: error:10000438:SSL routines:OPENSSL_internal:TLSV1_ALERT_INTERNAL_ERROR
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: error:10000438:SSL routines:OPENSSL_internal:TLSV1_ALERT_INTERNAL_ERROR
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459) ~[io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:806) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]

**Comment by MOLOCHT** [comment]
@dsambandam 
I encountered the same problem, prompting me to fail the handshake, and finally solved it?

**Comment by sijie** [comment]
@dsambandam sorry for late response. Is your problem resolved?

**Comment by sijie** [comment]
Closed this issue due to inactivities. If there are anything required from Pulsar team, please reopen the issue.
