### ISSUE TITLE
NullPointerException at closing consumer

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#2639]
*Problem*

```
Stacktrace
java.lang.NullPointerException
	at org.apache.pulsar.client.impl.ConsumerImpl.closeAsync(ConsumerImpl.java:696)
	at org.apache.pulsar.client.impl.ConsumerBase.close(ConsumerBase.java:284)
	at org.apache.pulsar.client.api.ServiceUrlProviderTest.testCreateClientWithAutoChangedServiceUrlProvider(ServiceUrlProviderTest.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sijie** [comment]
I think this is fixed by #2640
