### ISSUE TITLE
Flaky Test: DeadLetterTopicTest.testDeadLetterTopicWithMultiTopic

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#2647]
It has been seen multiple times in CI.

```
Method org.apache.pulsar.client.api.DeadLetterTopicTest.testDeadLetterTopicWithMultiTopic() didn't finish within the time-out 120000
Stacktrace
org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.client.api.DeadLetterTopicTest.testDeadLetterTopicWithMultiTopic() didn't finish within the time-out 120000
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jiazhai** [comment]
Here is an reference
```
org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.client.api.DeadLetterTopicTest.testDeadLetterTopicWithMultiTopic() didn't finish within the time-out 120000
	at org.apache.pulsar.client.api.PulsarClientException.<init>(PulsarClientException.java:35)
	at org.apache.pulsar.client.impl.MultiTopicsConsumerImpl.internalReceive(MultiTopicsConsumerImpl.java:317)
	at org.apache.pulsar.client.impl.ConsumerBase.receive(ConsumerBase.java:111)
	at org.apache.pulsar.client.api.DeadLetterTopicTest.testDeadLetterTopicWithMultiTopic(DeadLetterTopicTest.java:161)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sijie** [comment]
Close this issue for now. Feel free to open a new issue if the test fails again.
