### ISSUE TITLE
Exception thrown when running bin/pulsar standalone

### ISSUE THREAD

**Issue by YutanpoFR** [apache/pulsar#2652]
Hello !

#### Expected behavior

After fresh download & unzip of Pulsar incubator 2.1.1, "./bin/pulsar standalone" should run

#### Actual behavior

An exception is thrown:

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/pulsar/client/admin/PulsarAdminException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.apache.pulsar.client.admin.PulsarAdminException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

#### Steps to reproduce

Download Pulsar from: http://www.apache.org/dist/pulsar/pulsar-2.1.1-incubating/ (the download link from Pulsar website is dead: http://pulsar.apache.org/download/), 
uncompress
```
cd apache-pulsar-2.1.1-incubating
./bin/pulsar standalone

```
#### System configuration
**Pulsar version**: 2.1.1
**Java version**: OpenJDK 1.8.0_181
**OS version**: Ubuntu 18.04.1 LTS (Bash Ubuntu on Windows)

Similar report: https://github.com/apache/pulsar/issues/1822 closed due to no activity from reporter

**Comment by YutanpoFR** [comment]
Solved:
a jar is not included in classpath because of bad naming:
`org.apache.pulsar-pulsar-functions-runtime-all-2.1.1-incubating.j`
instead of
``org.apache.pulsar-pulsar-functions-runtime-all-2.1.1-incubating.jar``
