### ISSUE TITLE
Intermittent test failure in ManagedLedgerTest.testAsyncAddEntryAndSyncClose()

### ISSUE THREAD

**Issue by merlimat** [apache/pulsar#2667]
In `ManagedLedgerTest.testAsyncAddEntryAndSyncClose()` : 

Test fails with timeout : 

```
org.testng.internal.thread.ThreadTimeoutException: Method org.apache.bookkeeper.mledger.impl.ManagedLedgerTest.testAsyncAddEntryAndSyncClose() didn't finish within the time-out 20000
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

Cause seems to be assertion failed in callback thread: 

```
1:58:08.368 [bookkeeper-ml-workers-OrderedExecutor-3-0:org.apache.bookkeeper.mledger.impl.OpAddEntry@164] INFO  org.apache.bookkeeper.mledger.impl.OpAddEntry - [my_test_ledger] Closing ledger 6 for being full
01:58:08.372 [test-OrderedScheduler-0-0:org.apache.bookkeeper.client.PulsarMockBookKeeper@94] INFO  org.apache.bookkeeper.client.PulsarMockBookKeeper - Creating ledger 7
01:58:08.373 [test-OrderedScheduler-0-0:org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl@1178] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [my_test_ledger] Created new ledger 7
01:58:08.420 [bookkeeper-ml-workers-OrderedExecutor-3-0:org.apache.bookkeeper.mledger.impl.OpAddEntry@164] INFO  org.apache.bookkeeper.mledger.impl.OpAddEntry - [my_test_ledger] Closing ledger 7 for being full
01:58:08.424 [test-OrderedScheduler-0-0:org.apache.bookkeeper.client.PulsarMockBookKeeper@94] INFO  org.apache.bookkeeper.client.PulsarMockBookKeeper - Creating ledger 8
01:58:08.425 [test-OrderedScheduler-0-0:org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl@1178] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [my_test_ledger] Created new ledger 8
01:58:08.460 [bookkeeper-ml-workers-OrderedExecutor-3-0:org.apache.bookkeeper.common.util.SafeRunnable@38] ERROR org.apache.bookkeeper.common.util.SafeRunnable - Unexpected throwable caught 
java.lang.IllegalArgumentException: null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108) ~[guava-21.0.jar:?]
	at org.apache.bookkeeper.mledger.impl.OpAddEntry.safeRun(OpAddEntry.java:143) ~[classes/:?]
	at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [bookkeeper-common-4.7.2.jar:4.7.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
01:58:08.461 [bookkeeper-ml-workers-OrderedExecutor-3-0:org.apache.bookkeeper.common.util.SafeRunnable@38] ERROR org.apache.bookkeeper.common.util.SafeRunnable - Unexpected throwable caught 
java.lang.IllegalArgumentException: null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108) ~[guava-21.0.jar:?]
	at org.apache.bookkeeper.mledger.impl.OpAddEntry.safeRun(OpAddEntry.java:143) ~[classes/:?]
	at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [bookkeeper-common-4.7.2.jar:4.7.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
01:58:08.480 [bookkeeper-ml-workers-OrderedExecutor-3-0:org.apache.bookkeeper.mledger.impl.OpAddEntry@164] INFO  org.apache.bookkeeper.mledger.impl.OpAddEntry - [my_test_ledger] Closing ledger 8 for being full
01:58:08.484 [test-OrderedScheduler-0-0:org.apache.bookkeeper.client.PulsarMockBookKeeper@94] INFO  org.apache.bookkeeper.client.PulsarMockBookKeeper - Creating ledger 9
01:58:08.485 [test-OrderedScheduler-0-0:org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl@1178] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [my_test_ledger] Created new ledger 9
01:58:08.528 [bookkeeper-ml-workers-OrderedExecutor-3-0:org.apache.bookkeeper.mledger.impl.OpAddEntry@164] INFO  org.apache.bookkeeper.mledger.impl.OpAddEntry - [my_test_ledger] Closing ledger 9 for being full
01:58:08.532 [test-OrderedScheduler-0-0:org.apache.bookkeeper.client.PulsarMockBookKeeper@94] INFO  org.apache.bookkeeper.client.PulsarMockBookKeeper - Creating ledger 10
01:58:08.533 [test-OrderedScheduler-0-0:org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl@1178] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [my_test_ledger] Created new ledger 10
01:58:08.576 [bookkeeper-ml-workers-OrderedExecutor-3-0:org.apache.bookkeeper.mledger.impl.OpAddEntry@164] INFO  org.apache.bookkeeper.mledger.impl.OpAddEntry - [my_test_ledger] Closing ledger 10 for being full
01:58:08.580 [test-OrderedScheduler-0-0:org.apache.bookkeeper.client.PulsarMockBookKeeper@94] INFO  org.apache.bookkeeper.client.PulsarMockBookKeeper - Creating ledger 11
01:58:08.581 [test-OrderedScheduler-0-0:org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl@1178] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [my_test_ledger] Created new ledger 11
01:58:08.632 [bookkeeper-ml-workers-OrderedExecutor-3-0:org.apache.bookkeeper.mledger.impl.OpAddEntry@164] INFO  org.apache.bookkeeper.mledger.impl.OpAddEntry - [my_test_ledger] Closing ledger 11 for being full
01:58:08.636 [test-OrderedScheduler-0-0:org.apache.bookkeeper.client.PulsarMockBookKeeper@94] INFO  org.apache.bookkeeper.client.PulsarMockBookKeeper - Creating ledger 12
01:58:08.637 [test-OrderedScheduler-0-0:org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl@1178] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [my_test_ledger] Created new ledger 12
01:58:08.672 [bookkeeper-ml-workers-OrderedExecutor-3-0:org.apache.bookkeeper.mledger.impl.OpAddEntry@164] INFO  org.apache.bookkeeper.mledger.impl.OpAddEntry - [my_test_ledger] Closing ledger 12 for being full
01:58:08.673 [test-OrderedScheduler-0-0:org.apache.bookkeeper.client.PulsarMockBookKeeper@94] INFO  org.apache.bookkeeper.client.PulsarMockBookKeeper - Creating ledger 13
01:58:08.673 [test-OrderedScheduler-0-0:org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl@1178] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [my_test_ledger] Created new ledger 13
01:58:08.718 [bookkeeper-ml-workers-OrderedExecutor-3-0:org.apache.bookkeeper.mledger.impl.OpAddEntry@164] INFO  org.apache.bookkeeper.mledger.impl.OpAddEntry - [my_test_ledger] Closing ledger 13 for being full
```

**Comment by sijie** [comment]
@merlimat fixed it at #2694
