### ISSUE TITLE
NPE at RoundRobinScheduler

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#2743]
```
java.lang.NullPointerException: null
    at org.apache.pulsar.functions.worker.scheduler.RoundRobinScheduler.schedule(RoundRobinScheduler.java:46) ~[org.apache.pulsar-pulsar-functions-worker-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
    at org.apache.pulsar.functions.worker.SchedulerManager.invokeScheduler(SchedulerManager.java:208) ~[org.apache.pulsar-pulsar-functions-worker-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
    at org.apache.pulsar.functions.worker.SchedulerManager.lambda$schedule$0(SchedulerManager.java:139) ~[org.apache.pulsar-pulsar-functions-worker-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_181]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_181]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
00:14:32.907 [pulsar-web-30-17] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [08/Oct/2018:00:14:32 +0000] "GET //127.0.0.1:8080/admin/v2/persistent/public/functions/coordinate/stats HTTP/1.1" 200 1500 "-" "Jersey/2.25 (HttpUrlConnection 1.8.0_181)" 1
00:14:32.907 [pulsar-worker-2-5] WARN  org.apache.pulsar.functions.worker.SchedulerManager - Failed to invoke scheduler
java.lang.NullPointerException: null
    at org.apache.pulsar.functions.worker.scheduler.RoundRobinScheduler.schedule(RoundRobinScheduler.java:46) ~[org.apache.pulsar-pulsar-functions-worker-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
    at org.apache.pulsar.functions.worker.SchedulerManager.invokeScheduler(SchedulerManager.java:208) ~[org.apache.pulsar-pulsar-functions-worker-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
    at org.apache.pulsar.functions.worker.SchedulerManager.lambda$schedule$0(SchedulerManager.java:139) ~[org.apache.pulsar-pulsar-functions-worker-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_181]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_181]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
00:14:32.907 [pulsar-web-30-20] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [08/Oct/2018:00:14:32 +0000] "GET //127.0.0.1:8080/admin/v2/persistent/public/functions/coordinate/stats HTTP/1.1" 200 1500 "-" "Jersey/2.25 (HttpUrlConnection 1.8.0_181)" 0
00:14:32.907 [pulsar-worker-2-5] WARN  org.apache.pulsar.functions.worker.SchedulerManager - Failed to invoke scheduler
java.lang.NullPointerException: null
    at org.apache.pulsar.functions.worker.scheduler.RoundRobinScheduler.schedule(RoundRobinScheduler.java:46) ~[org.apache.pulsar-pulsar-functions-worker-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
    at org.apache.pulsar.functions.worker.SchedulerManager.invokeScheduler(SchedulerManager.java:208) ~[org.apache.pulsar-pulsar-functions-worker-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
    at org.apache.pulsar.functions.worker.SchedulerManager.lambda$schedule$0(SchedulerManager.java:139) ~[org.apache.pulsar-pulsar-functions-worker-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_181]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_181]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
    at java.util.concurrent.ThreadPoolExecutor$Worker^C8.jar:2.2.0-SNAPSHOT]
    at org.apache.pulsar.functions.worker.SchedulerManager.lambda$schedule$0(SchedulerManager.java:139) ~[org.apache.pulsar-pulsar-functions-worker-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_181]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_181]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
00:14:32.908 [pulsar-web-30-23] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [08/Oct/2018:00:14:32 +0000] "GET //127.0.0.1:8080/admin/v2/persistent/public/functions/coordinate/stats HTTP/1.1" 200 1500 "-" "Jersey/2.25 (HttpUrlConnection 1.8.0_181)" 0
00:14:32.908 [pulsar-worker-2-5] WARN  org.apache.pulsar.functions.worker.SchedulerManager - Failed to invoke scheduler
java.lang.NullPointerException: null
    at org.apache.pulsar.functions.worker.scheduler.RoundRobinScheduler.schedule(RoundRobinScheduler.java:46) ~[org.apache.pulsar-pulsar-functions-worker-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
    at org.apache.pulsar.functions.worker.SchedulerManager.invokeScheduler(SchedulerManager.java:208) ~[org.apache.pulsar-pulsar-functions-worker-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
    at org.apache.pulsar.functions.worker.SchedulerManager.lambda$schedule$0(SchedulerManager.java:139) ~[org.apache.pulsar-pulsar-functions-worker-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_181]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_181]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by sijie** [comment]
@srkukarni @jerrypeng can you help look at this?
