### ISSUE TITLE
null payload or property values generated NullPointerException in server

### ISSUE THREAD

**Issue by sfescape** [apache/pulsar#2751]
#### Expected behavior

I expected the server to accept null valued properties and payloads

#### Actual behavior

NullPointerException in base64 processing in the case of payload
NullPointerException in the case of property values being null

java.lang.NullPointerException: null
        at org.apache.pulsar.common.api.proto.PulsarApi$KeyValue$Builder.setValue(PulsarApi.java:1923) ~[org.apache.pulsar-pulsar-common-2.1.1-incubating.jar:2.1.1-incubating]

#### Steps to reproduce

I used the Websocket API to send in a message with either a null payload or property values set to null.

#### System configuration
2.1.1

**Comment by sfescape** [comment]
Not an empty string, a null value. I'm not sure if a base64 encoded empty string works. I can test that later. Here is the null value property stack trace. I'll look to see if I can find the base64 nullpointerexception on payload.

`java.lang.NullPointerException: null
        at org.apache.pulsar.common.api.proto.PulsarApi$KeyValue$Builder.setValue(PulsarApi.java:1923) ~[org.apache.pulsar-pulsar-common-2.1.1-incubating.jar:2.1.1-incubating]
        at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.properties(TypedMessageBuilderImpl.java:84) ~[org.apache.pulsar-pulsar-client-original-2.1.1-incubating.jar:2.1.1-incubating]
        at org.apache.pulsar.websocket.ProducerHandler.onWebSocketText(ProducerHandler.java:179) ~[org.apache.pulsar-pulsar-websocket-2.1.1-incubating.jar:2.1.1-incubating]
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:189) ~[org.eclipse.jetty.websocket-websocket-common-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69) ~[org.eclipse.jetty.websocket-websocket-common-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:66) [org.eclipse.jetty.websocket-websocket-common-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:158) ~[org.eclipse.jetty.websocket-websocket-common-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:162) [org.eclipse.jetty.websocket-websocket-common-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:376) [org.eclipse.jetty.websocket-websocket-common-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.websocket.common.extensions.AbstractExtension.nextIncomingFrame(AbstractExtension.java:176) [org.eclipse.jetty.websocket-websocket-common-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.nextIncomingFrame(PerMessageDeflateExtension.java:105) [org.eclipse.jetty.websocket-websocket-common-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.incomingFrame(PerMessageDeflateExtension.java:70) [org.eclipse.jetty.websocket-websocket-common-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220) [org.eclipse.jetty.websocket-websocket-common-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220) [org.eclipse.jetty.websocket-websocket-common-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:256) [org.eclipse.jetty.websocket-websocket-common-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:679) [org.eclipse.jetty.websocket-websocket-common-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:511) [org.eclipse.jetty.websocket-websocket-common-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [org.eclipse.jetty-jetty-io-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [org.eclipse.jetty-jetty-io-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [org.eclipse.jetty-jetty-io-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [org.eclipse.jetty-jetty-util-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [org.eclipse.jetty-jetty-util-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [org.eclipse.jetty-jetty-util-9.3.11.v20160721.jar:9.3.11.v20160721]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
        at java.lang.Thread.run(Thread.java:748)`

**Comment by sfescape** [comment]
Here is a thread dump for the null payload error.

java.lang.NullPointerException: null
        at java.util.Base64$Decoder.decode(Base64.java:549)
        at org.apache.pulsar.websocket.ProducerHandler.onWebSocketText(ProducerHandler.java:158) ~[org.apache.pulsar-pulsar-websocket-2.1.1-incubating.jar:2.1.1-incubating]
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:189) ~[org.eclipse.jetty.websocket-websocket-common-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69) ~[org.eclipse.jetty.websocket-websocket-common-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:66) [org.eclipse.jetty.websocket-websocket-common-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:158) ~[org.eclipse.jetty.websocket-websocket-common-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:162) [org.eclipse.jetty.websocket-websocket-common-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:376) [org.eclipse.jetty.websocket-websocket-common-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.websocket.common.extensions.AbstractExtension.nextIncomingFrame(AbstractExtension.java:176) [org.eclipse.jetty.websocket-websocket-common-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.nextIncomingFrame(PerMessageDeflateExtension.java:105) [org.eclipse.jetty.websocket-websocket-common-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.incomingFrame(PerMessageDeflateExtension.java:70) [org.eclipse.jetty.websocket-websocket-common-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220) [org.eclipse.jetty.websocket-websocket-common-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220) [org.eclipse.jetty.websocket-websocket-common-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:256) [org.eclipse.jetty.websocket-websocket-common-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:679) [org.eclipse.jetty.websocket-websocket-common-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:511) [org.eclipse.jetty.websocket-websocket-common-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [org.eclipse.jetty-jetty-io-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [org.eclipse.jetty-jetty-io-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [org.eclipse.jetty-jetty-io-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [org.eclipse.jetty-jetty-util-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [org.eclipse.jetty-jetty-util-9.3.11.v20160721.jar:9.3.11.v20160721]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [org.eclipse.jetty-jetty-util-9.3.11.v20160721.jar:9.3.11.v20160721]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
        at java.lang.Thread.run(Thread.java:748)

**Comment by jiazhai** [comment]
```NullPointerException in the case of property values being null```
This is related to protobuf, it does not support null-able field directly.
https://github.com/protocolbuffers/protobuf/issues/1606

**Comment by sijie** [comment]
@jiazhai we might add some valiations before this method is called.

**Comment by sijie** [comment]
This is fixed by #3034
