### ISSUE TITLE
namespace grant-permission Returns 500 in 2.1.1-incubating

### ISSUE THREAD

**Issue by oliverisaac** [apache/pulsar#2795]
#### Expected behavior

The below command should return successfully: 

`pulsar-admin namespaces grant-permission public/pulsar-gke/default --actions produce,consume --role oisaac`

#### Actual behavior

The broker server returns a 500 server error.

#### Steps to reproduce

I deployed a fresh cluster using the GKE deployment method. When enabling authentication and authorization I am unable to grant permissions to roles. Other admin actions work.

I was able to get this working in 2.1.0-incubating.

#### System configuration
**Pulsar version**: 2.1.1-incubating
Client: google container engine running kubernetes.

#### Error Log:

```
15:32:11.815 [pulsar-web-28-7] INFO  org.eclipse.jetty.server.RequestLog - 10.202.240.8 - - [12/Oct/2018:15:32:11 +0000] "POST https://10.202.240.14:8443/admin/namespaces/translators/pulsar-gke/default/permissions/oisaac HTTP/1.1" 500 389 "-" "curl/7.54.0" 128
javax.servlet.ServletException: javax.servlet.ServletException: java.lang.NullPointerException
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:139) ~[org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) ~[org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.Server.handle(Server.java:524) ~[org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319) [org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253) [org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [org.eclipse.jetty-jetty-io-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [org.eclipse.jetty-jetty-io-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:202) [org.eclipse.jetty-jetty-io-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [org.eclipse.jetty-jetty-io-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [org.eclipse.jetty-jetty-io-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [org.eclipse.jetty-jetty-io-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [org.eclipse.jetty-jetty-util-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [org.eclipse.jetty-jetty-util-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [org.eclipse.jetty-jetty-util-9.3.11.v20160721.jar:9.3.11.v20160721]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]Caused by: javax.servlet.ServletException: java.lang.NullPointerException
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:489) ~[org.glassfish.jersey.containers-jersey-container-servlet-core-2.25.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427) ~[org.glassfish.jersey.containers-jersey-container-servlet-core-2.25.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388) ~[org.glassfish.jersey.containers-jersey-container-servlet-core-2.25.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341) ~[org.glassfish.jersey.containers-jersey-container-servlet-core-2.25.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228) ~[org.glassfish.jersey.containers-jersey-container-servlet-core-2.25.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) ~[org.eclipse.jetty-jetty-servlet-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689) ~[org.eclipse.jetty-jetty-servlet-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.apache.pulsar.broker.web.ResponseHandlerFilter.doFilter(ResponseHandlerFilter.java:53) ~[org.apache.pulsar-pulsar-broker-2.1.1-incubating.jar:2.1.1-incubating]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676) ~[org.eclipse.jetty-jetty-servlet-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.apache.pulsar.broker.web.AuthenticationFilter.doFilter(AuthenticationFilter.java:74) ~[org.apache.pulsar-pulsar-broker-common-2.1.1-incubating.jar:2.1.1-incubating]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676) ~[org.eclipse.jetty-jetty-servlet-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581) ~[org.eclipse.jetty-jetty-servlet-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224) ~[org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) ~[org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511) ~[org.eclipse.jetty-jetty-servlet-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) ~[org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) ~[org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213) ~[org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119) ~[org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	... 17 moreCaused by: java.lang.NullPointerException
	at org.apache.pulsar.broker.admin.impl.NamespacesBase.internalGrantPermissionOnNamespace(NamespacesBase.java:301) ~[org.apache.pulsar-pulsar-broker-2.1.1-incubating.jar:2.1.1-incubating]
	at org.apache.pulsar.broker.admin.v1.Namespaces.grantPermissionOnNamespace(Namespaces.java:231) ~[org.apache.pulsar-pulsar-broker-2.1.1-incubating.jar:2.1.1-incubating]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[org.glassfish.jersey.core-jersey-server-2.25.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[org.glassfish.jersey.core-jersey-server-2.25.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[org.glassfish.jersey.core-jersey-server-2.25.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:143) ~[org.glassfish.jersey.core-jersey-server-2.25.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[org.glassfish.jersey.core-jersey-server-2.25.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[org.glassfish.jersey.core-jersey-server-2.25.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[org.glassfish.jersey.core-jersey-server-2.25.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[org.glassfish.jersey.core-jersey-server-2.25.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) ~[org.glassfish.jersey.core-jersey-server-2.25.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) ~[org.glassfish.jersey.core-jersey-common-2.25.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) ~[org.glassfish.jersey.core-jersey-common-2.25.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[org.glassfish.jersey.core-jersey-common-2.25.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[org.glassfish.jersey.core-jersey-common-2.25.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) ~[org.glassfish.jersey.core-jersey-common-2.25.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) ~[org.glassfish.jersey.core-jersey-common-2.25.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) ~[org.glassfish.jersey.core-jersey-server-2.25.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) ~[org.glassfish.jersey.core-jersey-server-2.25.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473) ~[org.glassfish.jersey.containers-jersey-container-servlet-core-2.25.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427) ~[org.glassfish.jersey.containers-jersey-container-servlet-core-2.25.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388) ~[org.glassfish.jersey.containers-jersey-container-servlet-core-2.25.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341) ~[org.glassfish.jersey.containers-jersey-container-servlet-core-2.25.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228) ~[org.glassfish.jersey.containers-jersey-container-servlet-core-2.25.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) ~[org.eclipse.jetty-jetty-servlet-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689) ~[org.eclipse.jetty-jetty-servlet-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.apache.pulsar.broker.web.ResponseHandlerFilter.doFilter(ResponseHandlerFilter.java:53) ~[org.apache.pulsar-pulsar-broker-2.1.1-incubating.jar:2.1.1-incubating]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676) ~[org.eclipse.jetty-jetty-servlet-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.apache.pulsar.broker.web.AuthenticationFilter.doFilter(AuthenticationFilter.java:74) ~[org.apache.pulsar-pulsar-broker-common-2.1.1-incubating.jar:2.1.1-incubating]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676) ~[org.eclipse.jetty-jetty-servlet-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581) ~[org.eclipse.jetty-jetty-servlet-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224) ~[org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) ~[org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511) ~[org.eclipse.jetty-jetty-servlet-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) ~[org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) ~[org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213) ~[org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119) ~[org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	... 17 more
15:32:11.810 [pulsar-web-28-7] WARN  org.eclipse.jetty.server.HttpChannel - https://10.202.240.14:8443/admin/namespaces/translators/pulsar-gke/default/permissions/oisaac
javax.servlet.ServletException: java.lang.NullPointerException
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:489) ~[org.glassfish.jersey.containers-jersey-container-servlet-core-2.25.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427) ~[org.glassfish.jersey.containers-jersey-container-servlet-core-2.25.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388) ~[org.glassfish.jersey.containers-jersey-container-servlet-core-2.25.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341) ~[org.glassfish.jersey.containers-jersey-container-servlet-core-2.25.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228) ~[org.glassfish.jersey.containers-jersey-container-servlet-core-2.25.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) ~[org.eclipse.jetty-jetty-servlet-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689) ~[org.eclipse.jetty-jetty-servlet-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.apache.pulsar.broker.web.ResponseHandlerFilter.doFilter(ResponseHandlerFilter.java:53) ~[org.apache.pulsar-pulsar-broker-2.1.1-incubating.jar:2.1.1-incubating]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676) ~[org.eclipse.jetty-jetty-servlet-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.apache.pulsar.broker.web.AuthenticationFilter.doFilter(AuthenticationFilter.java:74) ~[org.apache.pulsar-pulsar-broker-common-2.1.1-incubating.jar:2.1.1-incubating]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676) ~[org.eclipse.jetty-jetty-servlet-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581) [org.eclipse.jetty-jetty-servlet-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224) [org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511) [org.eclipse.jetty-jetty-servlet-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213) [org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119) [org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.Server.handle(Server.java:524) [org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319) [org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253) [org.eclipse.jetty-jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [org.eclipse.jetty-jetty-io-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [org.eclipse.jetty-jetty-io-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:202) [org.eclipse.jetty-jetty-io-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [org.eclipse.jetty-jetty-io-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [org.eclipse.jetty-jetty-io-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [org.eclipse.jetty-jetty-io-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [org.eclipse.jetty-jetty-util-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [org.eclipse.jetty-jetty-util-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [org.eclipse.jetty-jetty-util-9.3.11.v20160721.jar:9.3.11.v20160721]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]Caused by: java.lang.NullPointerException
	at org.apache.pulsar.broker.admin.impl.NamespacesBase.internalGrantPermissionOnNamespace(NamespacesBase.java:301) ~[org.apache.pulsar-pulsar-broker-2.1.1-incubating.jar:2.1.1-incubating]
	at org.apache.pulsar.broker.admin.v1.Namespaces.grantPermissionOnNamespace(Namespaces.java:231) ~[org.apache.pulsar-pulsar-broker-2.1.1-incubating.jar:2.1.1-incubating]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[org.glassfish.jersey.core-jersey-server-2.25.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[org.glassfish.jersey.core-jersey-server-2.25.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[org.glassfish.jersey.core-jersey-server-2.25.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:143) ~[org.glassfish.jersey.core-jersey-server-2.25.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[org.glassfish.jersey.core-jersey-server-2.25.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[org.glassfish.jersey.core-jersey-server-2.25.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[org.glassfish.jersey.core-jersey-server-2.25.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[org.glassfish.jersey.core-jersey-server-2.25.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) ~[org.glassfish.jersey.core-jersey-server-2.25.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) ~[org.glassfish.jersey.core-jersey-common-2.25.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) ~[org.glassfish.jersey.core-jersey-common-2.25.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[org.glassfish.jersey.core-jersey-common-2.25.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[org.glassfish.jersey.core-jersey-common-2.25.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) ~[org.glassfish.jersey.core-jersey-common-2.25.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) ~[org.glassfish.jersey.core-jersey-common-2.25.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) ~[org.glassfish.jersey.core-jersey-server-2.25.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) ~[org.glassfish.jersey.core-jersey-server-2.25.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473) ~[org.glassfish.jersey.containers-jersey-container-servlet-core-2.25.jar:?]
	... 36 more
```

**Comment by rsamo** [comment]
This bug is also happening on my end, v2.1.1 on bare metal installation. Just an FYI.

**Comment by sijie** [comment]
@oliverisaac did you try @rsamo 's suggestion?

**Comment by oliverisaac** [comment]
Yup, good to go!
