### ISSUE TITLE
Dependencies for using Pulsar in Storm topologies

### ISSUE THREAD

**Issue by jnioche** [apache/pulsar#2890]
**Pulsar version**: 2.2.0

I build an uber jar for a Storm toplogy containing the following dependency as per http://pulsar.apache.org/docs/latest/adaptors/PulsarStorm/

```
    <properties>
		<pulsar.version>2.2.0</pulsar.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.apache.pulsar</groupId>
			<artifactId>pulsar-storm</artifactId>
			<version>${pulsar.version}</version>
		</dependency>
	</dependencies>
```

am getting  

```
13900 [pulsar-client-io-3-1] WARN  o.a.p.c.i.ClientCnx - [localhost/127.0.0.1:6650] Got exception NoClassDefFoundError : org/asynchttpclient/channel/KeepAliveStrategy
java.lang.NoClassDefFoundError: org/asynchttpclient/channel/KeepAliveStrategy
	at org.apache.pulsar.client.impl.ClientCnx.newConnectCommand(ClientCnx.java:171) ~[pulsar-1.0-SNAPSHOT.jar:?]
	at org.apache.pulsar.client.impl.ClientCnx.channelActive(ClientCnx.java:151) ~[pulsar-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [pulsar-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [pulsar-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [pulsar-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [pulsar-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [pulsar-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [pulsar-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [pulsar-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1402) [pulsar-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [pulsar-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [pulsar-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:921) [pulsar-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.fulfillConnectPromise(AbstractEpollChannel.java:616) [pulsar-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:649) [pulsar-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:525) [pulsar-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394) [pulsar-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [pulsar-1.0-SNAPSHOT.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [pulsar-1.0-SNAPSHOT.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [pulsar-1.0-SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

so I added the following dependency explicitly

```
		<dependency>
			<groupId>org.asynchttpclient</groupId>
			<artifactId>async-http-client</artifactId>
			<version>2.1.0-alpha26</version>
		</dependency>
```
which seems to solve this particular problem. Shouldn't the documentation list that dependency?

Am then getting an endless stream of errors in the logs

```
72085 [pulsar-timer-8-1] WARN  o.a.p.c.i.ProducerImpl - [persistent://public/crawl/in-partition-8] [crawler-1-1540895529_0] error while closing out batch -- java.lang.NoSuchMethodError: com.scurrilous.circe.checksum.Crc32cIntChecksum.computeChecksum(Lio/netty/buffer/ByteBuf;)I
72086 [pulsar-timer-9-1] WARN  o.a.p.c.i.ProducerImpl - [persistent://public/crawl/in-partition-5] [crawler-1-1540895529_1] error while closing out batch -- java.lang.NoSuchMethodError: com.scurrilous.circe.checksum.Crc32cIntChecksum.computeChecksum(Lio/netty/buffer/ByteBuf;)I
72086 [pulsar-timer-8-1] WARN  o.a.p.c.i.ProducerImpl - [persistent://public/crawl/in-partition-6] [crawler-1-1540895529_0] error while closing out batch -- java.lang.NoSuchMethodError: com.scurrilous.circe.checksum.Crc32cIntChecksum.computeChecksum(Lio/netty/buffer/ByteBuf;)I
72086 [pulsar-timer-9-1] WARN  o.a.p.c.i.ProducerImpl - [persistent://public/crawl/in-partition-1] [crawler-1-1540895529_1] error while closing out batch -- java.lang.NoSuchMethodError: com.scurrilous.circe.checksum.Crc32cIntChecksum.computeChecksum(Lio/netty/buffer/ByteBuf;)I
```

I checked the dependencies and that class and method seem to be there. Any idea?

See https://github.com/DigitalPebble/storm-crawler/tree/pulsar/external/pulsar for the code I wrote based on your Storm adaptor. Thanks!

**Comment by jnioche** [comment]
The exception is thrown here

https://github.com/apache/pulsar/blob/b6a25f034bd8a9c3b30aa4a90eefdd45a0f0ee67/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java#L451

```
Thread [pulsar-timer-10-1] (Suspended (breakpoint at line 948 in Commands))	
	owns: ProducerImpl<T>  (id=1217043)	
	Commands.serializeCommandSendWithSize(PulsarApi$BaseCommand$Builder, Commands$ChecksumType, PulsarApi$MessageMetadata, ByteBuf) line: 948	
	Commands.newSend(long, long, int, Commands$ChecksumType, PulsarApi$MessageMetadata, ByteBuf) line: 315	
	ProducerImpl<T>.sendMessage(long, long, int, PulsarApi$MessageMetadata, ByteBuf) line: 451	
	ProducerImpl<T>.batchMessageAndSend() line: 1291	
	ProducerImpl<T>.access$500(ProducerImpl) line: 78	
	ProducerImpl$2.run(Timeout) line: 1248	
	HashedWheelTimer$HashedWheelTimeout.expire() line: 663	
	HashedWheelTimer$HashedWheelBucket.expireTimeouts(long) line: 738	
	HashedWheelTimer$Worker.run() line: 466	
	FastThreadLocalRunnable.run() line: 30	
	FastThreadLocalThread(Thread).run() line: 748	

```

I can see that the library we are using at runtime contains 

  _public static int computeChecksum(org.apache.pulsar.shade.io.netty.buffer.ByteBuf payload);_

whereas it is complaining about the lack of this signature

`Crc32cIntChecksum.computeChecksum(Lio/netty/buffer/ByteBuf;)I`

Could this be shading related?

**Comment by jnioche** [comment]
I tried reproducing the content of https://github.com/apache/pulsar/blob/b6a25f034bd8a9c3b30aa4a90eefdd45a0f0ee67/pom.xml

by setting 
```
		<dependency>
			<groupId>org.asynchttpclient</groupId>
			<artifactId>async-http-client</artifactId>
			<version>2.1.0-alpha26</version>
			<exclusions>
				<exclusion>
					<groupId>io.netty</groupId>
					<artifactId>*</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```

but it did not make any difference

**Comment by sijie** [comment]
@jnioche thank you for reporting this. will work on a fix.
