### ISSUE TITLE
Intermittent failure in PulsarFunctionsThreadTest.testAutoSchemaFunction

### ISSUE THREAD

**Issue by merlimat** [apache/pulsar#3012]
After adding integration tests timeout, it appears that this test is the once that never completes.

Consumer is stuck on receiving from the output topic.

https://builds.apache.org/job/pulsar_precommit_integrationtests/4932/

```
2018-11-18\T\17:16:35.565 [ERROR] pulsar-test-suite(org.apache.pulsar.tests.integration.functions.PulsarFunctionsThreadTest)  Time elapsed: 120.019 s  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testAutoSchemaFunction() didn't finish within the time-out 120000
	at org.apache.pulsar.common.util.collections.GrowableArrayBlockingQueue.take(GrowableArrayBlockingQueue.java:179)
	at org.apache.pulsar.client.impl.ConsumerImpl.internalReceive(ConsumerImpl.java:296)
	at org.apache.pulsar.client.impl.ConsumerBase.receive(ConsumerBase.java:111)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.publishAndConsumeAvroMessages(PulsarFunctionsTest.java:994)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testAutoSchemaFunction(PulsarFunctionsTest.java:961)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by tisonkun** [comment]
@codelipenghui may you add a brief comment about why we close these issues? Cannot be reproduced on master? It would be better then silently close these issues :)

**Comment by cbornet** [comment]
See #17353
