### ISSUE TITLE
Get stats on a exist topic but got topic not found error

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#3042]
#### Expected behavior

Get a blank stats data rather than `Topic not found` error by `get partitioned stats` or `get stats` on a topic when topic have no stats data on broker.

#### Actual behavior

The topic is already created but no message in or out will get a error of `Topic not found` by get stats rest api or admin cli.

```
--- An unexpected error occurred in the server ---

Message: Topic not found

Stacktrace:

org.apache.pulsar.client.admin.PulsarAdminException$NotFoundException: Topic not found
	at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:172)
	at org.apache.pulsar.client.admin.internal.TopicsImpl$9.failed(TopicsImpl.java:403)
	at org.glassfish.jersey.client.JerseyInvocation$7.failed(JerseyInvocation.java:965)
	at org.glassfish.jersey.client.JerseyInvocation$7.completed(JerseyInvocation.java:952)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:196)
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:74)
	at org.glassfish.jersey.client.ClientRuntime$2$1$1.run(ClientRuntime.java:166)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$2$1.response(ClientRuntime.java:164)
	at org.glassfish.jersey.client.internal.HttpUrlConnector$3.run(HttpUrlConnector.java:297)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at jersey.repackaged.com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:50)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:37)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:293)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:180)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:208)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1020)
	at org.glassfish.jersey.client.JerseyInvocation.access$900(JerseyInvocation.java:92)
	... 32 more
```

#### Steps to reproduce

1. Create a new topic
2. $ ./pulsar-admin topics stats {topic_name}

#### System configuration
**Pulsar version**: 2.1.0-incubating and 2.2.0

**Comment by sijie** [comment]
@codelipenghui it sounds like there is no stats available for that topic. so it might be a simple fix to return some empty stats object instead of "topic not found". are you working on a fix for it?

**Comment by codelipenghui** [comment]
@sijie I will fix it later

**Comment by codelipenghui** [comment]
@sijie Topics will auto delete while no active client and subscriptions.  I have already made a PR #3111 to improve the user prompts.

**Comment by jiazhai** [comment]
#3111 merged, would like to close this issue.
