### ISSUE TITLE
Client send timeout happens on one broker

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#3056]
1. 2018.11.25 11:00:00 Restart bookie node in the cluster. some topic's producer send message timeout. After restart all brokers, most problem topic get right, but almost 3 topic still with problem. Then found problem topics owner broker is same, so we restart the broker again. All topics get right.
2. 2018.11.26 18:48:30 Two topic can't write again, after check topic's owner broker, still same broker, after restart the broker, problem topics get right.

Some logs at that time:
```
17:08:31.717 [pulsar-io-21-95] INFO  org.apache.pulsar.broker.service.ServerCnx - [/172.30.151.122:44388] Subscribing on topic persistent://platform/passport/user.login-partition-0 / b.userbehavior.user.login
17:08:31.717 [pulsar-io-21-95] INFO  org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://platform/passport/user.login-partition-0][b.userbehavior.user.login] Created new subscription for 32
17:08:31.717 [pulsar-io-21-95] INFO  org.apache.pulsar.broker.service.ServerCnx - [/172.30.151.122:44388] Created subscription on topic persistent://platform/passport/user.login-partition-0 / b.userbehavior.user.login
17:09:31.712 [pulsar-io-21-95] INFO  org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers - Removed consumer Consumer{subscription=PersistentSubscription{topic=persistent://platform/passport/user.login-partition-0, name=b.userbehavior.user.login}, consumerId=32, consumerName=e9317, address=/172.30.151.122:44388} with pending 117 acks
```
Error log on log.bk
```
18:59:05.091 [BookKeeperClientScheduler-OrderedScheduler-0-0] ERROR org.apache.bookkeeper.common.util.SafeRunnable - Unexpected throwable caught
java.lang.IllegalArgumentException: negative size: -1
 at com.google.common.base.Preconditions.badPositionIndex(Preconditions.java:1231) ~[com.google.guava-guava-21.0.jar:?]
 at com.google.common.base.Preconditions.checkPositionIndex(Preconditions.java:1222) ~[com.google.guava-guava-21.0.jar:?]
 at com.google.common.base.Preconditions.checkPositionIndex(Preconditions.java:1204) ~[com.google.guava-guava-21.0.jar:?]
 at com.google.common.collect.LinkedListMultimap$NodeIterator.<init>(LinkedListMultimap.java:327) ~[com.google.guava-guava-21.0.jar:?]
 at com.google.common.collect.LinkedListMultimap$1ValuesImpl.listIterator(LinkedListMultimap.java:760) ~[com.google.guava-guava-21.0.jar:?]
 at java.util.AbstractList.listIterator(AbstractList.java:299) ~[?:1.8.0_181]
 at java.util.AbstractSequentialList.iterator(AbstractSequentialList.java:239) ~[?:1.8.0_181]
 at org.apache.bookkeeper.proto.PerChannelBookieClient.checkTimeoutOnPendingOperations(PerChannelBookieClient.java:803) ~[org.apache.bookkeeper-bookkeeper-server-4.7.1.jar:4.7.1]
 at org.apache.bookkeeper.proto.DefaultPerChannelBookieClientPool.checkTimeoutOnPendingOperations(DefaultPerChannelBookieClientPool.java:100) ~[org.apache.bookkeeper-bookkeeper-server-4.7.1.jar:4.7.1]
```
Client send timeout stats:
https://files.slack.com/files-pri/T5Z3B324U-FEB7PR341/image.png

**Comment by codelipenghui** [comment]
After check the broker dump, found some thing strange in current ledger of topic

1. lastAddPushed = 529 and lastAddConfirmed = -1
2. paddingAddOps has 530 elements

Here is the screenshot in yourkit

![image](https://user-images.githubusercontent.com/12592133/49053331-abd1c600-f22a-11e8-93e4-8b1dac494891.png)

And the broker dump file already upload to the slack:

https://apache-pulsar.slack.com/files/UC0BYCXKQ/FEB7C71U0/heap.bin.tar.gz.zip

**Comment by jiazhai** [comment]
@ivankelly
Regarding the Bk logs above, Do you think it is related with your fix: https://github.com/apache/bookkeeper/pull/1569

Through upgrade to latest pulsar, which contains your fix, would solve this issue, @codelipenghui is trying to get the reason of this issue.

**Comment by sijie** [comment]
@jiazhai I think the issue here is related to apache/bookkeeper#1569. 

![screen shot 2018-11-27 at 12 11 25 am](https://user-images.githubusercontent.com/1217863/49067864-05f66b00-f1da-11e8-9d39-dbdb37e1e269.png)

![screen shot 2018-11-27 at 12 19 28 am](https://user-images.githubusercontent.com/1217863/49067916-26bec080-f1da-11e8-954f-e1f33823e5c5.png)


in the heap dump, you can see one of the PerChannelBookieClient retains a lot of items in `completionObjects`, which they event weren't timed out because the race condition in apache/bookkeeper#1569 could cause NPE and IllegalArgumentException (all kind of runtime exceptions). 

The suggestion here is to upgrade Pulsar to 2.2.0, which contains the bookkeeper fix.

**Comment by ivankelly** [comment]
v2.1.1 has the fix also, if they want a less disruptive upgrade .
