### ISSUE TITLE
Maven Build Error 2.2.0 Linux

### ISSUE THREAD

**Issue by drdrill** [apache/pulsar#3069]
#### Expected behavior

Successful error free build

#### Actual behavior
Build failure.  
Note: Added to properties section in project level pom.xml file, but had no effect on the outcome
    <assembly.tarLongFileMode>posix</assembly.tarLongFileMode>

[INFO] Building tar: /home/user/apache-pulsar-2.2.0/apache-pulsar-2.2.0/pulsar-sql/presto-distribution/target/pulsar-presto-distribution.tar.gz
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Pulsar Build Tools ................................. SUCCESS [  1.964 s]
[INFO] Pulsar ............................................. SUCCESS [  1.315 s]
[INFO] Pulsar Common ...................................... SUCCESS [  9.323 s]
[INFO] Managed Ledger ..................................... SUCCESS [  6.981 s]
[INFO] Managed Ledger ..................................... SUCCESS [ 16.139 s]
[INFO] Apache Pulsar :: Jclouds shaded .................... SUCCESS [  2.319 s]
[INFO] Apache Pulsar :: Tiered Storage :: Parent .......... SUCCESS [  0.039 s]
[INFO] Apache Pulsar :: Tiered Storage :: JCloud .......... SUCCESS [  5.108 s]
[INFO] Pulsar ZooKeeper Utils ............................. SUCCESS [  5.013 s]
[INFO] pulsar-broker-common ............................... SUCCESS [  1.579 s]
[INFO] Pulsar Functions :: Parent ......................... SUCCESS [  0.040 s]
[INFO] Pulsar Functions :: Proto .......................... SUCCESS [  2.572 s]
[INFO] Pulsar Client Schema ............................... SUCCESS [  8.751 s]
[INFO] Pulsar Functions :: API ............................ SUCCESS [  0.520 s]
[INFO] Pulsar IO :: Parent ................................ SUCCESS [  0.034 s]
[INFO] Pulsar IO :: IO .................................... SUCCESS [  0.501 s]
[INFO] Pulsar Client Java ................................. SUCCESS [  3.458 s]
[INFO] Pulsar Discovery Service WAR ....................... SUCCESS [  2.432 s]
[INFO] Pulsar WebSocket ................................... SUCCESS [  2.361 s]
[INFO] Pulsar Client Admin Original ....................... SUCCESS [  1.611 s]
[INFO] Pulsar Functions :: Utils .......................... SUCCESS [  2.284 s]
[INFO] Pulsar Functions :: Instance ....................... SUCCESS [  3.004 s]
[INFO] Pulsar Functions :: Metrics ........................ SUCCESS [  4.127 s]
[INFO] Pulsar Functions :: Runtime ........................ SUCCESS [  2.149 s]
[INFO] Pulsar Functions :: Worker ......................... SUCCESS [  4.020 s]
[INFO] Pulsar Broker ...................................... SUCCESS [ 22.488 s]
[INFO] Pulsar Shaded Broker ............................... SUCCESS [ 47.586 s]
[INFO] Pulsar Client Java ................................. SUCCESS [ 10.479 s]
[INFO] Pulsar Client Admin ................................ SUCCESS [  9.834 s]
[INFO] Pulsar IO :: Cassandra ............................. SUCCESS [  1.527 s]
[INFO] Pulsar IO :: Twitter ............................... SUCCESS [  1.501 s]
[INFO] Pulsar Client Tools ................................ SUCCESS [  4.137 s]
[INFO] Pulsar Client Tools Test ........................... SUCCESS [  2.073 s]
[INFO] Pulsar Proxy ....................................... SUCCESS [  2.890 s]
[INFO] Pulsar Storm adapter ............................... SUCCESS [  2.421 s]
[INFO] Pulsar Flink Connectors ............................ SUCCESS [  2.159 s]
[INFO] Spark Streaming Pulsar Receivers ................... SUCCESS [  5.516 s]
[INFO] Pulsar Test Client ................................. SUCCESS [  2.228 s]
[INFO] pulsar-broker-auth-athenz .......................... SUCCESS [  2.087 s]
[INFO] pulsar-client-auth-athenz .......................... SUCCESS [  0.826 s]
[INFO] Pulsar Kafka compatibility ......................... SUCCESS [  0.030 s]
[INFO] Pulsar Kafka compatibility :: API (original) ....... SUCCESS [  0.478 s]
[INFO] Pulsar Kafka compatibility :: API .................. SUCCESS [ 13.622 s]
[INFO] Pulsar Kafka compatibility :: Tests ................ SUCCESS [  0.677 s]
[INFO] pulsar-zookeeper ................................... SUCCESS [  1.703 s]
[INFO] Pulsar Log4j2 Appender ............................. SUCCESS [  0.761 s]
[INFO] Pulsar SQL :: Parent ............................... SUCCESS [  0.028 s]
[INFO] Pulsar SQL :: Pulsar Presto Connector Packaging .... SUCCESS [  2.120 s]
[INFO] Pulsar SQL :: Pulsar Presto Connector .............. SUCCESS [  5.357 s]
[INFO] Pulsar SQL :: Pulsar Presto Distribution ........... FAILURE [ 15.494 s]
[INFO] Pulsar Functions :: Proto-shaded ................... SKIPPED
[INFO] Pulsar Functions :: API Examples ................... SKIPPED
[INFO] Pulsar Functions :: Runtime Shaded ................. SKIPPED
[INFO] Pulsar Functions :: Runtime All .................... SKIPPED
[INFO] Pulsar IO :: Aerospike ............................. SKIPPED
[INFO] Pulsar IO :: Kafka ................................. SKIPPED
[INFO] Pulsar IO :: RabbitMQ .............................. SKIPPED
[INFO] Pulsar IO :: Kinesis ............................... SKIPPED
[INFO] Pulsar IO :: Hdfs .................................. SKIPPED
[INFO] Pulsar IO :: Jdbc .................................. SKIPPED
[INFO] Pulsar IO :: Data Generator ........................ SKIPPED
[INFO] Pulsar IO :: ElasticSearch ......................... SKIPPED
[INFO] Pulsar IO :: Kafka Connect Adaptor ................. SKIPPED
[INFO] Pulsar IO :: Debezium .............................. SKIPPED
[INFO] Pulsar Examples :: Parent .......................... SKIPPED
[INFO] Pulsar Examples :: Flink Consumer Source ........... SKIPPED
[INFO] Pulsar :: Distribution ............................. SKIPPED
[INFO] Pulsar :: Distribution :: Server ................... SKIPPED
[INFO] Pulsar :: Distribution :: IO ....................... SKIPPED
[INFO] Pulsar :: Distribution :: Offloader ................ SKIPPED
[INFO] Apache Pulsar :: Docker Images ..................... SKIPPED
[INFO] Apache Pulsar :: Docker Images :: Pulsar Latest Version SKIPPED
[INFO] Apache Pulsar :: Docker Images :: Grafana .......... SKIPPED
[INFO] Apache Pulsar :: Docker Images :: Pulsar Latest Version (Include All Components) SKIPPED
[INFO] Apache Pulsar :: Docker Images :: Pulsar Standalone  SKIPPED
[INFO] Apache Pulsar :: Tests ............................. SKIPPED
[INFO] Apache Pulsar :: Tests :: Docker Images ............ SKIPPED
[INFO] Apache Pulsar :: Tests :: Docker Images :: Latest Version Testing SKIPPED
[INFO] Apache Pulsar :: Tests :: Integration .............. SKIPPED
[INFO] Apache Pulsar :: Tests :: Pulsar Kafka Compat Client Tests SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:07 min
[INFO] Finished at: 2018-11-27T11:25:23-05:00
[INFO] Final Memory: 396M/13407M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.6:single (package) on project pulsar-presto-distribution: Execution package of goal org.apache.maven.plugins:maven-assembly-plugin:2.6:single failed: user id '149566858' is too big ( > 2097151 ). -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.6:single (package) on project pulsar-presto-distribution: Execution package of goal org.apache.maven.plugins:maven-assembly-plugin:2.6:single failed: user id '149566858' is too big ( > 2097151 ).
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution package of goal org.apache.maven.plugins:maven-assembly-plugin:2.6:single failed: user id '149566858' is too big ( > 2097151 ).
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: java.lang.RuntimeException: user id '149566858' is too big ( > 2097151 ).
        at org.codehaus.plexus.archiver.commonscompress.archivers.tar.TarArchiveOutputStream.failForBigNumber(TarArchiveOutputStream.java:635)
        at org.codehaus.plexus.archiver.commonscompress.archivers.tar.TarArchiveOutputStream.failForBigNumber(TarArchiveOutputStream.java:626)
        at org.codehaus.plexus.archiver.commonscompress.archivers.tar.TarArchiveOutputStream.failForBigNumbers(TarArchiveOutputStream.java:617)
        at org.codehaus.plexus.archiver.commonscompress.archivers.tar.TarArchiveOutputStream.putArchiveEntry(TarArchiveOutputStream.java:290)
        at org.codehaus.plexus.archiver.tar.TarArchiver.tarFile(TarArchiver.java:312)
        at org.codehaus.plexus.archiver.tar.TarArchiver.execute(TarArchiver.java:171)
        at org.codehaus.plexus.archiver.AbstractArchiver.createArchive(AbstractArchiver.java:916)
        at org.apache.maven.plugin.assembly.archive.archiver.AssemblyProxyArchiver.createArchive(AssemblyProxyArchiver.java:445)
        at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:181)
        at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:484)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pulsar-presto-distribution

#### Steps to reproduce

Run the build process on a clean machine.

#### System configuration
**Pulsar version**: 2.2.0
Oracle Linux Server release 6.10
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Apache Maven 3.3.3

**Comment by jerrypeng** [comment]
https://maven.apache.org/plugins/maven-assembly-plugin/faq.html#tarFileModes

**Comment by jerrypeng** [comment]
@drdrill can you try adding:

<tarLongFileMode>posix</tarLongFileMode>

to the configurations section in the assembly plugin:

https://github.com/apache/pulsar/blob/v2.2.0/pulsar-sql/presto-distribution/pom.xml#L128

Then try rebuilding and see if this solves your issue.  If it does feel free to submit a PR to put this fix in.

**Comment by drdrill** [comment]
Thank you for the suggestion.  It fixed the problem.

**Comment by jerrypeng** [comment]
@drdrill can you submit a PR for this fix?
