### ISSUE TITLE
Go client Reader panics when passing custom StartMessageID 

### ISSUE THREAD

**Issue by tobgu** [apache/pulsar#3180]
#### Expected behavior

I can pass arbitrary type implementing the `pulsar.MessageID` interface in `pulsar.ReaderOptions`when creating a Reader instance.

#### Actual behavior

When I pass a custom type the client library panics:
````
panic: interface conversion: pulsar.MessageID is mypackage.pulsarMessageID, not *pulsar.messageID
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/apache/pulsar/pulsar-client-go/pulsar.createReaderAsync(0xc0002229a0, 0xc0001fe29a, 0x9, 0x0, 0x0, 0xb800a0, 0xc0002fb6e0, 0xc00018dd40, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/apache/pulsar@v2.2.0+incompatible/pulsar-client-go/pulsar/c_reader.go:115 +0x504
github.com/apache/pulsar/pulsar-client-go/pulsar.(*client).CreateReaderAsync(0xc0002229a0, 0xc0001fe29a, 0x9, 0x0, 0x0, 0xb800a0, 0xc0002fb6e0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/apache/pulsar@v2.2.0+incompatible/pulsar-client-go/pulsar/c_client.go:220 +0x65
github.com/apache/pulsar/pulsar-client-go/pulsar.(*client).CreateReader(0xc0002229a0, 0xc0001fe29a, 0x9, 0x0, 0x0, 0xb800a0, 0xc0002fb6e0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/apache/pulsar@v2.2.0+incompatible/pulsar-client-go/pulsar/c_client.go:207 +0xca
````

The culprit is the following line:
```go
// Unchecked type assertion assuming that StartMessageID is of type *messageID
C._pulsar_client_create_reader_async(client.ptr, topic, options.StartMessageID.(*messageID).ptr,
	conf, savePointer(&readerAndCallback{reader, conf, callback}))
```

#### Steps to reproduce
See above

#### System configuration
**Pulsar version**: 2.2
github.com/apache/pulsar v2.2.0+incompatible h1:i2dfg67DNdHRgdzdIiSObTb9VRavAtZStxC4YIySxAI=
github.com/apache/pulsar v2.2.0+incompatible/go.mod h1:7npmYEEu+jEeIMdpGSJwrTxUB86OW/UM5IkJCAyfl5Y=
g

**Comment by wolfstudy** [comment]
@tobgu Sorry missed this issue before.

> panic: interface conversion: pulsar.MessageID is mypackage.pulsarMessageID, not *pulsar.messageID

This problem looks like a go type assertion conversion error 

If you are convenient, can you give me the corresponding code?

**Comment by wolfstudy** [comment]
@tobgu about StartMessageID, we offer the following three ways:

```
// The initial reader positioning is done by specifying a message id. The options are:
	//  * `pulsar.EarliestMessage` : Start reading from the earliest message available in the topic
	//  * `pulsar.LatestMessage` : Start reading from the end topic, only getting messages published after the
	//                           reader was created
	//  * `MessageID` : Start reading from a particular message id, the reader will position itself on that
	//                  specific position. The first message to be read will be the message next to the specified
	//                  messageID
	StartMessageID MessageID
```

you can use it, for example:

```
reader, err := client.CreateReader(ReaderOptions{
		Topic:          "my-reader-topic",
		StartMessageID: LatestMessage,
	})
```

**Comment by tobgu** [comment]
Yes, my  problem was that I tried using a `StartMessageID` that implemented the required interface but which caused the code to blow up on a type assertion.
I never managed to use anything but the predefined `pulsar.EarliestMessage`, `pulsar.LatestMessage`. What I wanted to do was to start at an arbitrary message for which I had previously stored the offset (the byte slice).

**Comment by nitishv** [comment]
Hey @wolfstudy @sijie 

I'm new to this community, but would like to start contributing.
I had a look at the reader code and the type assertion seems incorrect here and must be tested to avoid the panic.
https://github.com/apache/pulsar/blob/master/pulsar-client-go/pulsar/c_reader.go#L118

Value of options.StartMessageID which is of Go Type [MessageID](https://github.com/apache/pulsar/blob/master/pulsar-client-go/pulsar/message.go#L81), will fail to be used as type *[messageID](https://github.com/apache/pulsar/blob/master/pulsar-client-go/pulsar/c_message.go#L39) if the value passed to it is created by anything other than these 2 available defaults https://github.com/apache/pulsar/blob/35bb23520ca0518764952d0a780a50861ee5a0d7/pulsar-client-go/pulsar/message.go#L93

The fix in my opinion would be to test the type assertion, and if it fails, recreate a messageID using its serialized data using this https://github.com/apache/pulsar/blob/35bb23520ca0518764952d0a780a50861ee5a0d7/pulsar-client-go/pulsar/message.go#L87
This will ensure compatibility with *messageID when passing as argument to underlying cgo code.

Let me know if this looks good.

Also, on a separate note, is there any documentation to test go code?
I tried unit testing locally from within the pulsar-client-go and got this error.
Are there some prep steps for the C environment which I'm missing?

```bash
$ go test github.com/apache/pulsar/pulsar-client-go/pulsar -run=TestReader
# github.com/apache/pulsar/pulsar-client-go/pulsar
In file included from pulsar/c_client.go:24:
./c_go_pulsar.h:22:10: fatal error: 'pulsar/c/client.h' file not found
#include <pulsar/c/client.h>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
FAIL    github.com/apache/pulsar/pulsar-client-go/pulsar [build failed]
```

**Comment by wolfstudy** [comment]
Thanks to @nitishv feedback, we will replace `cgo-client` with [native go client](https://github.com/apache/pulsar-client-go), can you try to use [native go client](https://github.com/apache/pulsar-client-go) to see if you will encounter the same problem?

**Comment by nitishv** [comment]
@wolfstudy the same panic happens with native go client

Here's what I tried.

- Added a unit test which creates custom message ID type, satisfying this interface https://github.com/apache/pulsar-client-go/blob/master/pulsar/message.go#L108

```bash
$ git diff pulsar/reader_test.go                                                                                                         
diff --git a/pulsar/reader_test.go b/pulsar/reader_test.go                                                                                                                        
index c98771d..988f0cf 100644                                                                                                                                                     
--- a/pulsar/reader_test.go                                                                                                                                                       
+++ b/pulsar/reader_test.go                   
@@ -362,3 +362,58 @@ func TestReaderHasNext(t *testing.T) {
 
        assert.Equal(t, 10, i)
 }
+
+type myMessageID struct {
+       data []byte
+}
+
+func (id *myMessageID) Serialize() []byte {
+       return id.data
+}
+
+func TestReaderWithCustomMessageID(t *testing.T) {
+       client, err := NewClient(ClientOptions{
+               URL: lookupURL,
+       })
+
+       assert.Nil(t, err)
+       defer client.Close()
+
+       topic := newTopicName()
+       ctx := context.Background()
+
+       // create producer
+       producer, err := client.CreateProducer(ProducerOptions{
+               Topic:           topic,
+               DisableBatching: true,
+       })
+       assert.Nil(t, err)
+       defer producer.Close()
+
+       // send 10 messages
+       msgIDs := [10]MessageID{}
+       for i := 0; i < 10; i++ {
+               msgID, err := producer.Send(ctx, &ProducerMessage{
+                       Payload: []byte(fmt.Sprintf("hello-%d", i)),
+               })
+               assert.NoError(t, err)
+               assert.NotNil(t, msgID)
+               msgIDs[i] = msgID
+       }
+
+       myMsg := &myMessageID{
+               data: msgIDs[4].Serialize(),
+       }
+
+       myMsg := &myMessageID{
+               data: msgIDs[4].Serialize(),
+       }
+
+       // attempt to create reader on 5th message (not included)
+       var reader Reader
+       assert.NotPanics(t, func() {
+               reader, err = client.CreateReader(ReaderOptions{
+                       Topic:          topic,
+                       StartMessageID: myMsg,
+               })
+       })
+
+       assert.Nil(t, err)
+       defer reader.Close()
+}
```

- Ran the modified UT using the CI bash script

```bash
NVASHISH-M-93PK:pulsar-client-go nvashish$ git diff run-ci.sh 
diff --git a/run-ci.sh b/run-ci.sh
index 2de0eee..7507b68 100755
--- a/run-ci.sh
+++ b/run-ci.sh
@@ -31,7 +31,7 @@ go build -o pulsar-perf ./perf
 
 ./pulsar-test-service-start.sh
 
-go test -race -coverprofile=/tmp/coverage -timeout=20m ./...
+go test -race -coverprofile=/tmp/coverage -timeout=20m ./... -run=TestReaderWithCustomMessageID
 go tool cover -html=/tmp/coverage -o coverage.html
 
 ./pulsar-test-service-stop.sh
```

- Test case failed with panic, even though it compiles.

```bash
-- Ready to start tests                                                                                                                                                           
+ go test -race -coverprofile=/tmp/coverage -timeout=20m ./... -run=TestReaderWithCustomMessageID                                                                                 
?       github.com/apache/pulsar-client-go/examples/consumer    [no test files]                                                                                                   
?       github.com/apache/pulsar-client-go/examples/consumer-listener   [no test files]                                                                                           
?       github.com/apache/pulsar-client-go/examples/producer    [no test files]                                                                                                   
?       github.com/apache/pulsar-client-go/examples/reader      [no test files]                                                                                                   
ok      github.com/apache/pulsar-client-go/integration-tests    1.022s  coverage: 0.0% of statements [no tests to run]                                                            
?       github.com/apache/pulsar-client-go/perf [no test files]                                                                                                                   
time="2020-07-05T05:54:05Z" level=info msg="Connecting to broker" remote_addr="pulsar://localhost:6650"                                                                           
time="2020-07-05T05:54:05Z" level=info msg="TCP connection established" local_addr="127.0.0.1:49144" remote_addr="pulsar://localhost:6650"                                        
time="2020-07-05T05:54:05Z" level=info msg="Connection is ready" local_addr="127.0.0.1:49144" remote_addr="pulsar://localhost:6650"                                               
time="2020-07-05T05:54:06Z" level=info msg="Created producer" cnx="127.0.0.1:49144 -> 127.0.0.1:6650" producer_name=standalone-0-0 topic="persistent://public/default/my-topic-501
323100"                                                                                                                                                                           
time="2020-07-05T05:54:06Z" level=info msg="Closing producer" producer_name=standalone-0-0 topic="persistent://public/default/my-topic-501323100"                                 
time="2020-07-05T05:54:06Z" level=info msg="Closed producer" producer_name=standalone-0-0 topic="persistent://public/default/my-topic-501323100"                                  
--- FAIL: TestReaderWithCustomMessageID (1.14s)                                                                                                                                   
    reader_test.go:410:                                                                                                                                                           
                Error Trace:    reader_test.go:410                                                                                                                                
                Error:          func (assert.PanicTestFunc)(0xba3710) should not panic                                                                                            
                                        Panic value:    interface conversion: pulsar.MessageID is *pulsar.myMessageID, not *pulsar.messageID                                      
                Test:           TestReaderWithCustomMessageID                                                                                                                     
panic: runtime error: invalid memory address or nil pointer dereference [recovered]                                                                                               
        panic: runtime error: invalid memory address or nil pointer dereference                                                                                                   
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb9e8f2]                                                                                                            
                                                                                                                                                                                  
goroutine 20 [running]:                                                                                                                                                           
testing.tRunner.func1(0xc000124200)                                                                                                                                               
        /usr/local/go/src/testing/testing.go:830 +0x69d                                                                                                                           
panic(0xcf0820, 0x13abde0)                                                                                                                                                        
        /usr/local/go/src/runtime/panic.go:522 +0x1b5                                                                                                                             
github.com/apache/pulsar-client-go/pulsar.TestReaderWithCustomMessageID(0xc000124200)                                                                                             
        /pulsar-client-go/pulsar/reader_test.go:418 +0x9c2                                                                                                                        
testing.tRunner(0xc000124200, 0xda0408)                                                                                                                                           
        /usr/local/go/src/testing/testing.go:865 +0x164                                                                                                                           
created by testing.(*T).Run                                                                                                                                                       
        /usr/local/go/src/testing/testing.go:916 +0x65b                                                                                                                           
FAIL    github.com/apache/pulsar-client-go/pulsar       1.164s                                                                                                                    
ok      github.com/apache/pulsar-client-go/pulsar/internal      1.029s  coverage: 0.0% of statements [no tests to run]                                                            
ok      github.com/apache/pulsar-client-go/pulsar/internal/auth 1.021s  coverage: 0.0% of statements [no tests to run]                                                            
ok      github.com/apache/pulsar-client-go/pulsar/internal/compression  1.025s  coverage: 17.9% of statements [no tests to run]                                                   
?       github.com/apache/pulsar-client-go/pulsar/internal/pulsar_proto [no test files]  
```


Should I open an issue for [native go client repo](https://github.com/apache/pulsar-client-go/issues) referencing this issue?

**Comment by wolfstudy** [comment]
Cool Thanks to @nitishv the https://github.com/apache/pulsar-client-go/pull/305 has been merged to master, will close the issue.
