### ISSUE TITLE
Error with BookKeeper 4.8.1 and Pulsar 2.2.0

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#3258]
#### Expected behavior

I am able to run a Pulsar Broker (2.2.0) having BookKeeper 4.8.1 client on the classpath.
It does now happen with 4.7.3.

#### Actual behavior

I have this error using v3 protocol. with v2 the error is not logged but with a debugger I see it is mostly the same. 

```
18-12-27-12-26-42	io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.toLiveRealCnt(AbstractReferenceCountedByteBuf.java:181)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:133)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:124)
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:88)
	at org.apache.bookkeeper.proto.checksum.DigestManager.computeDigestAndPackageForSending(DigestManager.java:131)
	at org.apache.bookkeeper.client.PendingAddOp.safeRun(PendingAddOp.java:243)
	at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

#### Steps to reproduce

I have created a unit test inside by non-public application.
Maybe just by replacing the BookKeeper dependency core Pulsar tests should fail. But I did not try

#### System configuration
**Pulsar version**: 2.2.0

**Comment by sijie** [comment]
- pulsar 2.2.0+ works with 4.7.2+ bookies

however if you are speaking of upgrading the bookkeeper client used by pulsar broker, you need the changes in https://github.com/apache/pulsar/pull/2906

because bk 4.8+ changed the behavior of reference counting in addEntry. so it requires code changes in managed ledger.

so typically you are okay to upgrade bookies (server) to a newer version. however we recommend you using the version of bookkeeper client shipped along with pulsar.

**Comment by sijie** [comment]
Closed the issue since it is answered.
