### ISSUE TITLE
Error while recovering ledger when send messages by producer

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#3279]
This is a transient exception while send messages by producer.
Stack trace:
```
15:10:00.028 [main] ERROR org.apache.pulsar.client.cli.PulsarClientTool - Error while producing messages
15:10:00.028 [main] ERROR org.apache.pulsar.client.cli.PulsarClientTool - org.apache.bookkeeper.client.BKException$BKLedgerRecoveryException: Error while recovering ledger
org.apache.pulsar.client.api.PulsarClientException: org.apache.bookkeeper.client.BKException$BKLedgerRecoveryException: Error while recovering ledger
	at org.apache.pulsar.client.impl.ClientCnx.getPulsarClientException(ClientCnx.java:760) ~[org.apache.pulsar-pulsar-client-original-2.1.0-incubating.jar:2.1.0-incubating]
	at org.apache.pulsar.client.impl.ClientCnx.handleError(ClientCnx.java:497) ~[org.apache.pulsar-pulsar-client-original-2.1.0-incubating.jar:2.1.0-incubating]
	at org.apache.pulsar.common.api.PulsarDecoder.channelRead(PulsarDecoder.java:154) ~[org.apache.pulsar-pulsar-common-2.1.0-incubating.jar:2.1.0-incubating]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414) ~[io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945) ~[io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:806) ~[io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404) ~[io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) ~[io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) ~[io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_111]
15:10:00.033 [main] INFO  org.apache.pulsar.client.cli.PulsarClientTool - 0 messages successfully produced
```
Restart the client, send messages will be ok!
#### System configuration
**Pulsar version**: 2.1.0

**Comment by sijie** [comment]
I have worked with @codelipenghui on debugging this issue. When the issue happened, following logging statements were found at broker.

```
15:10:00.028 [BookKeeperClientWorker-OrderedExecutor-22-0] WARN  org.apache.bookkeeper.client.LedgerHandle - Conditional update ledger metadata for ledger 153718 failed.
15:10:00.029 [BookKeeperClientWorker-OrderedExecutor-22-0] WARN  org.apache.bookkeeper.client.LedgerRecoveryOp - Close ledger 153718 failed during recovery:
```

So the `LedgerRecoveryException` received at producer side is coming from broker failing on updating ledger metadata when loading a topic - *Conditional update ledger metadata for ledger 153718 failed`.

**Why this happened**

The *Conditional update failure* can happen when the ownership of a topic is transferred from one broker to the other broker. The transfer can be triggered by any events, for example topic reassigned when network is partitioned, load balancing and such. 

During this period, old owner is unloading the topic and closing the last ledger in the topic. Closing the ledger involves updating ledger metadata. The new owner is loading the topic, and recovering the last ledger in the topic. At the end of recovery, it will also close the ledger (which also updates ledger metadata). Concurrent metadata updates will trigger this "conditional update" failure. One update will succeed and the other update will fail. And broker and client don't have retry logics for this case, so the exception is popped all the way back to applications.

This issue will be fixed by bk 4.9.0 release, since bk 4.9.0 will handle conditional update failure on closing and will not throw exception. (/cc @ivankelly for confirmation)

However I think at Pulsar side, there are a few improvements can be considered.

for example, at producer side, producer can potentially catch this exception and determine whether it should retry on this exception or not. If it can retry, the producer can retry it before popping the exception to applications.

**Comment by ivankelly** [comment]
@sijie 
With 4.9, the new producer will not have to worry about the exception, as the conditional update will succeed in this case. If the previous owner's attempt to close wins, the new owner's recovery close will fail, reread the metadata, see that the metadata is no longer in IN_RECOVERY state, so it can assume it is in CLOSED state. Since it is in closed state, it can just take the CLOSED metadata and use that.

https://github.com/apache/bookkeeper/blob/4c8587715104cde6dbd70d1e7de0fc1853122eda/bookkeeper-server/src/main/java/org/apache/bookkeeper/client/ReadOnlyLedgerHandle.java#L313

**Comment by sijie** [comment]
@ivankelly cool. thank you for the confirmation.

**Comment by sijie** [comment]
Pulsar has already upgraded bookkeeper to 4.10+
