### ISSUE TITLE
IndexOutOfBoundsException in kafka ConsumerExample

### ISSUE THREAD

**Issue by sautran** [apache/pulsar#3369]
Steps:
1. unzip tar ball: tar -xf apache-pulsar-2.2.1-bin.tar.gz , cd the directory
2. ./pulsar standalone
3. change the topic to  following in 
    org.apache.pulsar.client.kafka.compat.examples.ConsumerExample.java
        String topic = "persistent://public/default/test";
 4. Run  ConsumerExample

Server will have the following error
```
11:18:36.355 [zk-storage-container-manager] INFO  org.apache.bookkeeper.stream.storage.impl.sc.ZkStorageContainerManager - Servers left : []
11:18:36.355 [zk-storage-container-manager] INFO  org.apache.bookkeeper.stream.storage.impl.sc.ZkStorageContainerManager - Servers joined : []
11:18:36.355 [zk-storage-container-manager] INFO  org.apache.bookkeeper.stream.storage.impl.sc.ZkStorageContainerManager - Process container changes:
	Ideal = [0, 1]
	Live = [0, 1]
	Pending = []
	ToStart = []
	ToStop = []
11:18:49.553 [pulsar-io-49-4] INFO  org.apache.pulsar.broker.service.ServerCnx - New connection from /xx.xx.xx.xx:64591
11:18:49.582 [pulsar-io-49-4] WARN  org.apache.pulsar.broker.service.ServerCnx - [/xx.xx.xx.xx:64591] Got exception IndexOutOfBoundsException : writerIndex: 1179652 (expected: readerIndex(4) <= writerIndex <= capacity(20))
java.lang.IndexOutOfBoundsException: writerIndex: 1179652 (expected: readerIndex(4) <= writerIndex <= capacity(20))
	at io.netty.buffer.AbstractByteBuf.writerIndex(AbstractByteBuf.java:118) ~[io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at org.apache.pulsar.common.api.PulsarDecoder.channelRead(PulsarDecoder.java:83) ~[org.apache.pulsar-pulsar-common-2.2.1.jar:2.2.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:806) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:413) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
11:18:49.586 [pulsar-io-49-4] INFO  org.apache.pulsar.broker.service.ServerCnx - Closed connection from /xx.xx.xx.xx:64591
```

**Comment by foreversunyao** [comment]
@sautran , is it a reproduced issue ? or is it related the issue which was fixed recently #3373

**Comment by ambition119** [comment]
> @sautran , is it a reproduced issue ? or is it related the issue which was fixed recently #3373

sorry, I wrong related to #3373, this issue unresolved.

**Comment by ambition119** [comment]
example run result:
![image](https://user-images.githubusercontent.com/20353043/51537911-d2a72400-1e8a-11e9-80a0-5f7030e54e6b.png)
![image](https://user-images.githubusercontent.com/20353043/51537927-dc308c00-1e8a-11e9-94fe-e43df0b85c9d.png)
![image](https://user-images.githubusercontent.com/20353043/51537947-e9e61180-1e8a-11e9-9aa7-20258cc29969.png)

**Comment by jiazhai** [comment]
@ambition119  are you still looking into this issue?

**Comment by ambition119** [comment]
@jiazhai @sautran 
org.apache.pulsar.client.kafka.compat.examples.ConsumerExample.java should use pulsar shaded jar offered   [KafkaConsumer](https://github.com/apache/pulsar/blob/master/pulsar-client-kafka-compat/pulsar-client-kafka-shaded/pom.xml#L133) class. If you use a runtime environment like IDEA,  you actually Kafka native jar offer class, occurred this error.

solution：
Modify KafkaConsumer to PulsarKafkaConsumer then run this example, no errors occurred.
or Run the examples from command line, like:
```shell
$ vi run.sh
#!/usr/bin/env bash

RELEASE_JAR=`ls ${PULSAR_CODE}/pulsar-client-kafka-compat/pulsar-client-kafka-shaded/target/*.jar 2> /dev/null | grep -v tests | tail -1`
if [ $? == 0 ]; then
    PULSAR_JAR=$RELEASE_JAR
fi

PULSAR_CLASSPATH="$RELEASE_JAR:${PULSAR_CODE}/distribution/server/target/apache-pulsar-2.3.0-SNAPSHOT/conf/log4j2.yaml:${PULSAR_CODE}/pulsar-client-kafka-compat/pulsar-client-kafka-tests/target/pulsar-client-kafka-tests-tests.jar:${PULSAR_CODE}/distribution/server/target/apache-pulsar-2.3.0-SNAPSHOT/lib/*"
OPTS="-cp $PULSAR_CLASSPATH $OPTS"
cd ${PULSAR_CODE}/pulsar-client-kafka-compat/pulsar-client-kafka-tests/target
exec java $OPTS org.apache.pulsar.client.kafka.compat.examples.ProducerExample
```
then run.sh no errors occurred.

If there are no errors in the operation, this is not a bug.

**Comment by jiazhai** [comment]
@ambition119 👍 . Would you like to help adding some comments in the code or documentation for this issue?

**Comment by ambition119** [comment]
@sautran so this issue solved?

**Comment by sautran** [comment]
@ambition119 , thanks for fixing it!! The issue has been solved.
