### ISSUE TITLE
Can't run Pulsar locally on Mac, Bookkeeper throws "ZK exception checking and wait ephemeral znode expired"

### ISSUE THREAD

**Issue by bretlowery** [apache/pulsar#3435]
Attempting to run latest Pulsar locally on Mac (latest Mojave OS 10.14.2) results in:

```
08:13:48.440 [BookieStateManagerService-0] ERROR org.apache.bookkeeper.discover.ZKRegistrationManager - ZK exception checking and wait ephemeral znode /stream/servers/available/172.20.10.5:4181 expired : 
Exception in thread "main" java.lang.RuntimeException: Failed to intiailize a registration state service
	at org.apache.bookkeeper.stream.server.service.RegistrationStateService.doStart(RegistrationStateService.java:88)
	at org.apache.bookkeeper.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:78)
	at org.apache.bookkeeper.common.component.LifecycleComponentStack.lambda$start$2(LifecycleComponentStack.java:113)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)
	at org.apache.bookkeeper.common.component.LifecycleComponentStack.start(LifecycleComponentStack.java:113)
	at org.apache.bookkeeper.stream.server.StreamStorageLifecycleComponent.doStart(StreamStorageLifecycleComponent.java:51)
	at org.apache.bookkeeper.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:78)
	at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.runStreamStorage(LocalBookkeeperEnsemble.java:317)
	at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.startStandalone(LocalBookkeeperEnsemble.java:386)
	at org.apache.pulsar.PulsarStandalone.start(PulsarStandalone.java:265)
	at org.apache.pulsar.PulsarStandaloneStarter.main(PulsarStandaloneStarter.java:102)
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: org.apache.bookkeeper.bookie.BookieException$MetadataStoreException: java.io.IOException: ZK exception checking and wait ephemeral znode /stream/servers/available/172.20.10.5:4181 expired
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.bookkeeper.stream.server.service.RegistrationStateService.doStart(RegistrationStateService.java:84)
	... 10 more
Caused by: java.io.IOException: org.apache.bookkeeper.bookie.BookieException$MetadataStoreException: java.io.IOException: ZK exception checking and wait ephemeral znode /stream/servers/available/172.20.10.5:4181 expired
	at org.apache.bookkeeper.bookie.BookieStateManager.doRegisterBookie(BookieStateManager.java:257)
	at org.apache.bookkeeper.bookie.BookieStateManager.doRegisterBookie(BookieStateManager.java:242)
	at org.apache.bookkeeper.bookie.BookieStateManager$2.call(BookieStateManager.java:205)
	at org.apache.bookkeeper.bookie.BookieStateManager$2.call(BookieStateManager.java:201)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.bookkeeper.bookie.BookieException$MetadataStoreException: java.io.IOException: ZK exception checking and wait ephemeral znode /stream/servers/available/172.20.10.5:4181 expired
	at org.apache.bookkeeper.discover.ZKRegistrationManager.doRegisterBookie(ZKRegistrationManager.java:246)
	at org.apache.bookkeeper.discover.ZKRegistrationManager.registerBookie(ZKRegistrationManager.java:218)
	at org.apache.bookkeeper.bookie.BookieStateManager.doRegisterBookie(BookieStateManager.java:254)
	... 7 more
Caused by: java.io.IOException: ZK exception checking and wait ephemeral znode /stream/servers/available/172.20.10.5:4181 expired
	at org.apache.bookkeeper.discover.ZKRegistrationManager.checkRegNodeAndWaitExpired(ZKRegistrationManager.java:204)
	at org.apache.bookkeeper.discover.ZKRegistrationManager.doRegisterBookie(ZKRegistrationManager.java:227)
	... 9 more
Caused by: org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /stream/servers/available/172.20.10.5:4181
	at org.apache.bookkeeper.discover.ZKRegistrationManager.checkRegNodeAndWaitExpired(ZKRegistrationManager.java:193)
	... 10 more
```

Bookeeper has a current issue reported that is similar:
https://github.com/apache/bookkeeper/issues/1019

**Comment by bretlowery** [comment]
To be clear, this is when I run "bin/pulsar standalone".

**Comment by foreversunyao** [comment]
@bretlowery Try mvn clean install ? Not sure if pulsar made a clean shutdown

**Comment by sijie** [comment]
@bretlowery Can you see if you have another standalone running? Which version of pulsar are you running?

**Comment by bretlowery** [comment]
The issue is intermittent at startup. This is a code quality issue in Bookkeeper with how it is integrated with Zookeeper and how it checks and handles state at startup. Since it's a Bookkeeper issue, I'm closing this as a non-issue for Pulsar.
