### ISSUE TITLE
Intermittent test failure in PulsarWorkerAssignmentTest.testFunctionAssignmentsWithRestart

### ISSUE THREAD

**Issue by merlimat** [apache/pulsar#3482]
Seen failing a few times already `PulsarWorkerAssignmentTest.testFunctionAssignmentsWithRestart`

https://builds.apache.org/job/pulsar_precommit_java8/6037/testReport/junit/org.apache.pulsar.functions.worker/PulsarWorkerAssignmentTest/testFunctionAssignmentsWithRestart/ 

```
Error Message
Method org.apache.pulsar.functions.worker.PulsarWorkerAssignmentTest.testFunctionAssignmentsWithRestart() didn't finish within the time-out 20000
Stacktrace
org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.functions.worker.PulsarWorkerAssignmentTest.testFunctionAssignmentsWithRestart() didn't finish within the time-out 20000
	at java.lang.Thread.join(Thread.java:1252)
	at java.lang.Thread.join(Thread.java:1326)
	at org.apache.pulsar.functions.runtime.ThreadRuntime.stop(ThreadRuntime.java:123)
	at org.apache.pulsar.functions.runtime.RuntimeSpawner.close(RuntimeSpawner.java:146)
	at org.apache.pulsar.functions.worker.FunctionActioner.stopFunction(FunctionActioner.java:265)
	at org.apache.pulsar.functions.worker.FunctionRuntimeManager.stopFunction(FunctionRuntimeManager.java:447)
	at org.apache.pulsar.functions.worker.FunctionRuntimeManager.lambda$stopAllOwnedFunctions$1(FunctionRuntimeManager.java:435)
	at org.apache.pulsar.functions.worker.FunctionRuntimeManager$$Lambda$731/14050562.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:981)
	at org.apache.pulsar.functions.worker.FunctionRuntimeManager.stopAllOwnedFunctions(FunctionRuntimeManager.java:432)
	at org.apache.pulsar.functions.worker.FunctionRuntimeManager.close(FunctionRuntimeManager.java:807)
	at org.apache.pulsar.functions.worker.WorkerService.stop(WorkerService.java:218)
	at org.apache.pulsar.functions.worker.PulsarWorkerAssignmentTest.testFunctionAssignmentsWithRestart(PulsarWorkerAssignmentTest.java:292)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Full logs saved at https://gist.githubusercontent.com/merlimat/24b2f399eb8346cb7294ecd360d396e7/raw/437d824fbaad7015602bc4fd65923b8b6445850e/gistfile1.txt

**Comment by merlimat** [comment]
Saved the Jenkins job here: https://builds.apache.org/job/pulsar_precommit_java8/6447/
