### ISSUE TITLE
Intermittent test failure in ProxyLookupThrottlingTest

### ISSUE THREAD

**Issue by merlimat** [apache/pulsar#3552]
```
Error Message
expected [true] but found [false]
Stacktrace
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at org.apache.pulsar.proxy.server.ProxyLookupThrottlingTest.testLookup(ProxyLookupThrottlingTest.java:76
```

**Comment by ivankelly** [comment]
@merlimat Please link the failed build (and mark as "keep forever") for this flake issues.

**Comment by foreversunyao** [comment]
not sure if this is the same one ?
@ivankelly  @merlimat 
https://builds.apache.org/job/pulsar_precommit_java8/7991/console
