### ISSUE TITLE
Unexpected ZooKeeper disconnection and finally Brokers shutdown

### ISSUE THREAD

**Issue by nkurihar** [apache/pulsar#3566]
**Describe the bug**
A Bookie (1 of 10 in one cluster) suddenly went down:
```
21:07:04.804 [BookieJournal-3181] INFO  o.a.bookkeeper.bookie.JournalChannel - Opening journal /journal/current/16227802a46.txn
21:08:05.761 [bookie-io-1-20] INFO  o.a.bookkeeper.proto.AuthHandler     - Authentication success on server side
21:08:05.761 [bookie-io-1-20] INFO  o.a.b.proto.BookieRequestHandler     - Channel connected  [id: 0x68f20463, L:/<bookie ip>:3181 - R:/<bookie ip>:50480]
21:08:07.668 [bookie-io-1-21] INFO  o.a.bookkeeper.proto.AuthHandler     - Authentication success on server side
21:08:07.668 [bookie-io-1-21] INFO  o.a.b.proto.BookieRequestHandler     - Channel connected  [id: 0x2d93aca1, L:/<bookie ip>:3181 - R:/<bookie ip>:50488]
21:08:07.798 [BookieHighPriorityThread-3181-OrderedExecutor-1-0] INFO  o.a.b.proto.ReadEntryProcessorV3     - Ledger fence request received for ledger: 9358129 from address: /<bookie ip>:50488
21:08:08.061 [bookie-io-1-21] INFO  o.a.b.proto.BookieRequestHandler     - Channels disconnected: [id: 0x2d93aca1, L:/<bookie ip>:3181 ! R:/<bookie ip>:50488]
21:08:10.133 [bookie-io-1-20] INFO  o.a.b.proto.BookieRequestHandler     - Channels disconnected: [id: 0x68f20463, L:/<bookie ip>:3181 ! R:/<bookie ip>:50480]
21:09:24.324 [GarbageCollectorThread-11-1] INFO  o.a.b.bookie.GarbageCollectorThread  - Extracting entry log meta from entryLogId: 4417
# manually restarted
22:18:37.445 [main] INFO  org.apache.bookkeeper.server.Main    - Using configuration file /path/to/pulsar-bookie.conf
22:18:37.453 [main] INFO  org.apache.bookkeeper.server.Main    - Hello, I'm your bookie, listening on port 3181. Metadata service uri is zk+hierarchical://zk100.xx.xx;zk101.xx.xx;zk102.xx.xx;zk103.xx.xx;zk104.xx.xx/ledgers. Journals are in [/journal]. Ledgers are stored in /ledgers.
```

After that, we have seen unexpected Broker shutdown with ZooKeeper disconnection:
```
21:33:32.903 [pulsar-zk-session-watcher-5-1] WARN  o.a.p.z.ZooKeeperSessionWatcher      - zoo keeper disconnected, waiting to reconnect, time remaining = 25 seconds
21:33:34.903 [pulsar-zk-session-watcher-5-1] WARN  o.a.p.z.ZooKeeperSessionWatcher      - zoo keeper disconnected, waiting to reconnect, time remaining = 23 seconds
.
.
.
21:33:56.905 [pulsar-zk-session-watcher-5-1] WARN  o.a.p.z.ZooKeeperSessionWatcher      - zoo keeper disconnected, waiting to reconnect, time remaining = 0 seconds
21:33:58.905 [pulsar-zk-session-watcher-5-1] ERROR o.a.p.z.ZooKeeperSessionWatcher      - timeout expired for reconnecting, invoking shutdown service
21:33:58.906 [pulsar-zk-session-watcher-5-1] INFO  org.apache.zookeeper.ZooKeeper       - Session: 0x204f225a3fbaf49 closed
21:33:58.906 [pulsar-zk-session-watcher-5-1] INFO  o.a.p.b.MessagingServiceShutdownHook - Invoking Runtime.halt(-1)
```
* This was happen on all Brokers (actually 14) in one cluster at the almost same time (21:32-35). 
* All ZooKeepers seemed to be running normally at that time
* Any network error was not detected

I know when ZooKeeper is truly down, the befavior of Broker(shutdown) is natural.
However, we found no ZooKeeper down and network error etc., so we suspect some bugs or lack of tunings of Broker.

**Additional context**
Broker OS: CentOS Linux release 7.6.1810
Broker version: 2.1.1
Broker spec: Real server / 2.10GHz / 2CPU / 256GBMEM / SATA SSD 240GB x1 / 10G Base-T*2port

It looks similar to https://github.com/apache/pulsar/issues/3535 , however for now deduplication is disabled and we have seen no Full GCs.

**Comment by massakam** [comment]
This phenomenon seems to occur occasionally when rebooting the machine on which a bookie is running suddenly. I saw the same phenomenon occurred only once in our development environment.

The brokers in the development environment had been modified to output a thread dump using [ThreadDumpUtil](https://github.com/apache/pulsar/blob/v2.1.1-incubating/buildtools/src/main/java/org/apache/pulsar/tests/ThreadDumpUtil.java) just before shutdown.

```diff
diff --git a/pulsar-zookeeper-utils/src/main/java/org/apache/pulsar/zookeeper/ZooKeeperSessionWatcher.java b/pulsar-zookeeper-utils/src/main/java/org/apache/pulsar/zookeeper/ZooKeeperSessionWatcher.java
index d654a77..698fac9 100644
--- a/pulsar-zookeeper-utils/src/main/java/org/apache/pulsar/zookeeper/ZooKeeperSessionWatcher.java
+++ b/pulsar-zookeeper-utils/src/main/java/org/apache/pulsar/zookeeper/ZooKeeperSessionWatcher.java
@@ -156,6 +156,7 @@ public class ZooKeeperSessionWatcher implements Watcher, StatCallback, Runnable,
                         - TimeUnit.NANOSECONDS.toMillis(System.nanoTime() - disconnectedAt);
                 if (timeRemainingMillis <= 0) {
                     LOG.error("timeout expired for reconnecting, invoking shutdown service");
+                    LOG.info(ThreadDumpUtil.buildThreadDiagnosticString());
                     close();
                     shuttingDown = true;
                     shutdownService.shutdown(-1);
```

These are thread dumps just before the two brokers are shut down:

* [threaddump_broker1.txt](https://github.com/apache/pulsar/files/2855793/threaddump_broker1.txt)
* [threaddump_broker2.txt](https://github.com/apache/pulsar/files/2855794/threaddump_broker2.txt)

It seems to me that the problem is that `pulsar-ordered-OrderedExecutor-7-0-EventThread` and `pulsar-ordered-OrderedExecutor-3-0-EventThread` are waiting. These threads were watching events of ZK at each broker.

* [broker1.log](https://github.com/apache/pulsar/files/2855928/broker1.log)
* [broker2.log](https://github.com/apache/pulsar/files/2855929/broker2.log)

Does anyone know the cause of this problem?

**Comment by massakam** [comment]
I think the cause of this problem is that thread `pulsar-ordered-OrderedExecutor-x-x-EventThread` is deadlocking itself.

```
"pulsar-ordered-OrderedExecutor-7-0-EventThread" daemon prio=5 tid=26 in Object.wait()
java.lang.Thread.State: WAITING (on object monitor)
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1693)
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
        at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
        at org.apache.pulsar.zookeeper.ZooKeeperDataCache.get(ZooKeeperDataCache.java:94)
        at org.apache.pulsar.zookeeper.ZkBookieRackAffinityMapping.getRack(ZkBookieRackAffinityMapping.java:153)
        at org.apache.pulsar.zookeeper.ZkBookieRackAffinityMapping.resolve(ZkBookieRackAffinityMapping.java:145)
        at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl$DNSResolverDecorator.resolve(RackawareEnsemblePlacementPolicyImpl.java:153)
        at org.apache.bookkeeper.net.NetUtils.resolveNetworkLocation(NetUtils.java:81)
        at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl.resolveNetworkLocation(RackawareEnsemblePlacementPolicyImpl.java:342)
        at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl.createBookieNode(RackawareEnsemblePlacementPolicyImpl.java:221)
        at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl.convertBookiesToNodes(RackawareEnsemblePlacementPolicyImpl.java:452)
        at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl.newEnsembleInternal(RackawareEnsemblePlacementPolicyImpl.java:515)
        at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl.newEnsembleInternal(RackawareEnsemblePlacementPolicyImpl.java:480)
        at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl.newEnsemble(RackawareEnsemblePlacementPolicyImpl.java:471)
        at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicy.newEnsemble(RackawareEnsemblePlacementPolicy.java:92)
        at org.apache.bookkeeper.client.BookieWatcher.newEnsemble(BookieWatcher.java:209)
        at org.apache.bookkeeper.client.LedgerCreateOp.initiate(LedgerCreateOp.java:138)
        at org.apache.bookkeeper.client.BookKeeper.asyncCreateLedger(BookKeeper.java:879)
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.initializeBookKeeper(ManagedLedgerImpl.java:366)
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.access$300(ManagedLedgerImpl.java:113)
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl$1.operationComplete(ManagedLedgerImpl.java:305)
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl$1.operationComplete(ManagedLedgerImpl.java:258)
        at org.apache.bookkeeper.mledger.impl.MetaStoreImplZookeeper.lambda$null$0(MetaStoreImplZookeeper.java:150)
        at org.apache.bookkeeper.mledger.impl.MetaStoreImplZookeeper$$Lambda$354/2112358463.processResult(Unknown Source)
        at org.apache.bookkeeper.mledger.impl.MetaStoreImplZookeeper.lambda$null$18(MetaStoreImplZookeeper.java:378)
        at org.apache.bookkeeper.mledger.impl.MetaStoreImplZookeeper$$Lambda$357/778283669.accept(Unknown Source)
        at org.apache.bookkeeper.mledger.impl.MetaStoreImplZookeeper.lambda$asyncCreateFullPathOptimistic$21(MetaStoreImplZookeeper.java:382)
        at org.apache.bookkeeper.mledger.impl.MetaStoreImplZookeeper$$Lambda$355/1068452416.processResult(Unknown Source)
        at org.apache.bookkeeper.zookeeper.ZooKeeperClient$10$1.processResult(ZooKeeperClient.java:737)
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:607)
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:505)
```

Whenever the broker is shut down by reboot of bookie machine, this thread is waiting for data to be returned from the ZK cache on the following line:
https://github.com/apache/pulsar/blob/v2.1.1-incubating/pulsar-zookeeper-utils/src/main/java/org/apache/pulsar/zookeeper/ZkBookieRackAffinityMapping.java#L153

As far as I see the debug log, the following part is also processed by the same thread, so `pulsar-ordered-OrderedExecutor-x-x-EventThread` seems to continue waiting for completion of its own processing.
https://github.com/apache/pulsar/blob/v2.1.1-incubating/pulsar-zookeeper-utils/src/main/java/org/apache/pulsar/zookeeper/ZooKeeperCache.java#L322-L338

The deadlock as described above occurs when the following warning log is output and a bookie is quarantined:

> 13:17:21.063 [BookKeeperClientScheduler-OrderedScheduler-0-0] WARN o.a.bookkeeper.client.BookieWatcher - Bookie xxx.xxx.xxx.xxx:3181 has been quarantined because of read/write errors.

If the list of quarantined bookies is not empty, the processing in the following loop which is normally skipped is executed:
https://github.com/apache/bookkeeper/blob/release-4.7.2/bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java#L449-L455

**Comment by merlimat** [comment]
@massakam you analysis is 100% correct. I think that the problem should be solved by having all callbacks coming from `MetaStoreImplZookeeper` to be triggered outside of ZK event thread.

**Comment by merlimat** [comment]
This actually happens to be the case throughput `MetaStoreImplZookeeper`, except for the `asyncCreateFullPathOptimistic()` method. Fixing that.
