### ISSUE TITLE
Intermittent test failure PulsarWorkerAssignmentTest. testFunctionAssignments

### ISSUE THREAD

**Issue by merlimat** [apache/pulsar#3570]
```
org.apache.pulsar.functions.worker.PulsarWorkerAssignmentTest.testFunctionAssignments

Error Message
expected [2] but found [1]

Stacktrace
java.lang.AssertionError: expected [2] but found [1]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:652)
	at org.testng.Assert.assertEquals(Assert.java:662)
	at org.apache.pulsar.functions.worker.PulsarWorkerAssignmentTest.testFunctionAssignments(PulsarWorkerAssignmentTest.java:201)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ambition119** [comment]
@merlimat I run branch-2.3 and master code not error
![image](https://user-images.githubusercontent.com/20353043/53854071-fd94a400-4002-11e9-88d8-ece91c860da4.png)

**Comment by sijie** [comment]
Close this issue since there is no activity on this task. Please re-open if the same failure is found.
