### ISSUE TITLE
unit test failure in java PulsarWorkerAssignmentTest.testFunctionAssignmentsWithRestart

### ISSUE THREAD

**Issue by wolfstudy** [apache/pulsar#3660]
**Describe the bug**

```
2019-02-21\T\06:47:48.800 [ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 76.494 s <<< FAILURE! - in org.apache.pulsar.functions.worker.PulsarWorkerAssignmentTest
2019-02-21\T\06:47:48.801 [ERROR] testFunctionAssignmentsWithRestart(org.apache.pulsar.functions.worker.PulsarWorkerAssignmentTest)  Time elapsed: 20.027 s  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.functions.worker.PulsarWorkerAssignmentTest.testFunctionAssignmentsWithRestart() didn't finish within the time-out 20000
	at org.apache.logging.log4j.util.SortedArrayStringMap.ceilingNextPowerOfTwo(SortedArrayStringMap.java:529)
	at org.apache.logging.log4j.util.SortedArrayStringMap.<init>(SortedArrayStringMap.java:104)
	at org.apache.logging.log4j.util.SortedArrayStringMap.<init>(SortedArrayStringMap.java:97)
	at org.apache.logging.log4j.core.impl.ContextDataFactory.createContextData(ContextDataFactory.java:94)
	at org.apache.logging.log4j.core.impl.Log4jLogEvent.createContextData(Log4jLogEvent.java:441)
	at org.apache.logging.log4j.core.impl.Log4jLogEvent.<init>(Log4jLogEvent.java:320)
	at org.apache.logging.log4j.core.impl.DefaultLogEventFactory.createEvent(DefaultLogEventFactory.java:54)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:401)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2163)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2118)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2101)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2018)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1891)
	at org.apache.logging.slf4j.Log4jLogger.error(Log4jLogger.java:309)
	at org.apache.pulsar.functions.worker.FunctionRuntimeManager.initialize(FunctionRuntimeManager.java:218)
	at org.apache.pulsar.functions.worker.WorkerService.start(WorkerService.java:177)
	at org.apache.pulsar.functions.worker.PulsarWorkerAssignmentTest.testFunctionAssignmentsWithRestart(PulsarWorkerAssignmentTest.java:294)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sijie** [comment]
Closed the issue for now. If the problem happens again, please create a new issue.
