### ISSUE TITLE
Pulsar SQL queries fail with "failed: refCnt: 0"

### ISSUE THREAD

**Issue by ofaz** [apache/pulsar#3679]
**Describe the bug**
When querying topics via Pulsar SQL all queries return `failed: refCnt: 0`

**To Reproduce**
A topic is created and data is input via the python client version 2.3.0 with: 
```
class SimpleRecord(Record):
    field1 = String()
	
client = pulsar.Client(PULSAR_ADDRESS)
producer = client.create_producer(PULSAR_TOPIC,                                 schema=JsonSchema(SimpleRecord))

producer.send(SimpleRecord(field1 = 'hello'))
```

This data is then queried via Pulsar SQL e.g. `select * from pulsar."tenant/namespace".topic";`

This returns something along the lines of `Query 20190225_054406_00025_mvftm failed: refCnt: 0`

**Logs from presto-coordinator**

```
2019-02-25T05:44:06.304Z	INFO	20190225_054406_00025_mvftm.1.0-0-116	org.apache.pulsar.sql.presto.PulsarRecordCursor	Initializing split with parameters: PulsarSplit{splitId=0, connectorId='pulsar', schemaName='{TENANT}/{NAMESPACE}', tableName='[REDACTED]', splitSize=2, schema='{
 "name": "SimpleRecord",
 "type": "record",
 "fields": [
  {
   "name": "field1",
   "type": [
    "null",
    "string"
   ]
  }
 ]
}', schemaType=JSON, startPositionEntryId=0, endPositionEntryId=2, startPositionLedgerId=819, endPositionLedgerId=819}
2019-02-25T05:44:06.314Z	ERROR	SplitRunner-12-116	com.facebook.presto.execution.executor.TaskExecutor	Error processing Split 20190225_054406_00025_mvftm.1.0-0 PulsarSplit{splitId=0, connectorId='pulsar', schemaName={TENANT}/{NAMESPACE}', tableName='[REDACTED]', splitSize=2, schema='{
 "name": "SimpleRecord",
 "type": "record",
 "fields": [
  {
   "name": "field1",
   "type": [
    "null",
    "string"
   ]
  }
 ]
}', schemaType=JSON, startPositionEntryId=0, endPositionEntryId=2, startPositionLedgerId=819, endPositionLedgerId=819} (start = 6.21978132751379E8, wall = 23 ms, cpu = 0 ms, wait = 1 ms, calls = 1)
org.apache.pulsar.shade.io.netty.util.IllegalReferenceCountException: refCnt: 0
	at org.apache.pulsar.shade.io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1450)
	at org.apache.pulsar.shade.io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1434)
	at org.apache.pulsar.shade.io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1420)
	at org.apache.pulsar.shade.io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:895)
	at org.apache.pulsar.sql.presto.JSONSchemaHandler.deserialize(JSONSchemaHandler.java:66)
	at org.apache.pulsar.sql.presto.PulsarRecordCursor.advanceNextPosition(PulsarRecordCursor.java:403)
	at com.facebook.presto.spi.RecordPageSource.getNextPage(RecordPageSource.java:93)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:242)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:373)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:282)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:973)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:477)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


2019-02-25T05:44:06.315Z	INFO	SplitRunner-12-116	org.apache.pulsar.sql.presto.PulsarRecordCursor	Closing cursor record
2019-02-25T05:44:06.316Z	ERROR	SplitRunner-12-116	com.facebook.presto.operator.Driver	Error closing operator 0 for task 20190225_054406_00025_mvftm.1.0
org.apache.pulsar.shade.io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at org.apache.pulsar.shade.io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:124)
	at org.apache.pulsar.shade.io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:107)
	at org.apache.pulsar.shade.io.netty.buffer.AbstractPooledDerivedByteBuf$PooledNonRetainedSlicedByteBuf.release0(AbstractPooledDerivedByteBuf.java:271)
	at org.apache.pulsar.shade.io.netty.buffer.AbstractDerivedByteBuf.release(AbstractDerivedByteBuf.java:85)
	at org.apache.pulsar.common.api.raw.RawMessageImpl.release(RawMessageImpl.java:65)
	at org.apache.pulsar.sql.presto.PulsarRecordCursor.close(PulsarRecordCursor.java:507)
	at com.facebook.presto.spi.RecordPageSource.close(RecordPageSource.java:74)
	at com.facebook.presto.operator.TableScanOperator.finish(TableScanOperator.java:185)
	at com.facebook.presto.operator.TableScanOperator.close(TableScanOperator.java:174)
	at com.facebook.presto.operator.Driver.closeAndDestroyOperators(Driver.java:543)
	at com.facebook.presto.operator.Driver.destroyIfNecessary(Driver.java:506)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:680)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:650)
	at com.facebook.presto.operator.Driver.close(Driver.java:180)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.close(SqlTaskExecution.java:992)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.destroy(PrioritizedSplitRunner.java:115)
	at com.facebook.presto.execution.executor.TaskExecutor.splitFinished(TaskExecutor.java:355)
	at com.facebook.presto.execution.executor.TaskExecutor.access$800(TaskExecutor.java:75)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:514)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


2019-02-25T05:44:06.316Z	ERROR	remote-task-callback-60	com.facebook.presto.execution.StageStateMachine	Stage 20190225_054406_00025_mvftm.1 failed
org.apache.pulsar.shade.io.netty.util.IllegalReferenceCountException: refCnt: 0
	at org.apache.pulsar.shade.io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1450)
	at org.apache.pulsar.shade.io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1434)
	at org.apache.pulsar.shade.io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1420)
	at org.apache.pulsar.shade.io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:895)
	at org.apache.pulsar.sql.presto.JSONSchemaHandler.deserialize(JSONSchemaHandler.java:66)
	at org.apache.pulsar.sql.presto.PulsarRecordCursor.advanceNextPosition(PulsarRecordCursor.java:403)
	at com.facebook.presto.spi.RecordPageSource.getNextPage(RecordPageSource.java:93)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:242)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:373)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:282)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:973)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:477)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


2019-02-25T05:44:06.339Z	INFO	query-execution-22	com.facebook.presto.event.query.QueryMonitor	TIMELINE: Query 20190225_054406_00025_mvftm :: Transaction:[63d6212b-6394-4a8b-9a8d-486f7c4690e0] :: elapsed 140ms :: planning 56ms :: scheduling 60ms :: running 32ms :: finishing 0ms :: begin 2019-02-25T05:44:06.177Z :: end 2019-02-25T05:44:06.317Z

```

**Pulsar version**
All components are using the docker image `pulsar-all:2.3.0` 

Client that creates topic & associated schema etc is the Python client pulsar-client 2.3.0 pulled from Pip

Issue created off the back of discussions in #general in the Pulsar Slack with @sijie and others

**Comment by jerrypeng** [comment]
@ofaz was able to reproduce the error with a python pulsar client but everything works fine with the java pulsar client.  Will investigate further.

**Comment by jerrypeng** [comment]
The source exception is actually the following which causes the split to close and the exceptions in the close method

```
2019-02-25T11:00:59.712-0800	ERROR	SplitRunner-2-98	com.facebook.presto.execution.executor.TaskExecutor	Error processing Split 20190225_190056_00000_ps5tb.1.0-1 PulsarSplit{splitId=1, connectorId='pulsar', schemaName='public/default', tableName='test_topic', splitSize=3319, schema='{
 "name": "SimpleRecord",
 "type": "record",
 "fields": [
  {
   "name": "field1",
   "type": [
    "null",
    "string"
   ]
  }
 ]
}', schemaType=JSON, startPositionEntryId=3320, endPositionEntryId=6639, startPositionLedgerId=46, endPositionLedgerId=46} (start = 3.31200428911106E8, wall = 440 ms, cpu = 0 ms, wait = 1 ms, calls = 1)
org.apache.pulsar.shade.io.netty.util.IllegalReferenceCountException: refCnt: 0
	at org.apache.pulsar.shade.io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1450)
	at org.apache.pulsar.shade.io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1434)
	at org.apache.pulsar.shade.io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1420)
	at org.apache.pulsar.shade.io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:895)
	at org.apache.pulsar.sql.presto.JSONSchemaHandler.deserialize(JSONSchemaHandler.java:66)
	at org.apache.pulsar.sql.presto.PulsarRecordCursor.advanceNextPosition(PulsarRecordCursor.java:404)
	at com.facebook.presto.spi.RecordPageSource.getNextPage(RecordPageSource.java:93)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:242)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:373)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:282)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:973)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:477)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jerrypeng** [comment]
@ofaz I have a fix up for this issue:

https://github.com/apache/pulsar/pull/3684

in the mean time, to side step this issue, you can enable batching in your producer:

```
producer = client.create_producer(PULSAR_TOPIC,                             schema=JsonSchema(SimpleRecord)), batching_enabled=True)
```
