### ISSUE TITLE
[pulsar-function] intermittent test failure due to deadlock 

### ISSUE THREAD

**Issue by rdhabalia** [apache/pulsar#3768]
[org.apache.pulsar.functions.worker.PulsarWorkerAssignmentTest.shutdown()](https://builds.apache.org/job/pulsar_precommit_java8/7046/testReport/junit/org.apache.pulsar.functions.worker/PulsarWorkerAssignmentTest/shutdown/) has intermittent failure due to deadlock into function-worker. Disabling this for now and we have to enable back once deadlock issue is fixed at function-worker.
```
Error Message
Method org.apache.pulsar.functions.worker.PulsarWorkerAssignmentTest.shutdown() didn't finish within the time-out 60000
Stacktrace
org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.functions.worker.PulsarWorkerAssignmentTest.shutdown() didn't finish within the time-out 60000
	at io.netty.channel.epoll.Native.eventFdWrite(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.wakeup(EpollEventLoop.java:169)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:799)
	at io.netty.channel.AbstractChannelHandlerContext.safeExecute(AbstractChannelHandlerContext.java:1013)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:825)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:837)
	at org.apache.pulsar.client.impl.ClientCnx.sendRequestWithId(ClientCnx.java:685)
	at org.apache.pulsar.client.impl.ProducerImpl.closeAsync(ProducerImpl.java:609)
	at org.apache.pulsar.functions.sink.PulsarSink$PulsarSinkProcessorBase.close(PulsarSink.java:130)
	at org.apache.pulsar.functions.sink.PulsarSink.close(PulsarSink.java:306)
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.close(JavaInstanceRunnable.java:482)
	at org.apache.pulsar.functions.runtime.ThreadRuntime.stop(ThreadRuntime.java:128)
	at org.apache.pulsar.functions.runtime.RuntimeSpawner.close(RuntimeSpawner.java:151)
	at org.apache.pulsar.functions.worker.FunctionActioner.stopFunction(FunctionActioner.java:243)
	at org.apache.pulsar.functions.worker.FunctionRuntimeManager.conditionallyStopFunction(FunctionRuntimeManager.java:868)
	at org.apache.pulsar.functions.worker.FunctionRuntimeManager.stopFunction(FunctionRuntimeManager.java:441)
	at org.apache.pulsar.functions.worker.FunctionRuntimeManager.lambda$stopAllOwnedFunctions$1(FunctionRuntimeManager.java:429)
	at org.apache.pulsar.functions.worker.FunctionRuntimeManager$$Lambda$795/1890737615.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:981)
	at org.apache.pulsar.functions.worker.FunctionRuntimeManager.stopAllOwnedFunctions(FunctionRuntimeManager.java:426)
	at org.apache.pulsar.functions.worker.FunctionRuntimeManager.close(FunctionRuntimeManager.java:813)
	at org.apache.pulsar.functions.worker.WorkerService.stop(WorkerService.java:218)
	at org.apache.pulsar.functions.worker.PulsarWorkerAssignmentTest.shutdown(PulsarWorkerAssignmentTest.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by srkukarni** [comment]
@rdhabalia Could you please add more color on what the dead lock is?

**Comment by merlimat** [comment]
I think he's referring to the `PulsarWorkerAssignmentTest` test getting stuck during shutdown. There's already #3749 to fix that...though the ehm challenge is to get all these flaky to pass at once.

**Comment by tisonkun** [comment]
Closed as stale and it seems to be fixed. Please open a new issue if it's still relevant to the maintained versions.
