### ISSUE TITLE
failed to load RocksDB jni library

### ISSUE THREAD

**Issue by Archerxy** [apache/pulsar#3820]
pulsar version 2.3
java version java8
rocksdbjni-5.13.1

At first I got an error: "invalid -XX:MaxDirectMemory=4g"  (default config) and  "The specified size exceeds the maximum representable size.".
Then I changed it to 3g and I got "failed to load RocksDB jni library"

Here's the error now:
Exception in thread "main" java.io.IOException: Failed to load RocksDB JNI library
	at org.apache.bookkeeper.bookie.storage.ldb.KeyValueStorageRocksDB.<init>(KeyValueStorageRocksDB.java:91)
	at org.apache.bookkeeper.bookie.storage.ldb.KeyValueStorageRocksDB.<init>(KeyValueStorageRocksDB.java:83)
	at org.apache.bookkeeper.bookie.storage.ldb.KeyValueStorageRocksDB.lambda$static$0(KeyValueStorageRocksDB.java:58)

what should I do?

**Comment by GarimaM92** [comment]
@Archerxy I am facing the same issue. Can you please help me with the solution?

**Comment by ChangWinde** [comment]
@GarimaM92 Do you solve this problem？I met this problem before and solved it by updata the version of glibc, which is required more than 2.12. But this time the version of glibc is 2.28 ,this problem appear again.

**Comment by Gray-Fullbuster** [comment]
@ChangWinde Hello ,Do you solve this problem？I meet the same problem.My glibc's version is also 2.28. Is this version too low?

**Comment by Gray-Fullbuster** [comment]
@Archerxy Did you solve this problem? "Failed to load RocksDB JNI library" How to solve this problem
