### ISSUE TITLE
2.3.0 Broker Gets "Insufficient configured threads"

### ISSUE THREAD

**Issue by oliverisaac** [apache/pulsar#3948]
**Describe the bug**
I am running Pulsar in a kubernetes cluster. When I upgrade to 2.3.0 I am unable to get it to listen for https requests. Jetty throws an insufficient threads error:

'''
20:02:06.036 [main] ERROR org.apache.pulsar.broker.PulsarService - java.lang.IllegalStateException: Insufficient configured threads: required=4 < max=4 for WebExecutorThreadPool[etp1373646877]@51e0301d{STARTED,4<=4<=4,i=2,q=0,ReservedThreadExecutor@221ca495{s=0/1,p=0}}
org.apache.pulsar.broker.PulsarServerException: java.lang.IllegalStateException: Insufficient configured threads: required=4 < max=4 for WebExecutorThreadPool[etp1373646877]@51e0301d{STARTED,4<=4<=4,i=2,q=0,ReservedThreadExecutor@221ca495{s=0/1,p=0}}
	at org.apache.pulsar.broker.web.WebService.start(WebService.java:192) ~[org.apache.pulsar-pulsar-broker-2.3.0.jar:2.3.0]
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:427) [org.apache.pulsar-pulsar-broker-2.3.0.jar:2.3.0]
	at org.apache.pulsar.PulsarBrokerStarter$BrokerStarter.start(PulsarBrokerStarter.java:239) [org.apache.pulsar-pulsar-broker-2.3.0.jar:2.3.0]
	at org.apache.pulsar.PulsarBrokerStarter.main(PulsarBrokerStarter.java:293) [org.apache.pulsar-pulsar-broker-2.3.0.jar:2.3.0]
Caused by: java.lang.IllegalStateException: Insufficient configured threads: required=4 < max=4 for WebExecutorThreadPool[etp1373646877]@51e0301d{STARTED,4<=4<=4,i=2,q=0,ReservedThreadExecutor@221ca495{s=0/1,p=0}}
	at org.eclipse.jetty.util.thread.ThreadPoolBudget.check(ThreadPoolBudget.java:155) ~[org.eclipse.jetty-jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.ThreadPoolBudget.leaseTo(ThreadPoolBudget.java:129) ~[org.eclipse.jetty-jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.ThreadPoolBudget.leaseFrom(ThreadPoolBudget.java:181) ~[org.eclipse.jetty-jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:281) ~[org.eclipse.jetty-jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81) ~[org.eclipse.jetty-jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:235) ~[org.eclipse.jetty-jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[org.eclipse.jetty-jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.Server.doStart(Server.java:395) ~[org.eclipse.jetty-jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[org.eclipse.jetty-jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.apache.pulsar.broker.web.WebService.start(WebService.java:188) ~[org.apache.pulsar-pulsar-broker-2.3.0.jar:2.3.0]
	... 3 more
20:02:06.044 [main] ERROR org.apache.pulsar.PulsarBrokerStarter - Failed to start pulsar service.
org.apache.pulsar.broker.PulsarServerException: org.apache.pulsar.broker.PulsarServerException: java.lang.IllegalStateException: Insufficient configured threads: required=4 < max=4 for WebExecutorThreadPool[etp1373646877]@51e0301d{STARTED,4<=4<=4,i=2,q=0,ReservedThreadExecutor@221ca495{s=0/1,p=0}}
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:448) ~[org.apache.pulsar-pulsar-broker-2.3.0.jar:2.3.0]
	at org.apache.pulsar.PulsarBrokerStarter$BrokerStarter.start(PulsarBrokerStarter.java:239) ~[org.apache.pulsar-pulsar-broker-2.3.0.jar:2.3.0]
	at org.apache.pulsar.PulsarBrokerStarter.main(PulsarBrokerStarter.java:293) [org.apache.pulsar-pulsar-broker-2.3.0.jar:2.3.0]
Caused by: org.apache.pulsar.broker.PulsarServerException: java.lang.IllegalStateException: Insufficient configured threads: required=4 < max=4 for WebExecutorThreadPool[etp1373646877]@51e0301d{STARTED,4<=4<=4,i=2,q=0,ReservedThreadExecutor@221ca495{s=0/1,p=0}}
	at org.apache.pulsar.broker.web.WebService.start(WebService.java:192) ~[org.apache.pulsar-pulsar-broker-2.3.0.jar:2.3.0]
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:427) ~[org.apache.pulsar-pulsar-broker-2.3.0.jar:2.3.0]
	... 2 more
Caused by: java.lang.IllegalStateException: Insufficient configured threads: required=4 < max=4 for WebExecutorThreadPool[etp1373646877]@51e0301d{STARTED,4<=4<=4,i=2,q=0,ReservedThreadExecutor@221ca495{s=0/1,p=0}}
	at org.eclipse.jetty.util.thread.ThreadPoolBudget.check(ThreadPoolBudget.java:155) ~[org.eclipse.jetty-jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.ThreadPoolBudget.leaseTo(ThreadPoolBudget.java:129) ~[org.eclipse.jetty-jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.ThreadPoolBudget.leaseFrom(ThreadPoolBudget.java:181) ~[org.eclipse.jetty-jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:281) ~[org.eclipse.jetty-jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81) ~[org.eclipse.jetty-jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:235) ~[org.eclipse.jetty-jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[org.eclipse.jetty-jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.Server.doStart(Server.java:395) ~[org.eclipse.jetty-jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[org.eclipse.jetty-jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.apache.pulsar.broker.web.WebService.start(WebService.java:188) ~[org.apache.pulsar-pulsar-broker-2.3.0.jar:2.3.0]
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:427) ~[org.apache.pulsar-pulsar-broker-2.3.0.jar:2.3.0]
	... 2 more
'''

**To Reproduce**
1. Configure broker:
```
  webServicePortTls: "8443"
  brokerServicePortTls: "6651"
```
2. Run the pulsar:2.3.0 release.

**Expected behavior**
Should be able to use `pulsar-admin clusters list` with TLS AND should be able to curl http://<BROKER_URL>:<HTTP_PORT>/metrics/

**Additional context**
This configuration works in 2.2.1.

**Comment by sijie** [comment]
@oliverisaac - 

this is a jetty bug when broker running on a 1-cpu-core machine. you can configure `numHttpServerThreads` to be more than 2 to get around this bug. The bug is fixed and will be released as part of 2.3.1 release.

**Comment by oliverisaac** [comment]
Great, thanks! That seems to have fixed it

**Comment by phreed** [comment]
I tried setting numHttpServerThreads=3 and it simply changed the error so that instead of complaining about 2 it now faults 3.
Increasing to numHttpServerThreads=8 seems to do the trick.
