### ISSUE TITLE
[java client] run PulsarFunctionE2ETest failed

### ISSUE THREAD

**Issue by wolfstudy** [apache/pulsar#3964]
**Describe the bug**

```
2019-04-02\T\05:07:32.953 [INFO] Running org.apache.pulsar.io.PulsarFunctionE2ETest
2019-04-02\T\05:09:37.953 [ERROR] Tests run: 14, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 124.972 s <<< FAILURE! - in org.apache.pulsar.io.PulsarFunctionE2ETest
2019-04-02\T\05:09:37.953 [ERROR] testPulsarSourceStatsWithUrl(org.apache.pulsar.io.PulsarFunctionE2ETest)  Time elapsed: 1.325 s  <<< FAILURE!
java.lang.AssertionError: expected [1] but found [0]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:652)
	at org.testng.Assert.assertEquals(Assert.java:662)
	at org.apache.pulsar.io.PulsarFunctionE2ETest.testPulsarSourceStats(PulsarFunctionE2ETest.java:706)
	at org.apache.pulsar.io.PulsarFunctionE2ETest.testPulsarSourceStatsWithUrl(PulsarFunctionE2ETest.java:786)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by aahmed-se** [comment]
Is this a repeated behaviour ?

**Comment by wolfstudy** [comment]
already fixed
