### ISSUE TITLE
Pulsar standalone start failed

### ISSUE THREAD

**Issue by tuteng** [apache/pulsar#4002]
**Describe the bug**

**To Reproduce**
1. Go to pulsar
2. ./bin/pulsar standalone

**Expected behavior**
Pulsar standalone start success

**Screenshots**
```
11:51:45.698 [DLM-/stream/storage-OrderedScheduler-4-0] INFO  org.apache.bookkeeper.stream.storage.impl.sc.ZkStorageContainerManager - Storage container (org.apache.bookkeeper.stream.storage.impl.sc.StorageContainerImpl@7f2083be) is added to live set.
11:52:43.962 [SyncThread-7-1] INFO  org.apache.bookkeeper.bookie.EntryLogManagerBase - Creating a new entry log file because current active log channel has not initialized yet
11:52:43.965 [SyncThread-7-1] INFO  org.apache.bookkeeper.bookie.EntryLoggerAllocator - Created new entry log file data/standalone/bookkeeper0/current/0.log for logId 0.
11:52:43.970 [pool-5-thread-1] INFO  org.apache.bookkeeper.bookie.EntryLoggerAllocator - Created new entry log file data/standalone/bookkeeper0/current/1.log for logId 1.


^[[BException in thread "main" io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:530)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:482)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:699)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.handler.proxy.ProxyConnectException: http, none, /127.0.0.1:1086 => 192.168.199.133:4181, disconnected
	at io.netty.handler.proxy.ProxyHandler.channelInactive(ProxyHandler.java:236)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:420)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:390)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:355)
	at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:282)
	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:223)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:466)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
```

**Desktop (please complete the following information):**
 - OS: [e.g.Mac]
 - jdk1.8

**Additional context**

**Comment by tuteng** [comment]
./bin/pulsar standalone -nss
start success

**Comment by foreversunyao** [comment]
what I met is another error , but could due to **stream storage** as well.

```
23:23:54.839 [DLM-/stream/storage-OrderedScheduler-4-0] INFO  org.apache.bookkeeper.stream.storage.impl.sc.StorageContainerRegistryImpl - Successfully started registered StorageContainer ('1').
23:23:54.839 [DLM-/stream/storage-OrderedScheduler-4-0] INFO  org.apache.bookkeeper.stream.storage.impl.sc.ZkStorageContainerManager - Successfully started storage container (1)
23:23:54.839 [DLM-/stream/storage-OrderedScheduler-4-0] INFO  org.apache.bookkeeper.stream.storage.impl.sc.ZkStorageContainerManager - Storage container (org.apache.bookkeeper.stream.storage.impl.sc.StorageContainerImpl@6f79aa6f) is added to live set.
23:23:58.769 [main] INFO  org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble - Creating default namespace
Exception in thread "main" org.apache.bookkeeper.clients.exceptions.ClientException: fail to access its root range : code = INTERNAL_SERVER_ERROR
        at org.apache.bookkeeper.clients.impl.internal.ProtocolInternalUtils.createRootRangeException(ProtocolInternalUtils.java:105)
        at org.apache.bookkeeper.clients.impl.internal.RootRangeClientImpl.processCreateNamespaceResponse(RootRangeClientImpl.java:129)
        at org.apache.bookkeeper.clients.impl.internal.RootRangeClientImpl.lambda$createNamespace$4(RootRangeClientImpl.java:118)
        at org.apache.bookkeeper.clients.utils.RpcUtils$1.onSuccess(RpcUtils.java:78)
        at com.google.common.util.concurrent.Futures$4.run(Futures.java:1135)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:902)
        at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:813)
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:655)

```

**Comment by tuteng** [comment]
Reference https://github.com/apache/pulsar/issues/4593

**Comment by pgandhap** [comment]
Hi @tuteng 

Iam using windows machine . Even in my case also pulsar standalone started failing . 

I followed this document -> https://pulsar.apache.org/docs/en/standalone/#install-pulsar-using-binary-release

I downloaded pulsar through binary release using wget command . 

Followed below steps : 

1. wget https://archive.apache.org/dist/pulsar/pulsar-2.8.1/apache-pulsar-2.8.1-bin.tar.gz
2. tar xvfz apache-pulsar-2.8.1-bin.tar.gz
3. cd apache-pulsar-2.8.1
4. bin/pulsar standalone

In this 3 steps are done . While running ( bin/pulsar standalone ) to start pulsar , which is not giving any output instead of it's asking me to select any one method to open pulsar file which is inside bin folder .
![pulsar-command](https://user-images.githubusercontent.com/71866730/143538530-092c923a-2854-46f2-a459-2a6981c56eb2.PNG)

Please help me on this issue . Thanks !!!

**Comment by M1loseph** [comment]
Hello, could someone explain why `-nss` flag solves this issue and why it appears in the first place? I would be very grateful

**Comment by wthahaha** [comment]
> -nss

    -nss, --no-stream-storage
      Disable stream storage
      Default: false

**Comment by tisonkun** [comment]
Closed as unactionable.

Also, follow the instructions at https://pulsar.apache.org/docs/next/getting-started-standalone should be fine to start a standalone server. If there're still other issues, feel free to open new ones.
