### ISSUE TITLE
server checksum error when using pulsar-log4j2-appender

### ISSUE THREAD

**Issue by nyluke** [apache/pulsar#4051]
I added pulsar-log4j2-appender:2.3.1 to my project and I am running an apache-pulsar-2.3.1 standalone server. I've configured the appender like this:

```       
         <Pulsar name="Pulsar" serviceUrl="pulsar://localhost:6650" topic="persistent://public/default/log" avoidRecursive="false">
            <PatternLayout pattern="[%m]"/>
        </Pulsar>
        <Root level="debug" additivity="false">
            <AppenderRef ref="Pulsar"/>
        </Root>
```

When I start my app, I get this error repeated on the server:

```
[pulsar-io-49-52] ERROR org.apache.pulsar.broker.service.Producer - [PersistentTopic{topic=persistent://public/default/log}] [pulsar-log4j2-appender-persistent://public/default/log] Failed to verify checksum
[pulsar-io-49-52] WARN  org.apache.pulsar.broker.service.ServerCnx - [/127.0.0.1:47002] Got exception IndexOutOfBoundsException : readerIndex(0) + length(4) exceeds writerIndex(2): PooledSlicedByteBuf(ridx: 0, widx: 2, cap: 2/2, unwrapped: PooledUnsafeDirectByteBuf(ridx: 570, widx: 8192, cap: 8192))
java.lang.IndexOutOfBoundsException: readerIndex(0) + length(4) exceeds writerIndex(2): PooledSlicedByteBuf(ridx: 0, widx: 2, cap: 2/2, unwrapped: PooledUnsafeDirectByteBuf(ridx: 570, widx: 8192, cap: 8192))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1437) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:809) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.buffer.AbstractByteBuf.readUnsignedInt(AbstractByteBuf.java:825) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at org.apache.pulsar.common.api.PulsarDecoder.channelRead(PulsarDecoder.java:81) ~[org.apache.pulsar-pulsar-common-2.3.1.jar:2.3.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by foreversunyao** [comment]
@nyluke , can you try to add below code to https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Producer.java#L178

```
   for(int i=0;i< headersAndPayload.readableBytes();i++) {
                        System.out.print(String.format("%02X ", headersAndPayload.getByte(i)));
                    }
```

or try to tcpdump the package you sent ?
it seems some buffer package is incomplete .

**Comment by nyluke** [comment]
```
[ForkJoinPool.commonPool-worker-4] INFO  org.apache.pulsar.broker.service.ServerCnx - [/127.0.0.1:40776] Created new producer: Producer{topic=PersistentTopic{topic=persistent://public/default/log}, client=/127.0.0.1:40776, producerName=pulsar-log4j2-appender-persistent://public/default/log, producerId=0}
00 00 00 0A 08 06 32 06 08 00 10 00 18 02 0E 01 3C 39 F4 0B 00 00 00 46 0A 36 70 75 6C 73 61 72 2D 6C 6F 67 34 6A 32 2D 61 70 70 65 6E 64 65 72 2D 70 65 72 73 69 73 74 65 6E 74 3A 2F 2F 70 75 62 6C 69 63 2F 64 65 66 61 75 6C 74 2F 6C 6F 67 10 00 18 87 E9 DC B4 A2 2D 58 02 82 01 00 00 00 00 03 18 9D 01 5B 5B 70 65 72 73 69 73 74 65 6E 74 3A 2F 2F 70 75 62 6C 69 63 2F 64 65 66 61 75 6C 74 2F 6C 6F 67 5D 20 5B 70 75 6C 73 61 72 2D 6C 6F 67 34 6A 32 2D 61 70 70 65 6E 64 65 72 2D 70 65 72 73 69 73 74 65 6E 74 3A 2F 2F 70 75 62 6C 69 63 2F 64 65 66 61 75 6C 74 2F 6C 6F 67 5D 20 42 61 74 63 68 69 6E 67 20 74 68 65 20 6D 65 73 73 61 67 65 73 20 66 72 6F 6D 20 74 68 65 20 62 61 74 63 68 20 63 6F 6E 74 61 69 6E 65 72 20 66 72 6F 6D 20 74 69 6D 65 72 20 74 68 72 65 61 64 5D 00 00 00 03 18 9B 01 5B 5B 70 65 72 73 69 73 74 65 6E 74 3A 2F 2F 70 75 62 6C 69 63 2F 64 65 66 61 75 6C 74 2F 6C 6F 67 5D 20 5B 70 75 6C 73 61 72 2D 6C 6F 67 34 6A 32 2D 61 70 70 65 6E 64 65 72 2D 70 65 72 73 69 73 74 65 6E 74 3A 2F 2F 70 75 62 6C 69 63 2F 64 65 66 61 75 6C 74 2F 6C 6F 67 5D 20 42 61 74 63 68 69 6E 67 20 74 68 65 20 6D 65 73 73 61 67 65 73 20 66 72 6F 6D 20 74 68 65 20 62 61 74 63 10:40:11.772 [pulsar-io-49-10] INFO  org.apache.pulsar.broker.service.ServerCnx - Closed connection from /127.0.0.1:40730
68 20 63 6F 6E 74 61 69 6E 65 72 20 10:40:11.773 [pulsar-io-49-6] INFO  org.apache.pulsar.broker.service.ServerCnx - Closed connection from /127.0.0.1:40722
77 69 74 68 20 31 20 6D 65 73 73 61 67 65 73 5D 00 00 00 03 18 85 01 5B 5B 70 65 72 73 69 73 74 65 6E 74 3A 2F 2F 70 75 62 6C 69 63 2F 64 65 66 61 75 6C 74 2F 6C 6F 67 5D 20 5B 70 75 6C 73 61 72 2D 6C 6F 67 34 6A 32 2D 61 70 70 65 6E 64 65 72 2D 70 65 72 73 69 73 74 65 6E 74 3A 2F 2F 70 75 62 6C 69 63 2F 64 65 66 61 75 6C 74 2F 6C 6F 67 5D 20 6E 75 6D 20 6D 65 73 73 61 67 65 73 20 69 6E 20 62 61 74 63 68 20 62 65 69 6E 67 10:40:11.814 [pulsar-io-49-12] ERROR org.apache.pulsar.broker.service.Producer - [PersistentTopic{topic=persistent://public/default/log}] [pulsar-log4j2-appender-persistent://public/default/log] Failed to verify checksum
10:40:11.815 [pulsar-io-49-12] WARN  org.apache.pulsar.broker.service.ServerCnx - [/127.0.0.1:40776] Got exception IndexOutOfBoundsException : readerIndex(0) + length(4) exceeds writerIndex(2): PooledSlicedByteBuf(ridx: 0, widx: 2, cap: 2/2, unwrapped: PooledUnsafeDirectByteBuf(ridx: 570, widx: 1345, cap: 8192))
java.lang.IndexOutOfBoundsException: readerIndex(0) + length(4) exceeds writerIndex(2): PooledSlicedByteBuf(ridx: 0, widx: 2, cap: 2/2, unwrapped: PooledUnsafeDirectByteBuf(ridx: 570, widx: 1345, cap: 8192))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1437) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:809) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.buffer.AbstractByteBuf.readUnsignedInt(AbstractByteBuf.java:825) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at org.apache.pulsar.common.api.PulsarDecoder.channelRead(PulsarDecoder.java:83) ~[pulsar-common.jar:2.4.0-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.31.Final.jar:4.1.31.Final]
```

**Comment by sijie** [comment]
@nyluke did you happen to resolve the problem?

**Comment by nyluke** [comment]
no i didn’t

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant in maintained versions.
