### ISSUE TITLE
[pulsar functions] import java class conflicts

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar#4321]
**Describe the bug**
Add a dedicated JerseyClient dependency on functions throws conflicts during import.

```
java.lang.RuntimeException: java.lang.ClassNotFoundException: org.apache.pulsar.functions.runtime.shaded.org.glassfish.jersey.client.JerseyClientBuilder
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:110) ~[java-instance.jar:2.4.0-SNAPSHOT]
        at javax.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:121) ~[java-instance.jar:2.4.0-SNAPSHOT]
        at com.clevercloud.pulsar.util.PulsarRESTAPIUtils.createTenant(PulsarRESTAPIUtils.java:22) ~[pulsar-functions-0.1.0-SNAPSHOT.jar-unpacked/:?]
        at com.clevercloud.pulsar.function.RouteApplicationsAddonsLogs.lambda$publishToUser$0(RouteApplicationsAddonsLogs.java:83) ~[pulsar-functions-0.1.0-SNAPSHOT.jar-unpacked/:?]
        at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870) ~[?:1.8.0_192]
        at java.util.concurrent.CompletableFuture.uniExceptionallyStage(CompletableFuture.java:884) ~[?:1.8.0_192]
        at java.util.concurrent.CompletableFuture.exceptionally(CompletableFuture.java:2196) ~[?:1.8.0_192]
        at com.clevercloud.pulsar.function.RouteApplicationsAddonsLogs.publishToUser(RouteApplicationsAddonsLogs.java:77) ~[pulsar-functions-0.1.0-SNAPSHOT.jar-unpacked/:?]
        at com.clevercloud.pulsar.function.RouteApplicationsAddonsLogs.lambda$publishToUser$0(RouteApplicationsAddonsLogs.java:88) ~[pulsar-functions-0.1.0-SNAPSHOT.jar-unpacked/:?]
        at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870) ~[?:1.8.0_192]
        at java.util.concurrent.CompletableFuture.uniExceptionallyStage(CompletableFuture.java:884) ~[?:1.8.0_192]
        at java.util.concurrent.CompletableFuture.exceptionally(CompletableFuture.java:2196) ~[?:1.8.0_192]
        at com.clevercloud.pulsar.function.RouteApplicationsAddonsLogs.publishToUser(RouteApplicationsAddonsLogs.java:77) ~[pulsar-functions-0.1.0-SNAPSHOT.jar-unpacked/:?]
        at com.clevercloud.pulsar.function.RouteApplicationsAddonsLogs.lambda$publishToUser$0(RouteApplicationsAddonsLogs.java:88) ~[pulsar-functions-0.1.0-SNAPSHOT.jar-unpacked/:?]
        at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870) ~[?:1.8.0_192]
        at java.util.concurrent.CompletableFuture.uniExceptionallyStage(CompletableFuture.java:884) ~[?:1.8.0_192]
        at java.util.concurrent.CompletableFuture.exceptionally(CompletableFuture.java:2196) ~[?:1.8.0_192]
        at com.clevercloud.pulsar.function.RouteApplicationsAddonsLogs.publishToUser(RouteApplicationsAddonsLogs.java:77) ~[pulsar-functions-0.1.0-SNAPSHOT.jar-unpacked/:?]
        at com.clevercloud.pulsar.function.RouteApplicationsAddonsLogs.lambda$publishToUser$0(RouteApplicationsAddonsLogs.java:88) ~[pulsar-functions-0.1.0-SNAPSHOT.jar-unpacked/:?]
        at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870) [?:1.8.0_192]
        at java.util.concurrent.CompletableFuture.uniExceptionallyStage(CompletableFuture.java:884) [?:1.8.0_192]
        at java.util.concurrent.CompletableFuture.exceptionally(CompletableFuture.java:2196) [?:1.8.0_192]
        at com.clevercloud.pulsar.function.RouteApplicationsAddonsLogs.publishToUser(RouteApplicationsAddonsLogs.java:77) [pulsar-functions-0.1.0-SNAPSHOT.jar-unpacked/:?]
        at com.clevercloud.pulsar.function.RouteApplicationsAddonsLogs.process(RouteApplicationsAddonsLogs.java:56) [pulsar-functions-0.1.0-SNAPSHOT.jar-unpacked/:?]
        at com.clevercloud.pulsar.function.RouteApplicationsAddonsLogs.process(RouteApplicationsAddonsLogs.java:22) [pulsar-functions-0.1.0-SNAPSHOT.jar-unpacked/:?]
        at org.apache.pulsar.functions.instance.JavaInstance.handleMessage(JavaInstance.java:63) [java-instance.jar:2.4.0-SNAPSHOT]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:257) [java-instance.jar:2.4.0-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.lang.ClassNotFoundException: org.apache.pulsar.functions.runtime.shaded.org.glassfish.jersey.client.JerseyClientBuilder
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_192]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_192]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_192]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_192]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_192]
        at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_192]
        at javax.ws.rs.client.FactoryFinder.newInstance(FactoryFinder.java:111) ~[java-instance.jar:2.4.0-SNAPSHOT]
        at javax.ws.rs.client.FactoryFinder.find(FactoryFinder.java:209) ~[java-instance.jar:2.4.0-SNAPSHOT]
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:94) ~[java-instance.jar:2.4.0-SNAPSHOT]
        ... 27 more
```

`pom.xml` looks like:
```
<dependency>
  <groupId>org.glassfish.jersey.core</groupId>
  <artifactId>jersey-client</artifactId>
  <version>2.28</version>
</dependency>
<dependency>
  <groupId>org.glassfish.jersey.inject</groupId>
  <artifactId>jersey-hk2</artifactId>
  <version>2.28</version>
</dependency>
```

And the imports of the function:
```
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.Entity;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

import org.apache.commons.codec.binary.Base64;

import org.glassfish.jersey.client.authentication.HttpAuthenticationFeature;
import org.glassfish.jersey.client.ClientConfig;
import org.glassfish.jersey.logging.LoggingFeature;
```

I think it's about reflections on `javax.ws.rs.client.ClientBuilder` when it needs the jerserbuilder.

**Comment by KannarFr** [comment]
I got the same issue, even when I remove the dependencies of my functions (i.e. simple jar, not uber-jar one).

**Comment by jerrypeng** [comment]
@KannarFr even currently most the the internal function dependencies are shaded

**Comment by sijie** [comment]
@KannarFr can you double check if your problem is fixed in latest master?

**Comment by KannarFr** [comment]
@sijie It is not. Still have `java.lang.RuntimeException: java.lang.ClassNotFoundException: org.apache.pulsar.functions.runtime.shaded.org.glassfish.jersey.client.JerseyClientBuilder`. You can reproduce using createTenant method from function body:

```java
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.Entity;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

import org.apache.commons.codec.binary.Base64;

import org.glassfish.jersey.client.authentication.HttpAuthenticationFeature;
import org.glassfish.jersey.client.ClientConfig;
import org.glassfish.jersey.logging.LoggingFeature;

public class PulsarRESTAPIUtils {
  public final static String PULSAR_REST_API_URL = "pulsarurl";
  public final static String PULSAR_AUTH_STRING = "token";

  public static void createTenant(String tenant) throws Exception {
    String path = new StringBuilder("tenants/").append(tenant).toString();

    Response response = ClientBuilder
      .newClient()
      .target(new StringBuilder(PULSAR_REST_API_URL).append(path).toString())
      .request()
      .header("Content-Type", "application/json")
      .header("Authorization", new StringBuilder("Bearer ").append(PULSAR_AUTH_STRING).toString())
      .put(Entity.json(""));

    if (response.getStatus() < 200 && response.getStatus() > 299) {
      throw new Exception(String.format("%d on creation of tenant %s", response.getStatus(), tenant));
    }
  }
}
```

But is `org.glassfish.jersey.client` shaded, and it changes nothing that this method comes from static context?

**Comment by KannarFr** [comment]
Fixed. Jersey is now removed from shaded.

**Comment by Eminov-Vasif** [comment]
Hello 
I am facing below issue:
Exception in thread "main" java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:146)
	at org.jboss.resteasy.client.jaxrs.HttpClientBuilder43.initDefaultEngine43(HttpClientBuilder43.java:111)
	at org.jboss.resteasy.client.jaxrs.ResteasyClientBuilder.build(ResteasyClientBuilder.java:422)
	at org.jboss.resteasy.client.jaxrs.ResteasyClientBuilder.build(ResteasyClientBuilder.java:60)
	at javax.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:114)
	at client.ClientClassSender.postListValueInJSON(ClientClassSender.java:50)
	at webservice.WebService.main(WebService.java:43)


Please help me
