### ISSUE TITLE
Intermittent test failure in ReplicatorRateLimiterTest

### ISSUE THREAD

**Issue by merlimat** [apache/pulsar#4345]
Seen in https://builds.apache.org/job/pulsar_precommit_java8/9140/testReport/junit/org.apache.pulsar.broker.service/ReplicatorRateLimiterTest/setup/

```
Error Message
Method org.apache.pulsar.broker.service.ReplicatorRateLimiterTest.setup() didn't finish within the time-out 30000
Stacktrace
org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.broker.service.ReplicatorRateLimiterTest.setup() didn't finish within the time-out 30000
	at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.apply(AsyncHttpConnector.java:133)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:278)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
	at org.glassfish.jersey.client.JerseyInvocation$$Lambda$352/1202274369.call(Unknown Source)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:456)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.put(JerseyInvocation.java:340)
	at org.apache.pulsar.client.admin.internal.TenantsImpl.createTenant(TenantsImpl.java:66)
	at org.apache.pulsar.broker.service.ReplicatorTestBase.setup(ReplicatorTestBase.java:217)
	at org.apache.pulsar.broker.service.ReplicatorRateLimiterTest.setup(ReplicatorRateLimiterTest.java:59)

```

cc/ @jiazhai

**Comment by jiazhai** [comment]
@merlimat looked at the log. not able to find any clue. It is a timeout in setup(), except setting the timeout to 30s, ReplicatorRateLimiterTest calls super.setup, not do anything additional.

**Comment by jiazhai** [comment]
seems not seen this issue for a long time. would like to close this first.
