### ISSUE TITLE
Intermittent test failure int KeySharedSubscriptionTest.testConsumerCrashSendAndReceiveWithHashRangeStickyKeyConsumerSelector

### ISSUE THREAD

**Issue by merlimat** [apache/pulsar#4353]
https://builds.apache.org/job/pulsar_precommit_java8/9152/testReport/junit/org.apache.pulsar.client.api/KeySharedSubscriptionTest/testConsumerCrashSendAndReceiveWithHashRangeStickyKeyConsumerSelector/

```
org.apache.pulsar.client.api.KeySharedSubscriptionTest.testConsumerCrashSendAndReceiveWithHashRangeStickyKeyConsumerSelector

Failing for the past 1 build (Since Failed#9152 )
Took 5 min 0 sec.
add description
Error Message
Method org.apache.pulsar.client.api.KeySharedSubscriptionTest.testConsumerCrashSendAndReceiveWithHashRangeStickyKeyConsumerSelector() didn't finish within the time-out 300000
Stacktrace
org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.client.api.KeySharedSubscriptionTest.testConsumerCrashSendAndReceiveWithHashRangeStickyKeyConsumerSelector() didn't finish within the time-out 300000
	at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:457)
	at org.apache.pulsar.common.util.collections.GrowableArrayBlockingQueue.take(GrowableArrayBlockingQueue.java:191)
	at org.apache.pulsar.client.impl.ConsumerImpl.internalReceive(ConsumerImpl.java:312)
	at org.apache.pulsar.client.impl.ConsumerBase.receive(ConsumerBase.java:108)
	at org.apache.pulsar.client.api.KeySharedSubscriptionTest.testConsumerCrashSendAndReceiveWithHashRangeStickyKeyConsumerSelector(KeySharedSubscriptionTest.java:238)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

cc/ @codelipenghui

**Comment by jiazhai** [comment]
Seems this is related to changes in https://github.com/apache/pulsar/pull/4329 ?

**Comment by jiazhai** [comment]
@codelipenghui  Hi Penghui  is this the fix?
https://github.com/apache/pulsar/pull/4352/commits/9b5f749c82aeb0f3579333bddbe3fec6175f3ad0

**Comment by merlimat** [comment]
Yes, the pending acks needs to be filled in from the same thread, instead of doing that from the consumer connection thread.

**Comment by merlimat** [comment]
s
