### ISSUE TITLE
Intermittent test failure on PulsarFunctionE2ESecurityTest.testAuthorizationWithAnonymousUser

### ISSUE THREAD

**Issue by merlimat** [apache/pulsar#4355]
https://builds.apache.org/job/pulsar_precommit_java8/9160/testReport/junit/org.apache.pulsar.functions.worker/PulsarFunctionE2ESecurityTest/testAuthorizationWithAnonymousUser/

```
org.apache.pulsar.functions.worker.PulsarFunctionE2ESecurityTest.testAuthorizationWithAnonymousUser

Failing for the past 1 build (Since Failed#9160 )
Took 4.3 sec.
add description
Error Message
expected [0] but found [1]
Stacktrace
java.lang.AssertionError: expected [0] but found [1]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:652)
	at org.testng.Assert.assertEquals(Assert.java:662)
	at org.apache.pulsar.functions.worker.PulsarFunctionE2ESecurityTest.testAuthorizationWithAnonymousUser(PulsarFunctionE2ESecurityTest.java:520)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

cc/ @jerrypeng

**Comment by tisonkun** [comment]
It seems not recent reports. Closed as stale.

Feel free to open a new issue if it's still relevant to the maintained versions.
