### ISSUE TITLE
Broker start error

### ISSUE THREAD

**Issue by guozili520** [apache/pulsar#4394]
When I started the broker,  some error happened. What should I do about this problem？
ERROR org.apache.pulsar.broker.PulsarService - keyCertChain required for servers
java.lang.NullPointerException: keyCertChain required for servers
        at io.netty.util.internal.ObjectUtil.checkNotNull(ObjectUtil.java:33) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:312) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:247) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.handler.ssl.SslContextBuilder.forServer(SslContextBuilder.java:76) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
        at org.apache.pulsar.common.util.SecurityUtility.createNettySslContextForServer(SecurityUtility.java:109) ~[org.apache.pulsar-pulsar-common-2.3.1.jar:2.3.1]
        at org.apache.pulsar.broker.service.PulsarChannelInitializer.<init>

**Comment by joshuayan** [comment]
same issue on 2.3.2

**Comment by sijie** [comment]
@joshuayan @guozili520 can you share more about your configuration? Are you running broker with Tls enabled?

**Comment by sijie** [comment]
Close this issue due to inactivities. Please open a new issue if we need to investigate it.
