### ISSUE TITLE
Intermittent test failure in PeerReplicatorTest.testPeerClusterInReplicationClusterListChange

### ISSUE THREAD

**Issue by merlimat** [apache/pulsar#4397]
```
Regression
org.apache.pulsar.broker.service.PeerReplicatorTest.testPeerClusterInReplicationClusterListChange

Failing for the past 1 build (Since Failed#9321 )
Took 0.38 sec.
Error Message
Namespace already exists
Stacktrace
org.apache.pulsar.client.admin.PulsarAdminException$ConflictException: Namespace already exists
	at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:216)
	at org.apache.pulsar.client.admin.internal.NamespacesImpl.createNamespace(NamespacesImpl.java:176)
	at org.apache.pulsar.broker.service.PeerReplicatorTest.testPeerClusterInReplicationClusterListChange(PeerReplicatorTest.java:198)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.ws.rs.ClientErrorException: HTTP 409 Conflict
	at org.glassfish.jersey.client.JerseyInvocation.createExceptionForFamily(JerseyInvocation.java:1122)
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1105)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:883)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:456)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.put(JerseyInvocation.java:340)
	at org.apache.pulsar.client.admin.internal.NamespacesImpl.createNamespace(NamespacesImpl.java:174)
	... 13 more
```

**Comment by hellozepp** [comment]
I've got the same error.
[https://builds.apache.org/job/pulsar_precommit_java8/9586/testReport/junit/org.apache.pulsar.broker.service/ReplicatorRateLimiterTest/testReplicatorRateLimiterMessageReceivedAllMessages/](url)
`
org.apache.pulsar.client.admin.PulsarAdminException$ConflictException: Namespace already exists
	at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:216)
	at org.apache.pulsar.client.admin.internal.NamespacesImpl.createNamespace(NamespacesImpl.java:176)
	at org.apache.pulsar.broker.service.PeerReplicatorTest.testPeerClusterInReplicationClusterListChange(PeerReplicatorTest.java:198)
`

**Comment by tisonkun** [comment]
Closed as stale.

Feel free to open a new issue if it's still relevant to the maintained versions.
