### ISSUE TITLE
[Schema][AVRO] Unable to encode POJO class with byte[] fields

### ISSUE THREAD

**Issue by yjshen** [apache/pulsar#4489]
**Describe the bug**
When send a POJO with `byte[]` field, `UnresolvedUnionException` is thrown. It's because byte[] array are regarded as `array` in avro, but a `bytes` type in `schemaInfo`.
```
Caused by: org.apache.pulsar.shade.org.apache.avro.UnresolvedUnionException: Not in union ["null",{"type":"bytes","java-class":"[B"}]: [B@294bb6ae
	at org.apache.pulsar.shade.org.apache.avro.generic.GenericData.resolveUnion(GenericData.java:740)
	at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumWriter.resolveUnion(GenericDatumWriter.java:205)
	at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:123)
	at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:75)
	at org.apache.pulsar.shade.org.apache.avro.reflect.ReflectDatumWriter.write(ReflectDatumWriter.java:159)
	at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:166)
	at org.apache.pulsar.shade.org.apache.avro.specific.SpecificDatumWriter.writeField(SpecificDatumWriter.java:90)
	at org.apache.pulsar.shade.org.apache.avro.reflect.ReflectDatumWriter.writeField(ReflectDatumWriter.java:191)
	at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:156)
	at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:118)
	at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:75)
	at org.apache.pulsar.shade.org.apache.avro.reflect.ReflectDatumWriter.write(ReflectDatumWriter.java:159)
	at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:62)
	at org.apache.pulsar.client.impl.schema.writer.AvroWriter.write(AvroWriter.java:44)
```

**To Reproduce**
```java
class Foo {
    private byte[] bs;
    private boolean b;
}
Consumer c = client.newConsumer(Schema.AVRO(Foo.class)).....subscribe();
c.send(new Foo("12".getBytes(), true));
```

**Comment by ambition119** [comment]
Upgrading avro 1.9.0 can solve this issue, such as my PR. But because pulsar has a lot of reliance on avro, whether it needs to be upgraded or not, if everyone agree to upgrade, I can reopen PR.

**Comment by sijie** [comment]
@ambition119 +1 for upgrading to 1.9.0. I think `byte[]` is commonly used for representing `bytes` type.

**Comment by ambition119** [comment]
> @ambition119 +1 for upgrading to 1.9.0. I think `byte[]` is commonly used for representing `bytes` type.

Because avro is just released 1.9.0, many still use 1.8.2, such as `flink-avro`. If we upgrade, pulsar will have some changes, such as` org.joda.time.DateTime`.

**Comment by prakashsaraf7** [comment]
I have encountered same issue, any plans of upgrading Avro in release 2.4.0? Or any ETA?

**Comment by sijie** [comment]
@prakashsaraf7 2.4.0 is under releasing. so we probably don't want to change the avro version for 2.4.0. we will do it for the master, which can go with 2.5.0 and 2.4.1 (if needed).

**Comment by tisonkun** [comment]
Closed as stale and no one showed interest any longer. Please open a new issue if it's still relevant to the maintained versions.
