### ISSUE TITLE
Error open RocksDB database : Compression type LZ4 is not linked with the binary

### ISSUE THREAD

**Issue by GoX1337** [apache/pulsar#4684]
- Windows 10
- fresh repo clone
- mvn install

Tried to start pulsar, launching the script :
- bin/pulsar standalone

I got the following error :

```
21:35:04.476 [main] ERROR org.apache.bookkeeper.bookie.Journal - Problems reading from data\standalone\bookkeeper0\current\lastMark (this is okay if it is the first time starting this bookie
21:35:04.859 [main] ERROR org.apache.pulsar.PulsarStandaloneStarter - Failed to start pulsar service.
java.io.IOException: Error open RocksDB database
	at org.apache.bookkeeper.bookie.storage.ldb.KeyValueStorageRocksDB.<init>(KeyValueStorageRocksDB.java:182) ~[bookkeeper-server-4.9.2.jar:4.9.2]
	at org.apache.bookkeeper.bookie.storage.ldb.KeyValueStorageRocksDB.<init>(KeyValueStorageRocksDB.java:83) ~[bookkeeper-server-4.9.2.jar:4.9.2]
	at org.apache.bookkeeper.bookie.storage.ldb.KeyValueStorageRocksDB.lambda$static$0(KeyValueStorageRocksDB.java:58) ~[bookkeeper-server-4.9.2.jar:4.9.2]
	at org.apache.bookkeeper.bookie.storage.ldb.EntryLocationIndex.<init>(EntryLocationIndex.java:58) ~[bookkeeper-server-4.9.2.jar:4.9.2]
	at org.apache.bookkeeper.bookie.storage.ldb.SingleDirectoryDbLedgerStorage.<init>(SingleDirectoryDbLedgerStorage.java:161) ~[bookkeeper-server-4.9.2.jar:4.9.2]
	at org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorage.newSingleDirectoryDbLedgerStorage(DbLedgerStorage.java:148) ~[bookkeeper-server-4.9.2.jar:4.9.2]
	at org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorage.initialize(DbLedgerStorage.java:128) ~[bookkeeper-server-4.9.2.jar:4.9.2]
	at org.apache.bookkeeper.bookie.Bookie.<init>(Bookie.java:790) ~[bookkeeper-server-4.9.2.jar:4.9.2]
	at org.apache.bookkeeper.proto.BookieServer.newBookie(BookieServer.java:137) ~[bookkeeper-server-4.9.2.jar:4.9.2]
	at org.apache.bookkeeper.proto.BookieServer.<init>(BookieServer.java:106) ~[bookkeeper-server-4.9.2.jar:4.9.2]
	at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.runBookies(LocalBookkeeperEnsemble.java:272) ~[classes/:?]
	at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.startStandalone(LocalBookkeeperEnsemble.java:396) ~[classes/:?]
	at org.apache.pulsar.PulsarStandalone.start(PulsarStandalone.java:259) ~[classes/:?]
	at org.apache.pulsar.PulsarStandaloneStarter.main(PulsarStandaloneStarter.java:121) [classes/:?]
Caused by: org.rocksdb.RocksDBException: Compression type LZ4 is not linked with the binary.
	at org.rocksdb.RocksDB.open(Native Method) ~[rocksdbjni-5.13.3.jar:?]
	at org.rocksdb.RocksDB.open(RocksDB.java:231) ~[rocksdbjni-5.13.3.jar:?]
	at org.apache.bookkeeper.bookie.storage.ldb.KeyValueStorageRocksDB.<init>(KeyValueStorageRocksDB.java:179) ~[bookkeeper-server-4.9.2.jar:4.9.2]
	... 13 more
21:35:04.865 [Thread-1] ERROR org.apache.pulsar.PulsarStandaloneStarter - Shutdown failed: null

```

Can you help me ?

Thank you in advance.

**Comment by sijie** [comment]
@GoX1337 Currently I don't think Pulsar support running on Windows very well. Because there are a few dependencies are using native code. The bindings we are shipping probably doesn't contain the native libraries built for windows.

**Comment by GoX1337** [comment]
Ok thanks. 

I will try to start it on my Ubuntu laptop.
