### ISSUE TITLE
function apply protobuf input.

### ISSUE THREAD

**Issue by YangZunYu** [apache/pulsar#4742]
Hello. I'm testing pulsar function for easy ETL job recently, but i encountered some errors that i couldn't figure it out.  there is my snippet.
![image](https://user-images.githubusercontent.com/13885249/61344372-9d9cec80-a883-11e9-909a-e096e6c55210.png)

and producer is:
![image](https://user-images.githubusercontent.com/13885249/61344415-c1603280-a883-11e9-933a-fbf223470c3f.png)

#### Expected behavior
I assumed that localrunner could established a function process the deserialized messages with schema from schema registry, then produce to target topic.

#### Actual behavior
![image](https://user-images.githubusercontent.com/13885249/61344831-4ef05200-a885-11e9-8baf-4fece09c2aa8.png)
```log
[ERROR] 2019-07-17 11:19:20.175 [public/default/Addressbook-0] JavaInstanceRunnable - [public/default/Addressbook:0] Uncaught exception in Java Instance
java.lang.UnsupportedOperationException: null
	at java.util.AbstractMap.put(AbstractMap.java:209) ~[?:1.8.0_201]
	at org.apache.pulsar.client.impl.schema.SchemaDefinitionBuilderImpl.build(SchemaDefinitionBuilderImpl.java:101) ~[pulsar-client-2.4.0.jar:2.4.0]
	at org.apache.pulsar.client.impl.schema.ProtobufSchema.ofGenericClass(ProtobufSchema.java:106) ~[pulsar-client-2.4.0.jar:2.4.0]
	at org.apache.pulsar.functions.source.TopicSchema.newSchemaInstance(TopicSchema.java:149) ~[pulsar-functions-local-runner-2.4.0.jar:2.4.0]
	at org.apache.pulsar.functions.source.TopicSchema.newSchemaInstance(TopicSchema.java:173) ~[pulsar-functions-local-runner-2.4.0.jar:2.4.0]
	at org.apache.pulsar.functions.source.TopicSchema.lambda$getSchema$0(TopicSchema.java:66) ~[pulsar-functions-local-runner-2.4.0.jar:2.4.0]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127) ~[?:1.8.0_201]
```
Could anyone telling what to do, cause I could not find any document or example showing how it work.

#### System configuration
**Pulsar version**: 2.4

**Comment by jerrypeng** [comment]
@YangZunYu I think there is a bug.  Its a simple fix. It involves this line of code:

https://github.com/apache/pulsar/blob/master/pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/source/TopicSchema.java#L149

**Comment by YangZunYu** [comment]
OK. Thanks for your reply. :)

**Comment by sijie** [comment]
@YangZunYu are you interested in contributing a fix for it?

**Comment by jiazhai** [comment]
@YangZunYu @sijie  How about move this into 2.5.0?

**Comment by sijie** [comment]
This has been fixed in the latest master.
