### ISSUE TITLE
NPE is thrown when a consumer consumes a partitioned topic with struct schema

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#4838]
**Describe the bug**

NPE is thrown when a consumer consumes a partitioned topic (which doesn't have any registered schema) with struct schema.

```
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at org.apache.pulsar.client.impl.ConsumerBuilderImpl.subscribe(ConsumerBuilderImpl.java:89)
	... 29 more
Caused by: java.lang.NullPointerException
	at org.apache.pulsar.client.impl.PulsarClientImpl.preProcessSchemaBeforeSubscribe(PulsarClientImpl.java:749)
	at org.apache.pulsar.client.impl.PulsarClientImpl.singleTopicSubscribeAsync(PulsarClientImpl.java:332)
	at org.apache.pulsar.client.impl.PulsarClientImpl.subscribeAsync(PulsarClientImpl.java:324)
	at org.apache.pulsar.client.impl.ConsumerBuilderImpl.subscribeAsync(ConsumerBuilderImpl.java:107)
	... 30 more
```

**Comment by codelipenghui** [comment]
@congbobo184 please take a look this issue.

**Comment by congbobo184** [comment]
what are the steps for the recurrence of this problem and 
```
./pulsar-admin topics create-partitioned-topic -p 3 persistent://public/default/test-npe3

 PulsarClient client = PulsarClient.builder().serviceUrl("pulsar://127.0.0.1:6650").build();
        Consumer<MessageProcess> consumer = client
                .newConsumer(Schema.AVRO(MessageProcess.class))
                .topic("persistent://public/default/test-npe3")
                .subscriptionName("test")
                .subscribe();
        while (true) {
            Message<MessageProcess> message = consumer.receive();
            consumer.acknowledge(message);

        }
```
I did not reproduce it in this way.

**Comment by sijie** [comment]
@congbobo184 I think I made a mistake in the description I provided. The exception was thrown when I use AUTO_CONSUME schema.

**Comment by congbobo184** [comment]
OK, I will reproduce this and fix the bug
