### ISSUE TITLE
The frist position in managedLedger is ahead of the last

### ISSUE THREAD

**Issue by fxbing** [apache/pulsar#4852]
**Describe the bug**
After create a empty ledger by sub/unsub and trim ledgers, the frist position in managedLedger is ahead of the last when create a consumer and don't reopen the managed ledger.

**To Reproduce**
run test and set the retention policy to 0.

**Expected behavior**

no bug and "all message" output none.

**Screenshots**

```bash
16:05:50.795 [pulsar-io-50-2] INFO  org.apache.pulsar.broker.service.ServerCnx - [/127.0.0.1:45808] Subscribing on topic persistent://public/default/my-topic / my-sub
16:05:50.796 [pulsar-io-50-2] WARN  org.apache.bookkeeper.mledger.impl.ManagedCursorImpl - [public/default/persistent/my-topic] [my-sub] Current position 15:-1 is ahead of last position 13:0
16:05:50.797 [pulsar-io-50-2] INFO  org.apache.bookkeeper.mledger.impl.ManagedCursorImpl - [public/default/persistent/my-topic] Cursor my-sub recovered to position 13:0
16:05:50.797 [pulsar-io-50-2] WARN  org.apache.bookkeeper.client.BookieWatcherImpl - New ensemble: [127.0.0.1:3181] is not adhering to Placement Policy. quarantinedBookies: []
16:05:50.801 [pulsar-ordered-OrderedExecutor-6-0-EventThread] INFO  org.apache.bookkeeper.client.LedgerCreateOp - Ensemble: [127.0.0.1:3181] for ledger: 17
16:05:50.804 [BookKeeperClientWorker-OrderedExecutor-1-0] INFO  org.apache.bookkeeper.mledger.impl.MetaStoreImplZookeeper - [public/default/persistent/my-topic] [my-sub] Updating cursor info ledgerId=17 mark-delete=13:0
16:05:50.806 [bookkeeper-ml-workers-OrderedExecutor-2-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedCursorImpl - [public/default/persistent/my-topic] Updated cursor my-sub with ledger id 17 md-position=13:0 rd-position=13:1
16:05:50.806 [bookkeeper-ml-workers-OrderedExecutor-2-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [public/default/persistent/my-topic] Opened new cursor: ManagedCursorImpl{ledger=public/default/persistent/my-topic, name=my-sub, ackPos=13:0, readPos=13:1}
16:05:50.806 [bookkeeper-ml-workers-OrderedExecutor-2-0] ERROR org.apache.bookkeeper.common.util.SafeRunnable - Unexpected throwable caught 
java.lang.IllegalArgumentException: Invalid range: (15:-1..13:0]
	at com.google.common.collect.Range.<init>(Range.java:352) ~[guava-21.0.jar:?]
	at com.google.common.collect.Range.create(Range.java:146) ~[guava-21.0.jar:?]
	at com.google.common.collect.Range.openClosed(Range.java:194) ~[guava-21.0.jar:?]
	at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.getFirstPositionAndCounter(ManagedLedgerImpl.java:2809) ~[managed-ledger-original.jar:2.5.0-SNAPSHOT]
	at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl$6.operationComplete(ManagedLedgerImpl.java:722) ~[managed-ledger-original.jar:2.5.0-SNAPSHOT]
	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl$2.operationComplete(ManagedCursorImpl.java:420) ~[managed-ledger-original.jar:2.5.0-SNAPSHOT]
	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl$25$1.operationComplete(ManagedCursorImpl.java:2137) ~[managed-ledger-original.jar:2.5.0-SNAPSHOT]
	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl$27.operationComplete(ManagedCursorImpl.java:2306) ~[managed-ledger-original.jar:2.5.0-SNAPSHOT]
	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl$27.operationComplete(ManagedCursorImpl.java:2296) ~[managed-ledger-original.jar:2.5.0-SNAPSHOT]
	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl$23.operationComplete(ManagedCursorImpl.java:2009) ~[managed-ledger-original.jar:2.5.0-SNAPSHOT]
	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl$23.operationComplete(ManagedCursorImpl.java:2005) ~[managed-ledger-original.jar:2.5.0-SNAPSHOT]
	at org.apache.bookkeeper.mledger.impl.MetaStoreImplZookeeper.lambda$null$9(MetaStoreImplZookeeper.java:277) ~[managed-ledger-ono bug and "all messages" output none.riginal.jar:2.5.0-SNAPSHOT]
	at org.apache.bookkeeper.mledger.util.SafeRun$1.safeRun(SafeRun.java:32) ~[managed-ledger-original.jar:2.5.0-SNAPSHOT]
	at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [bookkeeper-common-4.9.2.jar:4.9.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.32.Final.jar:4.1.32.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Desktop (please complete the following information):**

 - pulsar-2.4.0/master

**Additional context**

```java
public class BugTest {
    static void consume(String topicName, String subName) throws Exception {
        try (
                PulsarClient client = PulsarClient.builder()
                        .serviceUrl("pulsar://localhost:6650")
                        .build();
                Consumer<byte[]> consumer = client.newConsumer()
                        .topic("persistent://public/default/" + topicName)
                        .subscriptionInitialPosition(SubscriptionInitialPosition.Earliest)
                        .subscriptionType(SubscriptionType.Exclusive)
                        .subscriptionName(subName)
                        .subscribe()) {

            Message<byte[]> msg = consumer.receive(10, TimeUnit.SECONDS);
            while (msg != null) {
                System.out.println("receive message,  value: " + new String(msg.getValue()));
                consumer.acknowledge(msg);
                msg = consumer.receive(10, TimeUnit.SECONDS);
            }
            consumer.unsubscribe();
        }
    }

    static void produceAndConsumeMessage(String topicName, String message, String subName) throws Exception {
        try (PulsarClient client = PulsarClient.builder()
                .serviceUrl("pulsar://localhost:6650")
                .build()) {
            try (Producer<String> producer = client.newProducer(Schema.STRING)
                    .topic("persistent://public/default/" + topicName)
                    .enableBatching(false)
                    .create();
                 Consumer<String> consumer = client.newConsumer(Schema.STRING)
                         .topic("persistent://public/default/" + topicName)
                         .subscriptionType(SubscriptionType.Exclusive)
                         .subscriptionName(subName)
                         .subscribe()) {
                producer.newMessage()
                        .value(message)
                        .send();
                producer.flush();
                System.out.println("produce message: " + message);

                Message<String> msg = consumer.receive();
                consumer.acknowledge(msg);
                consumer.unsubscribe();
                System.out.println("consume and ack message : " + msg.getValue());
            }
        }
        try (PulsarAdmin admin = PulsarAdmin.builder()
                .serviceHttpUrl("http://localhost:8080")
                .build()) {
            admin.topics().unload("persistent://public/default/" + topicName);
        }
    }

    static void test(String topicName, int n, String subName) throws Exception {
        try (PulsarAdmin admin = PulsarAdmin.builder()
                .serviceHttpUrl("http://localhost:8080")
                .build()) {
            admin.namespaces().setRetention("public/default", new RetentionPolicies(0, 0));
        }
        int i = 0;
        while (i++ < n) {
            System.out.println(new Date().toString());
            produceAndConsumeMessage(topicName, "value-" + i, subName);
            Thread.sleep(1000 * 60);
        }
        // sub and unSub to trigger trim ledgers
        try (
                PulsarClient client = PulsarClient.builder()
                        .serviceUrl("pulsar://localhost:6650")
                        .build();
                Consumer<String> consumer = client.newConsumer(Schema.STRING)
                        .topic("persistent://public/default/" + topicName)
                        .subscriptionType(SubscriptionType.Exclusive)
                        .subscriptionName(subName)
                        .subscribe()) {
            consumer.unsubscribe();
        }
        // The bug disappears after enabling the code below

//        try (PulsarAdmin admin = PulsarAdmin.builder()
//                .serviceHttpUrl("http://localhost:8080")
//                .build()) {
//            admin.topics().unload("persistent://public/default/" + topicName);
//        }
        System.out.println("-------------------------------------");
        System.out.println("all messages :");
        consume(topicName, subName);
        System.out.println("-------------------------------------");
    }

    public static void main(String[] args) {
        try {
            test("my-topic", 3, "my-sub");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

**Comment by fxbing** [comment]
fixed in #4853
