### ISSUE TITLE
pulsar-functions-local-runner(v2.4.0)

### ISSUE THREAD

**Issue by cumtwwei** [apache/pulsar#4864]
I use pulsar-2.4.0, and try to debug functions in localrun mode with 'pulsar-functions-local-runner'.

My code is just like: [https://github.com/jerrypeng/pulsar-functions-demos/tree/master/debugging](url)
But when I run my code , it got errors like bellow:

_[ERROR] 2019-08-01 14:29:33.107 [public/default/exclamation-0] JavaInstanceRunnable - [public/default/exclamation:0] Uncaught exception in Java Instance
java.util.concurrent.CompletionException: org.apache.pulsar.client.api.PulsarClientException$IncompatibleSchemaException: Trying to subscribe with incompatible schema
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_161]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_161]
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:700) ~[?:1.8.0_161]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire$$$capture(CompletableFuture.java:687) ~[?:1.8.0_161]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java) ~[?:1.8.0_161]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_161]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[?:1.8.0_161]
	at org.apache.pulsar.client.impl.ClientCnx.handleError(ClientCnx.java:597) ~[pulsar-functions-local-runner-2.4.0.jar:2.4.0]
	at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:154) ~[pulsar-functions-local-runner-2.4.0.jar:2.4.0]_

I alse see a issue at [https://github.com/apache/pulsar/issues/4857](url), and I set my pulsar-2.4.0 with Sijie's suggestion, but the error also came.
Finally,  I chang my pulsar's version to 2.3.1, use the same code, but it's all right, no error come.
So, I think is it a bug in pulsar-2.4.0?
Thanks a lot.

**Comment by sijie** [comment]
@cumtwwei you mean precreating the topic with `String` schema?

**Comment by cumtwwei** [comment]
the topic that just created by pulsar auto, and i use this command: `bin/pulsar-admin namespaces set-schema-autoupdate-strategy -d public/default.` Then the error come again.
but not try to precreate the topic with `String` schema. i will try to do it.

**Comment by cumtwwei** [comment]
@sijie 
after i recreate my topic with Schema.STRING, it's all right.
Thanks a lot.
