### ISSUE TITLE
PulsarBrokerStatsClientTest.testTopicInternalStats is flaky

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#4895]
```
Error Message
expected [true] but found [false]
Stacktrace
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at org.apache.pulsar.stats.client.PulsarBrokerStatsClientTest.testTopicInternalStats(PulsarBrokerStatsClientTest.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by fxbing** [comment]
Fixed in #5040

`individualDeletedMessages` is an instance of `ConcurrentOpenLongPairRangeSet` in `ManagedCursorImpl`.
In `CursorStats`,  the value of `totalNonContiguousDeletedMessagesRange`  is `individualDeletedMessages.size()`, and the value of `individuallyDeletedMessages` is `individualDeletedMessages.toString()`.
But in `ConcurrentOpenLongPairRangeSet`, `size()` and `toString()` use the same cache flag.
After using one of `size()` and `toString()`, another can't get the correct result.
