### ISSUE TITLE
[Java8 Tests Error] BrokerClientIntegrationTest.testResetCursor() didn't finish within the time-out 10000

### ISSUE THREAD

**Issue by wolfstudy** [apache/pulsar#4902]
**Describe the bug**

The Java8 test case of Jenkins fail.

```
org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.client.impl.BrokerClientIntegrationTest.testResetCursor() didn't finish within the time-out 10000
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Expected behavior**

Java8 tests case success.

**Comment by sijie** [comment]
Close this issue since it was created a year ago.
