### ISSUE TITLE
Broker unable to restart

### ISSUE THREAD

**Issue by mingfang** [apache/pulsar#4964]
I have a working Broker cluster with 3 replicas.
When I bounce any of the replicas, then they fail to start.
Here is the error 
```
16:17:50.180 [main INFO  org.apache.pulsar.broker.PulsarService - Starting name space service, bootstrap namespaces=
16:17:50.204 [main ERROR org.apache.pulsar.broker.namespace.NamespaceService - null
java.lang.NullPointerException: null
    at org.apache.pulsar.broker.namespace.ServiceUnitZkUtils.cleanupSingleNamespaceNode(ServiceUnitZkUtils.java:156) ~[org.apache.pulsar-pulsar-broker-2.4.0.jar:2.4.0
    at org.apache.pulsar.broker.namespace.ServiceUnitZkUtils.cleanupNamespaceNodes(ServiceUnitZkUtils.java:134) ~[org.apache.pulsar-pulsar-broker-2.4.0.jar:2.4.0
    at org.apache.pulsar.broker.namespace.ServiceUnitZkUtils.cleanupNamespaceNodes(ServiceUnitZkUtils.java:137) ~[org.apache.pulsar-pulsar-broker-2.4.0.jar:2.4.0
    at org.apache.pulsar.broker.namespace.ServiceUnitZkUtils.initZK(ServiceUnitZkUtils.java:113) ~[org.apache.pulsar-pulsar-broker-2.4.0.jar:2.4.0
    at org.apache.pulsar.broker.namespace.NamespaceService.<init>(NamespaceService.java:151) ~[org.apache.pulsar-pulsar-broker-2.4.0.jar:2.4.0
    at org.apache.pulsar.broker.PulsarService.lambda$getNamespaceServiceProvider$1(PulsarService.java:584) ~[org.apache.pulsar-pulsar-broker-2.4.0.jar:2.4.0
    at org.apache.pulsar.broker.PulsarService.startNamespaceService(PulsarService.java:580) [org.apache.pulsar-pulsar-broker-2.4.0.jar:2.4.0
    at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:375) [org.apache.pulsar-pulsar-broker-2.4.0.jar:2.4.0
    at org.apache.pulsar.PulsarBrokerStarter$BrokerStarter.start(PulsarBrokerStarter.java:273) [org.apache.pulsar-pulsar-broker-2.4.0.jar:2.4.0
    at org.apache.pulsar.PulsarBrokerStarter.main(PulsarBrokerStarter.java:332) [org.apache.pulsar-pulsar-broker-2.4.0.jar:2.4.0
16:17:50.208 [main ERROR org.apache.pulsar.broker.PulsarService - java.lang.NullPointerException
java.lang.RuntimeException: java.lang.NullPointerException
    at org.apache.pulsar.broker.namespace.ServiceUnitZkUtils.initZK(ServiceUnitZkUtils.java:116) ~[org.apache.pulsar-pulsar-broker-2.4.0.jar:2.4.0
    at org.apache.pulsar.broker.namespace.NamespaceService.<init>(NamespaceService.java:151) ~[org.apache.pulsar-pulsar-broker-2.4.0.jar:2.4.0
    at org.apache.pulsar.broker.PulsarService.lambda$getNamespaceServiceProvider$1(PulsarService.java:584) ~[org.apache.pulsar-pulsar-broker-2.4.0.jar:2.4.0
    at org.apache.pulsar.broker.PulsarService.startNamespaceService(PulsarService.java:580) ~[org.apache.pulsar-pulsar-broker-2.4.0.jar:2.4.0
    at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:375) [org.apache.pulsar-pulsar-broker-2.4.0.jar:2.4.0
    at org.apache.pulsar.PulsarBrokerStarter$BrokerStarter.start(PulsarBrokerStarter.java:273) [org.apache.pulsar-pulsar-broker-2.4.0.jar:2.4.0
    at org.apache.pulsar.PulsarBrokerStarter.main(PulsarBrokerStarter.java:332) [org.apache.pulsar-pulsar-broker-2.4.0.jar:2.4.0
Caused by: java.lang.NullPointerException
    at org.apache.pulsar.broker.namespace.ServiceUnitZkUtils.cleanupSingleNamespaceNode(ServiceUnitZkUtils.java:156) ~[org.apache.pulsar-pulsar-broker-2.4.0.jar:2.4.0
    at org.apache.pulsar.broker.namespace.ServiceUnitZkUtils.cleanupNamespaceNodes(ServiceUnitZkUtils.java:134) ~[org.apache.pulsar-pulsar-broker-2.4.0.jar:2.4.0
    at org.apache.pulsar.broker.namespace.ServiceUnitZkUtils.cleanupNamespaceNodes(ServiceUnitZkUtils.java:137) ~[org.apache.pulsar-pulsar-broker-2.4.0.jar:2.4.0
    at org.apache.pulsar.broker.namespace.ServiceUnitZkUtils.initZK(ServiceUnitZkUtils.java:113) ~[org.apache.pulsar-pulsar-broker-2.4.0.jar:2.4.0
    ... 6 more
16:17:50.209 [main ERROR org.apache.pulsar.PulsarBrokerStarter - Failed to start pulsar service.
```

**Comment by rdhabalia** [comment]
can you try with this fix #4965

**Comment by mingfang** [comment]
Is there CI/CD to push daily builds to Docker Hub?
Or do I have to build my own image?

**Comment by sijie** [comment]
@mingfang Have you fixed if a newer version of Pulsar has already fixed your issue?

**Comment by mingfang** [comment]
I just upgrade to v2.6.1 and this is no longer a problem. Thanks
