### ISSUE TITLE
"Connection is already closed" when creating a Producer

### ISSUE THREAD

**Issue by Muyoo** [apache/pulsar#5065]
After I set up a Pulsar in standalone on MacOS, I get an exception `Connection is already closed` when I create a Producer: 
```
15:53:56.739 [pulsar-client-io-1-1] INFO org.apache.pulsar.client.impl.ClientCnx - [id: 0x3fab3a4b, L:/127.0.0.1:60316 ! R:/127.0.0.1:6650] Disconnected
15:53:56.742 [pulsar-client-io-1-1] WARN org.apache.pulsar.client.impl.ConnectionPool - [[id: 0x3fab3a4b, L:/127.0.0.1:60316 ! R:/127.0.0.1:6650]] Connection handshake failed: org.apache.pulsar.client.api.PulsarClientException: Connection already closed
15:53:56.742 [pulsar-client-io-1-1] WARN org.apache.pulsar.client.impl.PulsarClientImpl - [persistent://public/default/wyq-test] Failed to get partitioned topic metadata: org.apache.pulsar.client.api.PulsarClientException: Connection already closed
Exception in thread "main" org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException: Connection already closed
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:297)
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:88)
	at org.xmuyoo.blueberry.crawling.streams.Publisher.main(Publisher.java:108)
Caused by: java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException: Connection already closed
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:86)
	... 1 more
Caused by: org.apache.pulsar.client.api.PulsarClientException: Connection already closed
	at org.apache.pulsar.client.impl.ClientCnx.channelInactive(ClientCnx.java:220)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at org.apache.pulsar.shade.io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:390)
	at org.apache.pulsar.shade.io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:355)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at org.apache.pulsar.shade.io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at org.apache.pulsar.shade.io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:826)
	at org.apache.pulsar.shade.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:474)
	at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
	at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

And I run Pulsar in Docker(18.09.2) with the command in the document:
```
$ docker run -it \
  -p 6650:6650 \
  -p 8080:8080 \
  -v $PWD/data:/pulsar/data \
  apachepulsar/pulsar:2.4.0 \
  bin/pulsar standalone
```
There is no ERROR in the log messages.

And my code is here:
```Java
public static void main(String[] args) throws Exception {
    PulsarClient client = PulsarClient.builder()
            .serviceUrl("pulsar://127.0.0.1:6650")
            .build();
    Producer<SeriesData> producer = client.newProducer(Schema.AVRO(SeriesData.class))
            .producerName("publisher-" + SeriesData.class.getSimpleName())
            .topic("persistent://public/default/wyq-test")
            .sendTimeout(10, TimeUnit.SECONDS)
            .blockIfQueueFull(true)
            .enableBatching(true)
            .batchingMaxPublishDelay(100, TimeUnit.MILLISECONDS)
            .create();

    producer.close();
    client.close();
```

I've tried to start Pulsar without Docker and it works.  But I want to set up it with Docker.

How do I solve this please?
Thanks!

**Comment by Muyoo** [comment]
Ok. I've just upgraded my Docket Desktop version to 19.03.1 and it works then.

**Comment by Muyoo** [comment]
What make me confused is that I've never met the same problem when I used other middlewares like PostgreSQL, Kafka, HBase and so on with Docker 18.09.2.

**Comment by sijie** [comment]
@Muyoo connection already closed doesn't mean your docker has any problem. It just means at the time you created producer, the connection from your cllient to broker is already closed. I don't believe it is related to docker version.
