### ISSUE TITLE
PulsarClientException NO SHUCH METHOD ERROR

### ISSUE THREAD

**Issue by otmanel31** [apache/pulsar#5081]
**Describe the bug**
Hi, i'm trying to send data to pulsar broker via Apache Nifi flow. I'm able to get connection to pulsar but when i tried to send my data i get an exception that is may be a dependency issue ...
The pulsar client generate this error and more precisly that happen when producer class is called and the not found method is com.scurrilous.circe.checksum.Crc32cIntChecksum.computeChecksum.
Any hint, suggestion ? or a dependency exclusion needed ? 

**To Reproduce**
use nifi 1.9 version
make a flow that connect to pulsar broker. I'm using this [nifi pulsar processor](https://github.com/streamlio/nifi-pulsar-bundle) that use the pulsar client api.
When the flow is configured, and a data is coming and when we try to send it, an exception is thrown:
Following exception is:

> 2019-08-29 09:15:26,749 ERROR [Timer-Driven Process Thread-5] o.a.n.p.pulsar.pubsub.PublishPulsar PublishPulsar[id=de260534-016c-1000-5f3d-db6103ca25d8] Unable to publish message to Pulsar broker pulsar://localhost:6650: org.apache.pulsar.client.api.PulsarClientException: java.lang.NoSuchMethodError: com.scurrilous.circe.checksum.Crc32cIntChecksum.computeChecksum(Lorg/apache/pulsar/shade/io/netty/buffer/ByteBuf;)I
org.apache.pulsar.client.api.PulsarClientException: java.lang.NoSuchMethodError: com.scurrilous.circe.checksum.Crc32cIntChecksum.computeChecksum(Lorg/apache/pulsar/shade/io/netty/buffer/ByteBuf;)I
	at org.apache.pulsar.client.impl.ProducerImpl.sendAsync(ProducerImpl.java:413)
	at org.apache.pulsar.client.impl.ProducerImpl.internalSendAsync(ProducerImpl.java:215)
	at org.apache.pulsar.client.impl.ProducerBase.send(ProducerBase.java:78)
	at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.send(TypedMessageBuilderImpl.java:55)
	at org.apache.pulsar.client.impl.ProducerBase.send(ProducerBase.java:52)
	at org.apache.nifi.processors.pulsar.pubsub.PublishPulsar.send(PublishPulsar.java:115)
	at org.apache.nifi.processors.pulsar.pubsub.PublishPulsar.onTrigger(PublishPulsar.java:83)
	at org.apache.nifi.processor.AbstractProcessor.onTrigger(AbstractProcessor.java:27)
	at org.apache.nifi.controller.StandardProcessorNode.onTrigger(StandardProcessorNode.java:1162)
	at org.apache.nifi.controller.tasks.ConnectableTask.invoke(ConnectableTask.java:205)
	at org.apache.nifi.controller.scheduling.TimerDrivenSchedulingAgent$1.run(TimerDrivenSchedulingAgent.java:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: com.scurrilous.circe.checksum.Crc32cIntChecksum.computeChecksum(Lorg/apache/pulsar/shade/io/netty/buffer/ByteBuf;)I
	at org.apache.pulsar.common.api.Commands.serializeCommandSendWithSize(Commands.java:948)
	at org.apache.pulsar.common.api.Commands.newSend(Commands.java:315)
	at org.apache.pulsar.client.impl.ProducerImpl.sendMessage(ProducerImpl.java:449)
	at org.apache.pulsar.client.impl.ProducerImpl.sendAsync(ProducerImpl.java:376)
	... 17 common frames omitted

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: linux ubuntu 18.04

**Additional context**
I'm working in nifi context

Below more logs before the exception was thrown:

> 2019-08-29 09:15:10,972 INFO [Timer-Driven Process Thread-1] o.a.nifi.amqp.processors.AMQPConsumer Successfully connected AMQPConsumer to amqp://admin_rabbit@127.0.0.1:5672/ and 'test_queue' queue
2019-08-29 09:15:24,747 INFO [pulsar-client-io-1-1] o.a.pulsar.client.impl.ConnectionPool [[id: 0x567a352e, L:/127.0.0.1:58138 - R:localhost/127.0.0.1:6650]] Connected to server
2019-08-29 09:15:26,485 INFO [pulsar-client-io-1-1] o.a.p.c.impl.ProducerStatsRecorderImpl Starting Pulsar producer perf with config: {
  "topicName" : "testOtman",
  "producerName" : null,
  "sendTimeoutMs" : 30000,
  "blockIfQueueFull" : false,
  "maxPendingMessages" : 1000,
  "maxPendingMessagesAcrossPartitions" : 50000,
  "messageRoutingMode" : "RoundRobinPartition",
  "hashingScheme" : "JavaStringHash",
  "cryptoFailureAction" : "FAIL",
  "batchingMaxPublishDelayMicros" : 10000,
  "batchingMaxMessages" : 1000,
  "batchingEnabled" : false,
  "compressionType" : "NONE",
  "initialSequenceId" : null,
  "autoUpdatePartitions" : true,
  "properties" : { }
}
2019-08-29 09:15:26,502 INFO [pulsar-client-io-1-1] o.a.p.c.impl.ProducerStatsRecorderImpl Pulsar client config: {
  "serviceUrl" : "pulsar://localhost:6650",
  "operationTimeoutMs" : 30000,
  "statsIntervalSeconds" : 60,
  "numIoThreads" : 1,
  "numListenerThreads" : 1,
  "connectionsPerBroker" : 1,
  "useTcpNoDelay" : false,
  "useTls" : false,
  "tlsTrustCertsFilePath" : "",
  "tlsAllowInsecureConnection" : false,
  "tlsHostnameVerificationEnable" : false,
  "concurrentLookupRequest" : 5000,
  "maxLookupRequest" : 50000,
  "maxNumberOfRejectedRequestPerConnection" : 50,
  "keepAliveIntervalSeconds" : 30,
  "connectionTimeoutMs" : 10000
}
2019-08-29 09:15:26,587 INFO [pulsar-client-io-1-1] o.a.pulsar.client.impl.ConnectionPool [[id: 0x9f4e2038, L:/127.0.0.1:58140 - R:localhost/127.0.0.1:6650]] Connected to server
2019-08-29 09:15:26,590 INFO [pulsar-client-io-1-1] org.apache.pulsar.client.impl.ClientCnx [id: 0x9f4e2038, L:/127.0.0.1:58140 - R:localhost/127.0.0.1:6650] Connected through proxy to target broker at allinone:6650
2019-08-29 09:15:26,627 INFO [pulsar-client-io-1-1] o.apache.pulsar.client.impl.ProducerImpl [testOtman] [null] Creating producer on cnx [id: 0x9f4e2038, L:/127.0.0.1:58140 - R:localhost/127.0.0.1:6650]
2019-08-29 09:15:26,664 INFO [pulsar-client-io-1-1] o.apache.pulsar.client.impl.ProducerImpl [testOtman] [standalone-7-725] Created producer on cnx [id: 0x9f4e2038, L:/127.0.0.1:58140 - R:localhost/127.0.0.1:6650]
2019-08-29 09:15:26,749 ERROR [Timer-Driven Process Thread-5] o.a.n.p.pulsar.pubsub.PublishPulsar PublishPulsar[id=de260534-016c-1000-5f3d-db6103ca25d8] Unable to publish message to Pulsar broker pulsar://localhost:6650: org.apache.pulsar.client.api.PulsarClientException: java.lang.NoSuchMethodError: com.scurrilous.circe.checksum.Crc32cIntChecksum.computeChecksum(Lorg/apache/pulsar/shade/io/netty/buffer/ByteBuf;)I
org.apache.pulsar.client.api.PulsarClientException: java.lang.NoSuchMethodError: com.scurrilous.circe.checksum.Crc32cIntChecksum.computeChecksum(Lorg/apache/pulsar/shade/io/netty/buffer/ByteBuf;)I
	at org.apache.pulsar.client.impl.ProducerImpl.sendAsync(ProducerImpl.java:413)
	at org.apache.pulsar.client.impl.ProducerImpl.internalSendAsync(ProducerImpl.java:215)
	at org.apache.pulsar.client.impl.ProducerBase.send(ProducerBase.java:78)
	at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.send(TypedMessageBuilderImpl.java:55)
	at org.apache.pulsar.client.impl.ProducerBase.send(ProducerBase.java:52)
	at org.apache.nifi.processors.pulsar.pubsub.PublishPulsar.send(PublishPulsar.java:115)
	at org.apache.nifi.processors.pulsar.pubsub.PublishPulsar.onTrigger(PublishPulsar.java:83)
	at org.apache.nifi.processor.AbstractProcessor.onTrigger(AbstractProcessor.java:27)
	at org.apache.nifi.controller.StandardProcessorNode.onTrigger(StandardProcessorNode.java:1162)
	at org.apache.nifi.controller.tasks.ConnectableTask.invoke(ConnectableTask.java:205)
	at org.apache.nifi.controller.scheduling.TimerDrivenSchedulingAgent$1.run(TimerDrivenSchedulingAgent.java:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: com.scurrilous.circe.checksum.Crc32cIntChecksum.computeChecksum(Lorg/apache/pulsar/shade/io/netty/buffer/ByteBuf;)I
	at org.apache.pulsar.common.api.Commands.serializeCommandSendWithSize(Commands.java:948)
	at org.apache.pulsar.common.api.Commands.newSend(Commands.java:315)
	at org.apache.pulsar.client.impl.ProducerImpl.sendMessage(ProducerImpl.java:449)
	at org.apache.pulsar.client.impl.ProducerImpl.sendAsync(ProducerImpl.java:376)
	... 17 common frames omitted

**Comment by sijie** [comment]
@david-streamlio can you please help @otmanel31 with his issue?

**Comment by sijie** [comment]
@otmanel31 I think you'd better to create an issue on streamlio/nifi-pulsar-bundle repo. hence you will get direct support over there

**Comment by david-streamlio** [comment]
Yes I will take a look and update this ticket as well as https://github.com/streamlio/nifi-pulsar-bundle

**Comment by david-streamlio** [comment]
Could it be related to this issue?  https://github.com/apache/pulsar/issues/2890

**Comment by david-streamlio** [comment]
I have published a fix in the https://github.com/streamlio/nifi-pulsar-bundle repo, let's close this issue.

**Comment by otmanel31** [comment]
hi thanks for  quick response. that"s work for me i'm now able to publish to pulsar broker without any issue. I close this issue.
👍

**Comment by otmanel31** [comment]
@david-streamlio Thank you very much.
