### ISSUE TITLE
NPE occurs while searching for namespace bundle

### ISSUE THREAD

**Issue by massakam** [apache/pulsar#5176]
The other day, stopping a broker caused an NPE on another broker in the same cluster. At this time, the client continued to fail to lookup the topic. The following is the log of the broker where NPE occurred:

```
11:27:17.757 [pulsar-1-1] WARN  o.a.p.b.namespace.NamespaceService   - Error when searching for candidate broker to acquire tenant/global/ns/0xa3ffffff_0xa7ffffff: null
java.lang.NullPointerException: null
        at org.apache.pulsar.broker.loadbalance.impl.LoadManagerShared.lambda$removeMostServicingBrokersForNamespace$3(LoadManagerShared.java:294)
        at java.util.Collection.removeIf(Collection.java:414)
        at org.apache.pulsar.broker.loadbalance.impl.LoadManagerShared.removeMostServicingBrokersForNamespace(LoadManagerShared.java:293)
        at org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerImpl.selectBrokerForAssignment(ModularLoadManagerImpl.java:721)
        at org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerWrapper.getLeastLoaded(ModularLoadManagerWrapper.java:69)
        at org.apache.pulsar.broker.namespace.NamespaceService.getLeastLoadedFromLoadManager(NamespaceService.java:519)
        at org.apache.pulsar.broker.namespace.NamespaceService.searchForCandidateBroker(NamespaceService.java:394)
        at org.apache.pulsar.broker.namespace.NamespaceService.lambda$null$4(NamespaceService.java:347)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
...
11:27:17.761 [pulsar-io-20-27] WARN  o.a.p.broker.lookup.TopicLookupBase  - Failed to lookup xxx for topic persistent://tenant/global/ns/dest-partition-6 with error java.lang.NullPointerException
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:984)
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
        at org.apache.pulsar.broker.namespace.NamespaceService.getBrokerServiceUrlAsync(NamespaceService.java:158)
        at org.apache.pulsar.broker.lookup.TopicLookupBase.lambda$lookupTopicAsync$8(TopicLookupBase.java:225)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:669)
        at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:1997)
        at org.apache.pulsar.broker.lookup.TopicLookupBase.lookupTopicAsync(TopicLookupBase.java:221)
        at org.apache.pulsar.broker.service.ServerCnx.lambda$handleLookup$3(ServerCnx.java:263)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983)
        at org.apache.pulsar.broker.service.ServerCnx.handleLookup(ServerCnx.java:261)
        at org.apache.pulsar.common.api.PulsarDecoder.channelRead(PulsarDecoder.java:112)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1436)
        at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1215)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1249)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
        at org.apache.pulsar.broker.loadbalance.impl.LoadManagerShared.lambda$removeMostServicingBrokersForNamespace$3(LoadManagerShared.java:294)
        at java.util.Collection.removeIf(Collection.java:414)
        at org.apache.pulsar.broker.loadbalance.impl.LoadManagerShared.removeMostServicingBrokersForNamespace(LoadManagerShared.java:293)
        at org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerImpl.selectBrokerForAssignment(ModularLoadManagerImpl.java:721)
        at org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerWrapper.getLeastLoaded(ModularLoadManagerWrapper.java:69)
        at org.apache.pulsar.broker.namespace.NamespaceService.getLeastLoadedFromLoadManager(NamespaceService.java:519)
        at org.apache.pulsar.broker.namespace.NamespaceService.searchForCandidateBroker(NamespaceService.java:394)
        at org.apache.pulsar.broker.namespace.NamespaceService.lambda$null$4(NamespaceService.java:347)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 2 common frames omitted
```

NPE was occurring on this line:
https://github.com/apache/pulsar/blob/v2.3.2/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LoadManagerShared.java#L294

This means that `brokerToNamespaceToBundleRange.get(broker).get(namespaceName)` returned null. However, it had been made sure in [this part](https://github.com/apache/pulsar/blob/v2.3.2/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LoadManagerShared.java#L269-L275) that `brokerToNamespaceToBundleRange.get(broker).get(namespaceName)` is not null, and it is mysterious that NPE occurred.

The version of Pulsar is 2.3.2.

**Comment by massakam** [comment]
Is there a possibility that `brokerToNamespaceToBundleRange` may be updated by other threads during the execution of the` removeMostServicingBrokersForNamespace()` method?
https://github.com/apache/pulsar/blob/01422476248d23741ff74f68e9cbd48ddf097108/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LoadManagerShared.java#L260-L296

**Comment by massakam** [comment]
I think that the cause of NPE is that entries of `brokerToNamespaceToBundleRange` are cleared in the following part:
https://github.com/apache/pulsar/blob/01422476248d23741ff74f68e9cbd48ddf097108/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java#L543-L549

In the above part, `namespaceToBundleRange` is locked, but it is not locked when executing `removeMostServicingBrokersForNamespace()`. Therefore, `brokerToNamespaceToBundleRange` may be updated during execution of `removeMostServicingBrokersForNamespace()`.
