### ISSUE TITLE
TooLongFrameException : Adjusted frame length exceeds 5253120: 369295620 - discarded => Error while producing message with TLS on standalone setup

### ISSUE THREAD

**Issue by iravishah** [apache/pulsar#5206]
I am using apache pulsar 2.4.0 on standalone setup on ubuntu machine 18.04. 

When i am producing message without TLS enabled it works fine but when i enable TLS throws error. Using Apache Pulsar docs i have created certs and updated standalone.conf and client.conf to producer message.

I am trying with inbuilt producer client itself.

### **Broker side error:**
`02:01:51.790 [pulsar-io-50-3] INFO  org.apache.pulsar.broker.service.ServerCnx - New connection from /127.0.0.1:41744
02:01:51.821 [pulsar-io-50-3] WARN  org.apache.pulsar.broker.service.ServerCnx - [/127.0.0.1:41744] Got exception TooLongFrameException : Adjusted frame length exceeds 5253120: 369295620 - discarded
io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 5253120: 369295620 - discarded
    at io.netty.handler.codec.LengthFieldBasedFrameDecoder.fail(LengthFieldBasedFrameDecoder.java:522) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.handler.codec.LengthFieldBasedFrameDecoder.failIfNecessary(LengthFieldBasedFrameDecoder.java:500) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.handler.codec.LengthFieldBasedFrameDecoder.exceededFrameLength(LengthFieldBasedFrameDecoder.java:387) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:430) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:343) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]`

### **Client side error while producing message** ###
`02:11:43.970 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.ConnectionPool - [[id: 0xf13e4ea5, L:/127.0.0.1:41900 - R:localhost/127.0.0.1:6651]] Connected to server
02:11:44.017 [pulsar-client-io-1-1] WARN  org.apache.pulsar.client.impl.ClientCnx - Error during handshake
java.nio.channels.ClosedChannelException: null
	at io.netty.handler.ssl.SslHandler.channelInactive(...)(Unknown Source) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
02:11:44.033 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.ClientCnx - [id: 0xf13e4ea5, L:/127.0.0.1:41900 ! R:localhost/127.0.0.1:6651] Disconnected
02:11:44.040 [pulsar-client-io-1-1] WARN  org.apache.pulsar.client.impl.ConnectionPool - [[id: 0xf13e4ea5, L:/127.0.0.1:41900 ! R:localhost/127.0.0.1:6651]] Connection handshake failed: org.apache.pulsar.client.api.PulsarClientException: Connection already closed
02:11:44.040 [pulsar-client-io-1-1] WARN  org.apache.pulsar.client.impl.PulsarClientImpl - [t1] Failed to get partitioned topic metadata: org.apache.pulsar.client.api.PulsarClientException: Connection already closed
02:11:44.041 [main] ERROR org.apache.pulsar.client.cli.PulsarClientTool - Error while producing messages
02:11:44.041 [main] ERROR org.apache.pulsar.client.cli.PulsarClientTool - java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException: Connection already closed
org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException: Connection already closed
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:297) ~[org.apache.pulsar-pulsar-client-api-2.4.0.jar:2.4.0]
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:88) ~[org.apache.pulsar-pulsar-client-original-2.4.0.jar:2.4.0]
	at org.apache.pulsar.client.cli.CmdProduce.publish(CmdProduce.java:179) [org.apache.pulsar-pulsar-client-tools-2.4.0.jar:2.4.0]
	at org.apache.pulsar.client.cli.CmdProduce.run(CmdProduce.java:169) [org.apache.pulsar-pulsar-client-tools-2.4.0.jar:2.4.0]
	at org.apache.pulsar.client.cli.PulsarClientTool.run(PulsarClientTool.java:131) [org.apache.pulsar-pulsar-client-tools-2.4.0.jar:2.4.0]
	at org.apache.pulsar.client.cli.PulsarClientTool.main(PulsarClientTool.java:165) [org.apache.pulsar-pulsar-client-tools-2.4.0.jar:2.4.0]
Caused by: java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException: Connection already closed
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_222]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) ~[?:1.8.0_222]
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:86) ~[org.apache.pulsar-pulsar-client-original-2.4.0.jar:2.4.0]
	... 4 more
Caused by: org.apache.pulsar.client.api.PulsarClientException: Connection already closed
	at org.apache.pulsar.client.impl.ClientCnx.channelInactive(ClientCnx.java:220) ~[org.apache.pulsar-pulsar-client-original-2.4.0.jar:2.4.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:390) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:355) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:390) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:355) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1054) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:826) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:335) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_222]
02:11:44.046 [main] INFO  org.apache.pulsar.client.cli.PulsarClientTool - 0 messages successfully produced
`
### **Expected -** 
It should produce message

**Comment by merlimat** [comment]
This looks like you're trying to connecting in clear text to the TLS port. 

Did you use `pulsar+ssl://x.x.x.x:6651` as your service URL?

**Comment by iravishah** [comment]
yes, I am using the same url.
pulsar+ssl://localhost:6651

**Comment by sijie** [comment]
@iravishah can you provide more details about how do you configure TLS for your broker and your client? This can help us debug your issue.

**Comment by iravishah** [comment]
@sijie I have followed [this](https://pulsar.apache.org/docs/en/security-tls-transport/) guide to generate certs for CA and Server.

**Standalone config**
`brokerServicePort=6651
webServicePort=8443
tlsEnabled=true
tlsCertificateFilePath=/path/to/broker.cert.pem
tlsKeyFilePath=/home/path/to/broker.key-pk8.pem
tlsTrustCertsFilePath=/path/to/ca.cert.pem`

**Client config**
`useTls=true
webServiceUrl=http://localhost:8443/
brokerServiceUrl=pulsar+ssl://localhost:6651/
authPlugin=org.apache.pulsar.client.impl.auth.AuthenticationTls
authParams=tlsCertFile:/path/to/broker.cert.pem,tlsKeyFile:/path/to/broker.key-pk8.pem
tlsAllowInsecureConnection=false
tlsEnableHostnameVerification=false
tlsTrustCertsFilePath=/path/to/ca.cert.pem`

**Comment by iravishah** [comment]
I have added `brokerServicePortTls=6651` and now i am getting 
`ERROR org.apache.pulsar.common.util.SslContextAutoRefreshBuilder - Execption while trying to refresh ssl Context Private key loading error`
while starting standalone pulsar

**Comment by TC-oKozlov** [comment]
We are having similar issue in our setup, however in our case we run Pulsar on Kubernetes and trying to have SSL terminate on the load balancer in-front of the Pulsar Proxy, so the client has to send msgs using "pulsar+ssl", but it's not encrypted behind the load balancer, so it's not clear whether  proxy and broker should use standard broker port 6650, or TLS broker port 6651?

**Comment by futeng** [comment]
I had the same problem, and I solved it. I hope it helps. @iravishah @sijie 
I configured TLS encryption based on the same [document](https://pulsar.apache.org/docs/en/security-tls-transport/).
When using `bin/pulsar-client` to generate data, the same exception occurs, and the log looks like this:

```shell
[root@offline126 apache-pulsar-2.4.2]# bin/pulsar-client --url pulsar://offline126:6651/  produce   persistent://public/default/test   -n 100   -m "Hello Pulsar"
09:47:29.955 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.ConnectionPool - [[id: 0x09a73636, L:/192.168.129.126:49002 - R:offline126/192.168.129.126:6651]] Connected to server
09:47:29.989 [pulsar-client-io-1-1] WARN  org.apache.pulsar.client.impl.ClientCnx - [offline126/192.168.129.126:6651] Got exception TooLongFrameException : Adjusted frame length exceeds 5253120: 352518404 - discarded
io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 5253120: 352518404 - discarded
...
```

I realized it might be a protocol header issue, so I changed the URL from **`pulsar://xxx`** to  **`pulsar+ssl://xxx`**. And it worked.

```shell
[root@offline126 apache-pulsar-2.4.2]# bin/pulsar-client --url pulsar+ssl://offline126:6651/  produce   persistent://public/default/test   -n 100   -m "Hello Pulsar"
10:11:14.695 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.ConnectionPool - [[id: 0x918ed558, L:/192.168.129.126:49218 - R:offline126/192.168.129.126:6651]] Connected to server
10
...
10:11:15.893 [main] INFO  org.apache.pulsar.client.cli.PulsarClientTool - 100 messages successfully produced
```

**Comment by sijie** [comment]
@futeng thank you! Yes. you need to use `pulsar+ssl` to connect to the service.

**Comment by sijie** [comment]
Close this issue since it was answered
