### ISSUE TITLE
how to safely delete bookie of pulsar cluster? 

### ISSUE THREAD

**Issue by sydnash** [apache/pulsar#5220]
**Describe the bug**
I have a pulsar cluster with four bookie, and ledger set like this:
```
# Number of bookies to use when creating a ledger
managedLedgerDefaultEnsembleSize=2

# Number of copies to store for each message
managedLedgerDefaultWriteQuorum=2

# Number of guaranteed copies (acks to wait before write is complete)
managedLedgerDefaultAckQuorum=2
```
when I publish some message to topic.(witch is already has subscriptions but no comsumer)
I close tow of the bookie and run the follow command which wait until the closed bookie's ledger is re-replicated to other bokie.（I do this step one by one)
```
    ./bookkeeper shell decommissionbookie  --bookieid closedbookieip:3181
```
after that  i couldn't  receive message on it any more, but i can produce to it.

the stats of topic like this:
```
{
  "msgRateIn" : 0.0,
  "msgThroughputIn" : 0.0,
  "msgRateOut" : 0.0,
  "msgThroughputOut" : 0.0,
  "averageMsgSize" : 0.0,
  "storageSize" : 318091591,
  "publishers" : [ ],
  "subscriptions" : {
    "subscription-1" : {
      "msgRateOut" : 0.0,
      "msgThroughputOut" : 0.0,
      "msgRateRedeliver" : 0.0,
      "msgBacklog" : 2379,
      "blockedSubscriptionOnUnackedMsgs" : false,
      "msgDelayed" : 0,
      "unackedMessages" : 0,
      "type" : "Exclusive",
      "msgRateExpired" : 0.0,
      "consumers" : [ ],
      "isReplicated" : false
    }
  },
  "replication" : { },
  "deduplicationStatus" : "Disabled"
}
```

**To Reproduce**
1. start a pulsar with four bookie
2. publish message to topic witch has subscription .
3. close the a bookie and run `./bookkeeper shell decommissionbookie  --bookieid  closedbookieip:3181` , then wait it report success message.
4. delete data of the bookie, and then restart the bookie.
5. repeat 3-4 one all bookie.

**Expected behavior**
I want i can receive message after the upon steps.

**Screenshots**
and after that i got some error when do some command
```
$ bin/pulsar-admin namespaces list public
public/default
$ bin/pulsar-admin topics list public/default
HTTP 500 Internal Server Error

Reason: HTTP 500 Internal Server Error
```
in he log file I find this errmsg:

```
14:59:03.405 [pulsar-web-30-2] ERROR org.apache.pulsar.broker.admin.v2.NonPersistentTopics - [null] Failed to get list of topics under namespace public/default
java.util.concurrent.ExecutionException: org.apache.pulsar.client.admin.PulsarAdminException$ServerSideErrorException: HTTP 500 Internal Server Error
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_212]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) ~[?:1.8.0_212]
        at org.apache.pulsar.broker.admin.v2.NonPersistentTopics.getList(NonPersistentTopics.java:184) ~[org.apache.pulsar-pulsar-broker-2.4.0.jar:2.4.0]
...
```
but i can use topics stats get the topics stats.
```
$ bin/pulsar-admin topics stats persistent://public/default/topic-test1
{
  "msgRateIn" : 0.0,
  "msgThroughputIn" : 0.0,
  "msgRateOut" : 0.0,
  "msgThroughputOut" : 0.0,
  "averageMsgSize" : 0.0,
  "storageSize" : 318091591,
  "publishers" : [ ],
  "subscriptions" : {
    "123" : {
      "msgRateOut" : 0.0,
      "msgThroughputOut" : 0.0,
      "msgRateRedeliver" : 0.0,
      "msgBacklog" : 0,
      "blockedSubscriptionOnUnackedMsgs" : false,
      "msgDelayed" : 0,
      "unackedMessages" : 0,
      "type" : "Exclusive",
      "msgRateExpired" : 0.0,
      "consumers" : [ ],
      "isReplicated" : false
    },
    "subscription-1" : {
      "msgRateOut" : 0.0,
      "msgThroughputOut" : 0.0,
      "msgRateRedeliver" : 0.0,
      "msgBacklog" : 2379,
      "blockedSubscriptionOnUnackedMsgs" : false,
      "msgDelayed" : 0,
      "unackedMessages" : 0,
      "type" : "Exclusive",
      "msgRateExpired" : 0.0,
      "consumers" : [ ],
      "isReplicated" : false
    }
  },
  "replication" : { },
  "deduplicationStatus" : "Disabled"
}
```

**Desktop (please complete the following information):**
 - OS:  linux centos

**Comment by sijie** [comment]
@sydnash can you share the `topic stats-internal` result?

**Comment by sydnash** [comment]
@sijie The scene has been destroyed, I solved it by restart all brokers.

**Comment by sydnash** [comment]
@sijie after restart all brokers, the all commonds are working corrected.
