### ISSUE TITLE
How do I test Pulsar Functions Locally? ModuleNotFoundError: No module named '_pulsar'

### ISSUE THREAD

**Issue by RAbraham** [apache/pulsar#5260]
**Describe the bug**
How do I run functions on my local Mac OS(Mojave) machine? It fails with `ModuleNotFoundError: No module named '_pulsar'`

**To Reproduce**
- In Terminal 1, I run `bin/pulsar functions-worker`
- In Terminal 2, 
```bash
➜  apache-pulsar-2.4.1 bin/pulsar-admin functions localrun \
  --py /Users/rabraham/Documents/dev/fifteenrock/fifteenrock-connector/pulsar_lib/functions.py \
  --className functions.ArrowFunction \
  --inputs persistent://public/default/file-topic \
  --output persistent://public/default/result-topic
12:19:14.644 [main] INFO  org.apache.pulsar.functions.runtime.ProcessRuntimeFactory - Java instance jar location is not defined, using the location defined in system environment : /Users/rabraham/Documents/dev/trial/pulsar-trial/apache-pulsar-2.4.1/instances/java-instance.jar
12:19:14.647 [main] INFO  org.apache.pulsar.functions.runtime.ProcessRuntimeFactory - Python instance file location is not defined using the location defined in system environment : /Users/rabraham/Documents/dev/trial/pulsar-trial/apache-pulsar-2.4.1/instances/python-instance/python_instance_main.py
12:19:14.654 [main] INFO  org.apache.pulsar.functions.runtime.ProcessRuntimeFactory - No extra dependencies location is defined in either function worker config or system environment
12:19:14.859 [main] INFO  org.apache.pulsar.functions.runtime.RuntimeSpawner - public/default/ArrowFunction-0 RuntimeSpawner starting function
12:19:14.861 [main] INFO  org.apache.pulsar.functions.runtime.ProcessRuntime - Creating function log directory /Users/rabraham/Documents/dev/trial/pulsar-trial/apache-pulsar-2.4.1/logs/functions/public/default/ArrowFunction
12:19:14.868 [main] INFO  org.apache.pulsar.functions.runtime.ProcessRuntime - Created or found function log directory /Users/rabraham/Documents/dev/trial/pulsar-trial/apache-pulsar-2.4.1/logs/functions/public/default/ArrowFunction
12:19:14.869 [main] INFO  org.apache.pulsar.functions.runtime.ProcessRuntime - ProcessBuilder starting the process with args python /Users/rabraham/Documents/dev/trial/pulsar-trial/apache-pulsar-2.4.1/instances/python-instance/python_instance_main.py --py /Users/rabraham/Documents/dev/fifteenrock/fifteenrock-connector/pulsar_lib/functions.py --logging_directory /Users/rabraham/Documents/dev/trial/pulsar-trial/apache-pulsar-2.4.1/logs/functions --logging_file ArrowFunction --logging_config_file /Users/rabraham/Documents/dev/trial/pulsar-trial/apache-pulsar-2.4.1/conf/functions-logging/logging_config.ini --instance_id 0 --function_id 5373e0b5-9b1c-4656-8ab5-dba7de1c4bfb --function_version 74f6460f-8573-4ff4-a875-ae0acba78aef --function_details '{"tenant":"public","namespace":"default","name":"ArrowFunction","className":"functions.ArrowFunction","runtime":"PYTHON","autoAck":true,"parallelism":1,"source":{"inputSpecs":{"persistent://public/default/file-topic":{}},"cleanupSubscription":true},"sink":{"topic":"persistent://public/default/result-topic"},"resources":{"cpu":1.0,"ram":"1073741824","disk":"10737418240"},"componentType":"FUNCTION"}' --pulsar_serviceurl pulsar://localhost:6650 --use_tls false --tls_allow_insecure false --hostname_verification_enabled false --max_buffered_tuples 1024 --port 52463 --metrics_port 52464 --expected_healthcheck_interval 30 --secrets_provider secretsprovider.ClearTextSecretsProvider --cluster_name local
12:19:14.879 [main] INFO  org.apache.pulsar.functions.runtime.ProcessRuntime - Started process successfully
Traceback (most recent call last):
  File "/Users/rabraham/Documents/dev/trial/pulsar-trial/apache-pulsar-2.4.1/instances/python-instance/python_instance_main.py", line 36, in <module>
    import pulsar
  File "/Users/rabraham/Documents/dev/trial/pulsar-trial/apache-pulsar-2.4.1/instances/python-instance/pulsar/__init__.py", line 102, in <module>
    import _pulsar
ModuleNotFoundError: No module named '_pulsar'
```

**Desktop (please complete the following information):**
 - OS: Mac OS (Mojave)

**Additional context**
I don't have `pulsar-client` on my machine. I thought that local cluster would have it's own version of pulsar python code?

**Comment by pouledodue** [comment]
what happens if you `pip install pulsar-client` before the above command

**Comment by pouledodue** [comment]
with or without using `pyenv`

**Comment by pouledodue** [comment]
you can run the docker standalone but it's python 3.5 #4944

**Comment by RAbraham** [comment]
Yes, `pip install pulsar-client ` moved it forward but it failed looking for the latest python code I think. I'm running Pulsar 2.4.1 but on python 3.6.8, the python library is at 2.0 and my personal problem is that I can't get pulsar to work with 3.7. Thanks for that tip though.
