### ISSUE TITLE
JAAS login in broker failed

### ISSUE THREAD

**Issue by ChangWinde** [apache/pulsar#5283]
**Describe the problem：**
I followed the guidance of the docs[https://pulsar.apache.org/docs/en/security-kerberos/] and try to use kerberos for authentication in pulsar. But I encountered following problem.

The information of exception：
ERROR org.apache.pulsar.broker.authentication.AuthenticationProviderSasl - JAAS login in broker failed: {}
javax.security.auth.login.LoginException: Unrecognized SASL GSSAPI Server Callback. not available to garner  authentication information from the user
        at com.sun.security.auth.module.Krb5LoginModule.promptForPass(Krb5LoginModule.java:940) ~[?:1.8.0_221]
        at com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:760) ~[?:1.8.0_221]
        at com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:617) ~[?:1.8.0_221]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_221]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_221]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_221]
        at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755) ~[?:1.8.0_221]
        at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195) ~[?:1.8.0_221]
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682) ~[?:1.8.0_221]
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680) ~[?:1.8.0_221]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_221]
        at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680) ~[?:1.8.0_221]
        at javax.security.auth.login.LoginContext.login(LoginContext.java:587) ~[?:1.8.0_221]
        at org.apache.pulsar.common.sasl.JAASCredentialsContainer.<init>(JAASCredentialsContainer.java:72) ~[org.apache.pulsar-pulsar-common-2.4.0.jar:2.4.0]
        at org.apache.pulsar.broker.authentication.AuthenticationProviderSasl.initialize(AuthenticationProviderSasl.java:88) [org.apache.pulsar-pulsar-broker-auth-sasl-2.4.0.jar:2.4.0]
        at org.apache.pulsar.broker.authentication.AuthenticationService.<init>(AuthenticationService.java:57) [org.apache.pulsar-pulsar-broker-common-2.4.0.jar:2.4.0]
        at org.apache.pulsar.broker.service.BrokerService.<init>(BrokerService.java:242) [org.apache.pulsar-pulsar-broker-2.4.0.jar:2.4.0]
        at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:366) [org.apache.pulsar-pulsar-broker-2.4.0.jar:2.4.0]
        at org.apache.pulsar.PulsarBrokerStarter$BrokerStarter.start(PulsarBrokerStarter.java:273) [org.apache.pulsar-pulsar-broker-2.4.0.jar:2.4.0]
        at org.apache.pulsar.PulsarBrokerStarter.main(PulsarBrokerStarter.java:332) [org.apache.pulsar-pulsar-broker-2.4.0.jar:2.4.0]
10:57:32.153 [main] ERROR org.apache.pulsar.broker.PulsarService - Failed to load an authentication provider.
org.apache.pulsar.broker.PulsarServerException: Failed to load an authentication provider.
        at org.apache.pulsar.broker.authentication.AuthenticationService.<init>(AuthenticationService.java:65) ~[org.apache.pulsar-pulsar-broker-common-2.4.0.jar:2.4.0]
        at org.apache.pulsar.broker.service.BrokerService.<init>(BrokerService.java:242) ~[org.apache.pulsar-pulsar-broker-2.4.0.jar:2.4.0]
        at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:366) [org.apache.pulsar-pulsar-broker-2.4.0.jar:2.4.0]
        at org.apache.pulsar.PulsarBrokerStarter$BrokerStarter.start(PulsarBrokerStarter.java:273) [org.apache.pulsar-pulsar-broker-2.4.0.jar:2.4.0]

**Environment：**
pulsar: 2.4.0
java: 1.8.0
kerberos: 1.17

**Comment by aerfalwl** [comment]
how did you solve this problem
