### ISSUE TITLE
presto connection to pulsar issues

### ISSUE THREAD

**Issue by tooptoop4** [apache/pulsar#5300]
1.
#hanging for more than 10mins so i killed it (presto .220 and pulsar 2.4.0)
select * from "event-notification-test-topic" limit 1;

2.

presto:public/default> show create table "trade-status-test";
Query 20191001_090836_00019_dq4m7 failed: Table has no columns: TableHandle{connectorId=pulsar, connectorHandle=PulsarTableHandle{connectorId=pulsar, schemaName=public/default, tableName=trade-status-test, topicName=trade-status-test}, layout=Optional.empty}
com.facebook.presto.spi.PrestoException: Table has no columns: TableHandle{connectorId=pulsar, connectorHandle=PulsarTableHandle{connectorId=pulsar, schemaName=public/default, tableName=trade-status-test, topicName=trade-status-test}, layout=Optional.empty}
        at com.facebook.presto.metadata.MetadataManager.getTableMetadata(MetadataManager.java:480)
        at com.facebook.presto.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowCreate(ShowQueriesRewrite.java:449)
        at com.facebook.presto.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowCreate(ShowQueriesRewrite.java:151)
        at com.facebook.presto.sql.tree.ShowCreate.accept(ShowCreate.java:67)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at com.facebook.presto.sql.rewrite.ShowQueriesRewrite.rewrite(ShowQueriesRewrite.java:148)
        at com.facebook.presto.sql.rewrite.StatementRewrite.rewrite(StatementRewrite.java:53)
        at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:76)
        at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:71)
        at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:209)
        at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:97)
        at com.facebook.presto.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:744)
        at com.facebook.presto.execution.SqlQueryManager.createQueryInternal(SqlQueryManager.java:366)
        at com.facebook.presto.execution.SqlQueryManager.lambda$createQuery$4(SqlQueryManager.java:305)
        at com.facebook.presto.$gen.Presto_0_220_dirty__0_220____20191001_090225_1.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

3.

presto:public/default> select count(1) c, 'test' t from "test";
Query 20191001_084757_00078_y4kjh failed: name is null
java.lang.NullPointerException: name is null
        at com.facebook.presto.spi.SchemaUtil.checkNotEmpty(SchemaUtil.java:25)
        at com.facebook.presto.spi.ColumnMetadata.<init>(ColumnMetadata.java:60)
        at com.facebook.presto.spi.ColumnMetadata.<init>(ColumnMetadata.java:50)
        at org.apache.pulsar.sql.presto.PulsarColumnMetadata.<init>(PulsarColumnMetadata.java:39)
        at org.apache.pulsar.sql.presto.PulsarMetadata.getColumns(PulsarMetadata.java:449)
        at org.apache.pulsar.sql.presto.PulsarMetadata.getPulsarColumnsFromStructSchema(PulsarMetadata.java:392)
        at org.apache.pulsar.sql.presto.PulsarMetadata.getPulsarColumns(PulsarMetadata.java:342)
        at org.apache.pulsar.sql.presto.PulsarMetadata.getTableMetadata(PulsarMetadata.java:326)
        at org.apache.pulsar.sql.presto.PulsarMetadata.getTableMetadata(PulsarMetadata.java:159)
        at com.facebook.presto.metadata.MetadataManager.getTableMetadata(MetadataManager.java:478)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:926)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:257)
        at com.facebook.presto.sql.tree.Table.accept(Table.java:53)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:271)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:1852)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1031)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:257)
        at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:127)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:271)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:281)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:746)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:257)
        at com.facebook.presto.sql.tree.Query.accept(Query.java:94)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:271)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:249)
        at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:79)
        at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:71)
        at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:209)
        at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:97)
        at com.facebook.presto.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:744)
        at com.facebook.presto.execution.SqlQueryManager.createQueryInternal(SqlQueryManager.java:366)
        at com.facebook.presto.execution.SqlQueryManager.lambda$createQuery$4(SqlQueryManager.java:305)
        at com.facebook.presto.$gen.Presto_0_220_dirty__0_220____20191001_083044_1.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

4.

presto:public/default> select count(1) c, 'tradestore-deadletter-topic' t from "tradestore-deadletter-topic";
Query 20191001_084810_00081_y4kjh failed: org.apache.bookkeeper.mledger.ManagedLedgerException: java.util.concurrent.CompletionException: org.apache.bookkeeper.client.BKException$BKReadException: Error while reading ledger
java.lang.RuntimeException: org.apache.bookkeeper.mledger.ManagedLedgerException: java.util.concurrent.CompletionException: org.apache.bookkeeper.client.BKException$BKReadException: Error while reading ledger
        at org.apache.pulsar.sql.presto.PulsarSplitManager.getSplits(PulsarSplitManager.java:134)
        at com.facebook.presto.split.SplitManager.getSplits(SplitManager.java:82)
        at com.facebook.presto.split.CloseableSplitSourceProvider.getSplits(CloseableSplitSourceProvider.java:51)
        at com.facebook.presto.sql.planner.SplitSourceFactory$Visitor.lambda$visitTableScan$0(SplitSourceFactory.java:126)
        at com.facebook.presto.sql.planner.SplitSourceFactory$Visitor.visitTableScan(SplitSourceFactory.java:131)
        at com.facebook.presto.sql.planner.SplitSourceFactory$Visitor.visitTableScan(SplitSourceFactory.java:102)
        at com.facebook.presto.sql.planner.plan.TableScanNode.accept(TableScanNode.java:175)
        at com.facebook.presto.sql.planner.SplitSourceFactory$Visitor.visitProject(SplitSourceFactory.java:258)
        at com.facebook.presto.sql.planner.SplitSourceFactory$Visitor.visitProject(SplitSourceFactory.java:102)
        at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:77)
        at com.facebook.presto.sql.planner.SplitSourceFactory$Visitor.visitAggregation(SplitSourceFactory.java:222)
        at com.facebook.presto.sql.planner.SplitSourceFactory$Visitor.visitAggregation(SplitSourceFactory.java:102)
        at com.facebook.presto.sql.planner.plan.AggregationNode.accept(AggregationNode.java:198)
        at com.facebook.presto.sql.planner.SplitSourceFactory$Visitor.processSources(SplitSourceFactory.java:356)
        at com.facebook.presto.sql.planner.SplitSourceFactory$Visitor.visitExchange(SplitSourceFactory.java:349)
        at com.facebook.presto.sql.planner.SplitSourceFactory$Visitor.visitExchange(SplitSourceFactory.java:102)
        at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:281)
        at com.facebook.presto.sql.planner.SplitSourceFactory$Visitor.visitAggregation(SplitSourceFactory.java:222)
        at com.facebook.presto.sql.planner.SplitSourceFactory$Visitor.visitAggregation(SplitSourceFactory.java:102)
        at com.facebook.presto.sql.planner.plan.AggregationNode.accept(AggregationNode.java:198)
        at com.facebook.presto.sql.planner.SplitSourceFactory.createSplitSources(SplitSourceFactory.java:84)
        at com.facebook.presto.execution.scheduler.SqlQueryScheduler.createStreamingLinkedStages(SqlQueryScheduler.java:411)
        at com.facebook.presto.execution.scheduler.SqlQueryScheduler.createStreamingLinkedStages(SqlQueryScheduler.java:500)
        at com.facebook.presto.execution.scheduler.SqlQueryScheduler.createStages(SqlQueryScheduler.java:327)
        at com.facebook.presto.execution.scheduler.SqlQueryScheduler.<init>(SqlQueryScheduler.java:207)
        at com.facebook.presto.execution.scheduler.SqlQueryScheduler.createSqlQueryScheduler(SqlQueryScheduler.java:154)
        at com.facebook.presto.execution.SqlQueryExecution.planDistribution(SqlQueryExecution.java:490)
        at com.facebook.presto.execution.SqlQueryExecution.startExecution(SqlQueryExecution.java:359)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.bookkeeper.mledger.ManagedLedgerException: java.util.concurrent.CompletionException: org.apache.bookkeeper.client.BKException$BKReadException: Error while reading ledger
Caused by: java.util.concurrent.CompletionException: org.apache.bookkeeper.client.BKException$BKReadException: Error while reading ledger
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at org.apache.bookkeeper.client.SyncCallbackUtils.finish(SyncCallbackUtils.java:83)
        at org.apache.bookkeeper.client.SyncCallbackUtils$SyncOpenCallback.openComplete(SyncCallbackUtils.java:157)
        at org.apache.bookkeeper.client.LedgerOpenOp.openComplete(LedgerOpenOp.java:232)
        at org.apache.bookkeeper.client.LedgerOpenOp$2.readLastConfirmedComplete(LedgerOpenOp.java:215)
        at org.apache.bookkeeper.client.LedgerHandle$10.readLastConfirmedDataComplete(LedgerHandle.java:1393)
        at org.apache.bookkeeper.client.ReadLastConfirmedOp.readEntryComplete(ReadLastConfirmedOp.java:142)
        at org.apache.bookkeeper.proto.BookieClientImpl$2.safeRun(BookieClientImpl.java:330)
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.bookkeeper.client.BKException.BKReadException: Error while reading ledger
        ... 12 more

5.

presto:public/default> select * from "myenvoysampletopic";
Query 20191001_090442_00008_dq4m7 failed: Table 'public/default.myenvoysampletopic' not found
com.facebook.presto.spi.TableNotFoundException: Table 'public/default.myenvoysampletopic' not found
        at org.apache.pulsar.sql.presto.PulsarMetadata.getTableMetadata(PulsarMetadata.java:282)
        at org.apache.pulsar.sql.presto.PulsarMetadata.getTableMetadata(PulsarMetadata.java:141)
        at com.facebook.presto.metadata.MetadataManager.getTableMetadata(MetadataManager.java:478)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:926)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:257)
        at com.facebook.presto.sql.tree.Table.accept(Table.java:53)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:271)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:1852)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1031)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:257)
        at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:127)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:271)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:281)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:746)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:257)
        at com.facebook.presto.sql.tree.Query.accept(Query.java:94)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:271)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:249)
        at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:79)
        at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:71)
        at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:209)
        at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:97)
        at com.facebook.presto.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:744)
        at com.facebook.presto.execution.SqlQueryManager.createQueryInternal(SqlQueryManager.java:366)
        at com.facebook.presto.execution.SqlQueryManager.lambda$createQuery$4(SqlQueryManager.java:305)
        at com.facebook.presto.$gen.Presto_0_220_dirty__0_220____20191001_090225_1.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by sijie** [comment]
@tooptoop4 it seems that you attempted to query topics without schema. The presto integration didn't handle topics without schema. There is a fix in master (will be released 2.5.0) to handle topics without schema.

**Comment by sijie** [comment]
This has been implemented by #4728
