### ISSUE TITLE
function worker v2.4.1 issues on shared dependencies

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar#5449]
**Describe the bug**
We bumped our functions workers to v2.4.1 from v2.4.0 and the function which is using several dependencies can't boot because of the following stack:

```
13:10:51.038 [clevercloud/functions/accessLogsCleverCloudADCHaproxy-0] ERROR org.apache.pulsar.functions.instance.JavaInstanceRunnable - [clevercloud/functions/accessLogsCleverCloudADCHaproxy:0] Uncaught exception in Java Instance
java.lang.RuntimeException: User class constructor throws exception
        at org.apache.pulsar.functions.utils.Reflections.createInstance(Reflections.java:126) ~[org.apache.pulsar-pulsar-functions-utils-2.4.1.jar:2.4.1]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.setupJavaInstance(JavaInstanceRunnable.java:189) ~[org.apache.pulsar-pulsar-functions-instance-2.4.1.jar:?]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:234) [org.apache.pulsar-pulsar-functions-instance-2.4.1.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_192]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_192]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_192]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_192]
        at org.apache.pulsar.functions.utils.Reflections.createInstance(Reflections.java:118) ~[org.apache.pulsar-pulsar-functions-utils-2.4.1.jar:2.4.1]
        ... 3 more
Caused by: java.lang.LinkageError: ClassCastException: attempting to castjar:file:/pulsar/lib/javax.ws.rs-javax.ws.rs-api-2.1.jar!/javax/ws/rs/client/ClientBuilder.class to file:/tmp/pulsar-nar/pulsar-functions-0.1.0-SNAPSHOT.jar-unpacked/javax/ws/rs/client/ClientBuilder.class
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:81) ~[javax.ws.rs-javax.ws.rs-api-2.1.jar:2.1]
        at javax.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:97) ~[javax.ws.rs-javax.ws.rs-api-2.1.jar:2.1]
        at com.clevercloud.pulsar.util.GeoIPAPI.updateDatabase(GeoIPAPI.java:101) ~[?:?]
        at com.clevercloud.pulsar.util.GeoIPAPI.<init>(GeoIPAPI.java:45) ~[?:?]
        at com.clevercloud.pulsar.function.ApplicationsAddonsHaproxyAccessLogs.<init>(ApplicationsAddonsHaproxyAccessLogs.java:28) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_192]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_192]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_192]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_192]
        at org.apache.pulsar.functions.utils.Reflections.createInstance(Reflections.java:118) ~[org.apache.pulsar-pulsar-functions-utils-2.4.1.jar:2.4.1]
        ... 3 more
13:10:51.047 [clevercloud/functions/accessLogsCleverCloudADCHaproxy-0] INFO  org.apache.pulsar.functions.instance.JavaInstanceRunnable - Closing instance
````

**Comment by KannarFr** [comment]
@sijie do you have news about this point?

**Comment by KannarFr** [comment]
@sijie As a reminder you told me this by Slack:

> it looks like there are pulsar-admin client dependencies in the runtime, and client dependencies in your function. they are loaded by different classloaders, so one can not be casted to the other.
I thnk we need to fix this bug or revert the approach back to the shade approach

**Comment by jiazhai** [comment]
@KannarFr Thanks for the reporting. is this still an issue in the latest code? would you please close this issue, if it is not?

**Comment by KannarFr** [comment]
This is not.
