### ISSUE TITLE
Similar to issue #2037 - Initialization of cluster meta data fails with KeeperErrorCode = NodeExists

### ISSUE THREAD

**Issue by apankha** [apache/pulsar#5523]
Very similar issue to: https://github.com/apache/pulsar/issues/2037

Initialization of cluster meta data fails while setting up a cluster pulsar instance following the steps in https://pulsar.apache.org/docs/en/deploy-bare-metal/

**Actual behaviour:**
Exception in thread "main" org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /namespace
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:122)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
        at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:792)
        at org.apache.pulsar.PulsarClusterMetadataSetup.main(PulsarClusterMetadataSetup.java:175)

**Expected behavior**
We have managed to set up a similar cluster with RHEL7 VMs with similar configuration without any issues.

**System Configuration**
Pulsar version 2.4.1
Java version zulu8.36.0.1-ca-jdk8.0.202-linux_x64

Any suggestions to help us resolve the problem?

**Comment by sijie** [comment]
@apankha it seems that you already set up a Pulsar cluster before. Are you planning to set up multiple Pulsar clusters using one zookeeper cluster?
