### ISSUE TITLE
Missing CLI error handling in pulsar-admin

### ISSUE THREAD

**Issue by candlerb** [apache/pulsar#5533]
**Describe the bug**
pulsar-admin can raise Java exceptions in certain conditions

**To Reproduce**

(1) Giving an invalid command - e.g. "functions getstate" (should be "functions querystate"), with or without `--help` added

```
$ apache-pulsar-2.4.1/bin/pulsar-admin functions getstate
Expected a command, got getstate

Exception in thread "main" com.beust.jcommander.ParameterException: Asking description for unknown command: null
	at com.beust.jcommander.JCommander.getCommandDescription(JCommander.java:1003)
	at com.beust.jcommander.JCommander.usage(JCommander.java:988)
	at com.beust.jcommander.JCommander.usage(JCommander.java:980)
	at com.beust.jcommander.JCommander.usage(JCommander.java:972)
	at org.apache.pulsar.admin.cli.CmdBase.run(CmdBase.java:49)
	at org.apache.pulsar.admin.cli.PulsarAdminTool.run(PulsarAdminTool.java:218)
	at org.apache.pulsar.admin.cli.PulsarAdminTool.main(PulsarAdminTool.java:260)
```
(Hangs here, have to press `^C`)

(2) Giving a querystate command without the "--key" option

```
$ apache-pulsar-2.4.1/bin/pulsar-admin functions querystate --name womble
null

Reason: java.lang.NullPointerException: path is 'null'.
```

tcpdump shows no traffic on port 8080, so this appears to be a local CLI issue.

**Expected behavior**
Error message to be reported

**Comment by candlerb** [comment]
Another example:

```
$ apache-pulsar-2.4.1/bin/pulsar-admin topics --help
Unknown option: --help

Exception in thread "main" com.beust.jcommander.ParameterException: Asking description for unknown command: null
	at com.beust.jcommander.JCommander.getCommandDescription(JCommander.java:1003)
	at com.beust.jcommander.JCommander.usage(JCommander.java:988)
	at com.beust.jcommander.JCommander.usage(JCommander.java:980)
	at com.beust.jcommander.JCommander.usage(JCommander.java:972)
	at org.apache.pulsar.admin.cli.CmdBase.run(CmdBase.java:49)
	at org.apache.pulsar.admin.cli.PulsarAdminTool.run(PulsarAdminTool.java:218)
	at org.apache.pulsar.admin.cli.PulsarAdminTool.main(PulsarAdminTool.java:260)
^C
```

**Comment by candlerb** [comment]
Another similar one:

```
bin/pulsar-admin topics public/default
Expected a command, got public/default

Exception in thread "main" com.beust.jcommander.ParameterException: Asking description for unknown command: null
	at com.beust.jcommander.JCommander.getCommandDescription(JCommander.java:1003)
	at com.beust.jcommander.JCommander.usage(JCommander.java:988)
	at com.beust.jcommander.JCommander.usage(JCommander.java:980)
	at com.beust.jcommander.JCommander.usage(JCommander.java:972)
	at org.apache.pulsar.admin.cli.CmdBase.run(CmdBase.java:49)
	at org.apache.pulsar.admin.cli.PulsarAdminTool.run(PulsarAdminTool.java:218)
	at org.apache.pulsar.admin.cli.PulsarAdminTool.main(PulsarAdminTool.java:260)
^C
```

**Comment by tuteng** [comment]
You can try pulsarctl, https://github.com/streamnative/pulsarctl

```
pulsarctl topics --help
Operations about topic(s)

Usage: pulsarctl topics [flags]

Commands:
  bundle-range  Get the namespace bundle range of a topic
  compact-status  Get status of compaction on a topic
  create      Create a topic with n partitions
  delete      Delete a topic
  get         Get the specified topic metadata
  get-permissions  Get the permissions of a topic
  grant-permissions  Grant permissions to a client on a topic
  internal-info  Get the topic internal info
  internal-stats  Get the internal stats of the specified topic
  last-message-id  Get the last message id of a topic
  list        List all exist topics under the specified namespace
  lookup      Look up a topic
  offload     Offload the messages of a topic to a long-term storage
  offload-status  Check the status of data offloading
  revoke-permissions  Revoke a client role permissions on a topic
  stats       Get the stats of an existing topic
  terminate   Terminate a non-partitioned topic
  unload      Unloading a topic
  update      Update partitioned topic partitions

Aliases: topics, topic

Common flags:
  -s, --admin-service-url string    The admin web service url that pulsarctl connects to. (default "http://localhost:8080")
      --auth-params string          Authentication parameters are used to configure the public and private key files required by tls
                                     For example: "tlsCertFile:val1,tlsKeyFile:val2"
  -C, --color string                toggle colorized logs (true,false,fabulous) (default "true")
  -h, --help                        help for this command
      --tls-allow-insecure          Allow TLS insecure connection
      --tls-trust-cert-pat string   Allow TLS trust cert file path
      --token string                Using the token to authentication
      --token-file string           Using the token file to authentication
  -v, --verbose int                 set log level, use 0 to silence, 4 for debugging (default 3)

Use 'pulsarctl topics [command] --help' for more information about a command.
```

**Comment by candlerb** [comment]
Yes, I have also been trying pulsarctl - that also has issues which I have raised [separately](https://github.com/streamnative/pulsarctl/issues).

pulsar-admin is the official admin tool for now, and means that I don't have to triage whether the problem is with pulsarctl or with Pulsar itself.

**Comment by zymap** [comment]
hi @candlerb. I fix the problem that when typing an invalid args the client hangs. 

And another issue is resolved at https://github.com/apache/pulsar/pull/5145.  I think this issue can be added to 2.4.2.

**Comment by candlerb** [comment]
Great, thanks!
