### ISSUE TITLE
Pulsar Broker restart fail owing to create functions/assignments topic fail

### ISSUE THREAD

**Issue by laxpio** [apache/pulsar#5669]
**Describe the bug**
restart pulsar broker，throws nullponitexception at create functions/assignments topic

error log：

```
13:46:52.437 [pulsar-ordered-OrderedExecutor-4-0-EventThread] INFO  org.apache.bookkeeper.client.LedgerCreateOp - Ensemble: [xxxx:3181, xxxxx:3181] for ledger: 276
13:46:52.438 [bookkeeper-ml-workers-OrderedExecutor-6-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [public/functions/persistent/coordinate] Created ledger 276
13:46:52.437 [bookkeeper-ml-workers-OrderedExecutor-0-0] ERROR org.apache.pulsar.broker.service.ServerCnx - [/xxxxxxx:28514] Failed to create topic persistent://public/functions/assignments
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_161]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:991) ~[?:1.8.0_161]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124) ~[?:1.8.0_161]
        at org.apache.pulsar.broker.service.persistent.MessageDeduplication.checkStatus(MessageDeduplication.java:178) ~[org.apache.pulsar-pulsar-broker-2.4.1.jar:2.4.1]
        at org.apache.pulsar.broker.service.persistent.PersistentTopic.checkDeduplicationStatus(PersistentTopic.java:899) ~[org.apache.pulsar-pulsar-broker-2.4.1.jar:2.4.1]
        at org.apache.pulsar.broker.service.BrokerService$2.lambda$openLedgerComplete$0(BrokerService.java:660) ~[org.apache.pulsar-pulsar-broker-2.4.1.jar:2.4.1]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981) ~[?:1.8.0_161]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124) ~[?:1.8.0_161]
        at org.apache.pulsar.broker.service.BrokerService$2.openLedgerComplete(BrokerService.java:658) ~[org.apache.pulsar-pulsar-broker-2.4.1.jar:2.4.1]
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerFactoryImpl.lambda$asyncOpen$7(ManagedLedgerFactoryImpl.java:328) ~[org.apache.pulsar-managed-ledger-original-2.4.1.jar:2.4.1]
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_161]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_161]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_161]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) ~[?:1.8.0_161]
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerFactoryImpl$2.initializeComplete(ManagedLedgerFactoryImpl.java:316) ~[org.apache.pulsar-managed-ledger-original-2.4.1.jar:2.4.1]
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl$3$1.operationComplete(ManagedLedgerImpl.java:467) ~[org.apache.pulsar-managed-ledger-original-2.4.1.jar:2.4.1]
        at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl$1.operationComplete(ManagedCursorImpl.java:271) ~[org.apache.pulsar-managed-ledger-original-2.4.1.jar:2.4.1]
        at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl$1.operationComplete(ManagedCursorImpl.java:244) ~[org.apache.pulsar-managed-ledger-original-2.4.1.jar:2.4.1]
        at org.apache.bookkeeper.mledger.impl.MetaStoreImplZookeeper.lambda$null$7(MetaStoreImplZookeeper.java:241) ~[org.apache.pulsar-managed-ledger-original-2.4.1.jar:2.4.1]
        at org.apache.bookkeeper.mledger.util.SafeRun$1.safeRun(SafeRun.java:32) [org.apache.pulsar-managed-ledger-original-2.4.1.jar:2.4.1]
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [org.apache.bookkeeper-bookkeeper-common-4.9.2.jar:4.9.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.startReadOperationOnLedger(ManagedLedgerImpl.java:1781) ~[org.apache.pulsar-managed-ledger-original-2.4.1.jar:2.4.1]
        at org.apache.bookkeeper.mledger.impl.OpReadEntry.create(OpReadEntry.java:52) ~[org.apache.pulsar-managed-ledger-original-2.4.1.jar:2.4.1]
        at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.asyncReadEntries(ManagedCursorImpl.java:475) ~[org.apache.pulsar-managed-ledger-original-2.4.1.jar:2.4.1]
        at org.apache.pulsar.broker.service.persistent.MessageDeduplication.replayCursor(MessageDeduplication.java:136) ~[org.apache.pulsar-pulsar-broker-2.4.1.jar:2.4.1]
        at org.apache.pulsar.broker.service.persistent.MessageDeduplication.recoverSequenceIdsMap(MessageDeduplication.java:124) ~[org.apache.pulsar-pulsar-broker-2.4.1.jar:2.4.1]
        at org.apache.pulsar.broker.service.persistent.MessageDeduplication.access$800(MessageDeduplication.java:55) ~[org.apache.pulsar-pulsar-broker-2.4.1.jar:2.4.1]
        at org.apache.pulsar.broker.service.persistent.MessageDeduplication$3.openCursorComplete(MessageDeduplication.java:223) ~[org.apache.pulsar-pulsar-broker-2.4.1.jar:2.4.1]
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.asyncOpenCursor(ManagedLedgerImpl.java:711) ~[org.apache.pulsar-managed-ledger-original-2.4.1.jar:2.4.1]
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.asyncOpenCursor(ManagedLedgerImpl.java:683) ~[org.apache.pulsar-managed-ledger-original-2.4.1.jar:2.4.1]
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.asyncOpenCursor(ManagedLedgerImpl.java:677) ~[org.apache.pulsar-managed-ledger-original-2.4.1.jar:2.4.1]
        at org.apache.pulsar.broker.service.persistent.MessageDeduplication.lambda$checkStatus$1(MessageDeduplication.java:216) ~[org.apache.pulsar-pulsar-broker-2.4.1.jar:2.4.1]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981) ~[?:1.8.0_161]
        ... 23 more
13:46:52.446 [bookkeeper-ml-workers-OrderedExecutor-6-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedCursorImpl - [public/functions/persistent/coordinate] Recovering from bookkeeper ledger cursor: pulsar.dedup

```

**Comment by wolfstudy** [comment]
@laxpio If you enabled `Deduplication` feature. If possible, please provide more detailed information, thanks.

**Comment by laxpio** [comment]
enabled Deduplication，
the logs are cleaned.

**Comment by wolfstudy** [comment]
Thanks @laxpio feedback.

> the logs are cleaned.

Can you provide the operation way when this error occurred or any information that can help locate this error?

**Comment by laxpio** [comment]
i modify the code，deal NUll return，and now can not reproduce it.
original code：
org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
```
PositionImpl startReadOperationOnLedger(PositionImpl position) {
        long ledgerId = ledgers.ceilingKey(position.getLedgerId()); // ceilingKey return will null
        if (ledgerId != position.getLedgerId()) {
            // The ledger pointed by this position does not exist anymore. It was deleted because it was empty. We need
            // to skip on the next available ledger
            position = new PositionImpl(ledgerId, 0);
        }

        return position;
    }
```

**Comment by sijie** [comment]
I think the NPE was thrown when `ledgers.ceilingKey` return a NULL value. so a proper fix would be change `long ledgerId` to `Long ledgerId` and check if ledgerId is NULL.
