### ISSUE TITLE
Elasticsearch 5.x Sink connector incompatible

### ISSUE THREAD

**Issue by jm7647** [apache/pulsar#5690]
**Describe the bug**
Works with ES 7.x version
Fails with ES 5.x version

Didn't try other versions.

**To Reproduce**
1. Configure and run ES Sink
2. See error

{"error":{"root_cause":[{"type":"invalid_type_name_exception","reason":"Document mapping type name can't start with '_', found: [_doc]"}],"type":"invalid_type_name_exception","reason":"Document mapping type name can't start with '_', found: [_doc]"},"status":400}
                at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:705) ~[?:?]
                at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235) ~[?:?]
                at org.elasticsearch.client.RestClient.performRequest(RestClient.java:198) ~[?:?]
                at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:522) ~[?:?]
                at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:508) ~[?:?]
                at org.elasticsearch.client.RestHighLevelClient.index(RestHighLevelClient.java:348) ~[?:?]
                at org.apache.pulsar.io.elasticsearch.ElasticSearchSink.write(ElasticSearchSink.java:91) ~[?:?]
                at org.apache.pulsar.functions.instance.JavaInstanceRunnable.sendOutputMessage(JavaInstanceRunnable.java:435) ~[org.apache.pulsar-pulsar-functions-instance-2.4.1.jar:?]
                at org.apache.pulsar.functions.instance.JavaInstanceRunnable.processResult(JavaInstanceRunnable.java:418) ~[org.apache.pulsar-pulsar-functions-instance-2.4.1.jar:?]
                at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:272) [org.apache.pulsar-pulsar-functions-instance-2.4.1.jar:?]
                at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
        Caused by: org.elasticsearch.client.ResponseException: method [POST], host [http://135.91.35.218:9200], URI [/eventslist/_doc?timeout=1m], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"invalid_type_name_exception","reason":"Document mapping type name can't start with '_', found: [_doc]"}],"type":"invalid_type_name_exception","reason":"Document mapping type name can't start with '_', found: [_doc]"},"status":400}

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 16

**Additional context**

**Comment by aahmed-se** [comment]
this probably requires another version of the connector should be part of a large discussion of managing the growing list of connectors.

**Comment by jiazhai** [comment]
@tuteng to take a look

**Comment by tuteng** [comment]
I will find some time to test the relevant version. If there is any problem, I think we may need to provide special support. Such as developing a new connector for the corresponding version. If there are others who need this feature, please leave a message under this issue to let us know. Thank you.

**Comment by fantapsody** [comment]
I have done some research in documents and some change histories of Elasticsearch, the problem is fundamentally related to the long term "[removal of types](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html)"  project in Elasticsearch.

In brief, Elasticsearch supported multiple [types](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/_basic_concepts.html#_type) before 6.0. However, they found it to be a problematic abstraction, and decided to remove it gradually. The road map is to support only a single type start from 6.0, with the default type name set to be "_doc" since [6.2](https://github.com/elastic/elasticsearch/pull/27816), and to support the type name "_doc" only(which will actually be considered as the name of the API endpoint rather than a type name) since 7.0, and finally remove the concept of type since 8.0, while "_doc" will be kept in the document APIs to make them backward compatible.

On the other hand, names with a leading underscore are generally considered as reserved for internally use in Elasticsearch, and are not allowed to be used in user provided names (index, field, type, ...). And "_doc" is a special type name added in 6.2 to make the transition to 7.0 smoother, so it will not be supported before version 6.2.

As a result, "_doc" is supported as the only type name since 7.0 while not supported before 6.2, it is likely not possible to specify a default type name without knowing the version of the destination cluster(In fact, we have changed the type name from "doc" to "_doc" to support 7.0 in https://github.com/apache/pulsar/pull/4322).

To fix the issue, we can provide a configuration "typeName" with the default value set to be "_doc", so it supports versions of Elasticsearch since 6.2 by default, and can also support the previous versions if users configure a valid type name. Auto detection of the version of the cluster is possible but may not be very valuable for current feature sets.

**Comment by jm7647** [comment]
agree, configuration "typeName" would be a perfect solution.
