### ISSUE TITLE
NPE when create message meta builder

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#5727]
**Describe the bug**
Here is the stack trace:
```
java.lang.NullPointerException
 at org.apache.pulsar.shade.io.netty.util.Recycler$DefaultHandle.access$1100(Recycler.java:201)
 at org.apache.pulsar.shade.io.netty.util.Recycler$Stack.pop(Recycler.java:517)
 at org.apache.pulsar.shade.io.netty.util.Recycler.get(Recycler.java:161)
 at org.apache.pulsar.common.api.proto.PulsarApi$MessageMetadata$Builder.create(PulsarApi.java:3762)
 at org.apache.pulsar.common.api.proto.PulsarApi$MessageMetadata$Builder.access$4700(PulsarApi.java:3738)
 at org.apache.pulsar.common.api.proto.PulsarApi$MessageMetadata.newBuilder(PulsarApi.java:3731)
 at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.<init>(TypedMessageBuilderImpl.java:49)
 at org.apache.pulsar.client.impl.ProducerBase.newMessage(ProducerBase.java:69)
 at com.zhaopin.boot.autoconfigure.pulsar.business.PulsarProducer.createMessage(PulsarProducer.java:269)
 at com.zhaopin.boot.autoconfigure.pulsar.business.PulsarProducer.send(PulsarProducer.java:82)
 at com.zhaopin.boot.autoconfigure.pulsar.business.PulsarProducer.send(PulsarProducer.java:60)
 at com.zhaopin.job.business.basic.JobBasicBusiness.modifyJob(JobBasicBusiness.java:717)
 at com.zhaopin.job.rpc.api.impl.JobBasicOperationServiceImpl.modifyJob(JobBasicOperationServiceImpl.java:84)
 at sun.reflect.GeneratedMethodAccessor1495.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at com.zhaopin.thrift.rpc.executor.DefaultThriftExecutor.doExecute(DefaultThriftExecutor.java:118)
 at com.zhaopin.thrift.rpc.executor.DefaultThriftExecutor$1.run(DefaultThriftExecutor.java:55)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)
```

**Additional context**
Pulsar client version:2.4.0

**Comment by jiazhai** [comment]
found a similar one: https://github.com/netty/netty/issues/9640

**Comment by codelipenghui** [comment]
The following demo can reproduce:

```
PulsarClient client = PulsarClient.builder().serviceUrl("pulsar://127.0.0.1:6650").build();
        Producer<byte[]> producer = client.newProducer().topic("test").create();
        TypedMessageBuilder<byte[]> messageBuilder = producer.newMessage();
        for (int i = 0; i < 1000; i++) {
            messageBuilder.key(i + "").value(new byte[128]).sendAsync();
        }
```
It's better to add check for TypedMessageBuilder, because it can only send once.

**Comment by liangyuanpeng** [comment]
Test pass from pulsar client 2.6.0.

**Comment by tisonkun** [comment]
Closed as fixed.
