### ISSUE TITLE
version 2.4.2 doesn't support bookkeeper 4.10.0？pulsar can NOT startup successfully based on BK 4.10.0

### ISSUE THREAD

**Issue by frank-dkvan** [apache/pulsar#5813]
**Describe the bug**
version 2.4.2 doesn't support bookkeeper 4.10.0？pulsar can NOT startup successfully based on BK 4.10.0

**To Reproduce**
0.  download latest 2.4.2 source code from github
1. Maven build 2.4.2 source code with Bookkeeper 4.10.0
2. then start up  this pulsar
3. then exception shows
4. then pulsar shut down  

**Screenshots**
11:12:05.943 [main] ERROR org.apache.pulsar.PulsarStandaloneStarter - Failed to start pulsar service.
java.lang.AbstractMethodError: Method org/apache/pulsar/zookeeper/ZkBookieRackAffinityMapping.registerRackChangeListener(Lorg/apache/bookkeeper/client/ITopologyAwareEnsemblePlacementPolicy;)V is abstract
	at org.apache.pulsar.zookeeper.ZkBookieRackAffinityMapping.registerRackChangeListener(ZkBookieRackAffinityMapping.java) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.4.2.jar:2.4.2]
	at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl.initialize(RackawareEnsemblePlacementPolicyImpl.java:263) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl.initialize(RackawareEnsemblePlacementPolicyImpl.java:79) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.client.BookKeeper.initializeEnsemblePlacementPolicy(BookKeeper.java:562) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.client.BookKeeper.<init>(BookKeeper.java:493) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.client.BookKeeper$Builder.build(BookKeeper.java:296) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.pulsar.broker.BookKeeperClientFactoryImpl.create(BookKeeperClientFactoryImpl.java:69) ~[org.apache.pulsar-pulsar-broker-2.4.2.jar:2.4.2]
	at org.apache.pulsar.broker.ManagedLedgerClientFactory.<init>(ManagedLedgerClientFactory.java:61) ~[org.apache.pulsar-pulsar-broker-2.4.2.jar:2.4.2]
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:369) ~[org.apache.pulsar-pulsar-broker-2.4.2.jar:2.4.2]
	at org.apache.pulsar.PulsarStandalone.start(PulsarStandalone.java:327) ~[org.apache.pulsar-pulsar-broker-2.4.2.jar:2.4.2]
	at org.apache.pulsar.PulsarStandaloneStarter.main(PulsarStandaloneStarter.java:121) [org.apache.pulsar-pulsar-broker-2.4.2.jar:2.4.2]
11:12:05.966 [ProcessThread(sid:0 cport:2181):] INFO  org.apache.zookeeper.server.PrepRequestProcessor - Processed session termination for sessionid: 0x10000014552000a
11:12:05.967 [pulsar-ordered-OrderedExecutor-6-0-EventThread] INFO  org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x10000014552000a
11:12:05.967 [Thread-1] INFO  org.apache.zookeeper.ZooKeeper - Session: 0x10000014552000a closed
11:12:05.968 [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] INFO  org.apache.zookeeper.server.NIOServerCnxn - Closed socket connection for client /127.0.0.1:49238 which had sessionid 0x10000014552000a
11:12:05.970 [ProcessThread(sid:0 cport:2181):] INFO  org.apache.zookeeper.server.PrepRequestProcessor - Processed session termination for sessionid: 0x100000145520009
11:12:05.971 [Thread-1] INFO  org.apache.zookeeper.ZooKeeper - Session: 0x100000145520009 closed
11:12:05.971 [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] INFO  org.apache.zookeeper.server.NIOServerCnxn - Closed socket connection for client /127.0.0.1:49235 which had sessionid 0x100000145520009
11:12:05.971 [pulsar-ordered-OrderedExecutor-2-0-EventThread] INFO  org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x100000145520009
11:12:05.977 [Curator-LeaderSelector-0] WARN  org.apache.bookkeeper.stream.storage.impl.cluster.ClusterControllerLeaderImpl - Controller leader is interrupted, giving up leadership
11:12:05.981 [Thread-1] INFO  org.apache.bookkeeper.stream.storage.impl.sc.ZkStorageContainerManager - Stopping storage container (0)
11:12:05.984 [Thread-1] INFO  org.apache.bookkeeper.stream.storage.impl.sc.StorageContainerRegistryImpl - Unregistered StorageContainer ('0').
11:12:05.984 [Thread-1] INFO  org.apache.bookkeeper.stream.storage.impl.sc.StorageContainerImpl - Stopping storage container (0) ...
11:12:05.988 [Thread-1] INFO  org.apache.bookkeeper.stream.storage.impl.store.MVCCStoreFactoryImpl - Closing 000000000000000000/000000000000000001/000000000000000000 of sc 0
11:12:05.989 [ProcessThread(sid:0 cport:2181):] INFO  org.apache.zookeeper.server.PrepRequestProcessor - Got user-level KeeperException when processing sessionid:0x100000145520004 type:delete cxid:0xc zxid:0x12b txntype:-1 reqpath:n/a Error Path:/stream/controller/_c_2ef4cee5-2a4d-44b4-8365-be83146e7103-lock-0000000003 Error:KeeperErrorCode = NoNode for /stream/controller/_c_2ef4cee5-2a4d-44b4-8365-be83146e7103-lock-0000000003
11:12:05.985 [Curator-LeaderSelector-0] ERROR org.apache.curator.framework.recipes.leader.LeaderSelector - The leader threw an exception
java.lang.InterruptedException: null
	at java.lang.Object.wait(Native Method) ~[?:1.8.0_211]
	at java.lang.Object.wait(Object.java:502) ~[?:1.8.0_211]
	at org.apache.zookeeper.ClientCnxn.submitRequest(ClientCnxn.java:1411) ~[org.apache.pulsar-pulsar-zookeeper-2.4.2.jar:2.4.2]
	at org.apache.zookeeper.ZooKeeper.delete(ZooKeeper.java:880) ~[org.apache.pulsar-pulsar-zookeeper-2.4.2.jar:2.4.2]
	at org.apache.curator.framework.imps.DeleteBuilderImpl$5.call(DeleteBuilderImpl.java:274) ~[org.apache.curator-curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.DeleteBuilderImpl$5.call(DeleteBuilderImpl.java:268) ~[org.apache.curator-curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.connection.StandardConnectionHandlingPolicy.callWithRetry(StandardConnectionHandlingPolicy.java:64) ~[org.apache.curator-curator-client-4.0.1.jar:?]
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:100) ~[org.apache.curator-curator-client-4.0.1.jar:?]
	at org.apache.curator.framework.imps.DeleteBuilderImpl.pathInForeground(DeleteBuilderImpl.java:265) ~[org.apache.curator-curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:249) ~[org.apache.curator-curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:34) ~[org.apache.curator-curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.recipes.locks.LockInternals.deleteOurPath(LockInternals.java:347) ~[org.apache.curator-curator-recipes-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.recipes.locks.LockInternals.releaseLock(LockInternals.java:124) ~[org.apache.curator-curator-recipes-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.recipes.locks.InterProcessMutex.release(InterProcessMutex.java:154) ~[org.apache.curator-curator-recipes-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.recipes.leader.LeaderSelector.doWork(LeaderSelector.java:449) [org.apache.curator-curator-recipes-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.recipes.leader.LeaderSelector.doWorkLoop(LeaderSelector.java:466) [org.apache.curator-curator-recipes-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.recipes.leader.LeaderSelector.access$100(LeaderSelector.java:65) [org.apache.curator-curator-recipes-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:246) [org.apache.curator-curator-recipes-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:240) [org.apache.curator-curator-recipes-4.0.1.jar:4.0.1]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_211]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
11:12:05.990 [io-write-scheduler-OrderedScheduler-1-0] INFO  org.apache.bookkeeper.statelib.impl.journal.AbstractStateStoreWithJournal - closing async state store 000000000000000000/000000000000000001/000000000000000000

![image](https://user-images.githubusercontent.com/17067653/70368262-6509b800-18e3-11ea-8414-2b1201e6f28e.png)

**Comment by wolfstudy** [comment]
> version 2.4.2 doesn't support bookkeeper 4.10.0？pulsar can NOT startup successfully based on BK 4.10.0

@frank-dkvan Yes, version 2.4.2 is just a bug fix for version 2.4.0. To ensure compatibility, we should not support any component version changes in version 2.4.2, including bk.

In version 2.5.0, it will support bk 4.10.0.

**Comment by frank-dkvan** [comment]
> > version 2.4.2 doesn't support bookkeeper 4.10.0？pulsar can NOT startup successfully based on BK 4.10.0
> 
> @frank-dkvan Yes, version 2.4.2 is just a bug fix for version 2.4.0. To ensure compatibility, we should not support any component version changes in version 2.4.2, including bk.
> 
> In version 2.5.0, it will support bk 4.10.0.

by the way, when will the version 2.5.0 get released? :-)

**Comment by sijie** [comment]
@frank-dkvan we will start releasing 2.5.0 next week.

**Comment by jiazhai** [comment]
@frank-dkvan Seems this has a clear answer, would like to close this issue. Please feel free to re-open it if needed.
