### ISSUE TITLE
website failed to build due to "Invalid code tab markdown"

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#5816]
**Describe the bug**

The website fails to build because there is an "invalid code tab markdown" in `website/translated_docs/zh-CN/version-2.4.2/functions-develop.md`

```
Error: Invalid code tab markdown
    at forEach (/pulsar/site2/website/node_modules/docusaurus/lib/core/Doc.js:104:15)
    at Array.forEach (<anonymous>)
    at splitTabsToTitleAndContent (/pulsar/site2/website/node_modules/docusaurus/lib/core/Doc.js:30:9)
    at replace (/pulsar/site2/website/node_modules/docusaurus/lib/core/Doc.js:190:14)
    at String.replace (<anonymous>)
    at Doc.renderContent (/pulsar/site2/website/node_modules/docusaurus/lib/core/Doc.js:160:20)
    at Doc.render (/pulsar/site2/website/node_modules/docusaurus/lib/core/Doc.js:247:32)
    at processChild (/pulsar/site2/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:3293:18)
    at resolve (/pulsar/site2/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:3124:5)
    at ReactDOMServerRenderer.render (/pulsar/site2/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:3598:22)
error Command failed with exit code 1.
```

**Additional context**

It seems that when crowdin generates the translated markdown file, some code tabs (e.g. `<!--DOCUSAURUS_CODE_TABS-->`, `<!--Java-->`) are removed.

**Comment by jiazhai** [comment]
Thanks @sijie for provided a work around in #5817.

**Comment by Jennifer88huang** [comment]
Do not close this issue currently. #5817 hasn't addressed the root cause. 
The language specific tab works well in v2.4.1. However, it does not work well in v2.4.2.

**Comment by sijie** [comment]
@Jennifer88huang just one though, I think this issue might be related to the duplicated string setting in crowdin. We might try to disable that setting.

**Comment by Jennifer88huang** [comment]
@sijie I'm not sure whether this issue is related to the duplicated string setting in Crowdin, we can try to disable it before building the website for a new release.

**Comment by tuteng** [comment]
> @sijie I'm not sure whether this issue is related to the duplicated string setting in Crowdin, we can try to disable it before building the website for a new release.

After you close it, you can download a new document and test it locally. @Jennifer88huang

**Comment by Jennifer88huang** [comment]
I've disabled the duplicated string in the setting, we can build and test it again.
![image](https://user-images.githubusercontent.com/47805623/72679698-9d103780-3aec-11ea-97fb-7d35c549ff1b.png)

**Comment by Anonymitaet** [comment]
Fixed. Thanks for your reminder @signormercurio
