### ISSUE TITLE
NullPointerException throwed by Debezium Connector  when  a row deleted

### ISSUE THREAD

**Issue by xiemeilong** [apache/pulsar#5832]
**Describe the bug**
Debezium Connector will throw NullPointerException and shutdown  when a row is deleted anytime.

**To Reproduce**
1. run a new Debezium Connector  pulsar io instance
2. delete a row in mysql
3. NullPointerException is throwed by Connector  

**Expected behavior**
delete transaction in bin log is write into pulsar normally

**Screenshots**

**Desktop (please complete the following information):**
 - k8s
-  apachepulsar/pulsar-all:2.4.2

**Additional context**
log
```
02:04:28.729 [iot/pipe/iot-mysql-log-test1-source-0] INFO  org.apache.pulsar.functions.instance.JavaInstanceRunnable - Encountered exception in sink write: 
java.lang.NullPointerException: null
        at org.apache.pulsar.common.schema.KeyValue.encode(KeyValue.java:101) ~[java-instance.jar:?]
        at org.apache.pulsar.client.impl.schema.KeyValueSchema.encode(KeyValueSchema.java:128) ~[org.apache.pulsar-pulsar-client-original-2.4.2.jar:2.4.2]
        at org.apache.pulsar.client.impl.schema.KeyValueSchema.encode(KeyValueSchema.java:37) ~[org.apache.pulsar-pulsar-client-original-2.4.2.jar:2.4.2]
        at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.value(TypedMessageBuilderImpl.java:116) ~[org.apache.pulsar-pulsar-client-original-2.4.2.jar:2.4.2]
        at org.apache.pulsar.functions.sink.PulsarSink.write(PulsarSink.java:282) ~[org.apache.pulsar-pulsar-functions-instance-2.4.2.jar:2.4.2]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.sendOutputMessage(JavaInstanceRunnable.java:445) [org.apache.pulsar-pulsar-functions-instance-2.4.2.jar:?]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.processResult(JavaInstanceRunnable.java:428) [org.apache.pulsar-pulsar-functions-instance-2.4.2.jar:?]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:282) [org.apache.pulsar-pulsar-functions-instance-2.4.2.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
02:04:28.735 [iot/pipe/iot-mysql-log-test1-source-0] WARN  org.apache.pulsar.functions.instance.JavaInstanceRunnable - Failed to process result of message org.apache.pulsar.io.kafka.connect.KafkaConnectSource$KafkaSourceRecord@6b986037
java.lang.RuntimeException: java.lang.NullPointerException
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.sendOutputMessage(JavaInstanceRunnable.java:449) ~[org.apache.pulsar-pulsar-functions-instance-2.4.2.jar:?]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.processResult(JavaInstanceRunnable.java:428) ~[org.apache.pulsar-pulsar-functions-instance-2.4.2.jar:?]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:282) [org.apache.pulsar-pulsar-functions-instance-2.4.2.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.NullPointerException
        at org.apache.pulsar.common.schema.KeyValue.encode(KeyValue.java:101) ~[java-instance.jar:?]
        at org.apache.pulsar.client.impl.schema.KeyValueSchema.encode(KeyValueSchema.java:128) ~[org.apache.pulsar-pulsar-client-original-2.4.2.jar:2.4.2]
        at org.apache.pulsar.client.impl.schema.KeyValueSchema.encode(KeyValueSchema.java:37) ~[org.apache.pulsar-pulsar-client-original-2.4.2.jar:2.4.2]
        at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.value(TypedMessageBuilderImpl.java:116) ~[org.apache.pulsar-pulsar-client-original-2.4.2.jar:2.4.2]
        at org.apache.pulsar.functions.sink.PulsarSink.write(PulsarSink.java:282) ~[org.apache.pulsar-pulsar-functions-instance-2.4.2.jar:2.4.2]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.sendOutputMessage(JavaInstanceRunnable.java:445) ~[org.apache.pulsar-pulsar-functions-instance-2.4.2.jar:?]
        ... 3 more
02:04:28.742 [iot/pipe/iot-mysql-log-test1-source-0] INFO  org.apache.pulsar.functions.instance.JavaInstanceRunnable - Encountered exception in source read: 
java.util.concurrent.ExecutionException: java.lang.Exception: Sink Error
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_232]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908) ~[?:1.8.0_232]
        at org.apache.pulsar.io.kafka.connect.KafkaConnectSource.read(KafkaConnectSource.java:148) ~[pulsar-io-kafka-connect-adaptor-2.4.2.jar:?]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.readInput(JavaInstanceRunnable.java:461) [org.apache.pulsar-pulsar-functions-instance-2.4.2.jar:?]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:246) [org.apache.pulsar-pulsar-functions-instance-2.4.2.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.Exception: Sink Error
        at org.apache.pulsar.io.kafka.connect.KafkaConnectSource$KafkaSourceRecord.fail(KafkaConnectSource.java:269) ~[pulsar-io-kafka-connect-adaptor-2.4.2.jar:?]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:285) ~[?:?]
        ... 1 more
02:04:28.743 [iot/pipe/iot-mysql-log-test1-source-0] ERROR org.apache.pulsar.functions.instance.JavaInstanceRunnable - [iot/pipe/iot-mysql-log-test1-source:0] Uncaught exception in Java Instance
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.Exception: Sink Error
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.readInput(JavaInstanceRunnable.java:465) ~[org.apache.pulsar-pulsar-functions-instance-2.4.2.jar:?]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:246) [org.apache.pulsar-pulsar-functions-instance-2.4.2.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.util.concurrent.ExecutionException: java.lang.Exception: Sink Error
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_232]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908) ~[?:1.8.0_232]
        at org.apache.pulsar.io.kafka.connect.KafkaConnectSource.read(KafkaConnectSource.java:148) ~[?:?]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.readInput(JavaInstanceRunnable.java:461) ~[org.apache.pulsar-pulsar-functions-instance-2.4.2.jar:?]
        ... 2 more
Caused by: java.lang.Exception: Sink Error
        at org.apache.pulsar.io.kafka.connect.KafkaConnectSource$KafkaSourceRecord.fail(KafkaConnectSource.java:269) ~[?:?]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:285) ~[org.apache.pulsar-pulsar-functions-instance-2.4.2.jar:?]
        ... 1 more
```

**Comment by jiazhai** [comment]
Thanks @xiemeilong for help reporting this issue. This is a special case that we should fix. And seems it is clear that we need to fix the Null value in `KeyValue.encode(KeyValue.java:101)`.  

@tuteng  to help take a look.
