### ISSUE TITLE
Biscuit customs authentication and authorization providers usages.

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar#5841]
**Describe the bug**
pulsar-client java invalid connection state using custom authentication & authorization provider:

Here are the breakpoints and their results:
[
![1](https://user-images.githubusercontent.com/7518245/70654540-d2587880-1c56-11ea-8251-520bdbc1a90b.png)
](url)

![Screenshot from 2019-12-11 20-41-53](https://user-images.githubusercontent.com/7518245/70654549-d5ebff80-1c56-11ea-938e-9823899a76ac.png)

and throws:

```
19:55:25.068 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.ConnectionPool - [[id: 0x88e0c178, L:/127.0.0.1:38446 - R:127.0.0.1/127.0.0.1:22022]] Connected to server
19:55:25.120 [pulsar-client-io-1-1] DEBUG org.apache.pulsar.common.protocol.PulsarHandler - [[id: 0x88e0c178, L:/127.0.0.1:38446 - R:127.0.0.1/127.0.0.1:22022]] Scheduling keep-alive task every 30 s
19:55:25.123 [pulsar-client-io-1-1] DEBUG org.apache.pulsar.client.impl.ClientCnx - [id: 0x88e0c178, L:/127.0.0.1:38446 - R:127.0.0.1/127.0.0.1:22022] Connected to broker
19:55:25.143 [pulsar-client-io-1-1] DEBUG org.apache.pulsar.client.impl.ClientCnx - Complete: true
19:55:25.163 [pulsar-client-io-1-1] DEBUG org.apache.pulsar.common.protocol.PulsarDecoder - [127.0.0.1/127.0.0.1:22022] Received cmd ERROR
20:34:55.905 [pulsar-client-io-1-1] WARN  org.apache.pulsar.client.impl.ClientCnx - [127.0.0.1/127.0.0.1:22022] Got exception IllegalArgumentException : null
java.lang.IllegalArgumentException: null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108) ~[guava-21.0.jar:?]
	at org.apache.pulsar.client.impl.ClientCnx.handleError(ClientCnx.java:588) ~[pulsar-client-original-2.4.1.jar:2.4.1]
	at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:154) ~[pulsar-common-2.4.1.jar:2.4.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) [netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) [netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433) [netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330) [netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) [netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.32.Final.jar:4.1.32.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

**To Reproduce**
1. `git clone git@github.com:CleverCloud/biscuit-pulsar.git`
2. `mvn install` # it's using hadoop-unit which boot a pulsar
3. `BiscuitPulsarIntegrationTest.java` should create a producer but it throws the quoted exception.

**Expected behavior**
Create producer and produce messages using biscuit authentication & authorization.

**Additional context**
To debug pulsar-client you probably needs to remove the hadoop-unit usage and use standalone. To do it you just need to boot a pulsar standalone and replace the needed configuration on pulsar client creation in `BiscuitPulsarIntegrationTest.java` and provide the built biscuit-plugin like:

```
# Enable authentication
authenticationEnabled=true

# Autentication provider name list, which is comma separated list of class names
authenticationProviders=com.clevercloud.biscuitpulsar.AuthenticationProviderBiscuit

# Enforce authorization
authorizationEnabled=true

# Authorization provider fully qualified class-name
authorizationProvider=com.clevercloud.biscuitpulsar.AuthorizationProviderBiscuit

# Biscuit root signing key
biscuitRootKey=da905388864659eb785877a319fbc42c48e2f8a40af0c5baea0ef8ff7c795253 #random string

superUserRoles=admin
```

**Comment by zymap** [comment]
Hi @KannarFr, I have reproduced your problem on my laptop.

And I got the same error as you. At the same time, the server was throwing an exception:
```
13:59:27.132 [pulsar-io-35-1] INFO  com.clevercloud.biscuitpulsar.AuthenticationProviderBiscuit - Biscuit to parse: Ck0IABIFdG9waWMSB3Byb2R1Y2UaOQo3CAQSBAgAEAASBAgAEAcSCggDKgZwdWJsaWMSCwgDKgdkZWZhdWx0EggIAyoEdGVzdBIECAAQCBogEOKv5aNjujWb9Ry9wgKtXWbAdsDvyK0PeJplco-DQgUiRAogSI-HOSHn-Z16ptBB8Xbe8szZGi-05FObmBx1qJecYXMSIEAdgMiKTsxqGpeLgeJDghISDxu25CipbP6v1bxoohgM
13:59:27.195 [pulsar-io-35-1] INFO  com.clevercloud.biscuitpulsar.AuthenticationProviderBiscuit - Deserialized biscuit
13:59:27.198 [pulsar-io-35-1] WARN  org.apache.pulsar.broker.service.ServerCnx - [/127.0.0.1:51685] Unable to authenticate
javax.naming.AuthenticationException: This biscuit was not generated with the expected root key
	at com.clevercloud.biscuitpulsar.AuthenticationProviderBiscuit.parseBiscuit(AuthenticationProviderBiscuit.java:104) ~[biscuit-pulsar-1.0-SNAPSHOT.jar:?]
	at com.clevercloud.biscuitpulsar.AuthenticationProviderBiscuit.authenticate(AuthenticationProviderBiscuit.java:61) ~[biscuit-pulsar-1.0-SNAPSHOT.jar:?]
	at org.apache.pulsar.broker.authentication.OneStageAuthenticationState.<init>(OneStageAuthenticationState.java:46) ~[org.apache.pulsar-pulsar-broker-common-2.4.1.jar:2.4.1]
	at org.apache.pulsar.broker.authentication.AuthenticationProvider.newAuthState(AuthenticationProvider.java:76) ~[org.apache.pulsar-pulsar-broker-common-2.4.1.jar:2.4.1]
	at org.apache.pulsar.broker.service.ServerCnx.handleConnect(ServerCnx.java:549) [org.apache.pulsar-pulsar-broker-2.4.1.jar:2.4.1]
	at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:143) [org.apache.pulsar-pulsar-common-2.4.1.jar:2.4.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:591) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:508) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
13:59:27.214 [pulsar-io-35-1] INFO  org.apache.pulsar.broker.service.ServerCnx - Closed connection from /127.0.0.1:51685
```

That looks like something error when authenticating the client.  

Is there any association between the biscuitRootKey and the pulsar client?  

```
byte[] seed = {0, 0, 0, 0};
    SecureRandom rng = new SecureRandom(seed);
    KeyPair root = new KeyPair(rng);

    LOGGER.info("ROOT PUBLICKEY");
    LOGGER.info(hex(root.public_key().key.compress().toByteArray()));

    SymbolTable symbols = Biscuit.default_symbol_table();

    Block authority_builder = new Block(0, symbols);
    authority_builder.add_fact(fact("right", Arrays.asList(s("authority"), s("topic"), string("public"), string("default"), string("test"), s("produce"))));

    Biscuit b = Biscuit.make(rng, root, Biscuit.default_symbol_table(), authority_builder.build()).get();
```
It seems we always create a new root to connect to the broker. I am not sure if this is the right process?

**Comment by zymap** [comment]
@KannarFr, The null represents the IllegalArgumentException has no exception message. You can dive into the `checkArgument`, it will throw an IllegalAgumentException. This issue does not impact your authentication and authorization implements.
 
I will fix this.

Thank you.

**Comment by KannarFr** [comment]
@zymap Thanks for your work sorry, I'm using hadoop-unit which is not logging the exception, we are working on a fix with its maintainer.
