### ISSUE TITLE
ConcurrentModificationException in ModularLoadManagerImpl

### ISSUE THREAD

**Issue by jerrypeng** [apache/pulsar#5952]
**Describe the bug**

Saw the following exception thrown in broker:

```
01:47:04.243 [pulsar-load-manager-6-1] WARN  org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerImpl - Error writing broker data on ZooKeeper: {}
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_212]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1479) ~[?:1.8.0_212]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1477) ~[?:1.8.0_212]
        at org.apache.pulsar.policies.data.loadbalancer.LocalBrokerData.updateBundleData(LocalBrokerData.java:175) ~[org.apache.pulsar-pulsar-common-2.4.1-streamlio-6.jar:2.4.1-streamlio-6]
        at org.apache.pulsar.policies.data.loadbalancer.LocalBrokerData.update(LocalBrokerData.java:133) ~[org.apache.pulsar-pulsar-common-2.4.1-streamlio-6.jar:2.4.1-streamlio-6]
        at org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerImpl.writeBrokerDataOnZooKeeper(ModularLoadManagerImpl.java:876) [org.apache.pulsar-pulsar-broker-2.4.1-streamlio-6.jar:2.4.1-streamlio-6]
        at org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerWrapper.writeLoadReportOnZookeeper(ModularLoadManagerWrapper.java:120) [org.apache.pulsar-pulsar-broker-2.4.1-streamlio-6.jar:2.4.1-streamlio-6]
        at org.apache.pulsar.broker.loadbalance.LoadReportUpdaterTask.run(LoadReportUpdaterTask.java:41) [org.apache.pulsar-pulsar-broker-2.4.1-streamlio-6.jar:2.4.1-streamlio-6]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_212]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_212]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
```

**To Reproduce**

Not sure

**Comment by ntysdd** [comment]
Possibly a threading problem.

**Comment by ntysdd** [comment]
Possible duplicate #5673

**Comment by jiazhai** [comment]
Thanks @ntysdd and @jerrypeng.  would like to close this issue, and use #5673 to track this issue.
