### ISSUE TITLE
[Github actions]V1_ProducerConsumerTest test error

### ISSUE THREAD

**Issue by tuteng** [apache/pulsar#6013]
**Describe the bug**

```
2020-01-07T14:24:18.7921463Z [INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 48.692 s - in org.apache.pulsar.client.impl.TopicsConsumerImplTest
2020-01-07T14:51:00.3882609Z [ERROR] Tests run: 69, Failures: 36, Errors: 0, Skipped: 26, Time elapsed: 1,956.429 s <<< FAILURE! - in org.apache.pulsar.client.api.v1.V1_ProducerConsumerTest
2020-01-07T14:51:00.3886754Z [ERROR] testBackoffAndReconnect(org.apache.pulsar.client.api.v1.V1_ProducerConsumerTest)  Time elapsed: 32.624 s  <<< FAILURE!
2020-01-07T14:51:00.3892043Z org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException: org.asynchttpclient.handler.MaxRedirectException: Maximum redirect reached: 5
2020-01-07T14:51:00.3894918Z    at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:717)
2020-01-07T14:51:00.3897469Z    at org.apache.pulsar.client.impl.ConsumerBuilderImpl.subscribe(ConsumerBuilderImpl.java:97)
2020-01-07T14:51:00.3900829Z    at org.apache.pulsar.client.api.v1.V1_ProducerConsumerTest.testBackoffAndReconnect(V1_ProducerConsumerTest.java:255)
2020-01-07T14:51:00.3902908Z    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-01-07T14:51:00.3905268Z    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-01-07T14:51:00.3907820Z    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-01-07T14:51:00.3909730Z    at java.lang.reflect.Method.invoke(Method.java:498)
2020-01-07T14:51:00.3912758Z    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
2020-01-07T14:51:00.3915148Z    at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
2020-01-07T14:51:00.3917740Z    at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
2020-01-07T14:51:00.3920065Z    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020-01-07T14:51:00.3922533Z    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-01-07T14:51:00.3924992Z    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-01-07T14:51:00.3927353Z    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-01-07T14:51:00.3929083Z    at java.lang.Thread.run(Thread.java:748)
2020-01-07T14:51:00.3933523Z Caused by: java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException: org.asynchttpclient.handler.MaxRedirectException: Maximum redirect reached: 5
2020-01-07T14:51:00.3936162Z    at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
2020-01-07T14:51:00.3938425Z    at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
2020-01-07T14:51:00.3940931Z    at org.apache.pulsar.client.impl.ConsumerBuilderImpl.subscribe(ConsumerBuilderImpl.java:95)
2020-01-07T14:51:00.3942323Z    ... 13 more
2020-01-07T14:51:00.3945832Z Caused by: org.apache.pulsar.client.api.PulsarClientException: org.asynchttpclient.handler.MaxRedirectException: Maximum redirect reached: 5
2020-01-07T14:51:00.3948172Z    at org.apache.pulsar.client.impl.HttpClient.lambda$null$1(HttpClient.java:175)
2020-01-07T14:51:00.3950608Z    at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
2020-01-07T14:51:00.3953473Z    at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
2020-01-07T14:51:00.3956172Z    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
2020-01-07T14:51:00.3958752Z    at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
2020-01-07T14:51:00.3961152Z    at org.asynchttpclient.netty.NettyResponseFuture.abort(NettyResponseFuture.java:273)
2020-01-07T14:51:00.3963729Z    at org.asynchttpclient.netty.request.NettyRequestSender.abort(NettyRequestSender.java:473)
2020-01-07T14:51:00.3966530Z    at org.asynchttpclient.netty.handler.HttpHandler.readFailed(HttpHandler.java:160)
2020-01-07T14:51:00.3968905Z    at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:153)
2020-01-07T14:51:00.3971757Z    at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78)
2020-01-07T14:51:00.3974636Z    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
2020-01-07T14:51:00.3977780Z    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
2020-01-07T14:51:00.3980595Z    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
2020-01-07T14:51:00.3983324Z    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
2020-01-07T14:51:00.3989161Z    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
2020-01-07T14:51:00.3990611Z    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
2020-01-07T14:51:00.4002571Z    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
2020-01-07T14:51:00.4046814Z    at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
2020-01-07T14:51:00.4047056Z    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
2020-01-07T14:51:00.4047204Z    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
2020-01-07T14:51:00.4047315Z    at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
2020-01-07T14:51:00.4047767Z    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
2020-01-07T14:51:00.4047942Z    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
2020-01-07T14:51:00.4048103Z    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
2020-01-07T14:51:00.4048260Z    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
2020-01-07T14:51:00.4048408Z    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by tisonkun** [comment]
Closed as stale. You can report a flaky test with the corresponding issue form if it's still relevant.
