### ISSUE TITLE
flink pulsar producer can not connect to cluster when enable Token Authentication

### ISSUE THREAD

**Issue by saosir** [apache/pulsar#6022]
**Describe the bug**
When Token Authentication is enabled in Pulsar 2.4.1 I start Pulsar standalone cluster,  `org.apache.flink.streaming.connectors.pulsar.FlinkPulsarProducer` can not startup. However it work well if disable pulsar token authentication.

**To Reproduce**
1. Startup a standalone cluster with Token Authentication config:

```
# Enable authentication
authenticationEnabled=true

# Autentication provider name list, which is comma separated list of class names
authenticationProviders=org.apache.pulsar.broker.authentication.AuthenticationProviderToken

# Enforce authorization
authorizationEnabled=true

tokenSecretKey=file:///root/secret.key

# Authorization provider fully qualified class-name
authorizationProvider=org.apache.pulsar.broker.authorization.PulsarAuthorizationProvider

# Allow wildcard matching in authorization
# (wildcard matching only applicable if wildcard-char:
# * presents at first or last position eg: *.pulsar.service, pulsar.service.*)
authorizationAllowWildcardsMatching=false

# Role names that are treated as "super-user", meaning they will be able to do all admin
# operations and publish/consume from all topics
superUserRoles=admin

# Authentication settings of the broker itself. Used when the broker connects to other brokers,
# either in same or other clusters
brokerClientAuthenticationPlugin=org.apache.pulsar.client.impl.auth.AuthenticationToken
brokerClientAuthenticationParameters=token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtZW5zaGVuIn0.w7nsT2GDGmHPd8DchqUDQH27xQ84xJp5dGKaOMsC7oU
```

2. Run flink job in local debug mode

```java
public class Test2 {
    public static void main(String[] args) throws Exception {

        // get the execution environment
        final StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();

        // get input data by connecting to the socket
        DataStream<String> text = env.socketTextStream("localhost", 9999, "\n");

        // parse the data, group it, window it, and aggregate the counts
        DataStream<WordWithCount> windowCounts = text
                .flatMap(new FlatMapFunction<String, WordWithCount>() {
                    @Override
                    public void flatMap(String value, Collector<WordWithCount> out) {
                        for (String word : value.split("\\s")) {
                            out.collect(new WordWithCount(word, 1L));
                        }
                    }
                })
                .keyBy("word")
                .timeWindow(Time.seconds(5), Time.seconds(1))
                .reduce(new ReduceFunction<WordWithCount>() {
                    @Override
                    public WordWithCount reduce(WordWithCount a, WordWithCount b) {
                        return new WordWithCount(a.word, a.count + b.count);
                    }
                });

        // print the results with a single thread, rather than in parallel
//        windowCounts.print().setParallelism(1);


        ClientConfigurationData clientConfigurationData = new ClientConfigurationData();
        clientConfigurationData.setServiceUrl("pulsar://devnet:6650");
        clientConfigurationData.setAuthentication(AuthenticationFactory.token("eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtZW5zaGVuIn0.w7nsT2GDGmHPd8DchqUDQH27xQ84xJp5dGKaOMsC7oU"));
        ProducerConfigurationData producerConfigurationData = new ProducerConfigurationData();
        producerConfigurationData.setTopicName("persistent://public/default/my-topic-flink");

        SinkFunction<WordWithCount> sink = new FlinkPulsarProducer<>(clientConfigurationData, producerConfigurationData,
                new JsonSerializationSchema<>(), null);

        windowCounts.addSink(sink);
        env.execute("Socket Window WordCount");
    }
    public static class WordWithCount {

        public String word;
        public long count;

        public WordWithCount() {}

        public WordWithCount(String word, long count) {
            this.word = word;
            this.count = count;
        }

        @Override
        public String toString() {
            return word + " : " + count;
        }
    }

```

3. See error

```
Exception in thread "main" org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
	at org.apache.flink.runtime.jobmaster.JobResult.toJobExecutionResult(JobResult.java:146)
	at org.apache.flink.runtime.minicluster.MiniCluster.executeJobBlocking(MiniCluster.java:627)
	at org.apache.flink.streaming.api.environment.LocalStreamEnvironment.execute(LocalStreamEnvironment.java:117)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.execute(StreamExecutionEnvironment.java:1507)
	at com.tencent.menshen.flink.Test2.main(Test2.java:64)
Caused by: java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException: Connection already closed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2070)
	at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarProducer.createProducer(FlinkPulsarProducer.java:191)
	at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarProducer.open(FlinkPulsarProducer.java:202)
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102)
	at org.apache.flink.streaming.api.operators.StreamSink.open(StreamSink.java:48)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.openAllOperators(StreamTask.java:529)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:393)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:705)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:530)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: org.apache.pulsar.client.api.PulsarClientException: Connection already closed
	at org.apache.pulsar.client.impl.ClientCnx.channelInactive(ClientCnx.java:221)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at org.apache.pulsar.shade.io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:390)
	at org.apache.pulsar.shade.io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:355)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at org.apache.pulsar.shade.io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at org.apache.pulsar.shade.io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:826)
	at org.apache.pulsar.shade.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:474)
	at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
	at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more

Process finished with exit code -1

```

**Expected behavior**
FlinkPulsarProducer startup success

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 14.04
- pulsar: 2.4.1
- flink client: 1.9.1(debug on window 10 with jetbrain idea)

**Additional context**
Debug flink job in local, I found that when flink invoke `FlinkPulsarProducer.createProducer`,  producer config `ClientConfigurationData.authentication` change to `AuthenticationDisabled`

**Comment by jiazhai** [comment]
@saosir ,  Not sure if it is related with the token config itself, or flink connector.
have you verified the auth config is right?  
e.g. change `config/client.conf` file to add the token, and use `bin/pulsar-client produce` to do a verify.

**Comment by saosir** [comment]
It is related with flink connector

In obove example set client auth token with

```        clientConfigurationData.setAuthentication(AuthenticationFactory.token("eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtZW5zaGVuIn0.w7nsT2GDGmHPd8DchqUDQH27xQ84xJp5dGKaOMsC7oU"));

```

but when flink job startup with obove example, the `clientConfigurationData.authentication` auto change to `AuthenticationDisabled`

**Comment by jiazhai** [comment]
@yijie to check if this is a known issue.

**Comment by sijie** [comment]
@saosir I would suggest not using 

```
clientConfigurationData.setAuthentication(AuthenticationFactory.token("eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtZW5zaGVuIn0.w7nsT2GDGmHPd8DchqUDQH27xQ84xJp5dGKaOMsC7oU"));
```

since the authentication object will not be serialized correctly. 

Use the client configuration data to pass in the token.

```
val confData = new ClientConfigurationData()
    confData.setAuthPluginClassName("org.apache.pulsar.client.impl.auth.AuthenticationToken")
    confData.setAuthParams("token:" + AUTH_TOKEN)

    val src: SourceFunction[String] =
      PulsarSourceBuilder
        .builder(new SimpleStringSchema())
        .pulsarAllClientConf(confData)
        .serviceUrl(SERVICE_URL)
        .topic(INPUT_TOPIC)
        .subscriptionName(SUBSCRIPTION_NAME)
        .build()
```

**Comment by saosir** [comment]
@sijie It works
But I think this way is not clear , because some people does not know the class `org.apache.pulsar.client.impl.auth.AuthenticationToken` exist

**Comment by sijie** [comment]
@saosir correct. we need to make AuthenticationToken serializable. Are you interested in contributing a fix for that?

**Comment by saosir** [comment]
I wrote source and sink based on the puslar flink connector in our project, but that is not very general. I hope to participate in the code development of pulsar in the next time.

**Comment by tisonkun** [comment]
Closed as workaround provided and no one worked on the suggested alternative.

BTW, @merlimat doesn't `Authentication` already implement `Serializable`?

**Comment by tisonkun** [comment]
Found https://github.com/apache/pulsar/pull/10574 that can be related.
