### ISSUE TITLE
"failed to load RocksDB jni library" 

### ISSUE THREAD

**Issue by Gray-Fullbuster** [apache/pulsar#6096]
When i start up bookie I meet this problem. Does anyone know how to solve this problem？help me please!

**Comment by sijie** [comment]
@Gray-Fullbuster 

1) what is your operating system?
2) what version of Pulsar are you using?

Besides that, I don't think that is a problem. It should be just a warning as it falls back to java code if the JNI library is not found.

**Comment by Gray-Fullbuster** [comment]
@sijie 
My operating system is Linux version 4.19.36-vhulk1905.1.0.h276.eulerosv2r8.aarch64 and Pulsar's veriosn is 2.4.2
I meet this problem When i start bookkeeper.Then bookie can't start up.The following is the error message：
[main] ERROR org.apache.bookkeeper.server.Main - Failed to build bookie server
java.io.IOException: Failed to load RocksDB JNI library 
		at org.apache.bookkeeper.bookie.storage.ldb.KeyValueStorageRocksDB.<init>(KeyValueStorageRocksDB.java:91) ~[org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.3-SNAPSHOT]
		at org.apache.bookkeeper.bookie.storage.ldb.KeyValueStorageRocksDB.<init>(KeyValueStorageRocksDB.java:83) ~[org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.3-SNAPSHOT]

**Comment by sijie** [comment]
Ah, what is the platform of the CPU?

**Comment by Gray-Fullbuster** [comment]
@sijie 
CPU's platform intel.Is this related to CPU？

**Comment by sijie** [comment]
It is a JNI library. So I am not sure why it fails to load it at your platform. Do you have the whole log file of the bookies?

**Comment by Gray-Fullbuster** [comment]
@sijie ok，this is all of bookies's log.
09:31:00.247 [main] INFO org.apache.bookkeeper.bookie.Bookie - Using ledger storage: org.apache.bookkeeper.bookie.storage.ldb.DbledgerStorage
09:31:00.249 [main] INFO org.apache.bookkeeper.bookie.storage.ldb.DbledgerStorage - Started Db Ledger Storage
09:31:00.249 [main] INFO org.apache.bookkeeper.bookie.storage.ldb.DbledgerStorage - - Number of directories: 12
09:31:00.249 [main] INFO org.apache.bookkeeper.bookie.storage.ldb.DbledgerStorage - - Write cache size: 1024 MB
09:31:00.249 [main] INFO org.apache.bookkeeper.bookie.storage.ldb.DbledgerStorage - - Read Cache: 1024MB
09:31:00.254 [main] INFO org.apache.bookkeeper.bookie.storage.ldb.DbledgerStorage - - Creating single directory db ledger storage on /srv/Bigdata/pulsar/data1/ledgers/current
09:31:00.364 [main] INFO org.apache.bookkeeper.proto.BookieNettyServer - Shutting down BookieNettyServer
09:31:00.402 [bookkeeper-tgt-refresh-thread] WARN org.apache.bookkeeper.sasl.TGTRefreshThread - TGT renewal thread has been interruputed and will exit.
09:31:00.402 [main] ORROR org.apache.bookkeeper.server.Main - Failed to build bookie server
java.io.IOException: Failed to load RocksDB JNI library
		at org.apache.bookkeeper.bookie.storage.ldb.KeyValueStorageRocksDB.<init>(KeyValueStorageRocksDB.java:91) ~[org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.3-SNAPSHOT]
		at org.apache.bookkeeper.bookie.storage.ldb.KeyValueStorageRocksDB.<init>(KeyValueStorageRocksDB.java:83) ~[org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.3-SNAPSHOT]
		at org.apache.bookkeeper.bookie.storage.ldb.KeyValueStorageRocksDB.lambda$static$0(KeyValueStorageRocksDB.java:58) ~[org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.3-SNAPSHOT]
		at org.apache.bookkeeper.bookie.storage.ldb.LedgerMetadataIndex.<init>(LedgerMetadataIndex.java:69) ~[org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.3-SNAPSHOT]
		at org.apache.bookkeeper.bookie.storage.ldb.SingleDirectoryDbLedgerStorage.<init>(SingleDirectoryDbLedgerStorage.java:160) ~[org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.3-SNAPSHOT]
		at org.apache.bookkeeper.bookie.storage.ldb.DbledgerStorage.newSingleDirectoryDbLedgerStorage(DbledgerStorage.java:148) ~[org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.3-SNAPSHOT]
		at org.apache.bookkeeper.bookie.storage.ldb.DbledgerStorage.initalize(DbledgerStorage.java:128)

**Comment by harleyalbert** [comment]
hello @Gray-Fullbuster I have the same problem,  I see you close this problem please share. i'm stuck this issue thanks

**Comment by Saner-Lee** [comment]
@Gray-Fullbuster hey gays, I have just sloved it by unstalling the old version java and installing the java8.
