### ISSUE TITLE
Itermittent test failure in ReplicatorTest.testResumptionAfterBacklogRelaxed

### ISSUE THREAD

**Issue by merlimat** [apache/pulsar#614]
Test logs at:
https://builds.apache.org/job/pulsar-pull-request/org.apache.pulsar$pulsar-broker/15/testReport/junit/org.apache.pulsar.broker.service/ReplicatorTest/testResumptionAfterBacklogRelaxed/

```
868617 [pulsar-io-23669-14] ERROR org.apache.pulsar.broker.service.persistent.PersistentReplicator - [persistent://pulsar/global/ns1/producer_exception][r1 -> r2] Error producing on remote broker
org.apache.pulsar.client.api.PulsarClientException$ProducerBlockedQuotaExceededException: Could not send pending messages as backlog exceeded
	at org.apache.pulsar.client.impl.ProducerImpl.lambda$connectionOpened$6(ProducerImpl.java:781)
	at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870)
	at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at org.apache.pulsar.client.impl.ClientCnx.handleError(ClientCnx.java:356)
```

**Comment by merlimat** [comment]
Happened again with better logs in https://builds.apache.org/job/pulsar-pull-request/org.apache.pulsar$pulsar-broker/69/testReport/junit/org.apache.pulsar.broker.service/ReplicatorTest/testResumptionAfterBacklogRelaxed/

```
org.apache.pulsar.client.api.PulsarClientException$TimeoutException: Could not send message to broker within given timeout
```

**Comment by sijie** [comment]
This duplicates #788
