### ISSUE TITLE
[docs] docusaurus in dev crashes

### ISSUE THREAD

**Issue by EugenDueck** [apache/pulsar#6149]
**Bug description**
When running docusaurus locally, as described in pulsar/site2/README.md, the server will run and serve for a while, and then, after some minutes (11:55 in the one case that I timed) crash out of the blue - without any browsing activity at the time of the crash that could be related.

The error message:
```
RangeError: Maximum call stack size exceeded
    at pulsar/site2/website/node_modules/gaze/lib/helper.js:76:11
```

**To Reproduce**
```bash 
git clone https://github.com/apache/pulsar.git
cd pulsar/site2/website
yarn install
yarn start
```
Then browse to a page like e.g. http://localhost:3000/docs/en/next/reference-metrics

**Expected behavior**
Why - no crash, of course.

**Environment**
NodeJs version: v10.15.2
Yarn version: 1.13.0
OS: Linux 5.3.0-26-lowlatency #28-Ubuntu SMP PREEMPT Wed Dec 18 06:21:38 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**
This gaze issue may be related: https://github.com/shama/gaze/issues/126

Here's the complete output (on debian, yarn is invoked as `yarnpkg`):
```
pulsar/site2/website$ time yarnpkg start
yarn run v1.13.0
warning package.json: No license field
$ docusaurus-start
Failed to start live reload server: RangeError: Maximum call stack size exceeded
LiveReload server started on port 35729
[BABEL] Note: The code generator has deoptimised the styling of pulsar/site2/website/node_modules/docusaurus/lib/core/metadata.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of pulsar/site2/website/node_modules/docusaurus/lib/core/metadata.js as it exceeds the max of 500KB.
Docusaurus server started on port 3000
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <div>. See https://fb.me/react-warning-keys for more information.
    in div
    in UsersBlock
    in div
    in div
    in Index
    in div
    in body
    in html
    in Site
Warning: Invalid DOM property `class`. Did you mean `className`?
    in div
    in div
    in div
    in Container
    in UsersBlock
    in div
    in div
    in Index
    in div
    in body
    in html
    in Site
pulsar/site2/website/node_modules/gaze/lib/helper.js:76
          callback(null);
          ^

RangeError: Maximum call stack size exceeded
    at pulsar/site2/website/node_modules/gaze/lib/helper.js:76:11
    at pulsar/site2/website/node_modules/gaze/lib/gaze.js:452:5
    at iterate (pulsar/site2/website/node_modules/gaze/lib/helper.js:69:5)
    at pulsar/site2/website/node_modules/gaze/lib/helper.js:78:11
    at pulsar/site2/website/node_modules/gaze/lib/gaze.js:452:5
    at iterate (pulsar/site2/website/node_modules/gaze/lib/helper.js:69:5)
    at pulsar/site2/website/node_modules/gaze/lib/helper.js:78:11
    at pulsar/site2/website/node_modules/gaze/lib/gaze.js:452:5
    at iterate (pulsar/site2/website/node_modules/gaze/lib/helper.js:69:5)
    at pulsar/site2/website/node_modules/gaze/lib/helper.js:78:11
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

real    11m54.598s
user    4m10.198s
sys     4m20.086s
```

**Comment by EugenDueck** [comment]
This is actually not a Pulsar bug, so I guess the type/bug label is wrong, but I don't see a way to change it.

**Comment by jiazhai** [comment]
Thanks @EugenDueck for the help of report and analysis this issue, seems this is related to  shama/gaze#126
