### ISSUE TITLE
Intermittent test failures in SimpleProducerConsumerTest.testSendCallBack

### ISSUE THREAD

**Issue by merlimat** [apache/pulsar#622]
As seen in https://builds.apache.org/job/pulsar-pull-request/org.apache.pulsar$pulsar-broker/30/testReport/junit/org.apache.pulsar.client.api/SimpleProducerConsumerTest/testSendCallBack/

```
java.util.concurrent.ExecutionException: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at org.apache.pulsar.client.api.SimpleProducerConsumerTest.testSendCallBack(SimpleProducerConsumerTest.java:958)
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at org.apache.pulsar.client.api.SimpleProducerConsumerTest.lambda$testSendCallBack$2(SimpleProducerConsumerTest.java:954)
	at org.apache.pulsar.client.api.SimpleProducerConsumerTest.testSendCallBack(SimpleProducerConsumerTest.java:950)
```

**Comment by jiazhai** [comment]
Seems not meet this issue for a long time,  would like to close this issue. could reopen it once meet again
