### ISSUE TITLE
Flaky-test - PulsarBoltTest failed to initialize producer

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#6232]
This exception occurs occasionally during builds. Here's one of the places it appeared: https://github.com/apache/pulsar/pull/6202/checks?check_run_id=428130764

```
[ERROR] Tests run: 15, Failures: 1, Errors: 0, Skipped: 11, Time elapsed: 57.314 s <<< FAILURE! - in org.apache.pulsar.storm.PulsarBoltTest
[ERROR] beforeMethod(org.apache.pulsar.storm.PulsarBoltTest)  Time elapsed: 34.056 s  <<< FAILURE!
java.lang.IllegalStateException: Failed to initialize producer for persistent://my-property/my-ns/my-topic1 : HTTP get request failed: Internal Server Error
	at org.apache.pulsar.storm.PulsarBolt.prepare(PulsarBolt.java:110)
	at org.apache.pulsar.storm.PulsarBoltTest.setup(PulsarBoltTest.java:83)
	at org.apache.pulsar.storm.PulsarBoltTest.beforeMethod(PulsarBoltTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at . . . 
```
This results in a test failure that looks like this:

```
[ERROR] org.apache.pulsar.storm.PulsarBoltTest.beforeMethod(org.apache.pulsar.storm.PulsarBoltTest)
[ERROR]   Run 1: PulsarBoltTest.beforeMethod:62->setup:83 » IllegalState Failed to initialize p...
```

I've attached the log archive. 
[logs_13139.zip](https://github.com/apache/pulsar/files/4161589/logs_13139.zip)

**Comment by devinbost** [comment]
I also wasn't sure if this should be labeled as a bug since it's just in tests.

**Comment by devinbost** [comment]
Here's another place where this occurred: https://github.com/apache/pulsar/pull/6202/checks?check_run_id=432617829
