### ISSUE TITLE
(Flaky-Test) Possible race condition - Fix Duplication Tests

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#6254]
These are intermittent errors that appear to be race conditions or concurrency issues, rather than issues with just the tests:

```
[ERROR] Tests run: 8, Failures: 3, Errors: 0, Skipped: 3, Time elapsed: 271.531 s <<< FAILURE! - in org.apache.pulsar.client.api.ClientDeduplicationTest
1158[ERROR] testProducerDeduplication(org.apache.pulsar.client.api.ClientDeduplicationTest) Time elapsed: 0.018 s <<< FAILURE!
1159java.lang.AssertionError: expected [-1] but found [2]
1160 at org.testng.Assert.fail(Assert.java:96)
1161 at org.testng.Assert.failNotEquals(Assert.java:776)
1162 at org.testng.Assert.assertEqualsImpl(Assert.java:137)
1163

[ERROR] testProducerDeduplicationNonBatchAsync(org.apache.pulsar.client.api.ClientDeduplicationTest) Time elapsed: 0.013 s <<< FAILURE!
1181java.lang.AssertionError: expected [-1] but found [5]
1182 at org.testng.Assert.fail(Assert.java:96)
1183 at org.testng.Assert.failNotEquals(Assert.java:776)
1184 at org.testng.Assert.assertEqualsImpl(Assert.java:137)
1185


[ERROR] testProducerDeduplicationWithDiscontinuousSequenceId(org.apache.pulsar.client.api.ClientDeduplicationTest) Time elapsed: 0.013 s <<< FAILURE!
1203java.lang.AssertionError: expected [-1] but found [5]
1204 at org.testng.Assert.fail(Assert.java:96)
1205 at org.testng.Assert.failNotEquals(Assert.java:776)
1206 at org.testng.Assert.assertEqualsImpl(Assert.java:137)
1207
```

They may reflect intermittent issues that are happening in production.

They can be seen here: https://github.com/apache/pulsar/pull/6202/checks?check_run_id=431093396

I've attached the logs. 

[logs_14078.zip](https://github.com/apache/pulsar/files/4168962/logs_14078.zip)

**Comment by tisonkun** [comment]
Closed as stale and no recent report. Please open a new issue if it's still relevant in maintained versions.
