### ISSUE TITLE
(Flaky-test) Intermittent assertion failure - testJdbcSink

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#6304]
I got this issue when running the integration tests locally:

```
java.lang.AssertionError: expected [1] but found [0]
Expected :1
Actual   :0
<Click to see difference>


	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:652)
	at org.testng.Assert.assertEquals(Assert.java:662)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.getSinkStatus(PulsarFunctionsTest.java:381)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.lambda$runSinkTester$1(PulsarFunctionsTest.java:205)
	at net.jodah.failsafe.Functions.lambda$toSupplier$8(Functions.java:236)
	at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:47)
	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:62)
	at net.jodah.failsafe.Execution.executeSync(Execution.java:129)
	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
	at net.jodah.failsafe.FailsafeExecutor.run(FailsafeExecutor.java:210)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.runSinkTester(PulsarFunctionsTest.java:205)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testSink(PulsarFunctionsTest.java:155)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testJdbcSink(PulsarFunctionsTest.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
```

I've attached the logs. 
[testJdbcSink_logs.txt](https://github.com/apache/pulsar/files/4189416/testJdbcSink_logs.txt)

**Comment by tisonkun** [comment]
Closed as stale and no recent report. Please open a new issue if it's still relevant in maintained versions.

IIRC I fixed a related issue at #17849.
