### ISSUE TITLE
(Flaky-test) Intermittent failure of SimpleLoadManagerImplTest.setup()

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#6369]
I came across this issue locally by running this command:
`mvn test '-Dtest=!PersistentTransactionBufferTest,!PulsarFunctionE2ESecurityTest,!ServerCnxTest,!AdminApiOffloadTest,!AdminApiSchemaValidationEnforced,!V1_AdminApiTest2,!ProxyPublishConsumeTlsTest,!PulsarFunctionE2ETest,!MessageIdSerialization,!AdminApiTest2,!PulsarFunctionLocalRunTest,!PartitionedProducerConsumerTest,!KafkaProducerSimpleConsumerTest,!MessagePublishThrottlingTest,!ReaderTest,!RackAwareTest,!SimpleProducerConsumerTest,!V1_ProducerConsumerTest,!PersistentFailoverE2ETest,!BrokerClientIntegrationTest,!ReplicatorRateLimiterTest' -DfailIfNoTests=false -pl pulsar-broker`

(This is the command used to run the Github CI Unit Broker test.)

```
[ERROR] Tests run: 26, Failures: 1, Errors: 0, Skipped: 23, Time elapsed: 46.456 s <<< FAILURE! - in org.apache.pulsar.broker.loadbalance.SimpleLoadManagerImplTest
[ERROR] setup(org.apache.pulsar.broker.loadbalance.SimpleLoadManagerImplTest)  Time elapsed: 36.245 s  <<< FAILURE!
java.io.IOException: Couldn't connect to zookeeper server
        at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble$ZKConnectionWatcher.waitForConnection(LocalBookkeeperEnsemble.java:475)
        at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.initializeZookeper(LocalBookkeeperEnsemble.java:214)
        at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.start(LocalBookkeeperEnsemble.java:384)
        at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.start(LocalBookkeeperEnsemble.java:393)
        at org.apache.pulsar.broker.loadbalance.SimpleLoadManagerImplTest.setup(SimpleLoadManagerImplTest.java:120)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
        at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
        at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
        at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
```

**Comment by devinbost** [comment]
It's not clear if this issue is related or not: https://github.com/apache/pulsar/issues/3537

**Comment by devinbost** [comment]
This test is failing at `bkEnsemble.start()` here:

 ```
   void setup() throws Exception {

        // Start local bookkeeper ensemble
        bkEnsemble = new LocalBookkeeperEnsemble(3, 0, () -> 0);
        bkEnsemble.start();
```
It seems odd that it couldn't connect to Zookeeper for over 30 seconds (which is how long it takes for the Zookeeper timeout to take effect.)

**Comment by tisonkun** [comment]
Closed as stale and no recent report. Please open a new issue if it's still relevant in maintained versions.
