### ISSUE TITLE
(Flaky-test) Intermittent failure of TestPulsarKeyValueSchemaHandler testSchema1 & testSchema2

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#6370]
When running this command locally:

`mvn install -DfailIfNoTests=false '-Dtest=!KafkaProducerSimpleConsumerTest,!PrimitiveSchemaTest,!BlobStoreManagedLedgerOffloaderTest' -pl '!pulsar-broker,!pulsar-proxy,!pulsar-broker-auth-sasl,!pulsar-io/kafka-connect-adaptor,!tests/pulsar-storm-test'`

(which is the command used to run the Github CI - Unit action)

I produced these errors:

```
[ERROR] Tests run: 6, Failures: 2, Errors: 0, Skipped: 2, Time elapsed: 0.962 s <<< FAILURE! - in org.apache.pulsar.sql.presto.TestPulsarKeyValueSchemaHandler
[ERROR] testSchema1(org.apache.pulsar.sql.presto.TestPulsarKeyValueSchemaHandler)  Time elapsed: 0.011 s  <<< FAILURE!
java.lang.NullPointerException
        at org.apache.pulsar.sql.presto.PulsarMetadata.getPulsarColumns(PulsarMetadata.java:344)
        at org.apache.pulsar.sql.presto.TestPulsarKeyValueSchemaHandler.testSchema1(TestPulsarKeyValueSchemaHandler.java:90)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
        at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
        at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.789 s - in org.apache.pulsar.sql.presto.TestPulsarSplitManager
[INFO] Tests run: 22, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.895 s - in org.apache.pulsar.sql.presto.TestPulsarMetadata
[ERROR] testSchema2(org.apache.pulsar.sql.presto.TestPulsarKeyValueSchemaHandler)  Time elapsed: 0.001 s  <<< FAILURE!
java.lang.NullPointerException
        at org.apache.pulsar.sql.presto.PulsarMetadata.getPulsarColumns(PulsarMetadata.java:344)
        at org.apache.pulsar.sql.presto.TestPulsarKeyValueSchemaHandler.testSchema2(TestPulsarKeyValueSchemaHandler.java:126)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
        at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
        at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by devinbost** [comment]
It appears (from the stack trace) that the NPE is getting thrown from the line:
`SchemaType schemaType = schemaInfo.getType();`

in this method:

```
 static List<ColumnMetadata> getPulsarColumns(TopicName topicName,
                                                 SchemaInfo schemaInfo,
                                                 boolean withInternalColumns,
                                                 PulsarColumnHandle.HandleKeyValueType handleKeyValueType) {
        SchemaType schemaType = schemaInfo.getType();
        if (schemaType.isStruct()) {
            return getPulsarColumnsFromStructSchema(topicName, schemaInfo, withInternalColumns, handleKeyValueType);
        } else if (schemaType.isPrimitive()) {
            return getPulsarColumnsFromPrimitiveSchema(topicName, schemaInfo, withInternalColumns, handleKeyValueType);
        } else if (schemaType.equals(SchemaType.KEY_VALUE)) {
            return getPulsarColumnsFromKeyValueSchema(topicName, schemaInfo, withInternalColumns);
        } else {
            throw new IllegalArgumentException("Unsupported schema : " + schemaInfo);
        }
    }
```

**Comment by codelipenghui** [comment]
@gaoran10 Please help take a look at this issue.

**Comment by tisonkun** [comment]
Closed as stale and no recent report. Please open a new issue if it's still relevant in maintained versions.
