### ISSUE TITLE
(Flaky-test) Intermittent failure of CompactionTest.setup

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#6371]
I came across this issue locally by running this command:
`mvn test '-Dtest=!PersistentTransactionBufferTest,!PulsarFunctionE2ESecurityTest,!ServerCnxTest,!AdminApiOffloadTest,!AdminApiSchemaValidationEnforced,!V1_AdminApiTest2,!ProxyPublishConsumeTlsTest,!PulsarFunctionE2ETest,!MessageIdSerialization,!AdminApiTest2,!PulsarFunctionLocalRunTest,!PartitionedProducerConsumerTest,!KafkaProducerSimpleConsumerTest,!MessagePublishThrottlingTest,!ReaderTest,!RackAwareTest,!SimpleProducerConsumerTest,!V1_ProducerConsumerTest,!PersistentFailoverE2ETest,!BrokerClientIntegrationTest,!ReplicatorRateLimiterTest' -DfailIfNoTests=false -pl pulsar-broker`

(This is the command used to run the Github CI Unit Broker test.)

```
[ERROR] Tests run: 61, Failures: 1, Errors: 0, Skipped: 53, Time elapsed: 86.474 s <<< FAILURE! - in org.apache.pulsar.compaction.CompactionTest
[ERROR] setup(org.apache.pulsar.compaction.CompactionTest)  Time elapsed: 2.767 s  <<< FAILURE!
org.apache.pulsar.client.admin.PulsarAdminException$NotFoundException: HTTP 404 Not Found
        at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:214)
        at org.apache.pulsar.client.admin.internal.ClustersImpl.createCluster(ClustersImpl.java:74)
        at org.apache.pulsar.compaction.CompactionTest.setup(CompactionTest.java:79)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
        at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
        at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
        at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
        at org.testng.TestRunner.privateRun(TestRunner.java:648)
        at org.testng.TestRunner.run(TestRunner.java:505)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
        at org.testng.SuiteRunner.run(SuiteRunner.java:364)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
```

**Comment by tisonkun** [comment]
Closed as stale and no recent report. Please open a new issue if it's still relevant in maintained versions.
