### ISSUE TITLE
Maven Pulsar Functions Utils test failure on standalone setup

### ISSUE THREAD

**Issue by alijmlzd** [apache/pulsar#6418]
**Describe the bug**
By running `bin/pulsar standalone` to start pulsar standalone it response me run `mvn package`:
```
Couldn't find presto distribution.
Make sure you've run 'mvn package'
```
And after running `mvn package` there are test failures:
```
[INFO] Running org.apache.pulsar.functions.utils.FunctionCommonTest
[ERROR] Tests run: 7, Failures: 2, Errors: 0, Skipped: 2, Time elapsed: 18.516 s <<< FAILURE! - in org.apache.pulsar.functions.utils.FunctionCommonTest
[ERROR] testDownloadFile(org.apache.pulsar.functions.utils.FunctionCommonTest)  Time elapsed: 0.014 s  <<< FAILURE!
java.net.UnknownHostException: central.maven.org
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at java.net.URL.openStream(URL.java:1045)
        at org.apache.pulsar.functions.utils.FunctionCommon.downloadFromHttpUrl(FunctionCommon.java:221)
        at org.apache.pulsar.functions.utils.FunctionCommonTest.testDownloadFile(FunctionCommonTest.java:78)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
        at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
        at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

[ERROR] testValidateHttpFileUrl(org.apache.pulsar.functions.utils.FunctionCommonTest)  Time elapsed: 0.003 s  <<< FAILURE!
java.net.UnknownHostException: central.maven.org
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at java.net.URL.openStream(URL.java:1045)
        at org.apache.pulsar.functions.utils.FunctionCommon.downloadFromHttpUrl(FunctionCommon.java:221)
        at org.apache.pulsar.functions.utils.FunctionCommon.extractFileFromPkgURL(FunctionCommon.java:266)
        at org.apache.pulsar.functions.utils.FunctionCommon.extractClassLoader(FunctionCommon.java:242)
        at org.apache.pulsar.functions.utils.FunctionCommonTest.testValidateHttpFileUrl(FunctionCommonTest.java:61)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
        at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
        at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

```
[ERROR] Failures: 
[ERROR] org.apache.pulsar.functions.utils.FunctionCommonTest.testDownloadFile(org.apache.pulsar.functions.utils.FunctionCommonTest)
[INFO]   Run 1: PASS
[ERROR]   Run 2: FunctionCommonTest.testDownloadFile:78 » UnknownHost central.maven.org
[INFO] 
[ERROR] org.apache.pulsar.functions.utils.FunctionCommonTest.testValidateHttpFileUrl(org.apache.pulsar.functions.utils.FunctionCommonTest)
[INFO]   Run 1: PASS
[ERROR]   Run 2: FunctionCommonTest.testValidateHttpFileUrl:61 » UnknownHost central.maven.org
[INFO] 
[INFO] 
[ERROR] Tests run: 86, Failures: 2, Errors: 0, Skipped: 0
```

```
[INFO] Pulsar Functions :: Utils .......................... FAILURE [02:01 min]
```

**To Reproduce**
Go to the root of the pulsar binary release downloaded and run `mvn package`.

**Desktop:**
 - OS: macOS 10.14.4

**Comment by jiazhai** [comment]
Thanks @alijmlzd for the reporting. Would you please try to use command `mvn package -DskipTests`?

**Comment by jiazhai** [comment]
regarding the error "java.net.UnknownHostException: central.maven.org", it looks like a dns issue

**Comment by alijmlzd** [comment]
@jiazhai Yeah, it seems to have some sort of issues about DNS but still can't fix by using various internet providers or proxies. anyway the command `mvn package` with `-DskipTests` works and fixed the building failures.
Thanks
