### ISSUE TITLE
auto_consume for avro crashes in decode (updated producer .class, old consumer schema .class)

### ISSUE THREAD

**Issue by shiv4289** [apache/pulsar#6419]
**Describe the bug**
We use schema compatibility = NONE. This means we can put data as per multiple schemas on the same topic. When we read those values back we build the consumer using AUTO_CONSUME.
On receiving the message,
1.  We extract the schema from message,
2. Construct avro schema from the message in (1)
3. schema.decode(msg)

**This used to work well for us with 2.3 server and 2.3 client. With server and client upgrade to 2.5 this does not work in some cases.** 

From my debugging on this, there seems to be an issue as a result of which avro does not use the the reader schema correctly  in the schema object provided here ->. schema.decode(msg)  .

**Expected behavior**
With schema.decode() the decode method should use the exact schema that was used to build avroSchema instance.

**Comment by shiv4289** [comment]
On debugging more, the issue seems to be this:
1. We maintain a library (say, _avro-schemas_) that contains all .avsc files and their generated .class files. Lets say we are on version v1 of this library on producer as well as consumer applications. This works fine.
2. We add a new field (with defaults) to avro in _avro-schemas_, update our library to v2 and update this in the producer application.
3. Consumer application is still using v1 of the _avro-schemas_ library.
4. The apache avro library looks for a class name with the name of schema in the class loader context. In our case, it finds the old class in v1.
5. Now it goes through every field in schema (updated schema), fetches that from binary data buffer and tries to set that in my old class. The fields in the old class are found by index and then updated by writing to that position which does not exist for new fields, thence the crash.

**Stacktrace**

[2020-02-26T10:23:34.441Z] ERROR main BeamRuleEngine:51 [/] java.lang.NullPointerException
	at org.apache.pulsar.shade.org.apache.avro.reflect.ReflectData.setField(ReflectData.java:139)
	at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumReader.readField(GenericDatumReader.java:232)
	at org.apache.pulsar.shade.org.apache.avro.specific.SpecificDatumReader.readField(SpecificDatumReader.java:122)
	at org.apache.pulsar.shade.org.apache.avro.reflect.ReflectDatumReader.readField(ReflectDatumReader.java:310)
	at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:222)
	at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:175)
	at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:153)
	at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:145)
	at org.apache.pulsar.client.impl.schema.reader.AvroReader.read(AvroReader.java:56)
	at org.apache.pulsar.client.api.schema.SchemaReader.read(SchemaReader.java:36)
	at org.apache.pulsar.client.impl.schema.StructSchema.decode(StructSchema.java:98)

**Comment by congbobo184** [comment]
This exception isn't come from msg.getValue(),  is it convenient to have a look at your schema? I think it is come from producer.send, because you add the field can't be empty.

**Comment by shiv4289** [comment]
Fixed with this in the consumer code:

```
            String avroGeneratedClassName = genericAvroRecord.getAvroRecord().getSchema().getFullName();
            Class<?> avroGeneratedClass = Class.forName(avroGeneratedClassName);

            org.apache.pulsar.shade.org.apache.avro.Schema writerSchema = new Parser().parse(new String(schemaProvider.getSchemaByVersion(msg.getSchemaVersion()).get().getSchema()));

            org.apache.avro.Schema avroNativeReaderSchema = (org.apache.avro.Schema) avroGeneratedClass.getDeclaredField("SCHEMA$").get(null);
            org.apache.pulsar.shade.org.apache.avro.Schema readerSchema = new Parser().parse(avroNativeReaderSchema.toString());

            AvroReader avroReader = new AvroReader(writerSchema, readerSchema);
            return avroReader.read(msg.getData());
```

**Comment by shiv4289** [comment]
Thanks @codelipenghui and @congbobo184 for your help. I will work on generalising this and submit a PR at a later point in time so this code can become a part of native consumer.
