### ISSUE TITLE
support prestosql not prestodb

### ISSUE THREAD

**Issue by JKeyZ** [apache/pulsar#6605]
We use prestosql, not prestodb of facebook. What’s the plan for support it ?

prestosql: https://prestosql.io/

**Comment by sijie** [comment]
@JKeyZ they should be identical in terms of features, right? Is there any interface changes between these two features?

**Comment by JKeyZ** [comment]
Sorry for replay to late. Prestosql was forked from prestodb by community. The first change was name of package which change it to io.prestosql . And optimize some feature.

**Comment by JKeyZ** [comment]
I copy the pulsar-presto-connector from binary package to my prestodb cluster, and config the properties according to guidelines of pulsar sql.But when I run the sql, it was failed.
config file of presto-pulsar:
`connector.name=pulsar
pulsar.broker-service-url=http://pulsarserver3:18080
pulsar.zookeeper-uri=pulsarserver3:2188
#pulsar.entry-read-batch-size=100
pulsar.target-num-splits=4`

the sql:
`select * from pulsar."public/default"."pulsar-string";`

log info:
`2020-03-30T23:09:45.529+0800	ERROR	Query-20200330_150942_00000_ycp8z-216	org.apache.pulsar.sql.presto.PulsarSplitManager	Failed to get splits
java.io.IOException: Failed to initialize ledger manager factory
	at org.apache.bookkeeper.client.BookKeeper.<init>(BookKeeper.java:520)
	at org.apache.bookkeeper.client.BookKeeper.<init>(BookKeeper.java:368)
	at org.apache.bookkeeper.mledger.impl.ManagedLedgerFactoryImpl$DefaultBkFactory.<init>(ManagedLedgerFactoryImpl.java:183)
	at org.apache.bookkeeper.mledger.impl.ManagedLedgerFactoryImpl.<init>(ManagedLedgerFactoryImpl.java:122)
	at org.apache.bookkeeper.mledger.impl.ManagedLedgerFactoryImpl.<init>(ManagedLedgerFactoryImpl.java:114)
	at org.apache.pulsar.sql.presto.PulsarConnectorCache.initManagedLedgerFactory(PulsarConnectorCache.java:108)
	at org.apache.pulsar.sql.presto.PulsarConnectorCache.<init>(PulsarConnectorCache.java:66)
	at org.apache.pulsar.sql.presto.PulsarConnectorCache.getConnectorCache(PulsarConnectorCache.java:83)
	at org.apache.pulsar.sql.presto.PulsarSplitManager.getSplitsNonPartitionedTopic(PulsarSplitManager.java:224)
	at org.apache.pulsar.sql.presto.PulsarSplitManager.getSplits(PulsarSplitManager.java:126)
	at com.facebook.presto.split.SplitManager.getSplits(SplitManager.java:64)
	at com.facebook.presto.sql.planner.DistributedExecutionPlanner$Visitor.visitTableScan(DistributedExecutionPlanner.java:145)
	at com.facebook.presto.sql.planner.DistributedExecutionPlanner$Visitor.visitTableScan(DistributedExecutionPlanner.java:121)
	at com.facebook.presto.sql.planner.plan.TableScanNode.accept(TableScanNode.java:128)
	at com.facebook.presto.sql.planner.DistributedExecutionPlanner.doPlan(DistributedExecutionPlanner.java:107)
	at com.facebook.presto.sql.planner.DistributedExecutionPlanner.doPlan(DistributedExecutionPlanner.java:112)
	at com.facebook.presto.sql.planner.DistributedExecutionPlanner.plan(DistributedExecutionPlanner.java:84)
	at com.facebook.presto.execution.SqlQueryExecution.planDistribution(SqlQueryExecution.java:404)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.bookkeeper.meta.exceptions.MetadataException: Failed to initialized ledger manager factory
	at org.apache.bookkeeper.meta.zk.ZKMetadataDriverBase.getLedgerManagerFactory(ZKMetadataDriverBase.java:243)
	at org.apache.bookkeeper.client.BookKeeper.<init>(BookKeeper.java:518)
	... 21 more
Caused by: java.io.IOException: Empty Ledger Root Path.
	at org.apache.bookkeeper.meta.AbstractZkLedgerManagerFactory.newLedgerManagerFactory(AbstractZkLedgerManagerFactory.java:158)
	at org.apache.bookkeeper.meta.zk.ZKMetadataDriverBase.getLedgerManagerFactory(ZKMetadataDriverBase.java:239)
	... 22 more


2020-03-30T23:09:45.578+0800	INFO	query-execution-1	com.facebook.presto.event.query.QueryMonitor	TIMELINE: Query 20200330_150942_00000_ycp8z :: Transaction:[006300e8-da04-4cd6-b619-0f5b3b0ef810] :: elapsed 2840ms :: planning 1114ms :: scheduling 1726ms :: running 0ms :: finishing 1726ms :: begin 2020-03-30T23:09:42.692+08:00 :: end 2020-03-30T23:09:45.532+08:00`

prestodb version is 0.210

**Comment by sijie** [comment]
Which version of pulsar-presto connector are you using?

**Comment by JKeyZ** [comment]
pulsar version is 2.5.0

**Comment by JKeyZ** [comment]
When I upgrade prestodb to 0.233.1, and run the sql was failed.
error :
Query 20200404_150253_00025_zyyqn failed: Internal error

sql: select * from  "pulsar-string" limit 10;

**Comment by ckdarby** [comment]
I was under the impression that Pulsar is using PrestoSQL and not PrestoDB.

Is it using PrestoSQL or PrestoDB? Can we clarify the docs to be more explicit?

**Comment by skyrocknroll** [comment]
@ckdarby it is using prestodb

**Comment by dionjansen** [comment]
I tried the same as @JKeyZ but I didn't get much further than this error when starting the presto server:

```
2020-06-06T14:03:16.935Z	DEBUG	main	io.prestosql.server.PluginManager	    /usr/lib/presto/plugin/pulsar-presto-connector/zookeeper-3.5.7.jar
2020-06-06T14:03:16.935Z	DEBUG	main	io.prestosql.server.PluginManager	    /usr/lib/presto/plugin/pulsar-presto-connector/zookeeper-jute-3.5.7.jar
2020-06-06T14:03:16.935Z	DEBUG	main	io.prestosql.server.PluginManager	    /usr/lib/presto/plugin/pulsar-presto-connector/zstd-jni-1.3.7-3.jar
2020-06-06T14:03:16.954Z	ERROR	main	io.prestosql.server.PrestoServer	No service providers of type io.prestosql.spi.Plugin
java.lang.IllegalStateException: No service providers of type io.prestosql.spi.Plugin
	at com.google.common.base.Preconditions.checkState(Preconditions.java:588)
	at io.prestosql.server.PluginManager.loadPlugin(PluginManager.java:157)
	at io.prestosql.server.PluginManager.loadPlugin(PluginManager.java:148)
	at io.prestosql.server.PluginManager.loadPlugins(PluginManager.java:129)
	at io.prestosql.server.PrestoServer.run(PrestoServer.java:127)
	at io.prestosql.$gen.Presto_329____20200606_140307_1.run(Unknown Source)
	at io.prestosql.server.PrestoServer.main(PrestoServer.java:72)
2020-06-06T14:03:16.955Z	INFO	Thread-79	io.airlift.bootstrap.LifeCycleManager	Life cycle stopping...
```

I grabbed the connector from https://archive.apache.org/dist/pulsar/pulsar-2.5.1/apache-pulsar-2.5.1-bin.tar.gz and build it ontop the [prestosql/presto:329](https://hub.docker.com/layers/prestosql/presto/329/images/sha256-3ce639c6a0e5eb3cd285a04e39f7b741698ad44d278859ecd88a602c99e3528a?context=explore) base image, my Pulsar cluster is version `2.5.1`.
