### ISSUE TITLE
[Integration test]Go function integration test failed

### ISSUE THREAD

**Issue by tuteng** [apache/pulsar#6643]
**Describe the bug**

At present, the go function integration test will have the following exceptions during the process, but the integration test has not been interrupted.

```
07:28:54.133 [tc-okhttp-stream-236682747:org.apache.pulsar.tests.integration.utils.DockerUtils$2@221] INFO  org.apache.pulsar.tests.integration.utils.DockerUtils - DOCKER.exec(PulsarFunctionsProcessTest-dtrmf-pulsar-functions-worker-process-gqrql-0:/pulsar/bin/pulsar-admin functions localrun  --broker-service-url pulsar://pulsar-broker-0:6650 --tenant public --namespace default --name localRunTest --inputs persistent://public/default/test-function-local-run-GO-input-oimciwbq --output test-function-local-run-GO-output-gmvisykv --go /pulsar/examples/go-examples/exclamationFunc): STDOUT: 07:28:54.132 [function-timer-thread-3-1] ERROR org.apache.pulsar.functions.runtime.process.ProcessRuntime - Health check failed for localRunTest-0
15204
java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
15205
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_242]
15206
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908) ~[?:1.8.0_242]
15207
	at org.apache.pulsar.functions.runtime.process.ProcessRuntime.lambda$start$1(ProcessRuntime.java:170) ~[org.apache.pulsar-pulsar-functions-runtime-2.6.0-SNAPSHOT.jar:2.6.0-SNAPSHOT]
15208
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
15209
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_242]
15210
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_242]
15211
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_242]
15212
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242] 
```

**To Reproduce**

Set enable to true https://github.com/apache/pulsar/blob/master/tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java#L847, then run command:
```
mvn -B -f tests/pom.xml test -DintegrationTestSuiteFile=pulsar-process.xml -Dtest=PulsarFunctionsProcessTest -Dgroups=function -DintegrationTests -DredirectTestOutputToFile=false
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
