### ISSUE TITLE
Cannot be cast to [B - presto connector

### ISSUE THREAD

**Issue by eaba** [apache/pulsar#6749]
Given a byte[] field in a Schema, pulsar presto connector throws this exceptions even when presto identifies the column as varbinary
````
java.lang.ClassCastException: java.nio.HeapByteBuffer cannot be cast to [B
2020-04-16T18:53:25.559818923Z 	at org.apache.pulsar.sql.presto.PulsarRecordCursor.getSlice(PulsarRecordCursor.java:496)
2020-04-16T18:53:25.559823223Z 	at com.facebook.presto.$gen.CursorProcessor_20200416_185325_28.project_0(Unknown Source)
2020-04-16T18:53:25.559827723Z 	at com.facebook.presto.$gen.CursorProcessor_20200416_185325_28.process(Unknown Source)
2020-04-16T18:53:25.559832623Z 	at com.facebook.presto.operator.ScanFilterAndProjectOperator.processColumnSource(ScanFilterAndProjectOperator.java:237)
2020-04-16T18:53:25.559836923Z 	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:229)
2020-04-16T18:53:25.559848923Z 	at com.facebook.presto.operator.Driver.processInternal(Driver.java:373)
2020-04-16T18:53:25.559852723Z 	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:282)
2020-04-16T18:53:25.559856623Z 	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
2020-04-16T18:53:25.559860423Z 	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
2020-04-16T18:53:25.559864323Z 	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:973)
2020-04-16T18:53:25.559868223Z 	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
2020-04-16T18:53:25.559872323Z 	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:477)
2020-04-16T18:53:25.559876423Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-04-16T18:53:25.559880323Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-04-16T18:53:25.559884223Z 	at java.lang.Thread.run(Thread.java:748)
````

**Comment by gaoran10** [comment]
@eaba Hi, could you provide the reproduce steps. I couldn't reproduce the issue, my steps as below.

use the pulsar 2.6.0

1. run pulsar standalone.
2. run pulsar sql-worker.
3. run pulsar sql cli.
4. produce message use byte[] schema, query messages successfully.
5. produce message use ByteBuffer schema. query messages successfully.

**Comment by eaba** [comment]
I used pulsar 2.5.0 then:
1. run using streamnative/chart with presto enabled
2. produce message using `AvroSchema` with byte[] field
3. query message exception is thrown as above

**Comment by sijie** [comment]
@gaoran10 I think the issue is related to using AvroSchema with a `byte[]` field. Can you try to reproduce it again?

**Comment by gaoran10** [comment]
@eaba @sijie I could reproduce the problem by the Avro schema as bellow.

# Schema
```
@Data
public static class LogFile {
    int id;
    String name;
    ByteBuffer data;
}

Producer<LogFile> producer = pulsarClient.newProducer(Schema.AVRO(LogFile.class)).topic(topic).create();
```

# Error log
```
2020-05-08T23:34:47.079+0800	ERROR	SplitRunner-5-101	com.facebook.presto.execution.executor.TaskExecutor	Error processing Split 20200508_153445_00006_nxngm.1.0-1 PulsarSplit{splitId=1, connectorId='pulsar', originSchemaName='bytes-sql-test4', schemaName='public/default', tableName='bytes-sql-test4', splitSize=4, schema='{"type":"record","name":"LogFile","namespace":"com.ran.schema.KeyValueSchemaTest$","fields":[{"name":"id","type":"int"},{"name":"name","type":["null","string"],"default":null},{"name":"data","type":["null","bytes"],"default":null}]}', schemaType=AVRO, startPositionEntryId=5, endPositionEntryId=9, startPositionLedgerId=3359, endPositionLedgerId=3359, schemaInfoProperties={"__alwaysAllowNull":"true"}} (start = 4.34095226272178E8, wall = 546 ms, cpu = 0 ms, wait = 0 ms, calls = 1)
java.lang.ClassCastException: java.nio.HeapByteBuffer cannot be cast to [B
	at org.apache.pulsar.sql.presto.PulsarRecordCursor.getSlice(PulsarRecordCursor.java:516)
	at com.facebook.presto.spi.RecordPageSource.getNextPage(RecordPageSource.java:117)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:242)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:373)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:282)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:973)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:477)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

We could find some useful information in the error log. `{"name":"data","type":["null","bytes"],"default":null}]}`. The Avro schema makes the `ByteBuffer` field use the type `bytes`.

The method `getSlice()` of the Class `PulsarRecordCursor` has a force cast `Slices.wrappedBuffer((byte[]) record)` but the record type is ByteBuffer.

I'll fix it.
