### ISSUE TITLE
[Pulsar SQL] multiple zk servers issue

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar#6852]
**Describe the bug**

Pulsar SQL documentation indicates:

```
pulsar.zookeeper-uri=localhost1,localhost2:2181
```

It doesn't work, I tried:

```
pulsar.zookeeper-uri=localhost1:2181,localhost2:2181
```

And same issue.

But for

```
pulsar.zookeeper-uri=localhost1:2181
```

It works.

When it doesn't work, it throws:

```
2020-04-30T12:33:53.229Z        INFO    Query-20200430_123351_00000_ak294-159   org.apache.zookeeper.common.X509Util    Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation
2020-04-30T12:33:53.233Z        INFO    Query-20200430_123351_00000_ak294-159   org.apache.zookeeper.ClientCnxnSocket   jute.maxbuffer value is 4194304 Bytes
2020-04-30T12:33:53.239Z        INFO    Query-20200430_123351_00000_ak294-159   org.apache.zookeeper.ClientCnxn zookeeper.request.timeout value is 0. feature enabled=
2020-04-30T12:33:53.247Z        INFO    Query-20200430_123351_00000_ak294-159-SendThread(yo-zookeeper-c2-n3:2184)      org.apache.zookeeper.ClientCnxnOpening socket connection to server yo-zookeeper-c2-n3/192.168.10.6:2184. Will not attempt to authenticate using SASL (unknown error)
2020-04-30T12:33:53.253Z        INFO    Query-20200430_123351_00000_ak294-159-SendThread(yo-zookeeper-c2-n3:2184)      org.apache.zookeeper.ClientCnxnSocket connection established, initiating session, client: /192.168.10.17:56234, server: yo-zookeeper-c2-n3/192.168.10.6:2184
2020-04-30T12:33:53.273Z        INFO    Query-20200430_123351_00000_ak294-159-SendThread(yo-zookeeper-c2-n3:2184)      org.apache.zookeeper.ClientCnxnSession establishment complete on server yo-zookeeper-c2-n3/192.168.10.6:2184, sessionid = 0x308edaa37a20019, negotiated timeout = 10000
2020-04-30T12:33:53.276Z        INFO    Query-20200430_123351_00000_ak294-159-EventThread       org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase    ZooKeeper client is connected now.
2020-04-30T12:33:53.306Z        INFO    Query-20200430_123351_00000_ak294-159   org.apache.bookkeeper.meta.MetadataDrivers      BookKeeper metadata driver manager initialized
2020-04-30T12:33:53.307Z        INFO    Query-20200430_123351_00000_ak294-159   org.apache.bookkeeper.meta.MetadataDrivers      BookKeeper metadata driver manager initialized
2020-04-30T12:33:53.307Z        INFO    Query-20200430_123351_00000_ak294-159   org.apache.bookkeeper.meta.MetadataDrivers      BookKeeper metadata driver manager initialized
2020-04-30T12:33:53.310Z        INFO    Query-20200430_123351_00000_ak294-159   org.apache.bookkeeper.meta.zk.ZKMetadataDriverBase      Initialize zookeeper metadata driver with external zookeeper client : ledgersRootPath = /ledgers.
2020-04-30T12:33:53.324Z        WARN    Query-20200430_123351_00000_ak294-159   org.apache.bookkeeper.util.EventLoopUtil        Could not use Netty Epoll event loop: failed to load the required native library
2020-04-30T12:33:53.347Z        ERROR   Query-20200430_123351_00000_ak294-159   org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl       Failed to initialize DNS Resolver org.apache.bookkeeper.net.ScriptBasedMapping, used default subnet resolver : java.lang.RuntimeException: No network topology script is found when using script based DNS resolver.
2020-04-30T12:33:53.353Z        INFO    Query-20200430_123351_00000_ak294-159   org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl       Initialize rackaware ensemble placement policy @ <Bookie:192.168.10.17:0> @ /default-rack : org.apache.bookkeeper.client.TopologyAwareEnsemblePlacementPolicy$DefaultResolver.
2020-04-30T12:33:53.353Z        INFO    Query-20200430_123351_00000_ak294-159   org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl       Not weighted
2020-04-30T12:33:53.356Z        INFO    Query-20200430_123351_00000_ak294-159   org.apache.bookkeeper.client.BookKeeper Weighted ledger placement is not enabled
2020-04-30T12:33:53.383Z        INFO    BookKeeperClientScheduler-OrderedScheduler-0-0  org.apache.bookkeeper.net.NetworkTopologyImpl   Adding a new node: /default-rack/yo-bookkeeper-c1-n3:3181
2020-04-30T12:33:53.383Z        INFO    BookKeeperClientScheduler-OrderedScheduler-0-0  org.apache.bookkeeper.net.NetworkTopologyImpl   Adding a new node: /default-rack/yo-bookkeeper-c1-n1:3181
2020-04-30T12:33:53.384Z        INFO    BookKeeperClientScheduler-OrderedScheduler-0-0  org.apache.bookkeeper.net.NetworkTopologyImpl   Adding a new node: /default-rack/yo-bookkeeper-c1-n2:3181
2020-04-30T12:33:53.386Z        ERROR   Query-20200430_123351_00000_ak294-159   org.apache.pulsar.sql.presto.PulsarSplitManager Failed to get splits
java.io.IOException: Failed to initialize ledger manager factory
        at org.apache.bookkeeper.client.BookKeeper.<init>(BookKeeper.java:520)
        at org.apache.bookkeeper.client.BookKeeper.<init>(BookKeeper.java:368)
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerFactoryImpl$DefaultBkFactory.<init>(ManagedLedgerFactoryImpl.java:183)
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerFactoryImpl.<init>(ManagedLedgerFactoryImpl.java:122)
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerFactoryImpl.<init>(ManagedLedgerFactoryImpl.java:114)
        at org.apache.pulsar.sql.presto.PulsarConnectorCache.initManagedLedgerFactory(PulsarConnectorCache.java:108)
        at org.apache.pulsar.sql.presto.PulsarConnectorCache.<init>(PulsarConnectorCache.java:66)
        at org.apache.pulsar.sql.presto.PulsarConnectorCache.getConnectorCache(PulsarConnectorCache.java:83)
        at org.apache.pulsar.sql.presto.PulsarSplitManager.getSplitsNonPartitionedTopic(PulsarSplitManager.java:224)
        at org.apache.pulsar.sql.presto.PulsarSplitManager.getSplits(PulsarSplitManager.java:126)
        at com.facebook.presto.split.SplitManager.getSplits(SplitManager.java:64)
        at com.facebook.presto.sql.planner.DistributedExecutionPlanner$Visitor.visitTableScan(DistributedExecutionPlanner.java:146)
        at com.facebook.presto.sql.planner.DistributedExecutionPlanner$Visitor.visitTableScan(DistributedExecutionPlanner.java:122)
        at com.facebook.presto.sql.planner.plan.TableScanNode.accept(TableScanNode.java:136)
        at com.facebook.presto.sql.planner.DistributedExecutionPlanner.doPlan(DistributedExecutionPlanner.java:108)
        at com.facebook.presto.sql.planner.DistributedExecutionPlanner.doPlan(DistributedExecutionPlanner.java:113)
        at com.facebook.presto.sql.planner.DistributedExecutionPlanner.plan(DistributedExecutionPlanner.java:85)
        at com.facebook.presto.execution.SqlQueryExecution.planDistribution(SqlQueryExecution.java:385)
        at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:287)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.bookkeeper.meta.exceptions.MetadataException: Failed to initialized ledger manager factory
        at org.apache.bookkeeper.meta.zk.ZKMetadataDriverBase.getLedgerManagerFactory(ZKMetadataDriverBase.java:243)
        at org.apache.bookkeeper.client.BookKeeper.<init>(BookKeeper.java:518)
        ... 21 more
Caused by: java.io.IOException: Empty Ledger Root Path.
        at org.apache.bookkeeper.meta.AbstractZkLedgerManagerFactory.newLedgerManagerFactory(AbstractZkLedgerManagerFactory.java:158)
        at org.apache.bookkeeper.meta.zk.ZKMetadataDriverBase.getLedgerManagerFactory(ZKMetadataDriverBase.java:239)
        ... 22 more

```

**Comment by codelipenghui** [comment]
@gaoran10 could you please help take a look this issue?

**Comment by gaoran10** [comment]
OK, I'll fix it.

**Comment by jiazhai** [comment]
@gaoran10  will handle it recently.
