### ISSUE TITLE
Sometimes get partitioned metadata  will throws  NullPointerException

### ISSUE THREAD

**Issue by liudezhi2098** [apache/pulsar#7163]
**Describe the bug**
Sometimes get partitioned metadata  will throws  NullPointerException,
because the NamespaceService not initialized yet

```bash
WARN  org.apache.pulsar.broker.service.ServerCnx - Failed to get Partitioned Metadata 
[/112.0.0.1:6760] persistent://public/default/test null
java.lang.NullPointerException: null      
        at org.apache.pulsar.broker.service.BrokerService.fetchPartitionedTopicMetadataCheckAllowAutoCreationAsync(Br
okerService.java:1830)     
        at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.lambda$23(PersistentTopicsBase.java:2215)     
        at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase$$Lambda$141/1430619109.apply(Unknown Source) ~[?:
?]
        at java.util.concurrent.CompletableFuture.doThenCompose(CompletableFuture.java:1996) 
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2546) 
at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.getPartitionedTopicMetadata(PersistentTopicsBase.
java:2214) 
        at org.apache.pulsar.broker.service.ServerCnx.lambda$4(ServerCnx.java:469)       
at org.apache.pulsar.broker.service.ServerCnx$$Lambda$131/1787376191.apply(Unknown Source)
        at java.util.concurrent.CompletableFuture.doThenApply(CompletableFuture.java:1530) 
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2369)      
 at org.apache.pulsar.broker.service.ServerCnx.handlePartitionMetadataRequest(ServerCnx.java:467) 
```

**Comment by jiazhai** [comment]
Thanks for @liudezhi2098 to help on this issue.
