### ISSUE TITLE
Redundant exceptions in broker logs

### ISSUE THREAD

**Issue by trexinc** [apache/pulsar#7366]
Our broker logs are filled with the exception below. That namespace indeed doesn't exists, and there is probably a "bad" consumer/publisher or a "bad" routing function. But still, those exceptions do not provide much useful info and just fill up the logs. If possible it would be great not to print them, or at least not to print the full exception stack.

```
2020-06-26 06:54:11 | 03:54:11.568 [ForkJoinPool.commonPool-worker-0] ERROR org.apache.pulsar.broker.web.PulsarWebResource - Policies not found for cve_updater_1592900096237_ABCD/risk namespace
-- | --
  |   | 2020-06-26 06:54:11 | at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_252]
  |   | 2020-06-26 06:54:11 | at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_252]
  |   | 2020-06-26 06:54:11 | at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_252]
  |   | 2020-06-26 06:54:11 | at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_252]
  |   | 2020-06-26 06:54:11 | at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) [?:1.8.0_252]
  |   | 2020-06-26 06:54:11 | at org.apache.pulsar.zookeeper.ZooKeeperCache.lambda$16(ZooKeeperCache.java:362) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.5.2.jar:2.5.2]
  |   | 2020-06-26 06:54:11 | at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) ~[?:1.8.0_252]
  |   | 2020-06-26 06:54:11 | at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_252]
  |   | 2020-06-26 06:54:11 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_252]
  |   | 2020-06-26 06:54:11 | at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_252]
  |   | 2020-06-26 06:54:11 | at org.apache.pulsar.zookeeper.ZooKeeperCache.lambda$18(ZooKeeperCache.java:377) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.5.2.jar:2.5.2]
  |   | 2020-06-26 06:54:11 | at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) ~[?:1.8.0_252]
  |   | 2020-06-26 06:54:11 | at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_252]
  |   | 2020-06-26 06:54:11 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_252]
  |   | 2020-06-26 06:54:11 | at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_252]
  |   | 2020-06-26 06:54:11 | at org.apache.pulsar.zookeeper.ZooKeeperDataCache.lambda$0(ZooKeeperDataCache.java:68) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.5.2.jar:2.5.2]
  |   | 2020-06-26 06:54:11 | at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) ~[?:1.8.0_252]
  |   | 2020-06-26 06:54:11 | at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_252]
  |   | 2020-06-26 06:54:11 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_252]
  |   | 2020-06-26 06:54:11 | at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_252]
  |   | 2020-06-26 06:54:11 | at org.apache.pulsar.broker.web.PulsarWebResource.lambda$checkLocalOrGetPeerReplicationCluster$4(PulsarWebResource.java:697) ~[org.apache.pulsar-pulsar-broker-2.5.2.jar:2.5.2]
  |   | 2020-06-26 06:54:11 | org.apache.pulsar.broker.web.RestException: Policies not found for cve_updater_1592900096232_ABCD/risk namespace
  |   | 2020-06-26 06:54:11 | 03:54:11.567 [ForkJoinPool.commonPool-worker-1] WARN  org.apache.pulsar.broker.service.ServerCnx - Failed to get Partitioned Metadata [/10.128.22.46:52250] persistent://cve_updater_1592900096232_ABCD/risk/0: Policies not found for cve_updater_1592900096232_ABCD/risk namespace


```

**Comment by tisonkun** [comment]
Closed as stale and no one worked on it. Please open a new issue if it's still relevant to the maintained versions.
