### ISSUE TITLE
Failed to create subscription on non-persistent topic.

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#7397]
**Describe the bug**
When use pulsar-admin to create a subscription on a non-persistent topic,  get server error like:

```
org.apache.pulsar.client.admin.PulsarAdminException$ServerSideErrorException: HTTP 500 Internal Server Error

	at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:209)
	at org.apache.pulsar.client.admin.internal.TopicsImpl.createSubscription(TopicsImpl.java:1077)
	at io.streamnative.pulsar.plugins.auditlog.WebserviceAuditLogTest.testCreateSubscriptionOnNonPersistentTopic(WebserviceAuditLogTest.java:930)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
Caused by: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1098)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:883)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:456)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.put(JerseyInvocation.java:340)
	at org.apache.pulsar.client.admin.internal.TopicsImpl.createSubscription(TopicsImpl.java:1075)
	... 25 more

```

**To Reproduce**
1. Start standalone
2. Create a subscription on a non-persistent topic
3. See error

```
org.apache.pulsar.client.admin.PulsarAdminException$ServerSideErrorException: HTTP 500 Internal Server Error

	at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:209)
	at org.apache.pulsar.client.admin.internal.TopicsImpl.createSubscription(TopicsImpl.java:1077)
	at io.streamnative.pulsar.plugins.auditlog.WebserviceAuditLogTest.testCreateSubscriptionOnNonPersistentTopic(WebserviceAuditLogTest.java:928)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
Caused by: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1098)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:883)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:456)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.put(JerseyInvocation.java:340)
	at org.apache.pulsar.client.admin.internal.TopicsImpl.createSubscription(TopicsImpl.java:1075)
	... 25 more
```

**Expected behavior**
The subscription should create successfully. Maybe the failed reason is if we create a subscription on a non-persistent topic, the broker will not keep messages for this subscription. But considering that users may turn off subscription automatic creation, the subscription should be created.

**Additional context**
pulsar 2.6.0

**Comment by jiazhai** [comment]
Thanks for @codelipenghui 's detailed report. mark it as `help wanted` for anyone interest to contribute to it.

**Comment by MarvinCai** [comment]
I can reproduce the issue by starting standalone and create tenant/namespace then try to create subscription on non-persistent topic with command:
`./pulsar-admin topics create-subscription  -s subscription non-persistent://tenant/namespace/topic`
and I see HTTP 500 Internal Server Error
I think the reason is the create-subscription is intended for persistent topic and it'll try to cast the created topic to PersistentTopic: https://github.com/apache/pulsar/blame/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java#L1843 so it'll fail if we provide a non persistent topic name.
Do we want to add support for non-persistent topic here?

**Comment by codelipenghui** [comment]
@MarvinCai Is it better to return a specific error to users? the internal server error is more confused. I thought about it carefully, allow create a subscription on a non-persistent topic by `pulsar-admin` is not a good point, because when the topic unloaded, the subscription will disappear, this is more difficult for users to understand.

**Comment by MarvinCai** [comment]
Then I think we can add a check at client side to see if passed in topic name, and throw exception if it's a non-persistent one. If that sounds good I'll make the change.

**Comment by codelipenghui** [comment]
@MarvinCai Do you mean pulsar-client or pulsar-admin? I think we should also fix the REST API.

**Comment by MarvinCai** [comment]
update REST api, as pulsar-admin also use REST api, it will fix for both.
