### ISSUE TITLE
Create function failed!

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#7405]
**Describe the bug**
1.The function application jar cannot be downloaded to the download directory when creating. It still shows that the creation is successful. The log output of function worker is normal. Check that the function application process does not exist by PS command.

2.Restart function worker. The PS command can check that the functions worker process exists, but the netstat command shows that the functions worker service port does not exist.

[pulsar-functions-worker.log](https://github.com/apache/pulsar/files/4856098/pulsar-functions-worker.log)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jiazhai** [comment]
@xuesong172500 Thanks for open this issue.
Seems there is some error logs need to analysis.
```
10:38:47.798 [function-web-20-8] ERROR org.apache.pulsar.functions.worker.rest.api.ComponentImpl - Operation not permitted on pulsar/system/streamPulsarBcn
```

```
12:40:50.755 [pulsar-client-io-15-1] ERROR org.apache.pulsar.functions.worker.FunctionMetaDataTopicTailer - Failed to retrieve messages from function state topic
java.util.concurrent.CompletionException: org.apache.pulsar.client.api.PulsarClientException$AlreadyClosedException: The consumer which subscribes the topic persistent://public/functions/metadata with subscription name reader-5a68249449 was already closed when cleaning and closing the consumers
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_151]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_151]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593) ~[?:1.8.0_151]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[?:1.8.0_151]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_151]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[?:1.8.0_151]
	at org.apache.pulsar.client.impl.ConsumerImpl.failPendingReceive(ConsumerImpl.java:814) ~[org.apache.pulsar-pulsar-client-original-2.5.1.jar:2.5.1]
	at org.apache.pulsar.client.impl.ConsumerImpl.cleanupAtClose(ConsumerImpl.java:795) ~[org.apache.pulsar-pulsar-client-original-2.5.1.jar:2.5.1]
	at org.apache.pulsar.client.impl.ConsumerImpl.lambda$closeAsync$4(ConsumerImpl.java:777) ~[org.apache.pulsar-pulsar-client-original-2.5.1.jar:2.5.1]
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822) [?:1.8.0_151]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797) [?:1.8.0_151]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) [?:1.8.0_151]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) [?:1.8.0_151]
	at org.apache.pulsar.client.impl.ClientCnx.handleSuccess(ClientCnx.java:413) [org.apache.pulsar-pulsar-client-original-2.5.1.jar:2.5.1]
	at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:222) [org.apache.pulsar-pulsar-common-2.5.1.jar:2.5.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) [io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321) [io.netty-netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295) [io.netty-netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) [io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) [io.netty-netty-transport-native-epoll-4.1.45.Final-linux-x86_64.jar:4.1.45.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) [io.netty-netty-transport-native-epoll-4.1.45.Final-linux-x86_64.jar:4.1.45.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [io.netty-netty-transport-native-epoll-4.1.45.Final-linux-x86_64.jar:4.1.45.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty-netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty-netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.45.Final.jar:4.1.45.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: org.apache.pulsar.client.api.PulsarClientException$AlreadyClosedException: The consumer which subscribes the topic persistent://public/functions/metadata with subscription name reader-5a68249449 was already closed when cleaning and closing the consumers
	at org.apache.pulsar.client.impl.ConsumerImpl.failPendingReceive(ConsumerImpl.java:816) ~[org.apache.pulsar-pulsar-client-original-2.5.1.jar:2.5.1]
	... 27 more
```

```
13:55:59.544 [function-web-20-5] ERROR org.apache.pulsar.functions.worker.rest.api.ComponentImpl - Function to deregister does not exist @ /pulsar/system/streamPulsarBcn
```

**Comment by tisonkun** [comment]
Closed as stale. Feel free to open a new issue if it's still relevant for maintained versions.
