### ISSUE TITLE
The ArgumentError of the 'replication_clusters' in producer.send method in python pulsar.

### ISSUE THREAD

**Issue by xuehuanran** [apache/pulsar#7464]
I want to use the geo-replication in python pulsar and my code is below.

```
client = pulsar.Client("pulsar://localhost:6650")
producer = client.create_producer("python_topic_00", schema=StringSchema())
producer.send("Message0", replication_clusters=["cluster1", "cluster2"])
```

The error message is :

```
Traceback (most recent call last):
  File "tests/test_pulsar_producer.py", line 8, in <module>
    producer.send("Message0", replication_clusters=["cluster1", "cluster2"])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pulsar/__init__.py", line 786, in send
    replication_clusters, disable_replication, event_timestamp)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pulsar/__init__.py", line 879, in _build_msg
    mb.replication_clusters(replication_clusters)
Boost.Python.ArgumentError: Python argument types in
    MessageBuilder.replication_clusters(MessageBuilder, list)
did not match C++ signature:
    replication_clusters(pulsar::MessageBuilder {lvalue}, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >)
```

What is the correct data format of the replication_cluster argument.

**Comment by wolfstudy** [comment]
> did not match C++ signature

It seems that the version of python-client you are using does not match the version of cpp-client. Can you provide information about the version you are using?

**Comment by wolfstudy** [comment]
ping @xuehuanran Is this issue solved currently?

**Comment by wolfstudy** [comment]
@xuehuanran will close this issue, If there are any other questions, please reopen it or let me know, thanks feedback.
