### ISSUE TITLE
Discovery service can't find active broker

### ISSUE THREAD

**Issue by aloyszhang** [apache/pulsar#7476]
**Describe the bug**
Discovery service (three nodes) can't find active broker when all brokers are running well.
```shell
21:05:33.529 [pulsar-discovery-io-2-1] WARN  org.apache.pulsar.discovery.service.ServerConnection - [/100.76.40.78:34900] Failed to get next active broker No active broker is available
org.apache.pulsar.broker.PulsarServerException: No active broker is available
        at org.apache.pulsar.discovery.service.BrokerDiscoveryProvider.nextBroker(BrokerDiscoveryProvider.java:95) ~[org.apache.pulsar-pulsar-discovery-service-2.6.0-SNAPSHOT.jar:2.6.0-SNAPSHOT]
        at org.apache.pulsar.discovery.service.ServerConnection.sendLookupResponse(ServerConnection.java:136) [org.apache.pulsar-pulsar-discovery-service-2.6.0-SNAPSHOT.jar:2.6.0-SNAPSHOT]
        at org.apache.pulsar.discovery.service.ServerConnection.handleLookup(ServerConnection.java:127) [org.apache.pulsar-pulsar-discovery-service-2.6.0-SNAPSHOT.jar:2.6.0-SNAPSHOT]
        at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:126) [org.apache.pulsar-pulsar-common-2.6.0-SNAPSHOT.jar:2.6.0-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) [io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321) [io.netty-netty-codec-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295) [io.netty-netty-codec-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) [io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) [io.netty-netty-transport-native-epoll-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) [io.netty-netty-transport-native-epoll-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [io.netty-netty-transport-native-epoll-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty-netty-common-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty-netty-common-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.45.Final.jar:4.1.45.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```
**To Reproduce**
After restart the discovery service , wo can't reproduce it immediately. 
But after running for some times (several days, no sure) it will appear.

**Expected behavior**
Discovery service  should be work well.

**Comment by aloyszhang** [comment]
Addtionally, ZooKeeper has no error.
And we dump the discovery process,  found that `BrokerDiscoveryProvider` does not has availableBrokers in its `ZookeeperCacheLoader` but `DiscoveryServiceServlet` has the information.

**Comment by sijie** [comment]
@aloyszhang 

No available broker usually happens when the session expires. Out of curiosity, why do you need to start a separate discovery service?

**Comment by aloyszhang** [comment]
@sijie, Both `DiscoveryServiceServlet`  and `BrokerDiscoveryProvider ` will be started if runs discovery service .

**Comment by aloyszhang** [comment]
Since not found the exactlly reason cause this issue. We bring a compromise solution， try get active brokers from zk one more time  if `availableBrokers` in `localZkCache` is empty.

**Comment by sijie** [comment]
@aloyszhang Can you contribute the change back?

**Comment by aloyszhang** [comment]
@sijie
OK, I'll add a PR later.
