### ISSUE TITLE
ERROR org.apache.bookkeeper.common.util.SafeRunnable - Unexpected throwable caught  java.lang.ArrayIndexOutOfBoundsException: 100 while starting broker in cluster mode

### ISSUE THREAD

**Issue by opera33** [apache/pulsar#7482]
**Describe the bug**
Getting error while trying to start broker in a 2 node cluster mode, with over 200 pulsar functions registered to it.

**To Reproduce**
I have freshly setup the cluster, and on first run, adding 200 of the function is fine, then when the broker goes down and come back, it can't be started again.

**Expected behavior**
Pulsar broker to start as usual

**Additional context**
The broker can be started if functionWorkerEnable is set to false, but we need the pulsar function to work.

` [broker-topic-workers-OrderedScheduler-7-0] ERROR org.apache.bookkeeper.common.util.SafeRunnable - Unexpected throwable caught 
java.lang.ArrayIndexOutOfBoundsException: 100
	at org.apache.pulsar.broker.service.EntryBatchIndexesAcks.setIndexesAcks(EntryBatchIndexesAcks.java:34) ~[org.apache.pulsar-pulsar-broker-2.6.0.jar:2.6.0]
	at org.apache.pulsar.broker.service.AbstractBaseDispatcher.filterEntriesForConsumer(AbstractBaseDispatcher.java:119) ~[org.apache.pulsar-pulsar-broker-2.6.0.jar:2.6.0]
	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherSingleActiveConsumer.internalReadEntriesComplete(PersistentDispatcherSingleActiveConsumer.java:241) ~[org.apache.pulsar-pulsar-broker-2.6.0.jar:2.6.0]
	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherSingleActiveConsumer.lambda$readEntriesComplete$1(PersistentDispatcherSingleActiveConsumer.java:187) ~[org.apache.pulsar-pulsar-broker-2.6.0.jar:2.6.0]
	at org.apache.bookkeeper.mledger.util.SafeRun$1.safeRun(SafeRun.java:32) ~[org.apache.pulsar-managed-ledger-2.6.0.jar:2.6.0]
	at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [org.apache.bookkeeper-bookkeeper-common-4.10.0.jar:4.10.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_252]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.48.Final.jar:4.1.48.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]`

**Comment by codelipenghui** [comment]
@opera33 Did you change the `dispatcherMaxRoundRobinBatchSize` in the broker.conf?

**Comment by codelipenghui** [comment]
@opera33 I have created a PR #7483 for fixing this problem, thanks for your feedback.

**Comment by opera33** [comment]
Hi,

Didn't change that, if that help, I can try setting it.

Thanks!
