### ISSUE TITLE
ERROR org.apache.bookkeeper.client.BKException$ZKException: Error while using ZooKeeper

### ISSUE THREAD

**Issue by 97arushisharma** [apache/pulsar#7488]
**Describe the bug**
I am deploying a pulsar cluster with 3 nodes each having zookeeper, bookie and broker running. I had first deployed the zookeeper cluster on the 3 nodes and they seem to be running fine. But, when I am trying to run the bookeeper using the following command I am getting errors in bookkeeper sanity tests:
Command:
```
$ bin/pulsar-daemon start bookie

doing start bookie ...
starting bookie, logging to /opt/apache-pulsar-2.6.0/logs/pulsar-bookie-apachepulsar-01.log
Note: Set immediateFlush to true in conf/log4j2.yaml will guarantee the logging event is flushing to disk immediately. The default behavior is switched off due to performance considerations.

$ bin/bookkeeper shell bookiesanity
```
Error Log:
```
12:00:51.244 [main] INFO  org.apache.zookeeper.ZooKeeper - Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
12:00:51.244 [main] INFO  org.apache.zookeeper.ZooKeeper - Client environment:java.io.tmpdir=/tmp
12:00:51.244 [main] INFO  org.apache.zookeeper.ZooKeeper - Client environment:java.compiler=<NA>
12:00:51.244 [main] INFO  org.apache.zookeeper.ZooKeeper - Client environment:os.name=Linux
12:00:51.244 [main] INFO  org.apache.zookeeper.ZooKeeper - Client environment:os.arch=amd64
12:00:51.245 [main] INFO  org.apache.zookeeper.ZooKeeper - Client environment:os.version=3.10.0-1127.el7.x86_64
12:00:51.245 [main] INFO  org.apache.zookeeper.ZooKeeper - Client environment:user.name=root
12:00:51.245 [main] INFO  org.apache.zookeeper.ZooKeeper - Client environment:user.home=/root
12:00:51.246 [main] INFO  org.apache.zookeeper.ZooKeeper - Client environment:user.dir=/opt/apache-pulsar-2.6.0
12:00:51.246 [main] INFO  org.apache.zookeeper.ZooKeeper - Client environment:os.memory.free=1914MB
12:00:51.246 [main] INFO  org.apache.zookeeper.ZooKeeper - Client environment:os.memory.max=2048MB
12:00:51.246 [main] INFO  org.apache.zookeeper.ZooKeeper - Client environment:os.memory.total=2048MB
12:00:51.259 [main] INFO  org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=apachepulsar-01:2181,apachepulsar-02:2181,apachepulsar-03:2181 sessionTimeout=30000 watcher=org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase@74eb909f
12:00:51.269 [main] INFO  org.apache.zookeeper.common.X509Util - Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation
12:00:51.484 [main] INFO  org.apache.zookeeper.ClientCnxnSocket - jute.maxbuffer value is 4194304 Bytes
12:00:51.635 [main] INFO  org.apache.zookeeper.ClientCnxn - zookeeper.request.timeout value is 0. feature enabled=
12:00:51.658 [main-SendThread(apachepulsar-02:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server apachepulsar-02/x.x.x.116:2181. Will not attempt to authenticate using SASL (unknown error)
12:00:51.669 [main-SendThread(apachepulsar-02:2181)] INFO  org.apache.zookeeper.ClientCnxn - Socket connection established, initiating session, client: /x.x.x.115:51726, server: apachepulsar-02/x.x.x.116:2181
12:00:51.681 [main-SendThread(apachepulsar-02:2181)] INFO  org.apache.zookeeper.ClientCnxn - Session establishment complete on server apachepulsar-02/x.x.x.116:2181, sessionid = 0x1001e82e5150009, negotiated timeout = 30000
12:00:51.686 [main-EventThread] INFO  org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase - ZooKeeper client is connected now.
12:00:52.069 [main] INFO  org.apache.bookkeeper.client.BookKeeper - Weighted ledger placement is not enabled
12:00:52.126 [main] ERROR org.apache.bookkeeper.client.BookieWatcherImpl - Failed to get bookie list : 
org.apache.bookkeeper.client.BKException$ZKException: Error while using ZooKeeper
	at org.apache.bookkeeper.discover.ZKRegistrationClient.lambda$getChildren$0(ZKRegistrationClient.java:220) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.zookeeper.ZooKeeperClient$25$1.processResult(ZooKeeperClient.java:1174) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:630) ~[org.apache.pulsar-pulsar-zookeeper-2.6.0.jar:2.6.0]
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:510) ~[org.apache.pulsar-pulsar-zookeeper-2.6.0.jar:2.6.0]
Exception in thread "main" com.google.common.util.concurrent.UncheckedExecutionException: Error while using ZooKeeper
	at org.apache.bookkeeper.tools.cli.commands.bookie.SanityTestCommand.apply(SanityTestCommand.java:80)
	at org.apache.bookkeeper.bookie.BookieShell$BookieSanityTestCmd.runCmd(BookieShell.java:887)
	at org.apache.bookkeeper.bookie.BookieShell$MyCommand.runCmd(BookieShell.java:223)
	at org.apache.bookkeeper.bookie.BookieShell.run(BookieShell.java:1976)
	at org.apache.bookkeeper.bookie.BookieShell.main(BookieShell.java:2067)
Caused by: org.apache.bookkeeper.client.BKException$ZKException: Error while using ZooKeeper
	at org.apache.bookkeeper.discover.ZKRegistrationClient.lambda$getChildren$0(ZKRegistrationClient.java:220)
	at org.apache.bookkeeper.zookeeper.ZooKeeperClient$25$1.processResult(ZooKeeperClient.java:1174)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:630)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:510)
```

I have 3 nodes namely:
- apachepulsar-01
- apachepulsar-02
- apachepulsar-03

Following are the bookkeeper.conf entries:
```
advertisedAddress=apachepulsar-01 //each node has its own name
allowLoopback=false
useHostNameAsBookieID=false
zkServers=apachepulsar-01:2181,apachepulsar-02:2181,apachepulsar-03:2181
```
UPDATE:
After stopping my zookeeper service and starting them using the following command, a new type of error seen:

Command:
```
PULSAR_EXTRA_OPTS="-Dstats_server_port=8001" bin/pulsar-daemon start zookeeper
```
Logs:
```
13:03:11.203 [main-EventThread] INFO  org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase - ZooKeeper client is connected now.
13:03:11.266 [main] ERROR org.apache.bookkeeper.discover.ZKRegistrationManager - BookKeeper metadata doesn't exist in zookeeper. Has the cluster been initialized? Try running bin/bookkeeper shell metaformat
13:03:11.268 [main] INFO  org.apache.bookkeeper.proto.BookieNettyServer - Shutting down BookieNettyServer
13:03:11.284 [main] ERROR org.apache.bookkeeper.server.Main - Failed to build bookie server
org.apache.bookkeeper.bookie.BookieException$MetadataStoreException: Failed to get cluster instance id
	at org.apache.bookkeeper.discover.ZKRegistrationManager.getClusterInstanceId(ZKRegistrationManager.java:392) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.bookie.Bookie.checkEnvironmentWithStorageExpansion(Bookie.java:406) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.bookie.Bookie.checkEnvironment(Bookie.java:250) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.bookie.Bookie.<init>(Bookie.java:688) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.proto.BookieServer.newBookie(BookieServer.java:136) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.proto.BookieServer.<init>(BookieServer.java:105) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.server.service.BookieService.<init>(BookieService.java:41) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.server.Main.buildBookieServer(Main.java:301) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.server.Main.doMain(Main.java:221) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.server.Main.main(Main.java:203) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.proto.BookieServer.main(BookieServer.java:313) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for BookKeeper metadata
	at org.apache.bookkeeper.discover.ZKRegistrationManager.getClusterInstanceId(ZKRegistrationManager.java:382) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	... 10 more

```
I have to deploy the cluster on 3 nodes. Any help will be appreciated.

**Comment by 97arushisharma** [comment]
I was able to resolve this problem by changing the `zkLedgersRootPath=/ledgers`. I had initially kept the wrong path assuming that it is the path on our system. However, I am still facing an issue which seem to be more like a bug.

I am able to start my 3 bookies with `bin/bookkeeper bookie` command. But when I try to check the sanity using `bin/bookkeeper shell bookiesanity` command, I am getting the above mentioned zookeeper error. I had to use nohups to start my bookies as:
``` 
nohup  bin/bookkeeper bookie &
```
And when I list my bookies, I am finally getting all the 3 bookies:
```
$ bin/bookkeeper shell listbookies -a

All Bookies :
apachepulsar-03(x.x.x.117):3181
apachepulsar-01(x.x.x.115):3181
apachepulsar-02(x.x.x.116):3181
```
All the above commands are followed from the official documentation [here](https://pulsar.apache.org/docs/en/deploy-bare-metal/).
I am using the apache-pulsar 2.6.0

**Comment by sijie** [comment]
@97arushisharma Can you share the fully copy for your bookie config files? It seems that you have used a wrong ledgers root path for initializing the cluster.

**Comment by 97arushisharma** [comment]
@sijie thanks for the reply. Here are the bookkeeper.conf files.
[bookkeeper-02.conf.txt](https://github.com/apache/pulsar/files/4901184/bookkeeper-02.conf.txt)
[bookkeeper-01.conf.txt](https://github.com/apache/pulsar/files/4901206/bookkeeper-01.conf.txt)
[bookkeeper-03.conf.txt](https://github.com/apache/pulsar/files/4901214/bookkeeper-03.conf.txt)

Also below is the metadata command I have used:
```
bin/pulsar initialize-cluster-metadata \
  --cluster miq-pulsar-cluster \
  --zookeeper apachepulsar-01:2181 \
  --configuration-store apachepulsar-01:2181 \
  --web-service-url http://apachepulsar-02:8080 \
  --web-service-url-tls https://apachepulsar-02:8443 \
  --broker-service-url pulsar://apachepulsar-02:6650 \
  --broker-service-url-tls pulsar+ssl://apachepulsar-02:6651
```

**Comment by sijie** [comment]
@97arushisharma the configurations look good to me. Based on your last comment, it seems that you have addressed your problem by setting `zkLedgersRootPath`. Is that correct? Any other issues that you need help?

**Comment by 97arushisharma** [comment]
Yup. Thanks @sijie .
