### ISSUE TITLE
split-bundle for public/functions error

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#7504]
**Describe the bug**
error log in pulsar-broker-xx.log
```
22:16:07.855 [pulsar-web-40-5] ERROR org.apache.pulsar.broker.admin.impl.ClustersBase - [null] Failed to get clusters/pulsar-cluster/namespaceIsolationPolicies
org.apache.pulsar.broker.web.RestException: NamespaceIsolationPolicies for cluster pulsar-cluster does not exist
        at org.apache.pulsar.broker.admin.impl.ClustersBase.lambda$getNamespaceIsolationPolicies$3(ClustersBase.java:486) ~[org.apache.pulsar-pulsar-broker-2.5.2.jar:2.5.2]
        at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_251]
        at org.apache.pulsar.broker.admin.impl.ClustersBase.getNamespaceIsolationPolicies(ClustersBase.java:486) ~[org.apache.pulsar-pulsar-broker-2.5.2.jar:2.5.2]
        at sun.reflect.GeneratedMethodAccessor123.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76) ~[org.glassfish.jersey.core-jersey-server-2.27.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148) [org.glassfish.jersey.core-jersey-server-2.27.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191) [org.glassfish.jersey.core-jersey-server-2.27.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:243) [org.glassfish.jersey.core-jersey-server-2.27.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethoSocket error Event: 32 Error: 10053..jersey.core-jersey-server-2.27.jar:?]
```

pulsar 2.5.2

**To Reproduce**
1. create a function
2. bin/pulsar-admin namespaces split-bundle -b 0x40000000_0x80000000 -u public/functions

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by zymap** [comment]
which version of pulsar? I am not see any request for the NamespaceIsolationPolicies. Could you please provide more information?

**Comment by xuesongxs** [comment]
> which version of pulsar? I am not see any request for the NamespaceIsolationPolicies. Could you please provide more information?

pulsar 2.5.2

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it is still relevant to maintained versions.
