### ISSUE TITLE
start/stop function fail

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#7505]
**Describe the bug**
After creating functions, the function runs normally. Stop function starts function again. The following error is reported in the function log. Update function is invalid. You must delete function and then create function to run normally. Function jar is a fat jar, pulsar version is 2.5.2.

00:00:00.539 [public/default/streamPulsarBcn-80-SendThread(10.32.211.206:31180)] INFO  org.apache.zookeeper.ClientCnxn - Socket connection established, initiating session, client: /xxx.xxx.xxx.xxx:53231, server: xxx.xxx.xxx.xxx/xxx.xxx.xxx:31180
00:00:06.321 [public/default/streamPulsarBcn-80-SendThread(xxx.xxx.xxx.xxx:31180)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x2730982e3a7024c for server xxx.xxx.xxx.xxx/xxx.xxx.xxx.xxx:31180, unexpected error, closing socket connection and attempting reconnect
java.lang.NoClassDefFoundError: org/apache/zookeeper/proto/SetWatches
	at org.apache.zookeeper.ClientCnxn$SendThread.primeConnection(ClientCnxn.java:906) ~[streamPulsarBcn-1.0-SNAPSHOT.jar:?]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:352) ~[streamPulsarBcn-1.0-SNAPSHOT.jar:?]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1118) [streamPulsarBcn-1.0-SNAPSHOT.jar:?]

org.apache.dubbo.remoting.RemotingException: Failed connect to server /xxx.xxx.xxx.xxx:18005 from NettyClient xxx.xxx.xxx.xxx using dubbo version 1.0-SNAPSHOT, cause: io/netty/channel/AbstractChannelHandlerContext$13
	at org.apache.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:211) ~[streamPulsarBcn-1.0-SNAPSHOT.jar:?]
	at org.apache.dubbo.remoting.transport.AbstractClient.reconnect(AbstractClient.java:246) ~[streamPulsarBcn-1.0-SNAPSHOT.jar:?]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeClient.reconnect(HeaderExchangeClient.java:155) ~[streamPulsarBcn-1.0-SNAPSHOT.jar:?]
	at org.apache.dubbo.remoting.exchange.support.header.ReconnectTimerTask.doTask(ReconnectTimerTask.java:49) [streamPulsarBcn-1.0-SNAPSHOT.jar:?]
	at org.apache.dubbo.remoting.exchange.support.header.AbstractTimerTask.run(AbstractTimerTask.java:87) [streamPulsarBcn-1.0-SNAPSHOT.jar:?]
	at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:648) [streamPulsarBcn-1.0-SNAPSHOT.jar:?]
	at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:727) [streamPulsarBcn-1.0-SNAPSHOT.jar:?]
	at org.apache.dubbo.common.timer.HashedWheelTimer$Worker.run(HashedWheelTimer.java:449) [streamPulsarBcn-1.0-SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NoClassDefFoundError: io/netty/channel/AbstractChannelHandlerContext$13
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:610) ~[streamPulsarBcn-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:465) ~[streamPulsarBcn-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:1003) ~[streamPulsarBcn-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannel.close(AbstractChannel.java:238) ~[streamPulsarBcn-1.0-SNAPSHOT.jar:?]
	at org.apache.dubbo.remoting.transport.netty4.NettyClient.doConnect(NettyClient.java:139) ~[streamPulsarBcn-1.0-SNAPSHOT.jar:?]
	at org.apache.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:190) ~[streamPulsarBcn-1.0-SNAPSHOT.jar:?]

**To Reproduce**
1. create function
2. stop function
3. start function

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
