### ISSUE TITLE
Failed to build bookie server

### ISSUE THREAD

**Issue by bleacha870721** [apache/pulsar#7569]
**Describe the bug**
Bookie pod CrashLoopBackOff and cannot restart
**To Reproduce**

![image](https://user-images.githubusercontent.com/59589208/87747268-5db96e00-c825-11ea-85fc-403b60bc9c45.png)
04:04:26.014 [main] ERROR org.apache.bookkeeper.server.Main - Failed to build bookie server
org.apache.bookkeeper.bookie.BookieException$InvalidCookieException: Cookie [4
bookieHost: "10.233.106.106:3181"
journalDir: "data/bookkeeper/journal"
ledgerDirs: "1\tdata/bookkeeper/ledgers"
instanceId: "7940c93b-5da8-4fa7-941e-d254d678fb1c"
] is not matching with [4
bookieHost: "10.233.107.121:3181"
journalDir: "data/bookkeeper/journal"
ledgerDirs: "1\tdata/bookkeeper/ledgers"
instanceId: "7940c93b-5da8-4fa7-941e-d254d678fb1c"
]
	at org.apache.bookkeeper.bookie.Cookie.verifyInternal(Cookie.java:136) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.bookie.Cookie.verify(Cookie.java:147) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.bookie.Bookie.verifyAndGetMissingDirs(Bookie.java:369) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.bookie.Bookie.checkEnvironmentWithStorageExpansion(Bookie.java:432) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.bookie.Bookie.checkEnvironment(Bookie.java:250) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.bookie.Bookie.<init>(Bookie.java:688) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.proto.BookieServer.newBookie(BookieServer.java:136) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.proto.BookieServer.<init>(BookieServer.java:105) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.server.service.BookieService.<init>(BookieService.java:41) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.server.Main.buildBookieServer(Main.java:301) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.server.Main.doMain(Main.java:221) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.server.Main.main(Main.java:203) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
**Expected behavior**

**Desktop (please complete the following information):**
 - OS: 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic

**Comment by bleacha870721** [comment]
pulsar version: 2.5.2

**Comment by sijie** [comment]
@bleacha870721 How did you deploy the Pulsar cluster? Bookies require a stable network identifier for bookie id. So you need to set `useHostNameAsBookieID` to be `true`.

See Pulsar Helm Chart: https://github.com/apache/pulsar-helm-chart/blob/master/charts/pulsar/templates/_bookkeeper.tpl#L84

**Comment by walter-csharp** [comment]
I think this issue is fixed in v2.6.0 
The condition check PF_ENV_PREFIX is missed when update the env values in env config files. Now it has fixed v2.6.0

https://github.com/apache/pulsar/blob/master/docker/pulsar/scripts/apply-config-from-env.py

**Comment by Ghatage** [comment]
I agree with @sijie, this is a configuration problem and not a bug.

**Comment by tisonkun** [comment]
Closed as stale and answered.

Feel free to open a new issue if it's still relevant to the maintained versions.

**Comment by cccdemon** [comment]
same issue here, after a crash of a node, with a destroyed pvc .... 
had to delete the pvc and the pv, and this leads to this issue (at least here)

how to solve?

`2024-07-17T10:10:23,047+0000 [main] ERROR org.apache.bookkeeper.bookie.LegacyCookieValidation - There are directories without a cookie, and this is neither a new environment, nor is storage expansion enabled. Empty directories are [/pulsar/data/bookkeeper/journal/current, /pulsar/data/bookkeeper/ledgers/current]
2024-07-17T10:10:23,048+0000 [main] ERROR org.apache.bookkeeper.server.Main - Failed to build bookie server
org.apache.bookkeeper.bookie.BookieException$InvalidCookieException:
	at org.apache.bookkeeper.bookie.LegacyCookieValidation.checkCookies(LegacyCookieValidation.java:113) ~[org.apache.bookkeeper-bookkeeper-server-4.16.5.jar:4.16.5]
	at org.apache.bookkeeper.server.EmbeddedServer$Builder.build(EmbeddedServer.java:408) ~[org.apache.bookkeeper-bookkeeper-server-4.16.5.jar:4.16.5]
	at org.apache.bookkeeper.server.Main.buildBookieServer(Main.java:277) ~[org.apache.bookkeeper-bookkeeper-server-4.16.5.jar:4.16.5]
	at org.apache.bookkeeper.server.Main.doMain(Main.java:216) ~[org.apache.bookkeeper-bookkeeper-server-4.16.5.jar:4.16.5]
	at org.apache.bookkeeper.server.Main.main(Main.java:199) ~[org.apache.bookkeeper-bookkeeper-server-4.16.5.jar:4.16.5]`
