### ISSUE TITLE
Java Client fail when compressionType=SNAPPY or ZSTD and disable batching

### ISSUE THREAD

**Issue by bigbang489** [apache/pulsar#7602]
**Describe the bug**
Unable to use compressionType=SNAPPY or ZSTD and enableBatching=false
Pulsar client version: 2.5.1, 

Error: Exception in thread "main" org.xerial.snappy.SnappyError: [NOT_A_DIRECT_BUFFER] input is not a direct buffer
	at org.xerial.snappy.Snappy.compress(Snappy.java:143)
	at org.apache.pulsar.common.compression.CompressionCodecSnappy.encode(CompressionCodecSnappy.java:46)
	at org.apache.pulsar.client.impl.ProducerImpl.sendAsync(ProducerImpl.java:358)
	at org.apache.pulsar.client.impl.ProducerImpl.internalSendAsync(ProducerImpl.java:269)
	at org.apache.pulsar.client.impl.ProducerBase.send(ProducerBase.java:108)
	at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.send(TypedMessageBuilderImpl.java:89)
	at org.apache.pulsar.client.impl.ProducerBase.send(ProducerBase.java:63)
	at com.test.TestCompression.publish(TestCompression.java:27)
	at com.test.TestCompression.main(TestCompression.java:13)

**To Reproduce**
Sample source code:
```
package com.test;

import org.apache.pulsar.client.api.AuthenticationFactory;
import org.apache.pulsar.client.api.ClientBuilder;
import org.apache.pulsar.client.api.CompressionType;
import org.apache.pulsar.client.api.Producer;
import org.apache.pulsar.client.api.PulsarClient;
import org.apache.pulsar.client.api.PulsarClientException;

public class TestCompression {

	public static void main(String[] args) throws PulsarClientException {
		publish("Test message", "only-avro");
	}
	
	static void publish(String message, String topic) throws PulsarClientException {
		ClientBuilder cb = PulsarClient.builder();
		cb.serviceUrl("pulsar://pulsar:6650");
		cb.authentication(AuthenticationFactory.token("***************"));
		PulsarClient client = cb.build();
		Producer<byte[]> producer = client.newProducer()
				.topic(topic)
				.enableBatching(false)
				.compressionType(CompressionType.SNAPPY)
				.create();
		try {
			System.out.println("\r\nSent message: " + producer.send(message.getBytes()));
		}
		finally {
			producer.close();
		}
	}

}

```

Screenshot:
![image](https://user-images.githubusercontent.com/29498440/87900057-62785f00-ca7d-11ea-87e2-7ce8a0aae498.png)
![image](https://user-images.githubusercontent.com/29498440/87900067-686e4000-ca7d-11ea-90e7-13e12f4fdff2.png)

**Comment by bigbang489** [comment]
I close this issue because it no longer exists in version 2.6.0
