### ISSUE TITLE
Redolookup on REST API call

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar#7692]
**Describe the bug**
When calling HTTP PUT on compaction endpoint I'm having:

```
...
Caused by: org.apache.pulsar.broker.service.BrokerServiceException$ServiceUnitNotReadyException: Namespace bundle for topic (persistent://orga_89c3e460-5ea2-4729-9eed-9e871fa73afc/pulsar_f29f1ee2-99ad-45fb-b6ed-024809f91f70/webhook-wildmoka-7) not served by this instance. Please redo the lookup. Request is denied: namespace=orga_89c3e460-5ea2-4729-9eed-9e871fa73afc/pulsar_f29f1ee2-99ad-45fb-b6ed-024809f91f70
        at org.apache.pulsar.broker.service.BrokerService.checkTopicNsOwnership(BrokerService.java:1372)
        at org.apache.pulsar.broker.service.BrokerService.loadOrCreatePersistentTopic(BrokerService.java:955)
        at org.apache.pulsar.broker.service.BrokerService.lambda$getTopic$13(BrokerService.java:732)
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.put(ConcurrentOpenHashMap.java:277)
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap.computeIfAbsent(ConcurrentOpenHashMap.java:130)
        at org.apache.pulsar.broker.service.BrokerService.getTopic(BrokerService.java:731)
        at org.apache.pulsar.broker.service.BrokerService.getTopicIfExists(BrokerService.java:711)
        at org.apache.pulsar.broker.
```

Isn't the proxy that has to lookup for next broker by itself?

**Comment by sijie** [comment]
@KannarFr Currently Proxy doesn't retry any requests. It only forwards requests to brokers.

**Comment by rudy2steiner** [comment]
Similar issue #7604

**Comment by rudy2steiner** [comment]
@KannarFr  which method you call and how to reproduce, maybe I can help
