### ISSUE TITLE
The broker node crashes and the log shows zktime out，pulsar version  2.5.0

### ISSUE THREAD

**Issue by jiangmincong** [apache/pulsar#7870]
zk log
2020-08-21 13:25:16,072 [myid:009] - WARN  [NIOWorkerThread-76:NIOServerCnxn@364] - Unexpected exception
EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /10.242.63.172:49630, session = 0xa00e3a203cd0463
        at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:163)
        at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:326)
        at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
        at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
		
broker log
INFO  org.apache.pulsar.zookeeper.ZooKeeperDataCache - [State:CONNECTED Timeout:30000 sessionid:0xa0293b70e940002 local:/10.242.63.194:51680

**Comment by jiangmincong** [comment]
Hello, are there other ways to avoid this problem? Modify configuration parameters or other?

**Comment by xuesong172500** [comment]
@jiangmincong modify zookeeper client zooKeeperSessionTimeoutMillis/zooKeeperOperationTimeoutSeconds, Modify the property value and set it larger.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.

**Comment by lhotari** [comment]
This is a type of issue that might be fixed in most recent versions of Pulsar. If you are running an old unsupported version, please consider upgrading your Pulsar version to a maintained and recent version. For example, if you are on 2.10.x, upgrade to the latest in 2.10.x series first. Similarly for 2.11.x or 3.0.x, upgrade to the most recent version in the series.
