### ISSUE TITLE
NPE when acknowledge messages at the broker side

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#7878]
**Describe the bug**
```
Aug 22 15:59:37 dc3-pulsar-ec-beta-pro02 pulsar[13707]: java.lang.NullPointerException: null
Aug 22 15:59:37 dc3-pulsar-ec-beta-pro02 pulsar[13707]: at org.apache.pulsar.broker.service.persistent.PersistentSubscription.acknowledgeMessage(PersistentSubscription.java:386) ~[org.apache.pulsar-pulsar-broker-2.6.0.jar:2.6.0]
Aug 22 15:59:37 dc3-pulsar-ec-beta-pro02 pulsar[13707]: at org.apache.pulsar.broker.service.persistent.ReplicatedSubscriptionsController.receiveSubscriptionUpdated(ReplicatedSubscriptionsController.java:177) ~[org.apache.pulsar-pulsar-broker-2.6.0.jar:2.6.0]
Aug 22 15:59:37 dc3-pulsar-ec-beta-pro02 pulsar[13707]: at org.apache.pulsar.broker.service.persistent.ReplicatedSubscriptionsController.receivedReplicatedSubscriptionMarker(ReplicatedSubscriptionsController.java:92) ~[org.apache.pulsar-pulsar-broker-2.6.0.jar:2.6.0]
Aug 22 15:59:37 dc3-pulsar-ec-beta-pro02 pulsar[13707]: at org.apache.pulsar.broker.service.persistent.PersistentTopic.receivedReplicatedSubscriptionMarker(PersistentTopic.java:2155) ~[org.apache.pulsar-pulsar-broker-2.6.0.jar:2.6.0]
Aug 22 15:59:37 dc3-pulsar-ec-beta-pro02 pulsar[13707]: at org.apache.pulsar.broker.service.persistent.PersistentReplicator.checkReplicatedSubscriptionMarker(PersistentReplicator.java:745) ~[org.apache.pulsar-pulsar-broker-2.6.0.jar:2.6.0]
Aug 22 15:59:37 dc3-pulsar-ec-beta-pro02 pulsar[13707]: at org.apache.pulsar.broker.service.persistent.PersistentReplicator.readEntriesComplete(PersistentReplicator.java:351) ~[org.apache.pulsar-pulsar-broker-2.6.0.jar:2.6.0]
Aug 22 15:59:37 dc3-pulsar-ec-beta-pro02 pulsar[13707]: at org.apache.bookkeeper.mledger.impl.OpReadEntry.lambda$checkReadCompletion$2(OpReadEntry.java:152) ~[org.apache.pulsar-managed-ledger-2.6.0.jar:2.6.0]
Aug 22 15:59:37 dc3-pulsar-ec-beta-pro02 pulsar[13707]: at org.apache.bookkeeper.mledger.util.SafeRun$1.safeRun(SafeRun.java:32) [org.apache.pulsar-managed-ledger-2.6.0.jar:2.6.0]
Aug 22 15:59:37 dc3-pulsar-ec-beta-pro02 pulsar[13707]: at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [org.apache.bookkeeper-bookkeeper-common-4.10.0.jar:4.10.0]
Aug 22 15:59:37 dc3-pulsar-ec-beta-pro02 pulsar[13707]: at org.apache.bookkeeper.common.util.OrderedExecutor$TimedRunnable.run(OrderedExecutor.java:203) [org.apache.bookkeeper-bookkeeper-common-4.10.0.jar:4.10.0]
Aug 22 15:59:37 dc3-pulsar-ec-beta-pro02 pulsar[13707]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
Aug 22 15:59:37 dc3-pulsar-ec-beta-pro02 pulsar[13707]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
Aug 22 15:59:37 dc3-pulsar-ec-beta-pro02 pulsar[13707]: at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.48.Final.jar:4.1.48.Final]
Aug 22 15:59:37 dc3-pulsar-ec-beta-pro02 pulsar[13707]: at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
```
**Additional context**
2.6.0

**Comment by jiazhai** [comment]
👍 This should be an easy fix.

**Comment by codelipenghui** [comment]
close via #7937
