### ISSUE TITLE
CI failure: PulsarFunctionE2ETest: PulsarAdminException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#7978]
recently the ci failed for test PulsarFunctionE2ETest.
https://github.com/apache/pulsar/pull/7973/checks?check_run_id=1069972906

```
[ERROR] Tests run: 25, Failures: 1, Errors: 0, Skipped: 14, Time elapsed: 188.983 s <<< FAILURE! - in org.apache.pulsar.io.PulsarFunctionE2ETest
[ERROR] setup(org.apache.pulsar.io.PulsarFunctionE2ETest)  Time elapsed: 69.463 s  <<< FAILURE!
org.apache.pulsar.broker.PulsarServerException: java.lang.RuntimeException: org.apache.pulsar.client.admin.PulsarAdminException: java.lang.NullPointerException
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:608)
	at org.apache.pulsar.io.PulsarFunctionE2ETest.setup(PulsarFunctionE2ETest.java:201)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
...

Caused by: java.lang.RuntimeException: org.apache.pulsar.client.admin.PulsarAdminException: java.lang.NullPointerException
	at org.apache.pulsar.functions.worker.WorkerService.start(WorkerService.java:292)
	at org.apache.pulsar.broker.PulsarService.startWorkerService(PulsarService.java:1308)
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:595)
	... 35 more
Caused by: org.apache.pulsar.client.admin.PulsarAdminException: java.lang.NullPointerException
	at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:233)
	at org.apache.pulsar.client.admin.internal.TopicsImpl.createSubscription(TopicsImpl.java:1080)
	at org.apache.pulsar.functions.worker.WorkerService.start(WorkerService.java:181)
	... 37 more
Caused by: java.lang.NullPointerException
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:697)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:632)
	at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:654)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:648)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:648)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:631)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:434)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.put(JerseyInvocation.java:318)
	at org.apache.pulsar.client.admin.internal.TopicsImpl.createSubscription(TopicsImpl.java:1078)
```

**Comment by jiazhai** [comment]
close this issue for not meet this issue anymore.
