### ISSUE TITLE
Most PR CI Unit Tests failed by Functions tests

### ISSUE THREAD

**Issue by zymap** [apache/pulsar#8020]
CI error:

```
ERROR] testStatsManagerNull(org.apache.pulsar.functions.instance.JavaInstanceRunnableTest)  Time elapsed: 0.011 s  <<< FAILURE!
2020-09-09T08:43:43.5449793Z java.lang.NoClassDefFoundError: Could not initialize class org.apache.pulsar.functions.proto.Function$SourceSpec$InputSpecsDefaultEntryHolder
2020-09-09T08:43:43.5449950Z 	at org.apache.pulsar.functions.proto.Function$SourceSpec.internalGetInputSpecs(Function.java:8843)
2020-09-09T08:43:43.5450092Z 	at org.apache.pulsar.functions.proto.Function$SourceSpec.getInputSpecsCount(Function.java:8850)
2020-09-09T08:43:43.5450262Z 	at org.apache.pulsar.functions.instance.InstanceUtils.calculateSubjectType(InstanceUtils.java:98)
2020-09-09T08:43:43.5450381Z 	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.<init>(JavaInstanceRunnable.java:164)
2020-09-09T08:43:43.5454406Z 	at org.apache.pulsar.functions.instance.JavaInstanceRunnableTest.createRunnable(JavaInstanceRunnableTest.java:61)
2020-09-09T08:43:43.5455430Z 	at org.apache.pulsar.functions.instance.JavaInstanceRunnableTest.testStatsManagerNull(JavaInstanceRunnableTest.java:114)
2020-09-09T08:43:43.5455567Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-09-09T08:43:43.5455679Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-09-09T08:43:43.5455797Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-09-09T08:43:43.5456160Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2020-09-09T08:43:43.5456293Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
2020-09-09T08:43:43.5465900Z 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
2020-09-09T08:43:43.5466267Z 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
2020-09-09T08:43:43.5466413Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020-09-09T08:43:43.5466540Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-09-09T08:43:43.5469870Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-09-09T08:43:43.5470215Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-09-09T08:43:43.5470360Z 	at java.lang.Thread.run(Thread.java:748)
2020-09-09T08:43:43.5470409Z 
2020-09-09T08:43:43.5484499Z [INFO] Running org.apache.pulsar.functions.instance.InstanceUtilsTest
2020-09-09T08:43:43.7409861Z [ERROR] Tests run: 6, Failures: 3, Errors: 0, Skipped: 3, Time elapsed: 0.181 s <<< FAILURE! - in org.apache.pulsar.functions.instance.InstanceUtilsTest
2020-09-09T08:43:43.7410402Z [ERROR] testCalculateSubjectTypeForFunction(org.apache.pulsar.functions.instance.InstanceUtilsTest)  Time elapsed: 0.011 s  <<< FAILURE!
2020-09-09T08:43:43.7410589Z java.lang.NoClassDefFoundError: Could not initialize class org.apache.pulsar.functions.proto.Function$ConsumerSpec$SchemaPropertiesDefaultEntryHolder
2020-09-09T08:43:43.7410736Z 	at org.apache.pulsar.functions.proto.Function$ConsumerSpec$Builder.internalGetSchemaProperties(Function.java:7236)
2020-09-09T08:43:43.7411275Z 	at org.apache.pulsar.functions.proto.Function$ConsumerSpec$Builder.buildPartial(Function.java:6830)
2020-09-09T08:43:43.7411424Z 	at org.apache.pulsar.functions.proto.Function$ConsumerSpec$Builder.build(Function.java:6811)
2020-09-09T08:43:43.7411640Z 	at org.apache.pulsar.functions.instance.InstanceUtilsTest.testCalculateSubjectTypeForFunction(InstanceUtilsTest.java:52)
2020-09-09T08:43:43.7411787Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-09-09T08:43:43.7412018Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-09-09T08:43:43.7412158Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-09-09T08:43:43.7412380Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2020-09-09T08:43:43.7412504Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
2020-09-09T08:43:43.7412619Z 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
2020-09-09T08:43:43.7424457Z 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
2020-09-09T08:43:43.7433320Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020-09-09T08:43:43.7433707Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-09-09T08:43:43.7433873Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-09-09T08:43:43.7433995Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-09-09T08:43:43.7436413Z 	at java.lang.Thread.run(Thread.java:748)
2020-09-09T08:43:43.7436471Z 
2020-09-09T08:43:43.7437026Z [ERROR] testCalculateSubjectTypeForSink(org.apache.pulsar.functions.instance.InstanceUtilsTest)  Time elapsed: 0.014 s  <<< FAILURE!
2020-09-09T08:43:43.7437197Z java.lang.NoClassDefFoundError: Could not initialize class org.apache.pulsar.functions.proto.Function$ConsumerSpec$SchemaPropertiesDefaultEntryHolder
2020-09-09T08:43:43.7437331Z 	at org.apache.pulsar.functions.proto.Function$ConsumerSpec$Builder.internalGetSchemaProperties(Function.java:7236)
2020-09-09T08:43:43.7446202Z 	at org.apache.pulsar.functions.proto.Function$ConsumerSpec$Builder.buildPartial(Function.java:6830)
2020-09-09T08:43:43.7446360Z 	at org.apache.pulsar.functions.proto.Function$ConsumerSpec$Builder.build(Function.java:6811)
2020-09-09T08:43:43.7446712Z 	at org.apache.pulsar.functions.instance.InstanceUtilsTest.testCalculateSubjectTypeForSink(InstanceUtilsTest.java:68)
2020-09-09T08:43:43.7447054Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-09-09T08:43:43.7466268Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-09-09T08:43:43.7466402Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-09-09T08:43:43.7466766Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2020-09-09T08:43:43.7466906Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
2020-09-09T08:43:43.7467037Z 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
2020-09-09T08:43:43.7467238Z 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
2020-09-09T08:43:43.7467374Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020-09-09T08:43:43.7467502Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-09-09T08:43:43.7467629Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-09-09T08:43:43.7467889Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-09-09T08:43:43.7468024Z 	at java.lang.Thread.run(Thread.java:748)
2020-09-09T08:43:43.7468088Z 
2020-09-09T08:43:43.7468289Z [ERROR] testCalculateSubjectTypeForSource(org.apache.pulsar.functions.instance.InstanceUtilsTest)  Time elapsed: 0.007 s  <<< FAILURE!
2020-09-09T08:43:43.7468446Z java.lang.NoClassDefFoundError: Could not initialize class org.apache.pulsar.functions.proto.Function$SourceSpec$TopicsToSerDeClassNameDefaultEntryHolder
2020-09-09T08:43:43.7468892Z 	at org.apache.pulsar.functions.proto.Function$SourceSpec$Builder.internalGetTopicsToSerDeClassName(Function.java:9965)
2020-09-09T08:43:43.7469046Z 	at org.apache.pulsar.functions.proto.Function$SourceSpec$Builder.buildPartial(Function.java:9508)
2020-09-09T08:43:43.7469284Z 	at org.apache.pulsar.functions.proto.Function$SourceSpec$Builder.build(Function.java:9493)
2020-09-09T08:43:43.7595894Z 	at org.apache.pulsar.functions.instance.InstanceUtilsTest.testCalculateSubjectTypeForSource(InstanceUtilsTest.java:36)
2020-09-09T08:43:43.7598853Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-09-09T08:43:43.7599888Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-09-09T08:43:43.7603354Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-09-09T08:43:43.7608041Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2020-09-09T08:43:43.7608293Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
2020-09-09T08:43:43.7608536Z 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
2020-09-09T08:43:43.7608690Z 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
2020-09-09T08:43:43.7608816Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020-09-09T08:43:43.7608932Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-09-09T08:43:43.7611278Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-09-09T08:43:43.7611626Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-09-09T08:43:43.7611755Z 	at java.lang.Thread.run(Thread.java:748)
2020-09-09T08:43:43.7611818Z 
2020-09-09T08:43:43.7655579Z [INFO] Running org.apache.pulsar.functions.instance.JavaInstanceRunnableTest$IntegerSerDe
2020-09-09T08:43:43.8049942Z [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.038 s - in org.apache.pulsar.functions.instance.JavaInstanceRunnableTest$IntegerSerDe
2020-09-09T08:43:43.8055019Z [INFO] Running org.apache.pulsar.functions.instance.JavaInstanceRunnableTest$ComplexSerDe
2020-09-09T08:43:43.8600297Z [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.052 s - in org.apache.pulsar.functions.instance.JavaInstanceRunnableTest$ComplexSerDe
2020-09-09T08:43:43.8604463Z [INFO] Running org.apache.pulsar.functions.instance.JavaInstanceRunnableTest$VoidInputHandler
2020-09-09T08:43:43.9228481Z [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.058 s - in org.apache.pulsar.functions.instance.JavaInstanceRunnableTest$VoidInputHandler
2020-09-09T08:43:43.9237104Z [INFO] Running org.apache.pulsar.functions.instance.state.StateContextImplTest
2020-09-09T08:43:44.9132305Z [INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.831 s - in org.apache.pulsar.functions.windowing.WaterMarkEventGeneratorTest
2020-09-09T08:43:44.9144957Z [INFO] Running org.apache.pulsar.functions.instance.FunctionResultRouterTest
2020-09-09T08:43:45.4900104Z [INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.563 s - in org.apache.pulsar.functions.instance.FunctionResultRouterTest
2020-09-09T08:43:45.4945963Z [INFO] Running org.apache.pulsar.functions.instance.JavaInstanceTest
2020-09-09T08:43:45.8143541Z [INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.361 s - in org.apache.pulsar.functions.windowing.WindowFunctionExecutorTest
2020-09-09T08:43:45.8158619Z [INFO] Running org.apache.pulsar.functions.instance.JavaInstanceRunnableTest$VoidOutputHandler
2020-09-09T08:43:45.8995477Z [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.082 s - in org.apache.pulsar.functions.instance.JavaInstanceRunnableTest$VoidOutputHandler
2020-09-09T08:43:45.9232754Z [INFO] Running org.apache.pulsar.functions.sink.PulsarSinkTest$1
2020-09-09T08:43:46.0063007Z [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.081 s - in org.apache.pulsar.functions.sink.PulsarSinkTest$1
2020-09-09T08:43:46.0085540Z [INFO] Running org.apache.pulsar.functions.sink.PulsarSinkTest$ComplexSerDe
2020-09-09T08:43:46.0680721Z [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.057 s - in org.apache.pulsar.functions.sink.PulsarSinkTest$ComplexSerDe
2020-09-09T08:43:46.0746826Z [INFO] Running org.apache.pulsar.functions.sink.PulsarSinkTest$2
2020-09-09T08:43:46.1701703Z [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.093 s - in org.apache.pulsar.functions.sink.PulsarSinkTest$2
2020-09-09T08:43:46.1711452Z [INFO] Running org.apache.pulsar.functions.sink.PulsarSinkTest$ComplexUserDefinedType
2020-09-09T08:43:46.2435018Z [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.07 s - in org.apache.pulsar.functions.sink.PulsarSinkTest$ComplexUserDefinedType
2020-09-09T08:43:46.2488662Z [INFO] Running org.apache.pulsar.functions.sink.PulsarSinkTest
2020-09-09T08:43:46.8351315Z [INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.909 s - in org.apache.pulsar.functions.instance.state.StateContextImplTest
2020-09-09T08:43:46.8364550Z [INFO] Running org.apache.pulsar.functions.sink.PulsarSinkTest$TestSerDe
2020-09-09T08:43:46.8723105Z [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.034 s - in org.apache.pulsar.functions.sink.PulsarSinkTest$TestSerDe
2020-09-09T08:43:46.8737509Z [INFO] Running org.apache.pulsar.functions.sink.PulsarSinkTest$3
2020-09-09T08:43:46.9159774Z [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.04 s - in org.apache.pulsar.functions.sink.PulsarSinkTest$3
2020-09-09T08:43:46.9205288Z [INFO] Running org.apache.pulsar.functions.source.PulsarSourceTest$ComplexSerDe
2020-09-09T08:43:46.9769821Z [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.044 s - in org.apache.pulsar.functions.source.PulsarSourceTest$ComplexSerDe
2020-09-09T08:43:46.9830881Z [INFO] Running org.apache.pulsar.functions.source.PulsarSourceTest$TestSerDe
2020-09-09T08:43:47.0269684Z [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.035 s - in org.apache.pulsar.functions.source.PulsarSourceTest$TestSerDe
2020-09-09T08:43:47.0543925Z [INFO] Running org.apache.pulsar.functions.source.batch.BatchSourceExecutorTest$TestBatchPushSource
2020-09-09T08:43:47.0974267Z [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.04 s - in org.apache.pulsar.functions.source.batch.BatchSourceExecutorTest$TestBatchPushSource
2020-09-09T08:43:47.1136536Z [INFO] Running org.apache.pulsar.functions.source.batch.BatchSourceExecutorTest$TestBatchSource
2020-09-09T08:43:47.1654499Z [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.049 s - in org.apache.pulsar.functions.source.batch.BatchSourceExecutorTest$TestBatchSource
2020-09-09T08:43:47.1775351Z [INFO] Running org.apache.pulsar.functions.source.batch.BatchSourceExecutorTest$TestDiscoveryTriggerer
2020-09-09T08:43:47.2261339Z [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.049 s - in org.apache.pulsar.functions.source.batch.BatchSourceExecutorTest$TestDiscoveryTriggerer
2020-09-09T08:43:47.2304114Z [INFO] Running org.apache.pulsar.functions.source.batch.BatchSourceExecutorTest
2020-09-09T08:43:47.3252873Z [INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.183 s - in org.apache.pulsar.functions.instance.ContextImplTest
2020-09-09T08:43:47.3339664Z [INFO] Running org.apache.pulsar.functions.source.batch.BatchSourceExecutorTest$1
2020-09-09T08:43:47.3371351Z [INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.845 s - in org.apache.pulsar.functions.instance.JavaInstanceTest
2020-09-09T08:43:47.3474941Z [INFO] Running org.apache.pulsar.functions.source.PulsarSourceTest
2020-09-09T08:43:47.3925931Z [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.047 s - in org.apache.pulsar.functions.source.batch.BatchSourceExecutorTest$1
2020-09-09T08:43:47.4078332Z [INFO] Running org.apache.pulsar.functions.source.PulsarSourceTest$ComplexUserDefinedType
2020-09-09T08:43:47.4758799Z [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.07 s - in org.apache.pulsar.functions.source.PulsarSourceTest$ComplexUserDefinedType
2020-09-09T08:43:47.4925616Z [INFO] Running org.apache.pulsar.functions.source.PulsarSourceTest$TopicMatcher
2020-09-09T08:43:47.5681621Z [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.074 s - in org.apache.pulsar.functions.source.PulsarSourceTest$TopicMatcher
2020-09-09T08:43:47.9748717Z [INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.719 s - in org.apache.pulsar.functions.sink.PulsarSinkTest
2020-09-09T08:43:48.4223500Z [INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.073 s - in org.apache.pulsar.functions.source.PulsarSourceTest
2020-09-09T08:43:48.8886422Z [INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.659 s - in org.apache.pulsar.functions.source.batch.BatchSourceExecutorTest
2020-09-09T08:43:49.2188254Z [INFO] 
2020-09-09T08:43:49.2188939Z [INFO] Results:
2020-09-09T08:43:49.2189233Z [INFO] 
2020-09-09T08:43:49.2195036Z [ERROR] Failures: 
2020-09-09T08:43:49.2195466Z [ERROR] org.apache.pulsar.functions.instance.InstanceUtilsTest.testCalculateSubjectTypeForFunction(org.apache.pulsar.functions.instance.InstanceUtilsTest)
2020-09-09T08:43:49.2199252Z [INFO]   Run 1: PASS
2020-09-09T08:43:49.2232939Z [ERROR]   Run 2: InstanceUtilsTest.testCalculateSubjectTypeForFunction:52 ? NoClassDefFound Cou...
2020-09-09T08:43:49.2233410Z [INFO] 
2020-09-09T08:43:49.2233898Z [ERROR] org.apache.pulsar.functions.instance.InstanceUtilsTest.testCalculateSubjectTypeForSink(org.apache.pulsar.functions.instance.InstanceUtilsTest)
2020-09-09T08:43:49.2234407Z [INFO]   Run 1: PASS
2020-09-09T08:43:49.2234878Z [ERROR]   Run 2: InstanceUtilsTest.testCalculateSubjectTypeForSink:68 ? NoClassDefFound Could n...
2020-09-09T08:43:49.2235041Z [INFO] 
2020-09-09T08:43:49.2235162Z [ERROR] org.apache.pulsar.functions.instance.InstanceUtilsTest.testCalculateSubjectTypeForSource(org.apache.pulsar.functions.instance.InstanceUtilsTest)
2020-09-09T08:43:49.2235265Z [INFO]   Run 1: PASS
2020-09-09T08:43:49.2235626Z [ERROR]   Run 2: InstanceUtilsTest.testCalculateSubjectTypeForSource:36 ? NoClassDefFound Could...
2020-09-09T08:43:49.2235756Z [INFO] 
2020-09-09T08:43:49.2235875Z [ERROR] org.apache.pulsar.functions.instance.JavaInstanceRunnableTest.testStatsManagerNull(org.apache.pulsar.functions.instance.JavaInstanceRunnableTest)
2020-09-09T08:43:49.2235997Z [INFO]   Run 1: PASS
2020-09-09T08:43:49.2236738Z [ERROR]   Run 2: JavaInstanceRunnableTest.testStatsManagerNull:114->createRunnable:61 ? NoClassDefFound
2020-09-09T08:43:49.2236851Z [INFO] 
2020-09-09T08:43:49.2236943Z [INFO] 
2020-09-09T08:43:49.2237045Z [ERROR] Tests run: 77, Failures: 4, Errors: 0, Skipped: 0
2020-09-09T08:43:49.2237131Z [INFO] 
2020-09-09T08:43:49.2331913Z [INFO] ------------------------------------------------------------------------
2020-09-09T08:43:49.2334533Z [INFO] Reactor Summary for Pulsar 2.7.0-SNAPSHOT:
2020-09-09T08:43:49.2335415Z [INFO] 
2020-09-09T08:43:49.2338669Z [INFO] Pulsar Build Tools ................................. SUCCESS [  1.220 s]
2020-09-09T08:43:49.2341888Z [INFO] Pulsar ............................................. SUCCESS [  1.546 s]
2020-09-09T08:43:49.2342328Z [INFO] Pulsar Test Mocks .................................. SUCCESS [  1.424 s]
2020-09-09T08:43:49.2344842Z [INFO] Pulsar Client :: API ............................... SUCCESS [  9.186 s]
2020-09-09T08:43:49.2348269Z [INFO] Pulsar Common ...................................... SUCCESS [ 42.615 s]
2020-09-09T08:43:49.2351249Z [INFO] Pulsar Metadata .................................... SUCCESS [  3.687 s]
2020-09-09T08:43:49.2354780Z [INFO] Managed Ledger ..................................... SUCCESS [ 40.395 s]
2020-09-09T08:43:49.2355277Z [INFO] Apache Pulsar :: Jclouds shaded .................... SUCCESS [  3.044 s]
2020-09-09T08:43:49.2359083Z [INFO] Apache Pulsar :: Tiered Storage :: Parent .......... SUCCESS [  0.040 s]
2020-09-09T08:43:49.2359515Z [INFO] Apache Pulsar :: Tiered Storage :: JCloud .......... SUCCESS [ 14.104 s]
2020-09-09T08:43:49.2363313Z [INFO] Apache Pulsar :: Tiered Storage :: File System ..... SUCCESS [ 12.827 s]
2020-09-09T08:43:49.2363752Z [INFO] Pulsar ZooKeeper Utils ............................. SUCCESS [ 11.395 s]
2020-09-09T08:43:49.2375241Z [INFO] pulsar-broker-common ............................... SUCCESS [ 12.115 s]
2020-09-09T08:43:49.2378688Z [INFO] Pulsar Transaction :: Parent ....................... SUCCESS [  0.216 s]
2020-09-09T08:43:49.2383531Z [INFO] Pulsar Transaction :: Common ....................... SUCCESS [  2.052 s]
2020-09-09T08:43:49.2400601Z [INFO] Apache Pulsar :: Bouncy Castle :: Parent ........... SUCCESS [  0.054 s]
2020-09-09T08:43:49.2404590Z [INFO] Apache Pulsar :: Bouncy Castle :: BC ............... SUCCESS [  1.099 s]
2020-09-09T08:43:49.2410201Z [INFO] Apache Pulsar :: Bouncy Castle :: BC Shaded ........ SUCCESS [  1.263 s]
2020-09-09T08:43:49.2416547Z [INFO] pulsar-client-messagecrypto-bc ..................... SUCCESS [  0.471 s]
2020-09-09T08:43:49.2424322Z [INFO] Pulsar Functions :: Parent ......................... SUCCESS [  0.023 s]
2020-09-09T08:43:49.2505427Z [INFO] Pulsar Functions :: Proto .......................... SUCCESS [  1.537 s]
2020-09-09T08:43:49.2513766Z [INFO] Pulsar Client Java ................................. SUCCESS [ 24.189 s]
2020-09-09T08:43:49.2519419Z [INFO] Pulsar Discovery Service WAR ....................... SUCCESS [  9.972 s]
2020-09-09T08:43:49.2521690Z [INFO] Pulsar WebSocket ................................... SUCCESS [  7.229 s]
2020-09-09T08:43:49.2523935Z [INFO] Pulsar Client Admin Original ....................... SUCCESS [ 11.140 s]
2020-09-09T08:43:49.2528092Z [INFO] Pulsar Functions :: API ............................ SUCCESS [  2.358 s]
2020-09-09T08:43:49.2530597Z [INFO] Pulsar IO :: Parent ................................ SUCCESS [  0.048 s]
2020-09-09T08:43:49.2532750Z [INFO] Pulsar IO :: IO .................................... SUCCESS [  3.277 s]
2020-09-09T08:43:49.2584576Z [INFO] pulsar-config-validation ........................... SUCCESS [  3.336 s]
2020-09-09T08:43:49.2587062Z [INFO] Pulsar Functions :: Utils .......................... SUCCESS [ 11.937 s]
2020-09-09T08:43:49.2589650Z [INFO] Pulsar Functions :: Secrets ........................ SUCCESS [  2.470 s]
2020-09-09T08:43:49.2591899Z [INFO] Pulsar Functions :: Instance ....................... FAILURE [ 12.839 s]
```

**Comment by jiazhai** [comment]
@wolfstudy Please update this issue once it get resolved

**Comment by wolfstudy** [comment]
> @wolfstudy Please update this issue once it get resolved

Sure

**Comment by wolfstudy** [comment]
Currently, the action ci in the master already works normally, so close this issue.
