### ISSUE TITLE
Pulsar Proxy caught exception

### ISSUE THREAD

**Issue by ndr-thitinan** [apache/pulsar#8420]
**Describe the bug**

**To Reproduce**
1. Set up/Run the Pulsar Proxy outside the proxy
2. Set up the Pulsar Proxy inside the proxy
3. Allow ACL for 6650, 6650, 8080, 8443
4. Tested the pulsar-client from the Pulsar Proxy to the Pulsar Broker: Success for both producer/consumer
5. Run the Pulsar Proxy
6. Test using the below command

`bin/pulsar-client --url pulsar://the.proxy.ip:6650 consume test -s "first-subscription"`

PS 1. I tried to use the --proxy-url and --proxy-protocol, it did't work.
PS 2. I checked the pulsar-client library, no setting for proxy so I assumed that using proxy url as a broker would be fine.
PS 3. Another reason for the previous PS is conf/proxy.conf has the URL for Pulsar Broker both of the pulsar:// and http://.
PS 4. I has the proxy config like below. Other options remain unchanged.

```
# if Service Discovery is Disabled this url should point to the discovery service provider.
brokerServiceURL=pulsar://the.broker.ip:6650
brokerServiceURLTLS=

# These settings are unnecessary if `zookeeperServers` is specified
brokerWebServiceURL=http://the.broker.ip:8080
brokerWebServiceURLTLS=

# If function workers are setup in a separate cluster, configure the following 2 settings
# to point to the function workers cluster
functionWorkerWebServiceURL=
functionWorkerWebServiceURLTLS=
.
.
.
# Whether client authorization credentials are forwared to the broker for re-authorization.
# Authentication must be enabled via authenticationEnabled=true for this to take effect.
forwardAuthorizationCredentials=true
```

**Expected behavior**
The following command works as usual.

`bin/pulsar-client --url pulsar://the.proxy.ip:6650 consume test -s "first-subscription"` 

**Desktop (please complete the following information):**
 - OS: 20.04.1 LTS (Focal Fossa)
 - Version: 2.6.1
 - Java Version:

```
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)
```

**Additional context**
The Pulsar Proxy gave the following error when get connected from the pulsar-client. 

```
01:28:12.790 [pulsar-proxy-io-2-1] INFO  org.apache.pulsar.proxy.server.ProxyConnection - [/the.client.ip:62031] New connection opened
01:28:12.793 [pulsar-proxy-io-2-1] INFO  org.apache.pulsar.proxy.server.ProxyConnection - [/the.client.ip:62031] complete connection, init proxy handler. authenticated with none role null, hasProxyToBrokerUrl: true
01:28:12.794 [pulsar-proxy-io-2-1] INFO  org.apache.pulsar.proxy.server.ProxyConnection - [/127.0.0.1:53436] New connection opened
01:28:12.797 [pulsar-proxy-io-2-1] INFO  org.apache.pulsar.proxy.server.ProxyConnection - [/127.0.0.1:53436] complete connection, init proxy handler. authenticated with none role null, hasProxyToBrokerUrl: false
01:28:12.803 [pulsar-proxy-io-2-1] WARN  io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.UnsupportedOperationException: null
        at org.apache.pulsar.common.protocol.PulsarDecoder.handleSubscribe(PulsarDecoder.java:460) ~[org.apache.pulsar-pulsar-common-2.6.1.jar:2.6.1]
        at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:215) ~[org.apache.pulsar-pulsar-common-2.6.1.jar:2.6.1]
        at org.apache.pulsar.proxy.server.ProxyConnection.channelRead(ProxyConnection.java:177) ~[org.apache.pulsar-pulsar-proxy-2.6.1.jar:2.6.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321) [io.netty-netty-codec-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295) [io.netty-netty-codec-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) [io.netty-netty-transport-native-epoll-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) [io.netty-netty-transport-native-epoll-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [io.netty-netty-transport-native-epoll-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty-netty-common-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty-netty-common-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.48.Final.jar:4.1.48.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
01:28:12.808 [pulsar-proxy-io-2-1] WARN  org.apache.pulsar.proxy.server.ProxyConnection - [/127.0.0.1:53436] Got exception UnsupportedOperationException : null java.lang.UnsupportedOperationException
01:28:12.814 [pulsar-proxy-io-2-1] INFO  org.apache.pulsar.client.impl.PulsarClientImpl - Client closing. URL: pulsar://the.proxy.ip:6650/
01:28:12.814 [pulsar-client-shutdown-thread] INFO  org.apache.pulsar.proxy.server.ProxyConnectionPool - Closing ProxyConnectionPool.
01:28:12.815 [pulsar-proxy-io-2-1] INFO  org.apache.pulsar.proxy.server.ProxyConnection - [/127.0.0.1:53436] Connection closed
01:28:12.816 [pulsar-proxy-io-2-1] INFO  org.apache.pulsar.client.impl.PulsarClientImpl - Client closing. URL: pulsar://the.proxy.ip:6650/
01:28:12.818 [pulsar-client-shutdown-thread] INFO  org.apache.pulsar.proxy.server.ProxyConnectionPool - Closing ProxyConnectionPool.
01:28:12.819 [pulsar-proxy-io-2-1] INFO  org.apache.pulsar.proxy.server.ProxyConnection - [/the.client.ip:62031] Connection closed
01:28:13.165 [pulsar-proxy-io-2-1] INFO  org.apache.pulsar.client.impl.PulsarClientImpl - Client closing. URL: pulsar://the.proxy.ip:6650/
01:28:13.165 [pulsar-client-shutdown-thread] INFO  org.apache.pulsar.proxy.server.ProxyConnectionPool - Closing ProxyConnectionPool.
01:28:13.165 [pulsar-proxy-io-2-1] INFO  org.apache.pulsar.proxy.server.ProxyConnection - [/the.client.ip:61975] Connection closed
01:28:13.166 [pulsar-proxy-io-2-1] INFO  org.apache.pulsar.client.impl.ClientCnx - [id: 0x5bac0d88, L:/the.proxy.ip:60026 ! R:the.broker.ip/the.broker.ip:6650] Disconnected
01:28:13.167 [pulsar-proxy-io-2-1] INFO  org.apache.pulsar.client.impl.ClientCnx - [id: 0x516064a6, L:/the.proxy.ip:60028 ! R:the.broker.ip/the.broker.ip:6650] Disconnected
```

**Comment by ndr-thitinan** [comment]
I found the problem.

Because the Pulsar server using the standalone mode, the advertisedAddress= inside the conf/standalone.conf file needed to be set. After setting this the exception is gone.
