### ISSUE TITLE
Flaky-test: KeySharedSubscriptionTest.testContinueDispatchMessagesWhenMessageTTL

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#8512]
The test KeySharedSubscriptionTest.testContinueDispatchMessagesWhenMessageTTL is flaky.

[example failure](https://github.com/apache/pulsar/pull/8511/checks?check_run_id=1381553002#step:11:458):
```
Error:  Tests run: 36, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 180.866 s <<< FAILURE! - in org.apache.pulsar.client.api.KeySharedSubscriptionTest
Error:  testContinueDispatchMessagesWhenMessageTTL(org.apache.pulsar.client.api.KeySharedSubscriptionTest)  Time elapsed: 8.447 s  <<< FAILURE!
java.lang.AssertionError: expected object to not be null
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.assertNotNull(Assert.java:942)
	at org.testng.Assert.assertNotNull(Assert.java:926)
	at org.apache.pulsar.client.api.KeySharedSubscriptionTest.testContinueDispatchMessagesWhenMessageTTL(KeySharedSubscriptionTest.java:855)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
