### ISSUE TITLE
Cannot run Pulsar Bookie on JDK14+

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#8558]
**Describe the bug**
The Bookie cannot start on JDK14, this is the error.
the command is
`bin/pulsar bookie`

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.apache.bookkeeper.util.EventLoopUtil.getEventLoopGroup(EventLoopUtil.java:52)
	at org.apache.bookkeeper.util.EventLoopUtil.getServerEventLoopGroup(EventLoopUtil.java:47)
	at org.apache.bookkeeper.proto.BookieNettyServer.<init>(BookieNettyServer.java:122)
	at org.apache.bookkeeper.proto.BookieServer.<init>(BookieServer.java:106)
	at org.apache.bookkeeper.server.service.BookieService.<init>(BookieService.java:52)
	at org.apache.bookkeeper.server.Main.buildBookieServer(Main.java:313)
	at org.apache.bookkeeper.server.Main.doMain(Main.java:226)
	at org.apache.bookkeeper.server.Main.main(Main.java:208)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 2
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3734)
	at java.base/java.lang.String.substring(String.java:1903)
	at org.apache.commons.lang.SystemUtils.getJavaVersionAsFloat(SystemUtils.java:1133)
	at org.apache.commons.lang.SystemUtils.<clinit>(SystemUtils.java:818)
	... 8 more


```
**Expected behavior**

The bookie should start

**Additional context**
Probably it is just a matter of upgrading Commons Lang Dependecy

**Comment by eolivelli** [comment]
I am sending a patch with the dependency upgrade

**Comment by eolivelli** [comment]
Issue https://github.com/sundrio/sundrio/issues/153
