### ISSUE TITLE
Tests of pulsar-functions-runtime are not passing on 2.7.0rc1 - if you do not have a local Kubernets environment

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#8673]
**Describe the bug**
Tests are not passing due to an error on Kubernetes client runtime, it created to a default configuration, failing with a NullPointerException. 

**To Reproduce**
- build pulsar from 2.7.0rc1 sources
- run tests in pulsar-functions-runtime

**Expected behavior**
Tests are passing 

**Desktop (please complete the following information):**
 - OS: Fedora
- Maven 3.6.3
- JDK 1.8 (OpenJDK)

**Additional context**
```
[ERROR] testResources(org.apache.pulsar.functions.runtime.kubernetes.KubernetesRuntimeTest)  Time elapsed: 0.011 s  <<< FAILURE!
java.lang.RuntimeException: java.lang.NullPointerException
	at org.apache.pulsar.functions.runtime.kubernetes.KubernetesRuntimeFactory.initialize(KubernetesRuntimeFactory.java:211)
	at org.apache.pulsar.functions.runtime.kubernetes.KubernetesRuntimeTest.createKubernetesRuntimeFactory(KubernetesRuntimeTest.java:217)
	at org.apache.pulsar.functions.runtime.kubernetes.KubernetesRuntimeTest.createKubernetesRuntimeFactory(KubernetesRuntimeTest.java:225)
	at org.apache.pulsar.functions.runtime.kubernetes.KubernetesRuntimeTest.testResources(KubernetesRuntimeTest.java:340)
	at org.apache.pulsar.functions.runtime.kubernetes.KubernetesRuntimeTest.testResources(KubernetesRuntimeTest.java:324)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at io.kubernetes.client.util.ClientBuilder.kubeconfig(ClientBuilder.java:259)
	at io.kubernetes.client.util.ClientBuilder.getClientBuilder(ClientBuilder.java:108)
	at io.kubernetes.client.util.ClientBuilder.standard(ClientBuilder.java:87)
	at io.kubernetes.client.util.ClientBuilder.standard(ClientBuilder.java:79)
	at io.kubernetes.client.util.Config.defaultClient(Config.java:113)
	at org.apache.pulsar.functions.runtime.kubernetes.KubernetesRuntimeFactory.setupClient(KubernetesRuntimeFactory.java:339)
	at org.apache.pul
```

**Comment by eolivelli** [comment]
The same error is on pulsar-functions-worker module
```

java.lang.RuntimeException: java.lang.NullPointerException
	at org.apache.pulsar.functions.runtime.kubernetes.KubernetesRuntimeFactory.initialize(KubernetesRuntimeFactory.java:211)
	at org.apache.pulsar.functions.worker.FunctionRuntimeManager.<init>(FunctionRuntimeManager.java:211)
	at org.apache.pulsar.functions.worker.FunctionRuntimeManagerTest.testExternallyManagedRuntimeUpdate(FunctionRuntimeManagerTest.java:674)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at io.kubernetes.client.util.ClientBuilder.kubeconfig(ClientBuilder.java:259)
	at io.kubernetes.client.util.ClientBuilder.getClientBuilder(ClientBuilder.java:108)
	at io.kubernetes.client.util.ClientBuilder.standard(ClientBuilder.java:87)
	at io.kubernetes.client.util.ClientBuilder.standard(ClientBuilder.java:79)
	at io.kubernetes.client.util.Config.defaultClient(Config.java:113)
	at org.apache.pulsar.functions.runtime.kubernetes.KubernetesRuntimeFactory.setupClient(KubernetesRuntimeFactory.java:339)
	at org.apache.pulsar.functions.runtime.kubernetes.KubernetesRuntimeFactory.initialize(KubernetesRuntimeFactory.java:208)
	... 14 more

```

**Comment by jiazhai** [comment]
@wolfstudy is helping on this issue.

**Comment by wolfstudy** [comment]
Hello @eolivelli More info reference to: https://apache-pulsar.slack.com/archives/C5ZSVEN4E/p1606187284156200?thread_ts=1606147723.154600&cid=C5ZSVEN4E

**Comment by eolivelli** [comment]
I have resolved my local problem by starting a **minikube instance** 

This is something we should document in some "how-to-build" document.

As we are releasing a source package the users must able to build it and all tests MUST pass, otherwise it is impossible for downstream users to check if the code is in good shape.

cc @ivankelly @merlimat @sijie @rdhabalia @jiazhai
