### ISSUE TITLE
Unauthorized Error when I use PulsarAdmin  API to query  another host's ownedNamespaces

### ISSUE THREAD

**Issue by xiaotongwang1** [apache/pulsar#8700]
1、init code with one ip of cluster
`       PulsarAdminBuilder pulsarAdminBuilder = PulsarAdmin.builder().serviceHttpUrl("http://host-10-33-50-144:8080");`
2、getActiveBrokers and getOwnedNamespaces
```
        List<String> brokers = adminClient.brokers().getActiveBrokers("pulsar-cluster-1");
        System.out.println("current brokers : " + brokers);
        for (String brokerUrl : brokers) {
            System.out.println("current broker : " + brokerUrl + "-->"
                + adminClient.brokers().getOwnedNamespaces("pulsar-cluster-1", brokerUrl));
        }
```

current brokers : [host-10-33-50-144:8080, host-10-33-50-71:8080, host-10-33-50-88:8080]
current broker : host-10-33-50-144:8080-->{pulsar/pulsar-cluster-1/host-10-33-50-144:8080/0x00000000_0xffffffff=[broker_assignment=shared is_controlled=false is_active=true]}
Exception in thread "main" org.apache.pulsar.client.admin.PulsarAdminException$NotAuthorizedException: HTTP 401 Unauthorized

doubt：can not getOwnedNamespaces if admin builder serviceHttpUrl host not the same with brokerUrl

https://github.com/apache/pulsar/issues/8681 Basic function bug : multi hots like http://localhost:8080,localhost:8081,localhost:8082 not work in sasl auth serviceUrl scenario #8681

should i need to create 3 PulsarAdmin instance to query 3  serevr's

**Comment by yanshuchong** [comment]
some error log 
9:54:25.058 [pulsar-web-42-12] ERROR org.apache.pulsar.broker.admin.impl.PersistentTopicsBase - [client@MY.REALM] Failed to get list of subscriptions for persistent://www/mynamespace/wxt.mq1-partition-1
javax.ws.rs.WebApplicationException: HTTP 307 Temporary Redirect
	at org.apache.pulsar.broker.web.PulsarWebResource.validateTopicOwnership(PulsarWebResource.java:598) ~[org.apache.pulsar-pulsar-broker-2.6.0.jar:2.6.0]
	at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.validateReadOperationOnTopic(PersistentTopicsBase.java:245) ~[org.apache.pulsar-pulsar-broker-2.6.0.jar:2.6.0]
	at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.internalGetSubscriptionsForNonPartitionedTopic(PersistentTopicsBase.java:874) ~[org.apache.pulsar-pulsar-broker-2.6.0.jar:2.6.0]
	at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.internalGetSubscriptions(PersistentTopicsBase.java:825) ~[org.apache.pulsar-pulsar-broker-2.6.0.jar:2.6.0]
	at org.apache.pulsar.broker.admin.v2.PersistentTopics.getSubscriptions(PersistentTopics.java:461) ~[org.apache.pulsar-pulsar-broker-2.6.0.jar:2.6.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76) ~[org.glassfish.jersey.core-jersey-server-2.27.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148) [org.glassfish.jersey.core-jersey-server-2.27.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191) [org.glassfish.jersey.core-jersey-server-2.27.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:183) [org.glassfish.jersey.core-jersey-server-2.27.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103) [org.glassfish.jersey.core-jersey-server-2.27.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493) [org.glassfish.jersey.core-jersey-server-2.27.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415) [org.glassfish.jersey.core-jersey-server-2.27.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104) [org.glassfish.jersey.core-jersey-server-2.27.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277) [org.glassfish.jersey.core-jersey-server-2.27.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272) [org.glassfish.jersey.core-jersey-common-2.27.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268) [org.glassfish.jersey.core-jersey-common-2.27.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316) [org.glassfish.jersey.core-jersey-common-2.27.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298) [org.glassfish.jersey.core-jersey-common-2.27.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268) [org.glassfish.jersey.core-jersey-common-2.27.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289) [org.glassfish.jersey.core-jersey-common-2.27.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256) [org.glassfish.jersey.core-jersey-server-2.27.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703) [org.glassfish.jersey.core-jersey-server-2.27.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416) [org





and 


Exception in thread "main" org.apache.pulsar.client.admin.PulsarAdminException$NotAuthorizedException: HTTP 401 Unauthorized
	at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:217)
	at org.apache.pulsar.client.admin.internal.TopicsImpl$9.failed(TopicsImpl.java:613)
	at org.glassfish.jersey.client.JerseyInvocation$4.failed(JerseyInvocation.java:1030)
	at org.glassfish.jersey.client.JerseyInvocation$4.completed(JerseyInvocation.java:1017)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:227)
	at org.glassfish.jersey.client.ClientRuntime.access$200(ClientRuntime.java:85)
	at org.glassfish.jersey.client.ClientRuntime$2.lambda$response$0(ClientRuntime.java:178)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)

**Comment by yanshuchong** [comment]
another api  adminClient.topics().getSubscriptions(topic) have same problem  with package 

Server 1 :
GET /admin/v2/persistent/www/mynamespace/wxt.mq1-partition-1/subscriptions HTTP/1.1
Accept: application/json
SASL-Type: Kerberos
SaslAuthRoleToken: u=client@MY.REALM&i=6&e=1606309235270&s=eF1GLXyx4QL4+zZsYJTygDVnagBgDDnf016sR5TuCNSHfFmM8bTsNeDOT4hzkG+8wFLm1eKkAm89GEdG3Pq0Pg==
State: Done
host: host-10-33-50-71:8080
user-agent: Pulsar-Java-v2.6.1
>t<,
HTTP/1.1 307 Temporary Redirect
Date: Wed, 25 Nov 2020 12:00:38 GMT
Location: http://host-10-33-50-144:8080/admin/v2/persistent/www/mynamespace/wxt.mq1-partition-1/subscriptions?authoritative=false
broker-address: host-10-33-50-71
Content-Length: 0
Server: Jetty(9.4.20.v20190813)



Server 2
tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
GET /admin/v2/persistent/www/mynamespace/wxt.mq1-partition-1/subscriptions?authoritative=false HTTP/1.1
Accept: application/json
SASL-Type: Kerberos
SaslAuthRoleToken: u=client@MY.REALM&i=6&e=1606309235270&s=eF1GLXyx4QL4+zZsYJTygDVnagBgDDnf016sR5TuCNSHfFmM8bTsNeDOT4hzkG+8wFLm1eKkAm89GEdG3Pq0Pg==
State: Done
host: host-10-33-50-144:8080
user-agent: Pulsar-Java-v2.6.1
HTTP/1.1 401 Authentication required
Date: Wed, 25 Nov 2020 12:00:38 GMT
Cache-Control: must-revalidate,no-cache,no-store
Content-Length: 0

**Comment by yanshuchong** [comment]
the PulsarBroker  kerberos principal in each server are different 
Is that the problem?

i will do some test

**Comment by yanshuchong** [comment]
10:08:09.894 [pulsar-web-42-8] ERROR org.apache.pulsar.client.impl.auth.PulsarSaslClient - SASL error
10:08:09.894 [pulsar-web-42-8] INFO  org.apache.pulsar.client.impl.auth.PulsarSaslClient - Using JAAS/SASL/GSSAPI auth to connect to server Principal broker/host-10-33-50-115,
10:08:09.900 [pulsar-web-42-8] ERROR org.apache.pulsar.client.impl.auth.PulsarSaslClient - SASL error
10:08:09.901 [pulsar-web-42-8] INFO  org.apache.pulsar.client.impl.auth.PulsarSaslClient - Using JAAS/SASL/GSSAPI auth to connect to server Principal broker/host-10-33-50-115,
10:08:09.908 [pulsar-web-42-8] ERROR org.apache.pulsar.client.impl.auth.PulsarSaslClient - SASL error
10:08:09.908 [pulsar-web-42-8] INFO  org.apache.pulsar.client.impl.auth.PulsarSaslClient - Using JAAS/SASL/GSSAPI auth to connect to server Principal broker/host-10-33-50-115,
10:08:09.915 [pulsar-web-42-8] ERROR org.apache.pulsar.client.impl.auth.PulsarSaslClient - SASL error
10:08:09.915 [pulsar-web-42-8] INFO  org.apache.pulsar.client.impl.auth.PulsarSaslClient - Using JAAS/SASL/GSSAPI auth to connect to server Principal broker/host-10-33-50-115,
10:08:09.922 [pulsar-web-42-8] ERROR org.apache.pulsar.client.impl.auth.PulsarSaslClient - SASL error
10:08:09.923 [pulsar-web-42-8] INFO  org.apache.pulsar.client.impl.auth.PulsarSaslClient - Using JAAS/SASL/GSSAPI auth to connect to server Principal broker/host-10-33-50-115,
10:08:09.928 [pulsar-web-42-8] ERROR org.apache.pulsar.client.impl.auth.PulsarSaslClient - SASL error
10:08:09.929 [pulsar-web-42-8] INFO  org.apache.pulsar.client.impl.auth.PulsarSaslClient - Using JAAS/SASL/GSSAPI auth to connect to server Principal broker/host-10-33-50-115,
10:08:09.933 [pulsar-web-42-8] ERROR org.apache.pulsar.client.impl.auth.PulsarSaslClient - SASL error
10:08:09.934 [pulsar-web-42-8] INFO  org.apache.pulsar.client.impl.auth.PulsarSaslClient - Using JAAS/SASL/GSSAPI auth to connect to server Principal broker/host-10-33-50-115,
10:08:09.941 [pulsar-web-42-8] ERROR org.apache.pulsar.client.impl.auth.PulsarSaslClient - SASL error


i use same principal  for broker ,but i found some error log ,maybe PulsarSaslClient  --> broker  some problem whit this

**Comment by yanshuchong** [comment]
AuthenticationProviderSasl  this.signer = new SaslRoleTokenSigner(Long.toString(new Random().nextLong()).getBytes());
sign will failed when HTTP/1.1 307 Temporary Redirect


SaslAuthRoleToken sign by broker1 ,so broker2 will verify failed for the signer are different

**Comment by yanshuchong** [comment]
finally i try to change the code of  org.apache.pulsar.broker.authentication.AuthenticationProviderSasl

line 98： this.signer = new SaslRoleTokenSigner(Long.toString(new Random().nextLong()).getBytes());

to 
 this.signer = new SaslRoleTokenSigner("xxxxx".getBytes());

and repleace all  the broker ,make sure all  the broker have the  same secret ,and the cross request will be sign success

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.
