### ISSUE TITLE
Can't deploy Stateful Pulsar Functions

### ISSUE THREAD

**Issue by david-streamlio** [apache/pulsar#8752]
**Describe the bug**
Getting the following error when deploying a Stateful Pulsar Function on a docker container running the apachepulsar/standalone:latest version of the Docker Image.

```
 Uncaught exception in Java Instance
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;)V
	at org.apache.bookkeeper.clients.config.StorageClientSettings_Builder.build(StorageClientSettings_Builder.java:455) ~[stream-storage-java-client-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.clients.config.StorageClientSettings$Builder.build(StorageClientSettings.java:120) ~[stream-storage-java-client-4.10.0.jar:4.10.0]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.setupStateTable(JavaInstanceRunnable.java:395) ~[pulsar-functions-instance-2.6.2.jar:2.6.2]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.setup(JavaInstanceRunnable.java:221) ~[pulsar-functions-instance-2.6.2.jar:2.6.2]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:248) [pulsar-functions-instance-2.6.2.jar:2.6.2]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

**To Reproduce**
1. Start a Docker container using apachepulsar/pulsar-standalone:latest
2. Start a LocalRunner instance pointing to the container, e.g. 
    localRunner = LocalRunner.builder()
				.brokerServiceUrl(BROKER_URL). <----- pulsar://localhost:6650
				.stateStorageServiceUrl(STATE_STORE_URL). <---- bk://localhost:4181
				.functionConfig(getFunctionConfig())
				.build();
		localRunner.start(false);
3. Specify a Stateful Pulsar Function in the passed in function config specified in `getFunctionConfig()`, e.g. have calls to `ctx.putState()` inside the code

**Expected behavior**
No error should be raised

**Additional context**
I believe the bookkeeper version (4.10) deployed in the Docker image is 2 version behind now and needs updated

**Comment by eolivelli** [comment]
The current master of Pulsar is using BK 4.12.

Btw it looks like a compatibility problem with Guava and not directly with BK version

**Comment by david-streamlio** [comment]
Thanks Enrico. The problem is that the current apachepulsar/pulsar-standalone:latest Docker image published on DockerHub still contains the older version (4.10) of all the BK jars.  I think someone with publish permission for the apachepulsar/pulsar-standalone image needs to just run and publish a newer version that is based on the the 2.8.0 version IMHO

**Comment by jiazhai** [comment]
@david-streamlio This step is include in the 2.7 release. @codelipenghui  updated it 21 hours ago. not the latest tag is the same as 2.7.0 tag. 
It should be Ok now. Would you please verify the issue fixed?

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.
