### ISSUE TITLE
Intermittent test failure: org.apache.pulsar.client.api.DispatcherBlockConsumerTest.testBlockBrokerDispatching

### ISSUE THREAD

**Issue by rdhabalia** [apache/pulsar#878]
[Build](https://builds.apache.org/job/pulsar-pull-request/org.apache.pulsar$pulsar-broker/671/testReport/junit/org.apache.pulsar.client.api/DispatcherBlockConsumerTest/testBlockBrokerDispatching/)

```
Error Message

expected [2] but found [1]
Stacktrace

java.lang.AssertionError: expected [2] but found [1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:265)
	at org.testng.Assert.assertEquals(Assert.java:275)
	at org.apache.pulsar.client.api.DispatcherBlockConsumerTest.testBlockBrokerDispatching(DispatcherBlockConsumerTest.java:804)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jiazhai** [comment]
close this issue, since the test is running well in current ci.
