### ISSUE TITLE
Test BatchMessageIndexAckTest.testDoNotRecycleAckSetMultipleTimes is failing

### ISSUE THREAD

**Issue by merlimat** [apache/pulsar#8825]
There's a bug in master and tests are failing.

The issue was introduced in #8161 and the test `BatchMessageIndexAckTest.testDoNotRecycleAckSetMultipleTimes` is failing as a result, although apparently is not being run from Github. 

```
FAILED: testDoNotRecycleAckSetMultipleTimes
java.lang.IllegalStateException: recycled multiple times
	at io.netty.util.Recycler$Stack.pop(Recycler.java:567)
	at io.netty.util.Recycler.get(Recycler.java:174)
	at org.apache.pulsar.common.util.collections.BitSetRecyclable.create(BitSetRecyclable.java:1200)
	at org.apache.pulsar.client.impl.PersistentAcknowledgmentsGroupingTracker.addBatchIndexAcknowledgment(PersistentAcknowledgmentsGroupingTracker.java:188)
	at org.apache.pulsar.client.impl.ConsumerImpl.doAcknowledge(ConsumerImpl.java:582)
	at org.apache.pulsar.client.impl.ConsumerBase.doAcknowledgeWithTxn(ConsumerBase.java:503)
	at org.apache.pulsar.client.impl.ConsumerBase.acknowledgeCumulativeAsync(ConsumerBase.java:463)
	at org.apache.pulsar.client.impl.ConsumerBase.acknowledgeCumulativeAsync(ConsumerBase.java:448)
	at org.apache.pulsar.client.impl.ConsumerBase.acknowledgeCumulative(ConsumerBase.java:348)
	at org.apache.pulsar.client.impl.ConsumerBase.acknowledgeCumulative(ConsumerBase.java:339)
	at org.apache.pulsar.client.impl.BatchMessageIndexAckTest.testDoNotRecycleAckSetMultipleTimes(BatchMessageIndexAckTest.java:231)
```

We should also understand why the PR validation jobs are not running all the tests and which ones are missing.

@congbobo @codelipenghui Please take a look.

**Comment by codelipenghui** [comment]
@merlimat Thanks, we will take a look soon.

**Comment by merlimat** [comment]
Thanks for fixing this quickly

**Comment by codelipenghui** [comment]
close this issue via #8829
