### ISSUE TITLE
NullPointerException while boostrapping a Producer with a Reader with a Schema  (pulsar 2.8.0-SNAPSHOT) standalone

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#8836]
**Describe the bug**

A NullPointerException happens when you create a Producer, write messages with a Schema, then start a Reader on the topic.
Using current master at 05c91569b5ec7e2b83395b8f30f7802912e793a7

Steps
- start pulsar standalone
- create a Java Producer with Avro schema, on persistent://public/default/topic
- topic is auto created
- create a reader with the same Java schema
- see the error

The problem looks like a non blocker, but usually a NPE is a symptom of something broken, so we should not fall into this case.
 

```
09:52:49.212 [ForkJoinPool.commonPool-worker-1] ERROR org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [public/default/persistent/topic] Can't find next valid position, fail back to the next position of the last position.
java.lang.NullPointerException: null
	at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.getNextValidPositionInternal(ManagedLedgerImpl.java:2942) ~[managed-ledger.jar:2.8.0-SNAPSHOT]
	at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.getNextValidPosition(ManagedLedgerImpl.java:2929) ~[managed-ledger.jar:2.8.0-SNAPSHOT]
	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.rewind(ManagedCursorImpl.java:2045) ~[managed-ledger.jar:2.8.0-SNAPSHOT]
	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherSingleActiveConsumer.scheduleReadOnActiveConsumer(PersistentDispatcherSingleActiveConsumer.java:113) ~[pulsar-broker.jar:2.8.0-SNAPSHOT]
	at org.apache.pulsar.broker.service.AbstractDispatcherSingleActiveConsumer.pickAndScheduleActiveConsumer(AbstractDispatcherSingleActiveConsumer.java:129) ~[pulsar-broker.jar:2.8.0-SNAPSHOT]
	at org.apache.pulsar.broker.service.AbstractDispatcherSingleActiveConsumer.addConsumer(AbstractDispatcherSingleActiveConsumer.java:162) ~[pulsar-broker.jar:2.8.0-SNAPSHOT]
	at org.apache.pulsar.broker.service.persistent.PersistentSubscription.addConsumer(PersistentSubscription.java:227) ~[pulsar-broker.jar:2.8.0-SNAPSHOT]
	at org.apache.pulsar.broker.service.AbstractTopic.addConsumerToSubscription(AbstractTopic.java:206) ~[pulsar-broker.jar:2.8.0-SNAPSHOT]
	at org.apache.pulsar.broker.service.persistent.PersistentTopic.lambda$subscribe$12(PersistentTopic.java:649) ~[pulsar-broker.jar:2.8.0-SNAPSHOT]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_242]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) ~[?:1.8.0_242]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) ~[?:1.8.0_242]
	at org.apache.pulsar.broker.service.persistent.PersistentTopic.subscribe(PersistentTopic.java:645) ~[pulsar-broker.jar:2.8.0-SNAPSHOT]
	at org.apache.pulsar.broker.service.ServerCnx.lambda$null$12(ServerCnx.java:921) ~[pulsar-broker.jar:2.8.0-SNAPSHOT]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966) ~[?:1.8.0_242]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940) ~[?:1.8.0_242]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_242]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) ~[?:1.8.0_242]
	at org.apache.pulsar.broker.service.schema.BookkeeperSchemaStorage.lambda$null$5(BookkeeperSchemaStorage.java:193) ~[pulsar-broker.jar:2.8.0-SNAPSHOT]
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:836) [?:1.8.0_242]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:811) [?:1.8.0_242]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457) [?:1.8.0_242]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_242]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_242]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_242]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_242]

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
