### ISSUE TITLE
Intermittent test failure: DispatcherBlockConsumerTest.testConsumerBlockingWithUnAckedMessagesAndRedelivery

### ISSUE THREAD

**Issue by rdhabalia** [apache/pulsar#886]
[build](https://builds.apache.org/job/pulsar-pull-request/org.apache.pulsar$pulsar-broker/681/testReport/junit/org.apache.pulsar.client.api/DispatcherBlockConsumerTest/testConsumerBlockingWithUnAckedMessagesAndRedelivery/)

```
Error Message

expected [true] but found [false]
Stacktrace

java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at org.apache.pulsar.client.api.DispatcherBlockConsumerTest.testConsumerBlockingWithUnAckedMessagesAndRedelivery(DispatcherBlockConsumerTest.java:288)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jiazhai** [comment]
currently, this is still ignored in the code, we could try to open this to have a try. mark this as help wanted, so developer, who would like to contribute to it, could help on this.

```
    /**
     *
     * Verifies: broker blocks dispatching once unack-msg reaches to max-limit. However, on redelivery it redelivers
     * those already delivered-unacked messages again
     *
     * @throws Exception
     */
    @SuppressWarnings("unchecked")
    @Test(enabled = false) // See https://github.com/apache/pulsar/issues/5438
    public void testConsumerBlockingWithUnAckedMessagesAndRedelivery() throws Exception {
...
```

**Comment by tisonkun** [comment]
Closed as stale.

I'll try to schedule some time to revive disabled tests. But it should be a brand new thread. Currently, there is no "unstable test testConsumerBlockingWithUnAckedMessagesAndRedelivery".
