### ISSUE TITLE
Flaky-test: Integration tests: PulsarStateTest#testSinkState

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#8897]
I have seen this temporary error on current master 6987d911897e66c384f8791535681f90887436b4

**Additional context**
pulsar-standalone-suite(org.apache.pulsar.tests.integration.functions.PulsarStateTest)  Time elapsed: 15.033 s  <<< FAILURE!
java.lang.AssertionError: expected [val1-9] but found [val1-7]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:629)
	at org.testng.Assert.assertEquals(Assert.java:639)
	at org.apache.pulsar.tests.integration.functions.PulsarStateTest.testSinkState(PulsarStateTest.java:182)

**Comment by tisonkun** [comment]
Closed as stale.

It should be resolved by #9870.
