### ISSUE TITLE
Flaky-test: org.apache.pulsar.tests.integration.presto.TestBasicPresto

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#8923]
TestBasicPresto is flaky. It fails sporadically.

[example failure](https://github.com/apache/pulsar/pull/8918/checks?check_run_id=1537345628#step:13:3716)

```
14:05:48.212 [delayer-47-1] ERROR org.apache.pulsar.broker.admin.v2.NonPersistentTopics - [null] Failed to get list of topics under namespace public/default
...
Error:  Tests run: 3, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 191.765 s <<< FAILURE! - in TestSuite
Error:  pulsar-test-suite(org.apache.pulsar.tests.integration.presto.TestBasicPresto)  Time elapsed: 35.365 s  <<< FAILURE!
org.apache.pulsar.tests.integration.docker.ContainerExecException: /bin/bash -c /pulsar/bin/pulsar sql --execute 'show tables in pulsar."public/default";' failed on d47fcd40a995010b1ab4aab278b0879fface6cf915cc5e1fd52577e1eba48b61 with error code 1
	at org.apache.pulsar.tests.integration.utils.DockerUtils$2.onComplete(DockerUtils.java:259)
	at com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec$1.onComplete(AbstrAsyncDockerCmdExec.java:51)
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.lambda$executeAndStream$4(OkHttpInvocationBuilder.java:331)
	at java.lang.Thread.run(Thread.java:748)
```

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
14:05:27.907 [pulsar-load-manager-1-1] INFO  org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerImpl - Writing local data to ZooKeeper because maximum change 100.0% exceeded threshold 10%; time since last report written is 15.0 seconds
14:05:27.908 [pulsar-ordered-OrderedExecutor-3-0-EventThread] INFO  org.apache.pulsar.zookeeper.ZooKeeperDataCache - [State:CONNECTED Timeout:30000 sessionid:0x100002aff64000e local:/172.18.0.6:52644 remoteserver:zookeeper/172.18.0.2:2181 lastZxid:156 xid:585 sent:585 recv:596 queuedpkts:0 pendingresp:1 queuedevents:0] Received ZooKeeper watch event: WatchedEvent state:SyncConnected type:NodeDataChanged path:/loadbalance/brokers/pulsar-broker-0:8080
14:05:40.349 [pulsar-ordered-OrderedExecutor-3-0-EventThread] INFO  org.apache.pulsar.zookeeper.ZooKeeperDataCache - [State:CONNECTED Timeout:30000 sessionid:0x100002aff64000e local:/172.18.0.6:52644 remoteserver:zookeeper/172.18.0.2:2181 lastZxid:157 xid:592 sent:592 recv:605 queuedpkts:0 pendingresp:0 queuedevents:0] Received ZooKeeper watch event: WatchedEvent state:SyncConnected type:NodeDataChanged path:/loadbalance/brokers/pulsar-broker-1:8080
14:05:48.212 [delayer-47-1] ERROR org.apache.pulsar.broker.admin.v2.NonPersistentTopics - [null] Failed to get list of topics under namespace public/default
java.util.concurrent.ExecutionException: org.apache.pulsar.client.admin.PulsarAdminException: java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_275]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908) ~[?:1.8.0_275]
	at org.apache.pulsar.broker.admin.v2.NonPersistentTopics.lambda$getList$1(NonPersistentTopics.java:283) ~[org.apache.pulsar-pulsar-broker-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:836) ~[?:1.8.0_275]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:811) ~[?:1.8.0_275]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_275]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) ~[?:1.8.0_275]
	at org.apache.pulsar.client.admin.internal.TopicsImpl$5.failed(TopicsImpl.java:233) ~[org.apache.pulsar-pulsar-client-admin-original-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	at org.glassfish.jersey.client.JerseyInvocation$1.failed(JerseyInvocation.java:839) ~[org.glassfish.jersey.core-jersey-client-2.31.jar:?]
	at org.glassfish.jersey.client.ClientRuntime.processFailure(ClientRuntime.java:247) ~[org.glassfish.jersey.core-jersey-client-2.31.jar:?]
	at org.glassfish.jersey.client.ClientRuntime.processFailure(ClientRuntime.java:242) ~[org.glassfish.jersey.core-jersey-client-2.31.jar:?]
	at org.glassfish.jersey.client.ClientRuntime.access$100(ClientRuntime.java:62) ~[org.glassfish.jersey.core-jersey-client-2.31.jar:?]
	at org.glassfish.jersey.client.ClientRuntime$2.lambda$failure$1(ClientRuntime.java:178) ~[org.glassfish.jersey.core-jersey-client-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[org.glassfish.jersey.core-jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[org.glassfish.jersey.core-jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[org.glassfish.jersey.core-jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[org.glassfish.jersey.core-jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[org.glassfish.jersey.core-jersey-common-2.31.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:288) ~[org.glassfish.jersey.core-jersey-common-2.31.jar:?]
	at org.glassfish.jersey.client.ClientRuntime$2.failure(ClientRuntime.java:178) ~[org.glassfish.jersey.core-jersey-client-2.31.jar:?]
	at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$apply$1(AsyncHttpConnector.java:200) ~[org.apache.pulsar-pulsar-client-admin-original-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) ~[?:1.8.0_275]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) ~[?:1.8.0_275]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_275]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) ~[?:1.8.0_275]
	at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$timeoutAfter$7(AsyncHttpConnector.java:300) ~[org.apache.pulsar-pulsar-client-admin-original-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_275]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_275]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_275]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.51.Final.jar:4.1.51.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: org.apache.pulsar.client.admin.PulsarAdminException: java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException
	at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:231) ~[org.apache.pulsar-pulsar-client-admin-original-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	... 26 more
Caused by: java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_275]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_275]
	at java.util.concurrent.CompletableFuture.orApply(CompletableFuture.java:1385) ~[?:1.8.0_275]
	at java.util.concurrent.CompletableFuture$OrApply.tryFire(CompletableFuture.java:1364) ~[?:1.8.0_275]
	at java.util.concurrent.CompletableFuture$CoCompletion.tryFire(CompletableFuture.java:1034) ~[?:1.8.0_275]
	... 10 more
Caused by: java.util.concurrent.TimeoutException
	... 8 more
14:05:48.214 [delayer-47-1] INFO  org.eclipse.jetty.server.RequestLog - 172.18.0.9 - - [11/Dec/2020:14:05:18 +0000] "GET /admin/v2/non-persistent/public/default HTTP/1.1" 500 3183 "-" "Pulsar-Java-v2.8.0-SNAPSHOT" 30006
14:05:48.426 [pulsar-io-23-3] INFO  org.apache.pulsar.broker.service.ServerCnx - Closed connection from /172.18.0.8:38092
</pre></code>
</detail>

**Comment by reswqa** [comment]
Hi, I'm not quite sure if it was caused by this pr (https://github.com/apache/pulsar/pull/8746) I created earlier, because I was getting this error from the CI test SQL when I pull the request, but today the test suddenly passed, so it was merged into master. if it was caused by it, I'm very sorry, but I didn't find out what went wrong at the time, any problems are welcome to point out.

**Comment by eolivelli** [comment]
I also see this failure in the same suite
TestBasicPresto.testSimpleSQLQueryBatched:73->testSimpleSQLQuery:140 expected:<[1]0> but was:<[2]0>

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
