### ISSUE TITLE
Currently auto consume works for type 'KEY_VALUE' is not supported yet

### ISSUE THREAD

**Issue by rafael81** [apache/pulsar#8956]
**Describe the bug**
Caused by: java.lang.IllegalArgumentException: Currently auto consume works for type 'KEY_VALUE' is not supported yet
	at org.apache.pulsar.client.impl.schema.AutoConsumeSchema.generateSchema(AutoConsumeSchema.java:163) ~[org.apache.pulsar-pulsar-client-original-2.7.0.jar:2.7.0]
	at org.apache.pulsar.client.impl.schema.AutoConsumeSchema.configureSchemaInfo(AutoConsumeSchema.java:129) ~[org.apache.pulsar-pulsar-client-original-2.7.0.jar:2.7.0]
	at org.apache.pulsar.client.impl.PulsarClientImpl.lambda$preProcessSchemaBeforeSubscribe$26(PulsarClientImpl.java:827) ~[org.apache.pulsar-pulsar-client-original-2.7.0.jar:2.7.0]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966) ~[?:1.8.0_275]
	... 29 more

**To Reproduce**
1. Setup Debezium source connector following by https://pulsar.apache.org/docs/en/io-cdc-debezium/
2. Setup JDBC sink connector following by https://pulsar.apache.org/docs/en/io-quickstart/#connect-pulsar-to-postgresql

**Expected behavior**
The produced data from topic are replicated to postgresql database.

**Screenshots**
![image](https://user-images.githubusercontent.com/36774/102096410-0406af80-3e68-11eb-9e57-9c2f94d95b32.png)

**Desktop (please complete the following information):**
 - OS: Docker

**Additional context**

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
