### ISSUE TITLE
bookkeeper shell cookie_get command fails in pulsar v2.7.0

### ISSUE THREAD

**Issue by anvinjain** [apache/pulsar#8993]
**Describe the bug**
When executing `bin/bookkeeper shell cookie_get`, the command fails with no such method error.
```
root@pulsar-mini-bookie-0:/pulsar# bin/bookkeeper shell cookie_get
JMX enabled by default
Exception in thread "main" java.lang.NoSuchMethodError: com.beust.jcommander.JCommander.usage(Ljava/lang/StringBuilder;)V
	at org.apache.bookkeeper.tools.framework.Cli.setupCli(Cli.java:142)
	at org.apache.bookkeeper.tools.framework.Cli.<init>(Cli.java:53)
	at org.apache.bookkeeper.tools.framework.Cli.runCli(Cli.java:243)
	at org.apache.bookkeeper.tools.common.BKCommand.apply(BKCommand.java:64)
	at org.apache.bookkeeper.tools.cli.helpers.BookieShellCommand.runCmd(BookieShellCommand.java:46)
	at org.apache.bookkeeper.bookie.BookieShell.run(BookieShell.java:2235)
	at org.apache.bookkeeper.bookie.BookieShell.main(BookieShell.java:2326)
```

**To Reproduce**
1. Install pulsar locally in minikube
2. `kubectl exec -n pulsar -it "pulsar-mini-bookie-0" -- /bin/bash`
3. In the container, execute: `bin/bookkeeper shell cookie_get`

**Expected behavior**
Should be able to get cookie for the bookie

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Minikube v1.15.1 on Max OSX 10.14.5
 - Pulsar v2.7.0. Local setup instructions followed from doc

**Additional context**
Looks like a packaging issue when bundling jars from bookkeeper and pulsar together. Pulsar depends on `jcommander:1.78` and bookkeeper depends on `jcommander:1.48`. The higher version(1.78) gets bundled in pulsar/lib which does not have usage(StringBuilder) signature.

**Comment by eolivelli** [comment]
We are going to cut a release of BK 4.12.1 soon.
Do you mind creating an issue in BK foe the upgrade?
Sending a patch would be top!

**Comment by codelipenghui** [comment]
Thanks @anvinjain @eolivelli, since we have an issue in the bookkeeper, I will close this issue first.
