### ISSUE TITLE
How to resolve BK Error while recovering ledger

### ISSUE THREAD

**Issue by xiaotongwang1** [apache/pulsar#9007]
pulsar broker version 2.7.0
bookkeeper version 4.10.0

--------------

**Pulsar Broker Error log when client producer message** 

```
15:01:12.364 [BookKeeperClientWorker-OrderedExecutor-0-0] ERROR org.apache.bookkeeper.client.BookKeeperAdmin - BK error opening ledger: 73176
org.apache.bookkeeper.client.BKException$BKReadException: Error while reading ledger
        at org.apache.bookkeeper.client.BKException.create(BKException.java:62) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.client.BookKeeperAdmin$6.openComplete(BookKeeperAdmin.java:751) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.client.LedgerOpenOp.openComplete(LedgerOpenOp.java:232) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.client.LedgerOpenOp$2.readLastConfirmedComplete(LedgerOpenOp.java:215) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.client.LedgerHandle$10.readLastConfirmedDataComplete(LedgerHandle.java:1405) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.client.ReadLastConfirmedOp.readEntryComplete(ReadLastConfirmedOp.java:117) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.proto.PerChannelBookieClient$ReadCompletion$1.readEntryComplete(PerChannelBookieClient.java:1829) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.proto.PerChannelBookieClient$ReadCompletion.handleReadResponse(PerChannelBookieClient.java:1910) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.proto.PerChannelBookieClient$ReadCompletion.handleV3Response(PerChannelBookieClient.java:1885) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.proto.PerChannelBookieClient$3.safeRun(PerChannelBookieClient.java:1446) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [org.apache.bookkeeper-bookkeeper-common-4.10.0.jar:4.10.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.48.Final.jar:4.1.48.Final]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
15:01:12.364 [BookKeeperClientWorker-OrderedExecutor-0-0] ERROR org.apache.bookkeeper.proto.BookkeeperInternalCallbacks - Error in multi callback : -1
15:01:12.364 [BookKeeperClientWorker-OrderedExecutor-7-0] DEBUG org.apache.bookkeeper.proto.PerChannelBookieClient - Got Read response from bookie:10.33.50.71:3181 rc:EUA, ledger:0:entry:0:entryLength:0
15:01:12.364 [BookKeeperClientWorker-OrderedExecutor-0-0] DEBUG org.apache.bookkeeper.proto.PerChannelBookieClient - Got Read response from bookie:10.33.50.144:3181 rc:EUA, ledger:0:entry:0:entryLength:0
15:01:12.364 [BookKeeperClientWorker-OrderedExecutor-0-0] DEBUG org.apache.bookkeeper.proto.PerChannelBookieClient - Got Read response from bookie:10.33.50.88:3181 rc:ENOENTRY, ledger:73176:entry:-1:entryLength:0
15:01:12.364 [BookKeeperClientWorker-OrderedExecutor-7-0] ERROR org.apache.bookkeeper.client.BookKeeperAdmin - BK error opening ledger: 73175
org.apache.bookkeeper.client.BKException$BKReadException: Error while reading ledger
        at org.apache.bookkeeper.client.BKException.create(BKException.java:62) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.client.BookKeeperAdmin$6.openComplete(BookKeeperAdmin.java:751) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.client.LedgerOpenOp.openComplete(LedgerOpenOp.java:232) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.client.LedgerOpenOp$2.readLastConfirmedComplete(LedgerOpenOp.java:215) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.client.LedgerHandle$10.readLastConfirmedDataComplete(LedgerHandle.java:1405) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.client.ReadLastConfirmedOp.readEntryComplete(ReadLastConfirmedOp.java:117) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.proto.PerChannelBookieClient$ReadCompletion$1.readEntryComplete(PerChannelBookieClient.java:1829) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.proto.PerChannelBookieClient$ReadCompletion.handleReadResponse(PerChannelBookieClient.java:1910) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.proto.PerChannelBookieClient$ReadCompletion.handleV3Response(PerChannelBookieClient.java:1885) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.proto.PerChannelBookieClient$3.safeRun(PerChannelBookieClient.java:1446) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [org.apache.bookkeeper-bookkeeper-common-4.10.0.jar:4.10.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.48.Final.jar:4.1.48.Final]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
15:01:12.364 [BookKeeperClientWorker-OrderedExecutor-7-0] ERROR org.apache.bookkeeper.proto.BookkeeperInternalCallbacks - Error in multi callback : -1


I try to run bookkeeper recover  

bookkeeper shell recover 10.33.50.144:3181

same error  

15:01:12.364 [BookKeeperClientWorker-OrderedExecutor-0-0] DEBUG org.apache.bookkeeper.proto.PerChannelBookieClient - Got Read response from bookie:10.33.50.88:3181 rc:ENOENTRY, ledger:73176:entry:-1:entryLength:0
15:01:12.364 [BookKeeperClientWorker-OrderedExecutor-7-0] ERROR org.apache.bookkeeper.client.BookKeeperAdmin - BK error opening ledger: 73175
org.apache.bookkeeper.client.BKException$BKReadException: Error while reading ledger
        at org.apache.bookkeeper.client.BKException.create(BKException.java:62) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.client.BookKeeperAdmin$6.openComplete(BookKeeperAdmin.java:751) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.client.LedgerOpenOp.openComplete(LedgerOpenOp.java:232) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.client.LedgerOpenOp$2.readLastConfirmedComplete(LedgerOpenOp.java:215) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.client.LedgerHandle$10.readLastConfirmedDataComplete(LedgerHandle.java:1405) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.client.ReadLastConfirmedOp.readEntryComplete(ReadLastConfirmedOp.java:117) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.proto.PerChannelBookieClient$ReadCompletion$1.readEntryComplete(PerChannelBookieClient.java:1829) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.proto.PerChannelBookieClient$ReadCompletion.handleReadResponse(PerChannelBookieClient.java:1910) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.proto.PerChannelBookieClient$ReadCompletion.handleV3Response(PerChannelBookieClient.java:1885) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.proto.PerChannelBookieClient$3.safeRun(PerChannelBookieClient.java:1446) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [org.apache.bookkeeper-bookkeeper-common-4.10.0.jar:4.10.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.48.Final.jar:4.1.48.Final]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
15:01:12.364 [BookKeeperClientWorker-OrderedExecutor-7-0] ERROR org.apache.bookkeeper.proto.BookkeeperInternalCallbacks - Error in multi callback : -1
```

**Comment by codelipenghui** [comment]
Could you please try to use `bin/bookkeeper shell ledgermetadata -ledgerid 73176`? If you can get the ledger metadata you can try to use `readledger` to read data from this ledger.

**Comment by yanshuchong** [comment]
[root@host-10-33-50-71 bin]# ./bookkeeper shell ledgermetadata -ledgerid 73176

some output 

ledgerID: 73176
LedgerMetadata{formatVersion=3, ensembleSize=3, writeQuorumSize=3, ackQuorumSize=2, state=IN_RECOVERY, digestType=CRC32C, password=base64:, ensembles={0=[10.33.50.71:3181, 10.33.50.88:3181, 10.33.50.144:3181]}, customMetadata={component=base64:bWFuYWdlZC1sZWRnZXI=, pulsar/managed-ledger=base64:d3d3L215bmFtZXNwYWNlMi9wZXJzaXN0ZW50L3d4dC5tcTEtcGFydGl0aW9uLTE=, application=base64:cHVsc2Fy}}


[root@host-10-33-50-71 bin]# ./bookkeeper shell readledger -bookie 10.33.50.71:3181 -ledgerid 73176

10:14:19.055 [main] INFO  org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl - Initialize rackaware ensemble placement policy @ <Bookie:10.33.50.71:0> @ /default-rack : org.apache.bookkeeper.client.TopologyAwareEnsemblePlacementPolicy$DefaultResolver.
10:14:19.055 [main] INFO  org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl - Not weighted
10:14:19.057 [main] INFO  org.apache.bookkeeper.client.BookKeeper - Weighted ledger placement is not enabled
10:14:19.068 [main-SendThread(10.33.50.144:2182)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x301e016970f0077, packet:: clientPath:/ledgers/available serverPath:/ledgers/available finished:false header:: 4,12  replyHeader:: 4,4295730347,0  request:: '/ledgers/available,T  response:: v{'10.33.50.144:3181,'10.33.50.88:3181,'readonly,'10.33.50.71:3181},s{4294967365,4294967365,1606482678656,1606482678656,0,68,0,0,0,4,4295623536} 
10:14:19.068 [main-SendThread(10.33.50.144:2182)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x301e016970f0077, packet:: clientPath:/ledgers/available/readonly serverPath:/ledgers/available/readonly finished:false header:: 5,12  replyHeader:: 5,4295730347,0  request:: '/ledgers/available/readonly,T  response:: v{},s{4294967366,4294967366,1606482678660,1606482678660,0,0,0,0,0,0,4294967366} 
10:14:19.074 [BookKeeperClientScheduler-OrderedScheduler-0-0] DEBUG org.apache.bookkeeper.client.TopologyAwareEnsemblePlacementPolicy - Cluster changed : left bookies are [], joined bookies are [10.33.50.71:3181, 10.33.50.144:3181, 10.33.50.88:3181], while dead bookies are [].
10:14:19.075 [BookKeeperClientScheduler-OrderedScheduler-0-0] INFO  org.apache.bookkeeper.net.NetworkTopologyImpl - Adding a new node: /default-rack/10.33.50.71:3181
10:14:19.075 [BookKeeperClientScheduler-OrderedScheduler-0-0] DEBUG org.apache.bookkeeper.net.NetworkTopologyImpl - NetworkTopology became:
Number of racks: 1
Expected number of leaves:1
/default-rack/10.33.50.71:3181

10:14:19.075 [BookKeeperClientScheduler-OrderedScheduler-0-0] DEBUG org.apache.bookkeeper.client.TopologyAwareEnsemblePlacementPolicy - Cluster changed : bookie 10.33.50.71:3181 joined the cluster.
10:14:19.075 [BookKeeperClientScheduler-OrderedScheduler-0-0] INFO  org.apache.bookkeeper.net.NetworkTopologyImpl - Adding a new node: /default-rack/10.33.50.144:3181
10:14:19.075 [BookKeeperClientScheduler-OrderedScheduler-0-0] DEBUG org.apache.bookkeeper.net.NetworkTopologyImpl - NetworkTopology became:
Number of racks: 1
Expected number of leaves:2
/default-rack/10.33.50.71:3181
/default-rack/10.33.50.144:3181

10:14:19.075 [BookKeeperClientScheduler-OrderedScheduler-0-0] DEBUG org.apache.bookkeeper.client.TopologyAwareEnsemblePlacementPolicy - Cluster changed : bookie 10.33.50.144:3181 joined the cluster.
10:14:19.075 [BookKeeperClientScheduler-OrderedScheduler-0-0] INFO  org.apache.bookkeeper.net.NetworkTopologyImpl - Adding a new node: /default-rack/10.33.50.88:3181
10:14:19.075 [BookKeeperClientScheduler-OrderedScheduler-0-0] DEBUG org.apache.bookkeeper.net.NetworkTopologyImpl - NetworkTopology became:
Number of racks: 1
Expected number of leaves:3
/default-rack/10.33.50.71:3181
/default-rack/10.33.50.144:3181
/default-rack/10.33.50.88:3181

10:14:19.076 [BookKeeperClientScheduler-OrderedScheduler-0-0] DEBUG org.apache.bookkeeper.client.TopologyAwareEnsemblePlacementPolicy - Cluster changed : bookie 10.33.50.88:3181 joined the cluster.
10:14:19.076 [BookKeeperClientScheduler-OrderedScheduler-0-0] DEBUG org.apache.bookkeeper.client.TopologyAwareEnsemblePlacementPolicy - Cluster changed : left bookies are [], joined bookies are [], while dead bookies are [].
10:14:19.077 [main] DEBUG org.apache.bookkeeper.zookeeper.ZooWorker - Execute getData (/ledgers/LAYOUT, watcher = false) at 0 retry attempt.
10:14:19.078 [main] DEBUG org.apache.bookkeeper.zookeeper.ZooWorker - Execute getData (/ledgers/LAYOUT, watcher = null) at 0 retry attempt.
10:14:19.079 [main-SendThread(10.33.50.144:2182)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x301e016970f0077, packet:: clientPath:null serverPath:null finished:false header:: 6,4  replyHeader:: 6,4295730347,0  request:: '/ledgers/LAYOUT,F  response:: #32a6f72672e6170616368652e626f6f6b6b65657065722e6d6574612e48696572617263686963616c4c65646765724d616e61676572466163746f72793a31,s{4294967369,4294967369,1606482678704,1606482678704,0,0,0,0,63,0,4294967369} 
10:14:19.080 [main] DEBUG org.apache.bookkeeper.meta.LedgerLayout - Parsing Layout: 2
org.apache.bookkeeper.meta.HierarchicalLedgerManagerFactory:1
10:14:19.080 [main] DEBUG org.apache.bookkeeper.meta.AbstractZkLedgerManagerFactory - read ledger layout LedgerLayout(managerFactoryClass=org.apache.bookkeeper.meta.HierarchicalLedgerManagerFactory, managerVersion=1, layoutFormatVersion=2)
10:14:19.087 [main] DEBUG org.apache.bookkeeper.meta.AbstractZkLedgerManager - Using AbstractZkLedgerManager with root path : /ledgers
10:14:19.088 [main] DEBUG org.apache.bookkeeper.meta.AbstractZkLedgerManager - Using AbstractZkLedgerManager with root path : /ledgers
10:14:19.089 [main] DEBUG org.apache.bookkeeper.meta.AbstractZkLedgerManager - Using AbstractZkLedgerManager with root path : /ledgers

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
