### ISSUE TITLE
Pulsar function startup specifies --jar mode is http:// and file:/// , Found an error

### ISSUE THREAD

**Issue by JueShanCoder** [apache/pulsar#9098]
**Pulsar Version**
2.6.1

**Describe the bug**
When I tried to start the pulsar function using localrun, I found that I specified --jar as http://xxx.com/xxx.jar and file:///pulsar/connectors/functions/xxx.jar  in the startup script, and then I found an error ,

**To Reproduce**
1. Function start up script : --jar http://xxx.com/xxx.jar or file:///pulsar/connectors/xxx.jar 
2. I found an error is 
 java.lang.RuntimeException: User class must be in class path
	at org.apache.pulsar.common.util.Reflections.createInstance(Reflections.java:112) ~[org.apache.pulsar-pulsar-common-2.6.1.jar:2.6.1]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.setup(JavaInstanceRunnable.java:208) ~[org.apache.pulsar-pulsar-functions-instance-2.6.1.jar:2.6.1]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:246) ~[org.apache.pulsar-pulsar-functions-instance-2.6.1.jar:2.6.1]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_252]
3. But I modify the startup script to connector/function/xxxx.jar ,I found that function can work ... 
4. The jar package used is downloaded from http://xxx.com/xxx.jar

I think this may be a problem with classloader loading, I hope to check it out soon, Tks

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.

Now, you can ask questions in https://github.com/apache/pulsar/discussions/categories/q-a instead, since we almost use issues to track actionable tasks.
