### ISSUE TITLE
Flaky-test: NPE in CompactionTest.cleanup

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#9432]
org.apache.pulsar.compaction.CompactionTest is flaky. The cleanup method fails sporadically.

```
java.lang.NullPointerException
	at org.apache.pulsar.compaction.CompactionTest.cleanup(CompactionTest.java:100)
```
Usage tip: To enable automatic navigation to failure message, open the links with CTRL/CMD-click.
[example failure 2021-01-26T17:03:16.9407472Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:12881)
[example failure 2021-01-26T17:03:16.8873820Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:12838)
[example failure 2021-01-26T17:03:16.8498120Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:12795)
[example failure 2021-01-26T17:03:16.8338151Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:12752)
[example failure 2021-01-26T17:03:16.8039434Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:12709)
[example failure 2021-01-26T17:03:16.7557871Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:12666)
[example failure 2021-01-26T17:03:16.7044893Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:12622)
[example failure 2021-01-26T17:03:16.6721640Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:12579)
[example failure 2021-01-26T17:03:16.6486545Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:12536)
[example failure 2021-01-26T17:03:16.5861220Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:12450)
[example failure 2021-01-26T17:03:16.5056385Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:12321)
[example failure 2021-01-26T17:03:16.4897161Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:12278)
[example failure 2021-01-26T17:03:16.3819475Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:12145)
[example failure 2021-01-26T17:03:16.3626732Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:12102)
[example failure 2021-01-26T17:03:16.3012579Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:12059)
[example failure 2021-01-26T17:03:16.2445722Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:12016)
[example failure 2021-01-26T17:01:46.2335923Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:7533)
[example failure 2021-01-26T17:01:46.1858853Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:7489)
[example failure 2021-01-26T17:01:46.1583808Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:7446)
[example failure 2021-01-26T17:01:46.1346959Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:7403)
[example failure 2021-01-26T17:01:46.1163923Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:7360)
[example failure 2021-01-26T17:01:45.9979541Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:7187)
[example failure 2021-01-26T17:01:45.9819418Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:7144)
[example failure 2021-01-26T17:01:45.8822893Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:6964)
[example failure 2021-01-26T17:01:45.8485025Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:6921)
[example failure 2021-01-26T17:01:45.8040817Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:6878)
[example failure 2021-01-26T17:01:45.7770882Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:6835)
[example failure 2021-01-26T17:01:45.7567063Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:6792)
[example failure 2021-01-26T17:01:45.7334390Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:6749)
[example failure 2021-01-26T17:01:45.7086920Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:6706)
[example failure 2021-01-26T17:01:45.6914715Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:6663)
[example failure 2021-01-26T17:01:45.6690741Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:6620)
[example failure 2021-01-26T17:00:16.0136965Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:2137)
[example failure 2021-01-26T17:00:15.9977734Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:2094)
[example failure 2021-01-26T17:00:15.9779021Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:2051)
[example failure 2021-01-26T17:00:15.9472661Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:2008)
[example failure 2021-01-26T17:00:15.8849868Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:1965)
[example failure 2021-01-26T17:00:15.8479016Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:1922)
[example failure 2021-01-26T17:00:15.8365886Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:1879)
[example failure 2021-01-26T17:00:15.8144162Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:1836)
[example failure 2021-01-26T17:00:15.7929478Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:1793)
[example failure 2021-01-26T17:00:15.7628915Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:1750)
[example failure 2021-01-26T17:00:15.7358773Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:1707)
[example failure 2021-01-26T17:00:15.7073745Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:1664)
[example failure 2021-01-26T17:00:15.6860064Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:1621)
[example failure 2021-01-26T17:00:15.6646173Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:1578)
[example failure 2021-01-26T17:00:15.6394054Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:1535)
[example failure 2021-01-26T17:00:15.6159294Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:1492)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
java.lang.NullPointerException
	at org.apache.pulsar.compaction.CompactionTest.cleanup(CompactionTest.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
	at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:701)
	at org.testng.internal.TestInvoker.runAfterGroupsConfigurations(TestInvoker.java:677)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:548)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:764)
	at org.testng.TestRunner.run(TestRunner.java:585)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.runSuites(TestNG.java:1069)
	at org.testng.TestNG.run(TestNG.java:1037)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeLazy(TestNGDirectoryTestSuite.java:123)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:90)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

</pre></code>
</details>
Usage tip: To enable automatic navigation to failure message, open the links with CTRL/CMD-click.
[example failure 2021-01-26T17:00:16.7479053Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:2894)
[example failure 2021-01-26T17:00:16.7176127Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:2852)
[example failure 2021-01-26T17:00:16.6624775Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:2810)
[example failure 2021-01-26T17:00:16.6494518Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:2768)
[example failure 2021-01-26T17:00:16.5909238Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:2726)
[example failure 2021-01-26T17:00:16.5657745Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:2684)
[example failure 2021-01-26T17:00:16.5277923Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:2642)
[example failure 2021-01-26T17:00:16.4805315Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:2600)
[example failure 2021-01-26T17:00:16.4228852Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:2558)
[example failure 2021-01-26T17:00:16.3645764Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:2516)
[example failure 2021-01-26T17:00:16.3235418Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:2474)
[example failure 2021-01-26T17:00:16.2816076Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:2432)
[example failure 2021-01-26T17:00:16.2344426Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:2390)
[example failure 2021-01-26T17:00:16.1766665Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:2348)
[example failure 2021-01-26T17:00:16.1485568Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:2306)
[example failure 2021-01-26T17:00:16.1065249Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:2264)
[example failure 2021-01-26T17:00:16.0573709Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:2222)
[example failure 2021-01-26T17:00:16.0336367Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:2180)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
java.lang.NullPointerException
	at org.apache.pulsar.compaction.CompactionTest.cleanup(CompactionTest.java:100)
	at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
	at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:701)
	at org.testng.internal.TestInvoker.runAfterGroupsConfigurations(TestInvoker.java:677)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:548)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:764)
	at org.testng.TestRunner.run(TestRunner.java:585)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.runSuites(TestNG.java:1069)
	at org.testng.TestNG.run(TestNG.java:1037)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeLazy(TestNGDirectoryTestSuite.java:123)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:90)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

</pre></code>
</details>
Usage tip: To enable automatic navigation to failure message, open the links with CTRL/CMD-click.
[example failure 2021-01-26T17:03:17.5340192Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:13686)
[example failure 2021-01-26T17:03:17.5182329Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:13644)
[example failure 2021-01-26T17:03:17.4939143Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:13602)
[example failure 2021-01-26T17:03:17.4707102Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:13560)
[example failure 2021-01-26T17:03:17.4525785Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:13518)
[example failure 2021-01-26T17:03:17.4330297Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:13476)
[example failure 2021-01-26T17:03:17.4063643Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:13433)
[example failure 2021-01-26T17:03:17.3454647Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:13344)
[example failure 2021-01-26T17:03:17.3080902Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:13302)
[example failure 2021-01-26T17:03:17.2692598Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:13260)
[example failure 2021-01-26T17:03:17.2327050Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:13218)
[example failure 2021-01-26T17:03:17.2156799Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:13176)
[example failure 2021-01-26T17:03:17.1942343Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:13134)
[example failure 2021-01-26T17:03:17.1533931Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:13092)
[example failure 2021-01-26T17:03:17.1210671Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:13050)
[example failure 2021-01-26T17:03:17.0950883Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:13008)
[example failure 2021-01-26T17:03:17.0485753Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:12966)
[example failure 2021-01-26T17:03:16.9901892Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:12924)
[example failure 2021-01-26T17:01:46.8163336Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:8290)
[example failure 2021-01-26T17:01:46.7910412Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:8248)
[example failure 2021-01-26T17:01:46.7713281Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:8206)
[example failure 2021-01-26T17:01:46.7471902Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:8164)
[example failure 2021-01-26T17:01:46.7209316Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:8122)
[example failure 2021-01-26T17:01:46.6649265Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:8080)
[example failure 2021-01-26T17:01:46.6338537Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:8038)
[example failure 2021-01-26T17:01:46.6009714Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:7996)
[example failure 2021-01-26T17:01:46.5909385Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:7954)
[example failure 2021-01-26T17:01:46.5423404Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:7912)
[example failure 2021-01-26T17:01:46.5233791Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:7870)
[example failure 2021-01-26T17:01:46.4527839Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:7828)
[example failure 2021-01-26T17:01:46.4256449Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:7786)
[example failure 2021-01-26T17:01:46.3904941Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:7744)
[example failure 2021-01-26T17:01:46.3566726Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:7702)
[example failure 2021-01-26T17:01:46.3308798Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:7660)
[example failure 2021-01-26T17:01:46.2859067Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:7618)
[example failure 2021-01-26T17:01:46.2548365Z](https://github.com/apache/pulsar/runs/1769412594?check_suite_focus=true#step:8:7576)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
java.lang.NullPointerException
	at org.apache.pulsar.compaction.CompactionTest.cleanup(CompactionTest.java:100)
	at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
	at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:701)
	at org.testng.internal.TestInvoker.runAfterGroupsConfigurations(TestInvoker.java:677)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:548)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:764)
	at org.testng.TestRunner.run(TestRunner.java:585)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.runSuites(TestNG.java:1069)
	at org.testng.TestNG.run(TestNG.java:1037)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeLazy(TestNGDirectoryTestSuite.java:123)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:90)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

</pre></code>
</details>

**Comment by Wzhipeng** [comment]
I'm working on that

**Comment by Wzhipeng** [comment]
I'm working on it.

**Comment by lhotari** [comment]
@Wzhipeng Good. btw. I noticed that a similar problem occurs in quite a few test cleanup methods. It must have been a case where the setup method fails before `compactionScheduler` has been created.

Would you mind fixing the NPEs in cleanup methods of these tests in addition to CompactionTest.cleanup? 
I believe this could be done in the same PR since it's about a similar issue.
```
org.apache.pulsar.compaction.CompactorTest.cleanup
org.apache.pulsar.websocket.proxy.ProxyAuthenticationTest.cleanup
org.apache.pulsar.websocket.proxy.ProxyAuthorizationTest.cleanup
org.apache.pulsar.websocket.proxy.ProxyPublishConsumeTest.cleanup
org.apache.pulsar.websocket.proxy.ProxyPublishConsumeTlsTest.cleanup
org.apache.pulsar.websocket.proxy.ProxyPublishConsumeWithoutZKTest.cleanup
org.apache.pulsar.websocket.proxy.v1.V1_ProxyAuthenticationTest.cleanup
```

The issue could be renames as "Fix NPEs in test cleanup methods", if this is fine for you.

**Comment by Wzhipeng** [comment]
> @Wzhipeng Good. btw. I noticed that a similar problem occurs in quite a few test cleanup methods. It must have been a case where the setup method fails before `compactionScheduler` has been created.
> 
> Would you mind fixing the NPEs in cleanup methods of these tests in addition to CompactionTest.cleanup?
> I believe this could be done in the same PR since it's about a similar issue.
> 
> ```
> org.apache.pulsar.compaction.CompactorTest.cleanup
> org.apache.pulsar.websocket.proxy.ProxyAuthenticationTest.cleanup
> org.apache.pulsar.websocket.proxy.ProxyAuthorizationTest.cleanup
> org.apache.pulsar.websocket.proxy.ProxyPublishConsumeTest.cleanup
> org.apache.pulsar.websocket.proxy.ProxyPublishConsumeTlsTest.cleanup
> org.apache.pulsar.websocket.proxy.ProxyPublishConsumeWithoutZKTest.cleanup
> org.apache.pulsar.websocket.proxy.v1.V1_ProxyAuthenticationTest.cleanup
> ```
> 
> The issue might be broader, but there are NPE failures at least in these methods in the last 14 days.
> 
> The issue could be renames as "Fix NPEs in test cleanup methods", if this is fine for you.

ok，I will solve the problem you mentioned above
