### ISSUE TITLE
Flaky-test: org.apache.pulsar.client.cli.PulsarClientToolWsTest

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#9437]
org.apache.pulsar.client.cli.PulsarClientToolWsTest is flaky. 

### The testWebSocketNonDurableSubscriptionMode test method fails sporadically.

```
org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.client.cli.PulsarClientToolWsTest.testWebSocketNonDurableSubscriptionMode() didn't finish within the time-out 20000
```
Usage tip: To enable automatic navigation to failure message, open the links with CTRL/CMD-click.
[example failure 2021-02-01T09:41:10.0922161Z](https://github.com/apache/pulsar/runs/1804628430?check_suite_focus=true#step:6:12322)
[example failure 2021-01-29T07:51:57.9989389Z](https://github.com/apache/pulsar/runs/1789838309?check_suite_focus=true#step:6:18491)
[example failure 2021-01-28T02:42:14.3316285Z](https://github.com/apache/pulsar/runs/1781184081?check_suite_focus=true#step:6:18415)
[example failure 2021-01-27T21:44:09.7619772Z](https://github.com/apache/pulsar/runs/1778470820?check_suite_focus=true#step:6:6213)
[example failure 2021-01-27T11:50:29.8217957Z](https://github.com/apache/pulsar/runs/1775096701?check_suite_focus=true#step:6:6211)
[example failure 2021-01-27T01:35:06.0873552Z](https://github.com/apache/pulsar/runs/1773587703?check_suite_focus=true#step:6:9443)
[example failure 2021-01-26T13:37:12.6427052Z](https://github.com/apache/pulsar/runs/1767980030?check_suite_focus=true#step:6:12287)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.client.cli.PulsarClientToolWsTest.testWebSocketNonDurableSubscriptionMode() didn't finish within the time-out 20000
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:371)
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:282)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:605)
	at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:764)
	at org.testng.TestRunner.run(TestRunner.java:585)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.runSuites(TestNG.java:1069)
	at org.testng.TestNG.run(TestNG.java:1037)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeLazy(TestNGDirectoryTestSuite.java:123)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:90)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

</pre></code>
</details>

### The testWebSocketDurableSubscriptionMode test method fails sporadically.

```
org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.client.cli.PulsarClientToolWsTest.testWebSocketDurableSubscriptionMode() didn't finish within the time-out 20000
```
Usage tip: To enable automatic navigation to failure message, open the links with CTRL/CMD-click.
[example failure 2021-02-01T10:03:48.2843186Z](https://github.com/apache/pulsar/runs/1804649429?check_suite_focus=true#step:7:14742)
[example failure 2021-01-29T00:13:51.9443386Z](https://github.com/apache/pulsar/runs/1788100839?check_suite_focus=true#step:7:6230)
[example failure 2021-01-28T07:31:28.0400645Z](https://github.com/apache/pulsar/runs/1782001809?check_suite_focus=true#step:6:14747)
[example failure 2021-01-28T00:09:57.8952827Z](https://github.com/apache/pulsar/runs/1780053828?check_suite_focus=true#step:6:6213)
[example failure 2021-01-27T16:05:58.5307493Z](https://github.com/apache/pulsar/runs/1777187576?check_suite_focus=true#step:6:6230)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.client.cli.PulsarClientToolWsTest.testWebSocketDurableSubscriptionMode() didn't finish within the time-out 20000
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:371)
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:282)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:605)
	at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:764)
	at org.testng.TestRunner.run(TestRunner.java:585)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.runSuites(TestNG.java:1069)
	at org.testng.TestNG.run(TestNG.java:1037)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeLazy(TestNGDirectoryTestSuite.java:123)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:90)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

</pre></code>
</details>

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
