### ISSUE TITLE
Flaky-test: PulsarFunctionsProcessTest.testAvroSchemaFunction 

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#9453]
org.apache.pulsar.tests.integration.functions.PulsarFunctionsThreadTest is flaky. The testAvroSchemaFunction test method fails sporadically.

```
org.apache.pulsar.tests.integration.docker.ContainerExecException: sh -c /pulsar/bin/pulsar-admin functions create --tenant public --namespace default --name test-avroschema-fn-202003241756 --className org.apache.pulsar.functions.api.examples.AvroSchemaTestFunction --inputs test-avroschema-input-gpzrhjct --output test-avroschema-output-nuicivxv --jar /pulsar/examples/java-test-functions.jar failed on 35273bf26fb7dd759302b59951ae7bc3e8bb77056539994ac94477847ce2e867 with error code 1
	at org.apache.pulsar.tests.integration.utils.DockerUtils$2.onComplete(DockerUtils.java:259)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-01-30T16:05:19.6332933Z](https://github.com/apache/pulsar/runs/1797736194?check_suite_focus=true#step:13:13063)
[example failure 2021-01-30T15:58:53.2952051Z](https://github.com/apache/pulsar/runs/1797736194?check_suite_focus=true#step:13:6831)
[example failure 2021-02-01T17:07:26.7690172Z](https://github.com/apache/pulsar/runs/1807469791?check_suite_focus=true#step:13:27486)
[example failure 2021-01-29T10:16:39.8466702Z](https://github.com/apache/pulsar/runs/1790322610?check_suite_focus=true#step:12:14264)
[example failure 2021-01-29T17:46:33.2592827Z](https://github.com/apache/pulsar/runs/1792703468?check_suite_focus=true#step:13:15484)
[example failure 2021-01-28T17:16:36.0105461Z](https://github.com/apache/pulsar/runs/1784431074?check_suite_focus=true#step:12:39864)
[example failure 2021-01-30T16:28:06.9629741Z](https://github.com/apache/pulsar/runs/1797736218?check_suite_focus=true#step:13:29403)
[example failure 2021-01-30T15:51:39.5002819Z](https://github.com/apache/pulsar/runs/1797687995?check_suite_focus=true#step:13:13433)
[example failure 2021-02-01T16:52:46.3045349Z](https://github.com/apache/pulsar/runs/1807469791?check_suite_focus=true#step:13:14069)
[example failure 2021-01-30T16:13:19.0035405Z](https://github.com/apache/pulsar/runs/1797736218?check_suite_focus=true#step:13:15204)
[example failure 2021-01-30T02:26:30.6161587Z](https://github.com/apache/pulsar/runs/1795631678?check_suite_focus=true#step:13:24152)
[example failure 2021-01-30T16:43:02.1673902Z](https://github.com/apache/pulsar/runs/1797736218?check_suite_focus=true#step:13:42705)
[example failure 2021-01-28T17:03:28.2985820Z](https://github.com/apache/pulsar/runs/1784431074?check_suite_focus=true#step:12:26003)
[example failure 2021-01-28T19:53:13.6502091Z](https://github.com/apache/pulsar/runs/1784537557?check_suite_focus=true#step:12:44782)
[example failure 2021-01-29T17:27:30.5266421Z](https://github.com/apache/pulsar/runs/1791621794?check_suite_focus=true#step:12:14039)
[example failure 2021-01-29T04:50:42.5422018Z](https://github.com/apache/pulsar/runs/1788981343?check_suite_focus=true#step:13:13375)
[example failure 2021-01-29T18:16:46.8326579Z](https://github.com/apache/pulsar/runs/1792703468?check_suite_focus=true#step:13:43860)
[example failure 2021-01-28T16:51:06.3928840Z](https://github.com/apache/pulsar/runs/1784431074?check_suite_focus=true#step:12:13268)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
org.apache.pulsar.tests.integration.docker.ContainerExecException: sh -c /pulsar/bin/pulsar-admin functions create --tenant public --namespace default --name test-avroschema-fn-202003241756 --className org.apache.pulsar.functions.api.examples.AvroSchemaTestFunction --inputs test-avroschema-input-gpzrhjct --output test-avroschema-output-nuicivxv --jar /pulsar/examples/java-test-functions.jar failed on 35273bf26fb7dd759302b59951ae7bc3e8bb77056539994ac94477847ce2e867 with error code 1
	at org.apache.pulsar.tests.integration.utils.DockerUtils$2.onComplete(DockerUtils.java:259)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec$1.onComplete(AbstrAsyncDockerCmdExec.java:51)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:276)
	at java.lang.Thread.run(Thread.java:748)

16:05:19.647 [docker-java-stream-1756188203:org.apache.pulsar.tests.integration.utils.DockerUtils$2@221] INFO  org.apache.pulsar.tests.integration.utils.DockerUtils - DOCKER.exec(PulsarFunctionsThreadTest-pbprw-pulsar-broker-0:tail -f /var/log/pulsar/broker.log): STDOUT: 16:05:19.413 [pulsar-io-25-2] INFO  org.apache.pulsar.broker.service.ServerCnx - [/172.19.0.8:38164] Closing consumer: consumerId=0
16:05:19.413 [pulsar-io-25-2] INFO  org.apache.pulsar.broker.service.AbstractDispatcherSingleActiveConsumer - Removing consumer Consumer{subscription=PersistentSubscription{topic=persistent://public/default/test-tumbling-count-window-THREAD-output-lwaebmmz, name=reader-56d8d972fd}, consumerId=0, consumerName=37687, address=/172.19.0.8:38164}
16:05:19.413 [pulsar-io-25-2] INFO  org.apache.pulsar.broker.service.persistent.PersistentSubscription - [persistent://public/default/test-tumbling-count-window-THREAD-output-lwaebmmz][reader-56d8d972fd] Successfully closed subscription [NonDurableCursorImpl{ledger=public/default/persistent/test-tumbling-count-window-THREAD-output-lwaebmmz, ackPos=67:8, readPos=67:9}]
16:05:19.414 [pulsar-io-25-2] INFO  org.apache.pulsar.broker.service.persistent.PersistentSubscription - [persistent://public/default/test-tumbling-count-window-THREAD-output-lw
16:05:19.648 [docker-java-stream-1756188203:org.apache.pulsar.tests.integration.utils.DockerUtils$2@221] INFO  org.apache.pulsar.tests.integration.utils.DockerUtils - DOCKER.exec(PulsarFunctionsThreadTest-pbprw-pulsar-broker-0:tail -f /var/log/pulsar/broker.log): STDOUT: aebmmz][reader-56d8d972fd] Successfully closed dispatcher for reader
16:05:19.414 [pulsar-io-25-2] INFO  org.apache.pulsar.broker.service.ServerCnx - [/172.19.0.8:38164] Closed consumer, consumerId=0
16:05:19.426 [pulsar-io-25-2] INFO  org.apache.pulsar.broker.service.ServerCnx - Closed connection from /172.19.0.8:38164
16:05:19.441 [pulsar-io-25-1] INFO  org.apache.pulsar.broker.service.ServerCnx - Closed connection from /172.19.0.8:38158
</pre></code>
</details>

**Comment by alex-treebeard** [comment]
hi @lhotari, did you generate this issue with a script? I'm researching tooling for battling test flakiness so am curious

**Comment by lhotari** [comment]
> did you generate this issue with a script? I'm researching tooling for battling test flakiness so am curious

@alex-treebeard yes, I have some ugly scripts to scrape GitHub Action workflow run logs. Please join Pulsar Slack and ping me there if you want to discuss more. The issue tracker is not for discussions about the tooling. Please don't continue the discussion on this issue.

**Comment by lhotari** [comment]
more recent failures:

[example failure 2021-03-13T10:46:02.2204787Z](https://github.com/apache/pulsar/runs/2101609704?check_suite_focus=true#step:13:37539)
[example failure 2021-03-15T16:09:16.2362273Z](https://github.com/apache/pulsar/runs/2113745655?check_suite_focus=true#step:13:19767)
[example failure 2021-03-11T03:01:30.8891230Z](https://github.com/apache/pulsar/runs/2082583912?check_suite_focus=true#step:12:20813)
[example failure 2021-03-07T17:10:41.9572496Z](https://github.com/apache/pulsar/runs/2051124860?check_suite_focus=true#step:12:19323)
[example failure 2021-03-09T03:05:12.5076847Z](https://github.com/apache/pulsar/runs/2062060713?check_suite_focus=true#step:12:37688)
[example failure 2021-03-13T09:05:44.5687206Z](https://github.com/apache/pulsar/runs/2101224146?check_suite_focus=true#step:13:56594)
[example failure 2021-03-04T06:33:07.9323749Z](https://github.com/apache/pulsar/runs/2028174442?check_suite_focus=true#step:12:37644)
[example failure 2021-03-10T19:24:22.3592853Z](https://github.com/apache/pulsar/runs/2078879416?check_suite_focus=true#step:12:36727)
[example failure 2021-03-09T11:39:01.0410178Z](https://github.com/apache/pulsar/runs/2065274754?check_suite_focus=true#step:12:20410)
[example failure 2021-03-09T16:53:52.9470455Z](https://github.com/apache/pulsar/runs/2067697840?check_suite_focus=true#step:12:17720)
[example failure 2021-03-10T11:44:30.5166152Z](https://github.com/apache/pulsar/runs/2075603542?check_suite_focus=true#step:12:42267)
[example failure 2021-03-10T10:35:53.1860771Z](https://github.com/apache/pulsar/runs/2075279942?check_suite_focus=true#step:12:35471)
[example failure 2021-03-07T10:34:41.5175765Z](https://github.com/apache/pulsar/runs/2049868199?check_suite_focus=true#step:12:18811)
[example failure 2021-03-11T03:16:59.3463294Z](https://github.com/apache/pulsar/runs/2082583912?check_suite_focus=true#step:12:38099)
[example failure 2021-03-10T18:04:08.9462899Z](https://github.com/apache/pulsar/runs/2078510916?check_suite_focus=true#step:12:17389)
[example failure 2021-03-03T22:04:41.2856828Z](https://github.com/apache/pulsar/runs/2025524040?check_suite_focus=true#step:12:17091)
[example failure 2021-03-12T03:23:41.2420778Z](https://github.com/apache/pulsar/runs/2091670962?check_suite_focus=true#step:12:37430)
[example failure 2021-03-08T16:19:57.6924736Z](https://github.com/apache/pulsar/runs/2056011363?check_suite_focus=true#step:12:56595)
[example failure 2021-03-08T01:21:35.4227191Z](https://github.com/apache/pulsar/runs/2052659524?check_suite_focus=true#step:12:17096)
[example failure 2021-03-10T22:19:30.2062076Z](https://github.com/apache/pulsar/runs/2080868883?check_suite_focus=true#step:12:20128)
[example failure 2021-03-06T14:35:51.3642590Z](https://github.com/apache/pulsar/runs/2046403900?check_suite_focus=true#step:12:19400)
[example failure 2021-03-09T03:56:09.3136675Z](https://github.com/apache/pulsar/runs/2062377452?check_suite_focus=true#step:12:18680)
[example failure 2021-03-12T03:11:15.2557159Z](https://github.com/apache/pulsar/runs/2091670962?check_suite_focus=true#step:12:19544)
[example failure 2021-03-10T19:10:47.4777994Z](https://github.com/apache/pulsar/runs/2078879416?check_suite_focus=true#step:12:17598)
[example failure 2021-03-12T03:04:35.5076438Z](https://github.com/apache/pulsar/runs/2091552329?check_suite_focus=true#step:12:18767)
[example failure 2021-03-10T07:49:15.4235073Z](https://github.com/apache/pulsar/runs/2074335003?check_suite_focus=true#step:12:19549)
[example failure 2021-03-11T01:26:46.0835089Z](https://github.com/apache/pulsar/runs/2081947260?check_suite_focus=true#step:12:36117)
[example failure 2021-03-11T06:10:06.7583709Z](https://github.com/apache/pulsar/runs/2083382005?check_suite_focus=true#step:12:20051)
[example failure 2021-03-10T11:28:39.7833407Z](https://github.com/apache/pulsar/runs/2075603542?check_suite_focus=true#step:12:20000)
[example failure 2021-03-06T13:40:15.6103635Z](https://github.com/apache/pulsar/runs/2046151794?check_suite_focus=true#step:12:40109)
[example failure 2021-03-12T01:39:05.0425482Z](https://github.com/apache/pulsar/runs/2091179855?check_suite_focus=true#step:12:18946)
[example failure 2021-03-07T17:25:19.6862642Z](https://github.com/apache/pulsar/runs/2051124860?check_suite_focus=true#step:12:38976)
[example failure 2021-03-10T19:39:22.0843379Z](https://github.com/apache/pulsar/runs/2078879416?check_suite_focus=true#step:12:56874)
[example failure 2021-03-10T10:21:57.0653755Z](https://github.com/apache/pulsar/runs/2075279942?check_suite_focus=true#step:12:17614)
[example failure 2021-03-06T03:09:09.6352743Z](https://github.com/apache/pulsar/runs/2044414785?check_suite_focus=true#step:12:17967)
[example failure 2021-03-09T01:05:08.3806426Z](https://github.com/apache/pulsar/runs/2061483387?check_suite_focus=true#step:12:17270)
[example failure 2021-03-10T18:02:31.4493212Z](https://github.com/apache/pulsar/runs/2078511050?check_suite_focus=true#step:12:10625)
[example failure 2021-03-10T09:01:54.2810491Z](https://github.com/apache/pulsar/runs/2074659660?check_suite_focus=true#step:12:8789)
[example failure 2021-03-08T16:08:28.9341245Z](https://github.com/apache/pulsar/runs/2056011706?check_suite_focus=true#step:12:8848)
[example failure 2021-03-10T19:15:13.9435318Z](https://github.com/apache/pulsar/runs/2078879590?check_suite_focus=true#step:12:7999)
[example failure 2021-03-04T06:06:26.8071357Z](https://github.com/apache/pulsar/runs/2028174344?check_suite_focus=true#step:12:8782)
[example failure 2021-03-05T09:50:13.6974945Z](https://github.com/apache/pulsar/runs/2037975215?check_suite_focus=true#step:12:7913)
[example failure 2021-03-11T11:18:01.7524658Z](https://github.com/apache/pulsar/runs/2084704344?check_suite_focus=true#step:12:7879)
[example failure 2021-03-09T11:31:42.7122820Z](https://github.com/apache/pulsar/runs/2065275073?check_suite_focus=true#step:12:8305)
[example failure 2021-03-05T09:57:04.2396688Z](https://github.com/apache/pulsar/runs/2037975215?check_suite_focus=true#step:12:15904)
[example failure 2021-03-07T10:24:10.8868107Z](https://github.com/apache/pulsar/runs/2049868051?check_suite_focus=true#step:12:7971)
[example failure 2021-03-11T18:10:47.0700052Z](https://github.com/apache/pulsar/runs/2088218386?check_suite_focus=true#step:13:8217)
[example failure 2021-03-09T01:05:22.7786128Z](https://github.com/apache/pulsar/runs/2061483124?check_suite_focus=true#step:12:17718)
[example failure 2021-03-09T00:58:49.9044318Z](https://github.com/apache/pulsar/runs/2061483124?check_suite_focus=true#step:12:8195)

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.
