### ISSUE TITLE
Flaky-test: PulsarFunctionsTest.testCustomSerdeFunction

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#9455]
org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest is flaky. The method testCustomSerdeFunction fails sporadically.

```
org.apache.pulsar.tests.integration.docker.ContainerExecException: sh -c /pulsar/bin/pulsar-admin functions create --tenant public --namespace default --name test-serde-fn-xzjvgepw --className org.apache.pulsar.functions.api.examples.CustomBaseToBaseFunction --inputs persistent://public/default/test-serde-java-input-zkqrttui --output test-publish-serde-output-lhuyeerv --outputSerdeClassName org.apache.pulsar.functions.api.examples.CustomBaseSerde --userConfig '{"serde-topic":"test-publish-serde-output-lhuyeerv"}' --jar /pulsar/examples/java-test-functions.jar failed on 3d092a81a00ae6ef1346c38ef8d9b979e32f114d98ece5fe6ec2b31bab8181c0 with error code 1
	at org.apache.pulsar.tests.integration.utils.DockerUtils$2.onComplete(DockerUtils.java:259)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-01-30T02:26:30.6603356Z](https://github.com/apache/pulsar/runs/1795631678?check_suite_focus=true#step:13:24207)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
org.apache.pulsar.tests.integration.docker.ContainerExecException: sh -c /pulsar/bin/pulsar-admin functions create --tenant public --namespace default --name test-serde-fn-xzjvgepw --className org.apache.pulsar.functions.api.examples.CustomBaseToBaseFunction --inputs persistent://public/default/test-serde-java-input-zkqrttui --output test-publish-serde-output-lhuyeerv --outputSerdeClassName org.apache.pulsar.functions.api.examples.CustomBaseSerde --userConfig '{"serde-topic":"test-publish-serde-output-lhuyeerv"}' --jar /pulsar/examples/java-test-functions.jar failed on 3d092a81a00ae6ef1346c38ef8d9b979e32f114d98ece5fe6ec2b31bab8181c0 with error code 1
	at org.apache.pulsar.tests.integration.utils.DockerUtils$2.onComplete(DockerUtils.java:259)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec$1.onComplete(AbstrAsyncDockerCmdExec.java:51)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:276)
	at java.lang.Thread.run(Thread.java:748)

</pre></code>
</details>

the logs contain line items like this, perhaps zookeeper crashed?
```
2021-01-30T02:26:20.4721007Z 02:26:18.342 [pulsar-ordered-OrderedExecutor-1-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/public/default due to -4
2021-01-30T02:26:20.4724056Z 02:26:18.342 [pulsar-ordered-OrderedExecutor-1-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/public/default due to -4
2021-01-30T02:26:20.4728053Z 02:26:18.342 [pulsar-ordered-OrderedExecutor-1-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/public/default due to -4
2021-01-30T02:26:20.4730821Z 02:26:18.342 [main-SendThread(zookeeper:2181)] ERROR org.apache.zookeeper.client.StaticHostProvider - Unable to resolve address: zookeeper:2181
2021-01-30T02:26:20.4733216Z java.net.UnknownHostException: zookeeper
2021-01-30T02:26:20.4734298Z 	at java.net.InetAddress.getAllByName0(InetAddress.java:1281) ~[?:1.8.0_282]
2021-01-30T02:26:20.4735595Z 	at java.net.InetAddress.getAllByName(InetAddress.java:1193) ~[?:1.8.0_282]
2021-01-30T02:26:20.4736679Z 	at java.net.InetAddress.getAllByName(InetAddre
2021-01-30T02:26:20.4740568Z 02:26:19.584 [docker-java-stream--455158542:org.apache.pulsar.tests.integration.utils.DockerUtils$2@221] INFO  org.apache.pulsar.tests.integration.utils.DockerUtils - DOCKER.exec(PulsarFunctionsProcessTest-qhxlj-pulsar-broker-1:tail -f /var/log/pulsar/broker.log): STDOUT: ss.java:1127) ~[?:1.8.0_282]
2021-01-30T02:26:20.4745047Z 	at org.apache.zookeeper.client.StaticHostProvider$1.getAllByName(StaticHostProvider.java:92) ~[org.apache.pulsar-pulsar-zookeeper-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
2021-01-30T02:26:20.4790474Z 	at org.apache.zookeeper.client.StaticHostProvider.resolve(StaticHostProvider.java:147) [org.apache.pulsar-pulsar-zookeeper-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
2021-01-30T02:26:20.4794117Z 	at org.apache.zookeeper.client.StaticHostProvider.next(StaticHostProvider.java:375) [org.apache.pulsar-pulsar-zookeeper-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
2021-01-30T02:26:20.4797190Z 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1137) [org.apache.pulsar-pulsar-zookeeper-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
2021-01-30T02:26:20.4800032Z 02:26:18.342 [pulsar-ordered-OrderedExecutor-1-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/public/default due to -4
2021-01-30T02:26:20.4802990Z 02:26:18.342 [pulsar-ordered-OrderedExecutor-1-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/public/defa
2021-01-30T02:26:20.4807081Z 02:26:19.584 [docker-java-stream--455158542:org.apache.pulsar.tests.integration.utils.DockerUtils$2@221] INFO  org.apache.pulsar.tests.integration.utils.DockerUtils - DOCKER.exec(PulsarFunctionsProcessTest-qhxlj-pulsar-broker-1:tail -f /var/log/pulsar/broker.log): STDOUT: ult due to -4
2021-01-30T02:26:20.4811096Z 02:26:18.342 [pulsar-ordered-OrderedExecutor-1-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/public/default due to -4
2021-01-30T02:26:20.4814065Z 02:26:18.342 [pulsar-ordered-OrderedExecutor-1-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/public/default due to -4
2021-01-30T02:26:20.4817038Z 02:26:18.342 [pulsar-ordered-OrderedExecutor-1-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/public/default due to -4
2021-01-30T02:26:20.4820003Z 02:26:18.342 [pulsar-ordered-OrderedExecutor-1-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/public/default due to -4
2021-01-30T02:26:20.4823158Z 02:26:18.342 [pulsar-ordered-OrderedExecutor-1-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/public/default due to -4
2021-01-30T02:26:20.4825098Z 02:26:18.342 [pulsar-ordered-OrderedExecutor-1-0-E
2021-01-30T02:26:20.4902652Z 02:26:19.584 [docker-java-stream--455158542:org.apache.pulsar.tests.integration.utils.DockerUtils$2@221] INFO  org.apache.pulsar.tests.integration.utils.DockerUtils - DOCKER.exec(PulsarFunctionsProcessTest-qhxlj-pulsar-broker-1:tail -f /var/log/pulsar/broker.log): STDOUT: ventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/public/default due to -4
2021-01-30T02:26:20.4908514Z 02:26:18.342 [pulsar-ordered-OrderedExecutor-1-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/public/default due to -4
2021-01-30T02:26:20.4915746Z 02:26:18.342 [pulsar-ordered-OrderedExecutor-1-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/public/default due to -4
2021-01-30T02:26:20.4918761Z 02:26:18.342 [pulsar-ordered-OrderedExecutor-1-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/public/default due to -4
2021-01-30T02:26:20.4924874Z 02:26:18.342 [pulsar-ordered-OrderedExecutor-1-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/public/default due to -4
2021-01-30T02:26:20.4930716Z 02:26:18.342 [pulsar-ordered-OrderedExecutor-1-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - F
2021-01-30T02:26:20.4934940Z 02:26:19.584 [docker-java-stream--455158542:org.apache.pulsar.tests.integration.utils.DockerUtils$2@221] INFO  org.apache.pulsar.tests.integration.utils.DockerUtils - DOCKER.exec(PulsarFunctionsProcessTest-qhxlj-pulsar-broker-1:tail -f /var/log/pulsar/broker.log): STDOUT: ailed to refresh zookeeper-cache for /admin/policies/public/default due to -4
2021-01-30T02:26:20.4985962Z 02:26:18.342 [pulsar-ordered-OrderedExecutor-1-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/public/default due to -4
2021-01-30T02:26:20.4989230Z 02:26:18.342 [pulsar-ordered-OrderedExecutor-1-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/public/default due to -4
2021-01-30T02:26:20.4992325Z 02:26:18.342 [pulsar-ordered-OrderedExecutor-1-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/public/default due to -4
2021-01-30T02:26:20.4995319Z 02:26:18.342 [pulsar-ordered-OrderedExecutor-1-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/public/default due to -4
2021-01-30T02:26:20.4998243Z 02:26:18.342 [pulsar-ordered-OrderedExecutor-1-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/public/defa
2021-01-30T02:26:20.5002543Z 02:26:19.586 [docker-java-stream--455158542:org.apache.pulsar.tests.integration.utils.DockerUtils$2@221] INFO  org.apache.pulsar.tests.integration.utils.DockerUtils - DOCKER.exec(PulsarFunctionsProcessTest-qhxlj-pulsar-broker-1:tail -f /var/log/pulsar/broker.log): STDOUT: ult due to -4
```

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
