### ISSUE TITLE
Flaky-test: ReplicatorTest.testReplication

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#9458]
org.apache.pulsar.broker.service.ReplicatorTest is flaky. The testReplication test method fails sporadically.

```
org.apache.pulsar.client.api.PulsarClientException$AuthorizationException: Client is not authorized to Produce
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:979)
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:94)
	at org.apache.pulsar.broker.service.ReplicatorTestBase$MessageProducer.<init>(ReplicatorTestBase.java:301)
	at org.apache.pulsar.broker.service.ReplicatorTest.testReplication(ReplicatorTest.java:295)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-02-01T01:35:59.4539012Z](https://github.com/apache/pulsar/runs/1803320722?check_suite_focus=true#step:9:508)
[example failure 2021-02-01T01:35:59.4493873Z](https://github.com/apache/pulsar/runs/1803320722?check_suite_focus=true#step:9:489)
[example failure 2021-01-30T07:38:30.7674464Z](https://github.com/apache/pulsar/runs/1796559473?check_suite_focus=true#step:8:667)
[example failure 2021-01-30T07:38:30.7639225Z](https://github.com/apache/pulsar/runs/1796559473?check_suite_focus=true#step:8:648)
[example failure 2021-01-29T04:50:34.2255253Z](https://github.com/apache/pulsar/runs/1789157136?check_suite_focus=true#step:8:508)
[example failure 2021-01-29T04:50:34.2177223Z](https://github.com/apache/pulsar/runs/1789157136?check_suite_focus=true#step:8:489)
[example failure 2021-01-29T04:34:55.1330899Z](https://github.com/apache/pulsar/runs/1789139622?check_suite_focus=true#step:8:508)
[example failure 2021-01-29T04:34:55.1231886Z](https://github.com/apache/pulsar/runs/1789139622?check_suite_focus=true#step:8:489)
[example failure 2021-01-29T00:06:45.0299447Z](https://github.com/apache/pulsar/runs/1788137301?check_suite_focus=true#step:8:508)
[example failure 2021-01-29T00:06:45.0264300Z](https://github.com/apache/pulsar/runs/1788137301?check_suite_focus=true#step:8:489)
[example failure 2021-01-28T18:15:18.2988053Z](https://github.com/apache/pulsar/runs/1784537496?check_suite_focus=true#step:8:656)
[example failure 2021-01-28T18:15:18.2959689Z](https://github.com/apache/pulsar/runs/1784537496?check_suite_focus=true#step:8:637)
[example failure 2021-01-26T21:41:26.0735469Z](https://github.com/apache/pulsar/runs/1770934077?check_suite_focus=true#step:8:508)
[example failure 2021-01-26T21:41:26.0647243Z](https://github.com/apache/pulsar/runs/1770934077?check_suite_focus=true#step:8:489)
[example failure 2021-01-26T02:02:01.4445808Z](https://github.com/apache/pulsar/runs/1766318508?check_suite_focus=true#step:8:508)
[example failure 2021-01-26T02:02:01.4403253Z](https://github.com/apache/pulsar/runs/1766318508?check_suite_focus=true#step:8:489)
[example failure 2021-01-25T22:27:52.3506097Z](https://github.com/apache/pulsar/runs/1762435483?check_suite_focus=true#step:8:667)
[example failure 2021-01-25T22:27:52.3451779Z](https://github.com/apache/pulsar/runs/1762435483?check_suite_focus=true#step:8:648)
[example failure 2021-01-25T12:24:27.5671729Z](https://github.com/apache/pulsar/runs/1760320664?check_suite_focus=true#step:8:656)
[example failure 2021-01-25T12:24:27.5516331Z](https://github.com/apache/pulsar/runs/1760320664?check_suite_focus=true#step:8:637)
[example failure 2021-01-22T11:39:17.6190592Z](https://github.com/apache/pulsar/runs/1748310523?check_suite_focus=true#step:8:508)
[example failure 2021-01-22T11:39:17.6113423Z](https://github.com/apache/pulsar/runs/1748310523?check_suite_focus=true#step:8:489)
[example failure 2021-01-21T21:09:43.3224477Z](https://github.com/apache/pulsar/runs/1743500150?check_suite_focus=true#step:8:647)
[example failure 2021-01-21T21:09:43.3183952Z](https://github.com/apache/pulsar/runs/1743500150?check_suite_focus=true#step:8:628)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
org.apache.pulsar.client.api.PulsarClientException$AuthorizationException: Client is not authorized to Produce
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:979)
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:94)
	at org.apache.pulsar.broker.service.ReplicatorTestBase$MessageProducer.<init>(ReplicatorTestBase.java:301)
	at org.apache.pulsar.broker.service.ReplicatorTest.testReplication(ReplicatorTest.java:295)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

</pre></code>
</details>

```
org.apache.pulsar.client.api.PulsarClientException$AuthorizationException: Client is not authorized to Produce
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:979)
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:95)
	at org.apache.pulsar.broker.service.ReplicatorTestBase$MessageProducer.<init>(ReplicatorTestBase.java:301)
	at org.apache.pulsar.broker.service.ReplicatorTest.testReplication(ReplicatorTest.java:295)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-02-02T13:46:14.3051150Z](https://github.com/apache/pulsar/runs/1813006738?check_suite_focus=true#step:9:508)
[example failure 2021-02-02T13:46:14.2968169Z](https://github.com/apache/pulsar/runs/1813006738?check_suite_focus=true#step:9:489)
[example failure 2021-02-01T03:56:01.5185348Z](https://github.com/apache/pulsar/runs/1803769568?check_suite_focus=true#step:9:667)
[example failure 2021-02-01T03:56:01.5079380Z](https://github.com/apache/pulsar/runs/1803769568?check_suite_focus=true#step:9:648)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
org.apache.pulsar.client.api.PulsarClientException$AuthorizationException: Client is not authorized to Produce
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:979)
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:95)
	at org.apache.pulsar.broker.service.ReplicatorTestBase$MessageProducer.<init>(ReplicatorTestBase.java:301)
	at org.apache.pulsar.broker.service.ReplicatorTest.testReplication(ReplicatorTest.java:295)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

</pre></code>
</details>

**Comment by lhotari** [comment]
Similar issues in testReplicatePeekAndSkip method.

```
org.apache.pulsar.client.api.PulsarClientException$AuthorizationException: Client is not authorized to Produce
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:979)
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:94)
	at org.apache.pulsar.broker.service.ReplicatorTestBase$MessageProducer.<init>(ReplicatorTestBase.java:301)
	at org.apache.pulsar.broker.service.ReplicatorTest.testReplicatePeekAndSkip(ReplicatorTest.java:451)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-02-01T01:35:59.3930831Z](https://github.com/apache/pulsar/runs/1803320722?check_suite_focus=true#step:9:405)
[example failure 2021-01-30T07:38:30.7445931Z](https://github.com/apache/pulsar/runs/1796559473?check_suite_focus=true#step:8:564)
[example failure 2021-01-29T04:50:34.1816114Z](https://github.com/apache/pulsar/runs/1789157136?check_suite_focus=true#step:8:405)
[example failure 2021-01-29T04:34:55.0968967Z](https://github.com/apache/pulsar/runs/1789139622?check_suite_focus=true#step:8:405)
[example failure 2021-01-29T00:06:44.9846566Z](https://github.com/apache/pulsar/runs/1788137301?check_suite_focus=true#step:8:405)
[example failure 2021-01-28T18:15:17.5098400Z](https://github.com/apache/pulsar/runs/1784537496?check_suite_focus=true#step:8:553)
[example failure 2021-01-26T21:41:25.9914089Z](https://github.com/apache/pulsar/runs/1770934077?check_suite_focus=true#step:8:405)
[example failure 2021-01-26T02:02:01.4166027Z](https://github.com/apache/pulsar/runs/1766318508?check_suite_focus=true#step:8:405)
[example failure 2021-01-25T22:27:52.2915803Z](https://github.com/apache/pulsar/runs/1762435483?check_suite_focus=true#step:8:564)
[example failure 2021-01-25T12:24:27.4867964Z](https://github.com/apache/pulsar/runs/1760320664?check_suite_focus=true#step:8:553)
[example failure 2021-01-22T11:39:17.5795634Z](https://github.com/apache/pulsar/runs/1748310523?check_suite_focus=true#step:8:405)
[example failure 2021-01-21T21:09:43.2682925Z](https://github.com/apache/pulsar/runs/1743500150?check_suite_focus=true#step:8:544)


<details>
<summary>Full exception stacktrace</summary>
<code><pre>
org.apache.pulsar.client.api.PulsarClientException$AuthorizationException: Client is not authorized to Produce
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:979)
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:94)
	at org.apache.pulsar.broker.service.ReplicatorTestBase$MessageProducer.<init>(ReplicatorTestBase.java:301)
	at org.apache.pulsar.broker.service.ReplicatorTest.testReplicatePeekAndSkip(ReplicatorTest.java:451)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

</pre></code>
</details>

```
org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.broker.service.ReplicatorTest.testReplicatePeekAndSkip() didn't finish within the time-out 30000
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-02-01T09:23:35.2532528Z](https://github.com/apache/pulsar/runs/1804639268?check_suite_focus=true#step:9:220)
[example failure 2021-01-29T03:33:46.4897010Z](https://github.com/apache/pulsar/runs/1788935938?check_suite_focus=true#step:8:553)
[example failure 2021-01-26T03:18:50.9534725Z](https://github.com/apache/pulsar/runs/1766603038?check_suite_focus=true#step:8:220)
[example failure 2021-01-25T22:26:49.8987651Z](https://github.com/apache/pulsar/runs/1762435483?check_suite_focus=true#step:8:220)
[example failure 2021-01-23T07:33:59.9204221Z](https://github.com/apache/pulsar/runs/1753234942?check_suite_focus=true#step:8:220)
[example failure 2021-01-12T15:04:54.5697148Z](https://github.com/apache/pulsar/runs/1688656661?check_suite_focus=true#step:8:402)


<details>
<summary>Full exception stacktrace</summary>
<code><pre>
org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.broker.service.ReplicatorTest.testReplicatePeekAndSkip() didn't finish within the time-out 30000
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:371)
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:282)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:605)
	at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:764)
	at org.testng.TestRunner.run(TestRunner.java:585)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.runSuites(TestNG.java:1069)
	at org.testng.TestNG.run(TestNG.java:1037)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

</pre></code>
</details>

```
org.apache.pulsar.client.api.PulsarClientException$AuthorizationException: Client is not authorized to Produce
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:979)
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:95)
	at org.apache.pulsar.broker.service.ReplicatorTestBase$MessageProducer.<init>(ReplicatorTestBase.java:301)
	at org.apache.pulsar.broker.service.ReplicatorTest.testReplicatePeekAndSkip(ReplicatorTest.java:451)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-02-02T13:46:14.2519579Z](https://github.com/apache/pulsar/runs/1813006738?check_suite_focus=true#step:9:405)
[example failure 2021-02-01T03:56:01.4441012Z](https://github.com/apache/pulsar/runs/1803769568?check_suite_focus=true#step:9:564)


<details>
<summary>Full exception stacktrace</summary>
<code><pre>
org.apache.pulsar.client.api.PulsarClientException$AuthorizationException: Client is not authorized to Produce
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:979)
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:95)
	at org.apache.pulsar.broker.service.ReplicatorTestBase$MessageProducer.<init>(ReplicatorTestBase.java:301)
	at org.apache.pulsar.broker.service.ReplicatorTest.testReplicatePeekAndSkip(ReplicatorTest.java:451)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

</pre></code>
</details>

**Comment by lhotari** [comment]
Flaky-test: org.apache.pulsar.broker.service.ReplicatorTest.testReplication
Number of failures: 6

org.apache.pulsar.broker.service.ReplicatorTest is flaky. The testReplication test method fails sporadically.

```
org.apache.pulsar.client.api.PulsarClientException$AuthorizationException: Client is not authorized to Produce
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:979)
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:95)
	at org.apache.pulsar.broker.service.ReplicatorTestBase$MessageProducer.<init>(ReplicatorTestBase.java:301)
	at org.apache.pulsar.broker.service.ReplicatorTest.testReplication(ReplicatorTest.java:297)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-03-08T00:24:45.4688122Z](https://github.com/apache/pulsar/runs/2052659566?check_suite_focus=true#step:8:385)
[example failure 2021-03-08T00:24:45.4458137Z](https://github.com/apache/pulsar/runs/2052659566?check_suite_focus=true#step:8:366)
[example failure 2021-03-05T08:57:35.5205645Z](https://github.com/apache/pulsar/runs/2037974359?check_suite_focus=true#step:8:381)


<details>
<summary>Full exception stacktrace</summary>
<code><pre>
org.apache.pulsar.client.api.PulsarClientException$AuthorizationException: Client is not authorized to Produce
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:979)
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:95)
	at org.apache.pulsar.broker.service.ReplicatorTestBase$MessageProducer.<init>(ReplicatorTestBase.java:301)
	at org.apache.pulsar.broker.service.ReplicatorTest.testReplication(ReplicatorTest.java:297)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

</pre></code>
</details>

```
org.apache.pulsar.client.api.PulsarClientException$AuthorizationException: Client is not authorized to Produce
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:979)
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:95)
	at org.apache.pulsar.broker.service.ReplicatorTestBase$MessageProducer.<init>(ReplicatorTestBase.java:301)
	at org.apache.pulsar.broker.service.ReplicatorTest.testReplication(ReplicatorTest.java:296)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-02-23T18:43:31.6518257Z](https://github.com/apache/pulsar/runs/1961603632?check_suite_focus=true#step:8:496)
[example failure 2021-02-23T18:43:31.6481685Z](https://github.com/apache/pulsar/runs/1961603632?check_suite_focus=true#step:8:477)


<details>
<summary>Full exception stacktrace</summary>
<code><pre>
org.apache.pulsar.client.api.PulsarClientException$AuthorizationException: Client is not authorized to Produce
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:979)
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:95)
	at org.apache.pulsar.broker.service.ReplicatorTestBase$MessageProducer.<init>(ReplicatorTestBase.java:301)
	at org.apache.pulsar.broker.service.ReplicatorTest.testReplication(ReplicatorTest.java:296)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

</pre></code>
</details>

```
org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException: HTTP get request failed: Internal Server Error
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:1027)
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:95)
	at org.apache.pulsar.broker.service.ReplicatorTestBase$MessageProducer.<init>(ReplicatorTestBase.java:301)
	at org.apache.pulsar.broker.service.ReplicatorTest.testReplication(ReplicatorTest.java:297)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-03-05T08:57:35.5257288Z](https://github.com/apache/pulsar/runs/2037974359?check_suite_focus=true#step:8:400)


<details>
<summary>Full exception stacktrace</summary>
<code><pre>
org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException: HTTP get request failed: Internal Server Error
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:1027)
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:95)
	at org.apache.pulsar.broker.service.ReplicatorTestBase$MessageProducer.<init>(ReplicatorTestBase.java:301)
	at org.apache.pulsar.broker.service.ReplicatorTest.testReplication(ReplicatorTest.java:297)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException: HTTP get request failed: Internal Server Error
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:93)
	... 14 more
Caused by: org.apache.pulsar.client.api.PulsarClientException: HTTP get request failed: Internal Server Error
	at org.apache.pulsar.client.impl.HttpClient.lambda$null$1(HttpClient.java:215)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at org.asynchttpclient.netty.NettyResponseFuture.loadContent(NettyResponseFuture.java:222)
	at org.asynchttpclient.netty.NettyResponseFuture.done(NettyResponseFuture.java:257)
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.finishUpdate(AsyncHttpClientHandler.java:241)
	at org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:114)
	at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:143)
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:387)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more

</pre></code>
</details>

**Comment by lhotari** [comment]
This issue might have been mitigated with earlier fixes, since there's no recent failures. The most recent failure is 2021-03-08. It seems that #9823 and #9787 have eliminated the flakiness of ReplicatorTest.testReplication.

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
