### ISSUE TITLE
Flaky-test: PulsarFunctionsTest.testDebeziumPostgreSqlSource

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#9459]
org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest is flaky. The testDebeziumPostgreSqlSource test method fails sporadically.

```
java.lang.AssertionError: expected [9] but found [18]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.pulsar.tests.integration.io.SourceTester.validateSourceResultJson(SourceTester.java:112)
	at org.apache.pulsar.tests.integration.io.SourceTester.validateSourceResult(SourceTester.java:91)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testDebeziumPostgreSqlConnect(PulsarFunctionsTest.java:2487)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testDebeziumPostgreSqlSource(PulsarFunctionsTest.java:166)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-01-27T06:39:14.9992308Z](https://github.com/apache/pulsar/runs/1774583665?check_suite_focus=true#step:13:4560)
[example failure 2021-01-26T15:40:54.1179988Z](https://github.com/apache/pulsar/runs/1768818440?check_suite_focus=true#step:13:13283)
[example failure 2021-01-26T15:34:28.7737830Z](https://github.com/apache/pulsar/runs/1768818440?check_suite_focus=true#step:13:8732)
[example failure 2021-01-26T15:28:04.6846521Z](https://github.com/apache/pulsar/runs/1768818440?check_suite_focus=true#step:13:4365)
[example failure 2021-01-26T08:45:59.1658699Z](https://github.com/apache/pulsar/runs/1767404835?check_suite_focus=true#step:13:4508)
[example failure 2021-01-26T02:03:44.7749540Z](https://github.com/apache/pulsar/runs/1766085301?check_suite_focus=true#step:13:4359)
[example failure 2021-01-25T08:42:16.8265157Z](https://github.com/apache/pulsar/runs/1759745320?check_suite_focus=true#step:13:4409)
[example failure 2021-01-24T07:59:32.1785602Z](https://github.com/apache/pulsar/runs/1756352592?check_suite_focus=true#step:13:4366)
[example failure 2021-01-24T02:31:04.9984523Z](https://github.com/apache/pulsar/runs/1755730905?check_suite_focus=true#step:13:4743)
[example failure 2021-01-23T06:02:05.2139687Z](https://github.com/apache/pulsar/runs/1752936738?check_suite_focus=true#step:13:4370)
[example failure 2021-01-22T03:35:42.3280145Z](https://github.com/apache/pulsar/runs/1746201292?check_suite_focus=true#step:13:4362)
[example failure 2021-01-22T00:18:05.6781763Z](https://github.com/apache/pulsar/runs/1745443385?check_suite_focus=true#step:13:4401)
[example failure 2021-01-20T12:06:33.0318072Z](https://github.com/apache/pulsar/runs/1733836670?check_suite_focus=true#step:13:8756)
[example failure 2021-01-20T12:00:27.7695066Z](https://github.com/apache/pulsar/runs/1733836670?check_suite_focus=true#step:13:4352)
[example failure 2021-01-07T09:42:06.7127965Z](https://github.com/apache/pulsar/runs/1661300198?check_suite_focus=true#step:13:5060)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
java.lang.AssertionError: expected [9] but found [18]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.pulsar.tests.integration.io.SourceTester.validateSourceResultJson(SourceTester.java:112)
	at org.apache.pulsar.tests.integration.io.SourceTester.validateSourceResult(SourceTester.java:91)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testDebeziumPostgreSqlConnect(PulsarFunctionsTest.java:2487)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testDebeziumPostgreSqlSource(PulsarFunctionsTest.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

</pre></code>
</details>

[example failure 2021-01-25T13:55:24.2903589Z](https://github.com/apache/pulsar/runs/1760325916?check_suite_focus=true#step:13:4746)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
java.lang.AssertionError: expected [9] but found [18]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.pulsar.tests.integration.io.SourceTester.validateSourceResultJson(SourceTester.java:112)
	at org.apache.pulsar.tests.integration.io.SourceTester.validateSourceResult(SourceTester.java:91)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testDebeziumPostgreSqlConnect(PulsarFunctionsTest.java:2487)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testDebeziumPostgreSqlSource(PulsarFunctionsTest.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

13:55:24.266 [docker-java-stream-702266328:org.apache.pulsar.tests.integration.utils.DockerUtils$2@221] INFO  org.apache.pulsar.tests.integration.utils.DockerUtils - DOCKER.exec(PulsarFunctionsThreadTest-qbcjw-pulsar-broker-0:tail -f /var/log/pulsar/broker.log): STDOUT: 13:55:23.851 [pulsar-io-24-4] INFO  org.apache.pulsar.broker.service.ServerCnx - [/172.19.0.8:42926] Closing consumer: consumerId=0
13:55:23.851 [pulsar-io-24-4] INFO  org.apache.pulsar.broker.service.AbstractDispatcherSingleActiveConsumer - Removing consumer Consumer{subscription=PersistentSubscription{topic=persistent://debezium/postgresql/dbserver1.inventory.products, name=debezium-source-tester}, consumerId=0, consumerName=e24fb, address=/172.19.0.8:42926}
13:55:23.852 [pulsar-io-24-4] INFO  org.apache.pulsar.broker.service.ServerCnx - [/172.19.0.8:42926] Closed consumer, consumerId=0
13:55:23.862 [pulsar-io-24-4] INFO  org.apache.pulsar.broker.service.ServerCnx - Closed connection from /172.19.0.8:42926
13:55:23.872 [pulsar-io-24-3] INFO  org.apache.pulsar.broker.service.ServerCnx - Closed connection from /172.19.0.8:42920
</pre></code>
</details>

[example failure 2021-01-30T08:05:02.0306885Z](https://github.com/apache/pulsar/runs/1796487110?check_suite_focus=true#step:14:4941)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
java.lang.AssertionError: expected [9] but found [18]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.pulsar.tests.integration.io.SourceTester.validateSourceResultJson(SourceTester.java:112)
	at org.apache.pulsar.tests.integration.io.SourceTester.validateSourceResult(SourceTester.java:91)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testDebeziumPostgreSqlConnect(PulsarFunctionsTest.java:2487)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testDebeziumPostgreSqlSource(PulsarFunctionsTest.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

08:05:01.938 [docker-java-stream-1743222451:org.apache.pulsar.tests.integration.utils.DockerUtils$2@221] INFO  org.apache.pulsar.tests.integration.utils.DockerUtils - DOCKER.exec(PulsarFunctionsThreadTest-wpaab-pulsar-broker-1:tail -f /var/log/pulsar/broker.log): STDOUT: 08:05:01.496 [pulsar-io-24-1] INFO  org.apache.pulsar.broker.service.ServerCnx - [/172.20.0.8:60666] Closing consumer: consumerId=0
08:05:01.496 [pulsar-io-24-1] INFO  org.apache.pulsar.broker.service.AbstractDispatcherSingleActiveConsumer - Removing consumer Consumer{subscription=PersistentSubscription{topic=persistent://debezium/postgresql/dbserver1.inventory.products, name=debezium-source-tester}, consumerId=0, consumerName=a3fa0, address=/172.20.0.8:60666}
08:05:01.496 [pulsar-io-24-1] INFO  org.apache.pulsar.broker.service.ServerCnx - [/172.20.0.8:60666] Closed consumer, consumerId=0
08:05:01.527 [pulsar-io-24-1] INFO  org.apache.pulsar.broker.service.ServerCnx - Closed connection from /172.20.0.8:60666
08:05:01.543 [pulsar-io-24-4] INFO  org.apache.pulsar.broker.service.ServerCnx - Closed connection from /172.20.0.8:60660
</pre></code>
</details>

[example failure 2021-01-07T09:48:26.2617356Z](https://github.com/apache/pulsar/runs/1661300198?check_suite_focus=true#step:13:9603)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
java.lang.AssertionError: expected [9] but found [18]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.pulsar.tests.integration.io.SourceTester.validateSourceResultJson(SourceTester.java:112)
	at org.apache.pulsar.tests.integration.io.SourceTester.validateSourceResult(SourceTester.java:91)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testDebeziumPostgreSqlConnect(PulsarFunctionsTest.java:2487)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testDebeziumPostgreSqlSource(PulsarFunctionsTest.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

09:48:26.171 [docker-java-stream-2099196559:org.apache.pulsar.tests.integration.utils.DockerUtils$2@221] INFO  org.apache.pulsar.tests.integration.utils.DockerUtils - DOCKER.exec(PulsarFunctionsThreadTest-zszng-pulsar-broker-0:tail -f /var/log/pulsar/broker.log): STDOUT: 09:48:25.768 [pulsar-io-23-3] INFO  org.apache.pulsar.broker.service.ServerCnx - [/172.20.0.8:36668] Closing consumer: 0
09:48:25.769 [pulsar-io-23-3] INFO  org.apache.pulsar.broker.service.AbstractDispatcherSingleActiveConsumer - Removing consumer Consumer{subscription=PersistentSubscription{topic=persistent://debezium/postgresql/dbserver1.inventory.products, name=debezium-source-tester}, consumerId=0, consumerName=e8b42, address=/172.20.0.8:36668}
09:48:25.769 [pulsar-io-23-3] INFO  org.apache.pulsar.broker.service.ServerCnx - [/172.20.0.8:36668] Closed consumer Consumer{subscription=PersistentSubscription{topic=persistent://debezium/postgresql/dbserver1.inventory.products, name=debezium-source-tester}, consumerId=0, consumerName=e8b42, address=/172.20.0.8:36668}
09:48:25.800 [pulsar-io-23-3] INFO  org.apache.pulsar.broker.service.ServerCnx - Closed connection from /172.20.0.8:36668
09:48:26.203 [docker-java-stream-1220710756:org.apache.pulsar.tests.integration.utils.DockerUtils$2@221] INFO  org.apache.pulsar.tests.integration.utils.DockerUtils - DOCKER.exec(PulsarFunctionsThreadTest-zszng-pulsar-broker-1:tail -f /var/log/pulsar/broker.log): STDOUT: 09:48:25.650 [pulsar-io-23-2] INFO  org.apache.pulsar.broker.service.ServerCnx - [PersistentTopic{topic=persistent://public/default/debe-output-topic-name}][PulsarFunctionsThreadTest-zszng-1-21] Closing producer on cnx /172.20.0.10:44418
09:48:25.650 [pulsar-io-23-2] INFO  org.apache.pulsar.broker.service.ServerCnx - [PersistentTopic{topic=persistent://public/default/debe-output-topic-name}][PulsarFunctionsThreadTest-zszng-1-21] Closed producer on cnx /172.20.0.10:44418
09:48:25.808 [pulsar-io-23-1] INFO  org.apache.pulsar.broker.service.ServerCnx - Closed connection from /172.20.0.8:47294
</pre></code>
</details>

```
java.lang.AssertionError: expected [9] but found [18]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.pulsar.tests.integration.io.SourceTester.validateSourceResultJson(SourceTester.java:112)
	at org.apache.pulsar.tests.integration.io.SourceTester.validateSourceResult(SourceTester.java:91)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testDebeziumPostgreSqlConnect(PulsarFunctionsTest.java:2504)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testDebeziumPostgreSqlSource(PulsarFunctionsTest.java:168)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-02-01T19:25:28.5163086Z](https://github.com/apache/pulsar/runs/1808358209?check_suite_focus=true#step:14:5208)
[example failure 2021-02-01T06:17:56.0805077Z](https://github.com/apache/pulsar/runs/1804096915?check_suite_focus=true#step:14:4384)
[example failure 2021-01-29T09:37:49.8471136Z](https://github.com/apache/pulsar/runs/1789953375?check_suite_focus=true#step:13:13495)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
java.lang.AssertionError: expected [9] but found [18]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.pulsar.tests.integration.io.SourceTester.validateSourceResultJson(SourceTester.java:112)
	at org.apache.pulsar.tests.integration.io.SourceTester.validateSourceResult(SourceTester.java:91)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testDebeziumPostgreSqlConnect(PulsarFunctionsTest.java:2504)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testDebeziumPostgreSqlSource(PulsarFunctionsTest.java:168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

</pre></code>
</details>

[example failure 2021-01-30T02:42:42.0546168Z](https://github.com/apache/pulsar/runs/1795667943?check_suite_focus=true#step:14:4373)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
java.lang.AssertionError: expected [9] but found [18]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.pulsar.tests.integration.io.SourceTester.validateSourceResultJson(SourceTester.java:112)
	at org.apache.pulsar.tests.integration.io.SourceTester.validateSourceResult(SourceTester.java:91)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testDebeziumPostgreSqlConnect(PulsarFunctionsTest.java:2504)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testDebeziumPostgreSqlSource(PulsarFunctionsTest.java:168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

02:42:42.000 [docker-java-stream-655700891:org.apache.pulsar.tests.integration.utils.DockerUtils$2@221] INFO  org.apache.pulsar.tests.integration.utils.DockerUtils - DOCKER.exec(PulsarFunctionsThreadTest-asltd-pulsar-broker-0:tail -f /var/log/pulsar/broker.log): STDOUT: 02:42:41.644 [pulsar-io-25-4] INFO  org.apache.pulsar.broker.service.ServerCnx - [/172.19.0.8:36900] Closing consumer: consumerId=0
02:42:41.644 [pulsar-io-25-4] INFO  org.apache.pulsar.broker.service.AbstractDispatcherSingleActiveConsumer - Removing consumer Consumer{subscription=PersistentSubscription{topic=persistent://debezium/postgresql/dbserver1.inventory.products, name=debezium-source-tester}, consumerId=0, consumerName=f9445, address=/172.19.0.8:36900}
02:42:41.646 [pulsar-io-25-4] INFO  org.apache.pulsar.broker.service.ServerCnx - [/172.19.0.8:36900] Closed consumer, consumerId=0
02:42:41.678 [pulsar-io-25-4] INFO  org.apache.pulsar.broker.service.ServerCnx - Closed connection from /172.19.0.8:36900
</pre></code>
</details>

[example failure 2021-01-30T15:32:29.4136946Z](https://github.com/apache/pulsar/runs/1797634050?check_suite_focus=true#step:14:4535)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
java.lang.AssertionError: expected [9] but found [18]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.pulsar.tests.integration.io.SourceTester.validateSourceResultJson(SourceTester.java:112)
	at org.apache.pulsar.tests.integration.io.SourceTester.validateSourceResult(SourceTester.java:91)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testDebeziumPostgreSqlConnect(PulsarFunctionsTest.java:2504)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testDebeziumPostgreSqlSource(PulsarFunctionsTest.java:168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

15:32:29.278 [docker-java-stream-1462882477:org.apache.pulsar.tests.integration.utils.DockerUtils$2@221] INFO  org.apache.pulsar.tests.integration.utils.DockerUtils - DOCKER.exec(PulsarFunctionsThreadTest-pqxlv-pulsar-broker-0:tail -f /var/log/pulsar/broker.log): STDOUT: 15:32:28.881 [pulsar-io-25-3] INFO  org.apache.pulsar.broker.service.ServerCnx - [/172.19.0.8:42034] Closing consumer: consumerId=0
15:32:28.881 [pulsar-io-25-3] INFO  org.apache.pulsar.broker.service.AbstractDispatcherSingleActiveConsumer - Removing consumer Consumer{subscription=PersistentSubscription{topic=persistent://debezium/postgresql/dbserver1.inventory.products, name=debezium-source-tester}, consumerId=0, consumerName=fb63e, address=/172.19.0.8:42034}
15:32:28.881 [pulsar-io-25-3] INFO  org.apache.pulsar.broker.service.ServerCnx - [/172.19.0.8:42034] Closed consumer, consumerId=0
15:32:28.906 [pulsar-io-25-3] INFO  org.apache.pulsar.broker.service.ServerCnx - Closed connection from /172.19.0.8:42034
</pre></code>
</details>

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
