### ISSUE TITLE
BufferOverflowException occurs while query data by Pulsar SQL and compression enabled.

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#9666]
**Describe the bug**
Here is the error log:

```
2021-02-22T08:29:11.873+0800	INFO	derserialize-thread-split-1	stderr	java.nio.BufferOverflowException
2021-02-22T08:29:11.873+0800	INFO	derserialize-thread-split-1	stderr		at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:206)
2021-02-22T08:29:11.873+0800	INFO	derserialize-thread-split-1	stderr		at org.apache.pulsar.common.compression.AirliftUtils.ensureAirliftSupported(AirliftUtils.java:32)
2021-02-22T08:29:11.873+0800	INFO	derserialize-thread-split-1	stderr		at org.apache.pulsar.common.compression.CompressionCodecZstd.decode(CompressionCodecZstd.java:100)
2021-02-22T08:29:11.873+0800	INFO	derserialize-thread-split-1	stderr		at org.apache.pulsar.common.api.raw.MessageParser.uncompressPayloadIfNeeded(MessageParser.java:140)
2021-02-22T08:29:11.873+0800	INFO	derserialize-thread-split-1	stderr		at org.apache.pulsar.common.api.raw.MessageParser.parseMessage(MessageParser.java:85)
2021-02-22T08:29:11.873+0800	INFO	derserialize-thread-split-1	stderr		at org.apache.pulsar.sql.presto.PulsarRecordCursor$DeserializeEntries$1.accept(PulsarRecordCursor.java:243)
2021-02-22T08:29:11.873+0800	INFO	derserialize-thread-split-1	stderr		at org.apache.pulsar.sql.presto.PulsarRecordCursor$DeserializeEntries$1.accept(PulsarRecordCursor.java:224)
2021-02-22T08:29:11.873+0800	INFO	derserialize-thread-split-1	stderr		at org.jctools.queues.SpscArrayQueue.drain(SpscArrayQueue.java:266)
2021-02-22T08:29:11.873+0800	INFO	derserialize-thread-split-1	stderr		at org.jctools.queues.SpscArrayQueue.drain(SpscArrayQueue.java:239)
2021-02-22T08:29:11.874+0800	INFO	derserialize-thread-split-1	stderr		at org.apache.pulsar.sql.presto.PulsarRecordCursor$DeserializeEntries.run(PulsarRecordCursor.java:224)
2021-02-22T08:29:11.874+0800	INFO	derserialize-thread-split-1	stderr		at java.lang.Thread.run(Thread.java:748)
2021-02-22T08:29:11.874+0800	INFO	derserialize-thread-split-0	stderr	Exception in thread "derserialize-thread-split-0"
2021-02-22T08:29:11.874+0800	INFO	derserialize-thread-split-0	stderr	java.nio.BufferOverflowException
2021-02-22T08:29:11.874+0800	INFO	derserialize-thread-split-0	stderr		at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:206)
2021-02-22T08:29:11.874+0800	INFO	derserialize-thread-split-0	stderr		at org.apache.pulsar.common.compression.AirliftUtils.ensureAirliftSupported(AirliftUtils.java:32)
2021-02-22T08:29:11.874+0800	INFO	derserialize-thread-split-0	stderr		at org.apache.pulsar.common.compression.CompressionCodecZstd.decode(CompressionCodecZstd.java:100)
2021-02-22T08:29:11.874+0800	INFO	derserialize-thread-split-0	stderr		at org.apache.pulsar.common.api.raw.MessageParser.uncompressPayloadIfNeeded(MessageParser.java:140)
2021-02-22T08:29:11.874+0800	INFO	derserialize-thread-split-0	stderr		at org.apache.pulsar.common.api.raw.MessageParser.parseMessage(MessageParser.java:85)
2021-02-22T08:29:11.874+0800	INFO	derserialize-thread-split-0	stderr		at org.apache.pulsar.sql.presto.PulsarRecordCursor$DeserializeEntries$1.accept(PulsarRecordCursor.java:243)
2021-02-22T08:29:11.874+0800	INFO	derserialize-thread-split-0	stderr		at org.apache.pulsar.sql.presto.PulsarRecordCursor$DeserializeEntries$1.accept(PulsarRecordCursor.java:224)
2021-02-22T08:29:11.874+0800	INFO	derserialize-thread-split-0	stderr		at org.jctools.queues.SpscArrayQueue.drain(SpscArrayQueue.java:266)
2021-02-22T08:29:11.874+0800	INFO	derserialize-thread-split-0	stderr		at org.jctools.queues.SpscArrayQueue.drain(SpscArrayQueue.java:239)
2021-02-22T08:29:11.874+0800	INFO	derserialize-thread-split-0	stderr		at org.apache.pulsar.sql.presto.PulsarRecordCursor$DeserializeEntries.run(PulsarRecordCursor.java:224)
2021-02-22T08:29:11.875+0800	INFO	derserialize-thread-split-0	stderr		at java.lang.Thread.run(Thread.java:748)
```

The root cause of this issue is the compression data size greater than the original data size.

**To Reproduce**
1. Send message `Pulsar` to a topic with Zstd compression
2.  Query data from topic
3. See error

**Versions**
1. branch master
2. branch-2.7
3. branch-2.6

**Comment by codelipenghui** [comment]
Related to #9658

**Comment by codelipenghui** [comment]
@gaoran10 Please help take a look at this issue, thanks.

**Comment by gaoran10** [comment]
Ok, I'll fix this problem.
