### ISSUE TITLE
Java Client: NullPointerException with GenericRecord.getField() on a sub-record

### ISSUE THREAD

**Issue by epsteina16** [apache/pulsar#9697]
**Describe the bug**
Calling GenericRecord.getField(Field field) on a GenericRecord that is a sub-record, where the field is a string, the Pulsar client throws a NullPointerException:

java.lang.NullPointerException
	at org.apache.pulsar.client.impl.schema.generic.GenericJsonRecord.isBinaryValue(GenericJsonRecord.java:110)
	at org.apache.pulsar.client.impl.schema.generic.GenericJsonRecord.getField(GenericJsonRecord.java:87)
	at org.apache.pulsar.client.api.schema.GenericRecord.getField(GenericRecord.java:53)

**To Reproduce**
1. Using the Pulsar Java Client create a consumer of type Schema.AUTO_CONSUME, to receive GenericRecords from the broker.
2. Fill the topic with messages with a subrecord with a string in it, in the form of a JsonSchema. This is an example schema:
    {
	"type": "JSON",
        "schema": "{\"type\":\"record\",\"namespace\":\"com.example\",\"name\":\"MyJsonSchema\",\"fields\":[{\"name\":\"subrecord_field\",\"type\":{\"type\":\"record\",\"name\":\"subrecord_field\",\"fields\":[{\"name\":\"substring_field\",\"type\":\"string\"}]}}]}",
	"properties": {}
}  
3. When a message is received, get the subrecord by calling .getField(Field field) on the top level record.
4. The try to get the field for the substring field by calling .getField() on the subrecord.

Example code:
GenericRecord subRecord = record.getField("subrecord_field");
subRecord.getField("substring_field"); // This will throw a null pointer exception

**Expected behavior**
getField should return the Object that is the field. i.e. for this, we should get a String back.

**Desktop (please complete the following information):**
 - OS: linux

**Additional context**
Pulsar client version 2.7.0

**Comment by codelipenghui** [comment]
@congbobo184 Could you please take a look at this issue?

**Comment by congbobo184** [comment]
@epsteina16 does the ```subrecord_field``` have value?

**Comment by epsteina16** [comment]
The `subrecord_field` contains fields. Whether or not `substring_field` is an empty string or has content, I see this. Pulsar should not have a NPE either way.

**Comment by codelipenghui** [comment]
@epsteina16 Agree, I notice `substring_field` is not allow null from the schema definition right? Can the writer write a message with `substring_field=null`?

@congbobo184 I think we need to fix this case, we should check if the GenericRecord has this field, if not, we should return null. You mentioned have value or don't have value, this means not null or null?

**Comment by eolivelli** [comment]
@vroyer PTAL
are you interested in providing a fix ?

**Comment by congbobo184** [comment]
Move this to the next release.

**Comment by eolivelli** [comment]
I believe that probably this has already been fixed

**Comment by michaeljmarshall** [comment]
@epsteina16 - can you confirm whether or not this bug is still present in recent releases of Pulsar? We are releasing 2.7.4 now, so I am going to remove this label. However, if the bug still exists, we should fix it. Thanks

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
