### ISSUE TITLE
Flaky-test: PersistentTopicE2ETest.testPayloadCorruptionDetection

### ISSUE THREAD

**Issue by MarvinCai** [apache/pulsar#9708]
https://github.com/apache/pulsar/pull/9659/checks?check_run_id=1975526561

```
2021-02-25T02:43:22.2268540Z [ERROR] testPayloadCorruptionDetection(org.apache.pulsar.broker.service.PersistentTopicE2ETest)  Time elapsed: 2.705 s  <<< FAILURE!
2021-02-25T02:43:22.2270357Z java.lang.NullPointerException
2021-02-25T02:43:22.2290842Z 	at org.apache.pulsar.broker.service.PersistentTopicE2ETest.testPayloadCorruptionDetection(PersistentTopicE2ETest.java:1472)
2021-02-25T02:43:22.2306727Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-02-25T02:43:22.2309848Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-02-25T02:43:22.2313554Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-02-25T02:43:22.2317109Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2021-02-25T02:43:22.2318689Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
2021-02-25T02:43:22.2320608Z 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
2021-02-25T02:43:22.2324631Z 	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
2021-02-25T02:43:22.2326265Z 	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
2021-02-25T02:43:22.2331996Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-02-25T02:43:22.2334821Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2021-02-25T02:43:22.2349797Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2021-02-25T02:43:22.2350847Z 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
