### ISSUE TITLE
Creating and modifying authorization policies is not thread safe

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#9711]
**Describe the bug**

Creating and modifying authorization policies is not thread safe. It leads to unexpected NullPointerExceptions for example and could lead to authorization data corruption.

**To Reproduce**

The flaky test #9709 is one example of the problem.

**Expected behavior**

Creating and modifying authorization policies should be thread safe.

**Observations**

It looks like the [org.apache.pulsar.common.policies.data.AuthPolicies](https://github.com/apache/pulsar/blob/master/pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/AuthPolicies.java) data structures are modified without a way to ensure thread safety and data consistency.

**Comment by eolivelli** [comment]
Good catch @lhotari 

I believe this is a blocker issue.

@wolfstudy @codelipenghui can we fix it for 2.7.1 ?

**Comment by 315157973** [comment]
When updating, a version will be passed in to determine whether the data has been modified. This is an optimistic lock. Why is there a thread safety issue?

**Comment by lhotari** [comment]
> When updating, a version will be passed in to determine whether the data has been modified. This is an optimistic lock. Why is there a thread safety issue?

that part is not the concern. The concerns are the maps that are the maps contained in the cached AuthPolicies entry. They are mutated without synchronization on both read & write access. Mutation for example here:
https://github.com/apache/pulsar/blob/7001f64aab6335b5192b408dba1e85602dd5ea6b/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java#L688
Accessed here:
https://github.com/apache/pulsar/blob/1fab5aa69446b4c2eaebb615d35fe9f5a509ba4c/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java#L206

**Comment by lhotari** [comment]
Another example of missing concurrency control:
https://github.com/apache/pulsar/blob/1fab5aa69446b4c2eaebb615d35fe9f5a509ba4c/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java#L325-L330

**Comment by 315157973** [comment]
> > When updating, a version will be passed in to determine whether the data has been modified. This is an optimistic lock. Why is there a thread safety issue?
> 
> that part is not the concern. The concerns are the maps that are contained in the cached AuthPolicies entry. They are mutated without synchronization on both read & write access. Mutation for example here:
> https://github.com/apache/pulsar/blob/7001f64aab6335b5192b408dba1e85602dd5ea6b/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java#L688
> 
> 
> Accessed here:
> https://github.com/apache/pulsar/blob/1fab5aa69446b4c2eaebb615d35fe9f5a509ba4c/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java#L206

Could you give an example like the following?

```
//MetadataCacheImpl.java 175
return store.put(path, newValue, Optional.of(expectedVersion)).thenAccept(stat -> {
                        objCache.put(path,
                                FutureUtils.value(Optional.of(new SimpleImmutableEntry<T, Stat>(newValueObj, stat))));
                    });
```
Normal scene:
t1: thread 1 updates zk successfully
t2: thread 1 updates the cache
t3: thread 2 updates zk successfully
t4: Thread 2 updates the cache

Concurrent scene:
t1: thread 1 updates zk successfully
t2: Thread 2 updates zk, which fails because the version is different
t3: Thread 1 updates the cache

**Comment by lhotari** [comment]
> Could you give an example like the following?

the problem is not about certain sequence of events. It's about unsafe mutation and access of the TreeMap / HashMap instances contained in the AuthPolicies class. A TreeMap or HashMap can only be safely mutated when all access (mutation and reading) happens under the same object monitor. Violating this rule will lead to undeterministic behavior.

**Comment by lhotari** [comment]
While investigating the flakiness in ReplicatorTest, I happened to come across this NPE related to the issues in creating and modifying authorization policies:
```
Caused by: java.lang.NullPointerException
	at java.util.TreeMap.getEntry(TreeMap.java:347) ~[?:1.8.0_275]
	at java.util.TreeMap.get(TreeMap.java:278) ~[?:1.8.0_275]
	at org.apache.pulsar.broker.authorization.PulsarAuthorizationProvider.lambda$checkPermission$12(PulsarAuthorizationProvider.java:404) ~[pulsar-broker-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_275]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) ~[?:1.8.0_275]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) ~[?:1.8.0_275]
	at org.apache.pulsar.broker.authorization.PulsarAuthorizationProvider.checkPermission(PulsarAuthorizationProvider.java:397) ~[pulsar-broker-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	at org.apache.pulsar.broker.authorization.PulsarAuthorizationProvider.checkAuthorization(PulsarAuthorizationProvider.java:378) ~[pulsar-broker-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	at org.apache.pulsar.broker.authorization.PulsarAuthorizationProvider.lambda$canConsumeAsync$2(PulsarAuthorizationProvider.java:148) ~[pulsar-broker-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_275]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) ~[?:1.8.0_275]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) ~[?:1.8.0_275]
	at org.apache.pulsar.broker.authorization.PulsarAuthorizationProvider.canConsumeAsync(PulsarAuthorizationProvider.java:112) ~[pulsar-broker-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	at org.apache.pulsar.broker.authorization.AuthorizationService.lambda$canConsumeAsync$1(AuthorizationService.java:216) ~[pulsar-broker-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966) ~[?:1.8.0_275]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940) ~[?:1.8.0_275]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_275]
	... 1 more
```

**Comment by lhotari** [comment]
It seems that ReplicatorTest triggers some of the thread safety issues  in updating policies. Some of the [reported issues about ReplicatorTest flakiness](https://github.com/apache/pulsar/search?o=desc&q=replicatortest&s=updated&type=issues).

**Comment by codelipenghui** [comment]
@eolivelli we don't want to block the 2.7.1 release, instead we can accelerate the 2.7.2 release. Here is the release proposal that we have discussed before https://github.com/apache/pulsar/wiki/PIP-47%3A-Time-Based-Release-Plan. If the problem is not introduced after 2.7.0 and it does not break the existing behavior, it's better to do not to block the 2.7.1 release.

**Comment by eolivelli** [comment]
@codelipenghui I am fine with keeping it only on master branch.

**Comment by lhotari** [comment]
On a busy system, unsafe HashMap mutation and access will eventually lead to infinite loops and 100% CPU core usage when the HashMap data structures get corrupted.
This problem is [demonstrated and explained in this article](https://dzone.com/articles/java-7-hashmap-vs), in the section "HashMap infinite looping problem replication". 

I might be missing something, but I can see that the Pulsar policy creation and modification contains quite a few locations where there is unsafe HashMap/TreeMap mutation and access. @merlimat PTAL

**Comment by 315157973** [comment]
@lhotari  How about change HashMap to ConcurrentHashMap, and do not update the cache, only invalidate the cache

**Comment by lhotari** [comment]
> @lhotari How about change HashMap to ConcurrentHashMap, and do not update the cache, only invalidate the cache .

+1, I guess ConcurrentHashMap is one possibility and probably leads to the simplest fix to the issue.

In general, I'd prefer a solution that is based on immutability so that an update returns a new copy and new instance. This approach is used in an open PR #9598 . However in that case, there aren't Maps that are involved. 
Using persistent collections such as [PCollections library](https://github.com/hrldcpr/pcollections) could be useful in the immutable approach.

**Comment by 315157973** [comment]
> In general, I'd prefer a solution that is based on immutability so that an update returns a new copy and new instance. This approach is used in an open PR #9598 . However in that case, there aren't Maps that are involved.

Creating new objects will produce garbage, I think ConcurrentHashMap will be better

**Comment by lhotari** [comment]
> Creating new objects will produce garbage, I think ConcurrentHashMap will be better

New objects are only a problem if it causes a bottleneck. I don't think that policy modifications would be a large part of the workload. Therefore there isn't a reason to reject solutions around immutability.
btw. Persistent data collections such as [PCollections library](https://github.com/hrldcpr/pcollections) help minimize the number of new objects that are created when using immutable collections.

**Comment by 315157973** [comment]
> New objects are only a problem if it causes a bottleneck or excessive GC pressure. I don't think that policy modifications would be a large part of the workload. Therefore there isn't a reason to reject solutions around immutability.

In the scene of this issue, compared with ConcurrentHashMap, what are its advantages?

**Comment by lhotari** [comment]
> In the scene of this issue, compared with ConcurrentHashMap, what are its advantages?

One of the advantages of immutable objects (all fields final in Java) is that there isn't any need for locks at access time after there is a reference to the object. A design where there's some kind of "single writer principle" and immutable objects can be easier to get right. However it might be an overkill to modify an existing solution to follow this type of pattern.
I guess that the benefit of using ConcurrentHashMap (or Collections.synchronizedMap wrapper) is that the change is relatively small to the existing solution as you have already demonstrated in the PR #9850 .

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by lhotari** [comment]
Addressed for namespace policies by #9900, separate issue for topic policies in #21303
