### ISSUE TITLE
Pulsar-Perf: Producer - java.lang.OutOfMemoryError: Direct buffer memory with very simple workload

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#9721]
**Describe the bug**

```
14:34:25.058 [pulsar-client-io-10-1] INFO  org.apache.pulsar.common.allocator.PulsarByteBufAllocator - Exiting JVM process for OOM error: Direct buffer memory
java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:175) ~[?:?]
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:118) ~[?:?]
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:317) ~[?:?]
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:758) ~[io.netty-netty-buffer-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:734) ~[io.netty-netty-buffer-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:245) ~[io.netty-netty-buffer-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:227) ~[io.netty-netty-buffer-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:147) ~[io.netty-netty-buffer-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:356) ~[io.netty-netty-buffer-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187) ~[io.netty-netty-buffer-4.1.48.Final.jar:4.1.48.Final]
	at org.apache.bookkeeper.common.allocator.impl.ByteBufAllocatorImpl.newDirectBuffer(ByteBufAllocatorImpl.java:164) [org.apache.bookkeeper-bookkeeper-common-allocator-4.11.1.jar:4.11.1]
	at org.apache.bookkeeper.common.allocator.impl.ByteBufAllocatorImpl.newDirectBuffer(ByteBufAllocatorImpl.java:158) [org.apache.bookkeeper-bookkeeper-common-allocator-4.11.1.jar:4.11.1]
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187) [io.netty-netty-buffer-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178) [io.netty-netty-buffer-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.unix.PreferredDirectByteBufAllocator.ioBuffer(PreferredDirectByteBufAllocator.java:53) [io.netty-netty-transport-native-unix-common-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.epoll.EpollRecvByteAllocatorHandle.allocate(EpollRecvByteAllocatorHandle.java:75) [io.netty-netty-transport-native-epoll-4.1.48.Final-linux-x86_64.jar:4.1.48.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:777) [io.netty-netty-transport-native-epoll-4.1.48.Final-linux-x86_64.jar:4.1.48.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) [io.netty-netty-transport-native-epoll-4.1.48.Final-linux-x86_64.jar:4.1.48.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [io.netty-netty-transport-native-epoll-4.1.48.Final-linux-x86_64.jar:4.1.48.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty-netty-common-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty-netty-common-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.48.Final.jar:4.1.48.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**To Reproduce**
I am running pulsar-perf produce (on Pulsar 2.6.2, actually Luna Streaming 2.6.2_1.0.0) with very simple configuration, after 3 minutes it breaks.

```
[/pulsar/conf/client.conf] Applying config brokerServiceUrl = pulsar://pulsar-proxy:6650/
[/pulsar/conf/client.conf] Applying config webServiceUrl = http://pulsar-proxy:8080/
Warning: Nashorn engine is planned to be removed from a future JDK release
14:31:51.660 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - Starting Pulsar perf producer with config: {
  "confFile" : "/pulsar/conf/client.conf",
  "topics" : [ "persistent://public/default/test" ],
  "numTestThreads" : 10,
  "msgRate" : 10000,
  "msgSize" : 1024,
  "numTopics" : 10,
  "numProducers" : 1,
  "serviceURL" : "http://pulsar-proxy:8080",
  "authPluginClassName" : "",
  "authParams" : "",
  "maxOutstanding" : 1000,
  "maxPendingMessagesAcrossPartitions" : 50000,
  "maxConnections" : 100,
  "numMessages" : 0,
  "statsIntervalSeconds" : 2,
  "compression" : "NONE",
  "payloadFilename" : null,
  "payloadDelimiter" : "\\n",
  "batchTimeMillis" : 1.0,
  "batchMaxMessages" : 1000,
  "batchMaxBytes" : 4194304,
  "testTime" : 3600,
  "warmupTimeSeconds" : 1.0,
  "tlsTrustCertsFilePath" : "",
  "tlsAllowInsecureConnection" : false,
  "encKeyName" : null,
  "encKeyFile" : null,
  "delay" : 0,
  "exitOnFailure" : true,
  "messageKeyGenerationMode" : null,
  "ioThreads" : 1
}
```

Relevant logs on broker
```
14:34:25.236 [pulsar-io-23-5] WARN  org.apache.pulsar.broker.service.ServerCnx - [/10.244.1.16:49994] Got exception io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
14:34:25.236 [pulsar-io-23-6] WARN  org.apache.pulsar.broker.service.ServerCnx - [/10.244.1.16:49964] Got exception io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
14:34:25.236 [pulsar-io-23-7] WARN  org.apache.pulsar.broker.service.ServerCnx - [/10.244.1.16:49966] Got exception io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
14:34:25.236 [pulsar-io-23-1] WARN  org.apache.pulsar.broker.service.ServerCnx - [/10.244.1.16:49976] Got exception io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
14:34:25.236 [pulsar-io-23-8] WARN  org.apache.pulsar.broker.service.ServerCnx - [/10.244.1.16:49972] Got exception io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
14:34:25.237 [pulsar-io-23-3] WARN  org.apache.pulsar.broker.service.ServerCnx - [/10.244.1.16:50050] Got exception io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
14:34:25.237 [pulsar-io-23-4] WARN  org.apache.pulsar.broker.service.ServerCnx - [/10.244.1.16:49956] Got exception io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
14:34:25.237 [pulsar-io-23-2] WARN  org.apache.pulsar.broker.service.ServerCnx - [/10.244.1.16:50044] Got exception io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer


```**Expected behavior**
No OOM error

It may sound like some memory leak in pulsar-perf

**Comment by eolivelli** [comment]
I am trying with more memory to the tool, but in general I do not expect Pulsar-Perf to retain much memory

**Comment by eolivelli** [comment]
I am no more able to reproduce the failure.
I have tested again with JDK8/11, 2.8.0-SNAPSHOT and the same version (2.6.2x) in which I saw the failure.

It looks like it is working pretty well, even in case of failures in the Broker.
I am closing the issue, now. I will reopen in case it happens again.

**Comment by eolivelli** [comment]
I managed to reproduce with apachepulsar/pulsar-all 2.7.0 docker image  (on JDK8)


```
12:50:32.165 [pulsar-client-io-2-1] INFO  org.apache.pulsar.common.allocator.PulsarByteBufAllocator - Exiting JVM process for OOM error: failed to allocate 16777216 byte(s) of direct memory (used: 1879048199, max: 1895497728)
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 1879048199, max: 1895497728)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:754) ~[io.netty-netty-common-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:709) ~[io.netty-netty-common-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:755) ~[io.netty-netty-buffer-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:731) ~[io.netty-netty-buffer-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:247) ~[io.netty-netty-buffer-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:227) ~[io.netty-netty-buffer-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:147) ~[io.netty-netty-buffer-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:356) ~[io.netty-netty-buffer-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187) ~[io.netty-netty-buffer-4.1.51.Final.jar:4.1.51.Final]
	at org.apache.bookkeeper.common.allocator.impl.ByteBufAllocatorImpl.newDirectBuffer(ByteBufAllocatorImpl.java:164) [org.apache.bookkeeper-bookkeeper-common-allocator-4.12.0.jar:4.12.0]
	at org.apache.bookkeeper.common.allocator.impl.ByteBufAllocatorImpl.newDirectBuffer(ByteBufAllocatorImpl.java:158) [org.apache.bookkeeper-bookkeeper-common-allocator-4.12.0.jar:4.12.0]
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187) [io.netty-netty-buffer-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178) [io.netty-netty-buffer-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.epoll.AbstractEpollChannel.newDirectBuffer0(AbstractEpollChannel.java:328) [io.netty-netty-transport-native-epoll-4.1.51.Final-linux-x86_64.jar:4.1.51.Final]
	at io.netty.channel.epoll.AbstractEpollChannel.newDirectBuffer(AbstractEpollChannel.java:314) [io.netty-netty-transport-native-epoll-4.1.51.Final-linux-x86_64.jar:4.1.51.Final]
	at io.netty.channel.epoll.AbstractEpollChannel.newDirectBuffer(AbstractEpollChannel.java:297) [io.netty-netty-transport-native-epoll-4.1.51.Final-linux-x86_64.jar:4.1.51.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel.filterOutboundMessage(AbstractEpollStreamChannel.java:521) [io.netty-netty-transport-native-epoll-4.1.51.Final-linux-x86_64.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:873) [io.netty-netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367) [io.netty-netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) [io.netty-netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) [io.netty-netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) [io.netty-netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) [io.netty-netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at org.apache.pulsar.common.protocol.ByteBufPair$Encoder.write(ByteBufPair.java:127) [org.apache.pulsar-pulsar-common-2.7.0.jar:2.7.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) [io.netty-netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) [io.netty-netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) [io.netty-netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) [io.netty-netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at org.apache.pulsar.client.impl.ProducerImpl$WriteInEventLoopCallback.run(ProducerImpl.java:764) [org.apache.pulsar-pulsar-client-original-2.7.0.jar:2.7.0]
```

**Comment by eolivelli** [comment]
The command is
`bin/pulsar-perf produce -m 0 -z NONE -time 1800 --exit-on-failure -i 20 -t 1 -r 10000 -threads 10 -u http://pulsar-proxy:8080`

with the default configuration that comes with the docker image

Actually I am applying this k8s manifest
```
              apiVersion: batch/v1
              kind: Job
              metadata:
                name: runproducer
              spec:
                template:
                  spec:
                    containers:
                      - name: pulsarproducerrunner
                        image: apachepulsar/pulsar-all:2.7.0
                        command: ["/bin/sh", "-c", "env && /pulsar/bin/apply-config-from-env.py /pulsar/conf/client.conf && bin/pulsar-perf produce -m 0 -z NONE -time 3600 --exit-on-failure -i 20 -t {{pulsarperf.numtopics}} -r 10000 -threads 10  -u http://pulsar-proxy:8080 persistent://public/default/test"]
                        env:
                          - name: webServiceUrl
                            value: http://pulsar-proxy:8080/
                          - name: brokerServiceUrl
                            value: pulsar://pulsar-proxy:6650/
                    restartPolicy: Never
                backoffLimit: 0
```

**Comment by eolivelli** [comment]
I have send this patch with some tool that I am using to debug this issue
https://github.com/apache/pulsar/pull/9769

**Comment by eolivelli** [comment]
With that patch this is the configuration I see 
```
16:27:21.668 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - Java Runtime Info
16:27:21.673 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - java.vendor.url.bug = http://bugreport.sun.com/bugreport/
16:27:21.673 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - java.vendor = Oracle Corporation
16:27:21.673 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - java.ext.dirs = /usr/local/openjdk-8/jre/lib/ext:/usr/java/packages/lib/ext
16:27:21.673 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - java.version = 1.8.0_282
16:27:21.673 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - java.vm.info = mixed mode
16:27:21.673 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - java.specification.vendor = Oracle Corporation
16:27:21.673 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - java.home = /usr/local/openjdk-8/jre
16:27:21.673 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - java.vm.specification.version = 1.8
16:27:21.673 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - java.specification.version = 1.8
16:27:21.673 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - java.awt.printerjob = sun.print.PSPrinterJob
16:27:21.674 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - os.version = 4.4.0-194-generic
16:27:21.674 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - java.net.preferIPv4Stack = true
16:27:21.674 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - java.specification.name = Java Platform API Specification
16:27:21.674 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - java.class.version = 52.0
16:27:21.674 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - java.library.path = /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
16:27:21.674 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - os.name = Linux
16:27:21.674 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - java.vm.specification.vendor = Oracle Corporation
16:27:21.674 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - java.io.tmpdir = /tmp
16:27:21.674 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - java.endorsed.dirs = /usr/local/openjdk-8/jre/lib/endorsed
16:27:21.674 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - os.arch = amd64
16:27:21.674 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - java.awt.graphicsenv = sun.awt.X11GraphicsEnvironment
16:27:21.674 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - java.runtime.version = 1.8.0_282-b08
16:27:21.674 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - java.vm.specification.name = Java Virtual Machine Specification
16:27:21.674 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - java.vm.name = OpenJDK 64-Bit Server VM
16:27:21.674 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - java.vm.vendor = Oracle Corporation
16:27:21.674 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - java.vendor.url = http://java.oracle.com/
16:27:21.674 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - java.vm.version = 25.282-b08
16:27:21.674 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - java.runtime.name = OpenJDK Runtime Environment
16:27:21.675 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - JVM args [-Dlog4j.configurationFile=log4j2.yaml, -Djava.net.preferIPv4Stack=true, -Dpulsar.allocator.exit_on_oom=true, -Dio.netty.recycler.maxCapacity.default=1000, -Dio.netty.recycler.linkCapacity=1024, -Dpulsar.log.appender=Console, -Dpulsar.log.dir=/pulsar/logs, -Dpulsar.log.file=pulsar-perftest.log]
16:27:21.697 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - Netty max memory (PlatformDependent.maxDirectMemory()) 1895497728
16:27:21.697 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - JVM max heap memory (Runtime.getRuntime().maxMemory()) 1895497728
16:27:21.738 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - Starting Pulsar perf producer with config: {
  "confFile" : "/pulsar/conf/client.conf",
  "topics" : [ "persistent://public/default/test" ],
  "numTestThreads" : 10,
  "msgRate" : 10000,
  "msgSize" : 1024,
  "numTopics" : 1,
  "numProducers" : 1,
  "serviceURL" : "http://pulsar-proxy:8080",
  "authPluginClassName" : "",
  "authParams" : "",
  "maxOutstanding" : 1000,
  "maxPendingMessagesAcrossPartitions" : 50000,
  "maxConnections" : 100,
  "numMessages" : 0,
  "statsIntervalSeconds" : 20,
  "compression" : "NONE",
  "payloadFilename" : null,
  "payloadDelimiter" : "\\n",
  "batchTimeMillis" : 1.0,
  "batchMaxMessages" : 1000,
  "batchMaxBytes" : 4194304,
  "testTime" : 1800,
  "warmupTimeSeconds" : 1.0,
  "tlsTrustCertsFilePath" : "",
  "tlsAllowInsecureConnection" : false,
  "encKeyName" : null,
  "encKeyFile" : null,
  "delay" : 0,
  "exitOnFailure" : true,
  "messageKeyGenerationMode" : null,
  "ioThreads" : 1,
  "producerAccessMode" : "Shared"
}
```

**Comment by eolivelli** [comment]
My suspect was about how Netty pools memory (as it uses pools bounds to the thread the allocates the memory), but
with -Dpulsar.allocator.pooled=false (that implies to use the heap and not Netty Pooled Direct Memory) I get the same error.
I will dig into the memory dump and check what's going on.
 
```
7:29:06.503 [pulsar-perf-producer-exec-1-2] WARN  org.apache.pulsar.testclient.PerformanceProducer - Write error on message
java.util.concurrent.CompletionException: org.apache.pulsar.client.api.PulsarClientException: java.lang.OutOfMemoryError: Java heap space
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_282]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_282]
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:714) ~[?:1.8.0_282]
	at java.util.concurrent.CompletableFuture.uniRunStage(CompletableFuture.java:731) ~[?:1.8.0_282]
	at java.util.concurrent.CompletableFuture.thenRun(CompletableFuture.java:2023) ~[?:1.8.0_282]
	at org.apache.pulsar.testclient.PerformanceProducer.runProducer(PerformanceProducer.java:540) ~[org.apache.pulsar-pulsar-testclient-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	at org.apache.pulsar.testclient.PerformanceProducer.lambda$main$1(PerformanceProducer.java:330) ~[org.apache.pulsar-pulsar-testclient-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_282]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.51.Final.jar:4.1.51.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: org.apache.pulsar.client.api.PulsarClientException: java.lang.OutOfMemoryError: Java heap space
	at org.apache.pulsar.client.impl.ProducerImpl.sendAsync(ProducerImpl.java:466) ~[org.apache.pulsar-pulsar-client-original-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	at org.apache.pulsar.client.impl.ProducerImpl.internalSendAsync(ProducerImpl.java:290) ~[org.apache.pulsar-pulsar-client-original-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	at org.apache.pulsar.client.impl.ProducerImpl.internalSendWithTxnAsync(ProducerImpl.java:361) ~[org.apache.pulsar-pulsar-client-original-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	at org.apache.pulsar.client.impl.PartitionedProducerImpl.internalSendWithTxnAsync(PartitionedProducerImpl.java:191) ~[org.apache.pulsar-pulsar-client-original-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	at org.apache.pulsar.client.impl.PartitionedProducerImpl.internalSendAsync(PartitionedProducerImpl.java:167) ~[org.apache.pulsar-pulsar-client-original-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.sendAsync(TypedMessageBuilderImpl.java:103) ~[org.apache.pulsar-pulsar-client-original-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	... 8 more
Caused by: java.lang.OutOfMemoryError: Java heap space
	at io.netty.util.internal.PlatformDependent.allocateUninitializedArray(PlatformDependent.java:281) ~[io.netty-netty-common-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.buffer.UnpooledUnsafeHeapByteBuf.allocateArray(UnpooledUnsafeHeapByteBuf.java:39) ~[io.netty-netty-buffer-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf.allocateArray(UnpooledByteBufAllocator.java:144) ~[io.netty-netty-buffer-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.buffer.UnpooledHeapByteBuf.<init>(UnpooledHeapByteBuf.java:59) ~[io.netty-netty-buffer-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.buffer.UnpooledUnsafeHeapByteBuf.<init>(UnpooledUnsafeHeapByteBuf.java:34) ~[io.netty-netty-buffer-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf.<init>(UnpooledByteBufAllocator.java:139) ~[io.netty-netty-buffer-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.buffer.UnpooledByteBufAllocator.newHeapBuffer(UnpooledByteBufAllocator.java:82) ~[io.netty-netty-buffer-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:168) ~[io.netty-netty-buffer-4.1.51.Final.jar:4.1.51.Final]
	at org.apache.bookkeeper.common.allocator.impl.ByteBufAllocatorImpl.newHeapBuffer(ByteBufAllocatorImpl.java:148) ~[org.apache.bookkeeper-bookkeeper-common-allocator-4.12.1.jar:4.12.1]
	at org.apache.bookkeeper.common.allocator.impl.ByteBufAllocatorImpl.buffer(ByteBufAllocatorImpl.java:137) ~[org.apache.bookkeeper-bookkeeper-common-allocator-4.12.1.jar:4.12.1]
	at org.apache.bookkeeper.common.allocator.impl.ByteBufAllocatorImpl.buffer(ByteBufAllocatorImpl.java:129) ~[org.apache.bookkeeper-bookkeeper-common-allocator-4.12.1.jar:4.12.1]
	at org.apache.pulsar.client.impl.BatchMessageContainerImpl.add(BatchMessageContainerImpl.java:75) ~[org.apache.pulsar-pulsar-client-original-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	at org.apache.pulsar.client.impl.ProducerImpl.serializeAndSendMessage(ProducerImpl.java:526) ~[org.apache.pulsar-pulsar-client-original-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	at org.apache.pulsar.client.impl.ProducerImpl.sendAsync(ProducerImpl.java:456) ~[org.apache.pulsar-pulsar-client-original-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	at org.apache.pulsar.client.impl.ProducerImpl.internalSendAsync(ProducerImpl.java:290) ~[org.apache.pulsar-pulsar-client-original-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	at org.apache.pulsar.client.impl.ProducerImpl.internalSendWithTxnAsync(ProducerImpl.java:361) ~[org.apache.pulsar-pulsar-client-original-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	at org.apache.pulsar.client.impl.PartitionedProducerImpl.internalSendWithTxnAsync(PartitionedProducerImpl.java:191) ~[org.apache.pulsar-pulsar-client-original-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	at org.apache.pulsar.client.impl.PartitionedProducerImpl.internalSendAsync(PartitionedProducerImpl.java:167) ~[org.apache.pulsar-pulsar-client-original-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.sendAsync(TypedMessageBuilderImpl.java:103) ~[org.apache.pulsar-pulsar-client-original-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	at org.apache.pulsar.testclient.PerformanceProducer.runProducer(PerformanceProducer.java:540) [org.apache.pulsar-pulsar-testclient-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	at org.apache.pulsar.testclient.PerformanceProducer.lambda$main$1(PerformanceProducer.java:330) [org.apache.pulsar-pulsar-testclient-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	at org.apache.pulsar.testclient.PerformanceProducer$$Lambda$22/1766911337.run(Unknown Source) [org.apache.pulsar-pulsar-testclient-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
	... 6 more
```

**Comment by eolivelli** [comment]
The trigger for the problem is the number for "threads", that for pulsar-perf produce is basically a number of producers.

in this case we have threads = 10, and basically you are running 10 PulsarClient/Producer concurrently.

The only "fix" or mitigation for this issue would be to add a global (static) memory limit like in PIP-74
https://github.com/apache/pulsar/wiki/PIP-74%3A-Pulsar-client-memory-limits

and also to share a single PulsarClient among the 'threads'

cc @merlimat 

I am not sure I can close this issue now or we can close it after PIP-74

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.
