### ISSUE TITLE
Pulsar C++ Client Library not working on Alpine Linux

### ISSUE THREAD

**Issue by kelvinlong** [apache/pulsar#9731]
**Describe the bug**
Pulsar C++ Client Library not working on Alpine Linux, not able to run example scripts using pulsar-client(npm/yarn) in docker container built based on alpine linux image.

hostname # node node_modules/pulsar-client/examples/consumer
/mars/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/lib/libpulsar.so.2.7.0)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (/mars/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/mars/node_modules/pulsar-client/index.js:20:42)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)

**Desktop (please complete the following information):**
 - OS:
 cat /etc/issue 
Welcome to Alpine Linux 3.11
Kernel \r on an \m (\l)

ldd
musl libc (x86_64)
Version 1.1.24
Dynamic Program Loader
Usage: /lib/ld-musl-x86_64.so.1 [options] [--] pathname

**Comment by kelvinlong** [comment]
@sijie any progress?

**Comment by ludusrusso** [comment]
I've also having this issue! Trying to add the missing library using `apk add gcompat` but then when I import pulsar-client node crashes in segmentation fault:

```
Welcome to Node.js v14.15.1.
Type ".help" for more information.
> const pulsar = require('pulsar-client');
Segmentation fault
```

any help?

**Comment by FengYujia** [comment]
> I've also having this issue! Trying to add the missing library using `apk add gcompat` but then when I import pulsar-client node crashes in segmentation fault:
> 
> ```
> Welcome to Node.js v14.15.1.
> Type ".help" for more information.
> > const pulsar = require('pulsar-client');
> Segmentation fault
> ```
> 
> any help?

same problem to me... any answer yet?

**Comment by merlimat** [comment]
While it's not shipped as part of the official releases (though it would be a good idea to do so), we do have scripts to generate Alpine APK packages and also Python wheel files suitable for Alpine. 

You can generate the package with: 
 * First create the Alpine build image: `./pulsar-client-cpp/docker/alpine/build-alpine-image.sh` 
 * Build the APK: `./pulsar-client-cpp/pkg/apk/docker-build-apk.sh`

**Comment by RobertLowe** [comment]
`docker/alpine/Dockerfile` fails to build

```
 > [10/11] RUN pip3 install wheel twine:
#13 0.904 Collecting wheel
#13 0.930   Downloading wheel-0.36.2-py2.py3-none-any.whl (35 kB)
#13 0.995 Collecting twine
#13 1.001   Downloading twine-3.4.2-py3-none-any.whl (34 kB)
#13 1.053 Collecting rfc3986>=1.4.0
#13 1.059   Downloading rfc3986-1.5.0-py2.py3-none-any.whl (31 kB)
#13 1.102 Collecting readme-renderer>=21.0
#13 1.107   Downloading readme_renderer-29.0-py2.py3-none-any.whl (15 kB)
#13 1.233 Collecting keyring>=15.1
#13 1.243   Downloading keyring-23.0.1-py3-none-any.whl (33 kB)
#13 1.272 Collecting requests-toolbelt!=0.9.0,>=0.8.0
#13 1.278   Downloading requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
#13 1.315 Collecting colorama>=0.4.3
#13 1.318   Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
#13 1.459 Collecting tqdm>=4.14
#13 1.463   Downloading tqdm-4.62.0-py2.py3-none-any.whl (76 kB)
#13 1.541 Collecting requests>=2.20
#13 1.549   Downloading requests-2.26.0-py2.py3-none-any.whl (62 kB)
#13 1.647 Collecting importlib-metadata>=3.6
#13 1.652   Downloading importlib_metadata-4.6.3-py3-none-any.whl (17 kB)
#13 1.683 Collecting pkginfo>=1.4.2
#13 1.687   Downloading pkginfo-1.7.1-py2.py3-none-any.whl (25 kB)
#13 1.764 Collecting zipp>=0.5
#13 1.769   Downloading zipp-3.5.0-py3-none-any.whl (5.7 kB)
#13 1.814 Collecting SecretStorage>=3.2
#13 1.818   Downloading SecretStorage-3.3.1-py3-none-any.whl (15 kB)
#13 1.847 Collecting jeepney>=0.4.2
#13 1.852   Downloading jeepney-0.7.1-py3-none-any.whl (54 kB)
#13 1.934 Collecting Pygments>=2.5.1
#13 1.938   Downloading Pygments-2.9.0-py3-none-any.whl (1.0 MB)
#13 1.988 Collecting docutils>=0.13.1
#13 1.996   Downloading docutils-0.17.1-py2.py3-none-any.whl (575 kB)
#13 2.048 Collecting six
#13 2.061   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
#13 2.110 Collecting bleach>=2.1.0
#13 2.115   Downloading bleach-4.0.0-py2.py3-none-any.whl (146 kB)
#13 2.145 Collecting webencodings
#13 2.149   Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
#13 2.201 Collecting packaging
#13 2.205   Downloading packaging-21.0-py3-none-any.whl (40 kB)
#13 2.263 Collecting idna<4,>=2.5
#13 2.268   Downloading idna-3.2-py3-none-any.whl (59 kB)
#13 2.306 Collecting certifi>=2017.4.17
#13 2.313   Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
#13 2.353 Collecting charset-normalizer~=2.0.0
#13 2.358   Downloading charset_normalizer-2.0.4-py3-none-any.whl (36 kB)
#13 2.433 Collecting urllib3<1.27,>=1.21.1
#13 2.439   Downloading urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
#13 2.966 Collecting cryptography>=2.0
#13 2.975   Downloading cryptography-3.4.7.tar.gz (546 kB)
#13 3.307   Installing build dependencies: started
#13 10.06   Installing build dependencies: finished with status 'done'
#13 10.06   Getting requirements to build wheel: started
#13 10.26   Getting requirements to build wheel: finished with status 'done'
#13 10.27     Preparing wheel metadata: started
#13 11.17     Preparing wheel metadata: finished with status 'done'
#13 11.51 Collecting cffi>=1.12
#13 11.52   Using cached cffi-1.14.6.tar.gz (475 kB)
#13 11.98 Collecting pycparser
#13 11.99   Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
#13 12.16 Collecting pyparsing>=2.0.2
#13 12.16   Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
#13 12.20 Using legacy 'setup.py install' for cffi, since package 'wheel' is not installed.
#13 12.20 Building wheels for collected packages: cryptography
#13 12.20   Building wheel for cryptography (PEP 517): started
#13 13.34   Building wheel for cryptography (PEP 517): finished with status 'error'
#13 13.34   ERROR: Command errored out with exit status 1:
#13 13.34    command: /usr/bin/python3.8 /usr/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpxonaga2k
#13 13.34        cwd: /tmp/pip-install-cbpjcyt2/cryptography_10e239a3cdb144c1bda84a7c76feba84
#13 13.34   Complete output (165 lines):
#13 13.34   running bdist_wheel
#13 13.34   running build
#13 13.34   running build_py
#13 13.34   creating build
#13 13.34   creating build/lib.linux-x86_64-3.8
#13 13.34   creating build/lib.linux-x86_64-3.8/cryptography
#13 13.34   copying src/cryptography/__about__.py -> build/lib.linux-x86_64-3.8/cryptography
#13 13.34   copying src/cryptography/__init__.py -> build/lib.linux-x86_64-3.8/cryptography
#13 13.34   copying src/cryptography/fernet.py -> build/lib.linux-x86_64-3.8/cryptography
#13 13.34   copying src/cryptography/exceptions.py -> build/lib.linux-x86_64-3.8/cryptography
#13 13.34   copying src/cryptography/utils.py -> build/lib.linux-x86_64-3.8/cryptography
#13 13.34   creating build/lib.linux-x86_64-3.8/cryptography/hazmat
#13 13.34   copying src/cryptography/hazmat/_types.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat
#13 13.34   copying src/cryptography/hazmat/__init__.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat
#13 13.34   copying src/cryptography/hazmat/_der.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat
#13 13.34   copying src/cryptography/hazmat/_oid.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat
#13 13.34   creating build/lib.linux-x86_64-3.8/cryptography/x509
#13 13.34   copying src/cryptography/x509/base.py -> build/lib.linux-x86_64-3.8/cryptography/x509
#13 13.34   copying src/cryptography/x509/oid.py -> build/lib.linux-x86_64-3.8/cryptography/x509
#13 13.34   copying src/cryptography/x509/__init__.py -> build/lib.linux-x86_64-3.8/cryptography/x509
#13 13.34   copying src/cryptography/x509/ocsp.py -> build/lib.linux-x86_64-3.8/cryptography/x509
#13 13.34   copying src/cryptography/x509/general_name.py -> build/lib.linux-x86_64-3.8/cryptography/x509
#13 13.34   copying src/cryptography/x509/certificate_transparency.py -> build/lib.linux-x86_64-3.8/cryptography/x509
#13 13.34   copying src/cryptography/x509/extensions.py -> build/lib.linux-x86_64-3.8/cryptography/x509
#13 13.34   copying src/cryptography/x509/name.py -> build/lib.linux-x86_64-3.8/cryptography/x509
#13 13.34   creating build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives
#13 13.34   copying src/cryptography/hazmat/primitives/hashes.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives
#13 13.34   copying src/cryptography/hazmat/primitives/_serialization.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives
#13 13.34   copying src/cryptography/hazmat/primitives/constant_time.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives
#13 13.34   copying src/cryptography/hazmat/primitives/__init__.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives
#13 13.34   copying src/cryptography/hazmat/primitives/_cipheralgorithm.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives
#13 13.34   copying src/cryptography/hazmat/primitives/_asymmetric.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives
#13 13.34   copying src/cryptography/hazmat/primitives/cmac.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives
#13 13.34   copying src/cryptography/hazmat/primitives/hmac.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives
#13 13.34   copying src/cryptography/hazmat/primitives/padding.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives
#13 13.34   copying src/cryptography/hazmat/primitives/poly1305.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives
#13 13.34   copying src/cryptography/hazmat/primitives/keywrap.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives
#13 13.34   creating build/lib.linux-x86_64-3.8/cryptography/hazmat/bindings
#13 13.34   copying src/cryptography/hazmat/bindings/__init__.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/bindings
#13 13.34   creating build/lib.linux-x86_64-3.8/cryptography/hazmat/backends
#13 13.34   copying src/cryptography/hazmat/backends/__init__.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/backends
#13 13.34   copying src/cryptography/hazmat/backends/interfaces.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/backends
#13 13.34   creating build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/serialization
#13 13.34   copying src/cryptography/hazmat/primitives/serialization/base.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/serialization
#13 13.34   copying src/cryptography/hazmat/primitives/serialization/__init__.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/serialization
#13 13.34   copying src/cryptography/hazmat/primitives/serialization/pkcs7.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/serialization
#13 13.34   copying src/cryptography/hazmat/primitives/serialization/pkcs12.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/serialization
#13 13.34   copying src/cryptography/hazmat/primitives/serialization/ssh.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/serialization
#13 13.34   creating build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/ciphers
#13 13.34   copying src/cryptography/hazmat/primitives/ciphers/aead.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/ciphers
#13 13.34   copying src/cryptography/hazmat/primitives/ciphers/base.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/ciphers
#13 13.34   copying src/cryptography/hazmat/primitives/ciphers/modes.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/ciphers
#13 13.34   copying src/cryptography/hazmat/primitives/ciphers/__init__.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/ciphers
#13 13.34   copying src/cryptography/hazmat/primitives/ciphers/algorithms.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/ciphers
#13 13.34   creating build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/asymmetric
#13 13.34   copying src/cryptography/hazmat/primitives/asymmetric/dh.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/asymmetric
#13 13.34   copying src/cryptography/hazmat/primitives/asymmetric/ed448.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/asymmetric
#13 13.34   copying src/cryptography/hazmat/primitives/asymmetric/ec.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/asymmetric
#13 13.34   copying src/cryptography/hazmat/primitives/asymmetric/__init__.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/asymmetric
#13 13.34   copying src/cryptography/hazmat/primitives/asymmetric/ed25519.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/asymmetric
#13 13.34   copying src/cryptography/hazmat/primitives/asymmetric/dsa.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/asymmetric
#13 13.34   copying src/cryptography/hazmat/primitives/asymmetric/padding.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/asymmetric
#13 13.34   copying src/cryptography/hazmat/primitives/asymmetric/x448.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/asymmetric
#13 13.34   copying src/cryptography/hazmat/primitives/asymmetric/rsa.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/asymmetric
#13 13.34   copying src/cryptography/hazmat/primitives/asymmetric/x25519.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/asymmetric
#13 13.34   copying src/cryptography/hazmat/primitives/asymmetric/utils.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/asymmetric
#13 13.34   creating build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/kdf
#13 13.34   copying src/cryptography/hazmat/primitives/kdf/concatkdf.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/kdf
#13 13.34   copying src/cryptography/hazmat/primitives/kdf/pbkdf2.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/kdf
#13 13.34   copying src/cryptography/hazmat/primitives/kdf/__init__.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/kdf
#13 13.34   copying src/cryptography/hazmat/primitives/kdf/x963kdf.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/kdf
#13 13.34   copying src/cryptography/hazmat/primitives/kdf/hkdf.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/kdf
#13 13.34   copying src/cryptography/hazmat/primitives/kdf/scrypt.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/kdf
#13 13.34   copying src/cryptography/hazmat/primitives/kdf/kbkdf.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/kdf
#13 13.34   creating build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/twofactor
#13 13.34   copying src/cryptography/hazmat/primitives/twofactor/__init__.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/twofactor
#13 13.34   copying src/cryptography/hazmat/primitives/twofactor/totp.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/twofactor
#13 13.34   copying src/cryptography/hazmat/primitives/twofactor/hotp.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/twofactor
#13 13.34   copying src/cryptography/hazmat/primitives/twofactor/utils.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/primitives/twofactor
#13 13.34   creating build/lib.linux-x86_64-3.8/cryptography/hazmat/bindings/openssl
#13 13.34   copying src/cryptography/hazmat/bindings/openssl/__init__.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/bindings/openssl
#13 13.34   copying src/cryptography/hazmat/bindings/openssl/binding.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/bindings/openssl
#13 13.34   copying src/cryptography/hazmat/bindings/openssl/_conditional.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/bindings/openssl
#13 13.34   creating build/lib.linux-x86_64-3.8/cryptography/hazmat/backends/openssl
#13 13.34   copying src/cryptography/hazmat/backends/openssl/aead.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/backends/openssl
#13 13.34   copying src/cryptography/hazmat/backends/openssl/dh.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/backends/openssl
#13 13.34   copying src/cryptography/hazmat/backends/openssl/hashes.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/backends/openssl
#13 13.34   copying src/cryptography/hazmat/backends/openssl/x509.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/backends/openssl
#13 13.34   copying src/cryptography/hazmat/backends/openssl/decode_asn1.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/backends/openssl
#13 13.34   copying src/cryptography/hazmat/backends/openssl/ed448.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/backends/openssl
#13 13.34   copying src/cryptography/hazmat/backends/openssl/ec.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/backends/openssl
#13 13.34   copying src/cryptography/hazmat/backends/openssl/__init__.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/backends/openssl
#13 13.34   copying src/cryptography/hazmat/backends/openssl/ocsp.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/backends/openssl
#13 13.34   copying src/cryptography/hazmat/backends/openssl/ed25519.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/backends/openssl
#13 13.34   copying src/cryptography/hazmat/backends/openssl/cmac.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/backends/openssl
#13 13.34   copying src/cryptography/hazmat/backends/openssl/dsa.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/backends/openssl
#13 13.34   copying src/cryptography/hazmat/backends/openssl/hmac.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/backends/openssl
#13 13.34   copying src/cryptography/hazmat/backends/openssl/backend.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/backends/openssl
#13 13.34   copying src/cryptography/hazmat/backends/openssl/x448.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/backends/openssl
#13 13.34   copying src/cryptography/hazmat/backends/openssl/poly1305.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/backends/openssl
#13 13.34   copying src/cryptography/hazmat/backends/openssl/encode_asn1.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/backends/openssl
#13 13.34   copying src/cryptography/hazmat/backends/openssl/ciphers.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/backends/openssl
#13 13.34   copying src/cryptography/hazmat/backends/openssl/rsa.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/backends/openssl
#13 13.34   copying src/cryptography/hazmat/backends/openssl/x25519.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/backends/openssl
#13 13.34   copying src/cryptography/hazmat/backends/openssl/utils.py -> build/lib.linux-x86_64-3.8/cryptography/hazmat/backends/openssl
#13 13.34   running egg_info
#13 13.34   writing src/cryptography.egg-info/PKG-INFO
#13 13.34   writing dependency_links to src/cryptography.egg-info/dependency_links.txt
#13 13.34   writing requirements to src/cryptography.egg-info/requires.txt
#13 13.34   writing top-level names to src/cryptography.egg-info/top_level.txt
#13 13.34   reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
#13 13.34   reading manifest template 'MANIFEST.in'
#13 13.34   no previously-included directories found matching 'docs/_build'
#13 13.34   warning: no previously-included files found matching 'vectors'
#13 13.34   warning: no previously-included files matching '*' found under directory 'vectors'
#13 13.34   warning: no previously-included files matching '*' found under directory '.github'
#13 13.34   warning: no previously-included files found matching 'release.py'
#13 13.34   warning: no previously-included files found matching '.coveragerc'
#13 13.34   warning: no previously-included files found matching 'codecov.yml'
#13 13.34   warning: no previously-included files found matching '.readthedocs.yml'
#13 13.34   warning: no previously-included files found matching 'dev-requirements.txt'
#13 13.34   warning: no previously-included files found matching 'tox.ini'
#13 13.34   warning: no previously-included files found matching 'mypy.ini'
#13 13.34   warning: no previously-included files matching '*' found under directory '.zuul.d'
#13 13.34   warning: no previously-included files matching '*' found under directory '.zuul.playbooks'
#13 13.34   adding license file 'LICENSE'
#13 13.34   adding license file 'LICENSE.APACHE'
#13 13.34   adding license file 'LICENSE.BSD'
#13 13.34   adding license file 'LICENSE.PSF'
#13 13.34   writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
#13 13.34   copying src/cryptography/py.typed -> build/lib.linux-x86_64-3.8/cryptography
#13 13.34   running build_ext
#13 13.34   generating cffi module 'build/temp.linux-x86_64-3.8/_padding.c'
#13 13.34   creating build/temp.linux-x86_64-3.8
#13 13.34   generating cffi module 'build/temp.linux-x86_64-3.8/_openssl.c'
#13 13.34   running build_rust
#13 13.34
#13 13.34       =============================DEBUG ASSISTANCE=============================
#13 13.34       If you are seeing a compilation error please try the following steps to
#13 13.34       successfully install cryptography:
#13 13.34       1) Upgrade to the latest pip and try again. This will fix errors for most
#13 13.34          users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
#13 13.34       2) Read https://cryptography.io/en/latest/installation.html for specific
#13 13.34          instructions for your platform.
#13 13.34       3) Check our frequently asked questions for more information:
#13 13.34          https://cryptography.io/en/latest/faq.html
#13 13.34       4) Ensure you have a recent Rust toolchain installed:
#13 13.34          https://cryptography.io/en/latest/installation.html#rust
#13 13.34       5) If you are experiencing issues with Rust for *this release only* you may
#13 13.34          set the environment variable `CRYPTOGRAPHY_DONT_BUILD_RUST=1`.
#13 13.34       =============================DEBUG ASSISTANCE=============================
#13 13.34
#13 13.34   error: can't find Rust compiler
#13 13.34
#13 13.34   If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
#13 13.34
#13 13.34   To update pip, run:
#13 13.34
#13 13.34       pip install --upgrade pip
#13 13.34
#13 13.34   and then retry package installation.
#13 13.34
#13 13.34   If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
#13 13.34
#13 13.34   This package requires Rust >=1.41.0.
#13 13.34   ----------------------------------------
#13 13.34   ERROR: Failed building wheel for cryptography
#13 13.34 Failed to build cryptography
#13 13.34 ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
#13 13.35 WARNING: You are using pip version 21.1.1; however, version 21.2.2 is available.
#13 13.35 You should consider upgrading via the '/usr/bin/python3.8 -m pip install --upgrade pip' command.
------
executor failed running [/bin/sh -c pip3 install wheel twine]: exit code: 1
```

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by JanVosNL** [comment]
@kelvinlong 

Apache Pulsar C++ client is available on Alpine Linux

```
# apk search pulsar-client
py3-pulsar-client-cpp-2.9.1-r0
pulsar-client-cpp-static-2.9.1-r0
pulsar-client-cpp-2.9.1-r0
pulsar-client-cpp-dev-2.9.1-r0

# apk info py3-pulsar-client-cpp
py3-pulsar-client-cpp-2.9.1-r0 description:
Python bindings for Apache Pulsar C++ client

py3-pulsar-client-cpp-2.9.1-r0 installed size:
4996 KiB

# apk info pulsar-client-cpp
pulsar-client-cpp-2.9.1-r0 description:
Apache Pulsar C++ client

pulsar-client-cpp-2.9.1-r0 installed size:
3168 KiB

# apk add py3-pulsar-client-cpp
(1/1) Installing py3-pulsar-client-cpp (2.9.1-r0)

# python3 --version
Python 3.10.3
```

**Comment by paullryan** [comment]
These are now giving stale for all pulsar packages in alpine and is breaking builds, what is your recommended path for alpine now https://pkgs.alpinelinux.org/package/edge/testing/x86/py3-pulsar-client-cpp (gives a 404 as do the urls for pulsar-client-cpp and pulsar-client-cpp-dev).

**Comment by eolivelli** [comment]
@BewareMyPower @merlimat could you help here please?

**Comment by merlimat** [comment]
@paullryan Since 3.0.0, C++ client APK packages for Alpine are provided. See: https://dist.apache.org/repos/dist/release/pulsar/pulsar-client-cpp-3.0.0/

**Comment by imaffe** [comment]
Seems there are only pulsar-client-cpp apk packages available. Do we have plans for pulsar-python-clients apk packages ?

**Comment by tisonkun** [comment]
Closed. The development of the C++ client has been permanently moved to http://github.com/apache/pulsar-client-cpp. Please open an issue there if it's still relevant.
