### ISSUE TITLE
Apache pulsar is not starting 

### ISSUE THREAD

**Issue by vishnuvardhanp4** [apache/pulsar#9830]
08:16:54.952 [main] INFO  org.apache.bookkeeper.proto.BookieNettyServer - Binding bookie-rpc endpoint to 0.0.0.0/0.0.0.0:3181
08:16:55.057 [main] INFO  org.apache.bookkeeper.meta.MetadataDrivers - BookKeeper metadata driver manager initialized
08:16:55.061 [main] INFO  org.apache.bookkeeper.meta.zk.ZKMetadataDriverBase - Initialize zookeeper metadata driver at metadata service uri zk+null://127.0.0.1:2181/ledgers : zkServers = 127.0.0.1:2181, ledgersRootPath = /ledgers.
08:16:55.064 [main] INFO  org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=127.0.0.1:2181 sessionTimeout=10000 watcher=org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase@74170687
08:16:55.065 [main] INFO  org.apache.zookeeper.ClientCnxnSocket - jute.maxbuffer value is 10485760 Bytes
08:16:55.065 [main] INFO  org.apache.zookeeper.ClientCnxn - zookeeper.request.timeout value is 0. feature enabled=
08:16:55.071 [main-SendThread(127.0.0.1:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
08:16:55.072 [main-SendThread(127.0.0.1:2181)] INFO  org.apache.zookeeper.ClientCnxn - Socket connection established, initiating session, client: /127.0.0.1:37354, server: localhost/127.0.0.1:2181
08:16:55.079 [main-SendThread(127.0.0.1:2181)] INFO  org.apache.zookeeper.ClientCnxn - Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x100002a28ef0001, negotiated timeout = 10000
08:16:55.080 [main-EventThread] INFO  org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase - ZooKeeper client is connected now.
08:16:55.099 [main] INFO  org.apache.bookkeeper.discover.ZKRegistrationManager - INSTANCEID not exists in zookeeper. Not considering it for data verification
08:16:55.208 [main] ERROR org.apache.bookkeeper.bookie.Bookie - Cookie for this bookie is not stored in metadata store. Bookie failing to come up
08:16:55.208 [main] INFO  org.apache.bookkeeper.proto.BookieNettyServer - Shutting down BookieNettyServer
08:16:55.233 [main] ERROR org.apache.pulsar.PulsarStandaloneStarter - Failed to start pulsar service.
org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /ledgers/cookies
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:118) ~[org.apache.pulsar-pulsar-zookeeper-2.7.0.jar:2.7.0]
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:54) ~[org.apache.pulsar-pulsar-zookeeper-2.7.0.jar:2.7.0]
        at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:2589) ~[org.apache.pulsar-pulsar-zookeeper-2.7.0.jar:2.7.0]
        at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:2617) ~[org.apache.pulsar-pulsar-zookeeper-2.7.0.jar:2.7.0]
        at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.runBookies(LocalBookkeeperEnsemble.java:307) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.7.0.jar:2.7.0]
        at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.startStandalone(LocalBookkeeperEnsemble.java:430) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.7.0.jar:2.7.0]
        at org.apache.pulsar.PulsarStandalone.start(PulsarStandalone.java:258) ~[org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]
        at org.apache.pulsar.PulsarStandaloneStarter.main(PulsarStandaloneStarter.java:115) [org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]
08:16:55.244 [Thread-0] ERROR org.apache.pulsar.PulsarStandaloneStarter - Shutdown failed: null
java.lang.NullPointerException: null
        at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.stop(LocalBookkeeperEnsemble.java:482) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.7.0.jar:2.7.0]
        at org.apache.pulsar.PulsarStandaloneStarter$1.run(PulsarStandaloneStarter.java:98) [org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]

**Comment by codelipenghui** [comment]
@vishnuvardhanp4 Could you please provide the reproduce steps? I tried on my laptop, the standalone can start successfully.

**Comment by vishnuvardhanp4** [comment]
1.upgraded data directory bookkeeper upgrade -u data 2.Again rolled back as
data is showing ./bin/bookkeeper upgrade --rollback
3.replaced the 2.7.0 lib directory with 2.6.0 4.And taken backup of lib and
conf
5.started apache pulsar then it showing the error

**Comment by vishnuvardhanp4** [comment]
when upgraded data directory data is missing so i rolled back is this ths
issue
locally i checked its working for me also

**Comment by codelipenghui** [comment]
I think you can try to replace the lib directory directly, before this backup your old lib directory.

**Comment by vishnuvardhanp4** [comment]
But after replacing lib  apache server is not starting showing the above
error that cookie of that bookie is not exist

**Comment by codelipenghui** [comment]
Interesting, If do not do the bookkeeper upgrade, the cookie also disappear from the zookeeper?

**Comment by vishnuvardhanp4** [comment]
No actually i upgraded data directory and again i rolled it back .After
that i replaced lib now pulsar is not starting

**Comment by eolivelli** [comment]
what is the content of "data/data/standalone/bookkeeper0/current" now ?
can you dump the contents of "VERSION" file, that is the "Cookie" ?

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.
