### ISSUE TITLE
Error while running two broker docker containers on the same physical host

### ISSUE THREAD

**Issue by abhilashmandaliya** [apache/pulsar#9837]
**Describe the bug**
I am trying to run a pulsar cluster on docker in a bare metal multi-cluster fashion. I have one zookeeper, 2 bookkeeper and 2 pulsar containers. On broker startup, one of the brokers starts normally but the other one fails with this error:

```ERROR org.apache.pulsar.broker.namespace.NamespaceService - namespace already owned by other broker : ns=pulsar/pulsar-cluster-1/192.168.29.24:8080 expected=pulsar://d913f2cc9d45:6650 actual=pulsar://185f6126f7bd:6650```

where 192.168.29.24 is the IP of my physical host and d913f2cc9d45 & 185f6126f7bd are docker containers running the broker. I am attaching the complete error message and the config file for reference. The same config file works if there is only one broker.

Error message:

```
07:40:49.346 [main] INFO  org.apache.pulsar.broker.namespace.OwnershipCache - Trying to acquire ownership of pulsar/pulsar-cluster-1/192.168.29.24:8080/0x00000000_0xffffffff
07:40:49.370 [pulsar-ordered-OrderedExecutor-6-0-EventThread] WARN  com.github.benmanes.caffeine.cache.LocalAsyncLoadingCache - Exception thrown during asynchronous load
org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:126) ~[org.apache.pulsar-pulsar-zookeeper-2.7.0.jar:2.7.0]
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:76) ~[org.apache.pulsar-pulsar-zookeeper-2.7.0.jar:2.7.0]
        at org.apache.pulsar.broker.namespace.OwnershipCache$OwnedServiceUnitCacheLoader.lambda$asyncLoad$0(OwnershipCache.java:146) [org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]
        at org.apache.bookkeeper.util.ZkUtils$1.processResult(ZkUtils.java:80) [org.apache.bookkeeper-bookkeeper-server-4.12.0.jar:4.12.0]
        at org.apache.bookkeeper.zookeeper.ZooKeeperClient$10$1.processResult(ZooKeeperClient.java:740) [org.apache.bookkeeper-bookkeeper-server-4.12.0.jar:4.12.0]
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:642) [org.apache.pulsar-pulsar-zookeeper-2.7.0.jar:2.7.0]
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:510) [org.apache.pulsar-pulsar-zookeeper-2.7.0.jar:2.7.0]
07:40:49.376 [ForkJoinPool.commonPool-worker-5] INFO  org.apache.pulsar.broker.namespace.OwnershipCache - Failed to acquire ownership of /namespace/pulsar/pulsar-cluster-1/192.168.29.24:8080/0x00000000_0xffffffff -- Already owned by broker NamespaceEphemeralData{nativeUrl=pulsar://185f6126f7bd:6650, httpUrl=http://185f6126f7bd:8080, disabled=false, advertisedListeners={internal=org.apache.pulsar.policies.data.loadbalancer.AdvertisedListener@42ed00e1}}
07:40:49.377 [main] ERROR org.apache.pulsar.broker.namespace.NamespaceService - namespace already owned by other broker : ns=pulsar/pulsar-cluster-1/192.168.29.24:8080 expected=pulsar://d913f2cc9d45:6650 actual=pulsar://185f6126f7bd:6650
java.lang.IllegalStateException: namespace already owned by other broker : ns=pulsar/pulsar-cluster-1/192.168.29.24:8080 expected=pulsar://d913f2cc9d45:6650 actual=pulsar://185f6126f7bd:6650
        at org.apache.pulsar.broker.namespace.NamespaceService.registerNamespace(NamespaceService.java:346) [org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]
        at org.apache.pulsar.broker.namespace.NamespaceService.registerBootstrapNamespaces(NamespaceService.java:291) [org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]
        at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:562) [org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]
        at org.apache.pulsar.PulsarBrokerStarter$BrokerStarter.start(PulsarBrokerStarter.java:277) [org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]
        at org.apache.pulsar.PulsarBrokerStarter.main(PulsarBrokerStarter.java:346) [org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]
07:40:49.377 [main] ERROR org.apache.pulsar.broker.PulsarService - java.lang.IllegalStateException: namespace already owned by other broker : ns=pulsar/pulsar-cluster-1/192.168.29.24:8080 expected=pulsar://d913f2cc9d45:6650 actual=pulsar://185f6126f7bd:6650
org.apache.pulsar.broker.PulsarServerException: java.lang.IllegalStateException: namespace already owned by other broker : ns=pulsar/pulsar-cluster-1/192.168.29.24:8080 expected=pulsar://d913f2cc9d45:6650 actual=pulsar://185f6126f7bd:6650
        at org.apache.pulsar.broker.namespace.NamespaceService.registerNamespace(NamespaceService.java:349) ~[org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]
        at org.apache.pulsar.broker.namespace.NamespaceService.registerBootstrapNamespaces(NamespaceService.java:291) ~[org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]
        at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:562) [org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]
        at org.apache.pulsar.PulsarBrokerStarter$BrokerStarter.start(PulsarBrokerStarter.java:277) [org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]
        at org.apache.pulsar.PulsarBrokerStarter.main(PulsarBrokerStarter.java:346) [org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]
Caused by: java.lang.IllegalStateException: namespace already owned by other broker : ns=pulsar/pulsar-cluster-1/192.168.29.24:8080 expected=pulsar://d913f2cc9d45:6650 actual=pulsar://185f6126f7bd:6650
        at org.apache.pulsar.broker.namespace.NamespaceService.registerNamespace(NamespaceService.java:346) ~[org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]
        ... 4 more
07:40:49.378 [main] ERROR org.apache.pulsar.PulsarBrokerStarter - Failed to start pulsar service.
org.apache.pulsar.broker.PulsarServerException: org.apache.pulsar.broker.PulsarServerException: java.lang.IllegalStateException: namespace already owned by other broker : ns=pulsar/pulsar-cluster-1/192.168.29.24:8080 expected=pulsar://d913f2cc9d45:6650 actual=pulsar://185f6126f7bd:6650
        at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:611) ~[org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]
        at org.apache.pulsar.PulsarBrokerStarter$BrokerStarter.start(PulsarBrokerStarter.java:277) ~[org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]
        at org.apache.pulsar.PulsarBrokerStarter.main(PulsarBrokerStarter.java:346) [org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]
Caused by: org.apache.pulsar.broker.PulsarServerException: java.lang.IllegalStateException: namespace already owned by other broker : ns=pulsar/pulsar-cluster-1/192.168.29.24:8080 expected=pulsar://d913f2cc9d45:6650 actual=pulsar://185f6126f7bd:6650
        at org.apache.pulsar.broker.namespace.NamespaceService.registerNamespace(NamespaceService.java:349) ~[org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]
        at org.apache.pulsar.broker.namespace.NamespaceService.registerBootstrapNamespaces(NamespaceService.java:291) ~[org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]
        at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:562) ~[org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]
        ... 2 more
Caused by: java.lang.IllegalStateException: namespace already owned by other broker : ns=pulsar/pulsar-cluster-1/192.168.29.24:8080 expected=pulsar://d913f2cc9d45:6650 actual=pulsar://185f6126f7bd:6650
        at org.apache.pulsar.broker.namespace.NamespaceService.registerNamespace(NamespaceService.java:346) ~[org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]
        at org.apache.pulsar.broker.namespace.NamespaceService.registerBootstrapNamespaces(NamespaceService.java:291) ~[org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]
        at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:562) ~[org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]
        ... 2 more
```

config: https://gist.github.com/abhilashmandaliya/37f35c19947833e735922681724cf8aa

**To Reproduce**
1. Launch 1 zookeeper container
2. Launch 2 bookkeeper containers
3. Launch 2 pulsar containers

**Expected behavior**
Shouldn't throw an exception.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 docker image
 - Zookeeper 3.6.1
 - Bookkeepr 4.10.0
 - Pulsar 2.7.0

**Comment by abhilashmandaliya** [comment]
as an work around for now, I am using pulsar proxy which has solved the issue,
