### ISSUE TITLE
Presto SQL throw Exception:No such ledger exists on Metadata Server when use 10.176.5.177:2181/test as zkServers;

### ISSUE THREAD

**Issue by sakurafly123** [apache/pulsar#9847]
Describe the bug

presto>select * from pulsar."public/default".test9;

2021-03-09 ERROR Query-20210309_0354421_00002_frcuq failed:org.apache.pulsar.sql.presto.PulsarSplitManager Failed to get splits
org.apache.bookkeeper.mledger.ManagedLedgerException: java.util.concurrent.CompletionException: org.apache.bookkeeper.client.BKException$BKNoSuchLedgerExistsException: No such ledger exists
Caused by: java.util.concurrent.CompletionException: org.apache.bookkeeper.client.BKException$BKNoSuchLedgerExistsException: No such ledger exists
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
at org.apache.bookkeeper.client.SyncCallbackUtils.finish(SyncCallbackUtils.java:83)
at org.apache.bookkeeper.client.SyncCallbackUtils$SyncOpenCallback.openComplete(SyncCallbackUtils.java:157)
at org.apache.bookkeeper.client.LedgerOpenOp.openComplete(LedgerOpenOp.java:232)
at org.apache.bookkeeper.client.LedgerOpenOp.lambda$initiate$0(LedgerOpenOp.java:117)
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
at org.apache.bookkeeper.meta.AbstractZkLedgerManager$3.processResult(AbstractZkLedgerManager.java:396)
at org.apache.bookkeeper.zookeeper.ZooKeeperClient$19$1.processResult(ZooKeeperClient.java:994)
at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:575)
at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:508)
Caused by: org.apache.bookkeeper.client.BKException$BKNoSuchLedgerExistsException: No such ledger exists
... 12 more
**To Reproduce**
**broker.conf
zookeeperServers=10.176.5.177:2181/test
bindAddresss=10.176.5.177
advertiseAddresss=10.176.5.177
managedLedgerDefaultEnsumbleSize=1
managedLedgerDefaultWriteQuorum=1
managedLedgerDefaultAackQuorum=1
clusterName=test**

**bookkeeper.conf
zkServers=10.176.177:2181/test
advertiseAddresss=10.176.5.177
journalSyncData=false**

**conf/presoto/catalog/pulsar.properties
pulsar.zookeeper-uri=10.176.5.177:2181/test**

**zookeeper,bookie And broker are deployed on the same mechine;**

1. run local zookeeepr (i download apache-zookeeper-3.5.8-bin.tar.gz)
2. bin/pulsar initialize-cluster-metadata --cluster test --zookeeper 10.176.5.177:2181/test --configuration-store 10.176.5.177:2181 /test --web-service-url http://10.176.5.177:8080 --broker-service-url pulsar://10.176.5.177:6650
3. run bookie(bin/pulsar-daemon start bookie)
4. run broker(bin/pulsar-daemon start broker)
5. run sql-worker(bin/pulsar sql-worker run)
6. send some message to topic test9
7. run sql client(bin/pulsar sql)
8. 8.execute sql Query: select * from pulsar."public/default".test9;

Additional context
if i use 10.176.5.177:2181 as zookeeperServers in broker.conf and 10.176.5.177:2181 as zkServers in bookeeper.conf and 10.176.5.177:2181 as pulsar.zookeeper-uri in pulsar.properties, the above exception will not occur；i don't konw how to solve it;
it is very similar to https://github.com/apache/pulsar/issues/4715#issue-467310250

**Comment by codelipenghui** [comment]
@sakurafly123 Seems related to https://github.com/apache/pulsar/issues/9818? I have left a comment here https://github.com/apache/pulsar/issues/9818#issuecomment-791382600

**Comment by sakurafly123** [comment]
> @sakurafly123 Seems related to #9818? I have left a comment here [#9818 (comment)](https://github.com/apache/pulsar/issues/9818#issuecomment-791382600)

yes ,i see it; now I give the complete configuration；

**Comment by sakurafly123** [comment]
> @sakurafly123 Seems related to #9818? I have left a comment here [#9818 (comment)](https://github.com/apache/pulsar/issues/9818#issuecomment-791382600)

i think there‘re a problem on  PulsarConnectorCache.java row115;
it may be replaced by  "
 return new ManagedLedgerFactoryImpl(bkClientConfiguration,managedLedgerFactoryConfig,bkClientConfiguration.getMetadataServiceUri());
"

**Comment by codelipenghui** [comment]
Oh, I see. The problem is related to the chroot of the zk connection string. Are you interested in fixing this problem?

**Comment by sakurafly123** [comment]
yes,i

> Oh, I see. The problem is related to the chroot of the zk connection string. Are you interested in fixing this problem?

ok,i can try to fix this problem
