### ISSUE TITLE
No factory for connector 'memory'

### ISSUE THREAD

**Issue by pointearth** [apache/pulsar#9909]
**Describe the bug**
I added a memory database connector config file memory.properties in conf/presto/catolog/ , 
https://trino.io/docs/current/connector/memory.html

`connector.name=memory`
`memory.max-data-per-node=128MB`

when I start the presto worker to run "./bin/pulsar sql-worker run", i get:

java.lang.IllegalArgumentException: No factory for connector 'memory'.  Available factories: [system, pulsar]
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:441)
	at io.prestosql.connector.ConnectorManager.createCatalog(ConnectorManager.java:185)
	at io.prestosql.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:88)
	at io.prestosql.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
	at io.prestosql.server.PrestoServer.run(PrestoServer.java:118)
	at io.prestosql.$gen.Presto_332____20210315_171503_1.run(Unknown Source)
	at io.prestosql.server.PrestoServer.main(PrestoServer.java:72)

Does any one can tell me the reason?

**Expected behavior**
sql worker started.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
just like https://github.com/prestodb/presto/issues/6134

@codelipenghui  @sijie Would you help to see it?

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.

We've recently upgrade to trino 363 and align all features with that version.
