### ISSUE TITLE
Flaky-test: ClientTestBase.resetCursorCompatibility / ClientTest2_x.testResetCursorCompatibility

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#9914]
ClientTestBase.resetCursorCompatibility is flaky. This is called from ClientTest2_2.testResetCursorCompatibility , ClientTest2_3.testResetCursorCompatibility , ClientTest2_4.testResetCursorCompatibility and ClientTest2_5.testResetCursorCompatibility. 

Flaky-test: org.apache.pulsar.tests.integration.backwardscompatibility.ClientTest2_2.testResetCursorCompatibility
Number of failures: 8

org.apache.pulsar.tests.integration.backwardscompatibility.ClientTest2_2 is flaky. The testResetCursorCompatibility test method fails sporadically.

```
org.apache.pulsar.client.api.PulsarClientException$ConsumerBusyException: Exclusive consumer is already connected
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:991)
	at org.apache.pulsar.client.impl.ConsumerBuilderImpl.subscribe(ConsumerBuilderImpl.java:102)
	at org.apache.pulsar.tests.integration.topologies.ClientTestBase.resetCursorCompatibility(ClientTestBase.java:70)
	at org.apache.pulsar.tests.integration.backwardscompatibility.ClientTest2_2.testResetCursorCompatibility(ClientTest2_2.java:32)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-03-09T01:33:10.0330850Z](https://github.com/apache/pulsar/runs/2061635785?check_suite_focus=true#step:12:5653)
[example failure 2021-03-08T04:12:00.1896049Z](https://github.com/apache/pulsar/runs/2053321076?check_suite_focus=true#step:12:5952)
[example failure 2021-03-05T09:34:04.7206126Z](https://github.com/apache/pulsar/runs/2037974037?check_suite_focus=true#step:12:5952)
[example failure 2021-03-02T23:22:49.9737794Z](https://github.com/apache/pulsar/runs/2016489765?check_suite_focus=true#step:12:6259)
[example failure 2021-03-02T10:16:42.4481903Z](https://github.com/apache/pulsar/runs/2011364844?check_suite_focus=true#step:12:11997)
[example failure 2021-03-02T02:42:12.3399984Z](https://github.com/apache/pulsar/runs/2009352852?check_suite_focus=true#step:12:5969)
[example failure 2021-02-24T15:40:54.2540159Z](https://github.com/apache/pulsar/runs/1969392699?check_suite_focus=true#step:12:5802)
[example failure 2021-02-23T19:56:04.6372777Z](https://github.com/apache/pulsar/runs/1961604069?check_suite_focus=true#step:12:11383)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
org.apache.pulsar.client.api.PulsarClientException$ConsumerBusyException: Exclusive consumer is already connected
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:991)
	at org.apache.pulsar.client.impl.ConsumerBuilderImpl.subscribe(ConsumerBuilderImpl.java:102)
	at org.apache.pulsar.tests.integration.topologies.ClientTestBase.resetCursorCompatibility(ClientTestBase.java:70)
	at org.apache.pulsar.tests.integration.backwardscompatibility.ClientTest2_2.testResetCursorCompatibility(ClientTest2_2.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

</pre></code>
</details>

        
Flaky-test: org.apache.pulsar.tests.integration.backwardscompatibility.ClientTest2_3.testResetCursorCompatibility
Number of failures: 11

org.apache.pulsar.tests.integration.backwardscompatibility.ClientTest2_3 is flaky. The testResetCursorCompatibility test method fails sporadically.

```
org.apache.pulsar.client.api.PulsarClientException$ConsumerBusyException: Exclusive consumer is already connected
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:991)
	at org.apache.pulsar.client.impl.ConsumerBuilderImpl.subscribe(ConsumerBuilderImpl.java:102)
	at org.apache.pulsar.tests.integration.topologies.ClientTestBase.resetCursorCompatibility(ClientTestBase.java:70)
	at org.apache.pulsar.tests.integration.backwardscompatibility.ClientTest2_3.testResetCursorCompatibility(ClientTest2_3.java:32)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-03-12T08:02:46.6994946Z](https://github.com/apache/pulsar/runs/2092902732?check_suite_focus=true#step:12:11952)
[example failure 2021-03-12T02:53:10.2319388Z](https://github.com/apache/pulsar/runs/2091552281?check_suite_focus=true#step:12:5963)
[example failure 2021-03-10T09:51:49.8640172Z](https://github.com/apache/pulsar/runs/2074896441?check_suite_focus=true#step:12:5963)
[example failure 2021-03-08T16:00:10.2591656Z](https://github.com/apache/pulsar/runs/2056011375?check_suite_focus=true#step:12:17434)
[example failure 2021-03-08T15:56:27.4725738Z](https://github.com/apache/pulsar/runs/2056011375?check_suite_focus=true#step:12:11718)
[example failure 2021-03-08T15:52:47.7052248Z](https://github.com/apache/pulsar/runs/2056011375?check_suite_focus=true#step:12:6258)
[example failure 2021-03-05T09:34:04.7362655Z](https://github.com/apache/pulsar/runs/2037974037?check_suite_focus=true#step:12:5971)
[example failure 2021-02-23T21:52:09.1996484Z](https://github.com/apache/pulsar/runs/1963498195?check_suite_focus=true#step:12:5826)
[example failure 2021-02-23T19:58:15.5462221Z](https://github.com/apache/pulsar/runs/1961604069?check_suite_focus=true#step:12:17263)
[example failure 2021-02-23T19:56:04.6500645Z](https://github.com/apache/pulsar/runs/1961604069?check_suite_focus=true#step:12:11402)
[example failure 2021-02-23T19:53:48.5170057Z](https://github.com/apache/pulsar/runs/1961604069?check_suite_focus=true#step:12:5529)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
org.apache.pulsar.client.api.PulsarClientException$ConsumerBusyException: Exclusive consumer is already connected
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:991)
	at org.apache.pulsar.client.impl.ConsumerBuilderImpl.subscribe(ConsumerBuilderImpl.java:102)
	at org.apache.pulsar.tests.integration.topologies.ClientTestBase.resetCursorCompatibility(ClientTestBase.java:70)
	at org.apache.pulsar.tests.integration.backwardscompatibility.ClientTest2_3.testResetCursorCompatibility(ClientTest2_3.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

</pre></code>
</details>

        
Flaky-test: org.apache.pulsar.tests.integration.backwardscompatibility.ClientTest2_4.testResetCursorCompatibility
Number of failures: 27

org.apache.pulsar.tests.integration.backwardscompatibility.ClientTest2_4 is flaky. The testResetCursorCompatibility test method fails sporadically.

```
org.apache.pulsar.client.api.PulsarClientException$ConsumerBusyException: Exclusive consumer is already connected
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:991)
	at org.apache.pulsar.client.impl.ConsumerBuilderImpl.subscribe(ConsumerBuilderImpl.java:102)
	at org.apache.pulsar.tests.integration.topologies.ClientTestBase.resetCursorCompatibility(ClientTestBase.java:70)
	at org.apache.pulsar.tests.integration.backwardscompatibility.ClientTest2_4.testResetCursorCompatibility(ClientTest2_4.java:32)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-03-14T18:45:05.3800257Z](https://github.com/apache/pulsar/runs/2107464330?check_suite_focus=true#step:13:5875)
[example failure 2021-03-12T07:59:38.8991687Z](https://github.com/apache/pulsar/runs/2092902732?check_suite_focus=true#step:12:5954)
[example failure 2021-03-12T02:59:41.7888504Z](https://github.com/apache/pulsar/runs/2091552281?check_suite_focus=true#step:12:17696)
[example failure 2021-03-12T02:53:10.2368670Z](https://github.com/apache/pulsar/runs/2091552281?check_suite_focus=true#step:12:5982)
[example failure 2021-03-11T15:36:49.6970180Z](https://github.com/apache/pulsar/runs/2086848074?check_suite_focus=true#step:12:5868)
[example failure 2021-03-11T06:00:57.5013087Z](https://github.com/apache/pulsar/runs/2083382065?check_suite_focus=true#step:12:5662)
[example failure 2021-03-10T22:08:30.6044944Z](https://github.com/apache/pulsar/runs/2080868696?check_suite_focus=true#step:12:17355)
[example failure 2021-03-10T18:56:44.6163596Z](https://github.com/apache/pulsar/runs/2078689521?check_suite_focus=true#step:12:17375)
[example failure 2021-03-10T18:50:02.5989395Z](https://github.com/apache/pulsar/runs/2078689521?check_suite_focus=true#step:12:5370)
[example failure 2021-03-10T17:50:10.4757205Z](https://github.com/apache/pulsar/runs/2078510309?check_suite_focus=true#step:12:11977)
[example failure 2021-03-10T17:47:01.9440270Z](https://github.com/apache/pulsar/runs/2078510309?check_suite_focus=true#step:12:5958)
[example failure 2021-03-10T07:45:47.2540459Z](https://github.com/apache/pulsar/runs/2074335098?check_suite_focus=true#step:12:17939)
[example failure 2021-03-10T07:39:29.1682563Z](https://github.com/apache/pulsar/runs/2074335098?check_suite_focus=true#step:12:5653)
[example failure 2021-03-09T01:39:33.3837030Z](https://github.com/apache/pulsar/runs/2061635785?check_suite_focus=true#step:12:17687)
[example failure 2021-03-09T00:58:46.1663171Z](https://github.com/apache/pulsar/runs/2061480067?check_suite_focus=true#step:12:11657)
[example failure 2021-03-08T15:52:47.7269720Z](https://github.com/apache/pulsar/runs/2056011375?check_suite_focus=true#step:12:6277)
[example failure 2021-03-08T12:21:29.8162753Z](https://github.com/apache/pulsar/runs/2055348208?check_suite_focus=true#step:12:5958)
[example failure 2021-03-08T07:58:26.9898720Z](https://github.com/apache/pulsar/runs/2054159098?check_suite_focus=true#step:12:12271)
[example failure 2021-03-08T07:55:06.9242839Z](https://github.com/apache/pulsar/runs/2054159098?check_suite_focus=true#step:12:5951)
[example failure 2021-03-07T10:23:23.3822635Z](https://github.com/apache/pulsar/runs/2049868221?check_suite_focus=true#step:12:5944)
[example failure 2021-03-06T12:54:03.8249913Z](https://github.com/apache/pulsar/runs/2046085955?check_suite_focus=true#step:12:17054)
[example failure 2021-03-06T12:47:49.8284928Z](https://github.com/apache/pulsar/runs/2046085955?check_suite_focus=true#step:12:5362)
[example failure 2021-03-05T19:06:45.3731411Z](https://github.com/apache/pulsar/runs/2041951998?check_suite_focus=true#step:12:5963)
[example failure 2021-03-02T23:29:19.4712494Z](https://github.com/apache/pulsar/runs/2016489765?check_suite_focus=true#step:12:18881)
[example failure 2021-03-02T10:13:32.4748215Z](https://github.com/apache/pulsar/runs/2011364844?check_suite_focus=true#step:12:6270)
[example failure 2021-03-02T02:42:12.3542141Z](https://github.com/apache/pulsar/runs/2009352852?check_suite_focus=true#step:12:5988)
[example failure 2021-02-23T21:52:09.2079955Z](https://github.com/apache/pulsar/runs/1963498195?check_suite_focus=true#step:12:5845)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
org.apache.pulsar.client.api.PulsarClientException$ConsumerBusyException: Exclusive consumer is already connected
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:991)
	at org.apache.pulsar.client.impl.ConsumerBuilderImpl.subscribe(ConsumerBuilderImpl.java:102)
	at org.apache.pulsar.tests.integration.topologies.ClientTestBase.resetCursorCompatibility(ClientTestBase.java:70)
	at org.apache.pulsar.tests.integration.backwardscompatibility.ClientTest2_4.testResetCursorCompatibility(ClientTest2_4.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

</pre></code>
</details>

        
Flaky-test: org.apache.pulsar.tests.integration.backwardscompatibility.ClientTest2_5.testResetCursorCompatibility
Number of failures: 43

org.apache.pulsar.tests.integration.backwardscompatibility.ClientTest2_5 is flaky. The testResetCursorCompatibility test method fails sporadically.

```
org.apache.pulsar.client.api.PulsarClientException$ConsumerBusyException: Exclusive consumer is already connected
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:991)
	at org.apache.pulsar.client.impl.ConsumerBuilderImpl.subscribe(ConsumerBuilderImpl.java:102)
	at org.apache.pulsar.tests.integration.topologies.ClientTestBase.resetCursorCompatibility(ClientTestBase.java:70)
	at org.apache.pulsar.tests.integration.backwardscompatibility.ClientTest2_5.testResetCursorCompatibility(ClientTest2_5.java:32)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-03-14T18:51:25.1804480Z](https://github.com/apache/pulsar/runs/2107464330?check_suite_focus=true#step:13:17983)
[example failure 2021-03-14T18:48:15.1274946Z](https://github.com/apache/pulsar/runs/2107464330?check_suite_focus=true#step:13:12077)
[example failure 2021-03-14T06:49:50.6909758Z](https://github.com/apache/pulsar/runs/2105295630?check_suite_focus=true#step:13:5571)
[example failure 2021-03-13T04:32:48.0071490Z](https://github.com/apache/pulsar/runs/2100541288?check_suite_focus=true#step:13:5280)
[example failure 2021-03-12T08:02:46.7139526Z](https://github.com/apache/pulsar/runs/2092902732?check_suite_focus=true#step:12:11971)
[example failure 2021-03-12T03:22:38.9521857Z](https://github.com/apache/pulsar/runs/2091671292?check_suite_focus=true#step:12:5655)
[example failure 2021-03-12T02:56:27.1324788Z](https://github.com/apache/pulsar/runs/2091552281?check_suite_focus=true#step:12:11692)
[example failure 2021-03-11T20:27:30.6939080Z](https://github.com/apache/pulsar/runs/2089064573?check_suite_focus=true#step:12:5959)
[example failure 2021-03-11T06:04:04.5519381Z](https://github.com/apache/pulsar/runs/2083382065?check_suite_focus=true#step:12:11658)
[example failure 2021-03-10T22:05:27.7902844Z](https://github.com/apache/pulsar/runs/2080868696?check_suite_focus=true#step:12:11659)
[example failure 2021-03-10T22:02:21.1066483Z](https://github.com/apache/pulsar/runs/2080868696?check_suite_focus=true#step:12:5657)
[example failure 2021-03-10T19:43:07.8590797Z](https://github.com/apache/pulsar/runs/2079121835?check_suite_focus=true#step:12:5649)
[example failure 2021-03-10T19:29:07.7943912Z](https://github.com/apache/pulsar/runs/2078879802?check_suite_focus=true#step:12:11669)
[example failure 2021-03-10T19:25:53.9959676Z](https://github.com/apache/pulsar/runs/2078879802?check_suite_focus=true#step:12:6260)
[example failure 2021-03-10T18:53:23.1912395Z](https://github.com/apache/pulsar/runs/2078689521?check_suite_focus=true#step:12:11078)
[example failure 2021-03-10T18:31:26.6835653Z](https://github.com/apache/pulsar/runs/2078627600?check_suite_focus=true#step:12:11668)
[example failure 2021-03-10T18:28:09.2902860Z](https://github.com/apache/pulsar/runs/2078627600?check_suite_focus=true#step:12:5956)
[example failure 2021-03-10T17:47:01.9485223Z](https://github.com/apache/pulsar/runs/2078510309?check_suite_focus=true#step:12:5977)
[example failure 2021-03-10T16:01:54.5068965Z](https://github.com/apache/pulsar/runs/2077869446?check_suite_focus=true#step:12:16763)
[example failure 2021-03-10T15:58:52.1436976Z](https://github.com/apache/pulsar/runs/2077869446?check_suite_focus=true#step:12:11355)
[example failure 2021-03-10T15:55:47.6953787Z](https://github.com/apache/pulsar/runs/2077869446?check_suite_focus=true#step:12:5659)
[example failure 2021-03-10T10:24:29.1640302Z](https://github.com/apache/pulsar/runs/2075280398?check_suite_focus=true#step:12:5859)
[example failure 2021-03-10T07:45:47.2662979Z](https://github.com/apache/pulsar/runs/2074335098?check_suite_focus=true#step:12:17958)
[example failure 2021-03-10T07:42:35.6275597Z](https://github.com/apache/pulsar/runs/2074335098?check_suite_focus=true#step:12:11648)
[example failure 2021-03-09T01:36:21.1767607Z](https://github.com/apache/pulsar/runs/2061635785?check_suite_focus=true#step:12:11384)
[example failure 2021-03-09T01:33:10.0489899Z](https://github.com/apache/pulsar/runs/2061635785?check_suite_focus=true#step:12:5672)
[example failure 2021-03-09T01:02:37.8873274Z](https://github.com/apache/pulsar/runs/2061483501?check_suite_focus=true#step:12:5663)
[example failure 2021-03-09T00:55:36.8050637Z](https://github.com/apache/pulsar/runs/2061480067?check_suite_focus=true#step:12:5952)
[example failure 2021-03-08T16:00:10.2727332Z](https://github.com/apache/pulsar/runs/2056011375?check_suite_focus=true#step:12:17453)
[example failure 2021-03-08T15:52:47.7321620Z](https://github.com/apache/pulsar/runs/2056011375?check_suite_focus=true#step:12:6296)
[example failure 2021-03-08T12:21:29.8280820Z](https://github.com/apache/pulsar/runs/2055348208?check_suite_focus=true#step:12:5977)
[example failure 2021-03-08T07:58:26.9985125Z](https://github.com/apache/pulsar/runs/2054159098?check_suite_focus=true#step:12:12290)
[example failure 2021-03-08T07:55:06.9401865Z](https://github.com/apache/pulsar/runs/2054159098?check_suite_focus=true#step:12:5970)
[example failure 2021-03-08T04:12:00.2003970Z](https://github.com/apache/pulsar/runs/2053321076?check_suite_focus=true#step:12:5971)
[example failure 2021-03-07T10:26:24.0212835Z](https://github.com/apache/pulsar/runs/2049868221?check_suite_focus=true#step:12:11647)
[example failure 2021-03-06T12:50:57.7003277Z](https://github.com/apache/pulsar/runs/2046085955?check_suite_focus=true#step:12:11059)
[example failure 2021-03-05T19:06:45.3823961Z](https://github.com/apache/pulsar/runs/2041951998?check_suite_focus=true#step:12:5982)
[example failure 2021-03-04T01:56:33.7271164Z](https://github.com/apache/pulsar/runs/2027058096?check_suite_focus=true#step:12:5958)
[example failure 2021-03-02T23:29:19.4900060Z](https://github.com/apache/pulsar/runs/2016489765?check_suite_focus=true#step:12:18900)
[example failure 2021-03-02T23:26:06.1337535Z](https://github.com/apache/pulsar/runs/2016489765?check_suite_focus=true#step:12:12581)
[example failure 2021-03-02T23:22:49.9856576Z](https://github.com/apache/pulsar/runs/2016489765?check_suite_focus=true#step:12:6278)
[example failure 2021-03-02T10:16:42.4579640Z](https://github.com/apache/pulsar/runs/2011364844?check_suite_focus=true#step:12:12016)
[example failure 2021-03-02T10:13:32.4853469Z](https://github.com/apache/pulsar/runs/2011364844?check_suite_focus=true#step:12:6289)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
org.apache.pulsar.client.api.PulsarClientException$ConsumerBusyException: Exclusive consumer is already connected
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:991)
	at org.apache.pulsar.client.impl.ConsumerBuilderImpl.subscribe(ConsumerBuilderImpl.java:102)
	at org.apache.pulsar.tests.integration.topologies.ClientTestBase.resetCursorCompatibility(ClientTestBase.java:70)
	at org.apache.pulsar.tests.integration.backwardscompatibility.ClientTest2_5.testResetCursorCompatibility(ClientTest2_5.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

</pre></code>
</details>

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
