### ISSUE TITLE
Flaky-test: DeadLetterTopicTest.testDeadLetterTopic

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#9916]
Flaky-test: org.apache.pulsar.client.api.DeadLetterTopicTest.testDeadLetterTopic
Number of failures: 20

org.apache.pulsar.client.api.DeadLetterTopicTest is flaky. The testDeadLetterTopic test method fails sporadically.

```
java.lang.AssertionError: expected [null] but found [org.apache.pulsar.client.impl.MessageImpl@151b99cf]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotSame(Assert.java:1033)
	at org.testng.Assert.assertNull(Assert.java:965)
	at org.testng.Assert.assertNull(Assert.java:953)
	at org.apache.pulsar.client.api.DeadLetterTopicTest.testDeadLetterTopic(DeadLetterTopicTest.java:124)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-03-10T21:36:48.2364681Z](https://github.com/apache/pulsar/runs/2080868725?check_suite_focus=true#step:8:336)
[example failure 2021-03-15T15:38:25.7377495Z](https://github.com/apache/pulsar/runs/2113745144?check_suite_focus=true#step:9:548)
[example failure 2021-03-12T01:03:28.7485909Z](https://github.com/apache/pulsar/runs/2091179719?check_suite_focus=true#step:8:336)
[example failure 2021-02-26T21:40:51.3841331Z](https://github.com/apache/pulsar/runs/1990688155?check_suite_focus=true#step:8:903)
[example failure 2021-03-10T15:26:59.3094996Z](https://github.com/apache/pulsar/runs/2077869103?check_suite_focus=true#step:8:336)
[example failure 2021-03-11T11:35:33.6131220Z](https://github.com/apache/pulsar/runs/2084704409?check_suite_focus=true#step:8:762)
[example failure 2021-03-11T11:23:56.2390495Z](https://github.com/apache/pulsar/runs/2084704409?check_suite_focus=true#step:8:549)
[example failure 2021-03-08T00:39:47.2234098Z](https://github.com/apache/pulsar/runs/2052659416?check_suite_focus=true#step:8:493)
[example failure 2021-03-11T11:12:15.4495348Z](https://github.com/apache/pulsar/runs/2084704409?check_suite_focus=true#step:8:336)
[example failure 2021-02-27T07:05:57.1162853Z](https://github.com/apache/pulsar/runs/1992797093?check_suite_focus=true#step:8:1301)
[example failure 2021-03-09T02:10:02.7834249Z](https://github.com/apache/pulsar/runs/2062060420?check_suite_focus=true#step:8:336)
[example failure 2021-03-10T15:39:08.1125019Z](https://github.com/apache/pulsar/runs/2077869103?check_suite_focus=true#step:8:549)
[example failure 2021-03-07T09:48:29.6697086Z](https://github.com/apache/pulsar/runs/2049868081?check_suite_focus=true#step:8:493)
[example failure 2021-03-03T21:36:00.2774777Z](https://github.com/apache/pulsar/runs/2025524293?check_suite_focus=true#step:8:493)
[example failure 2021-03-09T15:52:33.5570341Z](https://github.com/apache/pulsar/runs/2067697760?check_suite_focus=true#step:8:336)
[example failure 2021-03-13T04:18:16.5544068Z](https://github.com/apache/pulsar/runs/2100541222?check_suite_focus=true#step:9:572)
[example failure 2021-03-09T16:03:43.0219246Z](https://github.com/apache/pulsar/runs/2067697760?check_suite_focus=true#step:8:549)
[example failure 2021-03-08T01:01:26.6950037Z](https://github.com/apache/pulsar/runs/2052659416?check_suite_focus=true#step:8:1358)
[example failure 2021-03-14T06:24:52.5153419Z](https://github.com/apache/pulsar/runs/2105295699?check_suite_focus=true#step:9:336)
[example failure 2021-03-11T14:34:28.9441969Z](https://github.com/apache/pulsar/runs/2086717463?check_suite_focus=true#step:8:359)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
java.lang.AssertionError: expected [null] but found [org.apache.pulsar.client.impl.MessageImpl@151b99cf]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotSame(Assert.java:1033)
	at org.testng.Assert.assertNull(Assert.java:965)
	at org.testng.Assert.assertNull(Assert.java:953)
	at org.apache.pulsar.client.api.DeadLetterTopicTest.testDeadLetterTopic(DeadLetterTopicTest.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

</pre></code>
</details>

Flaky-test: org.apache.pulsar.client.api.DeadLetterTopicTest.testDeadLetterTopicByCustomTopicName
Number of failures: 8

org.apache.pulsar.client.api.DeadLetterTopicTest is flaky. The testDeadLetterTopicByCustomTopicName test method fails sporadically.

```
java.lang.AssertionError: expected [null] but found [org.apache.pulsar.client.impl.MessageImpl@4490d295]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotSame(Assert.java:1033)
	at org.testng.Assert.assertNull(Assert.java:965)
	at org.testng.Assert.assertNull(Assert.java:953)
	at org.apache.pulsar.client.api.DeadLetterTopicTest.testDeadLetterTopicByCustomTopicName(DeadLetterTopicTest.java:397)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-03-08T00:50:56.6220381Z](https://github.com/apache/pulsar/runs/2052659416?check_suite_focus=true#step:8:893)
[example failure 2021-03-06T02:41:58.7663850Z](https://github.com/apache/pulsar/runs/2044414838?check_suite_focus=true#step:8:493)
[example failure 2021-03-16T00:25:57.4946126Z](https://github.com/apache/pulsar/runs/2117276271?check_suite_focus=true#step:9:565)
[example failure 2021-03-15T15:47:58.3723431Z](https://github.com/apache/pulsar/runs/2113745144?check_suite_focus=true#step:9:757)
[example failure 2021-02-26T21:53:13.5461069Z](https://github.com/apache/pulsar/runs/1990688155?check_suite_focus=true#step:8:1320)
[example failure 2021-03-11T17:33:24.1271868Z](https://github.com/apache/pulsar/runs/2088218128?check_suite_focus=true#step:9:336)
[example failure 2021-03-09T02:10:02.8676980Z](https://github.com/apache/pulsar/runs/2062060420?check_suite_focus=true#step:8:356)
[example failure 2021-03-10T17:22:30.4745269Z](https://github.com/apache/pulsar/runs/2078510525?check_suite_focus=true#step:8:336)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
java.lang.AssertionError: expected [null] but found [org.apache.pulsar.client.impl.MessageImpl@4490d295]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotSame(Assert.java:1033)
	at org.testng.Assert.assertNull(Assert.java:965)
	at org.testng.Assert.assertNull(Assert.java:953)
	at org.apache.pulsar.client.api.DeadLetterTopicTest.testDeadLetterTopicByCustomTopicName(DeadLetterTopicTest.java:397)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

</pre></code>
</details>

**Comment by lhotari** [comment]
I tried to reproduce this locally on latest master branch, but didn't get the test to fail. If someone is able to reproduce, please comment here.

**Comment by michaeljmarshall** [comment]
I made some solid progress running through this test with a debugger. It does indeed look like there is a race condition based on the design of the test and the way that we send messages to dead letter queues. Essentially, we send a message to a DLQ before we acknowledge it on the original topic. Combine that with the fact that when a consumer client is closed, it releases all unacknowledged messages to any other consumers, and you get the flaky test that results from a race condition.

At this point, I have clearly identified why we have a flaky test, but I haven't determined the right solution (change the test or change the source). I will spend more time thinking about this and either post with follow up questions and/or options or submit a PR. Fundamentally, I don't think this test should be too hard to fix.

I need to sign off for the night, but I am very interested in solving this one. I should be able to get more time with it tomorrow or this weekend.

**Comment by michaeljmarshall** [comment]
Quick note: it does seem rather intentional that we send to the DLQ first and only acknowledge the message on the original topic upon successful delivery to the DLQ. This ordering is essential to our DLQ delivery semantics. If we switched the order, we'd end up with an at most once delivery to the DLQ, which seems undesirable to me and like a breaking change from the current behavior.

I have a few potential solutions that I need to spend a little more time thinking through. I'll post an update tomorrow.

**Comment by lhotari** [comment]
Thanks for putting effort into fixing this @michaeljmarshall . Fixing this test seems pretty challenging. If there are obstacles that are hard to overcome, perhaps there's a way to simplify the test.

One thing that I've noticed before with testing DLQ behavior is that disabling batching in the producer is necessary to get consistent behavior. That's one thing to try out when fixing this one.

**Comment by michaeljmarshall** [comment]
> Fixing this test seems pretty challenging. If there are obstacles that are hard to overcome, perhaps there's a way to simplify the test.

I agree this test is a bit complicated, but annotating the test should help to discuss the behavior that I believe is leading to test flakiness. Because there are no timeouts in the test, I only see one place for a race condition, and I'm able to consistently get failures by adding a `sleep` in one key location.

## Annotated Test

In the following code block, we create a normal consumer, a DLQ consumer, and a producer. We then produce `sendMessages` to the `topic`. This all appears deterministic to me.

```java
    public void testDeadLetterTopic() throws Exception {
        final String topic = "persistent://my-property/my-ns/dead-letter-topic";

        final int maxRedeliveryCount = 3;

        final int sendMessages = 100;

        Consumer<byte[]> consumer = pulsarClient.newConsumer(Schema.BYTES)
                .topic(topic)
                .subscriptionName("my-subscription")
                .subscriptionType(SubscriptionType.Shared)
                .ackTimeout(1, TimeUnit.SECONDS)
                .deadLetterPolicy(DeadLetterPolicy.builder().maxRedeliverCount(maxRedeliveryCount).build())
                .receiverQueueSize(100)
                .subscriptionInitialPosition(SubscriptionInitialPosition.Earliest)
                .subscribe();

        PulsarClient newPulsarClient = newPulsarClient(lookupUrl.toString(), 0);// Creates new client connection
        Consumer<byte[]> deadLetterConsumer = newPulsarClient.newConsumer(Schema.BYTES)
                .topic("persistent://my-property/my-ns/dead-letter-topic-my-subscription-DLQ")
                .subscriptionName("my-subscription")
                .subscriptionInitialPosition(SubscriptionInitialPosition.Earliest)
                .subscribe();

        Producer<byte[]> producer = pulsarClient.newProducer(Schema.BYTES)
                .topic(topic)
                .create();

        for (int i = 0; i < sendMessages; i++) {
            producer.send(String.format("Hello Pulsar [%d]", i).getBytes());
        }

        producer.close();
```

After running the above, we have a topic with 100 messages. The while loop will complete when we have completed 300 loops (100 * (2 + 1)). We start the while loop by consuming from the topic with the basic consumer. We consume 100 messages very quickly, and then wait 1 second for each of them to timeout because we haven't ack'ed any of them. We consume 100 messages again, then wait 1 second again. We do it a third time, which is when the `while` clause is false and we move on to the next block (before the messages time out from not being ack'ed).

```java
        int totalReceived = 0;
        do {
            Message<byte[]> message = consumer.receive();
            log.info("consumer received message : {} - {}", message.getMessageId(), new String(message.getData()));
            totalReceived++;
        } while (totalReceived < sendMessages * (maxRedeliveryCount + 1));
```

Up to this point, all of the behavior is deterministic as far as message delivery and acking. Even if the redeliveries are delayed, the code waits indefinitely until the messages are delivered. 

The next code block waits 1 second at `deadLetterConsumer.receive()` because that consumer is looking for messages on the DLQ topic, and messages aren't produced to the topic until they timeout from not being ack'ed. We then consume all 100 messages from the DLQ topic.

This is the where we find the race condition. The redelivery logic lives in the client. The client produces each expired message to the DLQ topic and when that call completes, the client sends acks to the source topic for each message. Given that order, the `deadLetterConsumer` could consume messages from the DLQ topic before they are removed (ack'ed) from the source topic.

We then close the clients. If a client is closed before the call to ack the messages, the ack calls will fail. Closing the client does not include any type of wait to give a best effort at delivering those acks.

```java
        int totalInDeadLetter = 0;
        do {
            Message message = deadLetterConsumer.receive();
            log.info("dead letter consumer received message : {} {}", message.getMessageId(), new String(message.getData()));
            deadLetterConsumer.acknowledge(message);
            totalInDeadLetter++;
        } while (totalInDeadLetter < sendMessages);

        deadLetterConsumer.close();
        consumer.close();
```

Next, we create a consumer to consume from the source topic to see if any messages are on it. If any messages are there, we fail the test (this is exactly what we've been seeing in the above failures).

```java
        Consumer<byte[]> checkConsumer = this.pulsarClient.newConsumer(Schema.BYTES)
                .topic(topic)
                .subscriptionName("my-subscription")
                .subscriptionType(SubscriptionType.Shared)
                .subscriptionInitialPosition(SubscriptionInitialPosition.Earliest)
                .subscribe();

        Message<byte[]> checkMessage = checkConsumer.receive(3, TimeUnit.SECONDS);
        if (checkMessage != null) {
            log.info("check consumer received message : {} - {}", checkMessage.getMessageId(), new String(checkMessage.getData()));
        }
        assertNull(checkMessage);

        checkConsumer.close();
        newPulsarClient.close();
```

## Thread Sleep And Reproducing Failure

To further prove this point, I added a `Thread.sleep(1000);` to the line immediately before the following:

https://github.com/apache/pulsar/blob/a8b921cf15c0a0f652f1d9f62a6481efea243881/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L1687

And it results in the test consistently failing with the following log line in the test logs:

```
23:24:11.934 [pulsar-client-io-38-1] WARN  org.apache.pulsar.client.impl.ConsumerImpl - [persistent://my-property/my-ns/dead-letter-topic] [my-subscription] [3e1bb] Failed to acknowledge the message 3:3:-1 of the original topic but send to the DLQ successfully.
org.apache.pulsar.client.api.PulsarClientException: Consumer not ready. State: Closing
	at org.apache.pulsar.client.impl.ConsumerImpl.doAcknowledge(ConsumerImpl.java:509) ~[classes/:?]
	at org.apache.pulsar.client.impl.ConsumerBase.doAcknowledgeWithTxn(ConsumerBase.java:506) ~[classes/:?]
	at org.apache.pulsar.client.impl.ConsumerBase.acknowledgeAsync(ConsumerBase.java:446) ~[classes/:?]
	at org.apache.pulsar.client.impl.ConsumerBase.acknowledgeAsync(ConsumerBase.java:435) ~[classes/:?]
	at org.apache.pulsar.client.impl.ConsumerImpl.lambda$processPossibleToDLQ$27(ConsumerImpl.java:1713) ~[classes/:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) [?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) [?:?]
	at org.apache.pulsar.client.impl.ProducerImpl$1.sendComplete(ProducerImpl.java:319) [classes/:?]
	at org.apache.pulsar.client.impl.ProducerImpl$OpSendMsg.sendComplete(ProducerImpl.java:1224) [classes/:?]
	at org.apache.pulsar.client.impl.ProducerImpl.ackReceived(ProducerImpl.java:991) [classes/:?]
	at org.apache.pulsar.client.impl.ClientCnx.handleSendReceipt(ClientCnx.java:402) [classes/:?]
	at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:220) [classes/:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-codec-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-codec-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.51.Final.jar:4.1.51.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

## Potential Solutions

I am still uncertain about how to best solve this test's flakiness. This test is a bit contrived, and the race condition is likely not one seen by end users. A few possible solutions:

1. Assuming the current design is what we want, find a way to improve the test.
2. Add logic to the pulsar client to ensure that when it is closed it waits (possibly with some configurable timeout) for these DLQ messages to be produced and ack'ed appropriately.
3. Look into the broker server's handling of these messages that have reached the maximum number of redeliveries.

I prefer the second option. The first option leaves the race condition in the client. The third is likely not easy because the server doesn't have the necessary information, and further, the current paradigm is that the redelivery logic lives in the client.

If there is agreement that the second solution is the right direction, I'm happy to look into implementing it.

**Comment by codelipenghui** [comment]
A quick fix is to close the consumer before ensuring the messages already get acked at the broker side? I think we can check the backlog by using the pulsar-admin?

**Comment by michaeljmarshall** [comment]
After looking at this a little more, I am wondering if it is inexpensive enough to use a transaction to produce to the DLQ topic and acknowledge the original message atomically. Then, the messages would not be end up available on both the source topic and the DLQ topic, as this test shows is currently possible.

> A quick fix is to close the consumer before ensuring the messages already get acked at the broker side?

@codelipenghui - I do not think this solution will work. When a consumer is closed, it drops any messages that are in the `possibleSendToDeadLetterTopicMessages` without moving them to the DLQ topic. That means the messages won't ever make it to the DLQ topic. As I mentioned in the annotations above, the DLQ topic consumer is the logic that waits 1 second for the original messages to time out and get delivered to the DLQ topic. All of the redelivery logic lives within the client, so closing it prematurely will lead to improper redelivery semantics.

I noticed while digging into this test that the `redeliveryCount` is not maintained from the first consumer to the second one. That seems unexpected to me, and I am wondering this is expected.

**Comment by codelipenghui** [comment]
@michaeljmarshall We can close the original consumer after check the DLQ has enough messages?

**Comment by michaeljmarshall** [comment]
> @michaeljmarshall We can close the original consumer after check the DLQ has enough messages?

That is essentially what we're currently doing in the test. We consume all of the messages from the DLQ and then close the two clients.

Regarding my earlier comment about using transactions, it looks like the transaction client isn't available in the consumer client class. I am going to look into delaying the closing of the client if there are outstanding messages to be ack'ed

**Comment by michaeljmarshall** [comment]
I took a look at updating the client so that when closeAsync is called, it waits for the DLQ steps to complete. It doesn't look like that would fit into the paradigm for how the client is currently closed.

I'm not sure about the right way to move forward here, but I'll keep thinking about it.

**Comment by michaeljmarshall** [comment]
I added this issue to the upcoming Pulsar Community meeting. There are a few design decisions I'd like to quickly talk through. Hopefully that will help identify a good solution to the existing race condition I exposed above.

**Comment by devinbost** [comment]
I just got this test in #10154 
The fundamental problem with this test (and many of the other Flaky tests) is that we are basing test logic on timing, which falls apart when the test runner non-deterministically encounters a "stop the world" garbage collection event (or some other kind of event that creates random delays) somewhere in the middle of that. If the test runner is very resource-constrained, those kinds of events will happen a lot as the JVM tries to free up resources. A large testbed that has lots of temporary one-time-use objects like Pulsar's is the perfect breeding ground for generating lots of dead objects that need to be garbage collected, resulting in long garbage collection times, further exasperating the issue.

Sharing resources between tests may help with that, but it's not a perfect solution because it would be impossible to completely eliminate garbage collection in the test runner.

**Comment by michaeljmarshall** [comment]
@devinbost - I agree that those conditions make these tests more likely to fail. This test is also problematic because the underlying dead letter logic has a data race that can lead to messages being read from both the DLQ topic and then from the source topic. Any chance that you looked up the logs before triggering another run of that test?

**Comment by devinbost** [comment]
I didn't see anything really useful in the logs, but perhaps this stack
trace will be of some value.

Errors: 0, Skipped: 2, Time elapsed: 66.568 s <<< FAILURE! - in
org.apache.pulsar.client.api.DeadLetterTopicTest
233Error:
testDeadLetterTopic(org.apache.pulsar.client.api.DeadLetterTopicTest) Time
elapsed: 6.148 s <<< FAILURE!
234java.lang.AssertionError: expected [null] but found
***@***.***
235 at org.testng.Assert.fail(Assert.java:99)
236 at org.testng.Assert.failNotSame(Assert.java:1033)
237 at org.testng.Assert.assertNull(Assert.java:965)
238 at org.testng.Assert.assertNull(Assert.java:953)
239 at
org.apache.pulsar.client.api.DeadLetterTopicTest.testDeadLetterTopic(DeadLetterTopicTest.java:125)
240 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
241 at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
242 at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
243 at java.lang.reflect.Method.invoke(Method.java:498)
244 at
org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
245 at
org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
246 at
org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
247 at
org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
248 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
249 at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
250 at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
251 at java.lang.Thread.run(Thread.java:748)
252

--
Devin G. Bost

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
