### ISSUE TITLE
Flaky-test: ManagedCursorMetricsTest.testManagedCursorMetrics

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#9919]
Flaky-test: org.apache.pulsar.broker.stats.ManagedCursorMetricsTest.testManagedCursorMetrics
Number of failures: 10

org.apache.pulsar.broker.stats.ManagedCursorMetricsTest is flaky. The testManagedCursorMetrics test method fails sporadically.

```
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertTrue(Assert.java:45)
	at org.testng.Assert.assertTrue(Assert.java:55)
	at org.apache.pulsar.broker.stats.ManagedCursorMetricsTest.testManagedCursorMetrics(ManagedCursorMetricsTest.java:70)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-03-08T17:30:26.3999781Z](https://github.com/apache/pulsar/runs/2056548871?check_suite_focus=true#step:8:190)
[example failure 2021-03-08T11:28:16.6508831Z](https://github.com/apache/pulsar/runs/2055117809?check_suite_focus=true#step:8:1036)
[example failure 2021-03-08T11:14:45.8989014Z](https://github.com/apache/pulsar/runs/2055117809?check_suite_focus=true#step:8:638)
[example failure 2021-03-05T21:58:01.2183193Z](https://github.com/apache/pulsar/runs/2043229259?check_suite_focus=true#step:8:190)
[example failure 2021-03-05T09:34:45.4232866Z](https://github.com/apache/pulsar/runs/2037997236?check_suite_focus=true#step:8:190)
[example failure 2021-03-05T09:22:25.4442285Z](https://github.com/apache/pulsar/runs/2037974738?check_suite_focus=true#step:8:1014)
[example failure 2021-03-05T09:10:53.5286506Z](https://github.com/apache/pulsar/runs/2037974738?check_suite_focus=true#step:8:614)
[example failure 2021-03-05T08:59:35.6870954Z](https://github.com/apache/pulsar/runs/2037974738?check_suite_focus=true#step:8:198)
[example failure 2021-03-04T06:23:51.0098464Z](https://github.com/apache/pulsar/runs/2028449927?check_suite_focus=true#step:8:688)
[example failure 2021-03-04T05:17:18.0634430Z](https://github.com/apache/pulsar/runs/2028174394?check_suite_focus=true#step:8:286)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertTrue(Assert.java:45)
	at org.testng.Assert.assertTrue(Assert.java:55)
	at org.apache.pulsar.broker.stats.ManagedCursorMetricsTest.testManagedCursorMetrics(ManagedCursorMetricsTest.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

</pre></code>
</details>

**Comment by lhotari** [comment]
@limingnihao ManagedCursorMetricsTest was introduced by #9618 and it seems to be flaky. Would you be able to take a look at this issue? Thank you

**Comment by lhotari** [comment]
recent failure: https://github.com/apache/pulsar/runs/4296627245?check_suite_focus=true#step:9:504

**Comment by lhotari** [comment]
recent failure: https://github.com/apache/pulsar/runs/4713066229?check_suite_focus=true#step:9:7671

**Comment by lhotari** [comment]
recent failure: https://github.com/apache/pulsar/runs/4863165088?check_suite_focus=true#step:9:430

**Comment by lhotari** [comment]
recent failure: https://github.com/apache/pulsar/runs/5008959840?check_suite_focus=true#step:9:645
```
Error:  testManagedCursorMetrics(org.apache.pulsar.broker.stats.ManagedCursorMetricsTest)  Time elapsed: 0.238 s  <<< FAILURE!
java.lang.AssertionError: did not expect [0] but found [0]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failEquals(Assert.java:1041)
	at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
	at org.testng.Assert.assertNotEquals(Assert.java:1531)
	at org.testng.Assert.assertNotEquals(Assert.java:1535)
	at org.apache.pulsar.broker.stats.ManagedCursorMetricsTest.testManagedCursorMetrics(ManagedCursorMetricsTest.java:89)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by lhotari** [comment]
recent failure: https://github.com/apache/pulsar/runs/5566227820?check_suite_focus=true#step:9:1975

**Comment by lhotari** [comment]
recent failure: https://github.com/apache/pulsar/runs/6092267620?check_suite_focus=true#step:11:967
