### ISSUE TITLE
Flaky-test: MultiTopicsConsumerImplTest.testConsumerCleanupOnSubscribeFailure

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#9920]
Flaky-test: org.apache.pulsar.client.impl.MultiTopicsConsumerImplTest.testConsumerCleanupOnSubscribeFailure
Number of failures: 9

org.apache.pulsar.client.impl.MultiTopicsConsumerImplTest is flaky. The testConsumerCleanupOnSubscribeFailure test method fails sporadically.

```
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertTrue(Assert.java:45)
	at org.testng.Assert.assertTrue(Assert.java:55)
	at org.apache.pulsar.client.impl.MultiTopicsConsumerImplTest.testConsumerCleanupOnSubscribeFailure(MultiTopicsConsumerImplTest.java:167)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-02-27T04:49:00.3581797Z](https://github.com/apache/pulsar/runs/1992516745?check_suite_focus=true#step:6:5154)
[example failure 2021-02-27T04:44:12.7215208Z](https://github.com/apache/pulsar/runs/1992516745?check_suite_focus=true#step:6:2426)
[example failure 2021-02-25T18:31:04.3371219Z](https://github.com/apache/pulsar/runs/1980632213?check_suite_focus=true#step:6:6134)
[example failure 2021-02-25T04:03:31.7937651Z](https://github.com/apache/pulsar/runs/1975757988?check_suite_focus=true#step:6:14661)
[example failure 2021-02-25T00:29:24.1708827Z](https://github.com/apache/pulsar/runs/1974695015?check_suite_focus=true#step:6:14664)
[example failure 2021-02-24T23:02:03.2989839Z](https://github.com/apache/pulsar/runs/1972988028?check_suite_focus=true#step:6:20374)
[example failure 2021-02-24T14:10:13.4008754Z](https://github.com/apache/pulsar/runs/1969282878?check_suite_focus=true#step:6:2426)
[example failure 2021-02-23T21:32:57.6043058Z](https://github.com/apache/pulsar/runs/1963498211?check_suite_focus=true#step:6:17371)
[example failure 2021-02-23T21:00:44.7134246Z](https://github.com/apache/pulsar/runs/1963498211?check_suite_focus=true#step:6:2444)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertTrue(Assert.java:45)
	at org.testng.Assert.assertTrue(Assert.java:55)
	at org.apache.pulsar.client.impl.MultiTopicsConsumerImplTest.testConsumerCleanupOnSubscribeFailure(MultiTopicsConsumerImplTest.java:167)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

</pre></code>
</details>

**Comment by lhotari** [comment]
already fixed by #9705 and there aren't any recent failures. Closing.
