### ISSUE TITLE
s/device/measurement

### ISSUE THREAD

**Issue by TIBCOeddie** [apache/pulsar#9939]
https://github.com/apache/pulsar/blob/94bf13f2f216c9f5d7ca00af31a5efaedde7e397/pulsar-io/influxdb/src/main/java/org/apache/pulsar/io/influxdb/v2/InfluxDBSink.java#L70

**Comment by tspannhw** [comment]
Hardcoded name.

org.apache.pulsar.client.api.SchemaSerializationException: device is a required field.
        at org.apache.pulsar.io.influxdb.v2.InfluxDBSink.buildPoint(InfluxDBSink.java:70) ~[H6kZDybItBmVXRzVBuylsA/:?]
        at org.apache.pulsar.io.influxdb.v2.InfluxDBSink.buildPoint(InfluxDBSink.java:41) ~[H6kZDybItBmVXRzVBuylsA/:?]
        at org.apache.pulsar.io.influxdb.BatchSink.flush(BatchSink.java:85) ~[H6kZDybItBmVXRzVBuylsA/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_312]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_312]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_312]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_312]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_312]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]

**Comment by tspannhw** [comment]
> https://github.com/apache/pulsar/blob/94bf13f2f216c9f5d7ca00af31a5efaedde7e397/pulsar-io/influxdb/src/main/java/org/apache/pulsar/io/influxdb/v2/InfluxDBSink.java#L70

This is related to the requirements for the InfluxDB v2 Line Protocol.   It requires a very specific format and fields.   You need to have a few minimum fields.    I have a Java example that works.

https://github.com/tspannhw/influx

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Fixed by https://github.com/apache/pulsar/pull/15416.
